v160
+ Tweaks: https://github.com/Fourdee/DietPi/issues/1311

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -198,6 +198,7 @@
 
 	#-----------------------------------------------------------------------------------
 	# DietPi Error Handler
+	# https://github.com/Fourdee/DietPi/issues/1311#issuecomment-353716344
 	#-----------------------------------------------------------------------------------
 	G_ERROR_HANDLER_EXITCODE=''					#input value to use with G_ERROR_HANDLER
 	G_ERROR_HANDLER_COMMAND=''					#eg: G_AGI: moooooooo
@@ -226,17 +227,16 @@
 
 	}
 
-	#Handles exit code errors, as defined by G_ERROR_HANDLER_xxxx settings, and last exit code of previous command
-	#	eg: 	mkdir /never/gonna/work
-	#			G_ERROR_HANDLER
+	#Handles exit code errors, as defined by G_ERROR_HANDLER_xxxx settings
+	#	Usage:
+	#		export G_ERROR_HANDLER_COMMAND='Doing something usefull with Owncloud'
+	#		export G_ERROR_HANDLER_ONERROR_EXIT=0 # Don't exit program on error, continue
+	#		export G_ERROR_HANDLER_ONERROR_FPLOGFILE=/var/log/mylogfile # to print if error occurs
+	#		export G_ERROR_HANDLER_ONERROR_USERMSG='Owncloud failed to pass a test, here is some info....' #optional user message if error occurs.
+	#		occ --doing-something-useful
+	#		export G_ERROR_HANDLER_EXITCODE=$?
+	#		G_ERROR_HANDLER
 	G_ERROR_HANDLER(){
-
-		#No exit code, grab current
-		if [ ! -n $G_ERROR_HANDLER_EXITCODE ]; then
-
-			G_ERROR_HANDLER_EXITCODE=$?
-
-		fi
 
 		#Ok
 		if (( $G_ERROR_HANDLER_EXITCODE == 0 )); then
@@ -364,10 +364,15 @@
 
 	#Run a command and send the output through the error handler. This has the same effect as running G_ERROR_HANDLER afterwards, however, allows for command used info, and log output/view when an error occurs
 	#	$@ = input command
-	#	eg:		G_RUN_CMD mkdir /never/gonna/work
+	#	eg:
+	#		G_ERROR_HANDLER_ONERROR_USERMSG='We couldn't make a critical directory, holy cow!' #Optional user message if error occurs
+	#		G_RUN_CMD mkdir /never/gonna/work
 	G_RUN_CMD(){
 
 		G_ERROR_HANDLER_COMMAND="$@"
+
+		G_DIETPI-NOTIFY 2 "Running command: $G_ERROR_HANDLER_COMMAND"
+		G_DIETPI-NOTIFY 2 'Please wait...'
 
 		$G_ERROR_HANDLER_COMMAND &> /tmp/G_ERROR_HANDLER_COMMAND
 		G_ERROR_HANDLER_EXITCODE=$?
