v6.0
+ DietPi-Globals | G_DIETPI-NOTIFY: Revert to "echo -ne", as "printf" shows format errors with leading hyphen

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -143,7 +143,7 @@
 			for (( i=0; i<=${#aprocess_string[@]}; i++ )); do
 
 				(( i == 11 )) && i=1
-				[ -f /tmp/dietpi-process.pid ] && printf "\r$bracket_string_l${aprocess_string[i]}$bracket_string_r " || break
+				[ -f /tmp/dietpi-process.pid ] && echo -ne "\r$bracket_string_l${aprocess_string[i]}$bracket_string_r " || break
 				sleep 0.15
 
 			done
@@ -160,34 +160,34 @@
 				tput ed
 
 			fi
-			printf "\r\e[K"
+			echo -ne "\r\e[K"
 
 		}
 
 		Print_Process(){
 
-			printf "\r\e[9C"
+			echo -ne "\r\e[9C"
 
 		}
 
 		Print_Ok(){
 
 			Clean_Process_Animation
-			printf "$bracket_string_l$status_text_ok$bracket_string_r "
+			echo -ne "$bracket_string_l$status_text_ok$bracket_string_r "
 
 		}
 
 		Print_Failed(){
 
 			Clean_Process_Animation
-			printf "$bracket_string_l$status_text_error$bracket_string_r "
+			echo -ne "$bracket_string_l$status_text_error$bracket_string_r "
 
 		}
 
 		Print_Info(){
 
 			Clean_Process_Animation
-			printf "$bracket_string_l$status_text_info$bracket_string_r "
+			echo -ne "$bracket_string_l$status_text_info$bracket_string_r "
 
 		}
 
@@ -198,7 +198,7 @@
 			local i=0
 			for (( i=$1;i<${#ainput_string[@]} ;i++))
 			do
-				printf "${ainput_string[$i]}"
+				echo -ne "${ainput_string[$i]}"
 			done
 
 		}
