dietpi-backup: check target fs permissions without creating the dir
It looks weird that on first dietpi-backup runs, the target dir is first created, then removed, both part of the check, and then created again for the final backup. Neither df not findmnt support checking the next parent fs for a non-existing directory, hence remove directory elements until the dir exists, then check via findmnt.

This commit adds some minor coding changes as well.

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -1488,48 +1488,42 @@ Press any key to continue...'
 	}
 
 	# $1 = directory to test permissions support
-	# Returns 0=ok >=1=failed
-	G_CHECK_FS_PERMISSION_SUPPORT(){
-
+	# Returns 0=ok 1=failed
+	G_CHECK_FS_PERMISSION_SUPPORT()
+	{
 		local input=$1 exit_code=1
 
 		while :
 		do
-			if ! mkdir -p "$input"; then
-
+			if ! mkdir -p "$input"
+			then
 				G_WHIP_MSG "Error creating directory $input, unable to check filesystem permissions"
 				break
-
 			fi
 
-			local fp_target="$input/.test"
-			if ! > "$fp_target"; then
-
+			local fp_target="$input/.dietpi-fs_permission_test"
+			if ! > "$fp_target"
+			then
 				G_WHIP_MSG "Error creating test file $fp_target, unable to check filesystem permissions"
 				break
-
 			fi
 
 			# Apply and check permissions support, twice (just in case the current value is already set)
 			local permissions_failed=0
 
 			chmod 600 "$fp_target"
-			if [[ $(stat -c "%a" "$fp_target") != '600' ]]; then
-
+			if [[ $(stat -c '%a' "$fp_target") != '600' ]]
+			then
 				permissions_failed=1
-
 			else
-
 				chmod 644 "$fp_target"
-				[[ $(stat -c "%a" "$fp_target") != '644' ]] && permissions_failed=1
-
+				[[ $(stat -c '%a' "$fp_target") != '644' ]] && permissions_failed=1
 			fi
 
-			if (( $permissions_failed )); then
-
+			if (( $permissions_failed ))
+			then
 				G_WHIP_MSG "ERROR: Filesystem does not support permissions (e.g.: FAT16/32):\n\n$fp_target\n\nPlease select a different drive and/or format it with ext4, ensuring support for filesystem permissions.\n\nUnable to continue, aborting..."
 				break
-
 			fi
 
 			# Else ok
@@ -1537,9 +1531,8 @@ Press any key to continue...'
 			break
 		done
 
-		[[ -f $fp_target ]] && rm -f "$fp_target"
+		rm -f "$fp_target"
 		return "$exit_code"
-
 	}
 
 	#-----------------------------------------------------------------------------------
