v6.29
+ DietPi-Globals | Add G_CHECK_CON and G_CHECK_DNS for general connection and DNS resolver checking to be called before firstrun setup, DietPi updates or software installs

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -1110,12 +1110,112 @@ $log_content" || break # Exit error handler menu loop on cancel
 
 	}
 
-	# URL Connection test
-	# - $@ = URL + optional arguments
+	#-----------------------------------------------------------------------------------
+	# Network connection checks
+	#-----------------------------------------------------------------------------------
+	# General network connection check
+	# - Checks general network connectivity by pinging a raw IP that must be publicly reachable at all time.
+	# - Uses the given input argument as IP to test against, else CONFIG_CHECK_CONNECTION_IP from dietpi.txt, else defaults to 9.9.9.9 (Quad9 DNS IP).
+	# - Uses G_CHECK_URL_TIMEOUT and G_CHECK_URL_ATTEMPTS variables, else CONFIG_G_CHECK_URL_TIMEOUT + CONFIG_G_CHECK_URL_ATTEMPTS from dietpi.txt, else defaults to 10 seconds and 2 attempts (1 retry).
+	# - Optional arguments:
+	#	$@ = IP + optional ping arguments
 	# - Optional variables:
-	#	- G_CHECK_URL_TIMEOUT to override default and dietpi.txt set timeout
-	#	- G_CHECK_URL_ATTEMPTS to override default and dietpi.txt set attempts
-	# - In case of failure and not $G_INTERACTIVE=0: Prompts user to configure network
+	#	G_CHECK_URL_TIMEOUT to override default and dietpi.txt set timeout
+	#	G_CHECK_URL_ATTEMPTS to override default and dietpi.txt set attempts
+	G_CHECK_CON(){
+
+		# Obtain IP
+		local ip
+		if [[ ! $@ ]]; then
+
+			ip=$(sed -n '/^[[:blank:]]*CONFIG_CHECK_CONNECTION_IP=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
+			[[ $ip ]] || ip='9.9.9.9'
+
+		fi
+
+		# Obtain timeout
+		if ! disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_TIMEOUT" 0; then
+
+			G_CHECK_URL_TIMEOUT=$(sed -n '/^[[:blank:]]*CONFIG_G_CHECK_URL_TIMEOUT=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
+			disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_TIMEOUT" 0 || G_CHECK_URL_TIMEOUT=10
+
+		fi
+
+		# Obtain attempts
+		if ! disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_ATTEMPTS" 0; then
+
+			G_CHECK_URL_ATTEMPTS=$(sed -n '/^[[:blank:]]*CONFIG_G_CHECK_URL_ATTEMPTS=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
+			disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_ATTEMPTS" 0 || G_CHECK_URL_ATTEMPTS=2
+
+		fi
+		G_EXEC_RETRIES=$(( $G_CHECK_URL_ATTEMPTS - 1 )) # 2 attempts = 1 retry
+
+		# Re-assign timeout ($5 => acommand[4]) on every retry, in case it is changed as solution attempt
+		G_EXEC_PRE_FUNC(){ acommand[4]=$G_CHECK_URL_TIMEOUT; }
+
+		G_EXEC_DESC='Checking network connectivity' G_EXEC ping -c 1 -W $G_CHECK_URL_TIMEOUT ${ip:-"$@"}
+		local exit_code=$?
+
+		unset -v G_CHECK_URL_TIMEOUT G_CHECK_URL_ATTEMPTS
+		return $exit_code
+
+	}
+
+	# General DNS resolver check
+	# - Checks general DNS capabilities by pinging a domain that must be publicly reachable at all time.
+	# - Uses the given input argument as domain to test against, else CONFIG_CHECK_DNS_DOMAIN from dietpi.txt, else defaults to dns9.quad9.net (Quad9 DNS domain).
+	# - Uses G_CHECK_URL_TIMEOUT and G_CHECK_URL_ATTEMPTS variables, else CONFIG_G_CHECK_URL_TIMEOUT + CONFIG_G_CHECK_URL_ATTEMPTS from dietpi.txt, else defaults to 10 seconds and 2 attempts (1 retry).
+	# - Optional arguments:
+	#	$@ = domain + optional ping arguments
+	# - Optional variables:
+	#	G_CHECK_URL_TIMEOUT to override default and dietpi.txt set timeout
+	#	G_CHECK_URL_ATTEMPTS to override default and dietpi.txt set attempts
+	G_CHECK_DNS(){
+
+		# Obtain IP
+		local domain
+		if [[ ! $@ ]]; then
+
+			domain=$(sed -n '/^[[:blank:]]*CONFIG_CHECK_DNS_DOMAIN=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
+			[[ $domain ]] || domain='dns9.quad9.net'
+
+		fi
+
+		# Obtain timeout
+		if ! disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_TIMEOUT" 0; then
+
+			G_CHECK_URL_TIMEOUT=$(sed -n '/^[[:blank:]]*CONFIG_G_CHECK_URL_TIMEOUT=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
+			disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_TIMEOUT" 0 || G_CHECK_URL_TIMEOUT=10
+
+		fi
+
+		# Obtain attempts
+		if ! disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_ATTEMPTS" 0; then
+
+			G_CHECK_URL_ATTEMPTS=$(sed -n '/^[[:blank:]]*CONFIG_G_CHECK_URL_ATTEMPTS=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
+			disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_ATTEMPTS" 0 || G_CHECK_URL_ATTEMPTS=2
+
+		fi
+		G_EXEC_RETRIES=$(( $G_CHECK_URL_ATTEMPTS - 1 )) # 2 attempts = 1 retry
+
+		# Re-assign timeout ($5 => acommand[4]) on every retry, in case it is changed as solution attempt
+		G_EXEC_PRE_FUNC(){ acommand[4]=$G_CHECK_URL_TIMEOUT; }
+
+		G_EXEC_DESC='Checking DNS resolver' G_EXEC ping -c 1 -W $G_CHECK_URL_TIMEOUT ${domain:-"$@"}
+		local exit_code=$?
+
+		unset -v G_CHECK_URL_TIMEOUT G_CHECK_URL_ATTEMPTS
+		return $exit_code
+
+	}
+
+	# URL connection test
+	# - Checks a specific HTTP/HTTPS/FTP online resource via its URL
+	# - Required arguments:
+	#	$@ = URL + optional wget arguments
+	# - Optional variables:
+	#	G_CHECK_URL_TIMEOUT to override default and dietpi.txt set timeout
+	#	G_CHECK_URL_ATTEMPTS to override default and dietpi.txt set attempts
 	G_CHECK_URL(){
 
 		# Obtain timeout
@@ -1133,14 +1233,13 @@ $log_content" || break # Exit error handler menu loop on cancel
 			disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_ATTEMPTS" 0 || G_CHECK_URL_ATTEMPTS=2
 
 		fi
+		G_EXEC_RETRIES=$(( $G_CHECK_URL_ATTEMPTS - 1 )) # 2 attempts = 1 retry
 
 		# Re-assign timeout ($6 => acommand[5]) on every retry, in case it is changed as solution attempt
 		G_EXEC_PRE_FUNC(){ acommand[5]=$G_CHECK_URL_TIMEOUT; }
 
-		G_EXEC_DESC="Connection test: $*"
-		G_EXEC_RETRIES=$G_CHECK_URL_ATTEMPTS
 		# Since --tries/-t is not applied on "fatal" errors (resolving failed, connection refused, 404), we need to loop ourself to exclude any temporary issue
-		G_EXEC wget --spider -t 1 -T $G_CHECK_URL_TIMEOUT "$@"
+		G_EXEC_DESC="Checking URL: $*" G_EXEC wget --spider -t 1 -T $G_CHECK_URL_TIMEOUT "$@"
 		local exit_code=$?
 
 		unset -v G_CHECK_URL_TIMEOUT G_CHECK_URL_ATTEMPTS
