v7.8
+ DietPi-Set_userdata | Fix "local" usage and align variable names with other scripts

diff --git a/dietpi/func/dietpi-set_userdata b/dietpi/func/dietpi-set_userdata
--- a/dietpi/func/dietpi-set_userdata
+++ b/dietpi/func/dietpi-set_userdata
@@ -13,7 +13,7 @@
 	# - Allows automated moving of user data in DietPi. Automatically generates a symlink from /mnt/dietpi_userdata to target directory if needed.
 	#
 	# Usage:
-	# - /boot/dietpi/func/dietpi-set_userdata SOURCE_DIRECTORY TARGET_DIRECTORY | Setup user data directory, move data if needed. If TARGET_DIRECTORY='auto', auto target location. Returns 1 if failed.
+	# - /boot/dietpi/func/dietpi-set_userdata FP_SOURCE FP_TARGET | Setup user data directory, move data if needed. If FP_TARGET='auto', auto target location. Returns 1 if failed.
 	#////////////////////////////////////
 
 	# Import DietPi-Globals --------------------------------------------------------------
@@ -27,11 +27,13 @@
 
 	# Grab input
 	# - Remove trailing slashes
-	SOURCE_DIRECTORY=${1%/}
-	TARGET_DIRECTORY=${2%/}
+	FP_SOURCE=${1%/}
+	FP_TARGET=${2%/}
 
 	readonly FP_LOG='/var/log/dietpi-move_userdata.log'
 	LOGFILE_OUTPUT_TEXT=
+	TARGET_FS_TYPE=
+	TARGET_FS_TYPE_SUPPORTED=0
 	FREESPACE_REQUIRED_SOURCE=0
 
 	Run_Move_Data(){
@@ -39,30 +41,30 @@
 		# Stop all running services
 		/boot/dietpi/dietpi-services stop
 
-		G_DIETPI-NOTIFY 2 "Moving your existing data from $SOURCE_DIRECTORY to $TARGET_DIRECTORY, please wait..."
+		G_DIETPI-NOTIFY 2 "Moving your existing data from $FP_SOURCE to $FP_TARGET, please wait..."
 
 		# Begin transfer
-		if cp -a "$SOURCE_DIRECTORY/." "$TARGET_DIRECTORY/"; then
+		if cp -a "$FP_SOURCE/." "$FP_TARGET/"; then
 
 			# Remove source
-			rm -R "$SOURCE_DIRECTORY"
+			rm -R "$FP_SOURCE"
 
 			# Create symlink at /mnt/dietpi_userdata if required
-			if [[ $TARGET_DIRECTORY != '/mnt/dietpi_userdata' ]]; then
+			if [[ $FP_TARGET != '/mnt/dietpi_userdata' ]]; then
 
 				rm -Rf /mnt/dietpi_userdata
-				ln -s "$TARGET_DIRECTORY" /mnt/dietpi_userdata
+				ln -s "$FP_TARGET" /mnt/dietpi_userdata
 
 			fi
 
 			# Apply dietpi:dietpi owner, used by some software titles like Syncthing and file servers to permit creating files and directories
-			chown dietpi:dietpi "$TARGET_DIRECTORY"
+			chown dietpi:dietpi "$FP_TARGET"
 
-			LOGFILE_OUTPUT_TEXT="Successfully moved your data from $SOURCE_DIRECTORY to $TARGET_DIRECTORY."
+			LOGFILE_OUTPUT_TEXT="Successfully moved your data from $FP_SOURCE to $FP_TARGET."
 
 		else
 
-			LOGFILE_OUTPUT_TEXT="Failed to copy $SOURCE_DIRECTORY/ to $TARGET_DIRECTORY."
+			LOGFILE_OUTPUT_TEXT="Failed to copy $FP_SOURCE/ to $FP_TARGET."
 			EXIT_CODE=1
 
 		fi
@@ -77,68 +79,68 @@
 	#/////////////////////////////////////////////////////////////////////////////////////
 
 	G_DIETPI-NOTIFY 3 'DietPi Updating user data location'
-	G_DIETPI-NOTIFY 2 " - From : $SOURCE_DIRECTORY"
-	G_DIETPI-NOTIFY 2 " - To   : $TARGET_DIRECTORY"
+	G_DIETPI-NOTIFY 2 " - From : $FP_SOURCE"
+	G_DIETPI-NOTIFY 2 " - To   : $FP_TARGET"
 	G_DIETPI-NOTIFY 2 'Please wait...'
 
 	# Sanity checks
 	# - Check for both inputs
-	if ! [[ $SOURCE_DIRECTORY && $TARGET_DIRECTORY ]]; then
+	if ! [[ $FP_SOURCE && $FP_TARGET ]]; then
 
-		LOGFILE_OUTPUT_TEXT="Please provide a source ($SOURCE_DIRECTORY) and target ($TARGET_DIRECTORY) directory for input."
+		LOGFILE_OUTPUT_TEXT="Please provide a source ($FP_SOURCE) and target ($FP_TARGET) directory for input."
 		EXIT_CODE=1
 
 	# - Check if symlink is already pointing to target directory
-	elif [[ $(readlink -f /mnt/dietpi_userdata) == "$TARGET_DIRECTORY" ]]; then
+	elif [[ $(readlink -f /mnt/dietpi_userdata) == "$FP_TARGET" ]]; then
 
-		LOGFILE_OUTPUT_TEXT="/mnt/dietpi_userdata has already been moved to $TARGET_DIRECTORY, nothing to do."
+		LOGFILE_OUTPUT_TEXT="/mnt/dietpi_userdata has already been moved to $FP_TARGET, nothing to do."
 
 	# - Check if source directory exists
-	elif [[ ! -d $SOURCE_DIRECTORY ]]; then
+	elif [[ ! -d $FP_SOURCE ]]; then
 
-		LOGFILE_OUTPUT_TEXT="Source directory $SOURCE_DIRECTORY does not exist."
+		LOGFILE_OUTPUT_TEXT="Source directory $FP_SOURCE does not exist."
 		EXIT_CODE=1
 
 	# - Check for disallowed directory match
-	elif [[ $SOURCE_DIRECTORY == "$TARGET_DIRECTORY" || $SOURCE_DIRECTORY == "$TARGET_DIRECTORY/"* || $TARGET_DIRECTORY == "$SOURCE_DIRECTORY/"* ]]; then
+	elif [[ $FP_SOURCE == "$FP_TARGET" || $FP_SOURCE == "$FP_TARGET/"* || $FP_TARGET == "$FP_SOURCE/"* ]]; then
 
-		LOGFILE_OUTPUT_TEXT="$SOURCE_DIRECTORY and $TARGET_DIRECTORY cannot be within each other. Disallowed directory match."
+		LOGFILE_OUTPUT_TEXT="$FP_SOURCE and $FP_TARGET cannot be within each other. Disallowed directory match."
 		EXIT_CODE=1
 
 	# - Only allow full path
-	elif [[ $SOURCE_DIRECTORY != '/'* || $TARGET_DIRECTORY != '/'* ]]; then
+	elif [[ $FP_SOURCE != '/'* || $FP_TARGET != '/'* ]]; then
 
-		LOGFILE_OUTPUT_TEXT="Source ($SOURCE_DIRECTORY) and target directories ($TARGET_DIRECTORY) must be given with absolute path, e.g.: /mnt/drive1"
+		LOGFILE_OUTPUT_TEXT="Source ($FP_SOURCE) and target directories ($FP_TARGET) must be given with absolute path, e.g.: /mnt/drive1"
 		EXIT_CODE=1
 
 	else
 		# Remove /mnt/dietpi_userdata symlink, if chosen as target
-		[[ $TARGET_DIRECTORY == '/mnt/dietpi_userdata' && -L '/mnt/dietpi_userdata' ]] && G_EXEC rm /mnt/dietpi_userdata
+		[[ $FP_TARGET == '/mnt/dietpi_userdata' && -L '/mnt/dietpi_userdata' ]] && G_EXEC rm /mnt/dietpi_userdata
 
 		# Create target directory
-		G_EXEC mkdir -p "$TARGET_DIRECTORY"
+		G_EXEC mkdir -p "$FP_TARGET"
 
 		# Check for supported filesystem type
-		local fs_type=$(df -T "$TARGET_DIRECTORY" | mawk 'NR==2 {print $2}') fs_type_supported=0
+		TARGET_FS_TYPE=$(df -T "$FP_TARGET" | mawk 'NR==2 {print $2}')
 		for i in 'ext4' 'ext3' 'ext2' 'f2fs' 'btrfs' 'xfs' 'zfs'
 		do
-			[[ $fs_type == "$i" ]] || continue
-			fs_type_supported=1
+			[[ $TARGET_FS_TYPE == "$i" ]] || continue
+			TARGET_FS_TYPE_SUPPORTED=1
 		done
 
 		# Not supported
-		if (( ! $fs_type_supported ))
+		if (( ! $TARGET_FS_TYPE_SUPPORTED ))
 		then
-			LOGFILE_OUTPUT_TEXT="Filesystem type $fs_type of $TARGET_DIRECTORY is not supported for transferring DietPi user data. Transfer aborted.\n - The filesystem type must be ext2/3/4, F2FS, Btrfs, XFS or ZFS for native symlink and UNIX permissions compatibilities."
+			LOGFILE_OUTPUT_TEXT="Filesystem type $TARGET_FS_TYPE of $FP_TARGET is not supported for transferring DietPi user data. Transfer aborted.\n - The filesystem type must be ext2/3/4, F2FS, Btrfs, XFS or ZFS for native symlink and UNIX permissions compatibilities."
 			EXIT_CODE=1
 		else
 			# Check for sufficient free space in target directory
 			# - "-m" => result in MiB actual disk usage, respecting disk block size, e.g. "144"
 			# - Trailing slash required with "du" to correctly check symlink target in case
-			FREESPACE_REQUIRED_SOURCE=$(du -sm "$SOURCE_DIRECTORY/" | mawk '{print $1}')
-			if ! G_CHECK_FREESPACE "$TARGET_DIRECTORY" "$FREESPACE_REQUIRED_SOURCE"
+			FREESPACE_REQUIRED_SOURCE=$(du -sm "$FP_SOURCE/" | mawk '{print $1}')
+			if ! G_CHECK_FREESPACE "$FP_TARGET" "$FREESPACE_REQUIRED_SOURCE"
 			then
-				LOGFILE_OUTPUT_TEXT="Not enough free space in target directory $TARGET_DIRECTORY.\n - Required: $FREESPACE_REQUIRED_SOURCE MiB"
+				LOGFILE_OUTPUT_TEXT="Not enough free space in target directory $FP_TARGET.\n - Required: $FREESPACE_REQUIRED_SOURCE MiB"
 				EXIT_CODE=1
 			else
 				# Run, attempt to move data.
