v8.3 (#5383)
- CI | Add shellcheck to GitHub actions
- Code | Address optional shellcheck annotations batch 1
- CI | Shellcheck: Disable optional checks for now, until we find time to address all of them

diff --git a/dietpi/func/dietpi-set_userdata b/dietpi/func/dietpi-set_userdata
--- a/dietpi/func/dietpi-set_userdata
+++ b/dietpi/func/dietpi-set_userdata
@@ -149,21 +149,20 @@
 		if (( $EXIT_CODE )); then
 
 			G_DIETPI-NOTIFY 1 "$LOGFILE_OUTPUT_TEXT"
-			echo -e "[FAILED] $LOGFILE_OUTPUT_TEXT" > $FP_LOG
+			echo -e "[FAILED] $LOGFILE_OUTPUT_TEXT" > "$FP_LOG"
 
 		# Ok
 		else
 
 			G_DIETPI-NOTIFY 0 "$LOGFILE_OUTPUT_TEXT"
-			echo -e "[  OK  ] $LOGFILE_OUTPUT_TEXT" > $FP_LOG
+			echo -e "[  OK  ] $LOGFILE_OUTPUT_TEXT" > "$FP_LOG"
 
 		fi
 
 	fi
 
 	#-----------------------------------------------------------------------------------
-	G_DIETPI-NOTIFY -1 $EXIT_CODE "$G_PROGRAM_NAME"
-	#-----------------------------------------------------------------------------------
-	exit $EXIT_CODE
+	G_DIETPI-NOTIFY -1 "$EXIT_CODE" "$G_PROGRAM_NAME"
+	exit "$EXIT_CODE"
 	#-----------------------------------------------------------------------------------
 }
