v7.8
+ DietPi-Drive_Manager | Enforce filesystem limit for moving the rootfs by only showing supported filesystem types in the format menu. The dedicated Btrfs warning/abortion is obsolete as the the target partition is reformatted.
+ DietPi-Drive_Manager | Allow moving the rootfs on Odroid C4, which works like on all other Odroids.
+ DietPi-Drive_Manager | Do not force the user to unmount the rootfs target manually, as this is done automatically when the partition is formatted.
+ DietPi-Drive_Manager | Check whether the filesystem is supported when moving DietPi user data. Enforce a filesystem type with native UNIX permissions and symlink support. NTFS with emulated features via ntfs-3g driver has been shown to not be reliable in this regards and a network drive is currently ruled out as the option isn't shown in the menu then. We may think about allowing user data on an NFS mount with verified that UNIX permissions and symlinks are both supported. Do the same fileystem type validation in dietpi-set_userdata, just in case it is called manually.

diff --git a/dietpi/func/dietpi-set_userdata b/dietpi/func/dietpi-set_userdata
--- a/dietpi/func/dietpi-set_userdata
+++ b/dietpi/func/dietpi-set_userdata
@@ -105,46 +105,46 @@
 		LOGFILE_OUTPUT_TEXT="$SOURCE_DIRECTORY and $TARGET_DIRECTORY cannot be within each other. Disallowed directory match."
 		EXIT_CODE=1
 
-	# - Only allow full filepaths
+	# - Only allow full path
 	elif [[ $SOURCE_DIRECTORY != '/'* || $TARGET_DIRECTORY != '/'* ]]; then
 
 		LOGFILE_OUTPUT_TEXT="Source ($SOURCE_DIRECTORY) and target directories ($TARGET_DIRECTORY) must be given with absolute path, e.g.: /mnt/drive1"
 		EXIT_CODE=1
 
 	else
-
 		# Remove /mnt/dietpi_userdata symlink, if chosen as target
-		[[ $TARGET_DIRECTORY == '/mnt/dietpi_userdata' && -L '/mnt/dietpi_userdata' ]] && rm /mnt/dietpi_userdata
+		[[ $TARGET_DIRECTORY == '/mnt/dietpi_userdata' && -L '/mnt/dietpi_userdata' ]] && G_EXEC rm /mnt/dietpi_userdata
 
 		# Create target directory
-		mkdir -p "$TARGET_DIRECTORY"
+		G_EXEC mkdir -p "$TARGET_DIRECTORY"
 
-		# Ensure target directory supports POSIX permissions
-		if ! G_CHECK_FS_PERMISSION_SUPPORT "$TARGET_DIRECTORY"; then
+		# Check for supported filesystem type
+		local fs_type=$(df -T "$TARGET_DIRECTORY" | mawk 'NR==2 {print $2}') fs_type_supported=0
+		for i in 'ext4' 'ext3' 'ext2' 'f2fs' 'btrfs' 'xfs' 'zfs'
+		do
+			[[ $fs_type == "$i" ]] || continue
+			fs_type_supported=1
+		done
 
-			LOGFILE_OUTPUT_TEXT="$TARGET_DIRECTORY does not support POSIX permissions. Transfer aborted."
+		# Not supported
+		if (( ! $fs_type_supported ))
+		then
+			LOGFILE_OUTPUT_TEXT="Filesystem type $fs_type of $TARGET_DIRECTORY is not supported for transferring DietPi user data. Transfer aborted.\n - The filesystem type must be ext2/3/4, F2FS, Btrfs, XFS or ZFS for native symlink and UNIX permissions compatibilities."
 			EXIT_CODE=1
-
 		else
-
 			# Check for sufficient free space in target directory
 			# - "-m" => result in MiB actual disk usage, respecting disk block size, e.g. "144"
 			# - Trailing slash required with "du" to correctly check symlink target in case
 			FREESPACE_REQUIRED_SOURCE=$(du -sm "$SOURCE_DIRECTORY/" | mawk '{print $1}')
-			if ! G_CHECK_FREESPACE "$TARGET_DIRECTORY" "$FREESPACE_REQUIRED_SOURCE"; then
-
+			if ! G_CHECK_FREESPACE "$TARGET_DIRECTORY" "$FREESPACE_REQUIRED_SOURCE"
+			then
 				LOGFILE_OUTPUT_TEXT="Not enough free space in target directory $TARGET_DIRECTORY.\n - Required: $FREESPACE_REQUIRED_SOURCE MiB"
 				EXIT_CODE=1
-
 			else
-
 				# Run, attempt to move data.
 				Run_Move_Data
-
 			fi
-
 		fi
-
 	fi
 
 	#-----------------------------------------------------------------------------------
