v6.0
+ G_CHECK_URL: prompt user to configure network on failure:
https://github.com/Fourdee/DietPi/issues/1385#issuecomment-358972239

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -727,27 +727,70 @@ $print_logfile_info
 	#-----------------------------------------------------------------------------------
 	# URL Connection test
 	#-----------------------------------------------------------------------------------
-	# $1 = URL
+	# $@ = URL
 	#	NB: automatically error handled (G_ERROR_HANDLER)
+	#	Prompts user to configure network if $G_USER_INPUTS=1 (default)
 	G_CHECK_URL(){
 
-		local string="$1"
+		local string="$@"
 		local timeout=10
 		local retry=2
+		local error_connection_failed=0
 
 		G_ERROR_HANDLER_EXITCODE=0
 		G_ERROR_HANDLER_COMMAND="Connection test: $string"
 		G_ERROR_HANDLER_ONERROR_FPLOGFILE='/tmp/G_CHECK_URL'
 
-		G_DIETPI-NOTIFY -2 "Testing connection to $string for max $(($timeout * $retry)) seconds"
+		while true
+		do
 
-		wget --spider --timeout=$timeout --tries=$retry "$string" &> /tmp/G_CHECK_URL
-		G_ERROR_HANDLER_EXITCODE=$?
+			#Allow user choice to configure network on failure
+			if (( $G_USER_INPUTS )); then
 
-		#--no-check-certificate
-		#https://github.com/Fourdee/DietPi/issues/352#issuecomment-221013166
+				G_ERROR_HANDLER_ONERROR_EXIT=0
 
-		G_ERROR_HANDLER
+				if (( $error_connection_failed )); then
+
+					#Ask to check settings,
+					whiptail --title "URL Connection Test Failed" --yesno "DietPi was unable to establish a connection:\n - $string\n\nIf problems persist, the URL may be offline/unreachable.\n\nWould you like to configure network settings and try again?" --yes-button "Ok" --no-button "Exit" --defaultno --backtitle "$G_PROGRAM_NAME" 15 70
+					CHOICE=$?
+
+					#run dietpi config
+					if (( $CHOICE == 0 )); then
+
+						whiptail --title "Launching DietPi-Config" --msgbox "DietPi-Config will now be started.\nUse the Network Options menu to change and test your network settings.\n\nWhen completed, Exit DietPi-Config to resume." --backtitle "Launching DietPi-Config" 14 60
+						/DietPi/dietpi/dietpi-config 8 1
+
+					#User aborted, exit now with current error information
+					else
+
+						G_ERROR_HANDLER_ONERROR_EXIT=1
+						G_ERROR_HANDLER_EXITCODE=1
+						G_USER_INPUTS=0 #disable whiptail info
+						G_ERROR_HANDLER
+
+					fi
+
+				fi
+
+			fi
+
+			G_DIETPI-NOTIFY -2 "Testing connection to $string for max $(($timeout * $retry)) seconds"
+
+			wget --spider --timeout=$timeout --tries=$retry "$string" &> /tmp/G_CHECK_URL
+			G_ERROR_HANDLER_EXITCODE=$?
+			if (( $G_ERROR_HANDLER_EXITCODE != 0 )); then
+
+				error_connection_failed=1
+
+			fi
+
+			#--no-check-certificate
+			#https://github.com/Fourdee/DietPi/issues/352#issuecomment-221013166
+
+			G_ERROR_HANDLER
+
+		done
 
 		rm /tmp/G_CHECK_URL
 
