v6.32
+ DietPi-Globals | G_TREESIZE: Handle "bytes" sizes and unit as well and do not require root. If "du" tries to access dirs without read permissions, it prints meaningful error messages to STDERR, not processed by sort + mawk, so now one sees the errors (in case) and the treesize for all permitted dirs.
+ DietPi-Globals | G_CHECK_FREESPACE: Check for valid du output as well when only printing available free space. This allows the feature to be used safely in scripts and will return a non-zero exit code if either the input path does not exist, cannot be read, df is broken or similar.
+ DietPi-Globals | Various output and failsafe coding enhancements

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -180,7 +180,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 		# Printing terminal height - 1 newlines seems to be the fastes method that is compatible with all terminal types.
 		local lines=$(stty size) i newlines
 		for ((i=1;i<${lines% *};i++)); do newlines+='\n'; done
-		printf "\e[0m$newlines\e[H"
+		echo -ne "\e[0m$newlines\e[H"
 
 	}
 
@@ -211,13 +211,13 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 			# Kill existing process animation if this is not a processing message
 			if [[ $1 != '-2' && -w '/tmp/dietpi-process.pid' ]]; then
 
-				kill -9 $(</tmp/dietpi-process.pid) &> /dev/null
+				kill -9 "$(</tmp/dietpi-process.pid)" &> /dev/null
 				rm -f /tmp/dietpi-process.pid &> /dev/null
 
 			fi
 
 		fi
-		local bracket_l="$grey[$reset" bracket_r="$grey]$reset"
+		local bracket_l="${grey}[$reset" bracket_r="$grey]$reset"
 		local ok="$bracket_l$green  OK  $bracket_r " failed="$bracket_l${red}FAILED$bracket_r "
 
 		# Print input array from index $1
@@ -925,7 +925,7 @@ $grey─────────────────────────
 
 				# Print $G_EXEC_DESC if given, else raw input command string and show current non-interactive attempt count if $G_EXEC_RETRIES is given
 				G_DIETPI-NOTIFY 2 "${G_EXEC_DESC:-$*}, please wait...${G_EXEC_RETRIES:+ ($attempt/$((G_EXEC_RETRIES+1)))}"
-				[[ $G_EXEC_OUTPUT_COL ]] && printf "$G_EXEC_OUTPUT_COL"
+				[[ $G_EXEC_OUTPUT_COL ]] && echo -ne "$G_EXEC_OUTPUT_COL"
 				"${acommand[@]}" 2>&1 | tee $fp_log
 				exit_code=${PIPESTATUS[0]}
 				[[ $G_EXEC_OUTPUT_COL ]] && printf '\e[0m'
@@ -1263,7 +1263,7 @@ $log_content" || break # Exit error handler menu loop on cancel
 		while :
 		do
 
-			if ! mkdir -p $input; then
+			if ! mkdir -p "$input"; then
 
 				G_WHIP_MSG "Error creating directory $input, unable to check filesystem permissions"
 				break
@@ -1271,7 +1271,7 @@ $log_content" || break # Exit error handler menu loop on cancel
 			fi
 
 			local fp_target="$input/.test"
-			if ! > $fp_target; then
+			if ! > "$fp_target"; then
 
 				G_WHIP_MSG "Error creating test file $fp_target, unable to check filesystem permissions"
 				break
@@ -1281,21 +1281,21 @@ $log_content" || break # Exit error handler menu loop on cancel
 			# Apply and check permissions support, twice (just incase the current value is already set)
 			local permissions_failed=0
 
-			chmod 600 $fp_target
-			if [[ $(stat -c "%a" $fp_target) != '600' ]]; then
+			chmod 600 "$fp_target"
+			if [[ $(stat -c "%a" "$fp_target") != '600' ]]; then
 
 				permissions_failed=1
 
 			else
 
-				chmod 644 $fp_target
-				[[ $(stat -c "%a" $fp_target) != '644' ]] && permissions_failed=1
+				chmod 644 "$fp_target"
+				[[ $(stat -c "%a" "$fp_target") != '644' ]] && permissions_failed=1
 
 			fi
 
 			if (( $permissions_failed )); then
 
-				G_WHIP_MSG "ERROR: Filesystem does not support permissions (eg: FAT16/32):\n\n$fp_target\n\nPlease select a different drive and/or format it with ext4, ensuring support for filesystem permissions.\n\nUnable to continue, aborting..."
+				G_WHIP_MSG "ERROR: Filesystem does not support permissions (e.g.: FAT16/32):\n\n$fp_target\n\nPlease select a different drive and/or format it with ext4, ensuring support for filesystem permissions.\n\nUnable to continue, aborting..."
 				break
 
 			fi
@@ -1306,7 +1306,7 @@ $log_content" || break # Exit error handler menu loop on cancel
 
 		done
 
-		[[ -f $fp_target ]] && rm -f $fp_target
+		[[ -f $fp_target ]] && rm -f "$fp_target"
 		return $result
 
 	}
@@ -1461,26 +1461,18 @@ $log_content" || break # Exit error handler menu loop on cancel
 	# MISC: Commands
 	#-----------------------------------------------------------------------------------
 	# Treesize
-	# - $1 = Optional input directory (eg: G_TREESIZE /etc/apt)
+	# - $1 = Optional input directory, e.g.: G_TREESIZE /var/cache/apt
 	G_TREESIZE(){
 
-		G_CHECK_ROOT_USER 1
-
-		du -k --max-depth=1 $1 | sort -nr | mawk '
-		BEGIN {
-			split("KB,MB,GB,TB", Units, ",");
-		}
+		du -B 1 -d 1 ${1:+"$1"} | sort -nr | mawk '
+		BEGIN { split("bytes,KiB,MiB,GiB,TiB", unit, ",") }
 		{
-			u = 1;
-			while ($1 >= 1024)
-			{
-				$1 = $1 / 1024;
-				u += 1;
-			}
-			$1 = sprintf("%.1f %s", $1, Units[u]);
-			print $0;
-		}
-		'
+			u=1
+			while ($1>=1024) { $1=$1/1024; u+=1 }
+			$1=sprintf("%.1f %s", $1, unit[u])
+			print $0
+		}'
+
 	}
 
 	# Returns current CPU temp 'C
@@ -1509,10 +1501,10 @@ $log_content" || break # Exit error handler menu loop on cancel
 
 			)
 
-			for i in ${afp_temperature[@]}
+			for i in "${afp_temperature[@]}"
 			do
 
-				[[ -f $i ]] && { temp=$(<$i); break; }
+				[[ -f $i ]] && { temp=$(<"$i"); break; }
 
 			done
 
@@ -1599,22 +1591,17 @@ $log_content" || break # Exit error handler menu loop on cancel
 		local return_value=1
 		local input_path=$1
 		local input_required_space=$2
-		local available_space=$(df -m --output=avail $input_path | mawk 'NR==2 {print $1}')
+		local available_space=$(df -m --output=avail "$input_path" | mawk 'NR==2 {print $1}')
 
-		if [[ ! $input_required_space ]]; then
+		if ! disable_error=1 G_CHECK_VALIDINT "$available_space"; then
 
-			if (( $info_autoscale )); then
+			G_WHIP_MSG 'G_CHECK_FREESPACE: Invalid integer from df result'
 
-				(( $available_space > 9999 )) && available_space="$(( $available_space / 1024 )) GiB" || available_space+=' MiB'
+		elif [[ ! $input_required_space ]]; then
 
-			fi
-
-			echo $available_space
+			(( $info_autoscale )) && { (( $available_space > 9999 )) && available_space="$(( $available_space / 1024 )) GiB" || available_space+=' MiB'; }
+			echo "$available_space"
 			return_value=0
-
-		elif ! disable_error=1 G_CHECK_VALIDINT $available_space; then
-
-			G_WHIP_MSG 'G_CHECK_FREESPACE: invalid integer from df result'
 
 		else
 
@@ -1704,7 +1691,7 @@ $log_content" || break # Exit error handler menu loop on cancel
 
 			# Check physical location exists and is mounted
 			fp_actual=$(readlink -f $G_FP_DIETPI_USERDATA)
-			df -P $fp_actual &> /dev/null || return_value=1
+			df -P "$fp_actual" &> /dev/null || return_value=1
 
 		fi
 
@@ -1788,21 +1775,20 @@ $log_content" || break # Exit error handler menu loop on cancel
 		# Run in blocking mode
 		if [[ $G_THREADING_ENABLED == 0 ]]; then
 
-			local command=$*
-			G_DIETPI-NOTIFY 2 "G_THREADING disabled, running command in blocking mode | $command"
-			$command
+			G_DIETPI-NOTIFY 2 "G_THREADING disabled, running command in blocking mode | $@"
+			"$@"
 
 		# Launch as background process
 		else
 
 			[[ $G_THREAD_COUNT =~ ^[0-9]+$ ]] || G_THREAD_COUNT=-1
 			((G_THREAD_COUNT++))
-			G_THREAD_COMMAND[$G_THREAD_COUNT]=$*
+			G_THREAD_COMMAND[$G_THREAD_COUNT]=$* # Store for later output with G_THREAD_WAIT
 
-			echo -1337 > /tmp/.G_THREAD_EXITCODE_$G_THREAD_COUNT
-			{ { G_INTERACTIVE=0 ${G_THREAD_COMMAND[$G_THREAD_COUNT]} &> /tmp/.G_THREAD_COMMAND_$G_THREAD_COUNT; echo $? > /tmp/.G_THREAD_EXITCODE_$G_THREAD_COUNT; } & disown; } &> /dev/null
+			echo -1337 > "/tmp/.G_THREAD_EXITCODE_$G_THREAD_COUNT"
+			{ { G_INTERACTIVE=0 "$@" &> "/tmp/.G_THREAD_COMMAND_$G_THREAD_COUNT"; echo $? > "/tmp/.G_THREAD_EXITCODE_$G_THREAD_COUNT"; } & disown; } &> /dev/null
 
-			G_DIETPI-NOTIFY 2 "G_THREAD_START_$G_THREAD_COUNT | ${G_THREAD_COMMAND[$G_THREAD_COUNT]}"
+			G_DIETPI-NOTIFY 2 "G_THREAD_START_$G_THREAD_COUNT | $*"
 
 		fi
 
@@ -1813,43 +1799,38 @@ $log_content" || break # Exit error handler menu loop on cancel
 		#local wait_for_specific_thread_pid=-1
 		#[[ $1 ]] && wait_for_specific_thread_pid=$1
 
-		local thread_active i waiting=-1
+		local i waiting_for exit_code
 
+		# Wait until all theads finished
 		while :
 		do
 
-			thread_active=0
-
-			for i in ${!G_THREAD_COMMAND[@]}
+			for i in "${!G_THREAD_COMMAND[@]}"
 			do
 
-				if [[ -f /tmp/.G_THREAD_EXITCODE_$i && $(</tmp/.G_THREAD_EXITCODE_$i) == '-1337' ]]; then
-
-					(( $waiting == $i )) || G_DIETPI-NOTIFY -2 "G_THREAD_WAIT_$i | ${G_THREAD_COMMAND[$i]}"
-					thread_active=1
-					break
-
-				fi
+				[[ -f /tmp/.G_THREAD_EXITCODE_$i && $(<"/tmp/.G_THREAD_EXITCODE_$i") == '-1337' ]] || continue
+				# Print what we are waiting for, update processing message if thread changed since last loop
+				[[ $waiting_for == $i ]] || G_DIETPI-NOTIFY -2 "G_THREAD_WAIT_$i | ${G_THREAD_COMMAND[$i]}"
+				waiting_for=$i
+				sleep 1
+				continue 2
 
 			done
 
-			(( $thread_active )) || break
-
-			waiting=$i
-			sleep 1
+			break
 
 		done
 
 		G_DIETPI-NOTIFY 0 'G_THREAD: All threads finished'
 
-		# - Check all thread exit codes for issues
-		for i in ${!G_THREAD_COMMAND[@]}
+		# Check all thread's exit codes for issues
+		for i in "${!G_THREAD_COMMAND[@]}"
 		do
 
 			if [[ -r /tmp/.G_THREAD_EXITCODE_$i ]]; then
 
-				local exit_code=$(</tmp/.G_THREAD_EXITCODE_$i)
-				(( $exit_code )) && G_WHIP_MSG "G_THREAD ERROR:\n - Command = ${G_THREAD_COMMAND[$i]}\n - Exit code = $exit_code\n\n$(</tmp/.G_THREAD_COMMAND_$i)"
+				exit_code=$(<"/tmp/.G_THREAD_EXITCODE_$i")
+				(( $exit_code )) && G_WHIP_MSG "G_THREAD ERROR:\n - Command = ${G_THREAD_COMMAND[$i]}\n - Exit code = $exit_code\n\n$(<"/tmp/.G_THREAD_COMMAND_$i")"
 
 			else
 
@@ -1973,18 +1954,18 @@ NB:
 \nRetry with proper permissions or apply the setting manually:
 	$setting_raw"
 
-		elif error=$(grep -Eq "^[[:blank:]]*$pattern" $file 2>&1); then
+		elif error=$(grep -Eq "^[[:blank:]]*$pattern" "$file" 2>&1); then
 			# As an error within the condition leads to result "false", it can be caught only in next "elif"/"else" statement.
 
 			if [[ $GCI_PRESERVE == 1 ]]; then
 
-				G_DIETPI-NOTIFY 0 "Current setting in \e[33m$file\e[0m will be preserved: \e[33m$([[ $GCI_PASSWORD == 1 ]] && echo "${setting_raw//\\/\\\\}" || grep -Em1 "^[[:blank:]]*$pattern" $file | sed 's|\\|\\\\|g')\e[0m"
+				G_DIETPI-NOTIFY 0 "Current setting in \e[33m$file\e[0m will be preserved: \e[33m$([[ $GCI_PASSWORD == 1 ]] && echo "${setting_raw//\\/\\\\}" || grep -Em1 "^[[:blank:]]*$pattern" "$file" | sed 's|\\|\\\\|g')\e[0m"
 
-			elif error=$(grep -Eq "^[[:blank:]]*$setting([[:space:]]|$)" $file 2>&1); then
+			elif error=$(grep -Eq "^[[:blank:]]*$setting([[:space:]]|$)" "$file" 2>&1); then
 
-				G_DIETPI-NOTIFY 0 "Desired setting in \e[33m$file\e[0m was already set: \e[33m$([[ $GCI_PASSWORD == 1 ]] && echo "${setting_raw//\\/\\\\}" || grep -Em1 "^[[:blank:]]*$pattern" $file | sed 's|\\|\\\\|g')\e[0m"
+				G_DIETPI-NOTIFY 0 "Desired setting in \e[33m$file\e[0m was already set: \e[33m$([[ $GCI_PASSWORD == 1 ]] && echo "${setting_raw//\\/\\\\}" || grep -Em1 "^[[:blank:]]*$pattern" "$file" | sed 's|\\|\\\\|g')\e[0m"
 
-			elif error=$( (( $(grep -Ec "^[[:blank:]]*$pattern" $file 2>&1) > 1 )) 2>&1); then
+			elif error=$( (( $(grep -Ec "^[[:blank:]]*$pattern" "$file" 2>&1) > 1 )) 2>&1); then
 				[[ $error ]] && { syntax_error; return 1; }
 
 				G_WHIP_MSG "[FAILED] Setting was found multiple times
@@ -1993,7 +1974,7 @@ NB:
 was found multiple times in file \$3
 	$file
 \n____________
-$(grep -En "^[[:blank:]]*$pattern" $file)
+$(grep -En "^[[:blank:]]*$pattern" "$file")
 ____________
 \nEither the pattern \$1 needs to be more specific or the desired setting can appear multiple times by design and it cannot be predicted which instance to edit.
 Please retry with more specific parameter \$1 or apply the setting manually:
@@ -2002,17 +1983,17 @@ Please retry with more specific parameter \$1 or apply the setting manually:
 			else
 				[[ $error ]] && { syntax_error; return 1; }
 
-				[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
-				error=$(sed -Ei "0,/^[[:blank:]]*$pattern.*$/s//$setting/" $file 2>&1) || { syntax_error; return 1; }
+				[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a "$file" "$file.bak" && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
+				error=$(sed -Ei "0,/^[[:blank:]]*$pattern.*$/s//$setting/" "$file" 2>&1) || { syntax_error; return 1; }
 				G_DIETPI-NOTIFY 0 "Setting in \e[33m$file\e[0m adjusted: \e[33m${setting_raw//\\/\\\\}\e[0m"
 
 			fi
 
-		elif error=$(grep -Eq "^[[:blank:]#;]*$pattern" $file 2>&1); then
+		elif error=$(grep -Eq "^[[:blank:]#;]*$pattern" "$file" 2>&1); then
 			[[ $error ]] && { syntax_error; return 1; }
 
-			[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
-			error=$(sed -Ei "0,/^[[:blank:]#;]*$pattern.*$/s//$setting/" $file 2>&1) || { syntax_error; return 1; }
+			[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a "$file" "$file.bak" && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
+			error=$(sed -Ei "0,/^[[:blank:]#;]*$pattern.*$/s//$setting/" "$file" 2>&1) || { syntax_error; return 1; }
 			G_DIETPI-NOTIFY 0 "Comment in \e[33m$file\e[0m converted to setting: \e[33m${setting_raw//\\/\\\\}\e[0m"
 
 		else
@@ -2020,11 +2001,11 @@ Please retry with more specific parameter \$1 or apply the setting manually:
 
 			if [[ $after ]]; then
 
-				if error=$(grep -Eq "^[[:blank:]]*$after" $file 2>&1); then
+				if error=$(grep -Eq "^[[:blank:]]*$after" "$file" 2>&1); then
 
-					[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
-					error=$(sed -Ei "0,/^[[:blank:]]*$after.*$/s//&\n$setting/" $file 2>&1) || { syntax_error; return 1; }
-					G_DIETPI-NOTIFY 0 "Added setting \e[33m${setting_raw//\\/\\\\}\e[0m to \e[33m$file\e[0m after line \e[33m$(grep -Em1 "^[[:blank:]]*$after" $file | sed 's|\\|\\\\|g')\e[0m"
+					[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a "$file" "$file.bak" && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
+					error=$(sed -Ei "0,/^[[:blank:]]*$after.*$/s//&\n$setting/" "$file" 2>&1) || { syntax_error; return 1; }
+					G_DIETPI-NOTIFY 0 "Added setting \e[33m${setting_raw//\\/\\\\}\e[0m to \e[33m$file\e[0m after line \e[33m$(grep -Em1 "^[[:blank:]]*$after" "$file" | sed 's|\\|\\\\|g')\e[0m"
 
 				else
 					[[ $error ]] && { syntax_error; return 1; }
@@ -2041,10 +2022,10 @@ could not be found in file \$3
 
 			else
 
-				[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
+				[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a "$file" "$file.bak" && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
 				# The following sed does not work on empty files:
-				[[ ! -s $file ]] && echo '# Added by DietPi:' >> $file
-				error=$(sed -Ei "\$a\\$setting" $file 2>&1) || { syntax_error; return 1; }
+				[[ ! -s $file ]] && echo '# Added by DietPi:' >> "$file"
+				error=$(sed -Ei "\$a\\$setting" "$file" 2>&1) || { syntax_error; return 1; }
 				G_DIETPI-NOTIFY 0 "Added setting \e[33m${setting_raw//\\/\\\\}\e[0m to end of file \e[33m$file\e[0m"
 
 			fi
@@ -2056,7 +2037,6 @@ could not be found in file \$3
 	#-----------------------------------------------------------------------------------
 	[[ $G_DEBUG == 1 ]] && G_DIETPI-NOTIFY 2 'DietPi-Globals loaded'
 	#-----------------------------------------------------------------------------------
-	# Return exit code 0, by triggering null as last command to output
-	:
+	: # Return exit code 0, by triggering null as last command to output
 	#-----------------------------------------------------------------------------------
 }
