adjusted example command for formatting and it serves as a test of colors inside custom commands

diff --git a/dietpi/func/dietpi-banner b/dietpi/func/dietpi-banner
--- a/dietpi/func/dietpi-banner
+++ b/dietpi/func/dietpi-banner
@@ -168,7 +168,7 @@
 	BW_INDENT_FIXED=3
 
 	# Default custom command example
-	CUSTOM_COMMANDS[0]='echo -e "${aCOLOUR[RED]}Hello ${aCOLOUR[GREEN]}World! ${COLOUR_RESET} :)"'
+	CUSTOM_COMMANDS[0]='echo -e "$GREEN_BULLET ${aCOLOUR[RED]}Hello ${aCOLOUR[GREEN]}World! ${COLOUR_RESET} :)"'
 	# Default disk patterns
 	SPACE_BASE_PATTERNS=("/" "/mnt/dietpi_userdata")
 
@@ -626,7 +626,7 @@ $GREEN_LINE"
 			cmd="${CUSTOM_COMMANDS[$i]}"
 			if [[ -n "$cmd" ]]; then
 				# shellcheck disable=SC2086
-				echo $(eval "$cmd" 2>&1) || echo -e "${aCOLOUR[RED]}Error executing custom command $((i+1))${COLOUR_RESET}"
+				echo "$(eval "$cmd" 2>&1)" || echo -e "${aCOLOUR[RED]}Error executing custom command $((i+1))${COLOUR_RESET}"
 			fi
 		done
 	}
@@ -823,13 +823,13 @@ $GREEN_LINE"
 
 			if (( $i == 10 ))
 			then
-				example_command='echo -e "${aCOLOUR[RED]}Hello ${aCOLOUR[GREEN]}World! $COLOUR_RESET :)"\n\n-- or with the standard format --\n\nPrint_Item_State "Description" "value"'
+				example_command='echo -e "$GREEN_BULLET ${aCOLOUR[RED]}Hello ${aCOLOUR[GREEN]}World! ${COLOUR_RESET} :)"\n\n-- or with the standard format --\n\nPrint_Item_State "Description" "value"'
 
 				# Manage custom commands list
 				while true; do
 					G_WHIP_MENU_ARRAY=( 'Add' 'Add a new command' 'Edit' 'Edit an existing command' 'Remove' 'Remove a command' 'Done' 'Finish custom commands configuration' )
 					G_WHIP_DEFAULT_ITEM='Done'
-					G_WHIP_MENU 'Manage custom banner commands.\n\nCAUTION!\nThese commands are executed with the same privileges as dietpi-banner :' || break
+					G_WHIP_MENU 'Manage custom banner commands.\n\n!CAUTION!\nThese commands are executed with the same privileges as dietpi-banner, and DO NOT have a time limit :' || break
 					case "$G_WHIP_RETURNED_VALUE" in
 						Add)
 							G_WHIP_INPUTBOX "Enter new command, for example :\n$example_command" || continue
@@ -862,6 +862,7 @@ $GREEN_LINE"
 					esac
 				done
 
+				# If no commands are configured, disable the custom commands option
 				(( ${#CUSTOM_COMMANDS[@]} == 0 )) && aENABLED[10]=0
 
 			elif (( $i == 19 ))
