v6.20
DietPi-Update | Added optional ability to automatically update DietPi, when updates are available. Please note, this is disabled by default.

+ Mask cron until install_stage is 1 (via dietpi-software)

+ optimize 1st run process

+ #DietPi First-Run Stage | -2 = PREP_SYSTEM/Unknown | -1 = first boot | 0 = 1st run dietpi-update | 1 = 1st run dietpi-software | 2 = completed | 10 = Pre-installed image, converts to 2 during 1st boot

+ dietpi-software, move NTPD checks to global (G_CHECK_NTP)

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -55,7 +55,7 @@
 
 	fi
 
-	#DietPi First-Run Stage | -2 = PREP_SYSTEM/Unknown | -1 = first boot | 0 = run dietpi-software at login | 1 = completed | 2 = Pre-installed image, converts to 1 during 1st boot
+	#DietPi First-Run Stage | -2 = PREP_SYSTEM/Unknown | -1 = first boot | 0 = 1st run dietpi-update | 1 = 1st run dietpi-software | 2 = completed | 10 = Pre-installed image, converts to 2 during 1st boot
 	G_DIETPI_INSTALL_STAGE=-2
 	if [[ -r '/DietPi/dietpi/.install_stage' ]]; then
 
@@ -1467,6 +1467,64 @@ $print_logfile_info
 		rm /tmp/G_CHECK_URL
 
 		return $G_ERROR_HANDLER_EXITCODE_RETURN
+
+	}
+
+	#Validate NTP sync, offer options if fail.
+	G_CHECK_NTP(){
+
+		# Timesync
+		until /DietPi/dietpi/func/run_ntpd
+		do
+
+			# - Ask
+			if (( $G_USER_INPUTS )); then
+
+				G_WHIP_MENU_ARRAY=(
+
+					'Retry' ': (Recommended) Rerun network time sync'
+					'NTP mirror' ': Change the NTP mirror used'
+					'NTP mode' ': Change the NTP mode (eg: daemon + drift)'
+					'Override' ': (NOT RECOMMENDED) Ignore failure and override time sync status'
+
+				)
+
+				G_WHIP_MENU 'Network time sync has not yet completed, or, failed to update.\nTo prevent issues with outdated system time during installations, please select an option below.\n
+NB: We highly recommend choosing "Retry" first. Failing that, "NTP mirror" then "NTP mode".\n"Override" is a last resort and may cause follow-up issues due to incorrect system clock time.'
+				if (( ! $? )); then
+
+					if [[ $G_WHIP_RETURNED_VALUE == 'Retry' ]]; then
+
+						killall -w /DietPi/dietpi/func/run_ntpd &> /dev/null # reset
+
+					elif [[ $G_WHIP_RETURNED_VALUE == 'NTP mirror' ]]; then
+
+						G_WHIP_MSG 'DietPi-Config will now be launched, on the next screen:\n - Select "NTP Mirror"\n - Select a different NTP mirror\n\nOnce completed, exit dietpi-config to resume setup'
+						/DietPi/dietpi/dietpi-config 16 1
+
+					elif [[ $G_WHIP_RETURNED_VALUE == 'NTP mode' ]]; then
+
+						G_WHIP_MSG 'DietPi-Config will now be launched, on the next screen:\n - Select "Time sync mode"\n - Select a different time sync mode (eg: Daemon + Drift)\n\nOnce completed, exit dietpi-config to resume setup'
+						/DietPi/dietpi/dietpi-config 3 1
+
+					elif [[ $G_WHIP_RETURNED_VALUE == 'Override' ]]; then
+
+						killall -w /DietPi/dietpi/func/run_ntpd &> /dev/null # reset
+						echo 0 > /DietPi/dietpi/.timesync_exit_status
+						echo 1 > /var/lib/dietpi/.ntpd_override
+
+					fi
+
+				fi
+
+			# - Endless retry
+			else
+
+				killall -w /DietPi/dietpi/func/run_ntpd &> /dev/null # reset
+
+			fi
+
+		done
 
 	}
 
