v6.13
+ DietPi-Globals | Automatically add a trap exit function, to purge existing working dir. Allow custom additional exit commands via declaring G_EXIT_CUSTOM() within the actual script.

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -116,18 +116,36 @@
 	#	eg: stuff we cant init in main globals/funcs due to .bashrc load into current session.
 	G_INIT(){
 
-		# - Set locale for scripts, prevents incorrect scraping
+		# Set locale for scripts, prevents incorrect scraping
 		export LANG=en_GB.UTF-8
 		export LC_ALL=en_GB.UTF-8
 
-		# - HIERARCHY system for G_DIETPI-NOTIFY 3
+		# HIERARCHY system for G_DIETPI-NOTIFY 3
 		[[ $HIERARCHY ]] && export HIERARCHY=$((HIERARCHY+1)) || export HIERARCHY=0
 
-		# - Ensure we are in script working dir or users home dir, if available: https://github.com/Fourdee/DietPi/issues/905#issuecomment-298223705
-		#	- If any $FP_WORK_DIR step fails, go to $HOME if it is assigned
+		# Ensure we are in script working dir or users home dir, if available: https://github.com/Fourdee/DietPi/issues/905#issuecomment-298223705
+		# - If any $FP_WORK_DIR step fails, go to $HOME if it is assigned
 		[[ $FP_WORK_DIR ]] && mkdir -p $FP_WORK_DIR && cd $FP_WORK_DIR || [[ $HOME ]] && cd $HOME
 
-		# - Auto print init header for all scripts
+		# Declare and trap G_EXIT() as exit script, that runs on INT, ERR and usual EXIT signal.
+		G_EXIT(){
+
+			# - Purging working directory
+			if [[ $FP_WORK_DIR && -d $FP_WORK_DIR ]]; then
+
+				# - Failsafe: Navigate incrementally to parent directory, if parent shell pwd is within $FP_WORK_DIR
+				while [[ $(pwd) =~ $FP_WORK_DIR ]]; do cd ..; done
+				rm -R $FP_WORK_DIR
+
+			fi
+
+			# - Execute custom exit commands, if existent
+			declare -F G_EXIT_CUSTOM &> /dev/null && G_EXIT_CUSTOM
+
+		fi
+		trap 'G_EXIT' EXIT
+
+		# Auto print init header for all scripts
 		# G_DIETPI-NOTIFY 3 "$G_PROGRAM_NAME" 'Init'
 
 	}
