v6.22
+ DietPi-RAMlog | Minor coding and wording align with DietPi-RAMdisk

diff --git a/dietpi/func/dietpi-ramlog b/dietpi/func/dietpi-ramlog
--- a/dietpi/func/dietpi-ramlog
+++ b/dietpi/func/dietpi-ramlog
@@ -9,49 +9,50 @@
 	#////////////////////////////////////
 	#
 	# Info:
-	# - Saves /var/log/* atrributes and ownerships during shutdown to $FP_DIETPI_RAMLOG_SAVE
-	# - Restores /var/log/* atrributes and ownerships during boot from $FP_DIETPI_RAMLOG_SAVE
-	# - Uses cp with preserve ownership and attributes only. This generates blank file if required (ramlog) without override existing file data (non-ramlog).
+	# - /var/log is mounted as tmpfs (RAMdisk) before this script runs.
+	# - Saves /var/log/* attributes and ownerships to $FP_STORE during shutdown
+	# - Restores /var/log/* atrributes and ownerships from $FP_STORE during boot
+	# - This allows us to vastly reduce filesystem I/O and increase logging performance
 	#
 	# Usage:
-	# - /DietPi/dietpi/func/dietpi-ramlog 0			= Startup Phase (restores /var/log)
-	# - /DietPi/dietpi/func/dietpi-ramlog 1			= Shutdown Phase (saves /var/log)
+	# - /DietPi/dietpi/func/dietpi-ramlog 0		= Restore from $FP_STORE to /var/log
+	# - /DietPi/dietpi/func/dietpi-ramlog 1		= Store from /var/log to $FP_STORE
 	#////////////////////////////////////
 
 	#-------------------------------------------------------------------------------------
-	#. /DietPi/dietpi/func/dietpi-globals	# Not compatible until dietpi-preboot.service and overkill for the purpose of this script.
-	#export LC_ALL=en_GB.UTF-8		# Not needed, as we do not parse any external command and "date" is allowed to be in user locale format.
-	#cd $HOME				# "cd: HOME not set" error and not needed, since we do not create any tmp files.
+	#. /DietPi/dietpi/func/dietpi-globals	# Not compatible until DietPi-PreBoot has finished and overkill for the purpose of this script.
+	#export LC_ALL=en_GB.UTF-8		# Not required, as we do not parse any external command and "date" is allowed to be in user locale format.
+	#cd $HOME				# Not required, as we do not create any tmp files and produces and: "cd: HOME not set"
 	#-------------------------------------------------------------------------------------
 
-	INPUT=-1 # Use no valid default to prevent accidental removal of storage or recovery of intentionally removed files.
-	[[ $1 =~ ^-?[0-9]+$ ]] && INPUT=$1
+	[[ $1 =~ ^-?[0-9]+$ ]] && INPUT=$1 || INPUT=-1
 
 	EXIT_CODE=0
 
 	PROGRAM_NAME='DietPi-RAMlog'
-	FP_DIETPI_RAMLOG_SAVE='/var/tmp/dietpi/logs/dietpi-ramlog_store'
+	FP_STORE='/var/tmp/dietpi/logs/dietpi-ramlog_store'
 
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Main Loop
 	#/////////////////////////////////////////////////////////////////////////////////////
 
-	# Startup Phase (restore /var/log directory structure and files)
+	# Startup phase: Restore from disk
 	if (( $INPUT == 0 )); then
 
-		echo "$(date) | $PROGRAM_NAME: Startup - Restoring log folder structure to RAMdisk..."
+		echo "$(date) | $PROGRAM_NAME: Restoring logs from disk..."
 
-		if [[ -d $FP_DIETPI_RAMLOG_SAVE ]]; then
+		if [[ -d $FP_STORE ]]; then
 
-			# - Apply previous attributes and ownerships. Generates empty file if it doesnt exist.
-			cp -Rp --attributes-only $FP_DIETPI_RAMLOG_SAVE/. /var/log/
-			EXIT_CODE=$?; if (( $EXIT_CODE )); then
+			# - Restore empty logs with ownership and permissions from disk
+			cp -an --attributes-only $FP_STORE/. /var/log/ || EXIT_CODE=$?
 
-				echo "$(date) | $PROGRAM_NAME: Startup failed with exit code $EXIT_CODE"
+			if (( $EXIT_CODE )); then
+
+				echo "$(date) | $PROGRAM_NAME: [ERROR] Restoring logs from disk failed with exit code: $EXIT_CODE"
 
 			else
 
-				echo "$(date) | $PROGRAM_NAME: Startup completed"
+				echo "$(date) | $PROGRAM_NAME: Restored logs from disk."
 
 			fi
 
@@ -61,39 +62,30 @@
 
 		fi
 
-	# Shutdown Phase (saves /var/log directory structure and filenames)
+	# Shutdown phase: Store to disk
 	elif (( $INPUT == 1 )); then
 
-		echo "$(date) | $PROGRAM_NAME: Shutdown - Saving log folder structure to disk..."
+		echo "$(date) | $PROGRAM_NAME: Storing logs to disk..."
 
-		# - Clear previous storage data
-		if [[ -d $FP_DIETPI_RAMLOG_SAVE ]]; then
+		# - Assure empty $FP_STORE
+		[[ -d $FP_STORE ]] && rm -Rf $FP_STORE/{,.??,.[^.]}* || mkdir -p $FP_STORE || EXIT_CODE=$?
 
-			rm -Rf $FP_DIETPI_RAMLOG_SAVE/{,.??,.[^.]}*
+		# - Store empty logs with ownership and permissions to disk
+		cp -af --attributes-only /var/log/. $FP_STORE/ || EXIT_CODE=$?
 
-		# - Create dir
-		else
+		if (( $EXIT_CODE )); then
 
-			mkdir -p $FP_DIETPI_RAMLOG_SAVE
-
-		fi
-
-		# - Copy logfile attributes and ownership to storage (not file contents)
-		cp -Rp --attributes-only /var/log/. $FP_DIETPI_RAMLOG_SAVE/
-		EXIT_CODE=$?; if (( $EXIT_CODE )); then
-
-			echo "$(date) | $PROGRAM_NAME: Shutdown failed with exit code $EXIT_CODE"
+			echo "$(date) | $PROGRAM_NAME: [ERROR] Storing logs to disk failed with exit code: $EXIT_CODE"
 
 		else
 
-			echo "$(date) | $PROGRAM_NAME: Shutdown completed"
+			echo "$(date) | $PROGRAM_NAME: Stored logs to disk."
 
 		fi
 
-	# Unknown argument
 	else
 
-		echo "$(date) | $PROGRAM_NAME: Unknown argument: $INPUT. Aborting..."
+		echo "$(date) | $PROGRAM_NAME: [ERROR] Unknown argument: $INPUT. Aborting..."
 		EXIT_CODE=1
 
 	fi
