v8.14
- DietPi-Globals | G_CHECK_NET: When hitting "Retry" from the error handler, the IPv6 connection check is now skipped as well when IPv6 is disabled via dietpi-config network settings or manually. The same is true for changes to the CONFIG_CHECK_CONNECTION/DOMAIN dietpi.txt settings. Many thanks to @derSebastian for reporting a related issue: https://github.com/MichaIng/DietPi/issues/5667

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -830,14 +830,17 @@ $grey─────────────────────────
 	# - $G_EXEC_ARRAY_ACTION[]	| Associative array, containing uneven $G_EXEC_ARRAY_TEXT[] values as keys and related commands as values
 	G_EXEC(){
 
-		local exit_code fp_log='/tmp/G_EXEC_LOG' attempt=1 acommand=("$@") ecommand=${*//\\/\\\\}
+		local exit_code fp_log='/tmp/G_EXEC_LOG' attempt=1 acommand=("$@") ecommand
 
 		# Enter retry loop
 		while :
 		do
 			declare -F G_EXEC_PRE_FUNC &> /dev/null && G_EXEC_PRE_FUNC
+			# Exit immediately if exit_code=0 was set by G_EXEC_PRE_FUNC
+			[[ $exit_code == 0 ]] && break
 
 			# Execute command, store output to $fp_log file and store exit code to $exit_code variable
+			ecommand=${acommand[@]//\\/\\\\}
 			# - Print full command output if $G_EXEC_OUTPUT=1 is given
 			if [[ $G_EXEC_OUTPUT == 1 ]]; then
 
@@ -901,7 +904,7 @@ $grey─────────────────────────
 - Hardware       | $G_HW_MODEL_NAME (ID=$G_HW_MODEL)
 - Kernel version | \`$(uname -a)\`
 - Distro         | $G_DISTRO_NAME (ID=$G_DISTRO${G_RASPBIAN:+,RASPBIAN=$G_RASPBIAN})
-- Command        | \`$*\`
+- Command        | \`${acommand[@]}\`
 - Exit code      | $exit_code
 - Software title | $G_PROGRAM_NAME
 #### Steps to reproduce:
@@ -940,7 +943,7 @@ $log_content
 				# Show "Ignore" on cancel button if $G_EXEC_NOEXIT=1 is given, else "Exit"
 				[[ $G_EXEC_NOEXIT == 1 ]] && G_WHIP_BUTTON_CANCEL_TEXT='Ignore' || G_WHIP_BUTTON_CANCEL_TEXT='Exit'
 				G_WHIP_DEFAULT_ITEM=${last_whip_menu_item:-Retry}
-				G_WHIP_MENU "${G_EXEC_DESC:+$(mawk '{gsub("\\\e[[0-9][;0-9]*m","");print}' <<< "$G_EXEC_DESC")\n} - Command: $*
+				G_WHIP_MENU "${G_EXEC_DESC:+$(mawk '{gsub("\\\e[[0-9][;0-9]*m","");print}' <<< "$G_EXEC_DESC")\n} - Command: ${acommand[@]}
  - Exit code: $exit_code
  - DietPi version: $dietpi_version | HW_MODEL: $G_HW_MODEL | HW_ARCH: $G_HW_ARCH | DISTRO: $G_DISTRO
 ${image_creator:+ - Image creator: $image_creator\n}${preimage_name:+ - Pre-image: $preimage_name\n} - Error log:
@@ -977,7 +980,7 @@ Press any key to continue...'
 
 				elif [[ $G_WHIP_RETURNED_VALUE == 'Change command' ]]; then
 
-					G_WHIP_DEFAULT_ITEM=$*
+					G_WHIP_DEFAULT_ITEM=${acommand[@]}
 					if G_WHIP_INPUTBOX 'Please enter/alter the command to be executed.
 \nNB: Please only use this solution if you know for sure that it will not cause follow up issues from the originating script. It will e.g. allow you to continue a certain software install, but if you edit the download link, the originating script might expect files which are not present.
 \nUse this work caution!'; then
@@ -1112,6 +1115,9 @@ Press any key to continue...'
 	# - Uses CONFIG_G_CHECK_URL_TIMEOUT + CONFIG_G_CHECK_URL_ATTEMPTS from dietpi.txt, else defaults to 10 seconds and 2 attempts (1 retry).
 	G_CHECK_NET()
 	{
+		# Store original G_EXEC_PRE_FUNC if any was passed
+		declare -F G_EXEC_PRE_FUNC &> /dev/null && eval "G_EXEC_PRE_FUNC_ORIG()$(declare -f G_EXEC_PRE_FUNC | tail +2)"
+
 		# Obtain timeout
 		local timeout=$(sed -n '/^[[:blank:]]*CONFIG_G_CHECK_URL_TIMEOUT=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
 		disable_error=1 G_CHECK_VALIDINT "$timeout" 0 || timeout=10
@@ -1121,11 +1127,8 @@ Press any key to continue...'
 		disable_error=1 G_CHECK_VALIDINT "$attempts" 1 || attempts=2
 		local retries=$(( $attempts - 1 )) # 2 attempts = 1 retry
 
-		# Obtain IPv4 test address
-		local ip=$(sed -n '/^[[:blank:]]*CONFIG_CHECK_CONNECTION_IP=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
-		[[ $ip ]] || ip='9.9.9.9'
-
-		# Check IPv4 connectivity
+		### Check IPv4 connectivity ###
+		# Add special options to the error handler menu
 		G_EXEC_ARRAY_TEXT=(
 
 			'Double timeout' ': Retry with doubled timeout for ping to wait for a reply'
@@ -1136,42 +1139,59 @@ Press any key to continue...'
 			['Double timeout']='((acommand[4]*=2)); attempt=1; continue 2'
 			['Network settings']='/boot/dietpi/dietpi-config 8 1'
 		)
+		# Obtain IPv4 test address on every retry
+		G_EXEC_PRE_FUNC()
+		{
+			declare -F G_EXEC_PRE_FUNC_ORIG &> /dev/null && G_EXEC_PRE_FUNC_ORIG
+			acommand[5]=$(sed -n '/^[[:blank:]]*CONFIG_CHECK_CONNECTION_IP=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
+			[[ ${acommand[5]} ]] || acommand[5]='9.9.9.9'
+		}
+		# Run check with given timeout and retries
 		G_EXEC_RETRIES=$retries
-		G_EXEC_DESC='Checking IPv4 network connectivity' G_EXEC ping -4nc 1 -W "$timeout" "$ip"
+		G_EXEC_DESC='Checking IPv4 network connectivity' G_EXEC ping -4nc 1 -W "$timeout" 'IP'
 
-		# Do IPv6 connectivity check if an IPv6 default route is assigned
-		if G_GET_NET -6 -q gateway > /dev/null
-		then
-			# Obtain IPv6 test address
-			local ip=$(sed -n '/^[[:blank:]]*CONFIG_CHECK_CONNECTION_IPV6=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
-			[[ $ip ]] || ip='2620:fe::fe'
+		### Check IPv6 connectivity ###
+		# Add special options to the error handler menu
+		G_EXEC_ARRAY_TEXT=(
 
-			# Check IPv6 connectivity
-			G_EXEC_ARRAY_TEXT=(
+			'Double timeout' ': Retry with doubled timeout for ping to wait for a reply'
+			'Disable IPv6' ': Disable IPv6 on your system and continue'
+			'Network settings' ': Enter dietpi-config network options'
+		)
+		declare -A G_EXEC_ARRAY_ACTION=(
 
-				'Double timeout' ': Retry with doubled timeout for ping to wait for a reply'
-				'Disable IPv6' ': Disable IPv6 on your system and continue'
-				'Network settings' ': Enter dietpi-config network options'
-			)
-			declare -A G_EXEC_ARRAY_ACTION=(
+			['Double timeout']='((acommand[4]*=2)); attempt=1; continue 2'
+			['Disable IPv6']='/boot/dietpi/func/dietpi-set_hardware enableipv6 0; acommand=(:); attempt=1; continue 2'
+			['Network settings']='/boot/dietpi/dietpi-config 8 1'
+		)
+		# Exit error handler loop if no IPv6 default route is assigned, otherwise obtain IPv6 test address on every retry
+		G_EXEC_PRE_FUNC()
+		{
+			declare -F G_EXEC_PRE_FUNC_ORIG &> /dev/null && G_EXEC_PRE_FUNC_ORIG
+			G_GET_NET -6 -q gateway > /dev/null || { exit_code=0; return 0; }
+			acommand[5]=$(sed -n '/^[[:blank:]]*CONFIG_CHECK_CONNECTION_IPV6=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
+			[[ ${acommand[5]} ]] || acommand[5]='2620:fe::fe'
+		}
+		# Run check with given timeout and retries
+		G_EXEC_RETRIES=$retries
+		G_EXEC_DESC='Checking IPv6 network connectivity' G_EXEC ping -6nc 1 -W "$timeout" 'IP'
 
-				['Double timeout']='((acommand[4]*=2)); attempt=1; continue 2'
-				['Disable IPv6']='/boot/dietpi/func/dietpi-set_hardware enableipv6 0; acommand=(:); attempt=1; continue 2'
-				['Network settings']='/boot/dietpi/dietpi-config 8 1'
-			)
-			G_EXEC_RETRIES=$retries
-			G_EXEC_DESC='Checking IPv6 network connectivity' G_EXEC ping -6nc 1 -W "$timeout" "$ip"
-		fi
-
-		# Obtain test domain
-		local domain=$(sed -n '/^[[:blank:]]*CONFIG_CHECK_DNS_DOMAIN=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
-		[[ $domain ]] || domain='dns9.quad9.net'
-
-		# Check DNS resolver
+		### Check DNS resolver ###
+		# Add special options to the error handler menu
 		G_EXEC_ARRAY_TEXT=('Network settings' ': Enter dietpi-config network options')
 		declare -A G_EXEC_ARRAY_ACTION=(['Network settings']='/boot/dietpi/dietpi-config 8 1')
+		# Obtain test domain on every retry
+		G_EXEC_PRE_FUNC()
+		{
+			declare -F G_EXEC_PRE_FUNC_ORIG &> /dev/null && G_EXEC_PRE_FUNC_ORIG
+			acommand[2]=$(sed -n '/^[[:blank:]]*CONFIG_CHECK_DNS_DOMAIN=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
+			[[ ${acommand[2]} ]] || acommand[2]='dns9.quad9.net'
+		}
+		# Run check with given retries
 		G_EXEC_RETRIES=$retries
-		G_EXEC_DESC='Checking DNS resolver' G_EXEC getent hosts "$domain"
+		G_EXEC_DESC='Checking DNS resolver' G_EXEC getent hosts 'DOMAIN'
+
+		unset -f G_EXEC_PRE_FUNC_ORIG
 	}
 
 	# URL connection test
@@ -1460,11 +1480,11 @@ Press any key to continue...'
 		declare -F G_EXEC_PRE_FUNC &> /dev/null && eval "G_EXEC_PRE_FUNC_ORIG()$(declare -f G_EXEC_PRE_FUNC | tail +2)"
 		G_EXEC_PRE_FUNC()
 		{
+			declare -F G_EXEC_PRE_FUNC_ORIG &> /dev/null && G_EXEC_PRE_FUNC_ORIG
 			local apackages=()
 			mapfile -t apackages < <(dpkg --get-selections "${acommand[@]:4}" 2> /dev/null | mawk '{print $1}')
 			# shellcheck disable=SC2015
 			[[ ${apackages[0]} ]] && acommand=("${acommand[@]::4}" "${apackages[@]}") || acommand=(G_DIETPI-NOTIFY 2 'None of the packages are currently installed. Aborting...')
-			declare -F G_EXEC_PRE_FUNC_ORIG &> /dev/null && G_EXEC_PRE_FUNC_ORIG
 		}
 
 		G_EXEC_DESC="\e[0mAPT purge \e[33m$*\e[0m"
@@ -1509,7 +1529,7 @@ Press any key to continue...'
 
 		# Clean cache before every update, which can corrupt and gets fully rewritten anyway
 		declare -F G_EXEC_PRE_FUNC &> /dev/null && eval "G_EXEC_PRE_FUNC_ORIG()$(declare -f G_EXEC_PRE_FUNC | tail +2)"
-		G_EXEC_PRE_FUNC(){ apt-get clean; declare -F G_EXEC_PRE_FUNC_ORIG &> /dev/null && G_EXEC_PRE_FUNC_ORIG; }
+		G_EXEC_PRE_FUNC(){ declare -F G_EXEC_PRE_FUNC_ORIG &> /dev/null && G_EXEC_PRE_FUNC_ORIG; apt-get clean; }
 
 		# Fail when some index files couldn't be downloaded, e.g. due to DNS failure. By default, apt-get update prints a warning but does not return an error code.
 		local eany=()
