v6.26
+ DietPi-Globals | G_DIETPI-NOTIFY -2: When calculating output lines, include $G_PROGRAM_NAME prefix if set
+ DietPi-Globals | G_DISTRO_NAME: Add initial Debian Bullseye recognition. Needs to be defined in DietPi-Obtain_HW_model as well!
+ DietPi-Globals | G_ERROR_HANDLER: Do not pre-declare any $G_ERROR_HANDLER_* variables to reduce variable count in shell sessions. Check those via [[ ]] against non-default value being set.
+ DietPi-Globals | Minor coding and wording

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -23,15 +23,17 @@
 	unset G_PROGRAM_NAME
 
 	# Debug mode
-	# - Do no pre-generate to reduce bash session variables: Needs to be checked via: [[ $G_DEBUG == 1 ]]
+	# - Do no pre-generate to reduce bash session variables => Needs to be checked via: [[ $G_DEBUG == 1 ]]
 	#G_DEBUG=${G_DEBUG:-0}
 
-	# Flag, if we are in interactive shell, by checking STDIN availability
-	#	OK | systemd	= non-STDIN
-	#	OK | Cron	= non-STDIN
-	#	NB | ~/.bashrc	= STDIN
+	# Interactive mode
 	# - Affects whether G_ERROR_ and G_WHIP_ prompts are displayed or not
-	#	NB: You can export G_USER_INPUTS=0 to force non-interactive/automated scipt calls. Run 'unset G_USER_INPUTS' afterwards to return to auto detection.
+	# - Run "export G_USER_INPUTS=0" prior to script call to force non-interactive/automated mode.
+	# - Run "unset G_USER_INPUTS" afterwards to return to auto detection.
+	# - If not set, check for STDIN availability:
+	#	OK | systemd	= no STDIN
+	#	OK | Cron	= no STDIN
+	#	NB | /etc/profile, ~/.profile, /etc/profile.d/, /etc/bash.bashrc, ~/.bashrc and /etc/bashrc.d/ can all be interactive since those are sourced from originating shell/bash session.
 	if [[ $G_USER_INPUTS != [01] ]]; then
 
 		[[ -t 0 ]] && G_USER_INPUTS=1 || G_USER_INPUTS=0
@@ -41,7 +43,7 @@
 	# DietPi First-Run Stage | -2 = PREP_SYSTEM/Unknown | -1 = 1st boot | 0 = 1st run dietpi-update | 1 = 1st run dietpi-software | 2 = completed | 10 = Pre-installed image, converts to 2 during 1st boot
 	[[ -f '/DietPi/dietpi/.install_stage' ]] && G_DIETPI_INSTALL_STAGE=$(</DietPi/dietpi/.install_stage) || G_DIETPI_INSTALL_STAGE=-2
 
-	# DietPi Versions/Branch
+	# DietPi version and Git branch
 	G_DIETPI_VERSION_CORE=${G_DIETPI_VERSION_CORE:-6}
 	G_DIETPI_VERSION_SUB=${G_DIETPI_VERSION_SUB:-26}
 	G_DIETPI_VERSION_RC=${G_DIETPI_VERSION_RC:-0}
@@ -67,7 +69,7 @@ _EOF_
 	G_FP_DIETPI_USERDATA='/mnt/dietpi_userdata'
 
 	# Allows to disable dietpi-services handling, e.g. if already handled within parent script.
-	# - Do no pre-generate to reduce bash session variables: Needs to be checked via: [[ $G_DIETPI_SERVICES_DISABLE == 1 ]]
+	# - Do no pre-generate to reduce bash session variables => Needs to be checked via: [[ $G_DIETPI_SERVICES_DISABLE == 1 ]]
 	#G_DIETPI_SERVICES_DISABLE=${G_DIETPI_SERVICES_DISABLE:-0}
 
 	# Device details
@@ -100,15 +102,19 @@ _EOF_
 
 			G_DISTRO_NAME='buster'
 
+		elif (( $G_DISTRO == 6 )); then
+
+			G_DISTRO_NAME='bullseye'
+
 		fi
 
 	fi
 
-	# INIT functions for originating script
-	# - Stuff we can't init in main globals/funcs due to /etc/bashrc.d/ load into current session.
+	# Init functions for originating script
+	# - Stuff we can't init in main globals/funcs due to /etc/bashrc.d/ load into login session.
 	# - Optional input variables:
-	#	G_INIT_ALLOW_CONCURRENT=1	=> Allow concurrent DietPi script execution (default: 0)
-	#	G_INIT_WAIT_CONCURRENT=<int>	=> Max time to wait for concurrent execution to exit before user prompt (default: 5)
+	#	G_INIT_ALLOW_CONCURRENT=1	= Allow concurrent DietPi script execution (default: 0)
+	#	G_INIT_WAIT_CONCURRENT=<int>	= Max time to wait for concurrent execution to exit before user prompt (default: 5)
 	G_INIT(){
 
 		# Set G_PROGRAM_NAME to originating command if it was not set by originating script
@@ -155,13 +161,13 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 		fi
 
-		# HIERARCHY system for G_DIETPI-NOTIFY 3
+		# HIERARCHY system for G_DIETPI-NOTIFY 3 to reduce highlight or sub script output
 		disable_error=1 G_CHECK_VALIDINT "$HIERARCHY" 0 && export HIERARCHY=$((HIERARCHY+1)) || export HIERARCHY=0
 
 		# Set locale for scripts to prevent incorrect scraping due to translated command outputs
 		export LC_ALL='en_GB.UTF-8'
 
-		# Declare and trap G_EXIT() as exit function, that runs on EXIT signal, which includes INT (error) and TERM (kill)
+		# Declare exit trap, that runs on EXIT signal, which includes INT (interruption) and TERM (kill)
 		G_EXIT(){
 
 			# - Navigate to /tmp, if we are inside working dir, which is about to be removed
@@ -171,7 +177,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 			else
 
-				[[ $G_DEBUG == 1 ]] && G_DIETPI-NOTIFY 2 "Failed to navigate to /tmp"
+				[[ $G_DEBUG == 1 ]] && G_DIETPI-NOTIFY 2 'Failed to navigate to /tmp'
 
 			fi
 
@@ -343,7 +349,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 				}
 
 				# Calculate the amount of output lines and in case move cursor up for correct animation and to allow cleaning the whole output.
-				local input_string=$(mawk '{gsub("\\\e[[0-9][;0-9]*m","");print}' <<< "$*") # Remove colour codes
+				local input_string=$(mawk '{gsub("\\\e[[0-9][;0-9]*m","");print}' <<< "${G_PROGRAM_NAME+$G_PROGRAM_NAME | }$*") # Remove colour codes
 				local screen_width=${G_WHIP_SIZE_X_OVERRIDE:-$(tput cols)} # Use override value in case STDOUT + STDERR are redirected
 				local output_lines=$(( ( ${#input_string} + 5 ) / $screen_width )) # +5 = [ .... ] - $1
 				(( $output_lines )) && echo -ne "\e[${output_lines}A"
@@ -398,7 +404,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 		elif (( $1 == 3 )); then
 
 			Clean_Process_Animation
-			if disable_error=1 G_CHECK_VALIDINT $HIERARCHY && (( $HIERARCHY > 0 )); then
+			if disable_error=1 G_CHECK_VALIDINT "$HIERARCHY" 1; then
 
 				local status_subfunction="$HIERARCHY "
 				# > 9 should never occur, however, if it is, lets make it line up regardless
@@ -451,7 +457,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 			else
 
 				export G_CHECK_ROOT_USER_VERIFIED=1
-				G_DIETPI-NOTIFY 0 'Root access verified.'
+				G_DIETPI-NOTIFY 0 'Root access verified'
 
 			fi
 
@@ -472,7 +478,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 			else
 
 				export G_CHECK_ROOTFS_RW_VERIFIED=1
-				G_DIETPI-NOTIFY 0 'RootFS R/W access verified.'
+				G_DIETPI-NOTIFY 0 'RootFS R/W access verified'
 
 			fi
 
@@ -484,13 +490,13 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 	# Alias defines
 	#-----------------------------------------------------------------------------------
 	# DietPi scripts, moved from /etc/bash.bashrc
-	# - sudo command that ensures DietPi-Globals with G_* commands are loaded
+	# - sudo wrapper that ensures DietPi-Globals with G_* commands are loaded
 	G_SUDO(){ local input=$@; sudo bash -c ". /DietPi/dietpi/func/dietpi-globals && $input"; }
-	# - sudo alias that allows running other aliases with "sudo"
-	alias sudo='sudo ' # https://github.com/MichaIng/DietPi/issues/424
+	# - sudo alias that allows running other aliases with "sudo": https://github.com/MichaIng/DietPi/issues/424
+	alias sudo='sudo '
 
 	# - DietPi programs
-	alias dietpi-process_tool='/DietPi/dietpi/dietpi-services' #Leave this in for few versions for end users, due to switchover to dietpi-services
+	alias dietpi-process_tool='/DietPi/dietpi/dietpi-services' # Leave this in for few versions for end users, due to switchover to dietpi-services
 	alias dietpi-letsencrypt='/DietPi/dietpi/dietpi-letsencrypt'
 	alias dietpi-autostart='/DietPi/dietpi/dietpi-autostart'
 	alias dietpi-cron='/DietPi/dietpi/dietpi-cron'
@@ -515,9 +521,6 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 	# - 1337 moments ;)
 	alias 1337='echo Indeed, you are =\)'
-
-	# - Helpers
-	#alias dd='dd status=progress ' # needs to be at end...
 
 	# - Optional DietPi software aliases/functions
 	[[ -d '/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn' ]] && alias dietpi-nordvpn='/DietPi/dietpi/misc/dietpi-nordvpn'
@@ -1004,47 +1007,35 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 	# DietPi Error Handler
 	# https://github.com/MichaIng/DietPi/issues/1311#issuecomment-353716344
 	#-----------------------------------------------------------------------------------
-	G_ERROR_HANDLER_EXITCODE=0		# input value to use with G_ERROR_HANDLER
-	G_ERROR_HANDLER_EXITCODE_RETURN=0	# Same as above, but not destroyed during G_ERROR_HANDLER_RESET, allowing us to return it in funcs
-	G_ERROR_HANDLER_COMMAND=''		# eg: G_AGI: moooooooo
-	#	For export: On error, following entries will be used
-	G_ERROR_HANDLER_NO_FAIL=0		# Always report a success, regardless of the exit code | G_USER_INPUTS=0 is not required for this
-	G_ERROR_HANDLER_INFO_ONLY=0		# Only print info and retry options, no exit or bug report, sets G_ERROR_HANDLER_ONERROR_EXIT=0 automatically
-	G_ERROR_HANDLER_ONERROR_EXIT=1		# Do we exit the program when the error occurs? 0=no 1=yes
-	G_ERROR_HANDLER_ONERROR_FPLOGFILE=''	# FP to logfile, if available
-	G_ERROR_HANDLER_RETRY=0			# Used in func with while loop to re-run func as needed
+	# Required input:
+	# - G_ERROR_HANDLER_COMMAND=<cmd>		| Command name for print out
+	# - G_ERROR_HANDLER_EXITCODE=<int>		| Commands exit code
+	# Optional input:
+	# - G_ERROR_HANDLER_NO_FAIL=1			| Always report a success, regardless of the exit code | G_USER_INPUTS=0 is not required for this
+	# - G_ERROR_HANDLER_INFO_ONLY=1			| Only print info and retry options, no exit or bug report, sets G_ERROR_HANDLER_ONERROR_EXIT=0 automatically
+	# - G_ERROR_HANDLER_ONERROR_EXIT=0		| Do not exit the script on error
+	# - G_ERROR_HANDLER_RETRY=1			| Allow to retry the command. Requires loop in originating script!
+	# - G_ERROR_HANDLER_ONERROR_FPLOGFILE=<path>	| File path to commands logfile, if available
+	# - l_message					| Alternative text to print on success, less cryptic for end user
+	# Output:
+	# - G_ERROR_HANDLER_EXITCODE_RETURN=<int>	| Contains $G_ERROR_HANDLER_EXITCODE, but is not destroyed during G_ERROR_HANDLER_RESET(), allowing us to call afterwards
 
 	# Runs automatically after G_ERROR_HANDLER to reset vars to default
 	G_ERROR_HANDLER_RESET(){
 
 		G_ERROR_HANDLER_EXITCODE_RETURN=$G_ERROR_HANDLER_EXITCODE
 
-		# Delete if used:
+		# Delete logfile if used
 		[[ $G_ERROR_HANDLER_ONERROR_FPLOGFILE && -f $G_ERROR_HANDLER_ONERROR_FPLOGFILE ]] && rm $G_ERROR_HANDLER_ONERROR_FPLOGFILE
 
-		# unset originating program
-		unset G_ERROR_HANDLER_EXITCODE
-		unset G_ERROR_HANDLER_COMMAND
-
-		unset G_ERROR_HANDLER_NO_FAIL
-		unset G_ERROR_HANDLER_INFO_ONLY
-		unset G_ERROR_HANDLER_ONERROR_EXIT
-		unset G_ERROR_HANDLER_ONERROR_FPLOGFILE
-		unset G_ERROR_HANDLER_RETRY
-
-		G_ERROR_HANDLER_EXITCODE=0
-		G_ERROR_HANDLER_COMMAND=''
-
-		G_ERROR_HANDLER_NO_FAIL=0
-		G_ERROR_HANDLER_INFO_ONLY=0
-		G_ERROR_HANDLER_ONERROR_EXIT=1
-		G_ERROR_HANDLER_ONERROR_FPLOGFILE=''
-		G_ERROR_HANDLER_RETRY=0
+		# Clear variables
+		unset G_ERROR_HANDLER_COMMAND G_ERROR_HANDLER_EXITCODE
+		unset G_ERROR_HANDLER_NO_FAIL G_ERROR_HANDLER_INFO_ONLY G_ERROR_HANDLER_ONERROR_EXIT
+		unset G_ERROR_HANDLER_RETRY G_ERROR_HANDLER_ONERROR_FPLOGFILE l_message
 
 	}
 
-	# Handles exit code errors, as defined by G_ERROR_HANDLER_xxxx settings
-	#	Usage: G_RUN_CMD dothis
+	# Handles exit code errors, as defined by G_ERROR_HANDLER_* settings
 	G_ERROR_HANDLER(){
 
 		[[ $l_message ]] || local l_message=$G_ERROR_HANDLER_COMMAND
@@ -1059,20 +1050,14 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 		# Error
 		else
 
+			(( $G_ERROR_HANDLER_INFO_ONLY )) && G_ERROR_HANDLER_ONERROR_EXIT=0
+
 			local send_bugreport=0
 			local bugreport_id='N/A'
-
-			if (( $G_ERROR_HANDLER_INFO_ONLY )); then
-
-				G_ERROR_HANDLER_ONERROR_EXIT=0
-
-			fi
-
 			local version_info="v$G_DIETPI_VERSION_CORE.$G_DIETPI_VERSION_SUB.$G_DIETPI_VERSION_RC ($G_GITOWNER/$G_GITBRANCH)"
-
 			local print_hw_info="DietPi version: $version_info | HW_MODEL:$G_HW_MODEL | HW_ARCH:$G_HW_ARCH | DISTRO:$G_DISTRO"
-			local image_creator='n/a'
-			local preimage_name='n/a'
+			local image_creator='N/A'
+			local preimage_name='N/A'
 			if [[ -r '/DietPi/dietpi/.prep_info' ]]; then
 
 				image_creator=$(mawk 'NR==1 {print}' /DietPi/dietpi/.prep_info)
@@ -1081,83 +1066,54 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 			fi
 
-			local print_logfile_info="Log file contents:\n$(tail -50 $G_ERROR_HANDLER_ONERROR_FPLOGFILE)"
-			local print_report_to_dietpi_info='If problems persist, please report this to DietPi for investigation'
+			local logfile_content='N/A'
+			[[ $G_ERROR_HANDLER_ONERROR_FPLOGFILE ]] && logfile_content=$(tail -50 $G_ERROR_HANDLER_ONERROR_FPLOGFILE)
+			local print_report_to_dietpi_info='If problems persist, please report at https://github.com/MichaIng/DietPi/issues for investigation.'
 			local print_unable_to_continue="Unable to continue, $G_PROGRAM_NAME will now terminate."
 
 			G_DIETPI-NOTIFY 1 "$G_ERROR_HANDLER_COMMAND"
 
-			#	Display "please report to dietpi", if its one of our programs
-			if [[ $G_PROGRAM_NAME && ! $G_ERROR_HANDLER_INFO_ONLY ]]; then
+			# Display "please report to dietpi", if it's one of our programs
+			[[ $G_PROGRAM_NAME && $G_ERROR_HANDLER_INFO_ONLY != 1 ]] && G_DIETPI-NOTIFY 2 "$print_report_to_dietpi_info"
 
-				G_DIETPI-NOTIFY 2 "$print_report_to_dietpi_info"
-
-			fi
-
-			# - On Error: Display whip version?
+			# If interactive, prompt whip message
 			if (( $G_USER_INPUTS )); then
 
-				local whip_msg=()
-				if [[ $G_PROGRAM_NAME ]]; then
+				local whip_msg="${G_PROGRAM_NAME+$G_PROGRAM_NAME: }$G_ERROR_HANDLER_COMMAND
+ - Exit code: $G_ERROR_HANDLER_EXITCODE
+ - $print_hw_info
+ - Image creator: $image_creator
+ - Pre-image: $preimage_name"
 
-					whip_msg+="$G_PROGRAM_NAME: $G_ERROR_HANDLER_COMMAND"
+				# Display logfile if available
+				[[ $G_ERROR_HANDLER_ONERROR_FPLOGFILE ]] && whip_msg+="\n\nLog file content:\n$logfile_content"
 
-				else
+				# Display "please report to dietpi", if its one of our programs
+				[[ $G_PROGRAM_NAME && $G_ERROR_HANDLER_INFO_ONLY != 1 ]] && whip_msg+="\n\n$print_report_to_dietpi_info"
 
-					whip_msg+=$G_ERROR_HANDLER_COMMAND
-
-				fi
-
-				whip_msg+="\n - Exit code: $G_ERROR_HANDLER_EXITCODE"
-				whip_msg+="\n - $print_hw_info"
-				whip_msg+="\n - Image creator: $image_creator"
-				whip_msg+="\n - Pre-image: $preimage_name"
-				whip_msg+='\n\n'
-
-				#	Display optional logfile?
-				if [[ $G_ERROR_HANDLER_ONERROR_FPLOGFILE ]]; then
-
-					whip_msg+=$print_logfile_info
-					whip_msg+='\n\n'
-
-				fi
-
-				#	Display "please report to dietpi", if its one of our programs
-				if [[ $G_PROGRAM_NAME && ! $G_ERROR_HANDLER_INFO_ONLY ]]; then
-
-					whip_msg+=$print_report_to_dietpi_info
-
-				fi
-
-				if (( $G_ERROR_HANDLER_ONERROR_EXIT )); then
-
-					whip_msg+='\n\n'
-					whip_msg+=$print_unable_to_continue
-
-				fi
+				[[ $G_ERROR_HANDLER_ONERROR_EXIT != 0 ]] && whip_msg+="\n\n$print_unable_to_continue"
 
 				if (( $G_ERROR_HANDLER_RETRY )); then
 
 					G_ERROR_HANDLER_RETRY=0
 
-					local aretry_menu_options=()
-					local retry_menu_options_count=0
-					aretry_menu_options+=('Retry' ': Re-run the last command that failed'); ((retry_menu_options_count++))
+					local aretry_menu_options=('Retry' ': Re-run the last command that failed')
+					local retry_menu_options_count=1
 
-					if ! ps aux | grep -qi '[d]ietpi-config' && (( ! $G_ERROR_HANDLER_INFO_ONLY )); then
+					if ! pgrep -cf 'dietpi-config' &> /dev/null && [[ $G_ERROR_HANDLER_INFO_ONLY != 1 ]]; then
 
 						aretry_menu_options+=('DietPi-Config' ': Edit network, APT/NTP mirror settings etc'); ((retry_menu_options_count++))
 
 					fi
 
-					if [[ $G_PROGRAM_NAME && ! $G_ERROR_HANDLER_INFO_ONLY ]]; then
+					if [[ $G_PROGRAM_NAME && $G_ERROR_HANDLER_INFO_ONLY != 1 ]]; then
 
 						aretry_menu_options+=('Send report' ': Uploads bugreport containing system info to DietPi'); ((retry_menu_options_count++))
 
 					fi
 
-					local no_button_text='Ignore'
-					(( $G_ERROR_HANDLER_ONERROR_EXIT )) && no_button_text='Exit'
+					local no_button_text='Exit'
+					[[ $G_ERROR_HANDLER_ONERROR_EXIT == 0 ]] && no_button_text='Ignore'
 
 					local choice=$(whiptail --title 'DietPi Error Handler:' --menu "$whip_msg" --cancel-button "$no_button_text" --scrolltext 24 90 $retry_menu_options_count "${aretry_menu_options[@]}" 3>&1 1>&2 2>&3)
 					if (( $? == 0 )); then
@@ -1180,15 +1136,13 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 					fi
 
-					unset aretry_menu_options
-
 				else
 
 					whiptail --title 'DietPi Error Handler:' --msgbox "$whip_msg" --scrolltext 22 85
 
 				fi
 
-			# - No user inputs, disable retry
+			# If non-interactive, never retry
 			else
 
 				G_ERROR_HANDLER_RETRY=0
@@ -1196,25 +1150,25 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 			fi
 
 			# GitHub printout
-			if (( ! $G_ERROR_HANDLER_INFO_ONLY )); then
+			if [[ $G_ERROR_HANDLER_INFO_ONLY != 1 ]]; then
 
 				echo -e "
 \e[41m
---------------------------------------------------------------------
-- DietPi has encounted an error, and, is unable to continue        -
+---------------------------------------------------------------------
+- DietPi has encounted an error, and, is unable to continue         -
 - Please create a ticket: https://github.com/MichaIng/DietPi/issues -
-- Copy and paste the BLUE lines below, into the ticket             -
---------------------------------------------------------------------
+- Copy and paste the BLUE lines below, into the ticket              -
+---------------------------------------------------------------------
 \e[0m
 \e[44m
 #### Details:
 - Date           | $(date)
 - Bug report     | $bugreport_id
 - DietPi version | $version_info
-- Img creator    | $image_creator
+- Image creator  | $image_creator
 - Pre-image      | $preimage_name
 - SBC device     | $G_HW_MODEL_DESCRIPTION (index=$G_HW_MODEL)
-- Kernel version | $(uname -v)
+- Kernel version | $(uname -a)
 - Distro         | $G_DISTRO_NAME (index=$G_DISTRO)
 - Command        | $G_ERROR_HANDLER_COMMAND
 - Exit code      | $G_ERROR_HANDLER_EXITCODE
@@ -1226,7 +1180,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 2. ...
 
 #### Expected behaviour:
-<!-- What SHOULD be happening? -->
+<!-- What SHOULD happen? -->
 - ...
 
 #### Actual behaviour:
@@ -1239,25 +1193,25 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 #### Additional logs:
 \`\`\`
-$print_logfile_info
+$logfile_content
 \`\`\`
 \e[0m
 
-\e[41m--------------------------------------------------------------------\e[0m
+\e[41m---------------------------------------------------------------------\e[0m
 " > /tmp/.G_ERROR_HANDLER_GITREPORT
 
 			fi
 
 			if (( $send_bugreport )); then
 
-				# - Send automated bug report
-				killall -w dietpi-bugreport &> /dev/null
+				# Send automated bug report
+				killall -qw dietpi-bugreport &> /dev/null
 				/DietPi/dietpi/dietpi-bugreport 1
 
 			fi
 
-			# - End
-			if (( ! $G_ERROR_HANDLER_RETRY )); then
+			# End
+			if [[ $G_ERROR_HANDLER_RETRY != 1 ]]; then
 
 				if [[ -f '/tmp/.G_ERROR_HANDLER_GITREPORT' ]]; then
 
@@ -1266,11 +1220,11 @@ $print_logfile_info
 
 				fi
 
-				if (( $G_ERROR_HANDLER_ONERROR_EXIT )); then
+				if [[ $G_ERROR_HANDLER_ONERROR_EXIT != 0 ]]; then
 
 					G_DIETPI-NOTIFY 1 "$print_unable_to_continue"
 					G_ERROR_HANDLER_RESET
-					# - Kill current script, excluding shell
+					# Kill current script, excluding shell
 					kill -INT $$
 
 				else
