v159
+ General | DietPi RPi kernel: Will no longer re-install, if the current
version is already at latest.
+ General | Odroid XU3/4 images updated: Includes kernel support for
EMMC 5.1 (thanks Meveric): https://github.com/Fourdee/DietPi/issues/1252

diff --git a/dietpi/func/dietpi-set_hardware b/dietpi/func/dietpi-set_hardware
--- a/dietpi/func/dietpi-set_hardware
+++ b/dietpi/func/dietpi-set_hardware
@@ -486,48 +486,68 @@ _EOF_
 
 		if [[ "$INPUT_DEVICE_VALUE" = "dietpi_rpi"* ]]; then
 
+			local update_required=1
+			local current_kernel='4.9.62-'
+
+			#Avoid updating main kernel, if latest is already installed
+			if (( $(uname -r | grep -ci -m1 "$current_kernel") )); then
+
+				update_required=0
+
+			fi
+
 			#	Default
 			local install_url_address='http://dietpi.com/downloads/binaries/rpi/dietpi_rpi_kernel_4.9.zip'
 			if [ "$INPUT_DEVICE_VALUE" = "dietpi_rpi_4.4" ]; then
 
 				install_url_address='http://dietpi.com/downloads/binaries/rpi/dietpi_rpi_kernel_4.4.zip'
+				update_required=1 #Always update alternative kernel
 
 			elif [ "$INPUT_DEVICE_VALUE" = "dietpi_rpi_rt" ]; then
 
 				install_url_address='http://dietpi.com/downloads/binaries/rpi/dietpi_rpi_kernel_rt.zip'
+				update_required=1 #Always update alternative kernel
 
 			fi
 
-			/DietPi/dietpi/func/check_connection "$install_url_address"
+			if (( $update_required )); then
 
-			#	Install
-			if (( $? == 0 )); then
+				/DietPi/dietpi/func/check_connection "$install_url_address"
 
-				# - Prevent kernel/firmware/bootloader upgrades from Raspbian repo
-				apt-mark hold raspberrypi-bootloader raspberrypi-kernel
+				#	Install
+				if (( $? == 0 )); then
 
-				wget "$install_url_address" -O package.zip
-				#	Cleanup disabled: https://github.com/Fourdee/DietPi/issues/905#issuecomment-298343932
-				# rm -R /boot/overlays/*
-				# rm -R /lib/modules/*
-				# rm -R /lib/firmware/*
-				# rm /boot/*.img
+					# - Prevent kernel/firmware/bootloader upgrades from Raspbian repo
+					apt-mark hold raspberrypi-bootloader raspberrypi-kernel
 
-				unzip -o package.zip -d /
-				if (( $? != 0 )); then
+					wget "$install_url_address" -O package.zip
+					#	Cleanup disabled: https://github.com/Fourdee/DietPi/issues/905#issuecomment-298343932
+					# rm -R /boot/overlays/*
+					# rm -R /lib/modules/*
+					# rm -R /lib/firmware/*
+					# rm /boot/*.img
 
-					/DietPi/dietpi/func/dietpi-notify 1 "Failed to extract $INPUT_DEVICE_NAME."
+					unzip -o package.zip -d /
+					if (( $? != 0 )); then
+
+						/DietPi/dietpi/func/dietpi-notify 1 "Failed to extract $INPUT_DEVICE_NAME."
+
+					fi
+
+					rm package.zip
+
+					# - flag
+					echo 1 > /etc/dietpi/.dietpi_rpi
+
+				else
+
+					/DietPi/dietpi/func/dietpi-notify 1 "Failed to install $INPUT_DEVICE_NAME. $install_url_address may be offline or unreachable."
 
 				fi
 
-				rm package.zip
-
-				# - flag
-				echo 1 > /etc/dietpi/.dietpi_rpi
-
 			else
 
-				/DietPi/dietpi/func/dietpi-notify 1 "Failed to install $INPUT_DEVICE_NAME. $install_url_address may be offline or unreachable."
+				/DietPi/dietpi/func/dietpi-notify 2 "$INPUT_DEVICE_NAME: Currently running latest kernel, no updates required."
 
 			fi
 
