v150
+ Report failed kernel extraction:
https://github.com/Fourdee/DietPi/issues/905#issuecomment-298343932

diff --git a/dietpi/func/dietpi-set_hardware b/dietpi/func/dietpi-set_hardware
--- a/dietpi/func/dietpi-set_hardware
+++ b/dietpi/func/dietpi-set_hardware
@@ -445,16 +445,22 @@ _EOF_
 				apt-mark hold raspberrypi-bootloader raspberrypi-kernel
 
 				wget "$install_url_address" -O package.zip
+				#	Cleanup disabled: https://github.com/Fourdee/DietPi/issues/905#issuecomment-298343932
 				# rm -R /boot/overlays/*
 				# rm -R /lib/modules/*
 				# rm -R /lib/firmware/*
 				# rm /boot/*.img
 
 				unzip -o package.zip -d /
+				if (( $? != 0 )); then
+
+					/DietPi/dietpi/func/dietpi-notify 1 "Failed to extract kernel $INPUT_DEVICE_NAME."
+
+				fi
 
 				rm package.zip
 
-				# - flag,
+				# - flag
 				echo 1 > /etc/dietpi/.dietpi_rpi
 
 			else
