v8.1
- DietPi-Benchmark | Apply performance CPU governor when running RAM I/O benchmark to avoid low frequency affecting RAM I/O results: https://github.com/MichaIng/DietPi/issues/5039#issuecomment-1021459310
- DietPi-Benchmark | A bunch of wording and coding enhancements, not affecting benchmark results

diff --git a/dietpi/func/dietpi-benchmark b/dietpi/func/dietpi-benchmark
--- a/dietpi/func/dietpi-benchmark
+++ b/dietpi/func/dietpi-benchmark
@@ -27,13 +27,8 @@
 	G_INIT
 	# Import DietPi-Globals --------------------------------------------------------------
 
+	[[ $1 ]] || { G_DIETPI-NOTIFY 1 'Invalid command, please see source code'; exit 1; }
 	INPUT=$1
-	if [[ ! $INPUT ]]; then
-
-		G_DIETPI-NOTIFY 1 'Invalid command, please see sourcecode'
-		exit 1
-
-	fi
 
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Global
@@ -42,7 +37,7 @@
 	SHOW_RESULTS=${SHOW_RESULTS:-1} # Optional input: Show results for individual tests?
 	CPUBENCH_INT_MAX=${CPUBENCH_INT_MAX:-1000000} # Optional input
 	BENCH_FILESIZE=${BENCH_FILESIZE:-0} # Optional input for automated
-	[[ ${FP_BENCHFILE:=/} == '/'* ]] || { G_DIETPI-NOTIFY 1 'FP_BENCHFILE must be an absolute file path, aborting...'; exit 1; } # Optional input
+	[[ ${FP_BENCHFILE:=/} == '/'* ]] || { G_DIETPI-NOTIFY 1 'FP_BENCHFILE must be an absolute directory path, aborting...'; exit 1; } # Optional input
 
 	BENCH_ROOTFS_WRITE='Not tested'
 	BENCH_ROOTFS_READ='Not tested'
@@ -78,21 +73,20 @@ _EOF_
 
 	Upload_Survey(){
 
-		if grep -q '^[[:blank:]]*SURVEY_OPTED_IN=1$' /boot/dietpi.txt; then
-
+		if grep -q '^[[:blank:]]*SURVEY_OPTED_IN=1$' /boot/dietpi.txt
+		then
 			/boot/dietpi/dietpi-survey 1
 
-		elif G_WHIP_YESNO 'To upload and compare your results against other users, you must be opted in to the DietPi-Survey.\n\nWould you like to run DietPi-Survey now, allowing you to opt in?'; then
-
+		elif G_WHIP_YESNO 'To upload and compare your results against other users, you must be opted in to the DietPi-Survey.\n\nWould you like to run DietPi-Survey now, allowing you to opt in?'
+		then
 			/boot/dietpi/dietpi-survey
-
 		fi
 
 	}
 
 	CPU_Benchmark(){
 
-		G_DIETPI-NOTIFY 0 "Running DietPi-CPU Benchmark with max value of 1000000 over $G_HW_CPU_CORES cores, please wait..."
+		G_DIETPI-NOTIFY 2 "Running CPU benchmark with max value of 1000000 over $G_HW_CPU_CORES cores, please wait..."
 
 		cat << _EOF_ > bench
 #!/bin/bash
@@ -105,20 +99,16 @@ aEnd_Int=()
 # Split the max int target based on total cores
 for ((i=0; i<\$cores; i++))
 do
-
 	aEnd_Int[\$i]=\$(( (\$i + 1) * \$int_split ))
 	aStart_Int[\$i]=\$(( \${aEnd_Int[\$i]} - \$int_split ))
 	echo \${aStart_Int[\$i]} \${aEnd_Int[\$i]}
-
 done
 
 Run_Bench(){
 
 	while (( \${aStart_Int[\$1]} < \${aEnd_Int[\$1]} ))
 	do
-
 		((aStart_Int[\$1]++))
-
 	done
 
 }
@@ -126,18 +116,14 @@ Run_Bench(){
 # Launch benchmark threads
 for ((i=0; i<\$cores; i++))
 do
-
 	Run_Bench \$i &
-
 done
 
 # Wait for jobs to finish
-for job in \`jobs -p\`
+for job in \$(jobs -p)
 do
-
 	echo \$job
 	wait \$job
-
 done
 _EOF_
 		G_EXEC chmod +x bench
@@ -152,12 +138,12 @@ _EOF_
 		BENCH_CPU_TEMP_END=$(G_OBTAIN_CPU_TEMP)
 		BENCH_CPU=$(mawk '/real/{print $2;exit}' bench_result)
 
-		if (( $SHOW_RESULTS )); then
-
-			G_WHIP_MSG "CPU Benchmark Results:\n
- - Total time     = $BENCH_CPU Seconds
+		if (( $SHOW_RESULTS ))
+		then
+			G_WHIP_MSG "CPU benchmark results:\n
+ - Total time     = $BENCH_CPU seconds
  - Value to reach = $CPUBENCH_INT_MAX
- - CPU temps      = Start: ${BENCH_CPU_TEMP_START}'c | End: ${BENCH_CPU_TEMP_END}'c
+ - CPU temps      = Start: ${BENCH_CPU_TEMP_START} °C | End: ${BENCH_CPU_TEMP_END} °C
 \n\nNB: A lower 'Total time' is faster"
 
 		fi
@@ -166,19 +152,15 @@ _EOF_
 
 	Filesystem_Benchmark(){
 
-		G_EXEC mkdir -p "$FP_BENCHFILE" # Failsafe
+		[[ -d $FP_BENCHFILE ]] || G_EXEC mkdir "$FP_BENCHFILE" # Failsafe
+		local benchmark_file_name='dietpi-benchmark_testfile'
+		FP_BENCHFILE="${FP_BENCHFILE%/}/$benchmark_file_name"
 		local min_benchmark_size=10
 		local max_benchmark_size=$(( $(G_CHECK_FREESPACE "$FP_BENCHFILE") - 50 )) # Assure 50 MiB stays free
-		#(( $max_benchmark_size > 10000 )) && max_benchmark_size=10000
-
-		local benchmark_file_name='benchmark.file'
-		FP_BENCHFILE="${FP_BENCHFILE%/}/$benchmark_file_name"
-
-		G_TERM_CLEAR
 
 		# Obtain user benchmark size
-		if (( $BENCH_FILESIZE == 0 )); then
-
+		if (( $BENCH_FILESIZE == 0 ))
+		then
 			G_WHIP_DEFAULT_ITEM=$min_benchmark_size
 			G_WHIP_INPUTBOX "Please enter a filesize test value (MiB). A value of 100 is recommended.
  - Minimum value: $min_benchmark_size
@@ -191,94 +173,95 @@ _EOF_
 		(( $BENCH_FILESIZE > $max_benchmark_size )) && BENCH_FILESIZE=$max_benchmark_size
 
 		# Run benchmark
-		G_DIETPI-NOTIFY 2 "Performing Read/Write benchmark on $FP_BENCHFILE, please wait..."
+		G_DIETPI-NOTIFY 2 "Running read/write benchmark on $FP_BENCHFILE ($BENCH_FILESIZE MiB)"
 
-		G_DIETPI-NOTIFY 2 "Testing Seq Write Speed ($BENCH_FILESIZE MiB)"
+		G_DIETPI-NOTIFY 2 'Testing seq write speed, please wait...'
 		sleep 1
-		local bench_write_result=$(dd bs=4K count=$(( $BENCH_FILESIZE * 256 )) if=/dev/zero of="$FP_BENCHFILE" conv=fdatasync 2>&1 | grep -m1 'copied')
-		bench_write_result=$(mawk '{printf "%.0f",$1/$8/1024^2}' <<< "$bench_write_result")
+		local bench_write_result=$(dd bs=4K count=$(( $BENCH_FILESIZE * 256 )) if=/dev/zero of="$FP_BENCHFILE" conv=fdatasync 2>&1 | mawk '/copied/{printf "%.0f",$1/$8/1024^2;exit}')
+		G_DIETPI-NOTIFY 0 "Result: $bench_write_result MiB/s"
 
-		# - Clear cache
+		G_DIETPI-NOTIFY 2 'Clearing filesystem cache...'
 		sync
 		echo 3 > /proc/sys/vm/drop_caches
 
-		G_DIETPI-NOTIFY 2 "Testing Seq Read Speed ($BENCH_FILESIZE MiB)"
+		G_DIETPI-NOTIFY 2 'Testing seq read speed, please wait...'
 		sleep 1
-		local bench_read_result=$(dd bs=4K count=$(( $BENCH_FILESIZE * 256 )) if="$FP_BENCHFILE" of=/dev/null 2>&1 | grep -m1 'copied')
-		bench_read_result=$(mawk '{printf "%.0f",$1/$8/1024^2}' <<< "$bench_read_result")
+		local bench_read_result=$(dd bs=4K count=$(( $BENCH_FILESIZE * 256 )) if="$FP_BENCHFILE" of=/dev/null 2>&1 | mawk '/copied/{printf "%.0f",$1/$8/1024^2;exit}')
+		G_DIETPI-NOTIFY 0 "Result: $bench_read_result MiB/s"
 
 		# - RootFS
-		if [[ $FP_BENCHFILE == '/'$benchmark_file_name ]]; then
-
+		if [[ $FP_BENCHFILE == "/$benchmark_file_name" ]]
+		then
 			BENCH_ROOTFS_WRITE=$bench_write_result
 			BENCH_ROOTFS_READ=$bench_read_result
 
 		# - RAM
-		elif [[ $FP_BENCHFILE == '/tmp/'$benchmark_file_name ]]; then
-
+		elif [[ $FP_BENCHFILE == "/tmp/$benchmark_file_name" ]]
+		then
 			BENCH_RAM_WRITE=$bench_write_result
 			BENCH_RAM_READ=$bench_read_result
 
 		# - Custom
 		else
-
 			BENCH_CUSTOMFS_WRITE=$bench_write_result
 			BENCH_CUSTOMFS_READ=$bench_read_result
-
 		fi
 
-		if (( $SHOW_RESULTS )); then
-
-			G_WHIP_MSG "Filesystem Benchmark Results:\n
- - Filepath  = $FP_BENCHFILE
+		if (( $SHOW_RESULTS ))
+		then
+			G_WHIP_MSG "Filesystem benchmark results:\n
+ - File path = $FP_BENCHFILE
  - Test size = $BENCH_FILESIZE MiB
  - WRITE     = $bench_write_result MiB/s
  - READ      = $bench_read_result MiB/s"
 
 		fi
 
-		[[ -f $FP_BENCHFILE ]] && rm -v "$FP_BENCHFILE"
+		[[ -f $FP_BENCHFILE ]] && G_EXEC rm "$FP_BENCHFILE"
 
 	}
 
 	Benchmark_Survey(){
 
 		SHOW_RESULTS=0
-		G_EXEC mkdir -p /var/lib/dietpi/dietpi-benchmark
+		[[ -d '/var/lib/dietpi/dietpi-benchmark' ]] || G_EXEC mkdir /var/lib/dietpi/dietpi-benchmark
 
-		if (( $G_INTERACTIVE )); then
-
+		if (( $G_INTERACTIVE ))
+		then
 			if G_WHIP_YESNO "$G_PROGRAM_NAME will now run the following benchmarks:\n - CPU performance\n - RootFS read/write performance\n - RAM read/write performance.
 The test duration will depend on hardware specs, however, most devices will not exceed 40 seconds.\n\nIf you are opted in to the DietPi-Survey, your scores will uploaded automatically.
-You can compare results against other users and hardware using the following link:\n - https://dietpi.com/survey#benchmark\n\nPlease select 'Ok' to begin the benchmark tests."; then
-
+You can compare results against other users and hardware using the following link:\n - https://dietpi.com/survey#benchmark\n\nPlease select 'Ok' to begin the benchmark tests."
+			then
 				# Additional checks
 				(( $G_HW_CPU_CORES > 2 )) || G_WHIP_YESNO "We have detected a low CPU core count ($G_HW_CPU_CORES). The tests may take up to 5 minutes to complete.\n\nDo you wish to continue?" || exit 0
-
 			else
-
-				G_DIETPI-NOTIFY 0 'Benchmark aborted'
+				G_DIETPI-NOTIFY 2 'Benchmark aborted'
 				exit 0
-
 			fi
-
 		fi
 
-		G_DIETPI-NOTIFY 0 'Running benchmark suite tests, please wait...'
+		G_DIETPI-NOTIFY 2 'Running benchmark suite tests, please wait...'
 		CPU_Benchmark
 
 		# FS/RAM
 		# - RAM
-		if df -t tmpfs /tmp &> /dev/null; then
+		if df -t tmpfs /tmp &> /dev/null
+		then
+			# Apply performance CPU governor to avoid low frequency affecting RAM I/O results: https://github.com/MichaIng/DietPi/issues/5039#issuecomment-1021459310
+			G_DIETPI-NOTIFY 2 'Temporarily applying performance CPU governor for RAM I/O benchmark...'
+			for i in /sys/devices/system/cpu/cpu[0-9]*/cpufreq/scaling_governor
+			do
+				echo 'performance' > "$i"
+			done
 
 			FP_BENCHFILE='/tmp'
 			BENCH_FILESIZE=$(mawk '/^MemFree:/{printf "%.0f",$2/2048;exit}' /proc/meminfo) # Assure 50% of physical mem stays free, so swapping can be ruled out: KiB => MiB / 2
 			Filesystem_Benchmark
 
+			G_DIETPI-NOTIFY 2 'Restoring original CPU governor...'
+			/boot/dietpi/func/dietpi-set_cpu
 		else
-
-			G_DIETPI-NOTIFY 1 '/tmp does not seem to be mounted as tmpfs (RAMdisk). Skipping RAM benchmark...'
-
+			G_DIETPI-NOTIFY 1 '/tmp does not seem to be mounted as tmpfs (RAMdisk). Skipping RAM I/O benchmark...'
 		fi
 
 		# - RootFS
@@ -289,10 +272,10 @@ You can compare results against other users and hardware using the following lin
 		SHOW_RESULTS=1
 
 		G_WHIP_MSG "Benchmarks completed:
- - CPU Performance : Duration = $BENCH_CPU seconds (lower is faster)
- - CPU Temp        : Idle = ${BENCH_CPU_TEMP_START}'c | Full load = ${BENCH_CPU_TEMP_END}'c
- - RootFS          : Write = $BENCH_ROOTFS_WRITE MiB/s | Read = $BENCH_ROOTFS_READ MiB/s
- - RAM             : Write = $BENCH_RAM_WRITE MiB/s | Read = $BENCH_RAM_READ MiB/s
+ - CPU performance : Duration = $BENCH_CPU seconds (lower is faster)
+ - CPU temps       : Idle = ${BENCH_CPU_TEMP_START} °C | Full load = ${BENCH_CPU_TEMP_END} °C
+ - RootFS I/O      : Write = $BENCH_ROOTFS_WRITE MiB/s | Read = $BENCH_ROOTFS_READ MiB/s
+ - RAM I/O         : Write = $BENCH_RAM_WRITE MiB/s | Read = $BENCH_RAM_READ MiB/s
 
 Compare these results online with other users, using the link below:
  - https://dietpi.com/survey#benchmark"
@@ -312,25 +295,20 @@ Compare these results online with other users, using the link below:
 
 	Benchmark_Lan_Client(){
 
+		G_WHIP_INPUTBOX 'Please enter the IP address of the system running the network benchmark server:\n - E.g.: 192.168.0.100' || return 0
+		IPERF_SERVER_IP=$G_WHIP_RETURNED_VALUE
+
 		G_AG_CHECK_INSTALL_PREREQ iperf
-		if G_WHIP_INPUTBOX 'Please enter the IP address of the system running the network benchmark server:\n - eg: 192.168.0.100'; then
 
-			IPERF_SERVER_IP=$G_WHIP_RETURNED_VALUE
-
-			G_DIETPI-NOTIFY 2 "Benchmarking network performance to $IPERF_SERVER_IP. Please wait..."
-			BENCH_NET_LAN_SPEED=$(iperf -c "$IPERF_SERVER_IP" -p 5001 -t 5 -y C | sed 's/.*,//g')
-			if disable_error=1 G_CHECK_VALIDINT "$BENCH_NET_LAN_SPEED"; then
-
-				BENCH_NET_LAN_SPEED=$(( $BENCH_NET_LAN_SPEED / 8 / 1024**2 ))
-				G_WHIP_MSG "Network LAN benchmark completed:\n - Transfer rate = $BENCH_NET_LAN_SPEED MiB/s"
-
-			else
-
-				G_WHIP_MSG 'Network LAN benchmark failed, please verify:\n - Server is running on the other system\n - Server IP address is correct'
-				BENCH_NET_LAN_SPEED='Not tested'
-
-			fi
-
+		G_DIETPI-NOTIFY 2 "Benchmarking network performance to $IPERF_SERVER_IP, please wait..."
+		BENCH_NET_LAN_SPEED=$(iperf -c "$IPERF_SERVER_IP" -p 5001 -t 5 -y C | sed 's/.*,//g')
+		if disable_error=1 G_CHECK_VALIDINT "$BENCH_NET_LAN_SPEED"
+		then
+			BENCH_NET_LAN_SPEED=$(( $BENCH_NET_LAN_SPEED / 8 / 1024**2 ))
+			G_WHIP_MSG "Network LAN benchmark completed:\n - Transfer rate = $BENCH_NET_LAN_SPEED MiB/s"
+		else
+			G_WHIP_MSG 'Network LAN benchmark failed, please verify:\n - Server is running on the other system\n - Server IP address is correct'
+			BENCH_NET_LAN_SPEED='Not tested'
 		fi
 
 	}
@@ -344,36 +322,34 @@ Compare these results online with other users, using the link below:
 	ionice -p $$ -c 1 -n 0
 	#-----------------------------------------------------------------------------------
 	# Init vars for sourcing
-	if (( $INPUT == 0 )); then
-
+	if (( $INPUT == 0 ))
+	then
 		Save_Results
 
 	# LAN bench server
-	elif (( $INPUT == 3 )); then
-
+	elif (( $INPUT == 3 ))
+	then
 		Benchmark_Lan_Server
 
 	# Run benchmarks
 	else
-
 		#-----------------------------------------------------------------------------------
 		/boot/dietpi/dietpi-services stop
 		#-----------------------------------------------------------------------------------
 		# Reuse existing results if done
 		Load_Results
 		#-----------------------------------------------------------------------------------
-		if (( $INPUT == 1 )); then
-
+		if (( $INPUT == 1 ))
+		then
 			Filesystem_Benchmark
 
-		elif (( $INPUT == 2 )); then
-
+		elif (( $INPUT == 2 ))
+		then
 			Benchmark_Survey
 
-		elif (( $INPUT == 4 )); then
-
+		elif (( $INPUT == 4 ))
+		then
 			Benchmark_Lan_Client
-
 		fi
 		#-----------------------------------------------------------------------------------
 		# Export results data for other scripts:
@@ -384,7 +360,6 @@ Compare these results online with other users, using the link below:
 		#-----------------------------------------------------------------------------------
 		/boot/dietpi/dietpi-services start
 		#-----------------------------------------------------------------------------------
-
 	fi
 	#-----------------------------------------------------------------------------------
 	exit 0
