v6.18
+ DietPi-Globals | G_CONFIG_INJECT: Minor wording and error catching enhancements
+ DietPi-Globals | G_CONFIG_INJECT: Do required special character escaping function internally
+ DietPi-Globals | G_CONFIG_INJECT: Remove extended regular expression support

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -2332,39 +2332,40 @@ $print_logfile_info
 
 	# Inject setting into config file
 	# - First tries to replace old setting, else commented setting and otherwise adds it to end of file.
-	#	- Optionally adds argument to new line after speficied pattern $4.
+	#	- Optionally adds argument to new line after specified pattern $4.
 	#	- PRESERVE=1 G_CONFIG_INJECT allows to keep current setting, if present.
 	#	- BACKUP=1 G_CONFIG_INJECT allows to backup to file before editing, if backup does not yet exist.
 	# - Example: G_CONFIG_INJECT 'prefer-family[[:blank:]=]' 'prefer-family = IPv4' /etc/wgetrc
-	# - Extended regular expressions can be used for the identifying patterns $1 and $4.
-	#	- Escape any of: ".+*?&\|^$()[]{}
-	#	- Escape baskashes doubled within double quotes.
+	#	- grep/sed basic regex are supported, related special characters will be escaped internally.
+	#	- Thus no special character escaping is required when adding arguments via variables.
+	#	- Within double quotes "", as usual, escape literally meant double quotes and dollar signs $ with leading backslash \.
+	#	- Within single quotes '', as usual, escape literally meant single quotes via: '\'' # End leading string; Add escaped single quote; Start trailing string
 	G_CONFIG_INJECT(){
 
 		[[ $G_PROGRAM_NAME ]] || local G_PROGRAM_NAME='G_CONFIG_INJECT'
-		local pattern="$1"
-		local setting="$2"
+		local pattern="${1//\\/\\\\}"; pattern="${pattern//./\\.}"; pattern="${pattern//\*/\\\*}"; pattern="${pattern//[/\\[}"; pattern="${pattern//^/\\^}"; pattern="${pattern//&/\\&}"; pattern="${pattern//$/\\$}"
+		local setting="${2//\\/\\\\}"; setting="${setting//./\\.}"; setting="${setting//\*/\\\*}"; setting="${setting//[/\\[}"; setting="${setting//^/\\^}"; setting="${setting//&/\\&}"; setting="${setting//$/\\$}"
 		local file="$3"
-		local after="$4"
+		local after="${4//\\/\\\\}"; after="${after//./\\.}"; after="${after//\*/\\\*}"; after="${after//[/\\[}"; after="${after//^/\\^}"; after="${after//&/\\&}"; after="${after//$/\\$}"
 		local error=''
 
 		syntax_error(){
 
-			[[ $after ]] && after='after line\n	'.$after.' ($4)\n'
-			[[ $error ]] && error="\n\"grep\" reported the following error:\n	$error\n"
+			[[ $after ]] && after='after line $4\n	'.$after.'\n'
+			[[ $error ]] && error="\n\"grep\" or \"sed\" reported the following error:\n	$error\n"
 
 			G_WHIP_MSG "[FAILED] Syntax error
 $error
-Couldn't add setting (\$2)
+Couldn't add setting \$2
 	$setting
-into file (\$3)
+into file \$3
 	$file
 $after
 NB:
-- Please escape any of the following characters with leading backslash (\):
-	\".+*?\\|^\$()[]{}
-- Within double quotes (\"\"), please escape backslashes (\) doubled:
-	\"\\\\\\\\\" results in \"\\\""
+ - grep/sed basic regex are supported, related special characters will be escaped internally.
+ - Thus no special character escaping is required when adding arguments via variables.
+ - Within double quotes \"\", as usual, escape literally meant double quotes, backslashes \ and dollar signs $ via leading backslash.
+ - Within single quotes '', as usual, escape literally meant single quotes via: '\'' # End leading string; Add escaped single quote; Start trailing string"
 
 			unset syntax_error
 
@@ -2372,72 +2373,85 @@ NB:
 
 		if [[ ! -w $file ]]; then
 
-			G_WHIP_MSG "[FAILED] '$file' does not exist or cannot be written to by current user.\n
-Please verify the existance of the file, retry with proper permissions or apply the setting manually:
-	$(sed -E "c\\$setting" <<< '')"
+			G_WHIP_MSG "[FAILED] File does not exist or cannot be written to by current user\n
+Please verify the existence of the file \$3
+	$file\n
+Retry with proper permissions or apply the setting manually:
+	$(sed "c\\$setting" <<< '')"
 
-		elif error=$(grep -qE "^[[:blank:]]*$pattern" $file 2>&1); then
-			# As an error within the condition leads to "false", it can be catched only after next condition match
+		elif error=$(grep -q "^[[:blank:]]*$pattern" $file 2>&1); then
+			# As an error within the condition leads to result "false", it can be caught only in next "elif"/"else" statement.
 
 			if [[ $PRESERVE == 1 ]]; then
 
-				G_DIETPI-NOTIFY 0 "Current setting in \e[33m$file\e[0m will be preserved: \e[33m$(grep -Em1 "^[[:blank:]]*$pattern" $file | sed 's|\\|\\\\|g')\e[0m"
+				G_DIETPI-NOTIFY 0 "Current setting in \e[33m$file\e[0m will be preserved: \e[33m$(grep -m1 "^[[:blank:]]*$pattern" $file | sed 's|\\|\\\\|g')\e[0m"
 
-			elif error=$(grep -qE "^[[:blank:]]*$setting([[:space:]]|$)" $file 2>&1); then
+			elif error=$(grep -q "^[[:blank:]]*$setting\([[:space:]]\|$\)" $file 2>&1); then
 
-				G_DIETPI-NOTIFY 0 "Desired setting in \e[33m$file\e[0m was already set: \e[33m$(grep -Em1 "^[[:blank:]]*$pattern" $file | sed 's|\\|\\\\|g')\e[0m"
+				G_DIETPI-NOTIFY 0 "Desired setting in \e[33m$file\e[0m was already set: \e[33m$(grep -m1 "^[[:blank:]]*$pattern" $file | sed 's|\\|\\\\|g')\e[0m"
+
+			elif error=$( (( $(grep -c "^[[:blank:]]*$pattern" $file 2>&1) > 1 )) 2>&1); then
+				[[ $error ]] && { syntax_error; return 1; }
+
+				G_WHIP_MSG "[FAILED] Setting was found multiple times\n
+The pattern \$1
+	$(sed "c\\$pattern" <<< '')
+was found multiple times in file \$3
+	$file\n
+____________
+$(grep -n "^[[:blank:]]*$pattern" $file) 
+____________\n
+Either the pattern \$1 needs to be more specific or the desired setting can appear multiple times by design and it cannot be predicted which instance to edit.
+Please retry with more specific parameter \$1 or apply the setting manually:
+	$(sed "c\\$setting" <<< '')"
 
 			else
-				[[ $error ]] && syntax_error && return 1
+				[[ $error ]] && { syntax_error; return 1; }
 
-				[[ $BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file\e[0m"
-				sed -Ei "0,\|^[[:blank:]]*$pattern.*$|s||$setting|" $file
-				(( $? )) && syntax_error && return 1
-				G_DIETPI-NOTIFY 0 "Setting in \e[33m$file\e[0m adjusted: \e[33m$(sed -E "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m"
+				[[ $BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
+				error=$(sed -i "0,\|^[[:blank:]]*$pattern.*$|s||$setting|" $file 2>&1) || { syntax_error; return 1; }
+				G_DIETPI-NOTIFY 0 "Setting in \e[33m$file\e[0m adjusted: \e[33m$(sed "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m"
 
 			fi
 
-		elif error=$(grep -qE "^[[:blank:]#;]*$pattern" $file 2>&1); then
-			[[ $error ]] && syntax_error && return 1
+		elif error=$(grep -q "^[[:blank:]#;]*$pattern" $file 2>&1); then
+			[[ $error ]] && { syntax_error; return 1; }
 
 			[[ $BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file\e[0m"
-			sed -Ei "0,\|^[[:blank:]#;]*$pattern.*$|s||$setting|" $file
-			(( $? )) && syntax_error && return 1
-			G_DIETPI-NOTIFY 0 "Comment in \e[33m$file\e[0m converted to setting: \e[33m$(sed -E "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m"
+			error=$(sed -i "0,\|^[[:blank:]#;]*$pattern.*$|s||$setting|" $file 2>&1) || { syntax_error; return 1; }
+			G_DIETPI-NOTIFY 0 "Comment in \e[33m$file\e[0m converted to setting: \e[33m$(sed "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m"
 
 		else
-			[[ $error ]] && syntax_error && return 1
+			[[ $error ]] && { syntax_error; return 1; }
 
 			if [[ $after ]]; then
 
-				if error=$(grep -qE "^[[:blank:]]*$after" $file 2>&1); then
+				if error=$(grep -q "^[[:blank:]]*$after" $file 2>&1); then
 
-					[[ $BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file\e[0m"
-					sed -Ei "0,\|^[[:blank:]]*$after.*$|s||&\n$setting|" $file
-					(( $? )) && syntax_error && return 1
-					G_DIETPI-NOTIFY 0 "Added setting \e[33m$(sed -E "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m to \e[33m$file\e[0m after line \e[33m$(grep -Em1 "^[[:blank:]]*$after" $file | sed 's|\\|\\\\|g')\e[0m"
+					[[ $BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
+					error=$(sed -i "0,\|^[[:blank:]]*$after.*$|s||&\n$setting|" $file 2>&1) || { syntax_error; return 1; }
+					G_DIETPI-NOTIFY 0 "Added setting \e[33m$(sed "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m to \e[33m$file\e[0m after line \e[33m$(grep -m1 "^[[:blank:]]*$after" $file | sed 's|\\|\\\\|g')\e[0m"
 
 				else
-					[[ $error ]] && syntax_error && return 1
+					[[ $error ]] && { syntax_error; return 1; }
 
-					G_WHIP_MSG "[FAILED] Setting could not be added after desired line.\n
-The pattern
-	$(sed -E "c\\$after" <<< '')
-could not be found in file
+					G_WHIP_MSG "[FAILED] Setting could not be added after desired line\n
+The pattern \$4
+	$(sed "c\\$after" <<< '')
+could not be found in file \$3
 	$file\n
-Please retry with valid parameter (\$4) or apply the setting manually:
-	$(sed -E "c\\$setting" <<< '')"
+Please retry with valid parameter \$4 or apply the setting manually:
+	$(sed "c\\$setting" <<< '')"
 
 				fi
 
 			else
 
-				[[ $BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file\e[0m"
+				[[ $BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
 				# The following sed does not work on empty files:
 				[[ ! -s $file ]] && echo '# Added by DietPi:' >> $file
-				sed -Ei "\$s|\$|\n$setting|" $file
-				(( $? )) && syntax_error && return 1
-				G_DIETPI-NOTIFY 0 "Added setting \e[33m$(sed -E "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m to end of file \e[33m$file\e[0m"
+				error=$(sed -i "\$s|\$|\n$setting|" $file 2>&1) || { syntax_error; return 1; }
+				G_DIETPI-NOTIFY 0 "Added setting \e[33m$(sed "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m to end of file \e[33m$file\e[0m"
 
 			fi
 
