v6.13
+ Add error handling to G_THREAD's: https://github.com/Fourdee/DietPi/issues/1801

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -2069,7 +2069,7 @@ $print_logfile_info
 			((G_THREAD_COUNT++))
 			G_THREAD_COMMAND[$G_THREAD_COUNT]=$@
 
-			( G_USER_INPUTS=0 ${G_THREAD_COMMAND[$G_THREAD_COUNT]} &> /tmp/.G_THREAD_COMMAND_$G_THREAD_COUNT & echo $! > /tmp/.G_THREAD_PID_$G_THREAD_COUNT ) > /dev/null
+			( G_USER_INPUTS=0 ${G_THREAD_COMMAND[$G_THREAD_COUNT]} &> /tmp/.G_THREAD_COMMAND_$G_THREAD_COUNT; echo $? > /tmp/.G_THREAD_EXITCODE_$G_THREAD_COUNT & echo $! > /tmp/.G_THREAD_PID_$G_THREAD_COUNT ) > /dev/null
 			G_THREAD_PID[$G_THREAD_COUNT]=$(cat /tmp/.G_THREAD_PID_$G_THREAD_COUNT)
 			rm /tmp/.G_THREAD_PID_$G_THREAD_COUNT
 
@@ -2128,7 +2128,30 @@ $print_logfile_info
 
 		done
 
-		sync #Sync changes to disk, prevent "no file found" when file exists in buffer.
+		# - Check all thread exit codes for issues
+		for (( i=0; i<${#G_THREAD_COMMAND[@]}; i++ ))
+		do
+
+			if [[ -f /tmp/.G_THREAD_EXITCODE_$i ]]; then
+
+				local exit_code=$(cat /tmp/.G_THREAD_EXITCODE_$i)
+				if (( $exit_code != 0 )); then
+
+					G_WHIP_MSG "G_THREAD ERROR:\n - Command = ${G_THREAD_COMMAND[$i]}\n - Exit code = $exit_code\n\n$(cat /tmp/.G_THREAD_COMMAND_$i)"
+
+				fi
+
+			else
+
+				G_DIETPI-NOTIFY 2 'DEBUG: /tmp/.G_THREAD_EXITCODE_$i does not exist'
+
+			fi
+
+		done
+
+		rm /tmp/.G_THREAD*
+
+		sync #Failsafe: Sync changes to disk
 
 		G_DIETPI-NOTIFY 0 'G_THREAD: All threads finished'
 
