custom command failures provide the exit code

diff --git a/dietpi/func/dietpi-banner b/dietpi/func/dietpi-banner
--- a/dietpi/func/dietpi-banner
+++ b/dietpi/func/dietpi-banner
@@ -623,10 +623,16 @@ $GREEN_LINE"
 	Print_Custom_Commands()
 	{
 		for i in "${!CUSTOM_COMMANDS[@]}"; do
-			cmd="${CUSTOM_COMMANDS[$i]}"
+			local cmd="${CUSTOM_COMMANDS[$i]}"
 			if [[ -n "$cmd" ]]; then
 				# shellcheck disable=SC2086
-				echo "$(eval "$cmd" 2>&1)" || echo -e "${aCOLOUR[RED]}Error executing custom command $((i+1))${COLOUR_RESET}"
+				output="$(eval "$cmd" 2>&1)"
+				status=$?
+				if [[ $status -ne 0 ]]; then
+					printf '%b\n' "${aCOLOUR[RED]}Error executing CUSTOM_COMMAND[$((i))] Exit Code: ${status}${COLOUR_RESET}"
+				else
+					printf '%b\n' "$output"
+				fi
 			fi
 		done
 	}
