v6.32
+ DietPi-Globals | Minor

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -189,26 +189,26 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 	#	-2 = Processing
 	#		$2+ = message
 	#	-1 = Autodetect ok or failed
-	#		$2 = exit code
+	#		$2  = exit code
 	#		$3+ = message
-	#	0 = Ok
+	#	0  = Ok
 	#		$2+ = message
-	#	1 = Failed
+	#	1  = Failed
 	#		$2+ = message
-	#	2 = Info
+	#	2  = Info
 	#		$2+ = message
-	#	3 = Header
-	#		$2 = program name
+	#	3  = Header
+	#		$2  = program name
 	#		$3+ = message, prefixed with "${G_NOTIFY_3_MODE}: ", defaults to "Mode: "
 	G_DIETPI-NOTIFY(){
 
 		local ainput_string=("$@") output_string grey green red reset yellow dietpi_green
-		# If this is a terminal, it understands ANSI escape sequences, so use colour, always start left-aligned with colour reset and clean from cursor until end of screen.
+		# If this is a terminal, it understands ANSI escape sequences, so use colour, always start left-aligned with colour reset and clear screen from cursor til end.
 		# - Assume if STDIN is a terminal that STDOUT is one as well, e.g. covered by "tee"
 		if [[ -t 0 || -t 1 ]]; then
 
 			output_string='\e[0m\r\e[J' grey='\e[90m' green='\e[32m' red='\e[31m' reset='\e[0m' yellow='\e[33m' dietpi_green='\e[38;5;154m'
-			# Kill existing process animation if this is not a processing message.
+			# Kill existing process animation if this is not a processing message
 			if [[ $1 != '-2' && -w '/tmp/dietpi-process.pid' ]]; then
 
 				kill -9 $(</tmp/dietpi-process.pid) &> /dev/null
@@ -217,13 +217,13 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 			fi
 
 		fi
-		local bracket_l="${grey}[${reset}" bracket_r="${grey}]${reset}"
-		local ok="$bracket_l  ${green}OK  $bracket_r " failed="$bracket_l${red}FAILED$bracket_r "
+		local bracket_l="$grey[$reset" bracket_r="$grey]$reset"
+		local ok="$bracket_l$green  OK  $bracket_r " failed="$bracket_l${red}FAILED$bracket_r "
 
 		# Print input array from index $1
 		Print(){
 
-			[[ $1 == 1 && $G_PROGRAM_NAME ]] && output_string+="${grey}$G_PROGRAM_NAME |${reset} "
+			[[ $1 == 1 && $G_PROGRAM_NAME ]] && output_string+="$grey$G_PROGRAM_NAME |$reset "
 			local i
 			for ((i=$1; i<${#ainput_string[@]}; i++))
 			do
@@ -231,7 +231,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 				output_string+=${ainput_string[$i]}
 
 			done
-			echo -ne "$output_string${reset}"
+			echo -ne "$output_string$reset"
 
 		}
 
@@ -244,15 +244,15 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 		# - Use this at end of DietPi scripts, e.g. G_DIETPI-NOTIFY -1 ${EXIT_CODE:=0}
 		if (( $1 == -1 )); then
 
-			if (( ! $2 )); then
+			if (( $2 )); then
 
-				output_string+=$ok
-				ainput_string+=(' Completed\n')
+				output_string+=$failed
+				ainput_string+=(' | Exited with error\n')
 
 			else
 
-				output_string+=$failed
-				ainput_string+=(' An issue has occurred\n')
+				output_string+=$ok
+				ainput_string+=(' | Completed\n')
 
 			fi
 			Print 2
@@ -263,7 +263,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 		# NB: Do not use this with newlines, literally or "\n", as this would cause parts of the processing message not being overwritten as intended.
 		elif (( $1 == -2 )); then
 
-			# If this is a terminal, it understands control codes, so make any next output overwriting the processing message.
+			# If this is a terminal, it understands control codes, so make any next output overwrite the processing message.
 			if [[ -t 0 || -t 1 ]]; then
 
 				# Calculate the amount of output lines and in case move cursor up for correct animation position and to allow overwriting the whole output.
@@ -317,7 +317,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 						for (( i=0; i<=${#aprocess_string[@]}; i++ )); do
 
 							(( i == ${#aprocess_string[@]} )) && i=0
-							[[ -w '/tmp/dietpi-process.pid' ]] && echo -ne "\e[2G${aprocess_string[$i]}${reset}\e[C" || return
+							[[ -w '/tmp/dietpi-process.pid' ]] && echo -ne "\e[2G${aprocess_string[$i]}$reset\e[C" || return
 							sleep 0.15
 
 						done
@@ -331,9 +331,10 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 					set +C
 
 				fi
+
 			else
 
-				output_string+="$bracket_l ${yellow}.... $bracket_r "
+				output_string+="$bracket_l $yellow.... $bracket_r "
 				Print 1
 
 			fi
@@ -363,7 +364,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 			output_string+="$bracket_l INFO $bracket_r "
 			# Keep info messages in gray, even if "$G_PROGRAM_NAME | \e[0m" is added:
-			ainput_string[1]="${grey}${ainput_string[1]}"
+			ainput_string[1]="$grey${ainput_string[1]}"
 			ainput_string+=('\n')
 			Print 1
 
@@ -379,15 +380,15 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 				# > 9 should never occur, however, if it is, lets make it line up regardless
 				(( $HIERARCHY > 9 )) && status_subfunction=$HIERARCHY
 
-				output_string+="$bracket_l ${yellow}SUB$status_subfunction$bracket_r $2 > "
+				output_string+="$bracket_l$yellow SUB$status_subfunction$bracket_r $2 > "
 				ainput_string+=('\n')
 
 			else
 
 				output_string+="
- ${dietpi_green}$2${reset}
-${grey}─────────────────────────────────────────────────────
- ${G_NOTIFY_3_MODE:-Mode}:${reset} "
+ $dietpi_green$2$reset
+$grey─────────────────────────────────────────────────────
+ ${G_NOTIFY_3_MODE:-Mode}:$reset "
 				ainput_string+=('\n\n')
 
 			fi
