v6.10
+DietPi-Globals | G_CHECK_USERDATA: Added to DietPi scripts: https://github.com/Fourdee/DietPi/issues/1850#issuecomment-401407996

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -1847,7 +1847,7 @@ $print_logfile_info
 
 	#G_CHECK_VALIDINT | Simple test to verify if a variable is a valid integer.
 	# $1=input
-	# 1=no
+	# 1=no | scripts killed automatically
 	# 0=yes
 	# Usage = if G_CHECK_VALIDINT input; then
 	G_CHECK_VALIDINT(){
@@ -1858,6 +1858,41 @@ $print_logfile_info
 		if [[ ! $input =~ ^-?[0-9]+$ ]]; then
 
 			return_value=1
+
+		fi
+
+		return $return_value
+
+	}
+
+	#Verifies the integrity of the DietPi userdata folder/symlink, based on where it should be psyhically. Basically, checks if user removed the USB drive with userdata on it.
+	#	NB: As this is considered a critical (if failed), current scripts will be exited automatically
+	# 1=fail
+	# 0=ok
+	G_CHECK_USERDATA(){
+
+		return_value=0
+
+		local fp_actual=$G_FP_DIETPI_USERDATA
+
+		#Symlinked?
+		if [[ -L $G_FP_DIETPI_USERDATA ]]; then
+
+			# - Check psyhical location exists and is mounted
+			fp_actual="$(readlink $G_FP_DIETPI_USERDATA)"
+			if ! df -P $fp_actual &> /dev/null; then
+
+				return_value=1
+
+			fi
+
+		fi
+
+		G_DIETPI-NOTIFY $return_value "DietPi-Userdata validation: $fp_actual"
+		if (( $return_value >= 1 )); then
+
+			G_WHIP_MSG "Error: DietPi-Userdata validation\n\nDietPi was unable to verify the existance of the userdata directory ($fp_actual).\n\nPlease ensure all previous external drives are connected and functional, before trying again.\n\nUnable to continue, exiting."
+			kill -INT $$ #kill all current scripts, excluding shell.
 
 		fi
 
