Change G_USER_INPUTS to G_INTERACTIVE Find and replace of 37 instances across the whole repo

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -28,15 +28,15 @@
 
 	# Interactive mode
 	# - Affects whether G_ERROR_ and G_WHIP_ prompts are displayed or not
-	# - Run "export G_USER_INPUTS=0" prior to script call to force non-interactive/automated mode.
-	# - Run "unset G_USER_INPUTS" afterwards to return to auto detection.
+	# - Run "export G_INTERACTIVE=0" prior to script call to force non-interactive/automated mode.
+	# - Run "unset G_INTERACTIVE" afterwards to return to auto detection.
 	# - If not set, check for STDIN availability:
 	#	OK | systemd	= no STDIN
 	#	OK | Cron	= no STDIN
 	#	NB | /etc/profile, ~/.profile, /etc/profile.d/, /etc/bash.bashrc, ~/.bashrc and /etc/bashrc.d/ can all be interactive since those are sourced from originating shell/bash session.
-	if [[ $G_USER_INPUTS != [01] ]]; then
+	if [[ $G_INTERACTIVE != [01] ]]; then
 
-		[[ -t 0 ]] && G_USER_INPUTS=1 || G_USER_INPUTS=0
+		[[ -t 0 ]] && G_INTERACTIVE=1 || G_INTERACTIVE=0
 
 	fi
 
@@ -536,7 +536,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 	#-----------------------------------------------------------------------------------
 	# Whiptail (Whippy-da-whip-whip-whip tail!)
-	# - Automatically detects/processes for G_USER_INPUTS
+	# - Automatically detects/processes for G_INTERACTIVE
 	#-----------------------------------------------------------------------------------
 	# Input:
 	# - G_WHIP_DEFAULT_ITEM		| Optional, to set the default selected/menu item or input box entry
@@ -784,7 +784,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 		local WHIP_MESSAGE=$@
 
-		if (( $G_USER_INPUTS )); then
+		if (( $G_INTERACTIVE )); then
 
 			G_WHIP_INIT 0
 			whiptail --title "$G_PROGRAM_NAME" --msgbox "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --backtitle "$WHIP_BACKTITLE" $WHIP_SIZE_Y $WHIP_SIZE_X
@@ -805,7 +805,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 		local WHIP_MESSAGE=$@
 
-		if (( $G_USER_INPUTS )); then
+		if (( $G_INTERACTIVE )); then
 
 			G_WHIP_INIT 0
 			whiptail --title "$G_PROGRAM_NAME" --scrolltext --msgbox "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --backtitle "$WHIP_BACKTITLE" $WHIP_SIZE_Y $WHIP_SIZE_X
@@ -827,7 +827,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 		local result=1
 
-		if (( $G_USER_INPUTS )); then
+		if (( $G_INTERACTIVE )); then
 
 			local WHIP_MESSAGE=$@
 			G_WHIP_INIT 0
@@ -851,7 +851,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 		local result=1
 		unset G_WHIP_RETURNED_VALUE # in case left from last G_WHIP
 
-		if (( $G_USER_INPUTS )); then
+		if (( $G_INTERACTIVE )); then
 
 			local WHIP_MESSAGE=$@
 			G_WHIP_INIT 0
@@ -881,7 +881,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 		local return_value=1
 		result=''
 
-		if (( $G_USER_INPUTS )); then
+		if (( $G_INTERACTIVE )); then
 
 			local WHIP_MESSAGE=$@
 			G_WHIP_INIT 0
@@ -920,7 +920,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 		local result=1
 		unset G_WHIP_RETURNED_VALUE # in case left from last G_WHIP
 
-		if (( $G_USER_INPUTS )); then
+		if (( $G_INTERACTIVE )); then
 
 			local WHIP_MESSAGE=$@
 			G_WHIP_INIT 1
@@ -944,7 +944,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 		local result=1
 		unset G_WHIP_RETURNED_VALUE # in case left from last G_WHIP
 
-		if (( $G_USER_INPUTS )); then
+		if (( $G_INTERACTIVE )); then
 
 			local WHIP_MESSAGE=$@
 			G_WHIP_INIT 2
@@ -967,7 +967,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 		local result=0
 
-		if (( $G_USER_INPUTS )); then
+		if (( $G_INTERACTIVE )); then
 
 			local log=${log:-0} # Optional yes/no prompt for viewing logs
 			local fp_file=$1
@@ -1011,7 +1011,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 	# - G_ERROR_HANDLER_COMMAND=<cmd>		| Command name for print out
 	# - G_ERROR_HANDLER_EXITCODE=<int>		| Commands exit code
 	# Optional input:
-	# - G_ERROR_HANDLER_NO_FAIL=1			| Always report a success, regardless of the exit code | G_USER_INPUTS=0 is not required for this
+	# - G_ERROR_HANDLER_NO_FAIL=1			| Always report a success, regardless of the exit code | G_INTERACTIVE=0 is not required for this
 	# - G_ERROR_HANDLER_INFO_ONLY=1			| Only print info and retry options, no exit or bug report, sets G_ERROR_HANDLER_ONERROR_EXIT=0 automatically
 	# - G_ERROR_HANDLER_ONERROR_EXIT=0		| Do not exit the script on error
 	# - G_ERROR_HANDLER_RETRY=1			| Allow to retry the command. Requires loop in originating script!
@@ -1077,7 +1077,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 			[[ $G_PROGRAM_NAME && $G_ERROR_HANDLER_INFO_ONLY != 1 ]] && G_DIETPI-NOTIFY 2 "$print_report_to_dietpi_info"
 
 			# If interactive, prompt whip message
-			if (( $G_USER_INPUTS )); then
+			if (( $G_INTERACTIVE )); then
 
 				local whip_msg="${G_PROGRAM_NAME+$G_PROGRAM_NAME: }$G_ERROR_HANDLER_COMMAND
  - Exit code: $G_ERROR_HANDLER_EXITCODE
@@ -1279,7 +1279,7 @@ $logfile_content
 	#	- $optional_cmd_inputs (eg: --no-check-certificate)
 	#	- G_CHECK_URL_TIMEOUT to override default and dietpi.txt set timeout
 	#	- G_CHECK_URL_ATTEMPTS to override default and dietpi.txt set attempts
-	#	In case of failure and $G_USER_INPUTS=1: Prompts user to configure network
+	#	In case of failure and $G_INTERACTIVE=1: Prompts user to configure network
 	G_CHECK_URL(){
 
 		local url=$@
@@ -2044,7 +2044,7 @@ $logfile_content
 			G_THREAD_COMMAND[$G_THREAD_COUNT]=$@
 
 			echo -1337 > /tmp/.G_THREAD_EXITCODE_$G_THREAD_COUNT
-			{ { G_USER_INPUTS=0 ${G_THREAD_COMMAND[$G_THREAD_COUNT]} &> /tmp/.G_THREAD_COMMAND_$G_THREAD_COUNT; echo $? > /tmp/.G_THREAD_EXITCODE_$G_THREAD_COUNT; } & disown; } &> /dev/null
+			{ { G_INTERACTIVE=0 ${G_THREAD_COMMAND[$G_THREAD_COUNT]} &> /tmp/.G_THREAD_COMMAND_$G_THREAD_COUNT; echo $? > /tmp/.G_THREAD_EXITCODE_$G_THREAD_COUNT; } & disown; } &> /dev/null
 
 			G_DIETPI-NOTIFY 2 "G_THREAD_START_$G_THREAD_COUNT | ${G_THREAD_COMMAND[$G_THREAD_COUNT]}"
 
@@ -2127,13 +2127,13 @@ $logfile_content
 
 		G_CHECK_ROOT_USER 1
 
-		export G_USER_INPUTS=0
+		export G_INTERACTIVE=0
 		/DietPi/dietpi/dietpi-backup -1
 		G_CONFIG_INJECT 'DEV_GITBRANCH=' 'DEV_GITBRANCH=dev' /DietPi/dietpi.txt
 		/DietPi/dietpi/dietpi-update -1
 		/DietPi/dietpi/dietpi-backup 1
 
-		unset G_USER_INPUTS
+		unset G_INTERACTIVE
 
 	}
 
@@ -2150,7 +2150,7 @@ $logfile_content
 	G_DEV_BENCH(){
 
 		echo 1 > /DietPi/dietpi/.dietpi-survey
-		G_USER_INPUTS=0 /DietPi/dietpi/func/dietpi-benchmark 2
+		G_INTERACTIVE=0 /DietPi/dietpi/func/dietpi-benchmark 2
 
 	}
 
