v6.17
+ Due to import tax rises, exports have been reduced: https://github.com/Fourdee/DietPi/issues/2083#issuecomment-429557430

@michaing :smile:

+ Use G_HW_CPU_CORES over nproc

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -76,17 +76,14 @@
 
 		cat << _EOF_ > /DietPi/dietpi/.version
 #!/bin/bash
-export G_DIETPI_VERSION_CORE=$G_DIETPI_VERSION_CORE
-export G_DIETPI_VERSION_SUB=$G_DIETPI_VERSION_SUB
-export G_DIETPI_VERSION_RC=$G_DIETPI_VERSION_RC
-export G_GITBRANCH=$G_GITBRANCH
-export G_GITOWNER=$G_GITOWNER
+G_DIETPI_VERSION_CORE=$G_DIETPI_VERSION_CORE
+G_DIETPI_VERSION_SUB=$G_DIETPI_VERSION_SUB
+G_DIETPI_VERSION_RC=$G_DIETPI_VERSION_RC
+G_GITBRANCH=$G_GITBRANCH
+G_GITOWNER=$G_GITOWNER
 _EOF_
 
 		chmod +x /DietPi/dietpi/.version
-
-		# - Auto reload
-		. /DietPi/dietpi/.version
 
 	}
 
@@ -878,7 +875,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i [d]ietpi)"; then
 	}
 
 	#G_WHIP_INPUTBOX "message"
-	# - Prompt user to input text and export it to G_WHIP_RETURNED_VALUE
+	# - Prompt user to input text and save it to G_WHIP_RETURNED_VALUE
 	# - returns result 0=Ok, everything else considered a user canceled result
 	G_WHIP_INPUTBOX(){
 
@@ -888,7 +885,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i [d]ietpi)"; then
 
 			WHIP_MESSAGE=("$@")
 			G_WHIP_INIT 0
-			export G_WHIP_RETURNED_VALUE=$(whiptail --title "$G_PROGRAM_NAME" --inputbox "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" --default-item "$G_WHIP_DEFAULT_ITEM" --backtitle "$WHIP_BACKTITLE" $WHIP_SIZE_Y $WHIP_SIZE_X "$G_WHIP_DEFAULT_ITEM" 3>&1 1>&2 2>&3; echo $? > /tmp/.G_WHIP_INPUTBOX_RESULT)
+			G_WHIP_RETURNED_VALUE=$(whiptail --title "$G_PROGRAM_NAME" --inputbox "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" --default-item "$G_WHIP_DEFAULT_ITEM" --backtitle "$WHIP_BACKTITLE" $WHIP_SIZE_Y $WHIP_SIZE_X "$G_WHIP_DEFAULT_ITEM" 3>&1 1>&2 2>&3; echo $? > /tmp/.G_WHIP_INPUTBOX_RESULT)
 			result=$(</tmp/.G_WHIP_INPUTBOX_RESULT)
 			if (( $result == 0 )) && [[ -z $G_WHIP_RETURNED_VALUE ]]; then
 
@@ -956,7 +953,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i [d]ietpi)"; then
 
 			WHIP_MESSAGE=("$@")
 			G_WHIP_INIT 1
-			export G_WHIP_RETURNED_VALUE=$(whiptail --title "$G_PROGRAM_NAME" --menu "$WHIP_MESSAGE" --default-item "$G_WHIP_DEFAULT_ITEM" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" --backtitle "$WHIP_BACKTITLE" $WHIP_SIZE_Y $WHIP_SIZE_X $WHIP_SIZE_Z "${G_WHIP_MENU_ARRAY[@]}" 3>&1 1>&2 2>&3; echo $? > /tmp/.WHIP_MENU_RESULT)
+			G_WHIP_RETURNED_VALUE=$(whiptail --title "$G_PROGRAM_NAME" --menu "$WHIP_MESSAGE" --default-item "$G_WHIP_DEFAULT_ITEM" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" --backtitle "$WHIP_BACKTITLE" $WHIP_SIZE_Y $WHIP_SIZE_X $WHIP_SIZE_Z "${G_WHIP_MENU_ARRAY[@]}" 3>&1 1>&2 2>&3; echo $? > /tmp/.WHIP_MENU_RESULT)
 			result=$(</tmp/.WHIP_MENU_RESULT)
 
 			rm /tmp/.WHIP_MENU_RESULT
@@ -980,7 +977,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i [d]ietpi)"; then
 			WHIP_MESSAGE=("$@")
 			G_WHIP_INIT 2
 			G_WHIP_RETURNED_VALUE=$(whiptail --title "$G_PROGRAM_NAME" --checklist "$WHIP_MESSAGE" --separate-output --default-item "$G_WHIP_DEFAULT_ITEM" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" --backtitle "$WHIP_BACKTITLE" $WHIP_SIZE_Y $WHIP_SIZE_X $WHIP_SIZE_Z "${G_WHIP_CHECKLIST_ARRAY[@]}" 3>&1 1>&2 2>&3; echo $? > /tmp/.WHIP_CHECKLIST_RESULT)
-			export G_WHIP_RETURNED_VALUE=$(echo -e "$G_WHIP_RETURNED_VALUE" | tr '\n' ' ')
+			G_WHIP_RETURNED_VALUE=$(echo -e "$G_WHIP_RETURNED_VALUE" | tr '\n' ' ')
 			result=$(</tmp/.WHIP_CHECKLIST_RESULT)
 
 			rm /tmp/.WHIP_CHECKLIST_RESULT
@@ -1399,7 +1396,7 @@ $print_logfile_info
 
 				fi
 
-			#Force exit on failure to end loop (overrides any export G_ERROR_HANDLER_ONERROR_EXIT in this session)
+			#Force exit on failure to end loop (overrides any G_ERROR_HANDLER_ONERROR_EXIT in this session)
 			else
 
 				G_ERROR_HANDLER_ONERROR_EXIT=1
@@ -1993,7 +1990,7 @@ $print_logfile_info
 		done < "$fp_temp"
 
 		# - ps returns usage of each core, so we devide the total by #n cores
-		cpu_usage=$(echo "scale=1;$cpu_usage / $(nproc --all)" | bc -l )
+		cpu_usage=$(echo "scale=1;$cpu_usage / $G_HW_CPU_CORES" | bc -l )
 
 		echo $cpu_usage
 
