v6.18
+ DietPi-Globals | G_CONFIG_INJECT: Re-enable extended regular expression support, as otherwise \( \| \? \+ are specially treated and not literally...
+ DietPi-Globals | G_CONFIG_INJECT: Use more individual option variable names

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -2330,22 +2330,29 @@ $print_logfile_info
 
 	}
 
-	# Inject setting into config file
-	# - First tries to replace old setting, else commented setting and otherwise adds it to end of file.
-	#	- Optionally adds argument to new line after specified pattern $4.
-	#	- PRESERVE=1 G_CONFIG_INJECT allows to keep current setting, if present.
-	#	- BACKUP=1 G_CONFIG_INJECT allows to backup to file before editing, if backup does not yet exist.
-	# - Example: G_CONFIG_INJECT 'prefer-family[[:blank:]=]' 'prefer-family = IPv4' /etc/wgetrc
-	#	- grep basic regex is supported for $1 and $4, thus related special characters need to be escaped manually via leading backslash \, if wanted literally:
-	#		\ . * [ ^ & $ |
-	#	- For setting $2 special character escaping is done internally, thus only single/double quote related escaping is required, if wanted literally:
-	#		- Within double quotes "", as usual, escape literally meant double quotes and dollar signs $ with leading backslash \.
-	#		- Within single quotes '', as usual, escape literally meant single quotes via: '\'' # End leading string; Add escaped single quote; Start trailing string
+	# Inject setting into config file: First tries to replace old setting, else commented setting and otherwise adds to end of file.
+	# Usage:
+	# - $1 Setting pattern to find existing setting with grep extended regular expression support
+	# - $2 Target setting + value, to inject into config file: After bash string expansion (e.g. variables), everything else will be taken literally, thus no further escaping is required.
+	# - $3 Path to config file
+	# - Optional: $4 Line pattern after which the setting will be added instead of end of file with grep extended regular expression support
+	# - GCI_PRESERVE=1 G_CONFIG_INJECT preserves current setting, if present.
+	# - GCI_BACKUP=1 G_CONFIG_INJECT creates a backup before editing the file, if backup does not yet exist, to: $3.bak
+	# - GCI_NEWLINE=1 G_CONFIG_INJECT explicitly expands newlines \n within $2, which by default are taken literally
+	# NB:
+	# - Within double quotes "", as usual, escape literally meant double quotes and dollar signs $ with leading backslash \.
+	# - Within single quotes '', as usual, escape literally meant single quotes via: '\'' # End leading string; Add escaped single quote; Start trailing string
+	# - Additionally in case of extended regular expression support ($1 and $4), the following characters need to be escaped via backslash \, if wanted literally:
+	#	\ . + * ? [ ( { ^ & $ |
+	# Example:
+	# - G_CONFIG_INJECT 'prefer-family[[:blank:]=]' 'prefer-family = IPv4' /etc/wgetrc
 	G_CONFIG_INJECT(){
 
 		[[ $G_PROGRAM_NAME ]] || local G_PROGRAM_NAME='G_CONFIG_INJECT'
 		local pattern="$1"
-		local setting="${2//\\/\\\\}"; setting="${setting//./\\.}"; setting="${setting//\*/\\\*}"; setting="${setting//[/\\[}"; setting="${setting//^/\\^}"; setting="${setting//&/\\&}"; setting="${setting//$/\\$}"; setting="${setting//|/\\|}"
+		local setting="${2//\\/\\\\}"; setting="${setting//./\\.}"; setting="${setting//+/\\+}"; "setting="${setting//\*/\\\*}"; "setting="${setting//\?/\\\?}"; setting="${setting//[/\\[}"
+		setting="${setting//\(/\\\(}"; setting="${setting//{/\\{}"; setting="${setting//^/\\^}"; setting="${setting//&/\\&}"; setting="${setting//$/\\$}"; setting="${setting//|/\\|}"
+		[[ $GCI_NEWLINE == 1 ]] && setting="${setting//\\\\n/\\n}"
 		local file="$3"
 		local after="$4"
 		local error=''
@@ -2363,11 +2370,10 @@ into file \$3
 	$file
 $after
 NB:
- - grep basic regex is supported for matching patterns \$1 and \$4, thus related special characters need to be escaped manually via leading backslash \\, if wanted literally:
- 	\\ . * [ ^ & \$ |
- - For setting \$2 special character escaping is done internally, thus only single/double quote related escaping is required, if wanted literally:
-	- Within double quotes "", as usual, escape literally meant double quotes and dollar signs \$ with leading backslash \\.
-	- Within single quotes '', as usual, escape literally meant single quotes via: '\\'' # End leading string; Add escaped single quote; Start trailing string"
+ - Within double quotes "", as usual, escape literally meant double quotes and dollar signs $ with leading backslash \.
+ - Within single quotes '', as usual, escape literally meant single quotes via: '\'' # End leading string; Add escaped single quote; Start trailing string
+ - Additionally in case of extended regular expression support (\$1 and \$4), the following characters need to be escaped via backslash \, if wanted literally:
+	\ . + * ? [ ( { ^ & $ |
 
 			unset syntax_error
 
@@ -2379,81 +2385,81 @@ NB:
 Please verify the existence of the file \$3
 	$file\n
 Retry with proper permissions or apply the setting manually:
-	$(sed "c\\$setting" <<< '')"
+	$(sed -E "c\\$setting" <<< '')"
 
-		elif error=$(grep -q "^[[:blank:]]*$pattern" $file 2>&1); then
+		elif error=$(grep -Eq "^[[:blank:]]*$pattern" $file 2>&1); then
 			# As an error within the condition leads to result "false", it can be caught only in next "elif"/"else" statement.
 
-			if [[ $PRESERVE == 1 ]]; then
+			if [[ $GCI_PRESERVE == 1 ]]; then
 
-				G_DIETPI-NOTIFY 0 "Current setting in \e[33m$file\e[0m will be preserved: \e[33m$(grep -m1 "^[[:blank:]]*$pattern" $file | sed 's|\\|\\\\|g')\e[0m"
+				G_DIETPI-NOTIFY 0 "Current setting in \e[33m$file\e[0m will be preserved: \e[33m$(grep -Em1 "^[[:blank:]]*$pattern" $file | sed 's|\\|\\\\|g')\e[0m"
 
-			elif error=$(grep -q "^[[:blank:]]*$setting\([[:space:]]\|$\)" $file 2>&1); then
+			elif error=$(grep -Eq "^[[:blank:]]*$setting([[:space:]]|$)" $file 2>&1); then
 
-				G_DIETPI-NOTIFY 0 "Desired setting in \e[33m$file\e[0m was already set: \e[33m$(grep -m1 "^[[:blank:]]*$pattern" $file | sed 's|\\|\\\\|g')\e[0m"
+				G_DIETPI-NOTIFY 0 "Desired setting in \e[33m$file\e[0m was already set: \e[33m$(grep -Em1 "^[[:blank:]]*$pattern" $file | sed 's|\\|\\\\|g')\e[0m"
 
-			elif error=$( (( $(grep -c "^[[:blank:]]*$pattern" $file 2>&1) > 1 )) 2>&1); then
+			elif error=$( (( $(grep -Ec "^[[:blank:]]*$pattern" $file 2>&1) > 1 )) 2>&1); then
 				[[ $error ]] && { syntax_error; return 1; }
 
 				G_WHIP_MSG "[FAILED] Setting was found multiple times\n
 The pattern \$1
-	$(sed "c\\$pattern" <<< '')
+	$(sed -E "c\\$pattern" <<< '')
 was found multiple times in file \$3
 	$file\n
 ____________
-$(grep -n "^[[:blank:]]*$pattern" $file) 
+$(grep -En "^[[:blank:]]*$pattern" $file) 
 ____________\n
 Either the pattern \$1 needs to be more specific or the desired setting can appear multiple times by design and it cannot be predicted which instance to edit.
 Please retry with more specific parameter \$1 or apply the setting manually:
-	$(sed "c\\$setting" <<< '')"
+	$(sed -E "c\\$setting" <<< '')"
 
 			else
 				[[ $error ]] && { syntax_error; return 1; }
 
-				[[ $BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
-				error=$(sed -i "0,\|^[[:blank:]]*$pattern.*$|s||$setting|" $file 2>&1) || { syntax_error; return 1; }
-				G_DIETPI-NOTIFY 0 "Setting in \e[33m$file\e[0m adjusted: \e[33m$(sed "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m"
+				[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
+				error=$(sed -Ei "0,\|^[[:blank:]]*$pattern|s||$setting|" $file 2>&1) || { syntax_error; return 1; }
+				G_DIETPI-NOTIFY 0 "Setting in \e[33m$file\e[0m adjusted: \e[33m$(sed -E "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m"
 
 			fi
 
-		elif error=$(grep -q "^[[:blank:]#;]*$pattern" $file 2>&1); then
+		elif error=$(grep -Eq "^[[:blank:]#;]*$pattern" $file 2>&1); then
 			[[ $error ]] && { syntax_error; return 1; }
 
-			[[ $BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file\e[0m"
-			error=$(sed -i "0,\|^[[:blank:]#;]*$pattern.*$|s||$setting|" $file 2>&1) || { syntax_error; return 1; }
-			G_DIETPI-NOTIFY 0 "Comment in \e[33m$file\e[0m converted to setting: \e[33m$(sed "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m"
+			[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file\e[0m"
+			error=$(sed -Ei "0,\|^[[:blank:]#;]*$pattern|s||$setting|" $file 2>&1) || { syntax_error; return 1; }
+			G_DIETPI-NOTIFY 0 "Comment in \e[33m$file\e[0m converted to setting: \e[33m$(sed -E "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m"
 
 		else
 			[[ $error ]] && { syntax_error; return 1; }
 
 			if [[ $after ]]; then
 
-				if error=$(grep -q "^[[:blank:]]*$after" $file 2>&1); then
+				if error=$(grep -Eq "^[[:blank:]]*$after" $file 2>&1); then
 
-					[[ $BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
-					error=$(sed -i "0,\|^[[:blank:]]*$after.*$|s||&\n$setting|" $file 2>&1) || { syntax_error; return 1; }
-					G_DIETPI-NOTIFY 0 "Added setting \e[33m$(sed "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m to \e[33m$file\e[0m after line \e[33m$(grep -m1 "^[[:blank:]]*$after" $file | sed 's|\\|\\\\|g')\e[0m"
+					[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
+					error=$(sed -Ei "0,\|^[[:blank:]]*$after|s||&\n$setting|" $file 2>&1) || { syntax_error; return 1; }
+					G_DIETPI-NOTIFY 0 "Added setting \e[33m$(sed -E "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m to \e[33m$file\e[0m after line \e[33m$(grep -Em1 "^[[:blank:]]*$after" $file | sed 's|\\|\\\\|g')\e[0m"
 
 				else
 					[[ $error ]] && { syntax_error; return 1; }
 
 					G_WHIP_MSG "[FAILED] Setting could not be added after desired line\n
 The pattern \$4
-	$(sed "c\\$after" <<< '')
+	$(sed -E "c\\$after" <<< '')
 could not be found in file \$3
 	$file\n
 Please retry with valid parameter \$4 or apply the setting manually:
-	$(sed "c\\$setting" <<< '')"
+	$(sed -E "c\\$setting" <<< '')"
 
 				fi
 
 			else
 
-				[[ $BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
+				[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
 				# The following sed does not work on empty files:
 				[[ ! -s $file ]] && echo '# Added by DietPi:' >> $file
-				error=$(sed -i "\$s|\$|\n$setting|" $file 2>&1) || { syntax_error; return 1; }
-				G_DIETPI-NOTIFY 0 "Added setting \e[33m$(sed "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m to end of file \e[33m$file\e[0m"
+				error=$(sed -Ei "\$s|\$|\n$setting|" $file 2>&1) || { syntax_error; return 1; }
+				G_DIETPI-NOTIFY 0 "Added setting \e[33m$(sed -E "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m to end of file \e[33m$file\e[0m"
 
 			fi
 
