v6.35
+ DietPi-Set_hardware | RPi: Do not attempt to start hciuart service directly when enabling Bluetooth. A reboot is required to have the device enabled, otherwise the service start will fail.

diff --git a/dietpi/func/dietpi-set_hardware b/dietpi/func/dietpi-set_hardware
--- a/dietpi/func/dietpi-set_hardware
+++ b/dietpi/func/dietpi-set_hardware
@@ -1067,7 +1067,7 @@ _EOF_
 			if (( $G_HW_MODEL < 10 )) && (( $G_HW_ONBOARD_WIFI )); then
 
 				systemctl disable --now hciuart 2> /dev/null
-				# Disable onboard BT via dtoverlay
+				# Disable onboard Bluetooth via device tree overlay
 				G_CONFIG_INJECT 'dtoverlay=disable-bt' 'dtoverlay=disable-bt' /boot/config.txt
 
 			# ASUS TB
@@ -1084,12 +1084,12 @@ _EOF_
 
 			systemctl disable --now bluetooth 2> /dev/null
 
-			# Unload and blacklist modules, bluetooth last
+			# Unload and blacklist kernel modules, bluetooth last
 			> /etc/modprobe.d/dietpi-disable_bluetooth.conf
 			for ((i=$(( ${#aBLUETOOTH_MODULES[@]} - 1 )); i>=0; i--))
 			do
 
-				modprobe -rf "${aBLUETOOTH_MODULES[$i]}" 2> /dev/null
+				modprobe -r "${aBLUETOOTH_MODULES[$i]}" 2> /dev/null
 				echo "blacklist ${aBLUETOOTH_MODULES[$i]}" >> /etc/modprobe.d/dietpi-disable_bluetooth.conf
 
 			done
@@ -1104,10 +1104,10 @@ _EOF_
 
 		elif [[ $INPUT_DEVICE_VALUE == 'enable' ]]; then
 
-			# Remove module blacklist
-			[[ -f '/etc/modprobe.d/dietpi-disable_bluetooth.conf' ]] && rm /etc/modprobe.d/dietpi-disable_bluetooth.conf
+			# Remove kernel module blacklist
+			[[ -f '/etc/modprobe.d/dietpi-disable_bluetooth.conf' ]] && G_EXEC rm /etc/modprobe.d/dietpi-disable_bluetooth.conf
 
-			# Pre-Reqs
+			# RPi
 			if (( $G_HW_MODEL < 10 )) && (( $G_HW_ONBOARD_WIFI )); then
 
 				# Login console on ttyAMA0 must be disabled: https://github.com/MichaIng/DietPi/issues/2607#issuecomment-470523194
@@ -1120,7 +1120,7 @@ Do you want to continue and disable the serial login console?' || return 1
 				fi
 
 				# Remove dtoverlay
-				sed -i '/^[[:blank:]]*dtoverlay=disable-bt/d' /boot/config.txt
+				G_EXEC sed -i '/^[[:blank:]]*dtoverlay=disable-bt/d' /boot/config.txt
 
 				G_AG_CHECK_INSTALL_PREREQ pi-bluetooth
 
@@ -1128,14 +1128,14 @@ Do you want to continue and disable the serial login console?' || return 1
 
 				# ROCK Pi S: https://wiki.radxa.com/RockpiS/Debian#Bluetooth
 				local rockpis
-				(( $G_HW_MODEL == 73 )) && apt-cache show rtl8723ds-firmware &> /dev/null && rockpis=rtl8723ds-firmware
+				(( $G_HW_MODEL == 73 )) && apt-cache show rtl8723ds-firmware &> /dev/null && rockpis='rtl8723ds-firmware'
 
 				# bluez-firmware: BCM203x dongles: https://packages.debian.org/bluez-firmware
 				G_AG_CHECK_INSTALL_PREREQ bluez bluez-firmware $rockpis
 
 			fi
 
-			# Load modules, bluetooth first
+			# Load kernel modules, bluetooth first
 			for i in "${aBLUETOOTH_MODULES[@]}"
 			do
 
@@ -1143,7 +1143,7 @@ Do you want to continue and disable the serial login console?' || return 1
 
 			done
 
-			# Failsafe, unblock all Bluetooth adapters
+			# Failsafe: Unblock all Bluetooth adapters if rfkill is installed
 			command -v rfkill > /dev/null && rfkill unblock bluetooth
 
 			# Broadcom-based models that need brcm_patchram_plus
@@ -1156,7 +1156,7 @@ Do you want to continue and disable the serial login console?' || return 1
 			G_EXEC systemctl enable --now bluetooth
 
 			# RPi
-			(( $G_HW_MODEL > 9 )) || (( ! $G_HW_ONBOARD_WIFI )) || G_EXEC systemctl enable --now hciuart
+			(( $G_HW_MODEL > 9 )) || (( ! $G_HW_ONBOARD_WIFI )) || G_EXEC systemctl enable hciuart
 
 		else
 
@@ -1508,10 +1508,6 @@ Do you want to continue and DISABLE Bluetooth now?' || return 1
 					[[ ! -f $FP_UENV ]] || grep -q "console=$INPUT_ADDITIONAL" $FP_UENV && return 0
 					echo "console=$INPUT_ADDITIONAL,115200n8" >> $FP_UENV
 
-				#elif (( $G_HW_MODEL == 70 )); then
-
-				#	grep -q "console=$INPUT_ADDITIONAL" $FP_UENV || sed -i "/bootargs=/s/$/ console=$INPUT_ADDITIONAL,115200n8/" $FP_UENV
-
 				fi
 
 			# Enable for all detected Serial/UART devices
@@ -1578,10 +1574,6 @@ Do you want to continue and DISABLE Bluetooth now?' || return 1
 
 					sed -i "/^[[:blank:]]*console=${INPUT_ADDITIONAL}[^\"[:blank:]]*[[:blank:]]*$/d" $FP_UENV # New style: One variable each line
 					sed -i "s/[[:blank:]]*console=${INPUT_ADDITIONAL}[^\"[:blank:]]*//" $FP_UENV # Old style: Multiple variables possible each line
-
-				#elif (( $G_HW_MODEL == 70 )); then
-
-				#	sed -i "s/[[:blank:]]*console=${INPUT_ADDITIONAL}[^\"[:blank:]]*//" $FP_UENV
 
 				fi
 
