v6.23
+ DietPi-Globals | G_CHECK_URL: Minor coding and wording

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -1376,52 +1376,43 @@ $print_logfile_info
 
 	#URL Connection test
 	# - $@ = URL
-	#	Optional inputs = timeout | retry_max | optional_cmd_inputs (eg: --no-check-certificate)
-	#	Prompts user to configure network if $G_USER_INPUTS=1
+	#	Optional variables: $optional_cmd_inputs (eg: --no-check-certificate)
+	#	In case of failure and $G_USER_INPUTS=1: Prompts user to configure network
 	G_CHECK_URL(){
 
 		local string=$@
 		local timeout=$(grep -m1 '^[[:blank:]]*CONFIG_G_CHECK_URL_TIMEOUT=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')
-		local retry_max=$(grep -m1 '^[[:blank:]]*CONFIG_G_CHECK_URL_RETRY=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')
-		local optional_cmd_inputs=${optional_cmd_inputs:-}
+		local attempts=$(grep -m1 '^[[:blank:]]*CONFIG_G_CHECK_URL_ATTEMPTS=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')
+		#local optional_cmd_inputs
 
 		while :
 		do
 
 			G_ERROR_HANDLER_COMMAND="Connection test: $string"
 			G_ERROR_HANDLER_ONERROR_FPLOGFILE='/tmp/G_CHECK_URL'
-
 			G_ERROR_HANDLER_RETRY=1
 
+			G_DIETPI-NOTIFY -2 "Testing connection to $string, please wait..."
+
 			local i=0
-			for ((i=1; i<=$retry_max; i++))
+			for ((i=1; i<=$attempts; i++))
 			do
 
-				G_DIETPI-NOTIFY -2 "($i/$retry_max) Testing connection to $string, please wait..."
-
-				wget --spider $optional_cmd_inputs --timeout=$timeout --tries=1 "$string" &> $G_ERROR_HANDLER_ONERROR_FPLOGFILE
+				# Since --tries/-t is not applied on "fatal" errors (resolving failed, connection refused, 404), we need to loop ourself to exclude any temporary issue
+				wget --spider -t 1 -T $timeout $optional_cmd_inputs "$string" &> $G_ERROR_HANDLER_ONERROR_FPLOGFILE
 				G_ERROR_HANDLER_EXITCODE=$?
-				#	Valid
-				if (( ! $G_ERROR_HANDLER_EXITCODE )); then
 
-					break
+				# Valid
+				(( $G_ERROR_HANDLER_EXITCODE )) || break
 
-				#	Retry
-				else
-
-					sleep 2
-					G_DIETPI-NOTIFY -2 "Failed connection attempt ($i/$retry_max), retrying..."
-
-				fi
+				# Retry
+				G_DIETPI-NOTIFY -2 "Failed connection attempt to $string ($i/$attempts), retrying..."
+				sleep 1
 
 			done
 
 			G_ERROR_HANDLER
-			if (( ! $G_ERROR_HANDLER_EXITCODE )); then
-
-				break
-
-			fi
+			(( $G_ERROR_HANDLER_EXITCODE )) || break
 
 		done
 
