v6.18
+ syntax

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -2418,7 +2418,7 @@ Please retry with more specific parameter \$1 or apply the setting manually:
 				[[ $error ]] && { syntax_error; return 1; }
 
 				[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
-				error=$(sed -Ei "0,\|^[[:blank:]]*$pattern|s||$setting|" $file 2>&1) || { syntax_error; return 1; }
+				error=$(sed -Ei "0,\|^[[:blank:]]*$pattern.*|s||$setting|" $file 2>&1) || { syntax_error; return 1; }
 				G_DIETPI-NOTIFY 0 "Setting in \e[33m$file\e[0m adjusted: \e[33m$(sed -E "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m"
 
 			fi
@@ -2427,7 +2427,7 @@ Please retry with more specific parameter \$1 or apply the setting manually:
 			[[ $error ]] && { syntax_error; return 1; }
 
 			[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file\e[0m"
-			error=$(sed -Ei "0,\|^[[:blank:]#;]*$pattern|s||$setting|" $file 2>&1) || { syntax_error; return 1; }
+			error=$(sed -Ei "0,\|^[[:blank:]#;]*$pattern.*|s||$setting|" $file 2>&1) || { syntax_error; return 1; }
 			G_DIETPI-NOTIFY 0 "Comment in \e[33m$file\e[0m converted to setting: \e[33m$(sed -E "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m"
 
 		else
@@ -2438,7 +2438,7 @@ Please retry with more specific parameter \$1 or apply the setting manually:
 				if error=$(grep -Eq "^[[:blank:]]*$after" $file 2>&1); then
 
 					[[ $GCI_BACKUP == 1 && ! -f $file.bak ]] && cp -a $file $file.bak && G_DIETPI-NOTIFY 2 "Config file backup created: \e[33m$file.bak\e[0m"
-					error=$(sed -Ei "0,\|^[[:blank:]]*$after|s||&\n$setting|" $file 2>&1) || { syntax_error; return 1; }
+					error=$(sed -Ei "0,\|^[[:blank:]]*$after.*|s||&\n$setting|" $file 2>&1) || { syntax_error; return 1; }
 					G_DIETPI-NOTIFY 0 "Added setting \e[33m$(sed -E "c\\$setting" <<< '' | sed 's|\\|\\\\|g')\e[0m to \e[33m$file\e[0m after line \e[33m$(grep -Em1 "^[[:blank:]]*$after" $file | sed 's|\\|\\\\|g')\e[0m"
 
 				else
