v160
Work in progress:
Improved error handle system.
+ G_ERROR_HANDLER
+ G_RUN_CMD (error handled)
+ G_AGX commands are now automatically error handled
https://github.com/Fourdee/DietPi/issues/1311#issuecomment-353716344

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -27,6 +27,16 @@
 	#Ensure we are in users home dir: https://github.com/Fourdee/DietPi/issues/905#issuecomment-298223705
 	cd "$HOME"
 
+	#To be exported by the originating script (eg: dietpi-software)
+	# - Used in:
+	#	G_ERROR_ (info)
+	G_PROGRAM_NAME=''
+
+	#User input?
+	#	Affects:
+	#	 - G_ERROR_HANDLER whiptail display
+	G_USER_INPUTS=1
+
 	# DietPi-Notify
 	# $1:
 	#	-1=autodetect_fail_ok
@@ -63,7 +73,7 @@
 
 		Print_Failed(){
 
-			echo -ne " $bracket_string_l\e[31mFailed\e[0m$bracket_string_r"
+			echo -ne " $bracket_string_l\e[31mError\e[0m$bracket_string_r"
 
 		}
 
@@ -182,6 +192,190 @@
 			exit 1
 
 		fi
+
+	}
+
+
+	#-----------------------------------------------------------------------------------
+	# DietPi Error Handler
+	#-----------------------------------------------------------------------------------
+	G_ERROR_HANDLER_EXITCODE=''					#input value to use with G_ERROR_HANDLER
+	G_ERROR_HANDLER_COMMAND=''					#eg: G_AGI: moooooooo
+	#	For export: On error, following entries will be used
+	G_ERROR_HANDLER_ONERROR_EXIT=1				#Do we exit the program when the error occurs? 0=no 1=yes
+	G_ERROR_HANDLER_ONERROR_FPLOGFILE=''		#FP to logfile, if available
+	G_ERROR_HANDLER_ONERROR_USERMSG=''			#Additional Message we can show user (eg: apt installation failures, please report to us, fixing tips etc)
+
+	#Runs automatically after G_ERROR_HANDLER to reset vars to default
+	G_ERROR_HANDLER_RESET(){
+
+		#unset originating program
+		unset G_ERROR_HANDLER_EXITCODE
+		unset G_ERROR_HANDLER_COMMAND
+
+		unset G_ERROR_HANDLER_ONERROR_EXIT
+		unset G_ERROR_HANDLER_ONERROR_FPLOGFILE
+		unset G_ERROR_HANDLER_ONERROR_USERMSG
+
+		G_ERROR_HANDLER_EXITCODE=''
+		G_ERROR_HANDLER_COMMAND=''
+
+		G_ERROR_HANDLER_ONERROR_EXIT=1
+		G_ERROR_HANDLER_ONERROR_FPLOGFILE=''
+		G_ERROR_HANDLER_ONERROR_USERMSG=''
+
+	}
+
+	#Handles exit code errors, as defined by G_ERROR_HANDLER_xxxx settings, and last exit code of previous command
+	#	eg: 	mkdir /never/gonna/work
+	#			G_ERROR_HANDLER
+	G_ERROR_HANDLER(){
+
+		#No exit code, grab current
+		if [ ! -n $G_ERROR_HANDLER_EXITCODE ]; then
+
+			G_ERROR_HANDLER_EXITCODE=$?
+
+		fi
+
+		#Ok
+		if (( $G_ERROR_HANDLER_EXITCODE == 0 )); then
+
+			G_DIETPI-NOTIFY 0 "$G_ERROR_HANDLER_COMMAND"
+
+		#Error
+		else
+
+			echo ''
+			if [ -n "$G_PROGRAM_NAME" ]; then
+
+				G_DIETPI-NOTIFY 1 "$G_PROGRAM_NAME: $G_ERROR_HANDLER_COMMAND"
+
+			else
+
+				G_DIETPI-NOTIFY 1 "$G_ERROR_HANDLER_COMMAND"
+
+			fi
+
+			G_DIETPI-NOTIFY 2 "exit_code = $G_ERROR_HANDLER_EXITCODE"
+			G_DIETPI-NOTIFY 2 "HW_MODEL:$G_HW_MODEL | HW_ARCH:$G_HW_ARCH | DISTRO:$G_DISTRO"
+
+			# - On Error: Display logfile FP, if set
+			if [ -n "$G_ERROR_HANDLER_ONERROR_FPLOGFILE" ]; then
+
+				G_DIETPI-NOTIFY 2 "Logfile contents:\n$(tail -50 $G_ERROR_HANDLER_ONERROR_FPLOGFILE)"
+
+			fi
+
+			# - On Error: Display user message?
+			if [ -n "$G_ERROR_HANDLER_ONERROR_USERMSG" ]; then
+
+				G_DIETPI-NOTIFY 2 "User message:\n$G_ERROR_HANDLER_ONERROR_USERMSG"
+
+			fi
+
+			#	Display "please report to dietpi", if its one of our programs
+			if [ -n "$G_PROGRAM_NAME" ]; then
+
+				G_DIETPI-NOTIFY 2 'If problems persist, please report this to DietPi for investigation, including a screenshot of this error! (https://github.com/Fourdee/DietPi/issues).'
+
+			fi
+
+			if (( $G_ERROR_HANDLER_ONERROR_EXIT )); then
+
+				G_DIETPI-NOTIFY 2 'Unable to continue, the program will now terminate.'
+
+			fi
+
+			# - On Error: Display whip version?
+			if (( $G_USER_INPUTS )); then
+
+				local whip_msg=()
+				if [ -n "$G_PROGRAM_NAME" ]; then
+
+					whip_msg+="$G_PROGRAM_NAME: $G_ERROR_HANDLER_COMMAND"
+
+				else
+
+					whip_msg+="$G_ERROR_HANDLER_COMMAND"
+
+				fi
+
+				whip_msg+='\n'
+				whip_msg+=" - Exit code = $G_ERROR_HANDLER_EXITCODE"
+				whip_msg+='\n'
+				whip_msg+=" - HW_MODEL:$G_HW_MODEL | HW_ARCH:$G_HW_ARCH | DISTRO:$G_DISTRO"
+				whip_msg+='\n\n'
+
+				#	Display optional logfile?
+				if [ -n "$G_ERROR_HANDLER_ONERROR_FPLOGFILE" ]; then
+
+					whip_msg+="Log file contents:\n$(tail -50 $G_ERROR_HANDLER_ONERROR_FPLOGFILE)"
+					whip_msg+='\n\n'
+
+				fi
+
+				#	Display optional usermessage?
+				if [ -n "$G_ERROR_HANDLER_ONERROR_USERMSG" ]; then
+
+					whip_msg+="$G_ERROR_HANDLER_ONERROR_USERMSG"
+					whip_msg+='\n\n'
+
+				fi
+
+				#	Display "please report to dietpi", if its one of our programs
+				if [ -n "$G_PROGRAM_NAME" ]; then
+
+					whip_msg+="If problems persist, please report this to DietPi for investigation, including a screenshot of this error! (https://github.com/Fourdee/DietPi/issues)."
+
+				fi
+
+				if (( $G_ERROR_HANDLER_ONERROR_EXIT )); then
+
+					whip_msg+='\n\n'
+					whip_msg+='Unable to continue, the program will now terminate.'
+
+				fi
+
+				whiptail --title 'DietPi Error Handler:' --msgbox "$whip_msg" --scrolltext 22 85
+
+			fi
+
+			# - On Error: Kill current script, excluding the shell.
+			if (( $G_ERROR_HANDLER_ONERROR_EXIT )); then
+
+				G_DIETPI-NOTIFY 1 'Unable to continue, this program will now terminate.'
+
+				# - Reset for next run
+				G_ERROR_HANDLER_RESET
+
+				kill -INT $$
+
+			fi
+
+		fi
+
+		return $G_ERROR_HANDLER_EXITCODE
+
+		# - Reset for next run
+		G_ERROR_HANDLER_RESET
+
+	}
+
+	#Run a command and send the output through the error handler. This has the same effect as running G_ERROR_HANDLER afterwards, however, allows for command used info, and log output/view when an error occurs
+	#	$@ = input command
+	#	eg:		G_RUN_CMD mkdir /never/gonna/work
+	G_RUN_CMD(){
+
+		G_ERROR_HANDLER_COMMAND="$@"
+
+		$G_ERROR_HANDLER_COMMAND &> /tmp/G_ERROR_HANDLER_COMMAND
+		G_ERROR_HANDLER_EXITCODE=$?
+		G_ERROR_HANDLER_ONERROR_FPLOGFILE='/tmp/G_ERROR_HANDLER_COMMAND'
+
+		G_ERROR_HANDLER
+
+		rm /tmp/G_ERROR_HANDLER_COMMAND &> /dev/null
 
 	}
 
@@ -330,24 +524,29 @@
 	# URL Connection test
 	#-----------------------------------------------------------------------------------
 	# $1 = URL
+	#	NB: automatically error handled (G_ERROR_HANDLER)
 	G_CHECK_URL(){
 
-		local exit_code=0
+		local string="$1"
 		local timeout=10
 		local retry=2
 
-		G_DIETPI-NOTIFY 2 "Testing connection to $1"
+		G_ERROR_HANDLER_EXITCODE=0
+		G_ERROR_HANDLER_COMMAND="Connection test: $string"
+
+		G_DIETPI-NOTIFY 2 "Testing connection to $string"
 		G_DIETPI-NOTIFY 2 "Max duration of $(($timeout * $retry)) seconds, please wait..."
 
-		wget -q --spider --timeout=$timeout --tries=$retry "$1"
-		exit_code=$?
+		wget -q --spider --timeout=$timeout --tries=$retry "$string"
+		G_ERROR_HANDLER_EXITCODE=$?
 
 		#--no-check-certificate
 		#https://github.com/Fourdee/DietPi/issues/352#issuecomment-221013166
 
-		G_DIETPI-NOTIFY -1 $exit_code "Connection test |"
+		G_ERROR_HANDLER_ONERROR_USERMSG="Connection failed while trying to access: $string. The URL may be offline, or invalid."
+		G_ERROR_HANDLER
 
-		return $exit_code
+		return $G_ERROR_HANDLER_EXITCODE
 
 	}
 
@@ -364,11 +563,12 @@
 
 	# fi
 
+	#apt-get install
+	#	NB: automatically error handled (G_ERROR_HANDLER)
 	G_AGI(){
 
 		local string="$@"
 		local force_options=''
-		local exit_code=0
 
 		if (( $G_DISTRO >= 4 )); then
 
@@ -380,23 +580,28 @@
 
 		fi
 
+		G_ERROR_HANDLER_EXITCODE=0
+		G_ERROR_HANDLER_COMMAND="G_AGI: $string"
+		G_ERROR_HANDLER_ONERROR_FPLOGFILE="$G_FP_LOG_APT"
+
+
 		#-qq can add a slight period of appearing nothing is happening, lets inform user
 		G_DIETPI-NOTIFY 2 "APT installation for: $string"
 		G_DIETPI-NOTIFY 2 "APT is processing, please wait...\n"
 
 		DEBIAN_FRONTEND=noninteractive apt-get install -y -qq $force_options $string 2>&1 | tee "$G_FP_LOG_APT"
-		exit_code=${PIPESTATUS[0]}
+		G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
 
-		G_DIETPI-NOTIFY -1 $exit_code 'G_AGI:'
+		G_ERROR_HANDLER
 
-		return $exit_code
+		return $G_ERROR_HANDLER_EXITCODE
 
 	}
 
 	#apt-get purge
+	#	NB: automatically error handled (G_ERROR_HANDLER)
 	G_AGP(){
 
-		local exit_code=0
 		local string="$@"
 		local options=''
 		if (( $G_DISTRO >= 4 )); then
@@ -405,86 +610,104 @@
 
 		fi
 
+		G_ERROR_HANDLER_EXITCODE=0
+		G_ERROR_HANDLER_COMMAND="G_AGP: $string"
+		G_ERROR_HANDLER_ONERROR_FPLOGFILE="$G_FP_LOG_APT"
+
 		G_DIETPI-NOTIFY 2 "APT removal for: $string"
 
-		DEBIAN_FRONTEND=noninteractive apt-get purge -y $string $options
-		exit_code=${PIPESTATUS[0]}
+		DEBIAN_FRONTEND=noninteractive apt-get purge -y $string $options 2>&1 | tee "$G_FP_LOG_APT"
+		G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
 
-		G_DIETPI-NOTIFY -1 $exit_code 'G_AGP:'
+		G_ERROR_HANDLER
 
-		return $exit_code
+		return $G_ERROR_HANDLER_EXITCODE
+
 	}
 
 	#apt-get autoremove
+	#	NB: automatically error handled (G_ERROR_HANDLER)
 	G_AGA(){
 
-		local exit_code=0
+		G_ERROR_HANDLER_EXITCODE=0
+		G_ERROR_HANDLER_COMMAND="G_AGA:"
+		G_ERROR_HANDLER_ONERROR_FPLOGFILE="$G_FP_LOG_APT"
 
 		G_DIETPI-NOTIFY 2 "APT autoremove + purge"
 
-		DEBIAN_FRONTEND=noninteractive apt-get autoremove --purge -y
-		exit_code=${PIPESTATUS[0]}
+		DEBIAN_FRONTEND=noninteractive apt-get autoremove --purge -y  2>&1 | tee "$G_FP_LOG_APT"
+		G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
 
-		G_DIETPI-NOTIFY -1 $exit_code 'G_AGA:'
+		G_ERROR_HANDLER
 
-		return $exit_code
+		return $G_ERROR_HANDLER_EXITCODE
 
 	}
 
 	#apt-get install -f
+	#	NB: automatically error handled (G_ERROR_HANDLER)
 	G_AGF(){
 
-		local exit_code=0
+		G_ERROR_HANDLER_EXITCODE=0
+		G_ERROR_HANDLER_COMMAND="G_AGF:"
+		G_ERROR_HANDLER_ONERROR_FPLOGFILE="$G_FP_LOG_APT"
 
 		G_DIETPI-NOTIFY 2 "APT fix"
 
 		DEBIAN_FRONTEND=noninteractive apt-get install -f -y 2>&1 | tee "$G_FP_LOG_APT"
-		exit_code=${PIPESTATUS[0]}
+		G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
 
-		G_DIETPI-NOTIFY -1 $exit_code 'G_AGF:'
+		G_ERROR_HANDLER
 
-		return $exit_code
+		return $G_ERROR_HANDLER_EXITCODE
 
 	}
 
 	#apt-get update
+	#	NB: automatically error handled (G_ERROR_HANDLER)
 	G_AGUP(){
 
-		local exit_code=0
+		G_ERROR_HANDLER_EXITCODE=0
+		G_ERROR_HANDLER_COMMAND="G_AGUP:"
+		G_ERROR_HANDLER_ONERROR_FPLOGFILE="$G_FP_LOG_APT"
 
 		G_DIETPI-NOTIFY 2 "APT update"
 
 		DEBIAN_FRONTEND=noninteractive apt-get update 2>&1 | tee "$G_FP_LOG_APT"
-		exit_code=${PIPESTATUS[0]}
+		G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
 
-		G_DIETPI-NOTIFY -1 $exit_code 'G_AGUP:'
+		G_ERROR_HANDLER
 
-		return $exit_code
+		return $G_ERROR_HANDLER_EXITCODE
 
 	}
 
 	#apt-get upgrade
+	#	NB: automatically error handled (G_ERROR_HANDLER)
 	G_AGUG(){
 
-		local exit_code=0
+		G_ERROR_HANDLER_EXITCODE=0
+		G_ERROR_HANDLER_COMMAND="G_AGUG:"
+		G_ERROR_HANDLER_ONERROR_FPLOGFILE="$G_FP_LOG_APT"
 
 		G_DIETPI-NOTIFY 2 "APT upgrade"
 
 		DEBIAN_FRONTEND=noninteractive apt-get upgrade -y 2>&1 | tee "$G_FP_LOG_APT"
-		exit_code=${PIPESTATUS[0]}
+		G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
 
-		G_DIETPI-NOTIFY -1 $exit_code 'G_AGUG:'
+		G_ERROR_HANDLER
 
-		return $exit_code
+		return $G_ERROR_HANDLER_EXITCODE
 
 	}
 
 	#apt-get dist-upgrade
+	#	NB: automatically error handled (G_ERROR_HANDLER)
 	G_AGDUG(){
 
-		local exit_code=0
-		local string="$@"
-		local force_options=''
+		G_ERROR_HANDLER_EXITCODE=0
+		G_ERROR_HANDLER_COMMAND="G_AGDUG:"
+		G_ERROR_HANDLER_ONERROR_FPLOGFILE="$G_FP_LOG_APT"
 
 		if (( $G_DISTRO >= 4 )); then
 
@@ -499,16 +722,17 @@
 		G_DIETPI-NOTIFY 2 "APT dist-upgrade"
 
 		DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y 2>&1 | tee "$G_FP_LOG_APT"
-		exit_code=${PIPESTATUS[0]}
+		G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
 
-		G_DIETPI-NOTIFY -1 $exit_code 'G_AGDUG:'
+		G_ERROR_HANDLER
 
-		return $exit_code
+		return $G_ERROR_HANDLER_EXITCODE
 
 	}
 
 	#Checks for required APT packages, installs if needed.
 	# $@ = list of required packages
+	#	NB: automatically error handled (G_ERROR_HANDLER)
 	G_AG_CHECK_INSTALL_PREREQ(){
 
 		local fp_temp='/tmp/.G_AG_CHECK_INSTALL_PREREQ'
@@ -547,7 +771,7 @@
 
 		fi
 
-		G_DIETPI-NOTIFY -1 $exit_code 'G_AG_CHECK_INSTALL_PREREQ:'
+		#G_AGI now handles the error
 
 		rm "$fp_temp"
 
