v6.2
+ G_AGP | Will now only remove packages which are installed. Non
matching items will be ignored. Supports wildcards. Prevents APT failure
if the package is simply not installed.

@MichaIng
Fixes cases such as "G_AGP debian-keyring" in patch file.

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -898,7 +898,8 @@ $print_logfile_info
 	#	NB: automatically error handled (G_ERROR_HANDLER)
 	G_AGP(){
 
-		local string="$@"
+		local string=( "$@" )
+		local exit_code=0
 		local options=''
 		if (( $G_DISTRO >= 4 )); then
 
@@ -910,10 +911,46 @@ $print_logfile_info
 		G_ERROR_HANDLER_COMMAND="G_AGP: $string"
 		G_ERROR_HANDLER_ONERROR_FPLOGFILE="$G_FP_LOG_APT"
 
-		G_DIETPI-NOTIFY 2 "APT removal for: $string, please wait..."
+		# - Remove non-matching packages from string, which are not installed, to prevent failures.
+		local fp_temp='/tmp/.G_AGP_CHECK_PKG_INSTALLED'
+		local packages_to_remove=''
+		dpkg --get-selections > "$fp_temp"
+		for i in "${string[@]}"
+		do
 
-		DEBIAN_FRONTEND=noninteractive apt-get purge -y $string $options 2>&1 | tee "$G_FP_LOG_APT"
-		G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
+			if (( $(grep -ci -m1 "^$i[[:space:]]" "$fp_temp") ||
+				( $(echo -e "$i" | grep -ci -m1 '*') && $(grep -ci -m1 "^$i" "$fp_temp") ) )); then #wildcard check
+
+				packages_to_remove+="$i "
+
+			else
+
+				G_DIETPI-NOTIFY 2 "Not installed, ignoring: $i"
+
+			fi
+
+		done
+
+		rm "$fp_temp"
+
+		if [ -n "$packages_to_remove" ]; then
+
+			G_DIETPI-NOTIFY 2 "APT removal for: $string, please wait..."
+			DEBIAN_FRONTEND=noninteractive apt-get purge -y $packages_to_remove $options 2>&1 | tee "$G_FP_LOG_APT"
+			G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
+
+		else
+
+			G_DIETPI-NOTIFY 2 "None of the requested packages are currently installed, aborting."
+
+		fi
+
+		# - Never fail if package not found
+		# if (( $(grep -ci -m1 'Unable to locate package' "$G_FP_LOG_APT") )); then
+
+			# G_ERROR_HANDLER_EXITCODE=0
+
+		# fi
 
 		G_ERROR_HANDLER
 
