v8.12
- DietPi-Set_hardware | Enable 3.5mm audio on ROCK Pi 4: https://github.com/MichaIng/DietPi/issues/5941
- DietPi-Set_hardware | Ignore "alsactl -g store" failure in general now: https://github.com/MichaIng/DietPi/discussions/5247#discussioncomment-4236146

diff --git a/dietpi/func/dietpi-set_hardware b/dietpi/func/dietpi-set_hardware
--- a/dietpi/func/dietpi-set_hardware
+++ b/dietpi/func/dietpi-set_hardware
@@ -1645,8 +1645,8 @@ _EOF_
 	# soundcard
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Disable all sound cards and reset all settings
-	Soundcard_Reset_All(){
-
+	Soundcard_Reset_All()
+	{
 		G_DIETPI-NOTIFY 2 'Resetting all sound card settings...'
 
 		# All
@@ -1680,27 +1680,31 @@ _EOF_
 
 			Soundcard_Reset_Odroid
 
-		# - H3
-		elif (( $G_HW_CPUID == 1 )); then
+		# - ASUS TB
+		elif (( $G_HW_MODEL == 52 )); then
 
-			Soundcard_Reset_H3
+			Soundcard_Reset_Asus
 
 		# - Sparky SBC
 		elif (( $G_HW_MODEL == 70 )); then
 
 			Soundcard_Reset_SparkySBC
 
-		# - ASUS TB
-		elif (( $G_HW_MODEL == 52 )); then
+		# - ROCK Pi 4
+		elif (( $G_HW_MODEL == 72 )); then
 
-			Soundcard_Reset_Asus
+			Soundcard_Reset_ROCKPi4
+
+		# - H3
+		elif (( $G_HW_CPUID == 1 )); then
+
+			Soundcard_Reset_H3
 
 		fi
-
 	}
 
-	Soundcard_Reset_RPi(){
-
+	Soundcard_Reset_RPi()
+	{
 		# Remove known sound card device tree overlays
 		sed -i '/^[[:blank:]]*dtoverlay=hifiberry-/d' /boot/config.txt
 		sed -i '/^[[:blank:]]*dtoverlay=iqaudio-/d' /boot/config.txt
@@ -1732,11 +1736,10 @@ _EOF_
 
 		# Use "auto" as default
 		[[ $INPUT_DEVICE_VALUE == 'default' ]] && INPUT_DEVICE_VALUE='rpi-bcm2835-auto'
-
 	}
 
-	Soundcard_Reset_Odroid(){
-
+	Soundcard_Reset_Odroid()
+	{
 		[[ -f '/var/lib/dietpi/postboot.d/c2_smp.sh' ]] && G_EXEC rm /var/lib/dietpi/postboot.d/c2_smp.sh
 
 		# HiFi shield plus
@@ -1753,32 +1756,20 @@ _EOF_
 			G_EXEC rm /etc/systemd/system/odroid-hifishield2.service
 		fi
 		[[ -d '/etc/systemd/system/odroid-hifishield2.service.d' ]] && G_EXEC rm -R /etc/systemd/system/odroid-hifishield2.service.d
-
 	}
 
-	Soundcard_Reset_OdroidN2(){
-
-		# Use HDMI as default
+	Soundcard_Reset_OdroidN2()
+	{
 		[[ $INPUT_DEVICE_VALUE == 'default' ]] && INPUT_DEVICE_VALUE='odroidn2_hdmi'
-
 	}
 
-	Soundcard_Reset_H3(){
-
-		# Set HDMI
-		SOUNDCARD_TARGET_CARD=1
-
+	Soundcard_Reset_Asus()
+	{
+		SOUNDCARD_TARGET_CARD=1 # HDMI
 	}
 
-	Soundcard_Reset_Asus(){
-
-		# Set HDMI
-		SOUNDCARD_TARGET_CARD=1
-
-	}
-
-	Soundcard_Reset_SparkySBC(){
-
+	Soundcard_Reset_SparkySBC()
+	{
 		# Allo Piano DAC
 		sed -i '/^[[:blank:]]*snd-soc-allo-piano-dac/d' /etc/modules
 
@@ -1788,7 +1779,19 @@ _EOF_
 		# Set HDMI
 		SOUNDCARD_TARGET_DEVICE=1
 		[[ $INPUT_DEVICE_VALUE != 'none' && -f '/proc/asound/cards' && $(</proc/asound/cards) ]] && amixer -c 0 set 'audio output mode switch' hdmi
+	}
 
+	Soundcard_Reset_ROCKPi4()
+	{
+		# Enable 3.5mm output, if available: https://github.com/MichaIng/DietPi/issues/5941
+		amixer -c 0 get 'Left Headphone Mixer Left DAC' &> /dev/null || return 0
+		G_EXEC amixer -c 0 set 'Left Headphone Mixer Left DAC' 'on'
+		G_EXEC amixer -c 0 set 'Right Headphone Mixer Right DAC' 'on'
+	}
+
+	Soundcard_Reset_H3()
+	{
+		SOUNDCARD_TARGET_CARD=1 # HDMI
 	}
 
 	Soundcard_Main(){
@@ -2078,7 +2081,6 @@ _EOF_
 				G_EXEC amixer -c 0 set 'FRDDR_A SINK 3 SEL' 'OUT 2'
 				# Set master volume to 85%
 				G_EXEC amixer -c 0 set 'ACODEC' '85%'
-				
 			;;
 
 			'odroidn2_3.5mm')
@@ -2097,7 +2099,6 @@ _EOF_
 				G_EXEC amixer -c 0 set 'FRDDR_A SINK 3 SEL' 'OUT 2'
 				# Set master volume to 85%
 				G_EXEC amixer -c 0 set 'ACODEC' '85%'
-				
 			;;
 
 			# --------------- H3 --------------------
@@ -2215,8 +2216,8 @@ _EOF_
 
 		# Store control states once to assure they are not lost on ungraceful shutdown
 		# - On RPi, this can fail, fake success for now until we find time to further investigate the when and why: https://github.com/MichaIng/DietPi/issues/4306
-		(( $G_HW_MODEL > 9 )) || G_EXEC_NOFAIL=1
-		G_EXEC alsactl -g store
+		# - Fails on ROCK 5B as well, ignore failures in general now, it is not mandatory to succeed here: https://github.com/MichaIng/DietPi/discussions/5247#discussioncomment-4236146
+		G_EXEC_NOFAIL=1 G_EXEC alsactl -g store
 
 		# Buster: Avoid alsa-state.service start if its config file does not exist: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932209
 		(( $G_DISTRO == 5 )) || return 0
