Minor coding enhancements
Use dash instead of bash for printing LE cert status via sudo, merge NOPASSWD check and actual sudo call into one, and avoid command substitutions where possible.

diff --git a/dietpi/func/dietpi-banner b/dietpi/func/dietpi-banner
--- a/dietpi/func/dietpi-banner
+++ b/dietpi/func/dietpi-banner
@@ -182,6 +182,20 @@ $GREEN_LINE"
 		echo -e "$GREEN_BULLET ${aCOLOUR[1]}${aDESCRIPTION[5]} $GREEN_SEPARATOR ${ip:-Use dietpi-config to setup a connection} (${iface:-NONE})"
 	}
 
+	Print_Cert_Status()
+	{
+		# Let's Encrypt cert status - MUST be run as root
+		local i
+		for i in /etc/letsencrypt/live/*/cert.pem
+        	do
+			# shellcheck disable=SC2292
+			[ -f "$i" ] || continue
+			openssl x509 -enddate -noout -in "$i" | mawk '/notAfter=/{print "Valid until "$4"-"substr($1,10)"-"$2" "$3}'
+			return 0
+        	done
+		echo 'No certificate found'
+	}
+
 	Print_Credits()
 	{
 		echo -e " ${aCOLOUR[2]}DietPi Team     : https://github.com/MichaIng/DietPi#the-dietpi-project-team"
@@ -216,19 +230,6 @@ $GREEN_LINE"
 		then
 			echo -e " ${aCOLOUR[1]}reboot$COLOUR_RESET          $GREEN_SEPARATOR ${aCOLOUR[3]}A reboot is required to finalise a recent kernel upgrade$COLOUR_RESET\n"
 		fi
-	}
-
-	Print_Cert_Info()
-	{
-		# Let's Encrypt cert status - MUST be run as root
-		local i certinfo='No certificate found'
-		for i in /etc/letsencrypt/live/*/cert.pem
-        	do
-                [[ -e "$i" ]] || continue
-                certinfo=$(openssl x509 -enddate -noout -in "$i" | mawk '/notAfter=/{print "Valid until "$4"-"substr($1,10)"-"$2" "$3}' 2>&1)
-                break
-        	done
-		echo "$certinfo"
 	}
 
 	Print_Useful_Commands()
@@ -272,23 +273,18 @@ $GREEN_LINE"
 		(( ${aENABLED[8]} == 1 )) && echo -e "$GREEN_BULLET ${aCOLOUR[1]}${aDESCRIPTION[8]} $GREEN_SEPARATOR $(df -h --output=used,size,pcent /mnt/dietpi_userdata | mawk 'NR==2 {print $1" of "$2" ("$3")"}' 2>&1)"
 		# Weather
 		(( ${aENABLED[9]} == 1 )) && echo -e "$GREEN_BULLET ${aCOLOUR[1]}${aDESCRIPTION[9]} $GREEN_SEPARATOR $(curl -sSfLm 3 'https://wttr.in/?format=4' 2>&1)"
-		# Let's Encrypt cert info
+		# Let's Encrypt cert status
 		if (( ${aENABLED[16]} == 1 ))
 		then
-			local certinfo
-			if [[ "$(id -u)" -eq 0 ]];
+			echo -en "$GREEN_BULLET ${aCOLOUR[1]}${aDESCRIPTION[16]} $GREEN_SEPARATOR "
+			if [[ $EUID == 0 ]]
 			then
 				# Running as root
-				certinfo=$(Print_Cert_Info)
-			elif sudo -n true 2>/dev/null
-			then
-				# Not running as root, with NOPASSWD sudo
-				certinfo=$(sudo bash -c "$(declare -f Print_Cert_Info); Print_Cert_Info")
+				Print_Cert_Status 2>&1
 			else
-				# Not running as root, sudo would ask for password
-				certinfo="need NOPASSWD sudo for cert info"
+				# Running as non-root: Fail silently without NOPASSWD to avoid password prompt, but print info instead
+				sudo -n dash -c "$(declare -f Print_Cert_Status); Print_Cert_Status 2>&1" 2> /dev/null || echo 'NOPASSWD sudo required to obtain cert status'
 			fi
-			echo -e "$GREEN_BULLET ${aCOLOUR[1]}${aDESCRIPTION[16]} $GREEN_SEPARATOR $certinfo"
 		fi
 		# Custom
 		(( ${aENABLED[10]} == 1 )) && echo -e "$GREEN_BULLET ${aCOLOUR[1]}${aDESCRIPTION[10]} $GREEN_SEPARATOR $(bash "$FP_CUSTOM" 2>&1)"
