v6.25
+ DietPi-Set_software | APT mirror: "buster-backports" does now exist, so add it by default
+ DietPi-Set_software | Add user: Apply encrypted global software password, if existent
+ DietPi-Set_software | Failsafe, wording and coding enhancements

diff --git a/dietpi/func/dietpi-set_software b/dietpi/func/dietpi-set_software
--- a/dietpi/func/dietpi-set_software
+++ b/dietpi/func/dietpi-set_software
@@ -73,19 +73,15 @@ $FP_SCRIPT	setpermissions		Applies required filesystem permissions to DietPi spe
 			# - Add en_GB.UTF-8 back in, if not chosen, as DietPi scripts require it
 			[[ $INPUT_MODE_VALUE != 'en_GB.UTF-8' ]] && echo 'en_GB.UTF-8 UTF-8' >> /etc/locale.gen
 
-			# - Remove exisiting settings that will break dpkg-reconfigure
+			# - Remove existing settings that will break dpkg-reconfigure
 			[[ -f '/etc/default/locale' ]] && rm /etc/default/locale
 
 			G_RUN_CMD dpkg-reconfigure -f noninteractive locales
 
 			# - Reassign locale, as in case of error (wrong locale variables) update-locale command will produce ugly errors.
-			export LANG=en_GB.UTF8
-			export LC_ALL=en_GB.UTF8
+			export LC_ALL='en_GB.UTF-8'
 
-			# - Update /etc/default/locales with new values (not effective until next load of bash session, eg: logout/in)
-			update-locale "LANG=$INPUT_MODE_VALUE"
-			update-locale "LC_CTYPE=$INPUT_MODE_VALUE"
-			update-locale "LC_TIME=$INPUT_MODE_VALUE"
+			# - Update /etc/default/locales with new value (not effective until next load of bash session, eg: logout/in)
 			update-locale "LC_ALL=$INPUT_MODE_VALUE"
 
 			G_CONFIG_INJECT 'AUTO_SETUP_LOCALE=' "AUTO_SETUP_LOCALE=$INPUT_MODE_VALUE" /DietPi/dietpi.txt
@@ -156,11 +152,6 @@ _EOF_
 					sed -Ei '/jessie-(backports|updates)/d' /etc/apt/sources.list
 					#	- ARMv8 has been dropped from security repo
 					(( $G_HW_ARCH == 3 )) && sed -i '/debian-security/d' /etc/apt/sources.list
-
-				# - Buster, remove backports: https://github.com/MichaIng/DietPi/issues/1285#issuecomment-351830101
-				elif (( $G_DISTRO > 4 )); then
-
-					sed -i '/backports/d' /etc/apt/sources.list
 
 				fi
 
@@ -293,7 +284,8 @@ _EOF_
 			killall -w /DietPi/dietpi/func/run_ntpd &> /dev/null
 
 			local ntp_mirror=$(grep -m1 '^[[:blank:]]*CONFIG_NTP_MIRROR=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')
-			local ntp_mirror_entry='Servers='$ntp_mirror
+			[[ $ntp_mirror ]] || ntp_mirror='default'
+			local ntp_mirror_entry="Servers=$ntp_mirror"
 
 			# - Default, lets timesyncd use DHCP server (Stretch+ only) or fallback to debian.pool.ntp.org.
 			if [[ ${ntp_mirror,,} == 'default' ]]; then
@@ -350,6 +342,7 @@ _EOF_
 			if (( $INPUT_MODE_VALUE == 4 )); then
 
 				G_AG_CHECK_INSTALL_PREREQ dbus
+				systemctl unmask systemd-timesyncd # Failsafe
 				systemctl enable systemd-timesyncd
 				systemctl start systemd-timesyncd
 
@@ -385,10 +378,10 @@ _EOF_
 		elif [[ $INPUT_MODE_VALUE == 'eth_static' ]]; then
 
 			G_CONFIG_INJECT 'iface eth' 'iface eth0 inet static' /etc/network/interfaces
-			G_CONFIG_INJECT 'address ' "address $INPUT_ADDITIONAL_1" /etc/network/interfaces
-			G_CONFIG_INJECT 'gateway ' "gateway $INPUT_ADDITIONAL_2" /etc/network/interfaces
-			G_CONFIG_INJECT 'netmask ' "netmask $INPUT_ADDITIONAL_3" /etc/network/interfaces
-			G_CONFIG_INJECT 'dns-nameservers ' "dns-nameservers $INPUT_ADDITIONAL_4" /etc/network/interfaces
+			G_CONFIG_INJECT 'address ' "address $INPUT_ADDITIONAL_1" /etc/network/interfaces '^[[:blank:]]*iface eth0'
+			G_CONFIG_INJECT 'gateway ' "gateway $INPUT_ADDITIONAL_2" /etc/network/interfaces '^[[:blank:]]*address'
+			G_CONFIG_INJECT 'netmask ' "netmask $INPUT_ADDITIONAL_3" /etc/network/interfaces '^[[:blank:]]*gateway'
+			G_CONFIG_INJECT 'dns-nameservers ' "dns-nameservers $INPUT_ADDITIONAL_4" /etc/network/interfaces '^[[:blank:]]*netmask'
 
 		else
 
@@ -403,44 +396,40 @@ _EOF_
 	#/////////////////////////////////////////////////////////////////////////////////////
 	Setpermissions_Main(){
 
-		# - Failsafe, assure /var/tmp 777 permissions: https://github.com/MichaIng/DietPi/issues/1144#issuecomment-425758727
+		# Failsafe, assure /var/tmp 777 permissions: https://github.com/MichaIng/DietPi/issues/1144#issuecomment-425758727
 		chmod 777 /var/tmp
 
-		# - DietPi-Software secure global_pw encrypted
+		# DietPi-Software secure global_pw encrypted
 		chown root:root /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin
 		chmod 600 /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin
 
-		# - /var/www / www-data
+		# Webserver
 		chown -R www-data:www-data /var/www
 		chmod -R 775 /var/www
 
-		#Apply non-root permissions for files and folders in G_FP_DIETPI_USERDATA
-
+		# Apply non-root permissions for files and folders in G_FP_DIETPI_USERDATA
 		# - dietpi user
 		#	Include symlinked locations via $G_FP_DIETPI_USERDATA/*
 		chown -R dietpi:dietpi /home/dietpi $G_FP_DIETPI_USERDATA $G_FP_DIETPI_USERDATA/*
 		chmod -R 775 $G_FP_DIETPI_USERDATA $G_FP_DIETPI_USERDATA/*
 
-		# - Apply program specific permissions
-		#	NB: Following should be ordered ascending by index to prevent dupes.
-
+		# Apply program specific permissions
+		# - NB: Following should be ordered ascending by index to prevent dupes.
 		# - Desktops
 		chown -R 775 /var/lib/dietpi/dietpi-software/installed/desktop
 		#	Set execute to prevent "untrusted" prompt in Mate, and possibily other desktops.
 		chmod +x /usr/share/applications/*
 		chmod +x /root/Desktop/*
 
-		# - O!MPD, requires write permissions
-		chmod -R 777 /var/www/ompd/tmp # Required for database update
-		chmod -R 777 /var/www/ompd/stream # Required for streaming files
-		chmod -R 777 /var/www/ompd/cache # Required for downloading files
+		# - O!MPD, requires write permissions for database, streaming and downloading
+		chmod -R 777 /var/www/ompd/{tmp,stream,cache}
 
 		# - MPD
 		chmod 0664 /var/log/mpd/mpd.log /etc/mpd.conf
 		chmod -R 775 /var/lib/mpd $G_FP_DIETPI_USERDATA/.mpd_cache
 		chown -R mpd:dietpi /etc/mpd.conf /var/log/mpd $G_FP_DIETPI_USERDATA/.mpd_cache /var/lib/mpd
 
-		# - MyMPD
+		# - myMPD
 		chown -R mympd:dietpi /var/lib/mympd
 
 		# - Mopidy
@@ -581,8 +570,27 @@ _EOF_
 
 		if [[ $INPUT_MODE_VALUE ]]; then
 
-			mkdir -p /home
-			useradd -m -s /bin/bash "$INPUT_MODE_VALUE" -p "$(grep -m1 '^[[:blank:]]*AUTO_SETUP_GLOBAL_PASSWORD=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
+			mkdir -p /home # Failsafe
+
+			# Get global password
+			local pbkdf2=''
+			(( $G_DISTRO > 4 )) && pbkdf2='-iter 10000'
+			# - Encrypted
+			if [[ -f '/var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin' ]]; then
+
+				GLOBAL_PW=$(openssl enc -d -a -md sha256 -aes-256-cbc $pbkdf2 -salt -pass pass:'DietPiRocks!' -in /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin)
+
+			# - DietPi-PREP, 1st run setup or user cancelled manual password choice
+			else
+
+				GLOBAL_PW=$(grep -m1 '^[[:blank:]]*AUTO_SETUP_GLOBAL_PASSWORD=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')
+
+			fi
+			[[ $GLOBAL_PW ]] || GLOBAL_PW='dietpi'
+
+			local usercmd='useradd -m'
+			getent passwd "$INPUT_MODE_VALUE" &> /dev/null && usercmd='usermod'
+			$usercmd "$INPUT_MODE_VALUE" -p "$GLOBAL_PW" -s /bin/bash
 
 			# Copy existing profile/bashrc
 			cp /root/.profile /home/"$INPUT_MODE_VALUE"/
@@ -591,39 +599,14 @@ _EOF_
 			chown -R "$INPUT_MODE_VALUE":"$INPUT_MODE_VALUE" /home/"$INPUT_MODE_VALUE"
 
 			# Allow sudo without pw
-			if ! grep -q "^$INPUT_MODE_VALUE[[:space:]]" /etc/sudoers.d/dietpi; then
+			if ! grep -q "^$INPUT_MODE_VALUE[[:blank:]]" /etc/sudoers.d/dietpi; then
 
 				echo "$INPUT_MODE_VALUE ALL=NOPASSWD: ALL" >> /etc/sudoers.d/dietpi
 
 			fi
 
-			# Same groups as user pi
-			local group_array=()
-			group_array+=('input')
-			group_array+=('netdev')
-			group_array+=('spi')
-			group_array+=('i2c')
-			group_array+=('gpio')
-			group_array+=('tty')
-			group_array+=('users')
-			group_array+=('games')
-			group_array+=('plugdev')
-			group_array+=('video')
-			group_array+=('audio')
-			group_array+=('sudo')
-			group_array+=('cdrom')
-			group_array+=('dialout')
-			group_array+=('adm')
-
-			# Allow access to www-data
-			group_array+=('www-data')
-
-			for i in ${group_array[@]}
-			do
-
-				usermod -a -G $i "$INPUT_MODE_VALUE"
-
-			done
+			# Same groups as user pi + tty + www-data
+			usermod -a -G adm,dialout,chrom,sudo,audio,video,plugdev,games,users,input,netdev,spi,i2c,gpio,tty,www-data "$INPUT_MODE_VALUE"
 
 		else
 
@@ -657,29 +640,25 @@ _EOF_
 		local url="https://raw.githubusercontent.com/MichaIng/DietPi/$G_GITBRANCH/dietpi.txt"
 		if G_CHECK_URL "$url"; then
 
-			G_DIETPI-NOTIFY 0 'Patching dietpi.txt'
-			l_message='Downloading current dietpi.txt' G_RUN_CMD wget "$url" -O /tmp/dietpi.txt_patch
+			G_DIETPI-NOTIFY -2 'Channing dietpi.txt for missing entries'
+			l_message='Downloading current dietpi.txt' G_RUN_CMD wget "$url" -O dietpi.txt_patch
+			sed -Ei '/^([#;/]|$)/d' dietpi.txt_patch
 
 			local entry value
 			while read line
 			do
 
-				entry=$(grep '^[^#;/]' <<< "$line")
-				if [[ $entry ]]; then
+				value=${entry#*=}  # *=X
+				entry=${entry%%=*} # X=*
+				if ! grep -qi "^[[:blank:]]*$entry=" /DietPi/dietpi.txt; then
 
-					value=${entry#*=}  # *=X
-					entry=${entry%%=*} # X=*
-					if ! grep -qi "^[[:blank:]]*$entry=" /DietPi/dietpi.txt; then
-
-						G_DIETPI-NOTIFY 2 "Updating dietpi.txt with new entry: $entry=$value"
-						echo "$entry=$value" >> /DietPi/dietpi.txt
-
-					fi
+					G_DIETPI-NOTIFY 2 "Updating dietpi.txt with new entry: $entry=$value"
+					echo "$entry=$value" >> /DietPi/dietpi.txt
 
 				fi
 
-			done < /tmp/dietpi.txt_patch
-			rm /tmp/dietpi.txt_patch
+			done < dietpi.txt_patch
+			rm dietpi.txt_patch
 
 			G_DIETPI-NOTIFY 0 'dietpi.txt verification completed'
 
@@ -705,19 +684,19 @@ _EOF_
 		else
 
 			# DietPi-Software PW
-			G_WHIP_YESNO 'Do you want to adjust the default global password for DietPi-Software installations and new unix users? We especially recommend to change the default password "dietpi". This does not affect any existing unix user login.\n
-NB: This password will be saved and encrypted within /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin to be useable by DietPi scripts for e.g. web application and database logins. We highly recommend to adjust all passwords for web services and new unix users independently afterwards.'
+			G_WHIP_YESNO 'Do you want to adjust the default global software password for DietPi-Software installations? We especially recommend to change the default password "dietpi". This does not affect any existing software passwords.\n
+NB: This password will be saved and encrypted within "/var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin" to be useable by DietPi scripts for e.g. web application and database logins. We highly recommend to apply individual passwords for each software title after first login.'
 			if (( ! $? )); then
 
-				G_WHIP_PASSWORD "Please enter a new global password:\nNB: The following characters are not supported \$|\\\"'"
+				G_WHIP_PASSWORD "Please enter a new global software password:\nNB: The following characters are not supported \$|\\\"'"
 				pw_dietpi_software=$result
 				unset result
 
 			fi
 
 			# Root/DietPi user PW
-			G_WHIP_YESNO 'Change unix user passwords?\n\nDietPi has two accounts by default "root" and "dietpi". On first boot, both share the global password "dietpi", respectively the one set in dietpi.txt.\n
-It is highly recommended to change this password, ideally, it should be different than the global DietPi-Software password.\n\nWould you like to change the login passwords for "root" and "dietpi"?'
+			G_WHIP_YESNO 'Change existing unix user passwords?\n\nDietPi has two accounts by default "root" and "dietpi". On first boot, both share the global password "dietpi", respectively the one set in "dietpi.txt".\n
+It is highly recommended to change this password, ideally, it should be different than the global software password.\n\nWould you like to change the login passwords for "root" and "dietpi"?'
 			if (( ! $? )); then
 
 				G_WHIP_PASSWORD 'Please enter a new unix user password:'
@@ -743,11 +722,11 @@ It is highly recommended to change this password, ideally, it should be differen
 
 			Setpermissions_Main &> /dev/null
 
-			G_DIETPI-NOTIFY 2 'Global password successfully changed'
+			G_DIETPI-NOTIFY 2 'Global software password successfully changed'
 
 		fi
 
-		# Apply | Root/DietPi users PW
+		# Apply | root/dietpi users PW
 		if [[ $pw_root_dietpi_users ]]; then
 
 			chpasswd <<< "root:$pw_root_dietpi_users"
@@ -803,7 +782,7 @@ It is highly recommended to change this password, ideally, it should be differen
 
 	elif [[ $INPUT_MODE_NAME == 'setpermissions' ]]; then
 
-		Setpermissions_Main &> /dev/null # As no file exist checks are done in bash (quicker to let the program report it missing), hide output
+		Setpermissions_Main &> /dev/null # As no file existence checks are done, hide output
 
 	else
 
