v6.20
+ DietPi-RAMlog | Resolve an issue where non-existent $FP_DIETPI_RAMLOG_SAVE lead to failing RAMlog startup, which prevents it's shutdown task from running as well

diff --git a/dietpi/func/dietpi-ramlog b/dietpi/func/dietpi-ramlog
--- a/dietpi/func/dietpi-ramlog
+++ b/dietpi/func/dietpi-ramlog
@@ -41,18 +41,23 @@
 
 		echo "$(date) | $PROGRAM_NAME: Startup - Restoring log folder structure to RAMdisk..."
 
-		# - Set bit permission
-		chmod 775 /var/log
+		if [[ -d $FP_DIETPI_RAMLOG_SAVE ]]; then
 
-		# - Apply previous attributes and ownerships. Generates empty file if it doesnt exist.
-		[[ -d $FP_DIETPI_RAMLOG_SAVE ]] && cp -R -p --attributes-only $FP_DIETPI_RAMLOG_SAVE/. /var/log/
-		EXIT_CODE=$?; if (( $EXIT_CODE )); then
+			# - Apply previous attributes and ownerships. Generates empty file if it doesnt exist.
+			cp -Rp --attributes-only $FP_DIETPI_RAMLOG_SAVE/. /var/log/
+			EXIT_CODE=$?; if (( $EXIT_CODE )); then
 
-			echo "$(date) | $PROGRAM_NAME: Startup failed with exit code $EXIT_CODE"
+				echo "$(date) | $PROGRAM_NAME: Startup failed with exit code $EXIT_CODE"
+
+			else
+
+				echo "$(date) | $PROGRAM_NAME: Startup completed"
+
+			fi
 
 		else
 
-			echo "$(date) | $PROGRAM_NAME: Startup completed"
+			echo "$(date) | $PROGRAM_NAME: No logs found on disk. Aborting..."
 
 		fi
 
@@ -74,7 +79,7 @@
 		fi
 
 		# - Copy logfile attributes and ownership to storage (not file contents)
-		cp -R -p --attributes-only /var/log/. $FP_DIETPI_RAMLOG_SAVE/
+		cp -Rp --attributes-only /var/log/. $FP_DIETPI_RAMLOG_SAVE/
 		EXIT_CODE=$?; if (( $EXIT_CODE )); then
 
 			echo "$(date) | $PROGRAM_NAME: Shutdown failed with exit code $EXIT_CODE"
