v6.10
+ Global function for https://github.com/Fourdee/DietPi/issues/1846

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -1286,6 +1286,29 @@ $print_logfile_info
 
 	}
 
+	#$1 = directory to test permissions support
+	#Returns 0=ok >=1=failed
+	G_CHECK_FS_PERMISSION_SUPPORT(){
+
+		local fp_input="$1/.test"
+
+		local result=0
+
+		> $fp_input
+		chown 775 $fp_input; result=$?
+
+		if (( $result != 0 )); then
+
+			G_WHIP_MSG "Filesystem does not support permissions (eg: FAT16/32):\n\n$fp_input\n\nPlease select a different drive and/or format it with ext4, ensuring support for filesystem permissions."
+
+		fi
+
+		rm $fp_input &> /dev/null
+
+		return $result
+
+	}
+
 	#Checks if a file/folder exists
 	G_FILE_EXISTS(){
 
