v6.29
+ DietPi-Globals | G_EXEC: Add options to redirect STDOUT and run an additional function before every core function execution
+ DietPi-Globals | Remove G_FILE_EXISTS which we used only a single time and in very most cases it is required to check for file or dir only, allow symlinks or explicitly do not, or similar
+ DietPi-Globals | Use G_EXEC to handle G_CHECK_URL and all G_AG* functions but G_AGP (ToDo)

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -19,7 +19,7 @@
 	# Core variables, functions and environment, used at start of all scripts
 	#-----------------------------------------------------------------------------------
 	# To be set by the originating script, after loading globals and before calling G_INIT()
-	# - Used in G_ERROR_HANDLER, G_WHIP_* and G_DIETPI-NOTIFY functions
+	# - Used in G_EXEC, G_WHIP and G_DIETPI-NOTIFY functions
 	unset G_PROGRAM_NAME
 
 	# Debug mode
@@ -27,7 +27,7 @@
 	#[[ $G_DEBUG == [01] ] || G_DEBUG=0
 
 	# Interactive mode
-	# - Affects whether G_ERROR_ and G_WHIP_ prompts are displayed or not
+	# - Affects whether G_EXEC and G_WHIP prompts are displayed or not
 	# - Run "export G_INTERACTIVE=0" prior to script call to force non-interactive/automated mode.
 	# - Run "unset G_INTERACTIVE" afterwards to return to auto detection.
 	# - If not set, check for STDIN availability:
@@ -896,10 +896,12 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 	# Error handled command execution wrapper
 	#-----------------------------------------------------------------------------------
 	# Required input:
-	# - $1=<command>		| Command to executed
+	# - $@=<command>		| Command to executed
 	# Optional input:
 	# - $G_EXEC_DESC=<text>		| Command description to print instead of raw command string
 	# - $G_EXEC_ATTEMPTS=<int>	| Non-interactive retries in case of error, before doing interactive error prompt
+	# - G_EXEC_RETRY_FUNC(){}	| Function to call before every core command execution, e.g. to re-evaluate variables
+	# - $G_EXEC_REDIRECT=<path>	| Redirect STDOUT to <path>
 	# - $G_EXEC_OUTPUT=1		| Print full command output instead of animated processing message
 	# - $G_EXEC_NOFAIL=1		| On error, override as success, only useful to replace verbose output by animated processing message, inherits $G_EXEC_NOHALT=1 and $G_EXEC_NOEXIT=1
 	# - $G_EXEC_NOHALT=1		| On error, print short error message only, skip error handler menu and do not exit script, inherits $G_EXEC_NOEXIT=1
@@ -908,26 +910,45 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 	# - $G_ECEC_ARRAY_ACTION[]	| Associative array, containing uneven $G_EXEC_ARRAY_TEXT[] values as keys and related commands as values
 	G_EXEC(){
 
-		local exit_code fp_log='/tmp/G_EXEC_LOG' attempt=1
+		local exit_code fp_log='/tmp/G_EXEC_LOG' attempt=1 acommand=("$@")
 
 		# Enter retry loop
 		while :
 		do
+
+			declare -f G_EXEC_RETRY_FUNC &> /dev/null && G_EXEC_RETRY_FUNC
 
 			# Execute command, store output to $fp_log file and store exit code to $exit_code variable
 			# - Print full command output if $G_EXEC_OUTPUT=1 is given
 			if [[ $G_EXEC_OUTPUT == 1 ]]; then
 
 				# Print $G_EXEC_DESC if given, else raw input command string and show current non-interactive attempt count if $G_EXEC_ATTEMPTS is given
-				G_DIETPI-NOTIFY 2 "${G_EXEC_DESC:-$*}${G_EXEC_ATTEMPTS:+ ($attempt/$G_EXEC_ATTEMPTS)"
-				"$@" 2>&1 | tee $fp_log
+				G_DIETPI-NOTIFY 2 "${G_EXEC_DESC:-$*}${G_EXEC_ATTEMPTS:+ ($attempt/$G_EXEC_ATTEMPTS)}"
+				# Redirect STDOUT to $G_EXEC_REDIRECT if given
+				if [[ $G_EXEC_REDIRECT ]]; then
+
+					"${acommand[@]}" 2>&1 > $G_EXEC_REDIRECT | tee $fp_log
+
+				else
+
+					"${acommand[@]}" 2>&1 | tee $fp_log
+
+				fi
 				exit_code=${PIPESTATUS[0]}
 
 			# - Else print animated processing message only
 			else
 
-				G_DIETPI-NOTIFY -2 "${G_EXEC_DESC:-$*}${G_EXEC_ATTEMPTS:+ ($attempt/$G_EXEC_ATTEMPTS)"
-				"$@" &> $fp_log
+				G_DIETPI-NOTIFY -2 "${G_EXEC_DESC:-$*}${G_EXEC_ATTEMPTS:+ ($attempt/$G_EXEC_ATTEMPTS)}"
+				if [[ $G_EXEC_REDIRECT ]]; then
+
+					"${acommand[@]}" > $G_EXEC_REDIRECT 2> $fp_log
+
+				else
+
+					"${acommand[@]}" &> $fp_log
+
+				fi
 				exit_code=$?
 
 			fi
@@ -1087,7 +1108,7 @@ $log_content" || break # Exit error handler menu loop on cancel
 		# - Do not exit originating script if $G_EXEC_NOEXIT=1 or $G_EXEC_NOHALT=1 is given
 		local noexit
 		[[ $G_EXEC_NOEXIT == 1 || $G_EXEC_NOHALT == 1 ]] && noexit=1
-		unset G_EXEC_DESC G_EXEC_ATTEMPTS G_EXEC_OUTPUT G_EXEC_NOFAIL G_EXEC_NOHALT G_EXEC_ARRAY_TEXT G_EXEC_ARRAY_ACTION G_EXEC_NOEXIT
+		unset G_EXEC_DESC G_EXEC_ATTEMPTS G_EXEC_RETRY_FUNC G_EXEC_REDIRECT G_EXEC_OUTPUT G_EXEC_NOFAIL G_EXEC_NOHALT G_EXEC_ARRAY_TEXT G_EXEC_ARRAY_ACTION G_EXEC_NOEXIT
 
 		# In case of unresolved error when exiting originating script, inform user and kill via SIGINT to prevent exiting from interactive shell session
 		[[ $exit_code == 0 || $noexit == 1 ]] || { G_DIETPI-NOTIFY 1 "Unable to continue, ${G_PROGRAM_NAME:-command} will now terminate."; kill -INT $$; }
@@ -1333,102 +1354,41 @@ $logfile_content
 
 	}
 
-	# Run a command and send the output through the error handler. Allows for command used info, and log output/view when an error occurs
-	#	NB: This command does not support inputs with redirects. For file creation, use G_FILE_EXISTS afterwards to check it exists: https://github.com/MichaIng/DietPi/issues/1311#issuecomment-354541417
-	#	NB: automatically error handled (G_ERROR_HANDLER)
-	#	$@ = input command
-	#	eg: G_RUN_CMD mkdir /never/gonna/work
-	G_RUN_CMD(){
-
-		G_CHECK_ROOT_USER 1
-
-		G_ERROR_HANDLER_COMMAND=$@
-
-		G_ERROR_HANDLER_RETRY=1
-		while (( $G_ERROR_HANDLER_RETRY ))
-		do
-
-			G_DIETPI-NOTIFY -2 "${l_message:-$G_ERROR_HANDLER_COMMAND}"
-
-			"$@" &> /tmp/G_ERROR_HANDLER_COMMAND
-			G_ERROR_HANDLER_EXITCODE=$?
-			G_ERROR_HANDLER_ONERROR_FPLOGFILE='/tmp/G_ERROR_HANDLER_COMMAND'
-
-			G_ERROR_HANDLER
-
-		done
-
-		return $G_ERROR_HANDLER_EXITCODE_RETURN
-
-	}
-
 	# URL Connection test
-	# - $@ = URL
-	#	Optional variables:
-	#	- $optional_cmd_inputs (eg: --no-check-certificate)
+	# - $@ = URL + optional arguments
+	# - Optional variables:
 	#	- G_CHECK_URL_TIMEOUT to override default and dietpi.txt set timeout
 	#	- G_CHECK_URL_ATTEMPTS to override default and dietpi.txt set attempts
-	#	In case of failure and $G_INTERACTIVE=1: Prompts user to configure network
+	# - In case of failure and not $G_INTERACTIVE=0: Prompts user to configure network
 	G_CHECK_URL(){
 
-		local url=$@
-		local timeout=10
-		if disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_TIMEOUT" 0; then
+		# Obtain timeout
+		if ! disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_TIMEOUT" 0; then
 
-			timeout=$G_CHECK_URL_TIMEOUT
-			unset G_CHECK_URL_TIMEOUT
-
-		elif [[ -f '/boot/dietpi.txt' ]]; then
-
-			timeout=$(sed -n '/^[[:blank:]]*CONFIG_G_CHECK_URL_TIMEOUT=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
-			disable_error=1 G_CHECK_VALIDINT "$timeout" 0 || timeout=10
-
-		fi
-		local attempts=2
-		if disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_ATTEMPTS" 0; then
-
-			attempts=$G_CHECK_URL_ATTEMPTS
-			unset G_CHECK_URL_ATTEMPTS
-
-		elif [[ -f '/boot/dietpi.txt' ]]; then
-
-			attempts=$(sed -n '/^[[:blank:]]*CONFIG_G_CHECK_URL_ATTEMPTS=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
-			disable_error=1 G_CHECK_VALIDINT "$attempts" 0 || attempts=2
+			G_CHECK_URL_TIMEOUT=$(sed -n '/^[[:blank:]]*CONFIG_G_CHECK_URL_TIMEOUT=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
+			disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_TIMEOUT" 0 || G_CHECK_URL_TIMEOUT=10
 
 		fi
 
-		while :
-		do
+		# Obtain attempts
+		if ! disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_ATTEMPTS" 0; then
 
-			G_ERROR_HANDLER_COMMAND="Connection test: $url"
-			G_ERROR_HANDLER_ONERROR_FPLOGFILE='/tmp/G_CHECK_URL'
-			G_ERROR_HANDLER_RETRY=1
+			G_CHECK_URL_ATTEMPTS=$(sed -n '/^[[:blank:]]*CONFIG_G_CHECK_URL_ATTEMPTS=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
+			disable_error=1 G_CHECK_VALIDINT "$G_CHECK_URL_ATTEMPTS" 0 || G_CHECK_URL_ATTEMPTS=2
 
-			G_DIETPI-NOTIFY -2 "Testing connection to $url, please wait..."
+		fi
 
-			local i=0
-			for ((i=1; i<=$attempts; i++))
-			do
+		# Re-assign timeout ($6 => acommand[5]) on every retry, in case it is changed as solution attempt
+		G_EXEC_RETRY_FUNC(){ acommand[5]=$G_CHECK_URL_TIMEOUT; }
 
-				# Since --tries/-t is not applied on "fatal" errors (resolving failed, connection refused, 404), we need to loop ourself to exclude any temporary issue
-				wget --spider -t 1 -T $timeout $optional_cmd_inputs "$url" &> $G_ERROR_HANDLER_ONERROR_FPLOGFILE
-				G_ERROR_HANDLER_EXITCODE=$?
+		G_EXEC_DESC="Connection test: $*"
+		G_EXEC_ATTEMPTS=$G_CHECK_URL_ATTEMPTS
+		# Since --tries/-t is not applied on "fatal" errors (resolving failed, connection refused, 404), we need to loop ourself to exclude any temporary issue
+		G_EXEC wget --spider -t 1 -T $G_CHECK_URL_TIMEOUT "$@"
+		local exit_code=$?
 
-				# Valid
-				(( $G_ERROR_HANDLER_EXITCODE )) || break
-
-				# Retry
-				G_DIETPI-NOTIFY -2 "Failed connection attempt to $url ($i/$attempts), retrying..."
-				sleep 1
-
-			done
-
-			G_ERROR_HANDLER
-			(( $G_ERROR_HANDLER_EXITCODE )) || break
-
-		done
-
-		return $G_ERROR_HANDLER_EXITCODE_RETURN
+		unset G_CHECK_URL_TIMEOUT G_CHECK_URL_ATTEMPTS
+		return $exit_code
 
 	}
 
@@ -1490,75 +1450,23 @@ $logfile_content
 
 	}
 
-	# Checks if a file/folder exists
-	G_FILE_EXISTS(){
-
-		G_ERROR_HANDLER_COMMAND=$@
-
-		G_DIETPI-NOTIFY -2 "Checking for existance: $G_ERROR_HANDLER_COMMAND"
-
-		local string
-
-		if [[ -f $G_ERROR_HANDLER_COMMAND ]]; then
-
-			string='File exists'
-
-		elif [[ -d $G_ERROR_HANDLER_COMMAND ]]; then
-
-			string='Folder exists'
-
-		else
-
-			string='File/folder does not exist'
-			G_ERROR_HANDLER_EXITCODE=1
-
-		fi
-
-		string+=" | $G_ERROR_HANDLER_COMMAND"
-
-		echo -e "$string" > /tmp/G_ERROR_HANDLER_COMMAND
-		G_ERROR_HANDLER_ONERROR_FPLOGFILE='/tmp/G_ERROR_HANDLER_COMMAND'
-		G_ERROR_HANDLER_COMMAND=$string
-
-		G_ERROR_HANDLER
-
-		[[ -f '/tmp/G_ERROR_HANDLER_COMMAND' ]] && rm -f /tmp/G_ERROR_HANDLER_COMMAND
-
-	}
-
 	#-----------------------------------------------------------------------------------
 	# APT
 	#-----------------------------------------------------------------------------------
 	G_FP_LOG_APT='/tmp/G_APT.log'
 
 	# apt-get install
-	#	NB: automatically error handled (G_ERROR_HANDLER)
+	#	NB: automatically error handled (G_EXEC)
 	G_AGI(){
 
 		G_CHECK_ROOT_USER 1
 
-		local string=$@
 		local options='--allow-change-held-packages'
 
-		G_ERROR_HANDLER_RETRY=1
-		while (( $G_ERROR_HANDLER_RETRY ))
-		do
+		G_EXEC_DESC="\e[0mAPT installation for: \e[33m$*\e[0m, please wait..."
+		G_EXEC_OUTPUT=1 G_EXEC DEBIAN_FRONTEND=noninteractive apt-get -qq $options install "$@"
 
-			G_ERROR_HANDLER_COMMAND="G_AGI $string"
-			G_ERROR_HANDLER_ONERROR_FPLOGFILE=$G_FP_LOG_APT
-
-			# -qq can add a slight period of appearing nothing is happening, lets inform user
-			G_DIETPI-NOTIFY 2 "\e[0mAPT installation for: \e[33m$string\e[0m, please wait..."
-
-			echo -ne '\e[90m'
-			DEBIAN_FRONTEND=noninteractive apt-get -qq $options install $string 2>&1 | tee $G_FP_LOG_APT
-			G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
-
-			G_ERROR_HANDLER
-
-		done
-
-		return $G_ERROR_HANDLER_EXITCODE_RETURN
+		return $?
 
 	}
 
@@ -1580,7 +1488,7 @@ $logfile_content
 
 			G_DIETPI-NOTIFY 2 "\e[0mAPT removal for: \e[33m$string\e[0m, please wait..."
 
-			# - Create one-lined list of matching installed packages, abort if none were found
+			# Create one-lined list of matching installed packages, abort if none were found
 			local packages=$(dpkg --get-selections $string 2> /dev/null | mawk '{print $1}' ORS=' ')
 			if [[ $packages ]]; then
 
@@ -1604,148 +1512,80 @@ $logfile_content
 	}
 
 	# apt-get autoremove
-	#	NB: automatically error handled (G_ERROR_HANDLER)
+	#	NB: automatically error handled (G_EXEC)
 	G_AGA(){
 
 		G_CHECK_ROOT_USER 1
 
-		G_ERROR_HANDLER_RETRY=1
-		while (( $G_ERROR_HANDLER_RETRY ))
-		do
+		G_EXEC_DESC='\e[0mAPT autoremove + purge, please wait...'
+		G_EXEC_OUTPUT=1 G_EXEC DEBIAN_FRONTEND=noninteractive apt-get -qq --purge autoremove
 
-			G_ERROR_HANDLER_COMMAND='G_AGA'
-			G_ERROR_HANDLER_ONERROR_FPLOGFILE=$G_FP_LOG_APT
-
-			G_DIETPI-NOTIFY 2 '\e[0mAPT autoremove + purge, please wait...'
-
-			echo -ne '\e[90m'
-			DEBIAN_FRONTEND=noninteractive apt-get -qq --purge autoremove 2>&1 | tee $G_FP_LOG_APT
-			G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
-
-			G_ERROR_HANDLER
-
-		done
-
-		return $G_ERROR_HANDLER_EXITCODE_RETURN
+		return $?
 
 	}
 
 	# apt-get -f install
-	#	NB: automatically error handled (G_ERROR_HANDLER)
+	#	NB: automatically error handled (G_EXEC)
 	G_AGF(){
 
 		G_CHECK_ROOT_USER 1
 
 		local options='--allow-change-held-packages'
 
-		G_ERROR_HANDLER_RETRY=1
-		while (( $G_ERROR_HANDLER_RETRY ))
-		do
+		G_EXEC_DESC='\e[0mAPT fix, please wait...'
+		G_EXEC_OUTPUT=1 G_EXEC DEBIAN_FRONTEND=noninteractive apt-get -qq $options -f install
 
-			G_ERROR_HANDLER_COMMAND='G_AGF'
-			G_ERROR_HANDLER_ONERROR_FPLOGFILE=$G_FP_LOG_APT
-
-			G_DIETPI-NOTIFY 2 '\e[0mAPT fix, please wait...'
-
-			echo -ne '\e[90m'
-			DEBIAN_FRONTEND=noninteractive apt-get -qq $options -f install 2>&1 | tee $G_FP_LOG_APT
-			G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
-
-			G_ERROR_HANDLER
-
-		done
-
-		return $G_ERROR_HANDLER_EXITCODE_RETURN
+		return $?
 
 	}
 
 	# apt-get clean + update
-	#	NB: automatically error handled (G_ERROR_HANDLER)
+	#	NB: automatically error handled (G_EXEC)
 	G_AGUP(){
 
 		G_CHECK_ROOT_USER 1
 
-		G_ERROR_HANDLER_RETRY=1
-		while (( $G_ERROR_HANDLER_RETRY ))
-		do
+		# Clean cache before every update, which can corrupt and gets fully rewritten anyway
+		G_EXEC_RETRY_FUNC(){ apt-get clean; }
 
-			G_ERROR_HANDLER_COMMAND='G_AGUP'
-			G_ERROR_HANDLER_ONERROR_FPLOGFILE=$G_FP_LOG_APT
+		G_EXEC_DESC='\e[0mAPT update, please wait...'
+		G_EXEC_OUTPUT=1 G_EXEC apt-get -q update
 
-			G_DIETPI-NOTIFY 2 '\e[0mAPT update, please wait...'
-
-			echo -ne '\e[90m'
-			DEBIAN_FRONTEND=noninteractive apt-get clean 2>&1 | tee $G_FP_LOG_APT
-			DEBIAN_FRONTEND=noninteractive apt-get -q update 2>&1 | tee -a $G_FP_LOG_APT
-			G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
-
-			G_ERROR_HANDLER
-
-		done
-
-		return $G_ERROR_HANDLER_EXITCODE_RETURN
+		return $?
 
 	}
 
 	# apt-get upgrade
-	#	NB: automatically error handled (G_ERROR_HANDLER)
+	#	NB: automatically error handled (G_EXEC)
 	G_AGUG(){
 
 		G_CHECK_ROOT_USER 1
 
-		G_ERROR_HANDLER_RETRY=1
-		while (( $G_ERROR_HANDLER_RETRY ))
-		do
+		G_EXEC_DESC='\e[0mAPT upgrade, please wait...'
+		G_EXEC_OUTPUT=1 G_EXEC DEBIAN_FRONTEND=noninteractive apt-get -qq upgrade
 
-			G_ERROR_HANDLER_COMMAND='G_AGUG'
-			G_ERROR_HANDLER_ONERROR_FPLOGFILE=$G_FP_LOG_APT
-
-			G_DIETPI-NOTIFY 2 '\e[0mAPT upgrade, please wait...'
-
-			echo -ne '\e[90m'
-			DEBIAN_FRONTEND=noninteractive apt-get -qq upgrade 2>&1 | tee $G_FP_LOG_APT
-			G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
-
-			G_ERROR_HANDLER
-
-		done
-
-		return $G_ERROR_HANDLER_EXITCODE_RETURN
+		return $?
 
 	}
 
 	# apt-get dist-upgrade
-	#	NB: automatically error handled (G_ERROR_HANDLER)
+	#	NB: automatically error handled (G_EXEC)
 	G_AGDUG(){
 
 		G_CHECK_ROOT_USER 1
 
 		local options='--allow-change-held-packages'
 
-		G_ERROR_HANDLER_RETRY=1
-		while (( $G_ERROR_HANDLER_RETRY ))
-		do
+		G_EXEC_DESC='\e[0mAPT dist-upgrade, please wait...'
+		G_EXEC_OUTPUT=1 G_EXEC DEBIAN_FRONTEND=noninteractive apt-get -qq $options dist-upgrade
 
-			G_ERROR_HANDLER_COMMAND='G_AGDUG'
-			G_ERROR_HANDLER_ONERROR_FPLOGFILE=$G_FP_LOG_APT
-
-			G_DIETPI-NOTIFY 2 '\e[0mAPT dist-upgrade, please wait...'
-
-			echo -ne '\e[90m'
-			DEBIAN_FRONTEND=noninteractive apt-get -qq $options dist-upgrade 2>&1 | tee $G_FP_LOG_APT
-			G_ERROR_HANDLER_EXITCODE=${PIPESTATUS[0]}
-
-			G_ERROR_HANDLER
-
-		done
-
-		return $G_ERROR_HANDLER_EXITCODE_RETURN
+		return $?
 
 	}
 
 	# Checks for required APT packages, installs if needed.
 	# $@ = list of required packages
-	#	NB: automatically error handled (G_ERROR_HANDLER)
+	#	NB: automatically error handled (G_EXEC)
 	G_AG_CHECK_INSTALL_PREREQ(){
 
 		G_CHECK_ROOT_USER 1
