v6.0
+ Manually handle G_CHECK_URL retries.

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -759,7 +759,7 @@ $print_logfile_info
 
 		local string="$@"
 		local timeout=10
-		local retry=2
+		local retry_max=5
 		local error_connection_failed=0
 
 		G_ERROR_HANDLER_EXITCODE=0
@@ -806,15 +806,28 @@ $print_logfile_info
 
 			fi
 
-			G_DIETPI-NOTIFY -2 "Testing connection to $string for max $(($timeout * $retry)) seconds"
+			for ((i=1; i<=$retry_max; i++))
+			do
 
-			wget --spider --timeout=$timeout --tries=$retry "$string" &> /tmp/G_CHECK_URL
-			G_ERROR_HANDLER_EXITCODE=$?
-			if (( $G_ERROR_HANDLER_EXITCODE != 0 )); then
+				G_DIETPI-NOTIFY -2 "($i/$retry_max) Testing connection to $string, please wait..."
 
-				error_connection_failed=1
+				wget --spider --timeout=$timeout --tries=1 "$string" &> /tmp/G_CHECK_URL
+				G_ERROR_HANDLER_EXITCODE=$?
+				#	Valid
+				if (( $G_ERROR_HANDLER_EXITCODE == 0 )); then
 
-			fi
+					break
+
+				#	Retry
+				else
+
+					sleep 2
+					error_connection_failed=1
+					G_DIETPI-NOTIFY -2 "Failed connection attempt ($i/$retry_max), retrying..."
+
+				fi
+
+			done
 
 			#--no-check-certificate
 			#https://github.com/Fourdee/DietPi/issues/352#issuecomment-221013166
