v6.15
+ G_RUN_CMD_INFO_ONLY renamed to G_ERROR_HANDLER_INFO_ONLY

+ G_ERROR_HANDLER_NO_FAIL option

https://github.com/Fourdee/DietPi/issues/316

@michaing RE:

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -1060,7 +1060,8 @@ $(ps f -eo pid,user,tty,cmd | grep -i [d]ietpi)"
 	G_ERROR_HANDLER_EXITCODE_RETURN=0			#Same as above, but not destroyed during G_ERROR_HANDLER_RESET, allowing us to return it in funcs
 	G_ERROR_HANDLER_COMMAND=''					#eg: G_AGI: moooooooo
 	#	For export: On error, following entries will be used
-	G_RUN_CMD_INFO_ONLY=0						#Only print info and retry options, no exit or bug report, sets G_ERROR_HANDLER_ONERROR_EXIT=1 automatically
+	G_ERROR_HANDLER_NO_FAIL=0					#Always report a success, regardless of the exit code
+	G_ERROR_HANDLER_INFO_ONLY=0					#Only print info and retry options, no exit or bug report, sets G_ERROR_HANDLER_ONERROR_EXIT=0 automatically
 	G_ERROR_HANDLER_ONERROR_EXIT=1				#Do we exit the program when the error occurs? 0=no 1=yes
 	G_ERROR_HANDLER_ONERROR_FPLOGFILE=''		#FP to logfile, if available
 	G_ERROR_HANDLER_RETRY=0						#Used in func with while loop to re-run func as needed
@@ -1074,20 +1075,20 @@ $(ps f -eo pid,user,tty,cmd | grep -i [d]ietpi)"
 		unset G_ERROR_HANDLER_EXITCODE
 		unset G_ERROR_HANDLER_COMMAND
 
+		unset G_ERROR_HANDLER_NO_FAIL
+		unset G_ERROR_HANDLER_INFO_ONLY
 		unset G_ERROR_HANDLER_ONERROR_EXIT
 		unset G_ERROR_HANDLER_ONERROR_FPLOGFILE
-
 		unset G_ERROR_HANDLER_RETRY
-		unset G_RUN_CMD_INFO_ONLY
 
 		G_ERROR_HANDLER_EXITCODE=0
 		G_ERROR_HANDLER_COMMAND=''
 
+		G_ERROR_HANDLER_NO_FAIL=0
+		G_ERROR_HANDLER_INFO_ONLY=0
 		G_ERROR_HANDLER_ONERROR_EXIT=1
 		G_ERROR_HANDLER_ONERROR_FPLOGFILE=''
-
 		G_ERROR_HANDLER_RETRY=0
-		G_RUN_CMD_INFO_ONLY=0
 
 	}
 
@@ -1098,7 +1099,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i [d]ietpi)"
 		[[ $l_message ]] || local l_message="$G_ERROR_HANDLER_COMMAND"
 
 		#Ok
-		if (( ! $G_ERROR_HANDLER_EXITCODE )); then
+		if (( ! $G_ERROR_HANDLER_EXITCODE || $G_ERROR_HANDLER_NO_FAIL )); then
 
 			G_DIETPI-NOTIFY 0 "$l_message"
 			G_ERROR_HANDLER_RESET
@@ -1109,7 +1110,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i [d]ietpi)"
 			local send_bugreport=0
 			local bugreport_id='N/A'
 
-			if (( $G_RUN_CMD_INFO_ONLY )); then
+			if (( $G_ERROR_HANDLER_INFO_ONLY )); then
 
 				G_ERROR_HANDLER_ONERROR_EXIT=0
 
@@ -1135,7 +1136,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i [d]ietpi)"
 			G_DIETPI-NOTIFY 1 "$G_ERROR_HANDLER_COMMAND"
 
 			#	Display "please report to dietpi", if its one of our programs
-			if [[ $G_PROGRAM_NAME && ! $G_RUN_CMD_INFO_ONLY ]]; then
+			if [[ $G_PROGRAM_NAME && ! $G_ERROR_HANDLER_INFO_ONLY ]]; then
 
 				G_DIETPI-NOTIFY 2 "$print_report_to_dietpi_info"
 
@@ -1170,7 +1171,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i [d]ietpi)"
 				fi
 
 				#	Display "please report to dietpi", if its one of our programs
-				if [[ $G_PROGRAM_NAME && ! $G_RUN_CMD_INFO_ONLY ]]; then
+				if [[ $G_PROGRAM_NAME && ! $G_ERROR_HANDLER_INFO_ONLY ]]; then
 
 					whip_msg+="$print_report_to_dietpi_info"
 
@@ -1191,14 +1192,14 @@ $(ps f -eo pid,user,tty,cmd | grep -i [d]ietpi)"
 					local retry_menu_options_count=0
 					aretry_menu_options+=('Retry' 'Re-run the last command that failed'); ((retry_menu_options_count++))
 
-					if ! ps aux | grep -qi '[d]ietpi-config' && (( ! $G_RUN_CMD_INFO_ONLY )); then
+					if ! ps aux | grep -qi '[d]ietpi-config' && (( ! $G_ERROR_HANDLER_INFO_ONLY )); then
 
 
 						aretry_menu_options+=('DietPi-Config' 'Edit network, APT/NTP mirror settings etc'); ((retry_menu_options_count++))
 
 					fi
 
-					if [[ $G_PROGRAM_NAME && ! $G_RUN_CMD_INFO_ONLY ]]; then
+					if [[ $G_PROGRAM_NAME && ! $G_ERROR_HANDLER_INFO_ONLY ]]; then
 
 						aretry_menu_options+=('Send report' 'Uploads bugreport containing system info to DietPi'); ((retry_menu_options_count++))
 
@@ -1248,7 +1249,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i [d]ietpi)"
 			fi
 
 			#Github printout
-			if (( ! $G_RUN_CMD_INFO_ONLY )); then
+			if (( ! $G_ERROR_HANDLER_INFO_ONLY )); then
 
 				echo -e "
 \e[41m
