v123
+ hciattach service check/restart:
https://github.com/Fourdee/DietPi/issues/376#issuecomment-230150821

diff --git a/dietpi/func/dietpi-set_wifi_bt b/dietpi/func/dietpi-set_wifi_bt
--- a/dietpi/func/dietpi-set_wifi_bt
+++ b/dietpi/func/dietpi-set_wifi_bt
@@ -124,8 +124,28 @@ _EOF_
 
 			# + RPi 3
 			if (( $HW_MODEL == 3 )); then
+
 				systemctl enable hciuart
-				systemctl start hciuart
+
+				#Start service again, if it fails: https://github.com/Fourdee/DietPi/issues/376#issuecomment-230149754
+				loop_count=0
+				max_count=3
+				while (( $(systemctl start hciuart;echo $?) != 0 ))
+				do
+
+					if (( $loop_count >= $max_count )); then
+						echo -e "\nERROR: hciuart failed to start after $loop_count attempts\n"
+						break
+					else
+						echo -e "\nINFO: hciuart failed to start. Attempting to restart it...\n"
+						((loop_count++))
+						sleep 1
+					fi
+
+				done
+
+				#/usr/bin/hciattach /dev/serial1 bcm43xx 921600 noflow -
+
 			fi
 
 		fi
