v6.3
G_WHIP optimizations/tweaks.

initial run of G_WHIP in dietpi-software

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -427,6 +427,10 @@
 	#G_WHIP_DEFAULT_ITEM | to be set by scripts to set the default selected item.
 	G_WHIP_DEFAULT_ITEM=''
 
+	#G_WHIP_BUTTON_X_TEXT | Change as needed, else, defaults to Ok/Cancel
+	G_WHIP_BUTTON_OK_TEXT=''
+	G_WHIP_BUTTON_CANCEL_TEXT=''
+
 	#G_WHIP_MENU_ARRAY | to be set by scripts to set available menu/checkbox options
 	G_WHIP_MENU_ARRAY=('NULL' 'NULL')
 
@@ -436,14 +440,43 @@
 	#G_WHIP_RETURNED_VALUE | Returned value from inputbox/menu/checklist based whiptail items
 	G_WHIP_RETURNED_VALUE=''
 
-	#G_WHIP_SIZE_UPDATE | update target whiptail size, based on current screen dimensions.
+	#G_WHIP_DESTROY | Clear vars after run of whiptail
+	G_WHIP_DESTROY(){
+
+		# - Delete
+		unset WHIP_MESSAGE
+		unset WHIP_SIZE_X
+		unset WHIP_SIZE_Y
+		unset WHIP_SIZE_Z
+		unset WHIP_BACKTITLE
+
+		# - Reset
+		G_WHIP_BUTTON_OK_TEXT=''
+		G_WHIP_BUTTON_CANCEL_TEXT=''
+		G_WHIP_MENU_ARRAY=('NULL' 'NULL')
+		G_WHIP_CHECKLIST_ARRAY=('NULL' 'NULL' 'off')
+
+	}
+
+	#G_WHIP_INIT
+	# - update target whiptail size, based on current screen dimensions.
 	# - Used by G_WHIP_ automatically, doesn't need to be a global function, however, bash does not support local functions.
 	# - $1 = calculate Z? 0=no 1=yes (G_WHIP_MENU_ARRAY) 2=yes (G_WHIP_CHECKLIST_ARRAY)
-	G_WHIP_SIZE_X=0
-	G_WHIP_SIZE_Y=0
-	G_WHIP_SIZE_Z=0
-	G_WHIP_SIZE_UPDATE(){
+	G_WHIP_INIT(){
 
+		#Set default button text, if not defined
+		G_WHIP_BUTTON_OK_TEXT=${G_WHIP_BUTTON_OK_TEXT:=Ok}
+		G_WHIP_BUTTON_CANCEL_TEXT=${G_WHIP_BUTTON_CANCEL_TEXT:=Cancel}
+
+		#Update backtitle
+		WHIP_BACKTITLE="$G_PROGRAM_NAME | $G_HW_MODEL_DESCRIPTION"
+		if [ -f /DietPi/dietpi/.network ]; then
+
+			WHIP_BACKTITLE+=" | IP: $(sed -n 4p /DietPi/dietpi/.network)"
+
+		fi
+
+		#Automaticaly set size of whiptail box and contents
 		local calculate_z=$1
 
 		# - Whip margins
@@ -455,23 +488,22 @@
 		local lines_required_whip_z=0
 
 		# - Set current screen dimensions ( - outside margin)
-		G_WHIP_SIZE_X=$(( $(tput cols) - 6 ))
-		if (( $G_WHIP_SIZE_X > 120 )); then
+		WHIP_SIZE_X=$(( $(tput cols) - 6 ))
+		if (( $WHIP_SIZE_X > 120 )); then
 
-			G_WHIP_SIZE_X=120
-
-		fi
-
-		G_WHIP_SIZE_Y=$(( $(tput lines) - 4 ))
-		if (( $G_WHIP_SIZE_Y > 40 )); then
-
-			G_WHIP_SIZE_Y=40
+			WHIP_SIZE_X=120
 
 		fi
 
-		G_WHIP_SIZE_Z=0
+		WHIP_SIZE_Y=$(( $(tput lines) - 4 ))
+		if (( $WHIP_SIZE_Y > 40 )); then
 
-		#Calculate Z?
+			WHIP_SIZE_Y=40
+
+		fi
+
+		WHIP_SIZE_Z=2
+
 		# - G_WHIP_MENU_ARRAY
 		if (( $calculate_z == 1 )); then
 
@@ -499,14 +531,14 @@
 
 		fi
 
-		#Calulate lines required for WHIP_MESSAGE, as displayed inside the whiptail box
-		# - This can then be used to increase/decrease size of G_WHIP_SIZE_Z automatically.
+		# - Calulate lines required for WHIP_MESSAGE, as displayed inside the whiptail box
+		#	This can then be used to increase/decrease size of WHIP_SIZE_Z automatically.
 		if [ -n "$WHIP_MESSAGE" ]; then
 
 			local line_count=$(echo -e "$WHIP_MESSAGE" | grep -c '^')
 
-			# - Lines required to fit text inside whiptail box. accomodate whip margins: 2 chars each side of G_WHIP_SIZE_X
-			lines_required_whip_y=$(( $lines_required_whip_y + $line_count + ( ${#WHIP_MESSAGE} / ( $G_WHIP_SIZE_X - $whip_x_internal_margin ) ) ))
+			# - Lines required to fit text inside whiptail box. accomodate whip margins: 2 chars each side of WHIP_SIZE_X
+			lines_required_whip_y=$(( $lines_required_whip_y + $line_count + ( ${#WHIP_MESSAGE} / ( $WHIP_SIZE_X - $whip_x_internal_margin ) ) ))
 
 			#DEBUG:
 			echo "WHIP_MESSAGE line count $line_count"
@@ -515,16 +547,16 @@
 
 		fi
 
-		#Process final whiptail size
-		# - Add internal whiptail margins to end line total
+		# - Process final whiptail size
+		#	Add internal whiptail margins to end line total
 		lines_required_whip_y=$(( $lines_required_whip_y + $whip_y_internal_margin ))
 
 		# - Message will not fit!
-		if (( $lines_required_whip_y > $G_WHIP_SIZE_Y )); then
+		if (( $lines_required_whip_y > $WHIP_SIZE_Y )); then
 
-			G_DIETPI-NOTIFY 1 "Lines required for Whiptail box and its contents, exceeds screen dimensions."
+			G_DIETPI-NOTIFY 1 "Lines required for Whiptail box and its contents (y=$lines_required_whip_y, z=$lines_required_whip_z), exceeds screen dimensions (y=$WHIP_SIZE_Y)."
 
-		# - Calculate a lower size of G_WHIP_SIZE_Y to fit everything and make it look nice!
+		# - Calculate a lower size of WHIP_SIZE_Y to fit everything and make it look nice!
 		else
 
 			# - Calc max size for lines_max_whip_z, based on lines_required_whip_y and current screen size
@@ -532,43 +564,42 @@
 
 				local lines_max_whip_z=$lines_required_whip_z
 
-				while (( ( $lines_max_whip_z + $lines_required_whip_y ) > $G_WHIP_SIZE_Y ))
+				while (( ( $lines_max_whip_z + $lines_required_whip_y ) > $WHIP_SIZE_Y ))
 				do
 
 					((lines_max_whip_z--))
 
 				done
 
-				#	lines_max_whip_z < 1 indicates G_WHIP_SIZE_Y is too small to fit all message text and any lines_required_whip_z.
+				#	lines_max_whip_z < 1 indicates WHIP_SIZE_Y is too small to fit all message text and any lines_required_whip_z.
 				#	So we must force lines_max_whip_z=1 resulting in some missing message text
 				if (( $lines_max_whip_z < 1 )); then
 
-					lines_max_whip_z=1
-					G_DIETPI-NOTIFY 1 "Lines required for Whiptail box and its contents (including lines_required_whip_z), exceeds screen dimensions."
+					lines_max_whip_z=2
+					G_DIETPI-NOTIFY 1 "Lines required for Whiptail box and its contents (y=$lines_required_whip_y, z=$lines_required_whip_z), exceeds screen dimensions (y=$WHIP_SIZE_Y)."
 
 				fi
 
-				G_WHIP_SIZE_Y=$(( $lines_required_whip_y + $lines_max_whip_z ))
-				G_WHIP_SIZE_Z=$lines_max_whip_z
+				WHIP_SIZE_Y=$(( $lines_required_whip_y + $lines_max_whip_z ))
+				WHIP_SIZE_Z=$lines_max_whip_z
 
 			else
 
-				G_WHIP_SIZE_Y=$lines_required_whip_y
+				WHIP_SIZE_Y=$lines_required_whip_y
 
 			fi
 
-
-			#DEBUG:
-			echo -e "lines_required_whip_y $lines_required_whip_y"
-			echo -e "lines_required_whip_z $lines_required_whip_z"
-			echo -e "G_WHIP_SIZE_X $G_WHIP_SIZE_X"
-			echo -e "G_WHIP_SIZE_Y $G_WHIP_SIZE_Y"
-			echo -e "G_WHIP_SIZE_Z $G_WHIP_SIZE_Z"
-			echo -e "X_SCREEN = $(( $(tput cols) - 6 ))"
-			echo -e "Y_SCREEN = $(( $(tput lines) - 4 ))"
-			#DEBUG:
-
 		fi
+
+		#DEBUG:
+		echo -e "lines_required_whip_y $lines_required_whip_y"
+		echo -e "lines_required_whip_z $lines_required_whip_z"
+		echo -e "WHIP_SIZE_X $WHIP_SIZE_X"
+		echo -e "WHIP_SIZE_Y $WHIP_SIZE_Y"
+		echo -e "WHIP_SIZE_Z $WHIP_SIZE_Z"
+		echo -e "X_SCREEN = $(( $(tput cols) - 6 ))"
+		echo -e "Y_SCREEN = $(( $(tput lines) - 4 ))"
+		#DEBUG:
 
 	}
 
@@ -580,8 +611,8 @@
 
 		if (( $G_USER_INPUTS )); then
 
-			G_WHIP_SIZE_UPDATE 0
-			whiptail --title "$G_PROGRAM_NAME" --msgbox "$WHIP_MESSAGE" --backtitle "$G_PROGRAM_NAME" $G_WHIP_SIZE_Y $G_WHIP_SIZE_X
+			G_WHIP_INIT 0
+			whiptail --title "$G_PROGRAM_NAME" --msgbox "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --backtitle "$WHIP_BACKTITLE" $WHIP_SIZE_Y $WHIP_SIZE_X
 
 		else
 
@@ -589,7 +620,7 @@
 
 		fi
 
-		unset WHIP_MESSAGE
+		G_WHIP_DESTROY
 
 	}
 
@@ -603,13 +634,13 @@
 
 		if (( $G_USER_INPUTS )); then
 
-			G_WHIP_SIZE_UPDATE 0
-			whiptail --title "$G_PROGRAM_NAME" --yesno "$WHIP_MESSAGE" --backtitle "$G_PROGRAM_NAME" --yes-button "Ok" --no-button "Cancel" --defaultno $G_WHIP_SIZE_Y $G_WHIP_SIZE_X
+			G_WHIP_INIT 0
+			whiptail --title "$G_PROGRAM_NAME" --yesno "$WHIP_MESSAGE" --backtitle "$WHIP_BACKTITLE" --yes-button "$G_WHIP_BUTTON_OK_TEXT" --no-button "$G_WHIP_BUTTON_CANCEL_TEXT" --defaultno $WHIP_SIZE_Y $WHIP_SIZE_X
 			result=$?
 
 		fi
 
-		unset WHIP_MESSAGE
+		G_WHIP_DESTROY
 
 		return $result
 
@@ -625,15 +656,15 @@
 
 		if (( $G_USER_INPUTS )); then
 
-			G_WHIP_SIZE_UPDATE 0
-			export G_WHIP_RETURNED_VALUE=$(whiptail --title "$G_PROGRAM_NAME" --inputbox "$WHIP_MESSAGE" --backtitle "$G_PROGRAM_NAME" $G_WHIP_SIZE_Y $G_WHIP_SIZE_X "$G_WHIP_DEFAULT_ITEM" 3>&1 1>&2 2>&3; echo $? > /tmp/.G_WHIP_INPUTBOX_RESULT)
+			G_WHIP_INIT 0
+			export G_WHIP_RETURNED_VALUE=$(whiptail --title "$G_PROGRAM_NAME" --inputbox "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" --backtitle "$WHIP_BACKTITLE" $WHIP_SIZE_Y $WHIP_SIZE_X "$G_WHIP_DEFAULT_ITEM" 3>&1 1>&2 2>&3; echo $? > /tmp/.G_WHIP_INPUTBOX_RESULT)
 
 			result=$(cat /tmp/.G_WHIP_INPUTBOX_RESULT)
 			rm /tmp/.G_WHIP_INPUTBOX_RESULT
 
 		fi
 
-		unset WHIP_MESSAGE
+		G_WHIP_DESTROY
 
 		return $result
 
@@ -649,18 +680,16 @@
 
 		if (( $G_USER_INPUTS )); then
 
-			G_WHIP_SIZE_UPDATE 1
-			export G_WHIP_RETURNED_VALUE=$(whiptail --title "$G_PROGRAM_NAME" --menu "$WHIP_MESSAGE" --default-item "$G_WHIP_DEFAULT_ITEM" --cancel-button "Cancel" --backtitle "$G_PROGRAM_NAME" $G_WHIP_SIZE_Y $G_WHIP_SIZE_X $G_WHIP_SIZE_Z "${G_WHIP_MENU_ARRAY[@]}" 3>&1 1>&2 2>&3; echo $? > /tmp/.G_WHIP_MENU_RESULT)
+			G_WHIP_INIT 1
+			export G_WHIP_RETURNED_VALUE=$(whiptail --title "$G_PROGRAM_NAME" --menu "$WHIP_MESSAGE" --default-item "$G_WHIP_DEFAULT_ITEM" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" --backtitle "$WHIP_BACKTITLE" $WHIP_SIZE_Y $WHIP_SIZE_X $WHIP_SIZE_Z "${G_WHIP_MENU_ARRAY[@]}" 3>&1 1>&2 2>&3; echo $? > /tmp/.WHIP_MENU_RESULT)
 
-			result=$(cat /tmp/.G_WHIP_MENU_RESULT)
-			rm /tmp/.G_WHIP_MENU_RESULT
+			result=$(cat /tmp/.WHIP_MENU_RESULT)
+			rm /tmp/.WHIP_MENU_RESULT
 
-			unset G_WHIP_MENU_ARRAY
-			export G_WHIP_MENU_ARRAY=('NULL' 'NULL')
 
 		fi
 
-		unset WHIP_MESSAGE
+		G_WHIP_DESTROY
 
 		return $result
 
@@ -676,18 +705,15 @@
 
 		if (( $G_USER_INPUTS )); then
 
-			G_WHIP_SIZE_UPDATE 2
-			export G_WHIP_RETURNED_VALUE=$(whiptail --title "$G_PROGRAM_NAME" --checklist "$WHIP_MESSAGE" --separate-output --default-item "$G_WHIP_DEFAULT_ITEM" --cancel-button "Cancel" --backtitle "$G_PROGRAM_NAME" $G_WHIP_SIZE_Y $G_WHIP_SIZE_X $G_WHIP_SIZE_Z "${G_WHIP_CHECKLIST_ARRAY[@]}" 3>&1 1>&2 2>&3; echo $? > /tmp/.G_WHIP_CHECKLIST_RESULT)
+			G_WHIP_INIT 2
+			export G_WHIP_RETURNED_VALUE=$(whiptail --title "$G_PROGRAM_NAME" --checklist "$WHIP_MESSAGE" --separate-output --default-item "$G_WHIP_DEFAULT_ITEM" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" --backtitle "$WHIP_BACKTITLE" $WHIP_SIZE_Y $WHIP_SIZE_X $WHIP_SIZE_Z "${G_WHIP_CHECKLIST_ARRAY[@]}" 3>&1 1>&2 2>&3; echo $? > /tmp/.WHIP_CHECKLIST_RESULT)
 
-			result=$(cat /tmp/.G_WHIP_CHECKLIST_RESULT)
-			rm /tmp/.G_WHIP_CHECKLIST_RESULT
-
-			unset G_WHIP_CHECKLIST_ARRAY
-			export G_WHIP_CHECKLIST_ARRAY=('NULL' 'NULL' 'off')
+			result=$(cat /tmp/.WHIP_CHECKLIST_RESULT)
+			rm /tmp/.WHIP_CHECKLIST_RESULT
 
 		fi
 
-		unset WHIP_MESSAGE
+		G_WHIP_DESTROY
 
 		return $result
 
@@ -708,10 +734,12 @@
 				#G_FILE_EXISTS "$fp_log"
 				#???
 
-				G_WHIP_SIZE_UPDATE 0
-				whiptail --title "$G_PROGRAM_NAME | Log viewer" --textbox "$fp_log"  --backtitle "$G_PROGRAM_NAME" --scrolltext $G_WHIP_SIZE_Y $G_WHIP_SIZE_X
+				G_WHIP_INIT 0
+				whiptail --title "$G_PROGRAM_NAME | Log viewer" --textbox "$fp_log" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --backtitle "$WHIP_BACKTITLE" --scrolltext $WHIP_SIZE_Y $WHIP_SIZE_X
 
 			fi
+
+			G_WHIP_DESTROY
 
 		fi
 
@@ -1123,7 +1151,7 @@ $print_logfile_info
 				if (( $error_connection_failed )); then
 
 					#Ask to check settings,
-					whiptail --title "URL Connection Test Failed" --yesno "DietPi was unable to establish a connection:\n - $string\n\nIf problems persist, the URL may be offline/unreachable.\n\nWould you like to configure network settings and try again?" --yes-button "Ok" --no-button "Exit" --defaultno --backtitle "$G_PROGRAM_NAME" 15 80
+					whiptail --title "URL Connection Test Failed" --yesno "DietPi was unable to establish a connection:\n - $string\n\nIf problems persist, the URL may be offline/unreachable.\n\nWould you like to configure network settings and try again?" --yes-button "Ok" --no-button "Exit" --defaultno --backtitle "$WHIP_BACKTITLE" 15 80
 					CHOICE=$?
 
 					#run dietpi config
