v6.9
+ DietPi-Globals | Add G_WHIP_PASSWORD for masked password inputs and secure non-global result handling

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -768,6 +768,27 @@
 
 	}
 
+	#G_WHIP_PASSWORD "message"
+	# - Prompt user to input password and return it. Do not export for security reasons!
+	# - No return value is considered as user cancel
+	G_WHIP_PASSWORD(){
+
+		local result=''
+		WHIP_MESSAGE=("$@")
+
+		if (( $G_USER_INPUTS )); then
+
+			G_WHIP_INIT 0
+			result=$(whiptail --title "$G_PROGRAM_NAME" --passwordbox "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" --backtitle "$WHIP_BACKTITLE" $WHIP_SIZE_Y $WHIP_SIZE_X 3>&1 1>&2 2>&3)
+
+		fi
+
+		G_WHIP_DESTROY
+
+		return $result
+
+	}
+
 	#G_WHIP_MENU "message"
 	# - Prompt user to select option from G_WHIP_MENU_ARRAY and sets G_WHIP_RETURNED_VALUE
 	# - returns result 0=Ok, everything else considered a user canceled result
