v6.27 (#3222)
+ DietPi-Config | RPi4: Add a menu entry to install and update the RPi4 EEPROM firmware
+ DietPi-Set_hardware | Add RPi4 EEPROM update command "rpi-eeprom" to install/upgrade required APT packages and update bootloader and VL805 USB firmware on devices' EEPROM
+ DietPi-Software | RPi4: Install/update EEPROM on firstrun setup automatically: https://github.com/MichaIng/DietPi/pull/3222
+ DietPi-Software | GLOBAL_PW: Do not decrypt/read the password earlier than required, i.e. directly before first software installs start. On firstrun setup it is therefore required to read it once (from dietpi.txt expectedly) to re-apply it as well for UNIX users.
+ DietPi-Software | Skip APT simulation install. G_AGUP (which includes cache clean: "apt-get clean") and G_AGUG are error handled, hence include the test already.
+ DietPi-Patch | Install/update EEPROM on RPi4 automatically: https://github.com/MichaIng/DietPi/issues/3217

diff --git a/dietpi/func/dietpi-set_hardware b/dietpi/func/dietpi-set_hardware
--- a/dietpi/func/dietpi-set_hardware
+++ b/dietpi/func/dietpi-set_hardware
@@ -29,6 +29,7 @@ $FP_SCRIPT	gpumemsplit		64/128/256 # RPi only
 $FP_SCRIPT	rpi-camera		enable/disable
 $FP_SCRIPT	rpi-opengl		vc4-kms-v3d/vc4-fkms-v3d/disable
 $FP_SCRIPT	rpi3_usb_boot		enable
+$FP_SCRIPT	rpi-eeprom
 "	#////////////////////////////////////
 
 	# Grab Inputs
@@ -189,6 +190,27 @@ _EOF_
 			Unknown_Input_Mode
 
 		fi
+
+	}
+
+	#/////////////////////////////////////////////////////////////////////////////////////
+	# rpi-eeprom: https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md
+	#/////////////////////////////////////////////////////////////////////////////////////
+	RPi_EEPROM(){
+
+		(( $G_HW_MODEL == 4 )) || { Unsupported_Input_Name; return 1; } # Exit path for non-RPi4
+
+		# Install required APT package, be failsafe and install/upgrade VC firmware and bootloader as well
+		G_AGUP
+		G_AGI rpi-eeprom rpi-eeprom-images flashrom libraspberrypi-bin raspberrypi-bootloader
+		# - Workaround: https://github.com/RPi-Distro/repo/issues/156
+		G_AG_CHECK_INSTALL_PREREQ binutils
+
+		# Update/flash new bootloader and VL805 USB firmware to EEPROM
+		rpi-eeprom-update -a
+
+		# Required? Enable update service to run on every boot
+		systemctl enable rpi-eeprom-update
 
 	}
 
@@ -2229,6 +2251,10 @@ _EOF_
 	elif [[ $INPUT_DEVICE_NAME == 'rpi3_usb_boot' ]]; then
 
 		RPi_USB_Boot_Main
+
+	elif [[ $INPUT_DEVICE_NAME == 'rpi-eeprom' ]]; then
+
+		RPi_EEPROM
 
 	elif [[ $INPUT_DEVICE_NAME == 'headless' ]]; then
 
