v6.27
+ DietPi-Globals | G_WHIP: Further tuning

diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -529,8 +529,6 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 	# G_WHIP_DESTROY | Clear vars after run of whiptail
 	G_WHIP_DESTROY(){
 
-		unset WHIP_SIZE_X WHIP_SIZE_Y WHIP_SIZE_Z
-		unset WHIP_BACKTITLE WHIP_SCROLLTEXT
 		unset G_WHIP_DEFAULT_ITEM G_WHIP_SIZE_X_MAX
 		unset G_WHIP_BUTTON_OK_TEXT G_WHIP_BUTTON_CANCEL_TEXT
 		unset G_WHIP_MENU_ARRAY G_WHIP_CHECKLIST_ARRAY
@@ -738,6 +736,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 		if (( $G_INTERACTIVE )); then
 
+			local WHIP_BACKTITLE WHIP_SCROLLTEXT WHIP_SIZE_X WHIP_SIZE_Y
 			G_WHIP_INIT
 			whiptail ${G_PROGRAM_NAME+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --msgbox "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" $WHIP_SCROLLTEXT $WHIP_SIZE_Y $WHIP_SIZE_X
 
@@ -760,7 +759,7 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 		if (( $G_INTERACTIVE )); then
 
-			local WHIP_MESSAGE=$@
+			local WHIP_BACKTITLE WHIP_SCROLLTEXT WHIP_SIZE_X WHIP_SIZE_Y WHIP_MESSAGE=$@
 			G_WHIP_INIT
 			local default_no='--defaultno'
 			[[ ${G_WHIP_DEFAULT_ITEM,,} == 'yes' || ${G_WHIP_DEFAULT_ITEM,,} == 'ok' ]] && default_no=
@@ -784,16 +783,17 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 		if (( $G_INTERACTIVE )); then
 
-			local WHIP_MESSAGE=$@
-			G_WHIP_INIT
-			G_WHIP_RETURNED_VALUE=$(whiptail ${G_PROGRAM_NAME+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --inputbox "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" $WHIP_SCROLLTEXT $WHIP_SIZE_Y $WHIP_SIZE_X "$G_WHIP_DEFAULT_ITEM" 3>&1 1>&2 2>&3-; echo $? > /tmp/.G_WHIP_INPUTBOX_RESULT)
-			result=$(</tmp/.G_WHIP_INPUTBOX_RESULT); rm /tmp/.G_WHIP_INPUTBOX_RESULT
-			if [[ $result == 0 && -z $G_WHIP_RETURNED_VALUE ]]; then
+			local error WHIP_BACKTITLE WHIP_SCROLLTEXT WHIP_SIZE_X WHIP_SIZE_Y WHIP_MESSAGE=$@
+			while :
+			do
 
-				result=1
-				whiptail ${G_PROGRAM_NAME+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --msgbox '[FAILED] An input value was not entered.' 9 60
+				G_WHIP_INIT
+				G_WHIP_RETURNED_VALUE=$(whiptail ${G_PROGRAM_NAME+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --inputbox "$error$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" $WHIP_SCROLLTEXT $WHIP_SIZE_Y $WHIP_SIZE_X "$G_WHIP_DEFAULT_ITEM" 3>&1 1>&2 2>&3-; echo $? > /tmp/.G_WHIP_INPUTBOX_RESULT)
+				result=$(</tmp/.G_WHIP_INPUTBOX_RESULT); rm /tmp/.G_WHIP_INPUTBOX_RESULT
+				[[ $result == 0 && -z $G_WHIP_RETURNED_VALUE ]] && { error='[FAILED] An input value was not entered, please try again...\n\n'; continue; }
+				break
 
-			fi
+			done
 
 		fi
 
@@ -808,29 +808,22 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 	G_WHIP_PASSWORD(){
 
 		local return_value=1
-		result=
+		unset result # in case left from last call
 
 		if (( $G_INTERACTIVE )); then
 
-			local WHIP_MESSAGE=$@
-			G_WHIP_INIT
-
+			local error WHIP_BACKTITLE WHIP_SCROLLTEXT WHIP_SIZE_X WHIP_SIZE_Y WHIP_MESSAGE=$@
 			while :
 			do
 
-				local password_0=$(whiptail ${G_PROGRAM_NAME+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --passwordbox "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --nocancel $WHIP_SCROLLTEXT $WHIP_SIZE_Y $WHIP_SIZE_X 3>&1 1>&2 2>&3-)
+				G_WHIP_INIT
+				local password_0=$(whiptail ${G_PROGRAM_NAME+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --passwordbox "$error$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --nocancel $WHIP_SCROLLTEXT $WHIP_SIZE_Y $WHIP_SIZE_X 3>&1 1>&2 2>&3-)
+				[[ $password_0 ]] || { error='[FAILED] No password entered, please try again...\n\n'; continue; }
 				local password_1=$(whiptail ${G_PROGRAM_NAME+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --passwordbox 'Please enter the new password again:' --ok-button "$G_WHIP_BUTTON_OK_TEXT" --nocancel $WHIP_SCROLLTEXT $WHIP_SIZE_Y $WHIP_SIZE_X 3>&1 1>&2 2>&3-)
-				if [[ $password_0 && $password_0 == "$password_1" ]]; then
-
-					result=$password_0
-					return_value=0
-					break
-
-				else
-
-					whiptail ${G_PROGRAM_NAME+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --msgbox '[FAILED] No password entered, or invalid match.\n\nPlease try again...' --ok-button 'Retry' 9 60
-
-				fi
+				[[ $password_0 == "$password_1" ]] || { error='[FAILED] Passwords do not match, please try again...\n\n'; continue; }
+				result=$password_0
+				return_value=0
+				break
 
 			done
 
@@ -847,11 +840,11 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 	G_WHIP_MENU(){
 
 		local result=1
-		unset G_WHIP_RETURNED_VALUE # in case left from last G_WHIP
+		unset G_WHIP_RETURNED_VALUE # in case left from last call
 
 		if (( $G_INTERACTIVE )); then
 
-			local WHIP_MESSAGE=$@
+			local WHIP_BACKTITLE WHIP_SCROLLTEXT WHIP_SIZE_X WHIP_SIZE_Y WHIP_SIZE_Z WHIP_MESSAGE=$@
 			G_WHIP_INIT 2
 			G_WHIP_RETURNED_VALUE=$(whiptail ${G_PROGRAM_NAME+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --menu "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" --default-item "$G_WHIP_DEFAULT_ITEM" $WHIP_SCROLLTEXT $WHIP_SIZE_Y $WHIP_SIZE_X $WHIP_SIZE_Z "${G_WHIP_MENU_ARRAY[@]}" 3>&1 1>&2 2>&3-; echo $? > /tmp/.WHIP_MENU_RESULT)
 			result=$(</tmp/.WHIP_MENU_RESULT); rm /tmp/.WHIP_MENU_RESULT
@@ -869,11 +862,11 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 	G_WHIP_CHECKLIST(){
 
 		local result=1
-		unset G_WHIP_RETURNED_VALUE # in case left from last G_WHIP
+		unset G_WHIP_RETURNED_VALUE # in case left from last call
 
 		if (( $G_INTERACTIVE )); then
 
-			local WHIP_MESSAGE=$@
+			local WHIP_BACKTITLE WHIP_SCROLLTEXT WHIP_SIZE_X WHIP_SIZE_Y WHIP_SIZE_Z WHIP_MESSAGE=$@
 			G_WHIP_INIT 3
 			G_WHIP_RETURNED_VALUE=$(whiptail ${G_PROGRAM_NAME+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --checklist "$WHIP_MESSAGE" --separate-output --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" --default-item "$G_WHIP_DEFAULT_ITEM" $WHIP_SCROLLTEXT $WHIP_SIZE_Y $WHIP_SIZE_X $WHIP_SIZE_Z "${G_WHIP_CHECKLIST_ARRAY[@]}" 3>&1 1>&2 2>&3-; echo $? > /tmp/.WHIP_CHECKLIST_RESULT)
 			G_WHIP_RETURNED_VALUE=$(echo -e "$G_WHIP_RETURNED_VALUE" | tr '\n' ' ')
@@ -894,29 +887,17 @@ $(ps f -eo pid,user,tty,cmd | grep -i '[d]ietpi')"; then
 
 		if (( $G_INTERACTIVE )); then
 
-			local log=${log:-0} # Optional yes/no prompt for viewing logs
-			local fp_file=$1
+			if [[ -f $1 ]]; then
 
-			if [[ -f $fp_file ]]; then
-
-				# Log file view with prompt
-				if (( $log )); then
-
-					G_WHIP_YESNO "Would you like to view the contents of the following logfile?\n - $fp_file\n\nThis will contain further additional information, that may be required by the user."
-					result=$?
-
-				fi
-
-				if (( ! $result )); then
-
-					G_WHIP_INIT
-					whiptail --title "${G_PROGRAM_NAME+$G_PROGRAM_NAME | }File viewer" --backtitle "$WHIP_BACKTITLE" --textbox $fp_file --ok-button "$G_WHIP_BUTTON_OK_TEXT" $WHIP_SCROLLTEXT $WHIP_SIZE_Y $WHIP_SIZE_X
-
-				fi
+				local WHIP_BACKTITLE WHIP_SCROLLTEXT WHIP_SIZE_X WHIP_SIZE_Y WHIP_TEXTFILE=$1
+				G_WHIP_INIT
+				local header='File viewer'
+				[[ $log == 1 ]] && header='Log viewer'
+				whiptail --title "${G_PROGRAM_NAME+$G_PROGRAM_NAME | }$header" --backtitle "$WHIP_BACKTITLE" --textbox "$WHIP_TEXTFILE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" $WHIP_SCROLLTEXT $WHIP_SIZE_Y $WHIP_SIZE_X
 
 			else
 
-				G_WHIP_MSG "[FAILED] File does not exist: $fp_file"
+				G_WHIP_MSG "[FAILED] File does not exist: $1"
 				result=1
 
 			fi
