v6.13
+ DietPi-Set_userdata | Remove checks loop to avoid confusing log file output and terminal output about already existing symlink

diff --git a/dietpi/func/dietpi-set_userdata b/dietpi/func/dietpi-set_userdata
--- a/dietpi/func/dietpi-set_userdata
+++ b/dietpi/func/dietpi-set_userdata
@@ -85,76 +85,70 @@
 	G_DIETPI-NOTIFY 2 " - To   : $TARGET_DIRECTORY"
 	G_DIETPI-NOTIFY 2 'Please wait...'
 
-	while :
-	do
+	# Sanity checks
+	# - Check for both inputs
+	if [[ -z $SOURCE_DIRECTORY || -z $TARGET_DIRECTORY ]]; then
 
-		# Sanity checks
-		# - Check for both inputs
-		if [[ -z $SOURCE_DIRECTORY || -z $TARGET_DIRECTORY ]]; then
+		LOGFILE_OUTPUT_TEXT="ERROR: Please provide a source ($SOURCE_DIRECTORY) and target ($TARGET_DIRECTORY) directory for input."
+		EXIT_CODE=1
 
-			LOGFILE_OUTPUT_TEXT="ERROR: Please provide a source ($SOURCE_DIRECTORY) and target ($TARGET_DIRECTORY) directory for input."
-			EXIT_CODE=1
-			break
+	# - Check if symlink is already pointing to target directory.
+	elif [[ $(readlink -f $G_FP_DIETPI_USERDATA) == $TARGET_DIRECTORY ]]; then
 
-		# - Check if symlink is already pointing to target directory.
-		elif [[ $(readlink -f $G_FP_DIETPI_USERDATA) == $TARGET_DIRECTORY ]]; then
+		LOGFILE_OUTPUT_TEXT="INFO: $G_FP_DIETPI_USERDATA is already symlinked to target directory."
 
-			LOGFILE_OUTPUT_TEXT="INFO: $G_FP_DIETPI_USERDATA is already symlinked to target directory."
-			EXIT_CODE=0 #return ok
-			break
+	# - Check if source directory exists
+	elif [[ ! -d $SOURCE_DIRECTORY ]]; then
 
-		# - Check if source directory exists
-		elif [[ ! -d $SOURCE_DIRECTORY ]]; then
+		LOGFILE_OUTPUT_TEXT="ERROR: source directory $SOURCE_DIRECTORY does not exist."
+		EXIT_CODE=1
 
-			LOGFILE_OUTPUT_TEXT="ERROR: source directory $SOURCE_DIRECTORY does not exist."
-			EXIT_CODE=1
-			break
+	# - Check for disallowed directory match
+	elif [[ $SOURCE_DIRECTORY =~ $TARGET_DIRECTORY || $TARGET_DIRECTORY =~ $SOURCE_DIRECTORY ]]; then
 
-		# - Check for disallowed directory match
-		elif [[ $SOURCE_DIRECTORY =~ $TARGET_DIRECTORY || $TARGET_DIRECTORY =~ $SOURCE_DIRECTORY ]]; then
+		LOGFILE_OUTPUT_TEXT="ERROR: $SOURCE_DIRECTORY and $TARGET_DIRECTORY cannot be within each other. Disallowed directory match."
+		EXIT_CODE=1
 
-			LOGFILE_OUTPUT_TEXT="ERROR: $SOURCE_DIRECTORY and $TARGET_DIRECTORY cannot be within each other. Disallowed directory match."
-			EXIT_CODE=1
-			break
+	# - Only allow full filepaths
+	elif [[ ${SOURCE_DIRECTORY:0:1} != '/' || ${TARGET_DIRECTORY:0:1} != '/' ]]; then
 
-		# - Only allow full filepaths
-		elif [[ ${SOURCE_DIRECTORY:0:1} != '/' || ${TARGET_DIRECTORY:0:1} != '/' ]]; then
+		LOGFILE_OUTPUT_TEXT="ERROR: Both source ($SOURCE_DIRECTORY) and target directories ($TARGET_DIRECTORY) must contain the full filepath (eg: /mnt/drive1)"
+		EXIT_CODE=1
 
-			LOGFILE_OUTPUT_TEXT="ERROR: Both source ($SOURCE_DIRECTORY) and target directories ($TARGET_DIRECTORY) must contain the full filepath (eg: /mnt/drive1)"
-			EXIT_CODE=1
-			break
-
-		# - Ensure we can create and write to target directory
-		# - Disallow FS with no permissions support.
-		elif ! G_CHECK_FS_PERMISSION_SUPPORT $TARGET_DIRECTORY; then
-
-			LOGFILE_OUTPUT_TEXT="ERROR: $TARGET_DIRECTORY does not support filesystem permissions. Transfer aborted."
-			EXIT_CODE=1
-			break
-
-		fi
+	else
 
 		# - Remove $G_FP_DIETPI_USERDATA symlink, if chosen as target
 		[[ $TARGET_DIRECTORY == $G_FP_DIETPI_USERDATA ]] && rm $G_FP_DIETPI_USERDATA &> /dev/null
 		mkdir -p "$TARGET_DIRECTORY" &> /dev/null
 
-		# - Ensure enough freespace in target
-		#	"-BM" => result in MiB actual disc usage, respecting disk block size, e.g. "144M"
-		# 	"-b"  => result in bytes apparent size, ignoring disk block size, e.g. "142662603"
-		#	Trailing slash required with "du" to correctly check symlink target in case
-		FREESPACE_REQUIRED_SOURCE=$(du -sBM "$SOURCE_DIRECTORY/" | awk '{print $1}')
-		if (( ! $(G_CHECK_FREESPACE "$TARGET_DIRECTORY" ${FREESPACE_REQUIRED_SOURCE/M/}) )); then
+		# - Ensure we can create, write and set permissions to target directory
+		if ! G_CHECK_FS_PERMISSION_SUPPORT $TARGET_DIRECTORY; then
 
-			LOGFILE_OUTPUT_TEXT="ERROR: Not enough free space in target directory $TARGET_DIRECTORY.\n - Required $FREESPACE_REQUIRED_SOURCE"
+			LOGFILE_OUTPUT_TEXT="ERROR: $TARGET_DIRECTORY does not support filesystem permissions. Transfer aborted."
 			EXIT_CODE=1
-			break
+
+		else
+
+			# - Ensure enough freespace in target
+			#	"-BM" => result in MiB actual disc usage, respecting disk block size, e.g. "144M"
+			# 	"-b"  => result in bytes apparent size, ignoring disk block size, e.g. "142662603"
+			#	Trailing slash required with "du" to correctly check symlink target in case
+			FREESPACE_REQUIRED_SOURCE=$(du -sBM "$SOURCE_DIRECTORY/" | awk '{print $1}')
+			if (( ! $(G_CHECK_FREESPACE "$TARGET_DIRECTORY" ${FREESPACE_REQUIRED_SOURCE/M/}) )); then
+
+				LOGFILE_OUTPUT_TEXT="ERROR: Not enough free space in target directory $TARGET_DIRECTORY.\n - Required $FREESPACE_REQUIRED_SOURCE"
+				EXIT_CODE=1
+
+			else
+
+				#Run, attempt to move data.
+				Run_Move_Data
+
+			fi
 
 		fi
 
-		#Run, attempt to move data.
-		Run_Move_Data
-
-	done
+	fi
 
 	#-----------------------------------------------------------------------------------
 	#Print results and send to logfile
