v25

diff --git a/dietpi/dietpi-update b/dietpi/dietpi-update
--- a/dietpi/dietpi-update
+++ b/dietpi/dietpi-update
@@ -12,9 +12,16 @@
 #////////////////////////////////////
 
 #/////////////////////////////////////////////////////////////////////////////////////
+#Obtain Hardware Details
+#/////////////////////////////////////////////////////////////////////////////////////
+HW_MODEL=$(sed -n 1p /boot/dietpi/.hw_model)
+HW_MODEL_DESCRIPTION=$(sed -n 2p /boot/dietpi/.hw_model)
+DISTRO=$(sed -n 3p /boot/dietpi/.hw_model)
+
+#/////////////////////////////////////////////////////////////////////////////////////
 #VERSION CODES
 #/////////////////////////////////////////////////////////////////////////////////////
-DIETPIUPDATE_VERSION_CURRENT=1 # Version of dietpi-update / set server_version line two to value++ and obsolete previous dietpi-update scripts
+DIETPIUPDATE_VERSION_CURRENT=2 # Version of dietpi-update / set server_version line two to value++ and obsolete previous dietpi-update scripts
 DIETPIUPDATE_VERSION_REQUIRED=0
 
 VERSION_CURRENT=0
@@ -32,6 +39,12 @@ RUN_UPDATE=false
 #/////////////////////////////////////////////////////////////////////////////////////
 # see /boot/dietpi/boot for info
 DIETPI_INSTALL_STAGE=$(cat /boot/dietpi/.install_stage)
+
+#/////////////////////////////////////////////////////////////////////////////////////
+#Git Status
+#/////////////////////////////////////////////////////////////////////////////////////
+#Was git installed prior to running dietpi-update (eg: remove it afterwards)
+GIT_INSTALLED=true
 
 #/////////////////////////////////////////////////////////////////////////////////////
 # MENUS
@@ -55,84 +68,108 @@ Menu_Update(){
 	fi
 }
 
-Start_Update(){
+Run_DietPi_Update(){
 
 	#Remove Files from git that are not to be updated
 	rm ~/Dietpi/dietpi/.* &> /dev/null
 	rm ~/Dietpi/dietpi/dietpi-update &> /dev/null	
-	
-	cp -Rfu ~/Dietpi/dietpi /boot
 
-	#Update Local Version
-	VERSION_CURRENT=$VERSION_SERVER
-	echo -e "$VERSION_CURRENT" > /boot/dietpi/.version
+	#Copy to Fat16/32 partition
+	cp -Rfu ~/Dietpi/dietpi /boot
+	
+	#Run Patch file
+	local bRunPatch=true
+	while "$bRunPatch"; do	
+		bRunPatch=false;
+		Get_Current_Version
+		
+		clear
+		/boot/dietpi/dietpi-banner 0
+		echo -e "DietPi-Update is running the update process, please wait.... \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+				
+		if [[ $VERSION_CURRENT < $VERSION_SERVER ]]; then
+			/boot/dietpi/patch_file "$VERSION_CURRENT" "$VERSION_SERVER"
+			((VERSION_CURRENT++))
+			
+			#Update Local Version ID
+			echo -e "$VERSION_CURRENT" > /boot/dietpi/.version
+			
+			bRunPatch=true
+		fi
+	done
+	
+	#Remove Patch file
+	rm /boot/dietpi/patch_file
 
 	RUN_UPDATE=false
+	
 }
 
 #/////////////////////////////////////////////////////////////////////////////////////
 # Main Loop
 #/////////////////////////////////////////////////////////////////////////////////////
-if [ "$DIETPI_INSTALL_STAGE" > -1 ]; then
+/boot/dietpi/dietpi-banner 0
+echo -e " DietPi-Update: \n Please wait.................."
 
-	/boot/dietpi/dietpi-banner 0
-	echo -e " DietPi-Update: \n Please wait.................."
+#Get Local Version
+Get_Current_Version
 
-	#Get Local Version
-	Get_Current_Version
-
-	#Check Server is online
-	wget -q --spider https://github.com
-	if [ $? -eq 0 ]; then
-		SERVER_ONLINE=true
-		
-		#Check git is installed
-		if [ ! -f /usr/bin/git ]; then
-			clear
-			echo -e "Installing Git"
-			apt-get update -y
-			apt-get upgrade -y
-			apt-get install git -y --no-install-recommends	
-		fi
-
-		rm ~/Dietpi/dietpi/server_version &> /dev/null
-
-		#Get update
-		cd ~/
-		git clone https://github.com/Fourdee/Dietpi
-
-		#Get server Version
-		VERSION_SERVER=$(sed -n 1p ~/Dietpi/dietpi/server_version)
-		DIETPIUPDATE_VERSION_REQUIRED=$(sed -n 2p ~/Dietpi/dietpi/server_version)
-	fi
-
-	if [ "$SERVER_ONLINE" = false ]; then
-		whiptail --title "Error - Server Offline" --msgbox "http://github.com is either offline, or, unable to connect \n \n No updates applied." 12 60
-	elif [[ $DIETPIUPDATE_VERSION_CURRENT < $DIETPIUPDATE_VERSION_REQUIRED ]]; then 
-		#Cannot update, Image required
-		/boot/dietpi/dietpi-banner 0
-		echo -e " Your version of DietPi is now obsolete and cannot be updated. \n Please download the latest DietPi image:\n http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=6 \n\n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
-	elif [[ $VERSION_CURRENT < $VERSION_SERVER ]]; then 
-		#Ask for update
-		Menu_Update
-	else
-		#No Updates
-		/boot/dietpi/dietpi-banner 0
-		echo -e " DietPi Update - No updates required \n Your DietPi installation is upto date \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
-	fi
+#Check Server is online
+wget -q --spider https://github.com
+if [ $? -eq 0 ]; then
+	SERVER_ONLINE=true
 	
-	#Run Update
-	if [ "$RUN_UPDATE" = true ]; then
+	#Check git is installed
+	if [ ! -f /usr/bin/git ]; then
+		GIT_INSTALLED=false
 		clear
-		Start_Update
-		/boot/dietpi/dietpi-banner 0
-		echo -e "DietPi Update Completed. \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+		echo -e "Installing Git"
+		apt-get update -y
+		apt-get upgrade -y
+		apt-get install git -y --no-install-recommends	
 	fi
-	
-	#Clear files
-	rm ~/-1 &> /dev/null
-	rm -R ~/Dietpi &> /dev/null
-else
-	/boot/dietpi/dietpi-banner 0
-    echo -e " >> Filesystem prep has not yet completed: \n Please wait for the system to reboot "
+
+	rm ~/Dietpi/dietpi/server_version &> /dev/null
+
+	#Get update
+	cd ~/
+	git clone https://github.com/Fourdee/Dietpi
+
+	#Get server Version
+	VERSION_SERVER=$(sed -n 1p ~/Dietpi/dietpi/server_version)
+	DIETPIUPDATE_VERSION_REQUIRED=$(sed -n 2p ~/Dietpi/dietpi/server_version)
 fi
+
+if [ "$SERVER_ONLINE" = false ]; then
+	whiptail --title "Error - Server Offline" --msgbox "http://github.com is either offline, or, unable to connect \n \n No updates applied." 12 60
+elif [[ $DIETPIUPDATE_VERSION_CURRENT < $DIETPIUPDATE_VERSION_REQUIRED ]]; then 
+	#Cannot update, Image required
+	/boot/dietpi/dietpi-banner 0
+	echo -e " Your version of DietPi is now obsolete and cannot be updated. \n Please download the latest DietPi image:\n http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=6 \n\n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+elif [[ $VERSION_CURRENT < $VERSION_SERVER ]]; then 
+	#Ask for update
+	Menu_Update
+else
+	#No Updates
+	/boot/dietpi/dietpi-banner 0
+	echo -e " DietPi Update - No updates required \n Your DietPi installation is upto date \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+fi
+
+#Run Update
+if [ "$RUN_UPDATE" = true ]; then
+	clear
+	Run_DietPi_Update
+	clear
+	/boot/dietpi/dietpi-banner 0
+	echo -e "DietPi Update Completed. \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+fi
+
+#Clear files
+rm ~/-1 &> /dev/null
+rm -R ~/Dietpi &> /dev/null
+
+#Remove Git if we installed it?
+#if [ ! "$GIT_INSTALLED" ]; then
+#	apt-get purge git -y
+#	apt-get autoremove --purge -y
+#fi
