v6.26
+ DietPi-LetsEncrypt | Use any "certbot" binary found on the system $PATH. If not found, in menu mode offer to have it installed now.

diff --git a/dietpi/dietpi-letsencrypt b/dietpi/dietpi-letsencrypt
--- a/dietpi/dietpi-letsencrypt
+++ b/dietpi/dietpi-letsencrypt
@@ -32,9 +32,6 @@
 	# Globals
 	#/////////////////////////////////////////////////////////////////////////////////////
 	FP_LOGFILE='/var/log/dietpi-letsencrypt.log'
-	FP_BINARY='/usr/bin/certbot'
-	[[ -f $FP_BINARY ]] && LETSENCRYPT_INSTALLED=1 || LETSENCRYPT_INSTALLED=0
-
 	# Add post-renewal tasks via systemd unit drop-in
 	FP_RENEWAL='/etc/systemd/system/certbot.service.d'
 
@@ -71,12 +68,12 @@
 			#	If cert exists already, attempt renewal. This allows easy configuration update via "dietpi-letsencrypt 1" without using up limited certs per week.
 			if [[ -f $fp_cert_dir'/cert.pem' ]]; then
 
-				$FP_BINARY renew
+				certbot renew
 				local exit_code=$?
 
 			else
 
-				$FP_BINARY $options --agree-tos --no-eff-email --rsa-key-size "$LETSENCRYPT_KEYSIZE" -m "$LETSENCRYPT_EMAIL" -d "$LETSENCRYPT_DOMAIN"
+				certbot $options --agree-tos --no-eff-email --rsa-key-size "$LETSENCRYPT_KEYSIZE" -m "$LETSENCRYPT_EMAIL" -d "$LETSENCRYPT_DOMAIN"
 				local exit_code=$?
 
 			fi
@@ -97,12 +94,12 @@
 			# - Cert me up
 			if [[ -f $fp_cert_dir'/cert.pem' ]]; then
 
-				$FP_BINARY renew
+				certbot renew
 				local exit_code=$?
 
 			else
 
-				$FP_BINARY certonly --webroot -w /var/www --agree-tos --no-eff-email --rsa-key-size "$LETSENCRYPT_KEYSIZE" -m "$LETSENCRYPT_EMAIL" -d "$LETSENCRYPT_DOMAIN"
+				certbot certonly --webroot -w /var/www --agree-tos --no-eff-email --rsa-key-size "$LETSENCRYPT_KEYSIZE" -m "$LETSENCRYPT_EMAIL" -d "$LETSENCRYPT_DOMAIN"
 				local exit_code=$?
 
 			fi
@@ -219,12 +216,12 @@ _EOF_
 			# - Cert me up Nginx
 			if [[ -f $fp_cert_dir'/cert.pem' ]]; then
 
-				$FP_BINARY renew
+				certbot renew
 				local exit_code=$?
 
 			else
 
-				$FP_BINARY $options --agree-tos --no-eff-email --rsa-key-size "$LETSENCRYPT_KEYSIZE" -m "$LETSENCRYPT_EMAIL" -d "$LETSENCRYPT_DOMAIN"
+				certbot $options --agree-tos --no-eff-email --rsa-key-size "$LETSENCRYPT_KEYSIZE" -m "$LETSENCRYPT_EMAIL" -d "$LETSENCRYPT_DOMAIN"
 				local exit_code=$?
 
 			fi
@@ -254,12 +251,12 @@ _EOF_
 			/DietPi/dietpi/dietpi-services stop
 			if [[ -f $fp_cert_dir'/cert.pem' ]]; then
 
-				$FP_BINARY renew
+				certbot renew
 				local exit_code=$?
 
 			else
 
-				$FP_BINARY certonly --standalone --staple-ocsp --agree-tos --no-eff-email --rsa-key-size "$LETSENCRYPT_KEYSIZE" -m "$LETSENCRYPT_EMAIL" -d "$LETSENCRYPT_DOMAIN"
+				certbot certonly --standalone --staple-ocsp --agree-tos --no-eff-email --rsa-key-size "$LETSENCRYPT_KEYSIZE" -m "$LETSENCRYPT_EMAIL" -d "$LETSENCRYPT_DOMAIN"
 				local exit_code=$?
 
 			fi
@@ -545,24 +542,26 @@ Enabling HSTS will prevent access to applications which use a standalone webserv
 
 	#-----------------------------------------------------------------------------------
 	# Check installed
-	if (( ! $LETSENCRYPT_INSTALLED )); then
+	until command -v certbot &> /dev/null; then
 
 		# Menu
-		if (( ! $INPUT )); then
+		if (( ! $INPUT )) && G_WHIP_YESNO '[WARNING] No CertBot binary found\n
+Would you like to install CertBot now via "dietpi-software"?'; then
 
-			G_DIETPI-NOTIFY 1 "CertBot binary not found ( $FP_BINARY )"
-			G_DIETPI-NOTIFY 2 'Please install CertBot with DietPi-Software before running this program.'
-			read -p 'Press any key to continue...'
+			/DietPi/dietpi/dietpi-software install 92
 
 		else
 
-			echo "[FAILURE] CertBot binary not found ( $FP_BINARY ), please install it with DietPi-Software. Aborting..." | tee $FP_LOGFILE
+			echo '[FAILURE] No CertBot binary found, please install it with "dietpi-software". Aborting...' | tee $FP_LOGFILE
+			exit 1
 
 		fi
 
+	fi
+
 	#-----------------------------------------------------------------------------------
 	# Menu
-	elif (( ! $INPUT )); then
+	if (( ! $INPUT )); then
 
 		while (( $TARGETMENUID > -1 )); do
 
