v131
+ DietPi-Drive Manager: https://github.com/Fourdee/DietPi/issues/271

diff --git a/dietpi/dietpi-drive_manager b/dietpi/dietpi-drive_manager
--- a/dietpi/dietpi-drive_manager
+++ b/dietpi/dietpi-drive_manager
@@ -1,21 +1,21 @@
 #!/bin/bash
 {
 	# ////////////////////////////////////
-	# DietPi External drive mount
+	# DietPi Drive Manager
 	#
 	#////////////////////////////////////
 	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
 	#
 	#////////////////////////////////////
 	#
-	# Info: - Formats and Mounts /dev/sda1 /mnt/usb_1
+	# Info: - Formats and Mounts /dev/sdX1 /mnt/usb_1
 	#
 	# Notes: Script does not support VM image.
-	# This script needs a complete rewrite, messy. Support multiple drives etc.
 	#
 	# Usage:
-	# 	  = Menu
+	# 	  = Drive Manager
 	#	1 = Automated format and mounting of /dev/sda
+	#	2 = Old system to allow for user to setup 1 dedicated USB drive (/dev/sda)
 	#////////////////////////////////////
 
 	#Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
@@ -34,6 +34,8 @@
 	if [[ $1 =~ ^-?[0-9]+$ ]]; then
 		INPUT=$1
 	fi
+
+	PROGRAM_NAME='DietPi-Drive Manager'
 
 	MAXDRIVES=5
 	FORMAT_GPT=0
@@ -140,6 +142,43 @@
 			fi
 
 		done
+
+	}
+
+	Run_Format(){
+
+		local drivepath_no_partitions=$(echo -e "${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}" | sed 's/[0-9]*//g')
+
+		# - Unmount drive
+		umount "$drivepath_no_partitions"[0-9]
+
+		# - Clear MBR and partition table from device
+		dd if=/dev/zero of=$drivepath_no_partitions bs=512 count=1
+
+		# - Create partition table type
+		local parition_table_type='msdos'
+		if (( $FORMAT_GPT )); then
+
+			parition_table_type='gpt'
+
+		fi
+		parted -s "$drivepath_no_partitions" mklabel "$parition_table_type"
+		parted -a optimal "$drivepath_no_partitions" mkpart primary 0% 100%
+		partprobe
+
+		# - Format ext4
+		sleep 1 # due to systemD automount, wait for it.
+		umount ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}
+		mkfs.ext4 -F ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}
+		resize2fs ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}
+
+		# - Reset FStab UUID. It changes after a format.
+		local current_fstab_source=$(cat /etc/fstab | grep -m1 "${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]}" | awk '{print $1}')
+		sed -i "s@^$current_fstab_source@${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}@g" /etc/fstab
+		systemctl daemon-reload
+
+		mount -a
+		chown -R root:root ${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]}
 
 	}
 
@@ -256,7 +295,7 @@
 
 			if (( $INPUT == 0 )); then
 
-				whiptail --title "Dedicated Drive Completed" --msgbox "Dedicated USB harddrive setup completed successfully:\n\nFilesystem      Size  Used Avail Use% Mounted on\n$(df -Ph | grep '/mnt/usb_1')" --backtitle "DietPi-External Drive Setup" 12 70
+				whiptail --title "Dedicated Drive Completed" --msgbox "Dedicated USB harddrive setup completed successfully:\n\nFilesystem      Size  Used Avail Use% Mounted on\n$(df -Ph | grep '/mnt/usb_1')" --backtitle "$PROGRAM_NAME" 12 70
 
 			fi
 
@@ -267,7 +306,7 @@
 
 			if (( $INPUT == 0 )); then
 
-				whiptail --title "Error - Not Mounted" --yesno "DietPi was unable to complete the external USB harddrive setup. The drive may have incompatible partitions and/or filesystem. Formatting the drive may resolve the issue.\n\nWould you like to try again?" --defaultno --backtitle "DietPi-External Drive Setup" 11 70
+				whiptail --title "Error - Not Mounted" --yesno "DietPi was unable to complete the external USB harddrive setup. The drive may have incompatible partitions and/or filesystem. Formatting the drive may resolve the issue.\n\nWould you like to try again?" --defaultno --backtitle "$PROGRAM_NAME" 11 70
 				CHOICE=$?
 				if (( $CHOICE == 0 )); then
 
@@ -307,43 +346,6 @@
 	}
 
 	#---OLD SYSTEM END --------------------------------------------------------------------------------
-
-	Run_Format(){
-
-		local drivepath_no_partitions=$(echo -e "${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}" | sed 's/[0-9]*//g')
-
-		# - Unmount drive
-		umount "$drivepath_no_partitions"[0-9]
-
-		# - Clear MBR and partition table from device
-		dd if=/dev/zero of=$drivepath_no_partitions bs=512 count=1
-
-		# - Create partition table type
-		local parition_table_type='msdos'
-		if (( $FORMAT_GPT )); then
-
-			parition_table_type='gpt'
-
-		fi
-		parted -s "$drivepath_no_partitions" mklabel "$parition_table_type"
-		parted -a optimal "$drivepath_no_partitions" mkpart primary 0% 100%
-		partprobe
-
-		# - Format ext4
-		sleep 1 # due to systemD automount, wait for it.
-		umount ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}
-		mkfs.ext4 -F ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}
-		resize2fs ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}
-
-		# - Reset FStab UUID. It changes after a format.
-		local current_fstab_source=$(cat /etc/fstab | grep -m1 "${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]}" | awk '{print $1}')
-		sed -i "s@^$current_fstab_source@${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}@g" /etc/fstab
-		systemctl daemon-reload
-
-		mount -a
-		chown -R root:root ${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]}
-
-	}
 
 	TARGETMENUID=0
 	MENU_LASTITEM=''
@@ -399,8 +401,8 @@
 
 		fi
 
-		WHIP_TITLE='DietPi - External Drive Manager'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Please select a drive to see available options:" --default-item "$MENU_LASTITEM" --cancel-button "Exit" 16 80 5 "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
+		WHIP_TITLE="$PROGRAM_NAME"
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Please select a drive to see available options:" --default-item "$MENU_LASTITEM" --cancel-button "Exit" --backtitle "$PROGRAM_NAME" 16 80 5 "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
 
 		CHOICE=$?
 
@@ -449,7 +451,7 @@
 		#Exit
 		else
 
-			TARGETMENUID=-1
+			Menu_Exit
 
 		fi
 
@@ -494,6 +496,7 @@
 
 				whiptail_desc+="Capacity:     ${aDRIVE_SIZE_TOTAL[$INDEX_DRIVE_BEING_EDITED]}b\n"
 				whiptail_desc+="Used:         ${aDRIVE_SIZE_USED[$INDEX_DRIVE_BEING_EDITED]}b (${aDRIVE_SIZE_PERCENTUSED[$INDEX_DRIVE_BEING_EDITED]})\n"
+				whiptail_desc+="Status:       Drive is online and ready for use (${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]})"
 
 				whiptail_menu_array+=("Unmount" ": Allows you to psyhically remove the drive")
 
@@ -529,8 +532,8 @@
 
 		whiptail_menu_array+=("Format" ": Wipe all data and format drive with ext4")
 
-		WHIP_TITLE='DietPi - External Drive Manager'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "$whiptail_desc" --default-item "$MENU_LASTITEM" --cancel-button "Back" 18 80 4 "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
+		WHIP_TITLE="$PROGRAM_NAME"
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "$whiptail_desc" --default-item "$MENU_LASTITEM" --cancel-button "Back" --backtitle "$PROGRAM_NAME" 19 80 4 "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
 
 		CHOICE=$?
 
@@ -563,7 +566,7 @@
 
 			elif [ "$OPTION" = "Move userdata" ]; then
 
-				whiptail --title "Move user data" --yesno "Your user data will be moved:\n - From: $current_userdata_dir/dietpi_userdata\n - To: ${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]}/dietpi_userdata\n\nDo you wish to continue?" --backtitle "DietPi" --defaultno 12 70
+				whiptail --title "Move user data" --yesno "Your user data will be moved:\n - From: $current_userdata_dir/dietpi_userdata\n - To: ${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]}/dietpi_userdata\n\nDo you wish to continue?" --backtitle "$PROGRAM_NAME" --defaultno 12 70
 				if (( $CHOICE == 0 )); then
 
 					/DietPi/dietpi/func/dietpi-set_userdata "$current_userdata_dir" "${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]}"
@@ -573,23 +576,18 @@
 
 			elif [ "$OPTION" = "Format" ]; then
 
-				whiptail --title "Partition table?" --yesno "Would you like to use GPT or MBR parition table?\n - GPT is required for 2TB+ drives\n - MBR does NOT support 2TB+ drives\n\nIf unsure, select MBR (default)" --yes-button "GPT" --no-button "MBR" --backtitle "DietPi" --defaultno 12 70
+				whiptail --title "Partition table?" --yesno "Would you like to use GPT or MBR parition table?\n - GPT is required for 2TB+ drives\n - MBR does NOT support 2TB+ drives\n\nIf unsure, select MBR (default)" --yes-button "GPT" --no-button "MBR" --backtitle "$PROGRAM_NAME" --defaultno 12 70
 				CHOICE=$?
 				FORMAT_GPT=0
+				local partition_table_text='MBR'
 				if (( $CHOICE == 0 )); then
 
 					FORMAT_GPT=1
-
-				fi
-
-				local partition_table_text='MBR'
-				if (( $FORMAT_GPT )); then
-
 					partition_table_text='GPT'
 
 				fi
 
-				whiptail --title "Format" --yesno "Format Drive:\n - ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}\n - UUID=${aDRIVE_UUID[$INDEX_DRIVE_BEING_EDITED]}\n - Partition table: $partition_table_text\n\nDo you wish to continue and DELETE ALL DATA ON THIS DRIVE?" --backtitle "DietPi" --defaultno 13 70
+				whiptail --title "Format" --yesno "Format Drive:\n - ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}\n - UUID=${aDRIVE_UUID[$INDEX_DRIVE_BEING_EDITED]}\n - Partition table: $partition_table_text\n\nDo you wish to continue and DELETE ALL DATA ON THIS DRIVE?" --backtitle "$PROGRAM_NAME" --defaultno 13 70
 				CHOICE=$?
 				if (( $CHOICE == 0 )); then
 
@@ -608,6 +606,26 @@
 
 	}
 
+	Menu_Exit(){
+
+		WHIP_TITLE="Exit $PROGRAM_NAME?"
+		WHIP_QUESTION="Exit $PROGRAM_NAME?"
+		whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --backtitle "$PROGRAM_NAME" --yes-button "Ok" --no-button "Back" --defaultno 9 55
+		CHOICE=$?
+		if (( $CHOICE == 0 )); then
+
+			#exit
+			TARGETMENUID=-1
+
+		else
+
+			#Return to Main Menu
+			TARGETMENUID=0
+
+		fi
+
+	}
+
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Main Loop
 	#/////////////////////////////////////////////////////////////////////////////////////
@@ -616,7 +634,7 @@
 
 	#-----------------------------------------------------------------------------------
 	#Old system - setup 1 drive
-	if (( $INPUT == 0 )); then
+	if (( $INPUT == 2 )); then
 
 		while (( $RUNNING_SETUP == 1 )); do
 
@@ -632,8 +650,9 @@
 		Finish_Setup
 
 
+	#-----------------------------------------------------------------------------------
 	#Drive Manager
-	elif (( $INPUT == 2 )); then
+	else
 
 		while (( $TARGETMENUID > -1 )); do
 
