v148
+ CloudPrint, use Dave Steele's repo for Jessie. Stretch will use Debian
repos for install and support ARM64:
https://github.com/Fourdee/DietPi/issues/855

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -975,6 +975,12 @@ _EOF_
 			 aSOFTWARE_ONLINEDOC_URL[$index_current]='f=8&t=5&p=6630#p6630'
  		  aSOFTWARE_REQUIRES_RSYSLOG[$index_current]=1 #Not required, but comes in as package dep
 
+		#Disabled for ARM64 on Jessie only: https://github.com/Fourdee/DietPi/issues/855#issuecomment-292712002
+		if (( $DISTRO == 3 )); then
+
+			aSOFTWARE_AVAIL_HW_ARCH[$index_current,10]=0
+
+		fi
 		#------------------
 
 		#Emulation / Gaming
@@ -2012,7 +2018,7 @@ _EOF_
 				 aSOFTWARE_WHIP_DESC[$index_current]='ssh server'
 			aSOFTWARE_CATEGORY_INDEX[$index_current]=0
 					  aSOFTWARE_TYPE[$index_current]=-1
-			 aSOFTWARE_ONLINEDOC_URL[$index_current]='f=8&t=5&start=20#p68'
+			 aSOFTWARE_ONLINEDOC_URL[$index_current]='f=8&t=5&start=10#p62'
 		#------------------
 		index_current=105
 
@@ -5950,7 +5956,33 @@ _EOF_
 
 			Banner_Installing
 
-			AGI cloudprint-service
+			if (( $DISTRO == 3 )); then #https://github.com/Fourdee/DietPi/issues/855#issuecomment-292712002
+
+				INSTALL_URL_ADDRESS='http://davesteele.github.io/cloudprint-service'
+
+				#url/redirect fails wget spider test...
+				/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+				if (( $? == 0 )); then
+
+					INSTALL_URL_ADDRESS+='/repo'
+
+					echo -e "deb $INSTALL_URL_ADDRESS cloudprint-jessie main" > /etc/apt/sources.list.d/cloudprint.list
+					wget -q -O - https://davesteele.github.io/key-366150CE.pub.txt | apt-key add -
+					apt-get update
+
+					AGI cloudprint-service
+
+				else
+
+					Error_NoConnection_NoInstall
+
+				fi
+
+			else
+
+				AGI cloudprint-service
+
+			fi
 
 		fi
 
@@ -10267,6 +10299,12 @@ _EOF_
 		elif (( $1 == 137 )); then
 
 			AGP cloudprint-service
+			if (( $DISTRO == 3 )); then
+
+				rm /etc/apt/sources.list.d/cloudprint.list
+				apt-get update
+
+			fi
 
 		elif (( $1 == 119 )); then
 
