v105

diff --git a/dietpi/dietpi-config b/dietpi/dietpi-config
--- a/dietpi/dietpi-config
+++ b/dietpi/dietpi-config
@@ -1341,10 +1341,10 @@
 		esac
 	}
 
-	SHARED_IP_STATIC="0.0.0.0"
-	SHARED_GATEWAY_STATIC="0.0.0.0"
-	SHARED_MASK_STATIC="0.0.0.0"
-	SHARED_DNS_STATIC="0.0.0.0"
+	ETH_IP_STATIC="0.0.0.0"
+	ETH_GATEWAY_STATIC="0.0.0.0"
+	ETH_MASK_STATIC="0.0.0.0"
+	ETH_DNS_STATIC="0.0.0.0"
 
 	ETH_INDEX=0
 	ETH_DISABLED=0
@@ -1357,6 +1357,11 @@
 	ETH_MODE=0 #0=static 1=dhcp
 	ETH_MODE_TARGET=0
 
+	WIFI_IP_STATIC="0.0.0.0"
+	WIFI_GATEWAY_STATIC="0.0.0.0"
+	WIFI_MASK_STATIC="0.0.0.0"
+	WIFI_DNS_STATIC="0.0.0.0"
+
 	WIFI_INDEX=0
 	WIFI_DISABLED=0
 	WIFI_HARDWARE=false
@@ -1367,30 +1372,30 @@
 	WIFI_DNS="0.0.0.0"
 	WIFI_MODE=0 #0=static 1=dhcp
 	WIFI_MODE_TARGET=0
-	WIFI_SSID=""
-	WIFI_KEY=""
+	WIFI_SSID="WifiSSID"
+	WIFI_KEY="WifiKey"
 	WIFI_BITRATE=0
 	WIFI_SIGNALSTRENGTH=0
 
 	Network_ETH_CopyCurrentToStatic(){
 
-		#Apply, Only if we have a connection (prevent blank details which breaks networking)
+		#Apply, Only if we have a connection
 		if (( $ETH_CONNECTED == 1 )); then
-			sed -i "/address/c\address $ETH_IP" /etc/network/interfaces
-			sed -i "/gateway/c\gateway $ETH_GATEWAY" /etc/network/interfaces
-			sed -i "/netmask/c\netmask $ETH_MASK" /etc/network/interfaces
-			sed -i "/dns-nameservers/c\dns-nameservers $ETH_DNS" /etc/network/interfaces
+			ETH_IP_STATIC=$ETH_IP
+			ETH_GATEWAY_STATIC=$ETH_GATEWAY
+			ETH_MASK_STATIC=$ETH_MASK
+			ETH_DNS_STATIC=$ETH_DNS
 		fi
 	}
 
 	Network_WIFI_CopyCurrentToStatic(){
 
-		#Apply, Only if we have a connection (prevent blank details which breaks networking)
+		#Apply, Only if we have a connection
 		if (( $WIFI_CONNECTED == 1 )); then
-			sed -i "/address/c\address $WIFI_IP" /etc/network/interfaces
-			sed -i "/gateway/c\gateway $WIFI_GATEWAY" /etc/network/interfaces
-			sed -i "/netmask/c\netmask $WIFI_MASK" /etc/network/interfaces
-			sed -i "/dns-nameservers/c\dns-nameservers $WIFI_DNS" /etc/network/interfaces
+			WIFI_IP_STATIC=$WIFI_IP
+			WIFI_GATEWAY_STATIC=$WIFI_GATEWAY
+			WIFI_MASK_STATIC=$WIFI_MASK
+			WIFI_DNS_STATIC=$WIFI_DNS
 		fi
 	}
 
@@ -1408,6 +1413,7 @@
 
 		#Restart Networking
 		if (( $DISTRO == 3 )); then
+			systemctl daemon-reload
 			systemctl restart networking
 		else
 			/etc/init.d/networking reload
@@ -1421,11 +1427,24 @@
 			ifup eth$ETH_INDEX
 		fi
 
+		#Update network data
+		Network_GetData
+
 	}
 
 	Network_ApplyChanges(){
 
-		#Eth Mode change
+		#Enable/disable adapters
+		sed -i "/auto eth/c\#auto eth$ETH_INDEX" /etc/network/interfaces
+		sed -i "/auto wlan/c\#auto wlan$WIFI_INDEX" /etc/network/interfaces
+
+		if (( $ETH_DISABLED == 0 )); then
+			sed -i "/auto eth/c\auto eth$ETH_INDEX" /etc/network/interfaces
+		elif (( $WIFI_DISABLED == 0 )); then
+			sed -i "/auto wlan/c\auto wlan$WIFI_INDEX" /etc/network/interfaces
+		fi
+
+		#Eth - Save STATIC DHCP
 		if (( $ETH_MODE_TARGET == 0 )); then
 			#Change to STATIC
 			sed -i "/iface eth/c\iface eth$ETH_INDEX inet static" /etc/network/interfaces
@@ -1438,7 +1457,7 @@
 		#Update Current Mode for network restart
 		ETH_MODE=$ETH_MODE_TARGET
 
-		#Wifi Mode change
+		#Wifi - Save STATIC DHCP
 		if (( $WIFI_MODE_TARGET == 0 )); then
 			#Change to STATIC
 			sed -i "/iface wlan/c\iface wlan$WIFI_INDEX inet static" /etc/network/interfaces
@@ -1449,55 +1468,107 @@
 		#Update Current Mode for network restart
 		WIFI_MODE=$WIFI_MODE_TARGET
 
-
-		#Enable/Disable shared dns-nameservers (If static IP. dns-nameservers MUST be enabled)
-		local dnsnameservers_required=0
+		#Enable/Disable dns-nameservers (If static IP. dns-nameservers MUST be enabled)
+		sed -i 's/^dns-nameservers/#dns-nameservers/g' /etc/network/interfaces
+		if (( $ETH_DISABLED == 0 )) && (( $ETH_MODE == 0 )); then
+			sed -i "$(cat -n /etc/network/interfaces | grep 'dns-nameservers ' | sed -n 1p | awk '{print $1}')s/^#dns-nameservers/dns-nameservers/g" /etc/network/interfaces
+		fi
 		if (( $WIFI_DISABLED == 0 )) && (( $WIFI_MODE == 0 )); then
-				dnsnameservers_required=1
-		elif (( $ETH_DISABLED == 0 )) && (( $ETH_MODE == 0 )); then
-				dnsnameservers_required=1
+			sed -i "$(cat -n /etc/network/interfaces | grep 'dns-nameservers ' | sed -n 2p | awk '{print $1}')s/^#dns-nameservers/dns-nameservers/g" /etc/network/interfaces
 		fi
 
-		if (( $dnsnameservers_required == 1 )); then
-			sed -i 's/^#dns-nameservers/dns-nameservers/g' /etc/network/interfaces
-		else
-			sed -i 's/^dns-nameservers/#dns-nameservers/g' /etc/network/interfaces
-		fi
+		#Save Static IPs (not applied to # disabled lines)
+		# - eth
+		sed -i "$(cat -n /etc/network/interfaces | grep 'address ' | sed -n 1p | awk '{print $1}')s/^address.*/address $ETH_IP_STATIC/" /etc/network/interfaces
+		sed -i "$(cat -n /etc/network/interfaces | grep 'gateway ' | sed -n 1p | awk '{print $1}')s/^gateway.*/gateway $ETH_GATEWAY_STATIC/" /etc/network/interfaces
+		sed -i "$(cat -n /etc/network/interfaces | grep 'netmask ' | sed -n 1p | awk '{print $1}')s/^netmask.*/netmask $ETH_MASK_STATIC/" /etc/network/interfaces
+		sed -i "$(cat -n /etc/network/interfaces | grep 'dns-nameservers ' | sed -n 1p | awk '{print $1}')s/^dns-nameservers.*/dns-nameservers $ETH_DNS_STATIC/" /etc/network/interfaces
+		# - wifi
+		sed -i "$(cat -n /etc/network/interfaces | grep 'address ' | sed -n 2p | awk '{print $1}')s/^address.*/address $WIFI_IP_STATIC/" /etc/network/interfaces
+		sed -i "$(cat -n /etc/network/interfaces | grep 'gateway ' | sed -n 2p | awk '{print $1}')s/^gateway.*/gateway $WIFI_GATEWAY_STATIC/" /etc/network/interfaces
+		sed -i "$(cat -n /etc/network/interfaces | grep 'netmask ' | sed -n 2p | awk '{print $1}')s/^netmask.*/netmask $WIFI_MASK_STATIC/" /etc/network/interfaces
+		sed -i "$(cat -n /etc/network/interfaces | grep 'dns-nameservers ' | sed -n 2p | awk '{print $1}')s/^dns-nameservers.*/dns-nameservers $WIFI_DNS_STATIC/" /etc/network/interfaces
+
+		#Save WiFi creds (not applied to # disabled lines)
+		sed -i "/^wireless-essid/c\wireless-essid $WIFI_SSID" /etc/network/interfaces
+		sed -i "/^wpa-ssid/c\wpa-ssid $WIFI_SSID" /etc/network/interfaces
+		sed -i "/^wireless-key/c\wireless-key $WIFI_KEY" /etc/network/interfaces
+		sed -i "/^wpa-psk/c\wpa-psk $WIFI_KEY" /etc/network/interfaces
 
 		#restart net
 		Network_Restart
 	}
 
 	Change_StaticIp(){
+
 		#Ethernet
-		OPTION=$(whiptail --inputbox "Enter Your New Ip Address" 8 60 "$SHARED_IP_STATIC" --title "Set Static Ip Address" 3>&1 1>&2 2>&3)
-		CHOICE=$?
-		if (( $CHOICE == 0 )); then
-			sed -i "/address/c\address $OPTION" /etc/network/interfaces
+		if (( $1 == 0 )); then
+			OPTION=$(whiptail --inputbox "Enter Your New Ip Address" 8 60 "$ETH_IP_STATIC" --title "Set Static Ip Address" 3>&1 1>&2 2>&3)
+			CHOICE=$?
+			if (( $CHOICE == 0 )); then
+				ETH_IP_STATIC=$OPTION
+			fi
+		#wifi
+		elif (( $1 == 1 )); then
+			OPTION=$(whiptail --inputbox "Enter Your New Ip Address" 8 60 "$WIFI_IP_STATIC" --title "Set Static Ip Address" 3>&1 1>&2 2>&3)
+			CHOICE=$?
+			if (( $CHOICE == 0 )); then
+				WIFI_IP_STATIC=$OPTION
+			fi
 		fi
 	}
 
 	Change_StaticGateway(){
-		OPTION=$(whiptail --inputbox "Enter Your New Gateway Address" 8 60 "$SHARED_GATEWAY_STATIC" --title "Set Static Gateway Address" 3>&1 1>&2 2>&3)
-		CHOICE=$?
-		if (( $CHOICE == 0 )); then
-			sed -i "/gateway/c\gateway $OPTION" /etc/network/interfaces
+		#Ethernet
+		if (( $1 == 0 )); then
+			OPTION=$(whiptail --inputbox "Enter Your New Gateway Address" 8 60 "$ETH_GATEWAY_STATIC" --title "Set Static Gateway Address" 3>&1 1>&2 2>&3)
+			CHOICE=$?
+			if (( $CHOICE == 0 )); then
+				ETH_GATEWAY_STATIC=$OPTION
+			fi
+		#wifi
+		elif (( $1 == 1 )); then
+			OPTION=$(whiptail --inputbox "Enter Your New Gateway Address" 8 60 "$WIFI_GATEWAY_STATIC" --title "Set Static Gateway Address" 3>&1 1>&2 2>&3)
+			CHOICE=$?
+			if (( $CHOICE == 0 )); then
+				WIFI_GATEWAY_STATIC=$OPTION
+			fi
 		fi
 	}
 
 	Change_StaticMask(){
-		OPTION=$(whiptail --inputbox "Enter Your New Mask Address" 8 60 "$SHARED_MASK_STATIC" --title "Set Static Mask Address" 3>&1 1>&2 2>&3)
-		CHOICE=$?
-		if (( $CHOICE == 0 )); then
-			sed -i "/netmask/c\netmask $OPTION" /etc/network/interfaces
+		#Ethernet
+		if (( $1 == 0 )); then
+			OPTION=$(whiptail --inputbox "Enter Your New Mask Address" 8 60 "$ETH_MASK_STATIC" --title "Set Static Mask Address" 3>&1 1>&2 2>&3)
+			CHOICE=$?
+			if (( $CHOICE == 0 )); then
+				ETH_MASK_STATIC=$OPTION
+			fi
+		#wifi
+		elif (( $1 == 1 )); then
+			OPTION=$(whiptail --inputbox "Enter Your New Mask Address" 8 60 "$WIFI_MASK_STATIC" --title "Set Static Mask Address" 3>&1 1>&2 2>&3)
+			CHOICE=$?
+			if (( $CHOICE == 0 )); then
+				WIFI_MASK_STATIC=$OPTION
+			fi
 		fi
 	}
 
 	Change_StaticDns(){
-		OPTION=$(whiptail --inputbox "Enter Your DNS Server Address\n - 2 maximum, seperated by a space.\n - eg: 8.8.8.8 8.8.4.4" 10 60 "$SHARED_DNS_STATIC" --title "Set Static Mask Address" 3>&1 1>&2 2>&3)
-		CHOICE=$?
-		if (( $CHOICE == 0 )); then
-			sed -i "/dns-nameservers/c\dns-nameservers $OPTION" /etc/network/interfaces
+		#Ethernet
+		if (( $1 == 0 )); then
+			OPTION=$(whiptail --inputbox "Enter Your DNS Server Address\n - 2 maximum, seperated by a space.\n - eg: 8.8.8.8 8.8.4.4" 10 60 "$ETH_DNS_STATIC" --title "Set Static DNS Address" 3>&1 1>&2 2>&3)
+			CHOICE=$?
+			if (( $CHOICE == 0 )); then
+				ETH_DNS_STATIC=$OPTION
+			fi
+		#wifi
+		elif (( $1 == 1 )); then
+			OPTION=$(whiptail --inputbox "Enter Your DNS Server Address\n - 2 maximum, seperated by a space.\n - eg: 8.8.8.8 8.8.4.4" 10 60 "$WIFI_DNS_STATIC" --title "Set Static DNS Address" 3>&1 1>&2 2>&3)
+			CHOICE=$?
+			if (( $CHOICE == 0 )); then
+				WIFI_DNS_STATIC=$OPTION
+			fi
 		fi
 	}
 
@@ -1505,8 +1576,7 @@
 		OPTION=$(whiptail --inputbox "Enter the SSID name to connect to." 8 60 "$WIFI_SSID" --title "Set Your SSID" 3>&1 1>&2 2>&3)
 		CHOICE=$?
 		if (( $CHOICE == 0 )); then
-			sed -i "/wireless-essid/c\wireless-essid $OPTION" /etc/network/interfaces
-			sed -i "/wpa-ssid/c\wpa-ssid $OPTION" /etc/network/interfaces
+			WIFI_SSID=$OPTION
 		fi
 	}
 
@@ -1514,8 +1584,7 @@
 		OPTION=$(whiptail --inputbox "Enter the Access Key (WPA/WEP)." 8 60 "$WIFI_KEY" --title "Set Your Acccess Key" 3>&1 1>&2 2>&3)
 		CHOICE=$?
 		if (( $CHOICE == 0 )); then
-			sed -i "/wireless-key/c\wireless-key $OPTION" /etc/network/interfaces
-			sed -i "/wpa-psk/c\wpa-psk $OPTION" /etc/network/interfaces
+			WIFI_KEY=$OPTION
 		fi
 	}
 
@@ -1542,8 +1611,6 @@
 		CHOICE=$?
 		if (( $CHOICE == 0 )); then
 			WIFI_SSID=${wifi_ssid_array[$OPTION]}
-			sed -i "/wireless-essid/c\wireless-essid $WIFI_SSID" /etc/network/interfaces
-			sed -i "/wpa-ssid/c\wpa-ssid $WIFI_SSID" /etc/network/interfaces
 			Change_WifiKey
 		fi
 
@@ -1602,14 +1669,17 @@
 		#Obtain network details (network indexs)
 		/DietPi/dietpi/func/obtain_network_details
 
+		#Copy /etc/network/interfaces to /tmp (tmpfs) and pull data from it.
+		cp /etc/network/interfaces /tmp/net_interfaces
+
 		#Reset
-		SHARED_IP_STATIC="0.0.0.0"
-		SHARED_GATEWAY_STATIC="0.0.0.0"
-		SHARED_MASK_STATIC="0.0.0.0"
-		SHARED_DNS_STATIC="0.0.0.0"
+		ETH_IP_STATIC=$(cat -n /tmp/net_interfaces | grep 'address ' | sed -n 1p | awk '{print $3}')
+		ETH_GATEWAY_STATIC=$(cat -n /tmp/net_interfaces | grep 'gateway ' | sed -n 1p | awk '{print $3}')
+		ETH_MASK_STATIC=$(cat -n /tmp/net_interfaces | grep 'netmask ' | sed -n 1p | awk '{print $3}')
+		ETH_DNS_STATIC=$(cat -n /tmp/net_interfaces | grep 'dns-nameservers ' | sed -n 1p | awk '{print $3,$4}')
 
 		ETH_INDEX=$(sed -n 1p /DietPi/dietpi/.network)
-		ETH_DISABLED=$(cat /etc/network/interfaces | grep -ci -m1 "#auto eth$ETH_INDEX")
+		ETH_DISABLED=$(cat /tmp/net_interfaces | grep -ci -m1 "#auto eth$ETH_INDEX")
 		ETH_HARDWARE=false
 		ETH_CONNECTED=0
 		ETH_IP="0.0.0.0"
@@ -1618,8 +1688,13 @@
 		ETH_DNS="0.0.0.0"
 		ETH_MODE=0
 
+		WIFI_IP_STATIC=$(cat -n /tmp/net_interfaces | grep 'address ' | sed -n 2p | awk '{print $3}')
+		WIFI_GATEWAY_STATIC=$(cat -n /tmp/net_interfaces | grep 'gateway ' | sed -n 2p | awk '{print $3}')
+		WIFI_MASK_STATIC=$(cat -n /tmp/net_interfaces | grep 'netmask ' | sed -n 2p | awk '{print $3}')
+		WIFI_DNS_STATIC=$(cat -n /tmp/net_interfaces | grep 'dns-nameservers ' | sed -n 2p | awk '{print $3,$4}')
+
 		WIFI_INDEX=$(sed -n 2p /DietPi/dietpi/.network)
-		WIFI_DISABLED=$(cat /etc/network/interfaces | grep -ci -m1 "#auto wlan$WIFI_INDEX")
+		WIFI_DISABLED=$(cat /tmp/net_interfaces | grep -ci -m1 "#auto wlan$WIFI_INDEX")
 		WIFI_HARDWARE=false
 		WIFI_CONNECTED=0
 		WIFI_IP="0.0.0.0"
@@ -1633,19 +1708,13 @@
 		WIFI_BITRATE=0
 		WIFI_SIGNALSTRENGTH=0
 
-		#Grab static address from /etc/network/interfaces
-		SHARED_IP_STATIC=$(cat /etc/network/interfaces  | grep -m1 'address' | awk '{ print $2 }')
-		SHARED_GATEWAY_STATIC=$(cat /etc/network/interfaces  | grep -m1 'gateway' | awk '{ print $2 }')
-		SHARED_MASK_STATIC=$(cat /etc/network/interfaces  | grep -m1 'netmask' | awk '{ print $2 }')
-		SHARED_DNS_STATIC=$(cat /etc/network/interfaces | grep -m1 'dns-nameservers' | awk '{ print $2,$3 }')
-
 		#eth
 		if [ -d /sys/class/net/eth$ETH_INDEX ]; then
 			#Hardware
 			ETH_HARDWARE=true
 
 			#Static or Dhcp?
-			ETH_MODE=$(cat /etc/network/interfaces | grep -ci -m1 "iface eth$ETH_INDEX inet dhcp")
+			ETH_MODE=$(cat /tmp/net_interfaces | grep -ci -m1 "iface eth$ETH_INDEX inet dhcp")
 
 			#Connected and Valid IP?
 			ETH_CONNECTED=$(ip r | grep -ci -m1 "eth$ETH_INDEX")
@@ -1659,22 +1728,20 @@
 			fi
 		fi
 
-		# static ip is shared for both Wifi and Ethernet
-
 		#wlan
 		if [ -d /sys/class/net/wlan$WIFI_INDEX ]; then
 			#Hardware
 			WIFI_HARDWARE=true
 
 			#Static or Dhcp?
-			WIFI_MODE=$(cat /etc/network/interfaces | grep -ci -m1 "iface wlan$WIFI_INDEX inet dhcp")
+			WIFI_MODE=$(cat /tmp/net_interfaces | grep -ci -m1 "iface wlan$WIFI_INDEX inet dhcp")
 
 			#Connected and Valid IP?
 			WIFI_CONNECTED=$(ip r | grep -ci -m1 "wlan$WIFI_INDEX")
 
 			#Wifi Extras
-			WIFI_SSID=$(cat /etc/network/interfaces | grep -m1 'wireless-essid' | sed 's/^[^\ ]\+\ //')
-			WIFI_KEY=$(cat /etc/network/interfaces | grep -m1 'wireless-key' | sed 's/^[^\ ]\+\ //')
+			WIFI_SSID=$(cat /tmp/net_interfaces | grep -m1 'wireless-essid' | sed 's/^[^\ ]\+\ //')
+			WIFI_KEY=$(cat /tmp/net_interfaces | grep -m1 'wireless-key' | sed 's/^[^\ ]\+\ //')
 
 			#Enabled and Connected
 			if (( $WIFI_DISABLED == 0 )) && (( $WIFI_CONNECTED == 1 )); then
@@ -1687,6 +1754,10 @@
 				WIFI_SIGNALSTRENGTH=$(iwconfig wlan$WIFI_INDEX | grep -m1 'Signal level=' | awk '{ print $4 }' | sed 's/level=//g' | cut -f1 -d "/")
 			fi
 		fi
+
+		#cleanup tmp
+		rm /tmp/net_interfaces &> /dev/null
+
 	}
 
 	Menu_SambaClientSetup(){
@@ -1831,7 +1902,7 @@
 				#No hardware found
 				if [ "$ETH_HARDWARE" = false ]; then
 					WHIP_TITLE=' Error: No Ethernet Hardware was found.'
-					WHIP_QUESTION=' No Ethernet Hardware was found. Your most likely running a Pi Model A'
+					WHIP_QUESTION=' No Ethernet Hardware was found. You are most likely running a Pi Model A'
 					whiptail --title "$WHIP_TITLE" --msgbox "$WHIP_QUESTION" --backtitle "$WHIP_BACKTITLE" 12 60
 					#Return to this Menu
 					TARGETMENUID=8
@@ -1841,8 +1912,8 @@
 					CHOICE=$?
 					#Confirm action
 					if (( $CHOICE == 0 )); then
-						sed -i "/auto eth/c\auto eth$ETH_INDEX" /etc/network/interfaces
-						sed -i "/auto wlan/c\#auto wlan$WIFI_INDEX" /etc/network/interfaces
+						ETH_DISABLED=0
+						WIFI_DISABLED=1
 						Network_ApplyChanges
 						TARGETMENUID=9
 					else
@@ -1868,8 +1939,8 @@
 					CHOICE=$?
 					#Confirm action
 					if (( $CHOICE == 0 )); then
-						sed -i "/auto wlan/c\auto wlan$WIFI_INDEX" /etc/network/interfaces
-						sed -i "/auto eth/c\#auto eth$ETH_INDEX" /etc/network/interfaces
+						ETH_DISABLED=1
+						WIFI_DISABLED=0
 						Network_ApplyChanges
 						TARGETMENUID=10
 					else
@@ -2006,9 +2077,6 @@
 
 		TARGETMENUID=8
 
-		#Check Network
-		Network_GetData
-
 		#Get current Mode details
 		local mode_current='DHCP'
 		if (( $ETH_MODE == 0 )); then
@@ -2027,10 +2095,10 @@
 		OPTION=$(whiptail --title "$WHIP_TITLE" --menu " Current Details: \n - Mode    = $mode_current \n - Ip      = $ETH_IP \n - Mask    = $ETH_MASK\n - Gateway = $ETH_GATEWAY\n - DNS     = $ETH_DNS" --cancel-button "$TEXT_MENU_BACK" --backtitle "$WHIP_BACKTITLE" 20 60 7 \
 		"Change Mode" "$mode_target" \
 		"Copy" "Copy Current address to Static" \
-		"Static Ip" "$SHARED_IP_STATIC"  \
-		"Static Mask" "$SHARED_MASK_STATIC"  \
-		"Static Gateway" "$SHARED_GATEWAY_STATIC"  \
-		"Static DNS" "$SHARED_DNS_STATIC" \
+		"Static Ip" "$ETH_IP_STATIC"  \
+		"Static Mask" "$ETH_MASK_STATIC"  \
+		"Static Gateway" "$ETH_GATEWAY_STATIC"  \
+		"Static DNS" "$ETH_DNS_STATIC" \
 		"Apply" "Save Changes (Restart Networking)" 3>&1 1>&2 2>&3)
 
 		CHOICE=$?
@@ -2046,6 +2114,7 @@
 				;;
 				Apply)
 					Ethernet_Reconnect
+
 					#Return to this menu
 					TARGETMENUID=9
 				;;
@@ -2055,30 +2124,26 @@
 					TARGETMENUID=9
 				;;
 				"Static Ip")
-					Change_StaticIp
+					Change_StaticIp 0
 					#Return to this menu
 					TARGETMENUID=9
 				;;
 				"Static Gateway")
-					Change_StaticGateway
+					Change_StaticGateway 0
 					#Return to this menu
 					TARGETMENUID=9
 				;;
 				"Static Mask")
-					Change_StaticMask
+					Change_StaticMask 0
 					#Return to this menu
 					TARGETMENUID=9
 				;;
 				"Static DNS")
-					Change_StaticDns
+					Change_StaticDns 0
 					#Return to this menu
 					TARGETMENUID=9
 				;;
 			esac
-		#Cancel
-		else
-			#Copy Current to Static (just incase user changed value, and didnt apply)
-			Network_ETH_CopyCurrentToStatic
 
 		fi
 
@@ -2088,9 +2153,6 @@
 	Menu_NetworkOptions_Wifi(){
 
 		TARGETMENUID=8
-
-		#Check Network
-		Network_GetData
 
 		#Get current Mode details
 		local mode_current='DHCP'
@@ -2112,10 +2174,10 @@
 		"Manual" "Manually Set Wireless Details" \
 		"Change Mode" "$mode_target" \
 		"Copy" "Copy Current address to Static" \
-		"Static Ip" "$SHARED_IP_STATIC"  \
-		"Static Mask" "$SHARED_MASK_STATIC"  \
-		"Static Gateway" "$SHARED_GATEWAY_STATIC"  \
-		"Static DNS" "$SHARED_DNS_STATIC" \
+		"Static Ip" "$WIFI_IP_STATIC"  \
+		"Static Mask" "$WIFI_MASK_STATIC"  \
+		"Static Gateway" "$WIFI_GATEWAY_STATIC"  \
+		"Static DNS" "$WIFI_DNS_STATIC" \
 		"Apply" "Save Changes (Restart Networking)" 3>&1 1>&2 2>&3)
 
 		CHOICE=$?
@@ -2153,30 +2215,26 @@
 					TARGETMENUID=10
 				;;
 				"Static Ip")
-					Change_StaticIp
+					Change_StaticIp 1
 					#Return to this menu
 					TARGETMENUID=10
 				;;
 				"Static Gateway")
-					Change_StaticGateway
+					Change_StaticGateway 1
 					#Return to this menu
 					TARGETMENUID=10
 				;;
 				"Static Mask")
-					Change_StaticMask
+					Change_StaticMask 1
 					#Return to this menu
 					TARGETMENUID=10
 				;;
 				"Static DNS")
-					Change_StaticDns
+					Change_StaticDns 1
 					#Return to this menu
 					TARGETMENUID=10
 				;;
 			esac
-		else
-			#Copy Current to Static (just incase user changed value, and didnt apply)
-			Network_WIFI_CopyCurrentToStatic
-
 		fi
 
 	}
