v159
+ Minor formatting fixes

diff --git a/dietpi/dietpi-services b/dietpi/dietpi-services
--- a/dietpi/dietpi-services
+++ b/dietpi/dietpi-services
@@ -133,6 +133,7 @@
 
 	fi
 
+	#init
 	aSERVICE_AVAILABLE=0
 	for ((i=0; i<${#aSERVICE_NAME[@]}; i++))
 	do
@@ -173,20 +174,21 @@
 	Print_Status()
 	{
 
-		#$1 = name
-		#$2 = exit code
+		#$1 = Method
+		#$2 = name
+		#$3 = exit code
 
 		#	NB: SystemD exit code 5 = not loaded/active, so dont trigger a failed result.
 
 		#ok
-		if (( $2 == 0 || $2 == 5 )); then
+		if (( $3 == 0 || $3 == 5 )); then
 
-			echo -e "\e[1A$(/DietPi/dietpi/func/dietpi-notify 0)\e[0m $1"
+			echo -e "\e[1A$(/DietPi/dietpi/func/dietpi-notify 0)\e[0m $1 : $2"
 
 		#failed
 		else
 
-			echo -e "\e[1A$(/DietPi/dietpi/func/dietpi-notify 1)\e[0m $1"
+			echo -e "\e[1A$(/DietPi/dietpi/func/dietpi-notify 1)\e[0m $1 : $2"
 
 		fi
 
@@ -213,7 +215,7 @@
 				echo -e "${aDIETPISERVICE_NAME[$i]}"
 
 				${aDIETPISERVICE_FP[$i]} $INPUT_MODE &> /dev/null
-				Print_Status ${aDIETPISERVICE_NAME[$i]} $?
+				Print_Status $INPUT_MODE ${aDIETPISERVICE_NAME[$i]} $?
 
 			fi
 
@@ -265,7 +267,7 @@
 
 				systemctl $INPUT_MODE ${aSERVICE_NAME[$i]} &> /dev/null
 
-				Print_Status ${aSERVICE_NAME[$i]} $?
+				Print_Status $INPUT_MODE ${aSERVICE_NAME[$i]} $?
 
 			fi
 
@@ -292,7 +294,7 @@
 				echo -e "${aDIETPISERVICE_NAME[$i]}"
 
 				${aDIETPISERVICE_FP[$i]} $INPUT_MODE &> /dev/null
-				Print_Status ${aDIETPISERVICE_NAME[$i]} $?
+				Print_Status $INPUT_MODE ${aDIETPISERVICE_NAME[$i]} $?
 
 			fi
 
@@ -348,7 +350,7 @@
 
 				systemctl $SYSTEMD_CMD ${aSERVICE_NAME[$i]} &> /dev/null
 
-				Print_Status ${aSERVICE_NAME[$i]} $?
+				Print_Status $INPUT_MODE ${aSERVICE_NAME[$i]} $?
 
 			fi
 
@@ -366,6 +368,7 @@
 		systemctl stop $INPUT_S2
 
 		systemctl $INPUT_MODE $INPUT_S2
+		#Print_Status $INPUT_MODE $INPUT_S2 $?
 		if (( $? == 0 )); then
 
 			/DietPi/dietpi/func/dietpi-notify 0 "$INPUT_MODE $INPUT_S2"
@@ -381,6 +384,7 @@
 		if [ "$INPUT_MODE" = "unmask" ]; then
 
 			INPUT_MODE='start'
+			echo -e ""
 			Set_Running_State
 
 		fi
