v6.20
+ DietPi-Software | ownCloud/Nextcloud: fastcgi_param HTTPS is now sed automatically correctly based on Nginx $https variable

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -7718,13 +7718,11 @@ url.redirect = (
 				# Stretch: Set 'fastcgi_request_buffering off';
 				(( $G_DISTRO > 3 )) && sed -i 's/#fastcgi_request_buffering off;/fastcgi_request_buffering off;/g' $owncloud_conf
 
-				# Set HTTPS on, if SSL connection is available, even with self-signed/untrusted certificate.
-				# - Only apply, if related dietpi-letsencrypt settings were found
-				wget -q --spider --timeout=10 --tries=2 https://localhost &> /dev/null
-				if (( $? == 0 || $? == 5)) && [[ -f /DietPi/dietpi/.dietpi-letsencrypt ]]; then
+				# Uncomment HSTS header, if chosen via dietpi-letsencrypt and HTTPS connection test succeeds (incl. self-singed cert => exit code 5)
+				if [[ -f /DietPi/dietpi/.dietpi-letsencrypt && $(sed -n 4p /DietPi/dietpi/.dietpi-letsencrypt) == 1 ]]; then
 
-					[[ $(sed -n 3p /DietPi/dietpi/.dietpi-letsencrypt) == 1 ]] && sed -i 's/#fastcgi_param HTTPS on;/fastcgi_param HTTPS on;/g' $owncloud_conf
-					[[ $(sed -n 4p /DietPi/dietpi/.dietpi-letsencrypt) == 1 ]] && sed -i 's/#add_header Strict-Transport-Security/add_header Strict-Transport-Security/g' $owncloud_conf
+					wget -q --spider --timeout=10 --tries=2 https://localhost &> /dev/null
+					(( $? == 0 || $? == 5)) && sed -i 's/#add_header Strict-Transport-Security/add_header Strict-Transport-Security/g' $owncloud_conf
 
 				fi
 
@@ -7974,13 +7972,11 @@ url.redirect = (
 				# Stretch: Set 'fastcgi_request_buffering off';
 				(( $G_DISTRO > 3 )) && sed -i 's/#fastcgi_request_buffering off;/fastcgi_request_buffering off;/g' $nextcloud_conf
 
-				# Set HTTPS on, if SSL connection is available, even with self-signed/untrusted certificate.
-				# - Only apply, if related dietpi-letsencrypt settings were found
-				wget -q --spider --timeout=10 --tries=2 https://localhost &> /dev/null
-				if (( $? == 0 || $? == 5)) && [[ -f /DietPi/dietpi/.dietpi-letsencrypt ]]; then
+				# Uncomment HSTS header, if chosen via dietpi-letsencrypt and HTTPS connection test succeeds (incl. self-singed cert => exit code 5)
+				if [[ -f /DietPi/dietpi/.dietpi-letsencrypt && $(sed -n 4p /DietPi/dietpi/.dietpi-letsencrypt) == 1 ]]; then
 
-					[[ $(sed -n 3p /DietPi/dietpi/.dietpi-letsencrypt) == 1 ]] && sed -i 's/#fastcgi_param HTTPS on;/fastcgi_param HTTPS on;/g' $nextcloud_conf
-					[[ $(sed -n 4p /DietPi/dietpi/.dietpi-letsencrypt) == 1 ]] && sed -i 's/#add_header Strict-Transport-Security/add_header Strict-Transport-Security/g' $nextcloud_conf
+					wget -q --spider --timeout=10 --tries=2 https://localhost &> /dev/null
+					(( $? == 0 || $? == 5)) && sed -i 's/#add_header Strict-Transport-Security/add_header Strict-Transport-Security/g' $nextcloud_conf
 
 				fi
 
