v6.13
+ DietPi-Drive_Manager | Add NFSv3 handling: Catch error that indicates NFSv3, then allow required server-side path to share input.
+ DietPi-Drive_Manager | Minor coding

diff --git a/dietpi/dietpi-drive_manager b/dietpi/dietpi-drive_manager
--- a/dietpi/dietpi-drive_manager
+++ b/dietpi/dietpi-drive_manager
@@ -476,7 +476,7 @@ aDRIVE_ISPARTITIONTABLE ${aDRIVE_ISPARTITIONTABLE[$i]}
 				if [[ $DRIVE_TARGET_BEING_EDITED == ${aDRIVE_MOUNT_TARGET[$i]} ]]; then
 
 					INDEX_DRIVE_BEING_EDITED=$i
-					#echo -e "DEBUG EDIT | ${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]} | ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]} | ${aDRIVE_SOURCE_DEVICE[$INDEX_DRIVE_BEING_EDITED]}"
+					(( $DEBUG )) && echo "[DEBUG$i] EDIT | ${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]} | ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]} | ${aDRIVE_SOURCE_DEVICE[$INDEX_DRIVE_BEING_EDITED]}"
 					break
 
 				fi
@@ -498,10 +498,9 @@ aDRIVE_ISPARTITIONTABLE ${aDRIVE_ISPARTITIONTABLE[$i]}
 	Rm_Empty_Dir(){
 
 		local fp_dir="$1"
-		if [[ -n $fp_dir && -z $(ls -A $fp_dir) ]]; then
+		if [[ $fp_dir && -z $(ls -A $fp_dir) ]]; then
 
 			rm -R "$fp_dir"
-
 			G_DIETPI-NOTIFY 2 "Removed empty directory: $fp_dir"
 
 		else
@@ -542,7 +541,7 @@ aDRIVE_ISPARTITIONTABLE ${aDRIVE_ISPARTITIONTABLE[$i]}
 			if [[ $G_WHIP_RETURNED_VALUE == '/mnt/'* ]]; then
 
 				# - replace spaces with underscores
-				target="$(echo -e $G_WHIP_RETURNED_VALUE | sed 's/[[:space:]]/_/g')"
+				target=$(sed 's/[[:space:]]/_/g' <<< "$G_WHIP_RETURNED_VALUE")
 
 			else
 
@@ -844,7 +843,7 @@ aDRIVE_ISPARTITIONTABLE ${aDRIVE_ISPARTITIONTABLE[$i]}
 
 	RootFS_RW_Check(){
 
-		if mount | grep -m1 '[[:blank:]]/[[:blank:]]' | grep -q '(ro,'; then
+		if mount | grep -q '[[:blank:]]/[[:blank:]].*(ro,'; then
 
 			G_DIETPI-NOTIFY 1 'RootFS is currently set to R/O.'
 			G_DIETPI-NOTIFY 2 'DietPi requires RootFS R/W access. Please run "dietpi-drive_manager" to re-enable.\n'
@@ -1018,7 +1017,7 @@ aDRIVE_ISPARTITIONTABLE ${aDRIVE_ISPARTITIONTABLE[$i]}
 				TARGETMENUID=3
 
 			# - Edit drive
-			elif [[ -n $G_WHIP_RETURNED_VALUE ]]; then
+			elif [[ $G_WHIP_RETURNED_VALUE ]]; then
 
 				TARGETMENUID=1
 				DRIVE_TARGET_BEING_EDITED="$G_WHIP_RETURNED_VALUE"
@@ -1084,13 +1083,13 @@ aDRIVE_ISPARTITIONTABLE ${aDRIVE_ISPARTITIONTABLE[$i]}
 		#Filesystem
 		else
 
-			if [[ -n ${aDRIVE_FSTYPE[$INDEX_DRIVE_BEING_EDITED]} ]]; then
+			if [[ ${aDRIVE_FSTYPE[$INDEX_DRIVE_BEING_EDITED]} ]]; then
 
 				whiptail_desc+="\nFilesystem:   ${aDRIVE_FSTYPE[$INDEX_DRIVE_BEING_EDITED]}"
 
 			fi
 
-			if [[ -n ${aDRIVE_UUID[$INDEX_DRIVE_BEING_EDITED]} ]]; then
+			if [[ ${aDRIVE_UUID[$INDEX_DRIVE_BEING_EDITED]} ]]; then
 
 				whiptail_desc+="\nUUID:         ${aDRIVE_UUID[$INDEX_DRIVE_BEING_EDITED]}"
 
@@ -1130,8 +1129,8 @@ aDRIVE_ISPARTITIONTABLE ${aDRIVE_ISPARTITIONTABLE[$i]}
 
 							G_WHIP_MENU_ARRAY+=('' '●─ Userdata & Swap options ')
 
-							if ( [[ ${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]} != '/' && $FP_USERDATA_CURRENT == ${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]}* ]] ) || #off rootfs
-								( [[ ${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]} == '/' && $FP_USERDATA_CURRENT == $G_FP_DIETPI_USERDATA ]] ); then #on rootfs
+							if { [[ ${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]} != '/' && $FP_USERDATA_CURRENT == ${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]}* ]]; } || #off rootfs
+								{ [[ ${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]} == '/' && $FP_USERDATA_CURRENT == $G_FP_DIETPI_USERDATA ]]; }; then #on rootfs
 
 								G_WHIP_MENU_ARRAY+=('User data' ": [X] | DietPi user data is currently located on this drive")
 								partition_contains_userdata=1
@@ -1183,7 +1182,7 @@ aDRIVE_ISPARTITIONTABLE ${aDRIVE_ISPARTITIONTABLE[$i]}
 
 							local reserved_blocks_percent_current=0
 							local fp_temp='.dietpi-drive_manager_dumpe2fs'
-							dumpe2fs -h "${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}" > "$fp_temp"
+							dumpe2fs -h "${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}" > $fp_temp
 							local block_count="$(grep -m1 '^Block count:' $fp_temp | awk '{print $3}')"
 							local reserved_block_count="$(grep -m1 '^Reserved block count:' $fp_temp | awk '{print $4}')"
 							rm $fp_temp
@@ -1207,7 +1206,7 @@ aDRIVE_ISPARTITIONTABLE ${aDRIVE_ISPARTITIONTABLE[$i]}
 
 			fi
 
-			if (( ! ${aDRIVE_ISROM[$INDEX_DRIVE_BEING_EDITED]} && ! ${aDRIVE_ISNETWORKED[$INDEX_DRIVE_BEING_EDITED]} )); then
+			if ! (( ${aDRIVE_ISROM[$INDEX_DRIVE_BEING_EDITED]} || ${aDRIVE_ISNETWORKED[$INDEX_DRIVE_BEING_EDITED]} )); then
 
 				if (( ! ${aDRIVE_ISREADONLY_CURRENTLY[$INDEX_DRIVE_BEING_EDITED]} )); then
 
@@ -1229,7 +1228,7 @@ aDRIVE_ISPARTITIONTABLE ${aDRIVE_ISPARTITIONTABLE[$i]}
 
 				#- Transfer RootFS
 				if [[ ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]} != $FP_ROOTFS_SOURCE ]] &&
-					(( $G_HW_MODEL < 10 || $G_HW_MODEL == 10 || $G_HW_MODEL == 11 || $G_HW_MODEL == 12 )); then
+					(( $G_HW_MODEL <= 12 )); then
 
 					G_WHIP_MENU_ARRAY+=('Transfer RootFS' ': Transfer RootFS to this drive')
 
@@ -1724,7 +1723,7 @@ NB:
 		local samba_clientpassword=''
 		local samba_fp_mount_target='samba'
 
-		while true
+		while :
 		do
 
 			G_WHIP_DEFAULT_ITEM="$samba_clientname"
@@ -1744,7 +1743,7 @@ NB:
 
 			fi
 			#	NB: Convert spaces into '\040': https://github.com/Fourdee/DietPi/issues/1201#issuecomment-339720271
-			samba_clientshare=$(echo -e "$G_WHIP_RETURNED_VALUE" | sed 's/ /\\\\040/g')
+			samba_clientshare=$(sed 's/ /\\\\040/g' <<< "$G_WHIP_RETURNED_VALUE")
 
 			G_WHIP_DEFAULT_ITEM="$samba_clientuser"
 			G_WHIP_INPUTBOX 'Please enter the fileservers username\n - eg: JoeBloggs'
@@ -1767,7 +1766,7 @@ NB:
 				break
 
 			fi
-			samba_fp_mount_target="/mnt/$(echo -e $G_WHIP_RETURNED_VALUE | sed 's/\///g' | sed 's/[[:space:]]/_/g')"
+			samba_fp_mount_target="/mnt/$(sed 's/\///g' <<< $G_WHIP_RETURNED_VALUE | sed 's/[[:space:]]/_/g')"
 
 			# - Unmount if connected
 			umount /mnt/$samba_fp_mount_target &> /dev/null
@@ -1831,15 +1830,18 @@ _EOF_
 	Mount_NFS(){
 
 		rm /mnt/nfs_client/readme.txt &> /dev/null
+		Rm_Empty_Dir /mnt/nfs_client
+		local fp_tmp='.mount_out'
 
 		local nfs_clientname=''
 		local nfs_fp_mount_target='nfs_client'
+		local nfs_fp_server_share=''
 
-		while true
+		while :
 		do
 
 			G_WHIP_DEFAULT_ITEM="$nfs_clientname"
-			G_WHIP_INPUTBOX 'Please enter the fileservers IP address\n - eg: 192.168.0.2'
+			G_WHIP_INPUTBOX 'Please enter the NFS servers IP address (eg: 192.168.0.2).'
 			if (( $? )); then
 
 				break
@@ -1848,13 +1850,13 @@ _EOF_
 			nfs_clientname="$G_WHIP_RETURNED_VALUE"
 
 			G_WHIP_DEFAULT_ITEM="$nfs_fp_mount_target"
-			G_WHIP_INPUTBOX 'Please enter a unique folder name for the mount location (eg: samba). This will be placed in /mnt/'
+			G_WHIP_INPUTBOX 'Please enter a unique folder name for the mount location (eg: nfs_client). This will be placed in /mnt/'
 			if (( $? )); then
 
 				break
 
 			fi
-			nfs_fp_mount_target="/mnt/$(echo -e $G_WHIP_RETURNED_VALUE | sed 's/\///g' | sed 's/[[:space:]]/_/g')"
+			nfs_fp_mount_target="/mnt/$(sed 's/\///g' <<< $G_WHIP_RETURNED_VALUE | sed 's/[[:space:]]/_/g')"
 
 			# - Unmount if connected
 			umount /mnt/$nfs_fp_mount_target &> /dev/null
@@ -1864,29 +1866,73 @@ _EOF_
 			#Mount now
 			mkdir -p $nfs_fp_mount_target
 
-			G_RUN_CMD_INFO_ONLY=1 G_RUN_CMD mount -t nfs -o port=2049 "$nfs_clientname":/ "$nfs_fp_mount_target"
-			if (( ! $G_ERROR_HANDLER_EXITCODE_RETURN )); then
+			mount -t nfs -o port=2049 "$nfs_clientname":/ "$nfs_fp_mount_target" &> $fp_tmp
+			if (( ! $? )); then
+
+				rm $fp_tmp
 
 				#Apply to fstab
 				sed -i "\#[[:space:]]$nfs_fp_mount_target[[:space:]]#d" /etc/fstab
 				cat << _EOF_ >> /etc/fstab
-$nfs_clientname:/ $nfs_fp_mount_target nfs auto,_netdev,nofail 0  0
+$nfs_clientname:/ $nfs_fp_mount_target nfs auto,_netdev,nofail 0 0
 _EOF_
 
 				DRIVE_TARGET_BEING_EDITED="$nfs_fp_mount_target"
 				TARGETMENUID=1
 
 				G_WHIP_MSG "Mount completed. The new mount can be accessed via:\n - $nfs_fp_mount_target"
+				return 0
 
-			else
+			# Detect NFSv3 server, which requires server side path to share directory:
+			elif grep -q '[[:blank:]]vers 3[[:blank:]]' $fp_tmp &&
+				grep -q 'access denied by server while mounting' $fp_tmp; then
 
-				Rm_Empty_Dir "$nfs_fp_mount_target"
+				G_WHIP_DEFAULT_ITEM="$nfs_fp_server_share"
+				G_WHIP_INPUTBOX 'Your NFS server appears to support NFSv3 only. Mounting NFSv3 shares requires the shares path server side to be entered.
+\nPlease enter the absolute path to the share on the NFS server (eg: /mnt/nfs_share).'
+				if (( $? )); then
+
+					break
+
+				fi
+				nfs_fp_server_share="$G_WHIP_RETURNED_VALUE"
+
+				mount -t nfs -o port=2049 "$nfs_clientname":"$nfs_fp_server_share" "$nfs_fp_mount_target" &> $fp_tmp
+				if (( ! $? )); then
+
+					rm $fp_tmp
+
+					#Apply to fstab
+					sed -i "\#[[:space:]]$nfs_fp_mount_target[[:space:]]#d" /etc/fstab
+					cat << _EOF_ >> /etc/fstab
+$nfs_clientname:$nfs_fp_server_share $nfs_fp_mount_target nfs auto,_netdev,nofail 0 0
+_EOF_
+
+					DRIVE_TARGET_BEING_EDITED="$nfs_fp_mount_target"
+					TARGETMENUID=1
+
+					G_WHIP_MSG "Mount completed. The new mount can be accessed via:\n - $nfs_fp_mount_target"
+					return 0
+
+				fi
 
 			fi
 
-			break
+			# Offer retry if drive could not be mounted
+			if [[ -f $fp_tmp ]]; then
+
+				G_WHIP_YESNO "Mounting NFS drive has failed. Either the NFS server is not reachable or your entered invalid inputs.
+Do you want to retry?
+
+Error log:
+$(<$fp_tmp)"
+				(( $? )) && break
+
+			fi
 
 		done
+
+		Rm_Empty_Dir "$nfs_fp_mount_target"
 
 	}
 
