v145
DietPi-Software | Apt errors: Are now logged to
'/var/log/dietpi-software_apt.log', and, displayed during notify:
https://github.com/Fourdee/DietPi/issues/791

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -59,6 +59,8 @@
 
 	FP_DIETPIAUTOMATION_LOG="/root/DietPi-Automation.log"
 
+	FP_APT_LOG='/var/log/dietpi-software_apt.log'
+
 	#Used to set user/personal data directories (eg: usbdrive)
 	FP_DIETPI_USERDATA_DIRECTORY='/mnt/dietpi_userdata'
 	FP_DIETPI_DEDICATED_USBDRIVE=''
@@ -2584,9 +2586,9 @@ _EOF_
 
 		#-qq can add a slight period of appearing nothing is happening, lets inform user
 		/DietPi/dietpi/func/dietpi-notify 2 "Apt-get is processing, please wait...\n"
-		DEBIAN_FRONTEND=noninteractive $APT_BINARY install -y -qq $force_options $string
+		DEBIAN_FRONTEND=noninteractive $APT_BINARY install -y -qq $force_options $string 2>&1 | tee "$FP_APT_LOG"
 
-		local result=$?
+		local result=${PIPESTATUS[0]}
 		if (( $result != 0 )); then
 
 			Error_AptGet_Failed
@@ -2606,9 +2608,9 @@ _EOF_
 	#apt-get install -f
 	AGF(){
 
-		DEBIAN_FRONTEND=noninteractive $APT_BINARY install -f -y --force-yes
+		DEBIAN_FRONTEND=noninteractive $APT_BINARY install -f -y --force-yes 2>&1 | tee "$FP_APT_LOG"
 
-		local result=$?
+		local result=${PIPESTATUS[0]}
 		if (( $result != 0 )); then
 
 			Error_AptGet_Failed
@@ -10401,8 +10403,8 @@ _EOF_
 		#Simluated apt installation to check for failures related to apt-cache.
 		/DietPi/dietpi/func/dietpi-notify 2 "Running apt simulation to check for errors, please wait..."
 		local package_to_test='bash-doc'
-		apt-get install $package_to_test -s -y &> /dev/null
-		local result=$?
+		apt-get install $package_to_test -qq -s -y 2>&1 | tee "$FP_APT_LOG"
+		local result=${PIPESTATUS[0]}
 
 		/DietPi/dietpi/func/dietpi-notify -1 $result "Apt simulation |"
 
@@ -11098,7 +11100,7 @@ _EOF_
 
 		if (( $USER_INPUTS )); then
 
-			whiptail --title "Error" --msgbox "$ERROR_TEXT" 16 70
+			whiptail --title "Error" --msgbox "$ERROR_TEXT" 18 70
 
 		else
 
@@ -11125,17 +11127,20 @@ _EOF_
 
 		if [ "$1" = "simulation" ]; then
 
-			ERROR_TEXT="Apt-get simulation has failed.\n\nDietPi-Software will now exit."
+			ERROR_TEXT="Apt-get simulation has failed.\n - Apt log = $(echo -e $FP_APT_LOG)\n\nDietPi-Software will now exit."
 			Error_Display
 
 		else
 
-			ERROR_TEXT="Apt-get has failed:\n - Apt string = $string\n - Error code = $result\n - Software Title = ${aSOFTWARE_WHIP_NAME[$INSTALLING_INDEX]}: ${aSOFTWARE_WHIP_DESC[$INSTALLING_INDEX]}\n\nPlease report this issue to DietPi so it can be investigated.\n\nDietPi-Software will now exit."
+			ERROR_TEXT="Apt-get has failed:\n - Apt string = $string\n - Error code = $result\n - Software Title = ${aSOFTWARE_WHIP_NAME[$INSTALLING_INDEX]}: ${aSOFTWARE_WHIP_DESC[$INSTALLING_INDEX]}\n - Apt log = $(echo -e $FP_APT_LOG)\n\nPlease report this issue to DietPi so it can be investigated.\n\nDietPi-Software will now exit."
 			Error_Display
 
 		fi
 
 		/DietPi/dietpi/func/dietpi-notify 1 "The apt cache may be corrupt, apt mirror offline, or you have held broken pacakages. DietPi-Software will now exit.\n"
+
+		/DietPi/dietpi/func/dietpi-notify 2 "Apt Log:\n$(cat $FP_APT_LOG)\n"
+
 		/DietPi/dietpi/func/dietpi-notify 2 "Please try:"
 		/DietPi/dietpi/func/dietpi-notify 2 "- Fixing apt package errors with 'apt-get install -f'"
 		/DietPi/dietpi/func/dietpi-notify 2 "- Change apt mirror: 'dietpi-config' > 'Networking: NAS/MISC' > 'Apt Mirror'"
