v7.0
+ DietPi-Backup | Do not stop services before we definitely run the backup or restore. The rsync process check still needs to be done after stopping the services, which include the rsync daemon. But do not kill a running rsync process afterwards, better error out.
+ DietPi-Backup | Implement a first function when restoring a backup, to check whether the backup's UUIDs match the current drive's UUIDs, so that we do not restore a system that is not booting, because the bootloader and fstab do not find the configured drives. If the UUIDs seem to not match, check whether we are able to reliably make the system bootable by adjusting known bootloader configurations. Add function to restore UUIDs, in case, but content is on ToDo for now :).

diff --git a/dietpi/dietpi-backup b/dietpi/dietpi-backup
--- a/dietpi/dietpi-backup
+++ b/dietpi/dietpi-backup
@@ -115,8 +115,6 @@ _EOF_
 		# Check valid FS
 		Check_Supported_Directory_Location || return 1
 
-		Services_Stop
-
 		# Generate target dir
 		mkdir -p "$FP_TARGET"
 
@@ -125,12 +123,12 @@ _EOF_
 
 			G_WHIP_MSG "$RSYNC_MODE_TEXT failed:\n\nUnable to create $FP_TARGET"
 
-		# Error: Rsync is already running
-		elif pgrep 'rsync' &> /dev/null; then
-
-			Error_Rsync_Already_Running
-
 		else
+
+			/boot/dietpi/dietpi-services stop
+
+			# Check if rsync is already running, while the daemon should have been stopped above
+			pgrep 'rsync' &> /dev/null && { Error_Rsync_Already_Running; return 1; }
 
 			# Start Backup
 			echo -e "DietPi-Backup Log File. $(Print_Date)\n\n" > $FP_LOG
@@ -142,22 +140,22 @@ _EOF_
 			do
 
 				# System
-				G_EXEC mkdir -p "$FP_TARGET"/data
+				G_EXEC mkdir -p "$FP_TARGET/data"
 
 				# Check for sufficient free space
 				# - NB: working in KiB until end MiB conversion, as, don't like using long long int, and, KiB should offer a good end result.
-				local old_backup_size=$(du -ks "$FP_TARGET"/data | mawk '{print $1}') # Actual disk space usage
+				local old_backup_size=$(du -ks "$FP_TARGET/data" | mawk '{print $1}') # Actual disk space usage
 
-				rsync --dry-run --stats "${aRSYNC_RUN_OPTIONS_BACKUP[@]}" "$FP_SOURCE" "$FP_TARGET"/data/ > /tmp/dietpi-backup_result
+				rsync --dry-run --stats "${aRSYNC_RUN_OPTIONS_BACKUP[@]}" "$FP_SOURCE" "$FP_TARGET/data/" > /tmp/dietpi-backup_result
 				local new_backup_size=$(( $(grep -m1 '^Total file size:' /tmp/dietpi-backup_result | sed 's/[^0-9]*//g') / 1024 +1 ))  # Theoretical, data size only
 				local total_file_count=$(mawk '/^Number of files:/{print $6;exit}' /tmp/dietpi-backup_result | sed 's/[^0-9]*//g')
 				local total_folder_count=$(mawk '/^Number of files:/{print $8;exit}' /tmp/dietpi-backup_result | sed 's/[^0-9]*//g')
-				local target_fs_blocksize=$(stat -fc %s "$FP_TARGET"/data)
+				local target_fs_blocksize=$(stat -fc %s "$FP_TARGET/data")
 				new_backup_size=$(( $new_backup_size + ( $total_file_count + $total_folder_count ) * $target_fs_blocksize / 1024 + 1 )) # Add one block size to each file + dir as worst case result
 				local end_result=$(( ( $new_backup_size - $old_backup_size ) / 1024 + 1 ))
 				rm /tmp/dietpi-backup_result
 
-				if ! G_CHECK_FREESPACE "$FP_TARGET"/data $end_result; then
+				if ! G_CHECK_FREESPACE "$FP_TARGET/data" $end_result; then
 
 					G_WHIP_BUTTON_OK_TEXT='Ignore'
 					G_WHIP_BUTTON_CANCEL_TEXT='Exit'
@@ -173,7 +171,7 @@ _EOF_
 
 				G_DIETPI-NOTIFY 2 "$RSYNC_MODE_TEXT to $FP_TARGET in progress, please wait..."
 
-				rsync "${aRSYNC_RUN_OPTIONS_BACKUP[@]}" "${aRSYNC_LOGGING_OPTIONS[@]}" "$FP_SOURCE" "$FP_TARGET"/data/
+				rsync "${aRSYNC_RUN_OPTIONS_BACKUP[@]}" "${aRSYNC_LOGGING_OPTIONS[@]}" "$FP_SOURCE" "$FP_TARGET/data/"
 				EXIT_CODE=$?
 				G_DIETPI-NOTIFY -1 $EXIT_CODE "$G_PROGRAM_NAME: $RSYNC_MODE_TEXT"
 				if (( $EXIT_CODE == 0 )); then
@@ -192,15 +190,61 @@ _EOF_
 
 			done
 
+			/boot/dietpi/dietpi-services start
+
 			log=1 G_WHIP_VIEWFILE $FP_LOG
 
-			# Return to main menu
-			TARGETMENUID=0
+			TARGETMENUID=0 # Return to main menu
 
 		fi
 
-		Services_Start
+	}
 
+	# When restoring a backup, assure that either the UUIDs stored in the backup fstab/boot config matches the current system drive, or that we know all relevant files to adjust afterwards.
+	Check_UUIDs()
+	{
+		UPDATE_GRUB=0 UPDATE_RPI=0 UPDATE_ARMBIAN=0 UPDATE_ODROID=0 UPDATE_UBOOT=0
+		local uuid_root=$(lsblk -no UUID "$G_ROOTFS_DEV")
+		local partuuid_root=$(lsblk -no PARTUUID "$G_ROOTFS_DEV")
+
+		# If the current rootfs' UUID or PARTUUID can be found in the the backups fstab, it can be assumed that it was created from the same drives.
+		grep -q "^UUID=$uuid_root[[:blank:]]" "$FP_TARGET/data/etc/fstab" || grep -q "^PARTUUID=$partuuid_root[[:blank:]]" "$FP_TARGET/data/etc/fstab" && return 0
+
+		# Else check if we know how to adjust the boot config after the backup has been restored.
+		# - x86_64
+		if (( $G_HW_ARCH == 10 )) && command -v update-grub > /dev/null
+		then
+			UPDATE_GRUB=1
+
+		# - RPi
+		elif (( $G_HW_MODEL < 10 )) && [[ -f $FP_TARGET/boot/cmdline.txt ]]
+		then
+			UPDATE_RPI=1
+
+		# - Armbian
+		elif [[ -f $FP_TARGET/boot/armbianEnv.txt ]]
+		then
+			UPDATE_ARMBIAN=1
+
+		# - Odroids / classic U-Boot
+		elif [[ -f $FP_TARGET/boot/boot.ini ]]
+		then
+			UPDATE_ODROID=1
+
+		# - Modern U-Boot
+		elif [[ -f $FP_TARGET/boot/boot.cmd ]] && command -v mkimage > /dev/null
+		then
+			UPDATE_UBOOT=1
+
+		# - Else we cannot assure that the restored image will boot.
+		else
+			return 1
+		fi
+	}
+
+	Restore_UUIDs()
+	{
+		:
 	}
 
 	Run_Restore(){
@@ -212,8 +256,6 @@ _EOF_
 		# Check valid FS
 		Check_Supported_Directory_Location || return 1
 
-		Services_Stop
-
 		# Error: Backup not found
 		if [[ ! -f $FP_TARGET/$BACKUP_STATS_FILENAME ]]; then
 
@@ -222,20 +264,22 @@ _EOF_
 
 			G_WHIP_MSG "$RSYNC_MODE_TEXT failed:\n\n$FP_TARGET/$BACKUP_STATS_FILENAME does not exist\n\nHave you created a backup?"
 
-		# Error: Rsync is already running
-		elif pgrep 'rsync' &> /dev/null; then
-
-			Error_Rsync_Already_Running
-
 		# Restore
 		else
+
+			Check_UUIDs || return 1
+
+			/boot/dietpi/dietpi-services stop
+
+			# Check if rsync is already running, while the daemon should have been stopped above
+			pgrep 'rsync' &> /dev/null && { Error_Rsync_Already_Running; return 1; }
 
 			# Generate Exclude/Include lists
 			Create_Filter_Include_Exclude
 
 			G_DIETPI-NOTIFY 2 "$RSYNC_MODE_TEXT from $FP_TARGET in progress, please wait..."
 
-			rsync "${aRSYNC_RUN_OPTIONS_RESTORE[@]}" "${aRSYNC_LOGGING_OPTIONS[@]}" "$FP_TARGET"/data/ "$FP_SOURCE"
+			rsync "${aRSYNC_RUN_OPTIONS_RESTORE[@]}" "${aRSYNC_LOGGING_OPTIONS[@]}" "$FP_TARGET/data/" "$FP_SOURCE"
 			EXIT_CODE=$?
 			hash -d # Clear PATH cache
 			G_DIETPI-NOTIFY -1 $EXIT_CODE "$G_PROGRAM_NAME: $RSYNC_MODE_TEXT"
@@ -250,14 +294,15 @@ _EOF_
 
 			fi
 
+			Restore_UUIDs
+
+			/boot/dietpi/dietpi-services start
+
 			log=1 G_WHIP_VIEWFILE $FP_LOG
 
-			# Done
-			TARGETMENUID=0
+			TARGETMENUID=0 # Return to main menu
 
 		fi
-
-		Services_Start
 
 	}
 
@@ -275,10 +320,10 @@ _EOF_
 			if [[ ! -d $FP_TARGET ]]
 			then
 				G_EXEC mkdir -p "$FP_TARGET"
-				TARGET_FILESYSTEM_TYPE=$(df -T $FP_TARGET | mawk 'NR==2 {print $2}')
+				TARGET_FILESYSTEM_TYPE=$(df -T "$FP_TARGET" | mawk 'NR==2 {print $2}')
 				G_EXEC rmdir "$FP_TARGET"
 			else
-				TARGET_FILESYSTEM_TYPE=$(df -T $FP_TARGET | mawk 'NR==2 {print $2}')
+				TARGET_FILESYSTEM_TYPE=$(df -T "$FP_TARGET" | mawk 'NR==2 {print $2}')
 			fi
 
 			for i in "${aSUPPORTED_FILESYSTEMS[@]}"
@@ -355,7 +400,7 @@ _EOF_
 \nSimply choose a location where you want to save and restore your backups from, then, select Backup or Restore.
 \nMore information: https://dietpi.com/docs/dietpi_tools/#dietpi-backup-backuprestore";;
 
-				'Delete') G_WHIP_YESNO "Do you wish to DELETE the following backup?\n - $FP_TARGET" && rm -R "$FP_TARGET";;
+				'Delete') G_WHIP_YESNO "Do you wish to DELETE the following backup?\n - $FP_TARGET" && G_EXEC_NOEXIT=1 G_EXEC rm -R "$FP_TARGET";;
 
 				'Backup') G_WHIP_YESNO "The system will be backed up to:\n - $FP_TARGET\n\nDo you wish to continue and start the backup?" && Run_Backup;;
 
@@ -448,8 +493,7 @@ _EOF_
 
 		else
 
-			# Return to main menu
-			TARGETMENUID=0
+			TARGETMENUID=0 # Return to main menu
 
 		fi
 
@@ -481,9 +525,10 @@ _EOF_
 
 	Error_Rsync_Already_Running(){
 
-		G_DIETPI-NOTIFY 1 'Another Rsync process is already running.'
-		echo -e "$RSYNC_MODE_TEXT failed: $(Print_Date). Rsync is already running." >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
+		G_DIETPI-NOTIFY 1 'Another rsync process is already running.'
+		echo -e "$RSYNC_MODE_TEXT failed: $(Print_Date). rsync is already running." >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
 		G_WHIP_MSG "$RSYNC_MODE_TEXT Error:\n\nA $RSYNC_MODE_TEXT could not be started as rsync is already running."
+		/boot/dietpi/dietpi-services start
 
 	}
 
@@ -512,7 +557,6 @@ _EOF_
 #	NB: To exclude from a custom located dietpi_userdata, you need to add its symlinked path: /mnt/dietpi_userdata/excludeThis
 #- /path/to/my/file
 #- /path/to/my/directory/
-
 _EOF_
 
 	#-----------------------------------------------------------------------------
