v120
+ FBturbo for Pine64:
https://github.com/Fourdee/DietPi/issues/380#issuecomment-226512966

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -2371,6 +2371,40 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 
 				cp /DietPi/dietpi/conf/xorg_c1.conf /etc/X11/xorg.conf
 
+			#Pine64
+			elif (( $HW_MODEL >= 40 && $HW_MODEL < 50 )); then
+
+				#check source is online
+				INSTALL_URL_ADDRESS='http://dietpi.com/downloads/binaries/all/libump_1-1_arm64.deb'
+				/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+				#Install
+				if (( $? == 0 )); then
+
+					wget "$INSTALL_URL_ADDRESS" -O package.deb
+					dpkg -i package.deb
+					rm package.deb
+
+					wget http://dietpi.com/downloads/binaries/all/xf86-video-fbturbo_1-1_arm64.deb -O package.deb
+					dpkg -i package.deb
+					rm package.deb
+
+					cat << _EOF_ > /etc/X11/xorg.conf
+Section "Device"
+        Identifier      "Allwinner A10/A13 FBDEV"
+        Driver          "fbturbo"
+        Option          "fbdev" "/dev/fb0"
+        Option          "SwapbuffersWait" "true"
+EndSection
+_EOF_
+
+				else
+					Error_NoConnection_NoInstall
+
+					#Abort failed install
+					XSERVERXORG=0
+				fi
+
 			fi
 
 		fi
