v105

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -1462,7 +1462,7 @@
 				AGI hostapd isc-dhcp-server
 
 				wget "$INSTALL_URL_ADDRESS" -O package.zip
-				unzip package.zip -d /usr/sbin
+				unzip -o package.zip -d /usr/sbin
 				rm package.zip
 				chmod +x /usr/sbin/hostapd
 
@@ -3196,7 +3196,7 @@ interface=wlan$wifi_index
 driver=rtl871xdrv
 ssid=$(cat /DietPi/dietpi.txt | grep -m1 '^wifi_hotspot_ssid=' | sed 's/.*=//')
 hw_mode=g
-channel=6
+channel=$(cat /DietPi/dietpi.txt | grep -m1 '^wifi_hotspot_channel=' | sed 's/.*=//')
 macaddr_acl=0
 auth_algs=1
 ignore_broadcast_ssid=0
@@ -4995,6 +4995,56 @@ _EOF_
 				/DietPi/dietpi/dietpi-config 8 1
 
 			fi
+		fi
+
+		#Wifi Hotspot Criteria
+		if (( $WIFIHOTSPOT == 1 )); then
+
+			local check_criteria=1
+			while (( $check_criteria == 1 )); do
+
+				local criteria_passed=1
+
+				WHIP_TITLE="WiFi Hotspot Criteria"
+				WHIP_QUESTION="The following criteria must be met for this installation to succeed:"
+
+				local ethernet_active_state=$(ip r | grep -ci -m1 "$(sed -n 1p /DietPi/dietpi/.network)")
+				if (( $ethernet_active_state == 1 )); then
+					WHIP_QUESTION+="\n\n - Ethernet online: PASSED"
+				else
+					criteria_passed=0
+					WHIP_QUESTION+="\n\n - Ethernet online: FAILED.\nUse dietpi-config to connect and configure ethernet."
+				fi
+
+				if [ -d /sys/class/net/wlan$(sed -n 2p /DietPi/dietpi/.network) ]; then
+					WHIP_QUESTION+="\n\n - Wifi adapter detected: PASSED"
+				else
+					criteria_passed=0
+					WHIP_QUESTION+="\n\n - Wifi adapter detected: FAILED.\nPlease connect a WiFi adapter and try again."
+				fi
+
+				#Passed
+				if (( $criteria_passed == 1 )); then
+					WHIP_QUESTION+="\n\nPASSED: Criteria met. Good to go."
+					whiptail --title "$WHIP_TITLE" --msgbox "$WHIP_QUESTION" --backtitle "$WHIP_BACKTITLE" 14 75
+					check_criteria=0
+
+				#Failed, retry?
+				else
+					WHIP_QUESTION+="\n\nFAILED: Criteria not met. Would you like to check again?"
+					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 16 75
+					CHOICE=$?
+					if (( $CHOICE == 0 )); then
+						echo "retry" &> /dev/null
+					else
+						check_criteria=0
+						WIFIHOTSPOT=0
+						whiptail --title "WiFi Hotspot Failed" --msgbox "WiFi Hotspot criteria was not met. Your selection has been removed." --backtitle "$WHIP_BACKTITLE" 10 65
+					fi
+				fi
+
+			done
+
 		fi
 
 		#Weaved
