v6.26
+ DietPi-LetsEncrypt | Minor coding and wording

diff --git a/dietpi/dietpi-letsencrypt b/dietpi/dietpi-letsencrypt
--- a/dietpi/dietpi-letsencrypt
+++ b/dietpi/dietpi-letsencrypt
@@ -38,8 +38,8 @@
 	# Add post-renewal tasks via systemd unit drop-in
 	FP_RENEWAL='/etc/systemd/system/certbot.service.d'
 
-	LETSENCRYPT_DOMAIN='mydomain.com'
-	LETSENCRYPT_EMAIL='myemail@email.com'
+	LETSENCRYPT_DOMAIN='mydomain.org'
+	LETSENCRYPT_EMAIL='myemail@email.org'
 	LETSENCRYPT_REDIRECT=0
 	LETSENCRYPT_HSTS=0
 	LETSENCRYPT_KEYSIZE=4096
@@ -69,7 +69,7 @@
 
 			# - Cert me up Apache2
 			#	If cert exists already, attempt renewal. This allows easy configuration update via "dietpi-letsencrypt 1" without using up limited certs per week.
-			if [[ -f $fp_cert_dir/cert.pem ]]; then
+			if [[ -f $fp_cert_dir'/cert.pem' ]]; then
 
 				$FP_BINARY renew
 				local exit_code=$?
@@ -82,8 +82,8 @@
 			fi
 			if (( $exit_code )); then
 
-				echo "[FAILED] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..." | tee $FP_LOGFILE
-				(( $INPUT )) || G_WHIP_MSG "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..."
+				echo "[FAILED] CertBot failed with error code ($exit_code), please check its terminal output. Aborting..." | tee $FP_LOGFILE
+				(( $INPUT )) || G_WHIP_MSG "[FAILURE] CertBot failed with error code ($exit_code), please check its terminal output. Aborting..."
 				return 1
 
 			fi
@@ -95,7 +95,7 @@
 			G_DIETPI-NOTIFY 0 'Lighttpd webserver detected'
 
 			# - Cert me up
-			if [[ -f $fp_cert_dir/cert.pem ]]; then
+			if [[ -f $fp_cert_dir'/cert.pem' ]]; then
 
 				$FP_BINARY renew
 				local exit_code=$?
@@ -108,15 +108,15 @@
 			fi
 			if (( $exit_code )); then
 
-				echo "[FAILED] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..." | tee $FP_LOGFILE
-				(( $INPUT )) || G_WHIP_MSG "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..."
+				echo "[FAILED] CertBot failed with error code ($exit_code), please check its terminal output. Aborting..." | tee $FP_LOGFILE
+				(( $INPUT )) || G_WHIP_MSG "[FAILURE] CertBot failed with error code ($exit_code), please check its terminal output. Aborting..."
 				return 1
 
 			fi
 
 			# - Create combined key
 			cat "$fp_cert_dir/privkey.pem" "$fp_cert_dir/cert.pem" > "$fp_cert_dir/combined.pem"
-			if [[ ! -f $fp_cert_dir/combined.pem ]]; then
+			if [[ ! -f $fp_cert_dir'/combined.pem' ]]; then
 
 				echo "[FAILED] $fp_cert_dir/combined.pem could not be created. Please check existence of privkey.pem and cert.pem within this folder, as result of CertBot execution. Aborting..." | tee $FP_LOGFILE
 				(( $INPUT )) || G_WHIP_MSG "[FAILED] $fp_cert_dir/combined.pem could not be created. Please check existence of privkey.pem and cert.pem within this folder, as result of CertBot execution. Aborting..."
@@ -210,7 +210,7 @@ _EOF_
 			G_CONFIG_INJECT 'server_name[[:blank:]]' "	server_name $LETSENCRYPT_DOMAIN;" "$fp_defaultsite" 'listen[[:blank:]]'
 
 			# - Restart Nginx to apply server_name change
-			systemctl restart nginx
+			G_RUN_CMD systemctl restart nginx
 
 			local options='--nginx'
 			(( $LETSENCRYPT_REDIRECT )) && options+=' --redirect' || options+=' --no-redirect'
@@ -230,8 +230,8 @@ _EOF_
 			fi
 			if (( $exit_code )); then
 
-				echo "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..." | tee $FP_LOGFILE
-				(( $INPUT )) || G_WHIP_MSG "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..."
+				echo "[FAILURE] CertBot failed with error code ($exit_code), please check its terminal output. Aborting..." | tee $FP_LOGFILE
+				(( $INPUT )) || G_WHIP_MSG "[FAILURE] CertBot failed with error code ($exit_code), please check its terminal output. Aborting..."
 				return 1
 
 			fi
@@ -265,8 +265,8 @@ _EOF_
 			fi
 			if (( $exit_code )); then
 
-				echo "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..." | tee $FP_LOGFILE
-				(( $INPUT )) || G_WHIP_MSG "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..."
+				echo "[FAILURE] CertBot failed with error code ($exit_code), please check its terminal output. Aborting..." | tee $FP_LOGFILE
+				(( $INPUT )) || G_WHIP_MSG "[FAILURE] CertBot failed with error code ($exit_code), please check its terminal output. Aborting..."
 				return 1
 
 			fi
@@ -316,14 +316,15 @@ _EOF_
 			# - Change permissions on renewal script
 			G_RUN_CMD chmod +x /home/minio-user/.minio/dietpi-cert-renewl.sh
 
-			# Add Minio renewal to certbot system service
+			# - Add Minio renewal to certbot system service
 			[[ -d $FP_RENEWAL ]] || mkdir "$FP_RENEWAL"
 			cat << _EOF_ > "$FP_RENEWAL"/dietpi-minio.conf
 [Service]
 ExecStartPost=/home/minio-user/.minio/dietpi-cert-renewl.sh &>> $FP_LOGFILE
 _EOF_
 
-			echo '[ INFO ] HTTPS redirect and HSTS is not supported for Minio, thus will be ignored.' | tee $FP_LOGFILE
+			# - Inform user that HTTPS redirect and HSTS is not supported for Minio, if chosen
+			(( $LETSENCRYPT_REDIRECT || $LETSENCRYPT_HSTS )) && echo '[ INFO ] HTTPS redirect and HSTS is not supported for Minio, thus will be ignored.' | tee $FP_LOGFILE
 
 		else
 
@@ -400,16 +401,9 @@ _EOF_
 		local input_desc=$2
 
 		G_WHIP_DEFAULT_ITEM=$input_value
-		if G_WHIP_INPUTBOX "Please enter a value for $input_desc"; then
+		G_WHIP_INPUTBOX "Please enter a value for $input_desc" || return 1
 
-			input_value=$G_WHIP_RETURNED_VALUE
-
-			# Prevent null values
-			[[ $input_value ]] || input_value='NULL'
-
-		fi
-
-		echo "$input_value"
+		echo "${G_WHIP_RETURNED_VALUE:-NULL}"
 
 	}
 
@@ -443,13 +437,22 @@ _EOF_
 
 				'Domain')
 
-					while :
+					local new=$LETSENCRYPT_DOMAIN
+					local error=''
+					while new=$(Input_Box "$new" "Website-Domain$error")
 					do
 
-						LETSENCRYPT_DOMAIN=$(Input_Box "$LETSENCRYPT_DOMAIN" Website-Domain)
-						[[ $LETSENCRYPT_DOMAIN == *?.?* && ! $(sed 's/\.//g' <<< "$LETSENCRYPT_DOMAIN") =~ ^[0-9]*$ ]] && break
+						# Must contain at least one dot with leading secondary domain and trailing top domain
+						# Must not be an IP address with integers and dots only
+						if [[ $new == *?.?* && $new == *[^0-9.]* ]]; then
 
-						G_WHIP_MSG "[FAILED] \"$LETSENCRYPT_DOMAIN\" is no valid domain name.\n\nNote that raw IP addresses are not allowed by LetsEncrypt, thus a domain is required.\nYou can install No-IP with DietPi-Software to aquire one.\n\nPlease try again..."
+							LETSENCRYPT_DOMAIN=$new
+
+						else
+
+							error="\n\n[FAILED] \"$new\" is no valid domain name.\n\nNote that raw IP addresses are not allowed by Let's Encrypt, thus a domain is required.\nYou can install No-IP with DietPi-Software to aquire one.\n\nPlease retry..."
+
+						fi
 
 					done
 
@@ -477,19 +480,15 @@ _EOF_
 
 						G_WHIP_YESNO 'HTTP Strict Transport Security (HSTS)\n
 Carefully read the following, before enabling this feature:
-
-HSTS will make your browser remember that it accessed your domain/IP via HTTPS for one or half a year.
+\nHSTS will make your browser remember that it accessed your domain/IP via HTTPS for one or half a year.
 From then on, it will always access the same domain/IP via HTTPS, denying all HTTP access attempts.
 This increases security in addition to encrypted traffic, as noone can silently redirect you to a fake web page.
 HTTPS forces web pages to verify their identity via the HTTPS certificate, which cannot be faked in a reasonable time.
-
-The downside is, your browser will deny access to all non-HTTPS web applications behind the same domain/IP.
+\nThe downside is, your browser will deny access to all non-HTTPS web applications behind the same domain/IP.
 EG: "Sonarr" uses a standalone web server contained within the application. This uses a custom port, which can be recognized as you need to add a non-default port to your IP/domain to access it: "192.168.0.100:8989".
 Enabling HSTS will prevent access to applications which use a standalone webserver.
-
-It is possible to enable HTTPS support for standalone web servers, however, you will need to research and achieve this manually.
-
-Are you sure that you want to enable HTTP Strict Transport Security?' && LETSENCRYPT_HSTS=1
+\nIt is possible to enable HTTPS support for standalone web servers, however, you will need to research and achieve this manually.
+\nAre you sure that you want to enable HTTP Strict Transport Security?' && LETSENCRYPT_HSTS=1
 
 					fi
 
@@ -503,12 +502,12 @@ Are you sure that you want to enable HTTP Strict Transport Security?' && LETSENC
 
 				'Apply')
 
-					if G_WHIP_YESNO 'LetsEncrypt will now be run. This will:
-- Create your free SSL cert.
-- Automatically apply and enable your SSL cert
+					if G_WHIP_YESNO 'CertBot will now run, which will:
+- Create your free SSL certificate
+- Automatically apply your SSL certificate to the webserver
+- Enable HTTPS for all web applications which use "/var/www/"
 - NB: This process can take a long time, please be patient.
-- NB: HTTPS will automatically be applied to the webserver and applications which use "/var/www/*".
-      Applications which use their own webserver (these usually have their own :port number), will not be available under HTTPS, and, these will need to be configured manually.
+      This does not apply to applications which use their own webserver, which usually have their own :port number. These will need to be configured manually.
 \nWould you like to continue?'; then
 
 						Write_Settings_File
