v7.0
+ DietPi-Drive_Manager | The "_netdev" mount option is not required for CIFS and Samba mounts, since systemd identifies them automatically as remote/network mounts. This option is only required when the remote/network mount cannot be identified by its file system type: http://codingberg.com/linux/systemd_when_to_use_netdev_mount_option
+ DietPi-Drive_Manager | Minor coding

diff --git a/dietpi/dietpi-drive_manager b/dietpi/dietpi-drive_manager
--- a/dietpi/dietpi-drive_manager
+++ b/dietpi/dietpi-drive_manager
@@ -30,8 +30,8 @@
 	SERVICES_STOPPED=0
 	G_EXIT_CUSTOM(){ (( $SERVICES_STOPPED )) && /boot/dietpi/dietpi-services start; }
 
-	# Grab input (valid interger)
-	disable_error=1 G_CHECK_VALIDINT "$1" && INPUT=$1 || INPUT=0
+	# Grab input
+	[[ $1 == [134] ]] || INPUT=0
 
 	EXIT_CODE=0
 
@@ -65,7 +65,6 @@
 		aDRIVE_SIZE_TOTAL[$index]=
 		aDRIVE_SIZE_USED[$index]=
 		aDRIVE_SIZE_PERCENTUSED[$index]=
-
 		aDRIVE_ISFILESYSTEM[$index]=0
 		aDRIVE_ISMOUNTED[$index]=0
 		aDRIVE_ISREADONLY_CURRENTLY[$index]=0
@@ -1725,7 +1724,7 @@ NTFS:\nRecommended if you plan to use this drive on a Windows system. High CPU u
 		G_AG_CHECK_INSTALL_PREREQ smbclient cifs-utils
 
 		# Mount now
-		mkdir -p "$samba_fp_mount_target"
+		G_EXEC mkdir -p "$samba_fp_mount_target"
 		> $fp_tmp
 
 		# - Mount attempts from highest CIFS version to lowest, until one succeeds
@@ -1740,7 +1739,7 @@ NTFS:\nRecommended if you plan to use this drive on a Windows system. High CPU u
 				# Apply to fstab
 				sed -i "\#[[:space:]]${samba_fp_mount_target}[[:space:]]#d" /etc/fstab
 				# - NB: Convert spaces to '\040': https://github.com/MichaIng/DietPi/issues/1201#issuecomment-339720271
-				echo "//$samba_clientname/${samba_clientshare//[[:space:]]/\\040} $samba_fp_mount_target cifs username=$samba_clientuser,password=$samba_clientpassword,iocharset=utf8,uid=dietpi,gid=dietpi,file_mode=0770,dir_mode=0770,vers=$i,_netdev,nofail,noauto,x-systemd.automount" >> /etc/fstab
+				echo "//$samba_clientname/${samba_clientshare//[[:space:]]/\\040} $samba_fp_mount_target cifs username=$samba_clientuser,password=$samba_clientpassword,iocharset=utf8,uid=dietpi,gid=dietpi,file_mode=0770,dir_mode=0770,vers=$i,nofail,noauto,x-systemd.automount" >> /etc/fstab
 
 				MENU_DRIVE_TARGET=$samba_fp_mount_target
 				Init_Drives_and_Refresh
@@ -1795,14 +1794,14 @@ NTFS:\nRecommended if you plan to use this drive on a Windows system. High CPU u
 		G_AG_CHECK_INSTALL_PREREQ nfs-common netbase
 
 		# Mount now
-		mkdir -p "$nfs_fp_mount_target"
+		G_EXEC mkdir -p "$nfs_fp_mount_target"
 		> $fp_tmp
 
 		if mount -vt nfs -o port=2049 "$nfs_server_ip":/ "$nfs_fp_mount_target" &>> $fp_tmp; then
 
 			# Apply to fstab
 			sed -i "\#[[:space:]]${nfs_fp_mount_target}[[:space:]]#d" /etc/fstab
-			echo "$nfs_server_ip:/ $nfs_fp_mount_target nfs _netdev,nofail,noauto,x-systemd.automount" >> /etc/fstab
+			echo "$nfs_server_ip:/ $nfs_fp_mount_target nfs nofail,noauto,x-systemd.automount" >> /etc/fstab
 
 			MENU_DRIVE_TARGET=$nfs_fp_mount_target
 			Init_Drives_and_Refresh
@@ -1825,7 +1824,7 @@ NTFS:\nRecommended if you plan to use this drive on a Windows system. High CPU u
 
 				# Apply to fstab
 				sed -i "\#[[:space:]]${nfs_fp_mount_target}[[:space:]]#d" /etc/fstab
-				echo "$nfs_server_ip:$nfs_fp_server_share $nfs_fp_mount_target nfs _netdev,nofail,noauto,x-systemd.automount" >> /etc/fstab
+				echo "$nfs_server_ip:$nfs_fp_server_share $nfs_fp_mount_target nfs nofail,noauto,x-systemd.automount" >> /etc/fstab
 
 				MENU_DRIVE_TARGET=$nfs_fp_mount_target
 				Init_Drives_and_Refresh
@@ -1870,24 +1869,18 @@ NTFS:\nRecommended if you plan to use this drive on a Windows system. High CPU u
 		# Generate menu
 		G_WHIP_MENU_ARRAY=()
 
-		df -Ph | tail -n +2 | sed -E '/(^udev|tmpfs)/d' > .df_out_tmp
-
 		while read -r line
 		do
 
 			G_WHIP_MENU_ARRAY+=("$(mawk '{print $6}' <<< "$line")" ": $(mawk '{print $1" | size: "$2"iB | available: "$4"iB"}' <<< "$line")")
 
-		done < .df_out_tmp
-		rm .df_out_tmp
+		done < <(df -Ph | tail -n +2 | sed -E '/(^udev|tmpfs)/d')
 
-		if G_WHIP_MENU 'Please select a mount location to use:'; then
+		G_WHIP_MENU 'Please select a mount location to use:' || exit 1
 
-			G_DIETPI-NOTIFY 0 "Drive mount selected: $G_WHIP_RETURNED_VALUE"
-			echo "$G_WHIP_RETURNED_VALUE" > $fp_mount_selection
-			exit 0
-
-		fi
-		exit 1
+		G_DIETPI-NOTIFY 0 "Drive mount selected: $G_WHIP_RETURNED_VALUE"
+		echo "$G_WHIP_RETURNED_VALUE" > $fp_mount_selection
+		exit 0
 
 	}
 
