v90

diff --git a/dietpi/dietpi-backup b/dietpi/dietpi-backup
--- a/dietpi/dietpi-backup
+++ b/dietpi/dietpi-backup
@@ -295,115 +295,137 @@
 	}
 
 	Run_Backup(){
-	
-		##Ensure Rsync isnt already running
-		#if (( $( ps aux | grep -ci -m1 "[r]sync ") == 1 )); then
+
+		local mode_text="Backup"
+
+		#Generate target dir.
+		mkdir -p "$FP_TARGET"
 
 		#Check valid FS
 		Check_Supported_Filesystem
-		if (( $TARGET_FILESYSTEM_SUPPORTED == 1 )); then
 
-			Services_Stop
+		#Error: Rsync is already running
+		if (( $(ps aux | grep -ci -m1 "[r]sync") == 1 )); then
+
+			echo -e "$mode_text failed: $(date +"%d-%m-%Y_%H%M"). Rsync is already running." >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
+			#Menu
+			if (( $INPUT == 0 )); then
+				whiptail --title "$mode_text Error" --msgbox "A $mode_text could not be started as rsync is already running." --backtitle "$WHIP_BACKTITLE" 13 60
+			fi
+
+		#Error: Filesystem not supported
+		elif (( $TARGET_FILESYSTEM_SUPPORTED == 0 )); then
+
+			echo -e "Filesystem not supported: $TARGET_FILESYSTEM_TYPE"
+
+		#Error: Unable to create target folder.
+		elif [ ! -d "$FP_TARGET" ]; then
+
+			if (( $INPUT == 0 )); then
+				whiptail --title "$mode_text failed." --msgbox "Unable to create $FP_TARGET" --backtitle "$WHIP_BACKTITLE" 10 60
+			fi
+
+		else
+
+			#Start Backup
+
+			echo -e "DietPi-Backup Log File. $(date +"%d-%m-%Y_%H%M")\n\n" > "$LOGFILE"
 
 			#Generate Exclude/Include lists
 			Create_Exclude_File
 			Create_Include_File
 
-			#Generate target dir.
-			mkdir -p "$FP_TARGET"
+			Services_Stop
 
-			#Start Backup
-			if [ -d "$FP_TARGET" ]; then
-
-				#Remove previous logfile
-				rm "$LOGFILE" &> /dev/null
-				echo -e "DietPi-Backup Log File. $(date +"%d-%m-%Y_%H%M")\n\n" > "$LOGFILE"
-
-				#Backup
-				rsync $RSYNC_RUN_OPTIONS "$FP_SOURCE" "$FP_TARGET"/
-
-				#Success
-				if (( $? == 0 )); then
-					echo -e "Backup Completed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
-					#Menu
-					if (( $INPUT == 0 )); then
-						whiptail --title "Backup completed" --msgbox "Your backup was saved to:\n$FP_TARGET\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 11 60
-					fi
-
-				#Failed
-				else
-					echo -e "Backup Failed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
-					#Menu
-					if (( $INPUT == 0 )); then
-						whiptail --title "Backup failed" --msgbox "Your backup has failed. Please see the Log file for more information:\n\n$LOGFILE" --backtitle "$WHIP_BACKTITLE" 12 60
-					fi
-				fi
-
-				#return to main menu
-				TARGETMENUID=0
-
-			#error Folder not found
-			else
-				if (( $INPUT == 0 )); then
-					whiptail --title "Backup failed." --msgbox "Unable to create $FP_TARGET" --backtitle "$WHIP_BACKTITLE" 10 60
-				fi
-			fi
+			rsync $RSYNC_RUN_OPTIONS "$FP_SOURCE" "$FP_TARGET"/
 
 			Services_Start
 
-		else
-			echo -e "Filesystem not supported: $TARGET_FILESYSTEM_TYPE"
+			#Success
+			if (( $? == 0 )); then
+				echo -e "$mode_text Completed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
+				#Menu
+				if (( $INPUT == 0 )); then
+					whiptail --title "$mode_text completed" --msgbox "Your $mode_text was saved to:\n$FP_TARGET\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 11 60
+				fi
+
+			#Failed
+			else
+				echo -e "$mode_text Failed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
+				#Menu
+				if (( $INPUT == 0 )); then
+					whiptail --title "$mode_text failed" --msgbox "Your $mode_text has failed. Please see the Log file for more information:\n\n$LOGFILE" --backtitle "$WHIP_BACKTITLE" 12 60
+				fi
+			fi
+
+			#return to main menu
+			TARGETMENUID=0
+
 		fi
 
 	}
 
 	Run_Restore(){
 
+		local mode_text="Restore"
+
 		#Check valid FS
 		Check_Supported_Filesystem
-		if (( $TARGET_FILESYSTEM_SUPPORTED == 1 )); then
 
-			Services_Stop
+		#Error: Rsync is already running
+		if (( $(ps aux | grep -ci -m1 "[r]sync") == 1 )); then
+
+			echo -e "$mode_text failed: $(date +"%d-%m-%Y_%H%M"). Rsync is already running." >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
+			#Menu
+			if (( $INPUT == 0 )); then
+				whiptail --title "$mode_text Error" --msgbox "A $mode_text could not be started as rsync is already running." --backtitle "$WHIP_BACKTITLE" 13 60
+			fi
+
+		#Error: Filesystem not supported
+		elif (( $TARGET_FILESYSTEM_SUPPORTED == 0 )); then
+
+			echo -e "Filesystem not supported: $TARGET_FILESYSTEM_TYPE"
+
+		#Error: Backup not found
+		elif [ ! -f "$FP_TARGET/$BACKUP_STATS_FILENAME" ]; then
+
+			if (( $INPUT == 0 )); then
+				whiptail --title "$mode_text failed." --msgbox "$FP_TARGET/$BACKUP_STATS_FILENAME does not exist" --backtitle "$WHIP_BACKTITLE" 10 70
+			fi
+
+		#Restore
+		else
 
 			#Generate Exclude/Include lists
 			Create_Exclude_File
 			Create_Include_File
 
-			#Restore
-			if [ -f "$FP_TARGET/$BACKUP_STATS_FILENAME" ]; then
-				rsync $RSYNC_RUN_OPTIONS "$FP_TARGET"/ "$FP_SOURCE"
+			Services_Stop
 
-				#Success
-				if (( $? == 0 )); then
-					echo -e "Restore Completed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
-					#Menu
-					if (( $INPUT == 0 )); then
-						whiptail --title "Restore completed" --msgbox "Your system has been restored from:\n$FP_TARGET" --backtitle "$WHIP_BACKTITLE" 10 60
-					fi
-
-				#Failed
-				else
-					echo -e "Restore Failed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
-					#Menu
-					if (( $INPUT == 0 )); then
-						whiptail --title "Restore failed" --msgbox "Your restore has failed. Please see the Log file for more information:\n\n$LOGFILE" --backtitle "$WHIP_BACKTITLE" 12 60
-					fi
-				fi
-
-				#return to main menu
-				TARGETMENUID=0
-
-			#error backup not found
-			else
-				if (( $INPUT == 0 )); then
-					whiptail --title "Restore failed." --msgbox "$FP_TARGET/$BACKUP_STATS_FILENAME does not exist" --backtitle "$WHIP_BACKTITLE" 10 70
-				fi
-			fi
+			rsync $RSYNC_RUN_OPTIONS "$FP_TARGET"/ "$FP_SOURCE"
 
 			Services_Start
 
-		else
-			echo -e "Filesystem not supported: $TARGET_FILESYSTEM_TYPE"
+			#Success
+			if (( $? == 0 )); then
+				echo -e "$mode_text Completed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
+				#Menu
+				if (( $INPUT == 0 )); then
+					whiptail --title "$mode_text completed" --msgbox "Your system has been restored from:\n$FP_TARGET" --backtitle "$WHIP_BACKTITLE" 10 60
+				fi
+
+			#Failed
+			else
+				echo -e "$mode_text Failed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
+				#Menu
+				if (( $INPUT == 0 )); then
+					whiptail --title "$mode_text failed" --msgbox "Your $mode_text has failed. Please see the Log file for more information:\n\n$LOGFILE" --backtitle "$WHIP_BACKTITLE" 12 60
+				fi
+			fi
+
+			#return to main menu
+			TARGETMENUID=0
+
 		fi
 
 	}
@@ -447,7 +469,6 @@
 
 		TARGET_FILESYSTEM_SUPPORTED=0
 		TARGET_FILESYSTEM_TYPE="$( df -T $FP_TARGET | sed -n '2p' | awk '{print $2}')"
-
 		for ((i=0; i<${#aSUPPORTED_FILESYSTEMS[@]}; i++))
 		do
 			if [ "$TARGET_FILESYSTEM_TYPE" = "${aSUPPORTED_FILESYSTEMS[$i]}" ]; then
@@ -508,7 +529,7 @@
 
 	#-----------------------------------------------------------------------------
 	#Run menu
-	else
+	elif (( $INPUT == 0 )); then
 
 		while (( $TARGETMENUID > -1 )); do
 
@@ -522,6 +543,8 @@
 
 		done
 
+		#Save settings
+		Write_Settings_File
 	fi
 
 	#-----------------------------------------------------------------------------------
@@ -531,9 +554,6 @@
 	#-----------------------------------------------------------------------------------
 	#delete[] array
 	unset aSUPPORTED_FILESYSTEMS
-	#-----------------------------------------------------------------------------------
-	#Save settings
-	Write_Settings_File
 	#-----------------------------------------------------------------------------------
 	exit
 	#-----------------------------------------------------------------------------------
diff --git a/dietpi/dietpi-sync b/dietpi/dietpi-sync
--- a/dietpi/dietpi-sync
+++ b/dietpi/dietpi-sync
@@ -42,6 +42,8 @@
 	SYNC_DRY_RUN=0
 
 	SYNC_MODE_TEXT="Disabled"
+	SYNC_COMPRESSION_TEXT="Disabled"
+	SYNC_CRONDAILY_TEXT="Disabled"
 
 	#TARGETMENUID=0
 	Menu_Main(){
@@ -56,15 +58,21 @@
 			SYNC_COMPRESSION_TEXT="Enabled"
 		fi
 
+		SYNC_CRONDAILY_TEXT="Disabled"
+		if (( $SYNC_CRONDAILY == 1 )); then
+			SYNC_CRONDAILY_TEXT="Enabled"
+		fi
+
 		WHIP_TITLE='--- DietPi-Sync ---'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Source location:\n$FP_SOURCE\n\nTarget location:\n$FP_TARGET" --cancel-button "Exit" --backtitle "$WHIP_BACKTITLE" 19 73 7 \
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Source location:\n$FP_SOURCE\n\nTarget location:\n$FP_TARGET" --cancel-button "Exit" --backtitle "$WHIP_BACKTITLE" 20 73 8 \
 		"Help" "What does DietPi-Sync do?" \
 		"Source Location" "Change the Source directory." \
 		"Target Location" "Change the Target directory." \
 		"Delete Mode" "$SYNC_MODE_TEXT" \
 		"Compression" "$SYNC_COMPRESSION_TEXT" \
-		"Dry Run" "Run a test Sync without modifying any data." \
-		"Sync" "Sync the Source location to the Target location." 3>&1 1>&2 2>&3)
+		"Sync: Daily" "$SYNC_CRONDAILY_TEXT" \
+		"Sync: Dry Run" "Run a test Sync without modifying any data." \
+		"Sync: Now" "Sync the Source location to the Target location." 3>&1 1>&2 2>&3)
 
 		CHOICE=$?
 		if (( $CHOICE == 0 )); then
@@ -79,7 +87,16 @@
 				Help)
 					whiptail --title "DietPi-Sync Help" --msgbox "DietPi-Sync is a program that allows you to duplicate a directory from one location (Source) to another (Target).\n\nFor example: If we want to duplicate (sync) the data on our external USB HDD to another location, we simply select the USB HDD as the source, then, select a target location. The target location can be anything from a networked samba fileserver, or even a FTP server.\n\nIf you would like to test a sync without modifiying any data, simply select Dry Run.\n\nMore information:\n - http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=5&p=256#p256" --backtitle "$WHIP_BACKTITLE" 19 75
 				;;
-				"Dry Run")
+				"Delete Mode")
+					TARGETMENUID=3
+				;;
+				Compression)
+					TARGETMENUID=4
+				;;
+				"Sync: Daily")
+					TARGETMENUID=5
+				;;
+				"Sync: Dry Run")
 					WHIP_TITLE=' Test Dry Run Sync? '
 					whiptail --title "$WHIP_TITLE" --yesno "Source location:\n$FP_SOURCE/*\n\nTarget location:\n$FP_TARGET/*\n\nThis is a Dry Run for testing. No data will be modified.\n\nDo you wish to continue?" --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 16 72
 					CHOICE=$?
@@ -88,7 +105,7 @@
 						Run_Sync
 					fi
 				;;
-				Sync)
+				"Sync: Now")
 					WHIP_TITLE=' Start Sync? '
 					whiptail --title "$WHIP_TITLE" --yesno "Source location:\n$FP_SOURCE/*\n\nTarget location:\n$FP_TARGET/*\n\nA copy of all the files and folders inside your Source location, will be created at the Target location.\n\nDo you wish to continue?" --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 16 72
 					CHOICE=$?
@@ -96,12 +113,6 @@
 						SYNC_DRY_RUN=0
 						Run_Sync
 					fi
-				;;
-				"Delete Mode")
-					TARGETMENUID=3
-				;;
-				Compression)
-					TARGETMENUID=4
 				;;
 			esac
 
@@ -243,7 +254,7 @@
 	#TARGETMENUID=4
 	Menu_Set_Compression(){
 
-		WHIP_TITLE=' Sync Delete Mode '
+		WHIP_TITLE=' Sync Compression Mode '
 		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Please select the compression mode.\n\nDisabled:\nNo compression will be used during data transfer.\n\nEnabled:\nData will be compressed when its being transfered. Useful for slow connections, however, its CPU intensive." --cancel-button "Back" --default-item "$SYNC_COMPRESSION_TEXT" --backtitle "$WHIP_BACKTITLE" 17 75 2 \
 		"Disabled" "Transfer data in its original state." \
 		"Enabled" "Compress the data during transfer." 3>&1 1>&2 2>&3)
@@ -257,6 +268,33 @@
 				;;
 				Enabled)
 					SYNC_COMPRESSION=1
+				;;
+			esac
+
+		fi
+
+		#Return to main menu
+		TARGETMENUID=0
+
+	}
+
+	#TARGETMENUID=5
+	Menu_Set_CronDaily(){
+
+		WHIP_TITLE=' Sync Cron Daily '
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Disabled:\nThe user must manually sync using dietpi-sync.\n\nEnabled:\nA cron job will be created that automatically runs dietpi-sync, once a day.\n\n(NOTICE):\nBefore enabling this feature, please run a test sync (Dry Run) to verify what will happen." --cancel-button "Back" --default-item "$SYNC_COMPRESSION_TEXT" --backtitle "$WHIP_BACKTITLE" 19 75 2 \
+		"Disabled" "Manual sync." \
+		"Enabled" "Automatically sync once a day." 3>&1 1>&2 2>&3)
+		CHOICE=$?
+
+		if (( $CHOICE == 0 )); then
+
+			case "$OPTION" in
+				Disabled)
+					SYNC_CRONDAILY=0
+				;;
+				Enabled)
+					SYNC_CRONDAILY=1
 				;;
 			esac
 
@@ -347,10 +385,10 @@
 	FP_EXCLUDE_USER="/DietPi/dietpi/.dietpi-sync_exclude"
 	FP_INCLUDE_USER="/DietPi/dietpi/.dietpi-sync_include"
 
-	#Extra Rsync options
-	# (0=update 1=--delete)
+	#Extra options
 	SYNC_DELETE_MODE=0
 	SYNC_COMPRESSION=0
+	SYNC_CRONDAILY=0
 
 
 	Create_Exclude_File(){
@@ -420,17 +458,29 @@
 
 	Run_Sync(){
 
-		#Services_Stop
-
-		#Generate Exclude/Include lists
-		Create_Exclude_File
-		Create_Include_File
-
 		#Generate Target dir.
 		mkdir -p "$FP_TARGET"
 
+		#Check if Rsync is already running
+		if (( $(ps aux | grep -ci -m1 "[r]sync") == 1 )); then
+			echo -e "Sync failed: $(date +"%d-%m-%Y_%H%M"). Rsync is already running." >> "$FP_TARGET/$SYNC_STATS_FILENAME"
+			#Menu
+			if (( $INPUT == 0 )); then
+				whiptail --title "Sync Error" --msgbox "A sync job could not be started as rsync is already running." --backtitle "$WHIP_BACKTITLE" 13 60
+			fi
+
+		#error Folder not found
+		elif [ ! -d "$FP_TARGET" ]; then
+			if (( $INPUT == 0 )); then
+				whiptail --title "Sync failed." --msgbox "Unable to create Target directory $FP_TARGET" --backtitle "$WHIP_BACKTITLE" 10 60
+			fi
+
 		#Start sync
-		if [ -d "$FP_TARGET" ]; then
+		else
+
+			#Generate Exclude/Include lists
+			Create_Exclude_File
+			Create_Include_File
 
 			#Archive mode
 			local rync_options="-a"
@@ -456,13 +506,15 @@
 				rync_options+=" --delete"
 			fi
 
-			#Remove previous logfile
-			rm "$LOGFILE" &> /dev/null
+			#Write new logfile
 			echo -e "DietPi-Sync Log File.\n$(date +%d-%m-%Y_%H%M)\nSYNC_DRY_RUN=$SYNC_DRY_RUN\n\n" > "$LOGFILE"
 
+			#Services_Stop
+
 			#Sync
-			local rsync_exit_code=0
 			rsync $rync_options --log-file=$LOGFILE --exclude-from="$FP_EXCLUDE_GLOBAL" --include-from="$FP_INCLUDE_GLOBAL" "$FP_SOURCE"/ "$FP_TARGET"/
+
+			#Services_Start
 
 			#Success
 			if (( $? == 0 )); then
@@ -494,14 +546,7 @@
 			#return to main menu
 			TARGETMENUID=0
 
-		#error Folder not found
-		else
-			if (( $INPUT == 0 )); then
-				whiptail --title "Sync failed." --msgbox "Unable to create Target directory $FP_TARGET" --backtitle "$WHIP_BACKTITLE" 10 60
-			fi
 		fi
-
-		#Services_Start
 
 	}
 
@@ -563,16 +608,19 @@
 		echo -e "$FP_TARGET" >> "$FP_DIETPISYNC_SETTINGS"
 		echo -e "$SYNC_DELETE_MODE" >> "$FP_DIETPISYNC_SETTINGS"
 		echo -e "$SYNC_COMPRESSION" >> "$FP_DIETPISYNC_SETTINGS"
+		echo -e "$SYNC_CRONDAILY" >> "$FP_DIETPISYNC_SETTINGS"
 
 	}
 
 	Read_Settings_File(){
 
 		if [ -f "$FP_DIETPISYNC_SETTINGS" ]; then
-			FP_SOURCE=$(sed -n 1p "$FP_DIETPISYNC_SETTINGS")
-			FP_TARGET=$(sed -n 2p "$FP_DIETPISYNC_SETTINGS")
-			SYNC_DELETE_MODE=$(sed -n 3p "$FP_DIETPISYNC_SETTINGS")
-			SYNC_COMPRESSION=$(sed -n 4p "$FP_DIETPISYNC_SETTINGS")
+			local sed_index=1
+			FP_SOURCE=$(sed -n "$sed_index"p "$FP_DIETPISYNC_SETTINGS");((sed_index++))
+			FP_TARGET=$(sed -n "$sed_index"p "$FP_DIETPISYNC_SETTINGS");((sed_index++))
+			SYNC_DELETE_MODE=$(sed -n "$sed_index"p "$FP_DIETPISYNC_SETTINGS");((sed_index++))
+			SYNC_COMPRESSION=$(sed -n "$sed_index"p "$FP_DIETPISYNC_SETTINGS");((sed_index++))
+			SYNC_CRONDAILY=$(sed -n "$sed_index"p "$FP_DIETPISYNC_SETTINGS");((sed_index++))
 		fi
 
 	}
@@ -595,7 +643,7 @@
 
 	#-----------------------------------------------------------------------------
 	#Run menu
-	else
+	elif (( $INPUT == 0 )); then
 
 		while (( $TARGETMENUID > -1 )); do
 
@@ -610,9 +658,14 @@
 				Menu_Set_Sync_Delete_Mode
 			elif (( $TARGETMENUID == 4 )); then
 				Menu_Set_Compression
+			elif (( $TARGETMENUID == 5 )); then
+				Menu_Set_CronDaily
 			fi
 
 		done
+
+		#Save settings
+		Write_Settings_File
 
 	fi
 
@@ -620,9 +673,6 @@
 	#Cleaup left over tmp files
 	rm "$FP_INCLUDE_GLOBAL" &> /dev/null
 	rm "$FP_EXCLUDE_GLOBAL" &> /dev/null
-	#-----------------------------------------------------------------------------------
-	#Save settings
-	Write_Settings_File
 	#-----------------------------------------------------------------------------------
 	exit
 	#-----------------------------------------------------------------------------------
