v103

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -40,7 +40,7 @@
 	DISTRO=$(sed -n 3p /DietPi/dietpi/.hw_model)
 
 	#cpu/core count
-	CPU_CORES_TOTAL=$(nproc)
+	CPU_CORES_TOTAL=$(nproc --all)
 
 	#Overide XU3/4 to 4 cores
 	if (( $HW_MODEL == 11 )); then
@@ -178,6 +178,7 @@
 	PHPIMAGEGALLERY=0
 	AMPACHE=0
 	OPENVPNSERVER=0
+	LETSENCRYPT=0
 
 	#Linux Software
 	INSTALL_LINUX_CHOICESMADE=false
@@ -290,6 +291,8 @@
 		echo -e "PHPIMAGEGALLERY $PHPIMAGEGALLERY" >> "$FILEPATH_INSTALLED_FILE"
 		echo -e "AMPACHE $AMPACHE" >> "$FILEPATH_INSTALLED_FILE"
 		echo -e "OPENVPNSERVER $OPENVPNSERVER" >> "$FILEPATH_INSTALLED_FILE"
+		echo -e "LETSENCRYPT $LETSENCRYPT" >> "$FILEPATH_INSTALLED_FILE"
+
 
 		echo -e "#Additional Linux Software" >> "$FILEPATH_INSTALLED_FILE"
 		echo -e "VIMFULL $VIMFULL" >> "$FILEPATH_INSTALLED_FILE"
@@ -374,6 +377,7 @@
 		PHPIMAGEGALLERY=$(cat "$FILEPATH_INSTALLED_FILE" | grep -m1 'PHPIMAGEGALLERY ' | awk '{print $2}')
 		AMPACHE=$(cat "$FILEPATH_INSTALLED_FILE" | grep -m1 'AMPACHE ' | awk '{print $2}')
 		OPENVPNSERVER=$(cat "$FILEPATH_INSTALLED_FILE" | grep -m1 'OPENVPNSERVER ' | awk '{print $2}')
+		LETSENCRYPT=$(cat "$FILEPATH_INSTALLED_FILE" | grep -m1 'LETSENCRYPT ' | awk '{print $2}')
 
 		#Linux
 		VIMFULL=$(cat "$FILEPATH_INSTALLED_FILE" | grep -m1 'VIMFULL ' | awk '{print $2}')
@@ -1217,7 +1221,7 @@
 				#Pre-reqs
 				AGI libpcre3-dev libssl-dev
 				#Compile and install
-				make -j "$(nproc)" TARGET=linux2628 CPU=generic USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_LINUX_SPLICE=1
+				make -j "$(nproc --all)" TARGET=linux2628 CPU=generic USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_LINUX_SPLICE=1
 				make install
 
 				mkdir /etc/haproxy
@@ -1401,6 +1405,37 @@
 			AGI openvpn easy-rsa iptables
 
 		fi
+
+		#LETSENCRYPT
+		if (( $LETSENCRYPT == 1 )); then
+			INSTALL_DESCRIPTION='Lets Encrypt (SSL cert)'
+			Banner_Installing
+
+			#check source is online
+			INSTALL_URL_ADDRESS='https://github.com/letsencrypt/letsencrypt/archive/master.zip'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+			#Install
+			if (( $? == 0 )); then
+				wget "$INSTALL_URL_ADDRESS" -O package.zip
+				unzip package.zip -d /root
+				rm package.zip
+				mv letsencrypt* /etc/letsencrypt_scripts
+
+				#This is the only way to run the apt-get installs, without running the front end.
+				cd /etc/letsencrypt_scripts
+				./letsencrypt-auto --help
+				cd ~/
+
+			else
+				Info_NoConnection_NoInstall
+
+				#Abort Install, prevent configs being applied
+				LETSENCRYPT=0
+			fi
+
+		fi
+
 
 	}
 
@@ -3077,6 +3112,13 @@ _EOF_
 
 		fi
 
+		#LETSENCRYPT
+		if (( $LETSENCRYPT == 1 )); then
+
+			LETSENCRYPT=2
+
+		fi
+
 	}
 
 	Install_Apply_GPU_Settings(){
@@ -3197,6 +3239,20 @@ _EOF_
 
 		#Update apt (waits for thread completion)
 		/DietPi/dietpi/dietpi-apt-get_update 1
+
+		#Simluated apt installation to check for failures related to apt-cache.
+		echo -e "\nDietPi: Running apt simulation to check for errors, please wait...\n"
+		local package_to_test="bash-doc"
+		apt-get install $package_to_test -s -y &> /dev/null
+		local result=$?
+		if (( $result != 0 )); then
+			#Kill all apt processes
+			killall apt-get &> /dev/null
+			killall dietpi-apt-get_update &> /dev/null
+
+			#Force an apt-get update
+			/DietPi/dietpi/dietpi-apt-get_update 2
+		fi
 
 		#Upgrade Apt
 		Banner_Setup
@@ -4042,6 +4098,15 @@ _EOF_
 			fi
 		fi
 
+		local letsencrypt_w="off"
+		if (( $LETSENCRYPT > 0 )); then
+			letsencrypt_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $LETSENCRYPT == 1 )); then
+				LETSENCRYPT=0
+			fi
+		fi
+
 		#-----------------------------------------------------------------------------
 		WHIP_TITLE='DietPi Optimized Software Selection'
 
@@ -4080,6 +4145,7 @@ _EOF_
 			"LEMP" "Webserver: Nginx   / MySql  / Php." $webserver_lemp_w \
 			"LESP" "Webserver: Nginx   / SQLite / Php." $webserver_lesp_w \
 			"phpMyAdmin" "Optional MySql admin tools." $webserver_phpmyadmin_w \
+			"LetsEncrypt" "Free SSL cert allowing https." $letsencrypt_w \
 			"" "────DNS Servers────────────────────────────" "off" \
 			"Pi-hole" "Block adverts for any device on your network." $pihole_w \
 			"" "────File Servers───────────────────────────" "off" \
@@ -4126,6 +4192,7 @@ _EOF_
 			"LEMP" "Webserver: Nginx   / MySql  / Php." $webserver_lemp_w \
 			"LESP" "Webserver: Nginx   / SQLite / Php." $webserver_lesp_w \
 			"phpMyAdmin" "Optional MySql admin tools." $webserver_phpmyadmin_w \
+			"LetsEncrypt" "Free SSL cert allowing https." $letsencrypt_w \
 			"" "────DNS Servers────────────────────────────" "off" \
 			"Pi-hole" "Block adverts for any device on your network." $pihole_w \
 			"" "────File Servers───────────────────────────" "off" \
@@ -4176,6 +4243,7 @@ _EOF_
 			"LEMP" "Webserver: Nginx   / MySql  / Php." $webserver_lemp_w \
 			"LESP" "Webserver: Nginx   / SQLite / Php." $webserver_lesp_w \
 			"phpMyAdmin" "Optional MySql admin tools." $webserver_phpmyadmin_w \
+			"LetsEncrypt" "Free SSL cert allowing https." $letsencrypt_w \
 			"" "────DNS Servers────────────────────────────" "off" \
 			"Pi-hole" "Block adverts for any device on your network." $pihole_w \
 			"" "────File Servers───────────────────────────" "off" \
@@ -4239,6 +4307,7 @@ _EOF_
 				"LEMP" "Webserver: Nginx   / MySql  / Php." $webserver_lemp_w \
 				"LESP" "Webserver: Nginx   / SQLite / Php." $webserver_lesp_w \
 				"phpMyAdmin" "Optional MySql admin tools." $webserver_phpmyadmin_w \
+				"LetsEncrypt" "Free SSL cert allowing https." $letsencrypt_w \
 				"" "────DNS Servers────────────────────────────" "off" \
 				"Pi-hole" "Block adverts for any device on your network." $pihole_w \
 				"" "────File Servers───────────────────────────" "off" \
@@ -4299,6 +4368,7 @@ _EOF_
 				"LEMP" "Webserver: Nginx   / MySql  / Php." $webserver_lemp_w \
 				"LESP" "Webserver: Nginx   / SQLite / Php." $webserver_lesp_w \
 				"phpMyAdmin" "Optional MySql admin tools." $webserver_phpmyadmin_w \
+				"LetsEncrypt" "Free SSL cert allowing https." $letsencrypt_w \
 				"" "────DNS Servers────────────────────────────" "off" \
 				"Pi-hole" "Block adverts for any device on your network." $pihole_w \
 				"" "────File Servers───────────────────────────" "off" \
@@ -4320,6 +4390,13 @@ _EOF_
 		while read choice
 		do
 			case $choice in
+
+			LetsEncrypt)
+				if (( $LETSENCRYPT == 0 )); then
+					LETSENCRYPT=1
+					INSTALL_DIETPI_CHOICESMADE=true
+				fi
+			;;
 			OpenVPN)
 				if (( $OPENVPNSERVER == 0 )); then
 					OPENVPNSERVER=1
