v74

diff --git a/dietpi/dietpi-config b/dietpi/dietpi-config
--- a/dietpi/dietpi-config
+++ b/dietpi/dietpi-config
@@ -217,8 +217,8 @@
 					HW_OptionNotSupported
 				#Enabled
 				elif [ "$overscan_enabled" = 1 ]; then
-					WHIP_QUESTION=" Current setting: $overscan_text \n Would you like to disable overscan? \n \n If you have black borders on your screen, select Disable."
-					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "Disable" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 12 60
+					WHIP_QUESTION=" Current setting: $overscan_text \n Would you like to disable overscan? \n \n If you have black borders on your screen, select Ok."
+					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 12 60
 					CHOICE=$?
 					if (( $CHOICE == 0 )); then
 						sed -i '/disable_overscan=/c\disable_overscan=1' /DietPi/config.txt
@@ -227,7 +227,7 @@
 				#Disabled
 				elif [ "$overscan_enabled" = 0 ]; then
 					WHIP_QUESTION=" Current setting: $overscan_text \n Would you like to enable overscan?"
-					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "Enable" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 12 60
+					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 12 60
 					CHOICE=$?
 					if (( $CHOICE == 0 )); then
 						sed -i '/disable_overscan=/c\disable_overscan=0' /DietPi/config.txt
@@ -244,7 +244,7 @@
 				#Enabled
 				elif [ "$hdmi_boost_disabled" = 0 ]; then
 					WHIP_QUESTION=" Current setting: $hdmi_boost_text \n Would you like to disable HDMI Signal Boost?"
-					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "Disable" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 12 60
+					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 12 60
 					CHOICE=$?
 					if (( $CHOICE == 0 )); then
 						sed -i '/config_hdmi_boost=/c\#config_hdmi_boost=4' /DietPi/config.txt
@@ -253,7 +253,7 @@
 				#Disabled
 				elif [ "$hdmi_boost_disabled" = 1 ]; then
 					WHIP_QUESTION=" Current setting: $hdmi_boost_text \n Would you like to enable HDMI Signal Boost? \n \n If you have no display output, or, blinking, selecting Enable may resolve it "
-					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "Enable" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 12 60
+					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 12 60
 					CHOICE=$?
 					if (( $CHOICE == 0 )); then
 						sed -i '/config_hdmi_boost=/c\config_hdmi_boost=4' /DietPi/config.txt
@@ -499,7 +499,7 @@
 				#Enabled
 				elif (( $usb_max_current_enabled == 1 )); then
 					WHIP_QUESTION=" Current setting: $usb_max_current_text (1.2AMP) \n Would you like to disable this setting ? \n \n Once Disabled: \n - Max USB current will be set to 0.6AMP (default)"
-					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "Disable" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 12 70
+					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 12 70
 					CHOICE=$?
 					if (( $CHOICE == 0 )); then
 						sed -i '/max_usb_current=/c\max_usb_current=0' /DietPi/config.txt
@@ -508,7 +508,7 @@
 				#Disabled
 				elif (( $usb_max_current_enabled == 0 )); then
 					WHIP_QUESTION=" Current setting: $usb_max_current_text (0.6AMP) \n Would you like to enable this setting ? \n \n Once Enabled: \n - Max USB current will be set to 1.2AMP \n - (Warning) Do not enable this setting, unless you have a 2AMP+ PSU. "
-					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "Enable" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 14 70
+					whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 14 70
 					CHOICE=$?
 					if (( $CHOICE == 0 )); then
 						sed -i '/max_usb_current=/c\max_usb_current=1' /DietPi/config.txt
@@ -684,7 +684,30 @@
 		else
 			WHIP_TITLE='Password Aborted'
 			whiptail --title "$WHIP_TITLE" --msgbox " Password change has been aborted. No changes have been applied" 8 60
-		fi	
+		fi
+		
+		##Whiptail password box always returns exit code 0. No way to obtain if a choice was made.
+		#local passw1=$(whiptail --passwordbox "Please Enter Your New Password" 8 60 --title "Change PW" 3>&1 1>&2 2>&3)
+		#CHOICE=$?
+		#if (( $CHOICE == 0 )); then
+		#
+		#	local passw2=$(whiptail --passwordbox "Please Confirm Your New Password" 8 60 --title "Confirm PW" 3>&1 1>&2 2>&3)
+		#	CHOICE=$?
+		#	if (( $CHOICE == 0 )); then
+		#
+		#		#Password Mismatch
+		#		if [ "$passw1" != "$passw2" ]; then
+		#			WHIP_TITLE='Error - Password Mismatch'
+		#			whiptail --title "$WHIP_TITLE" --msgbox " The Passwords you have entered do not match, therefor, no changes have been applied. Please try again" 8 60
+		#		#Apply Password
+		#		else
+		#			echo -e "$passw1\n$passw1" | passwd -q root
+		#			WHIP_TITLE='Password Applied'
+		#			whiptail --title "$WHIP_TITLE" --msgbox " Your new password has successfully been applied." 8 60
+		#		fi
+		#	fi
+		#fi
+		
 	}
 
 	Change_Hostname(){
@@ -1091,7 +1114,7 @@
 
 	Wifi_Reconnect(){
 		WHIP_QUESTION="SSID: $WIFI_SSID \nKEY: $WIFI_KEY \n\nConnect now? \n\n(NOTICE) All connections will be dropped!"
-		whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --yes-button "Connect" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 14 60
+		whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --backtitle "$WHIP_BACKTITLE" 14 60
 		CHOICE=$?
 		if (( $CHOICE == 0 )); then
 			#Apply Changes
@@ -1103,7 +1126,7 @@
 
 	Ethernet_Reconnect(){
 		WHIP_QUESTION="Do you wish to apply settings and reconnect network now? \n\n(NOTICE) All connections will be dropped!"
-		whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --yes-button "Connect" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 12 60
+		whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --backtitle "$WHIP_BACKTITLE" 12 60
 		CHOICE=$?
 		if (( $CHOICE == 0 )); then
 			#Apply Changes
@@ -1363,7 +1386,7 @@
 				TARGETMENUID=8	
 			#Disabled
 			elif (( $ETH_DISABLED == 1 )); then
-				whiptail --title "Ethernet is Disabled" --yesno " Ethernet must be enabled before settings can be changed. \n \n Would you like to Enable Ethernet now? \n - (NOTICE) All connections will drop! \n - (NOTICE) This will disable Wifi" --defaultno --yes-button "Enable" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 14 60
+				whiptail --title "Ethernet is Disabled" --yesno " Ethernet must be enabled before settings can be changed. \n \n Would you like to Enable Ethernet now? \n - (NOTICE) All connections will drop! \n - (NOTICE) This will disable Wifi" --defaultno --backtitle "$WHIP_BACKTITLE" 14 60
 				CHOICE=$?
 				#Confirm action
 				if (( $CHOICE == 0 )); then
@@ -1390,7 +1413,7 @@
 				TARGETMENUID=8		    
 			#Disabled
 			elif (( $WIFI_DISABLED == 1 )); then
-				whiptail --title "Wifi is Disabled" --yesno " Wifi must be enabled before settings can be changed. \n \n Would you like to Enable Wifi now? \n - (NOTICE) All connections will drop! \n - (NOTICE) This will disable Ethernet" --defaultno --yes-button "Enable" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 14 60
+				whiptail --title "Wifi is Disabled" --yesno " Wifi must be enabled before settings can be changed. \n \n Would you like to Enable Wifi now? \n - (NOTICE) All connections will drop! \n - (NOTICE) This will disable Ethernet" --defaultno --backtitle "$WHIP_BACKTITLE" 14 60
 				CHOICE=$?
 				#Confirm action
 				if (( $CHOICE == 0 )); then
@@ -1420,7 +1443,7 @@
 		  Samba*)
 			#Installed?
 			if (( $sambaclient_installed == 0 )); then
-				whiptail --title "Samba Client Not Installed" --yesno " Samba Client is not installed, would you like to install it now? \n \n - This is required to access Windows Share Files" --defaultno --yes-button "Install" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 12 65
+				whiptail --title "Samba Client Not Installed" --yesno " Samba Client is not installed, would you like to install it now? \n \n - This is required to access Windows Share Files" --defaultno --backtitle "$WHIP_BACKTITLE" 12 65
 				CHOICE=$?
 				if (( $CHOICE == 0 )); then
 					#install smbclient
@@ -1442,7 +1465,7 @@
 		  Ftp*)
 			#Installed?
 			if (( $curlftpfs_installed == 0 )); then
-				whiptail --title "FTP Client Not Installed" --yesno " FTP Client (curlftpfs) is not installed, would you like to install it now? \n \n - This is required to mount an FTP connection to filesystem" --defaultno --yes-button "Install" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 12 65
+				whiptail --title "FTP Client Not Installed" --yesno " FTP Client (curlftpfs) is not installed, would you like to install it now? \n \n - This is required to mount an FTP connection to filesystem" --defaultno --backtitle "$WHIP_BACKTITLE" 12 65
 				CHOICE=$?
 				if (( $CHOICE == 0 )); then
 					#install curlftpfs
@@ -1464,7 +1487,7 @@
 		  NoIp)
 			#Installed?
 			if (( $noip_installed == 0 )); then
-				whiptail --title "NoIp Client Not Installed" --yesno "NoIp Client is not installed, would you like to install it now?\n\n- NoIp will allow you to use a fixed web address, regardless of your internet IP\neg: MySuperDooperWebsite.noip2.biz would point to this device!" --defaultno --yes-button "Install" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 13 70
+				whiptail --title "NoIp Client Not Installed" --yesno "NoIp Client is not installed, would you like to install it now?\n\n- NoIp will allow you to use a fixed web address, regardless of your internet IP\neg: MySuperDooperWebsite.noip2.biz would point to this device!" --defaultno --backtitle "$WHIP_BACKTITLE" 13 70
 				CHOICE=$?
 				if (( $CHOICE == 0 )); then
 					#install noip
@@ -1843,7 +1866,7 @@
 				;;
 			  high)
 				Warning_Overclocking
-				whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "DO IT ANYWAY!" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 14 60
+				whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 14 60
 				CHOICE=$?
 				if (( $CHOICE == 0 )); then
 					Reset_Overclocking
@@ -1856,7 +1879,7 @@
 				;;
 			  extreme)
 				Warning_Overclocking
-				whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "DO IT ANYWAY!" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 14 60
+				whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 14 60
 				CHOICE=$?
 				if (( $CHOICE == 0 )); then
 					Reset_Overclocking
@@ -1887,7 +1910,7 @@
 				;;
 			  low)
 				Warning_Overclocking
-				whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "DO IT ANYWAY!" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 14 60
+				whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 14 60
 				CHOICE=$?
 				if (( $CHOICE == 0 )); then
 					Reset_Overclocking
@@ -1899,7 +1922,7 @@
 				;;
 			  med)
 				Warning_Overclocking
-				whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "DO IT ANYWAY!" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 14 60
+				whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 14 60
 				CHOICE=$?
 				if (( $CHOICE == 0 )); then
 					Reset_Overclocking
@@ -1913,7 +1936,7 @@
 				;;
 			  extreme)
 				Warning_Overclocking
-				whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "DO IT ANYWAY!" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 14 60
+				whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 14 60
 				CHOICE=$?
 				if (( $CHOICE == 0 )); then
 					Reset_Overclocking
@@ -2003,7 +2026,7 @@
 					#Enabled
 					if (( $hq_analogue_audio_enabled == 1 )); then
 						WHIP_QUESTION=" Current setting: $hq_analogue_audio_current_text \n Would you like to disable this setting ? \n \n Once Disabled: \n - No dedicated pll to PWM audio \n - Reduces analogue audio quality \n - Allows core_freq to be set independently from the GPU"
-						whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "Disable" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 14 60
+						whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 14 60
 						CHOICE=$?
 						if (( $CHOICE == 0 )); then
 							sed -i '/avoid_pwm_pll=/c\avoid_pwm_pll=1' /DietPi/config.txt
@@ -2012,7 +2035,7 @@
 					#Disabled
 					elif (( $hq_analogue_audio_enabled == 0 )); then
 						WHIP_QUESTION=" Current setting: $hq_analogue_audio_current_text \n Would you like to enable this setting ? \n \n Once Enabled: \n - Dedicated pll to PWM audio \n - Maximum analogue audio quality \n - Any core_freq overclocking will also effect GPU clock"
-						whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --yes-button "Enable" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 14 60
+						whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 14 60
 						CHOICE=$?
 						if (( $CHOICE == 0 )); then
 							sed -i '/avoid_pwm_pll=/c\avoid_pwm_pll=0' /DietPi/config.txt
