v140
+ Node-Red: https://github.com/Fourdee/DietPi/issues/614
+ Mosquitto: https://github.com/Fourdee/DietPi/issues/614
+ NAA Daemon:  https://github.com/Fourdee/DietPi/issues/641

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -220,7 +220,7 @@ _EOF_
 	# - Software
 	#NB: All software has a unique index that must not be changed (eg: DESKTOP_LXDE = 23)
 	TOTAL_SOFTWARE_INDEXS=0
-	TOTAL_SOFTWARE_INDEXS_HARDLIMIT=122 #Increase as needed. Must be higher than TOTAL_SOFTWARE_INDEXS once calculated in Software_Arrays_Init
+	TOTAL_SOFTWARE_INDEXS_HARDLIMIT=125 #Increase as needed. Must be higher than TOTAL_SOFTWARE_INDEXS once calculated in Software_Arrays_Init
 
 	INSTALLING_INDEX=0					#Which software index is currently being installed?
 
@@ -699,6 +699,32 @@ _EOF_
 			aSOFTWARE_CATEGORY_INDEX[$index_current]=2
 					  aSOFTWARE_TYPE[$index_current]=0
 			 aSOFTWARE_ONLINEDOC_URL[$index_current]='xxxxxxxxxxxxxxxxxxxxxx'
+			 aSOFTWARE_REQUIRES_ALSA[$index_current]=1
+
+		# - Currently ARMv7+ only, so disable all archs
+		for ((i=0; i<=$MAX_HW_ARCH; i++))
+		do
+
+			aSOFTWARE_AVAIL_HW_ARCH[$index_current,$i]=0
+
+		done
+
+		#	renable for armv7+
+		for ((i=2; i<10; i++))
+		do
+
+			aSOFTWARE_AVAIL_HW_ARCH[$index_current,$i]=1
+
+		done
+
+		#------------------
+		index_current=124
+
+				 aSOFTWARE_WHIP_NAME[$index_current]='NAA daemon'
+				 aSOFTWARE_WHIP_DESC[$index_current]='signalyst network audio adaptor (naa)'
+			aSOFTWARE_CATEGORY_INDEX[$index_current]=2
+					  aSOFTWARE_TYPE[$index_current]=0
+			 aSOFTWARE_ONLINEDOC_URL[$index_current]='f=8&t=5&start=90#p4294'
 			 aSOFTWARE_REQUIRES_ALSA[$index_current]=1
 
 		# - Currently ARMv7+ only, so disable all archs
@@ -1208,6 +1234,33 @@ _EOF_
 			aSOFTWARE_AVAIL_HW_MODEL[$index_current,$i]=0
 
 		done
+
+		#------------------
+		index_current=122
+
+				 aSOFTWARE_WHIP_NAME[$index_current]='Node-Red'
+				 aSOFTWARE_WHIP_DESC[$index_current]='tool for wiring devices, APIs and online services'
+			aSOFTWARE_CATEGORY_INDEX[$index_current]=11
+					  aSOFTWARE_TYPE[$index_current]=0
+		   aSOFTWARE_REQUIRES_NODEJS[$index_current]=1
+   aSOFTWARE_REQUIRES_BUILDESSENTIAL[$index_current]=1
+			 aSOFTWARE_ONLINEDOC_URL[$index_current]='f=8&t=5&start=80#p4292'
+
+		# - Disabled for HW_ARCH
+		#aSOFTWARE_AVAIL_HW_ARCH[$index_current,10]=0
+		aSOFTWARE_AVAIL_HW_ARCH[$index_current,21]=0
+
+		#------------------
+		index_current=123
+
+				 aSOFTWARE_WHIP_NAME[$index_current]='Mosquitto '
+				 aSOFTWARE_WHIP_DESC[$index_current]='MQTT messaging broker'
+			aSOFTWARE_CATEGORY_INDEX[$index_current]=11
+					  aSOFTWARE_TYPE[$index_current]=0
+			 aSOFTWARE_ONLINEDOC_URL[$index_current]='f=8&t=5&start=90#p4293'
+
+		# - Disabled for HW_ARCH
+		aSOFTWARE_AVAIL_HW_ARCH[$index_current,10]=0
 
 		#------------------
 
@@ -3781,6 +3834,99 @@ _EOF_
 			Banner_Installing
 
 			/DietPi/dietpi/func/dietpi-set_hardware i2c enable
+
+		fi
+
+		#nodered
+		INSTALLING_INDEX=122
+		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
+
+			Banner_Installing
+
+			AGI python python3
+
+			# - Serialport fails to build unless below flags are provided
+			npm install -g node-red --unsafe-perm
+
+		fi
+
+		#mosquitto
+		INSTALLING_INDEX=123
+		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
+
+			Banner_Installing
+
+			INSTALL_URL_ADDRESS='http://repo.mosquitto.org/debian/mosquitto-jessie.list'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+			if (( $? == 0 )); then
+
+				wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
+				apt-key add mosquitto-repo.gpg.key
+				rm mosquitto-repo.gpg.key
+
+				wget "$INSTALL_URL_ADDRESS" -O /etc/apt/sources.list.d/mosquitto-jessie.list
+
+				apt-get update
+
+				AGI mosquitto
+
+			else
+
+				Error_NoConnection_NoInstall
+
+			fi
+
+		fi
+
+		#NAA Daemon
+		INSTALLING_INDEX=124
+		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
+
+			Banner_Installing
+
+			#Packages requires from Stretch
+			local apackages=(
+
+				'http://ftp.us.debian.org/debian/pool/main/g/gcc-6/gcc-6-base_6.2.1-5_armhf.deb'
+				'http://ftp.us.debian.org/debian/pool/main/g/gcc-6/libstdc++6_6.2.1-5_armhf.deb'
+				'https://www.signalyst.eu/bins/naa/linux/stretch/networkaudiod_3.4.2-33_armhf.deb'
+
+			)
+
+			# - check online
+			for ((i=0; i<${#apackages[@]}; i++))
+			do
+
+				INSTALL_URL_ADDRESS="${apackages[$i]}"
+				/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+				if (( $? != 0 )); then
+
+					Error_NoConnection_NoInstall
+
+					break
+
+				fi
+
+			done
+
+			# - install (Error_NoConnection_NoInstall() sets state to 0)
+			if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
+
+				# - Prereqs
+				AGI libasound2
+
+				for ((i=0; i<${#apackages[@]}; i++))
+				do
+
+					wget "${apackages[$i]}" -O package.deb
+					dpkg -i package.deb
+					rm package.deb
+
+				done
+
+			fi
+
+			unset apackages
 
 		fi
 
@@ -6495,6 +6641,27 @@ _EOF_
 
 		fi
 
+		#NodeRed
+		INSTALLING_INDEX=122
+		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
+
+			mkdir -p "$FP_DIETPI_USERDATA_DIRECTORY"/node-red
+
+			cat << _EOF_ > /etc/systemd/system/node-red.service
+[Unit]
+Description=Node-Red
+
+[Service]
+Type=simple
+User=root
+ExecStart=/usr/local/bin/node-red -u $FP_DIETPI_USERDATA_DIRECTORY/node-red
+
+[Install]
+WantedBy=multi-user.target
+_EOF_
+
+		fi
+
 		#CAVA
 		INSTALLING_INDEX=119
 		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
@@ -8855,6 +9022,19 @@ _EOF_
 
 			rm /etc/systemd/system/roonbridge.service
 			rm -R /etc/roonbridge
+
+		elif (( $1 == 122 )); then
+
+			rm /etc/systemd/system/node-red.service
+
+		elif (( $1 == 123 )); then
+
+			AGP mosquitto
+			rm /etc/apt/sources.list.d/mosquitto-jessie.list
+
+		elif (( $1 == 124 )); then
+
+			AGP networkaudiod
 
 		elif (( $1 == 119 )); then
 
