v118

diff --git a/dietpi/dietpi-config b/dietpi/dietpi-config
--- a/dietpi/dietpi-config
+++ b/dietpi/dietpi-config
@@ -97,6 +97,12 @@
 	WHIP_QUESTION='DietPi-Config'
 	CHOICE=0
 	OPTION=0
+
+	WHIP_SELECTION_PREVIOUS=''
+
+	# - Whiptail sizes
+	WHIP_OPTIONS_MAX_DISPLAY=9
+
 	REBOOT_REQUIRED=0
 
 	#Interger min/max value holders
@@ -185,7 +191,7 @@
 
 			# Reboot Required
 			if(( $REBOOT_REQUIRED == 1 )); then
-				WHIP_TITLE=' Changes Made - Reboot Now? '
+				WHIP_TITLE='Changes Made - Reboot Now?'
 				WHIP_QUESTION=' A reboot is required to apply your new settings.\n Would you like to reboot now?'
 				whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_BACKTITLE" 9 65
 				CHOICE=$?
@@ -1101,7 +1107,7 @@
 						Description+="\nPerformance  | Static. Increases energy consumption, heat, performance."
 					fi
 
-					OPTION=$(whiptail --title "$WHIP_TITLE" --menu "$Description" --cancel-button "$TEXT_MENU_BACK" --backtitle "$WHIP_BACKTITLE" 18 80 5 "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
+					OPTION=$(whiptail --title "$WHIP_TITLE" --menu "$Description" --cancel-button "$TEXT_MENU_BACK" --backtitle "$WHIP_BACKTITLE" --default-item "$current_cpu_governor" 18 80 5 "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
 					CHOICE=$?
 
 					#delete[] array
@@ -1492,6 +1498,7 @@
 	WIFI_BITRATE=0
 	WIFI_SIGNALSTRENGTH=0
 	WIFI_HOTSPOT=0
+	WIFI_COUNTRYCODE="Unknown"
 
 	Network_ETH_CopyCurrentToStatic(){
 
@@ -1768,6 +1775,65 @@
 		fi
 	}
 
+	Change_CountryCode(){
+
+		local wifi_country_code_target=$WIFI_COUNTRYCODE
+
+		#2.4GHZ
+		local whiptail_menu_array=()
+		whiptail_menu_array+=("GB" "Europe / United Kingdom (1-13)")
+		whiptail_menu_array+=("US" "United States           (1-11)")
+		whiptail_menu_array+=("JP" "Japan                   (1-13)")
+		whiptail_menu_array+=("Manual" "Enter a custom country code")
+
+		local description_text="Choose a country to enable WiFi channels allowed in your country."
+
+		WHIP_TITLE='Change WiFi country code'
+
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "$description_text" --cancel-button "$TEXT_MENU_BACK" --backtitle "$WHIP_BACKTITLE" --default-item "$WIFI_COUNTRYCODE" 14 60 4 "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
+		CHOICE=$?
+
+		#delete []
+		unset whiptail_menu_array
+
+		if (( $CHOICE == 0 )); then
+
+			case "$OPTION" in
+				Manual)
+					OPTION=$(whiptail --inputbox "Please enter a 2 character country code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2" 8 60 "$WIFI_COUNTRYCODE" --title "WiFi Country Code" 3>&1 1>&2 2>&3)
+					CHOICE=$?
+					if (( $CHOICE == 0 )); then
+						wifi_country_code_target=$OPTION
+					fi
+				;;
+				*)
+					wifi_country_code_target=$OPTION
+				;;
+			esac
+
+			#Apply
+			iw reg set "$wifi_country_code_target"
+
+			# - Manually update var, else, not updated until Network_GetData() is run.
+			#   "iw reg get" will sometimes return the previous value, even after its been succesfully changed. So add little delay before running "iw reg get".
+			sleep 1
+			WIFI_COUNTRYCODE=$(iw reg get | grep -m1 'country' | awk '{print $2}' | tr -d ':')
+
+			# - Check if country code was successfully applied
+			if [ "$WIFI_COUNTRYCODE" = "$wifi_country_code_target" ]; then
+
+				# - Apply to system configs, for reboots
+				echo -e "REGDOMAIN=$wifi_country_code_target" > /etc/default/crda
+				echo -e "options cfg80211 ieee80211_regdom=$wifi_country_code_target" > /etc/modprobe.d/cfg80211.conf
+
+			else
+				whiptail --title "Error: Country Code" --msgbox "Country code ($wifi_country_code_target) could not been applied. Please check the country code and try again." --backtitle "$WHIP_BACKTITLE" 8 55
+			fi
+
+		fi
+
+	}
+
 	Scan_Wifi(){
 
 		#Get all ssids
@@ -1895,6 +1961,7 @@
 		if [ -f /usr/sbin/hostapd ]; then
 			WIFI_HOTSPOT=1
 		fi
+		WIFI_COUNTRYCODE=$(iw reg get | grep -m1 'country' | awk '{print $2}' | tr -d ':')
 
 		#eth
 		if [ -d /sys/class/net/eth$ETH_INDEX ]; then
@@ -2168,7 +2235,7 @@
 		fi
 
 		WHIP_TITLE='DietPi - Ethernet Network Options'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu " Current Details: \n - Mode    = $mode_current \n - Ip      = $ETH_IP \n - Mask    = $ETH_MASK\n - Gateway = $ETH_GATEWAY\n - DNS     = $ETH_DNS" --cancel-button "$TEXT_MENU_BACK" --backtitle "$WHIP_BACKTITLE" 21 60 8 \
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu " Current Details: \n - Mode    = $mode_current \n - Ip      = $ETH_IP \n - Mask    = $ETH_MASK\n - Gateway = $ETH_GATEWAY\n - DNS     = $ETH_DNS" --cancel-button "$TEXT_MENU_BACK" --default-item "$WHIP_SELECTION_PREVIOUS" --backtitle "$WHIP_BACKTITLE" 21 60 8 \
 		"Change Mode" "$mode_target" \
 		"Copy" "Copy Current address to Static" \
 		"Static Ip" "$ETH_IP_STATIC"  \
@@ -2180,6 +2247,9 @@
 
 		CHOICE=$?
 		if (( $CHOICE == 0 )); then
+
+			WHIP_SELECTION_PREVIOUS=$OPTION
+
 			case "$OPTION" in
 				"Change Mode")
 					((ETH_MODE_TARGET++))
@@ -2256,22 +2326,48 @@
 			mode_target='STATIC'
 		fi
 
+		local whip_options_total=0
+
+		local whiptail_menu_array=()
+		whiptail_menu_array+=("Scan" "Scan and Connect"); ((whip_options_total++))
+		whiptail_menu_array+=("Manual" "Manually Set Wireless Details"); ((whip_options_total++))
+		whiptail_menu_array+=("Change Mode" "$mode_target"); ((whip_options_total++))
+		# - show static options
+		if (( $WIFI_MODE_TARGET == 0 )); then
+			whiptail_menu_array+=("Copy" "Copy Current address to Static"); ((whip_options_total++))
+			whiptail_menu_array+=("Static Ip" "$WIFI_IP_STATIC"); ((whip_options_total++))
+			whiptail_menu_array+=("Static Mask" "$WIFI_MASK_STATIC"); ((whip_options_total++))
+			whiptail_menu_array+=("Static Gateway" "$WIFI_GATEWAY_STATIC"); ((whip_options_total++))
+			whiptail_menu_array+=("Static DNS" "$WIFI_DNS_STATIC"); ((whip_options_total++))
+		fi
+		whiptail_menu_array+=("Country" "$WIFI_COUNTRYCODE"); ((whip_options_total++))
+		whiptail_menu_array+=("Disable" "Disable WiFi adapter"); ((whip_options_total++))
+		whiptail_menu_array+=("Apply" "Save Changes (Restart Networking)"); ((whip_options_total++))
+
+		if (( $whip_options_total > $WHIP_OPTIONS_MAX_DISPLAY )); then
+			whip_options_total=$WHIP_OPTIONS_MAX_DISPLAY
+		fi
+
+		local description_text=" Current Details: \n - SSID    = $WIFI_SSID | $WIFI_BITRATE Mbit | Strength: $WIFI_SIGNALSTRENGTH%\n - KEY     = $WIFI_KEY \n - Mode    = $mode_current \n - Ip      = $WIFI_IP\n - Mask    = $WIFI_MASK\n - DNS     = $WIFI_DNS"
+		local description_line_count=$(( 7 + $(echo -e "$description_text" | wc -l) )) # 7 is the minimal height of whiptail with no data/entries
+
 		WHIP_TITLE='DietPi - Wireless Network Options'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu " Current Details: \n - SSID    = $WIFI_SSID | $WIFI_BITRATE Mbit | Strength: $WIFI_SIGNALSTRENGTH%\n - KEY     = $WIFI_KEY \n - Mode    = $mode_current \n - Ip      = $WIFI_IP\n - Mask    = $WIFI_MASK\n - DNS     = $WIFI_DNS" --cancel-button "$TEXT_MENU_BACK" --backtitle "$WHIP_BACKTITLE" 24 65 10 \
-		"Scan" "Scan and Connect" \
-		"Manual" "Manually Set Wireless Details" \
-		"Change Mode" "$mode_target" \
-		"Copy" "Copy Current address to Static" \
-		"Static Ip" "$WIFI_IP_STATIC"  \
-		"Static Mask" "$WIFI_MASK_STATIC"  \
-		"Static Gateway" "$WIFI_GATEWAY_STATIC"  \
-		"Static DNS" "$WIFI_DNS_STATIC" \
-		"Disable" "Disable WiFi adapter" \
-		"Apply" "Save Changes (Restart Networking)" 3>&1 1>&2 2>&3)
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "$description_text" --cancel-button "$TEXT_MENU_BACK" --backtitle "$WHIP_BACKTITLE" --default-item "$WHIP_SELECTION_PREVIOUS" $(( $description_line_count + $whip_options_total )) 65 $whip_options_total "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
+
+		#delete []
+		unset whiptail_menu_array
 
 		CHOICE=$?
 		if (( $CHOICE == 0 )); then
+
+			WHIP_SELECTION_PREVIOUS=$OPTION
+
 			case "$OPTION" in
+				Country)
+					Change_CountryCode
+					#Return to this Menu
+					TARGETMENUID=10
+				;;
 				Disable)
 					whiptail --title "WiFi is Enabled" --yesno "Would you like to disable the WiFi adapter?\n - (NOTICE) All WiFi connections will be dropped." --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 10 60
 					CHOICE=$?
