v120
+ Fix MC/IPERF installs: https://github.com/Fourdee/DietPi/issues/374
+ Tweaks to user data creation and moving, to support adding drive at
later date: https://github.com/Fourdee/DietPi/issues/377

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -2452,6 +2452,14 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 			GNUEMACS=2
 		fi
 
+		if (( $IPERF == 1 )); then
+			INSTALL_DESCRIPTION='Iperf'
+			Banner_Installing
+			AGI iperf
+
+			IPERF=2
+		fi
+
 		if (( $MIDNIGHTCOMMANDER == 1 )); then
 			INSTALL_DESCRIPTION='Midnight Commander'
 			Banner_Installing
@@ -5099,41 +5107,31 @@ _EOF_
 		setterm -blank 0 -powersave off 2> /dev/null
 
 		#------------------------------------------------------------
-		#Attempt to create user data directory
-		mkdir -p "$DIETPI_USERDATA_DIRECTORY" &> /dev/null
-
-		#Check if we need to setup different userdata directory for the 1st time.
-		local current_userdata_dir=$(/DietPi/dietpi/func/dietpi-move_userdata return_source)
+		#Check if we need to setup different userdata directory for this run.
+		local current_userdata_dir=$(/DietPi/dietpi/func/dietpi-set_userdata return_source)
 		local target_userdata_dir=$DIETPI_USERDATA_DIRECTORY
 
-		# - custom directory
-		dietpi_userdata_basedirectory=$(cat /DietPi/dietpi.txt | grep -m1 'dietpi_userdata_basedirectory=' | sed 's/.*=//' | tr '[:upper:]' '[:lower:]')
-		if [ "$dietpi_userdata_basedirectory" != "auto" ]; then
-
-			target_userdata_dir=$dietpi_userdata_basedirectory
-
 		# - Auto | flash is default value, set to USB drive if available
-		elif (( $USBDRIVE == 2 )); then
+		dietpi_userdata_basedirectory=$(cat /DietPi/dietpi.txt | grep -m1 'dietpi_userdata_basedirectory=' | sed 's/.*=//' | tr '[:upper:]' '[:lower:]')
+		if [ "$dietpi_userdata_basedirectory" = "auto" ]; then
 
-			target_userdata_dir=$DIETPI_USBDRIVE_DIRECTORY
+			if (( $USBDRIVE == 2 )); then
+				target_userdata_dir=$DIETPI_USBDRIVE_DIRECTORY
+			fi
 
+		# - custom directory
+		else
+			target_userdata_dir=$dietpi_userdata_basedirectory
 		fi
 
-		# - Permissions test | Generate a test file inside the target directory, and check it exists.
-		local test_file_name=".testfile_dietpi_userdata_basedirectory"
-		echo 0 > "$target_userdata_dir"/"$test_file_name"
-
-		if [ -f "$target_userdata_dir"/"$test_file_name" ]; then
-			rm "$target_userdata_dir"/"$test_file_name"
-		else
+		# - Setup user directory and move existing userdata if required
+		/DietPi/dietpi/func/dietpi-set_userdata "$current_userdata_dir" "$target_userdata_dir"
+		# - Check for failure
+		if (( $? != 0 )); then
 			Error_Create_UserDataDirectory
 			exit
 		fi
 
-		# - move data?
-		if [ "$current_userdata_dir" != "$target_userdata_dir" ]; then
-			/DietPi/dietpi/func/dietpi-move_userdata "$current_userdata_dir" "$target_userdata_dir"
-		fi
 
 		#------------------------------------------------------------
 		#Set current path to home folder
@@ -5547,7 +5545,7 @@ _EOF_
 
 	Error_Create_UserDataDirectory(){
 
-		ERROR_TEXT="DietPi was unable to create your user data directory ($(cat /DietPi/dietpi.txt | grep -m1 'dietpi_userdata_basedirectory=' | sed 's/.*=//'))\n\nDietPi-Software will now exit. Please contact us on the DietPi forums for support http://dietpi.com/forum"
+		ERROR_TEXT="DietPi was unable to create your user data directory:\n\n $(cat /var/log/dietpi-move_userdata.log)\n\nDietPi-Software will now exit."
 		Error_Display
 	}
 
@@ -5608,7 +5606,7 @@ _EOF_
 		local user_data_mode=$(cat /DietPi/dietpi.txt | grep -m1 '^dietpi_userdata_basedirectory=' | sed 's/.*=//' | tr '[:upper:]' '[:lower:]')
 
 		# - Get current location of userdata
-		local user_data_location_actual=$(/DietPi/dietpi/func/dietpi-move_userdata return_source)
+		local user_data_location_actual=$(/DietPi/dietpi/func/dietpi-set_userdata return_source)
 		local user_data_mode_description='Custom'
 		if [ "$user_data_location_actual" = "$DIETPI_USBDRIVE_DIRECTORY" ]; then
 			user_data_mode_description="USB Drive"
@@ -5760,7 +5758,7 @@ _EOF_
 				WHIP_TITLE='User Data Location'
 
 				# - Vars if we need to move data.
-				local move_data_source=$(/DietPi/dietpi/func/dietpi-move_userdata return_source)
+				local move_data_source=$(/DietPi/dietpi/func/dietpi-set_userdata return_source)
 				local move_data_target=$move_data_source
 				local dietpi_txt_entry='Auto'
 				local custom_location=1 #As we are now replacing Auto when the user selects Force DRIVE, we need to know what is considered a custom location.
@@ -5857,22 +5855,21 @@ _EOF_
 					if [ "$move_data_source" != "$move_data_target" ]; then
 
 						# - Ask before we begin
-						whiptail --title "Data move required" --yesno "DietPi will now attempt to move your data from $move_data_source to $move_data_target\n\nWould you like to begin?" --backtitle "$WHIP_BACKTITLE" --defaultno 12 70
+						whiptail --title "Data move required" --yesno "DietPi will now attempt to move any existing user data from $move_data_source to $move_data_target\n\nWould you like to begin?" --backtitle "$WHIP_BACKTITLE" --defaultno 12 70
 						CHOICE=$?
 						if (( $CHOICE == 0 )); then
 
 							# - Move data, setup symlinks
-							/DietPi/dietpi/func/dietpi-move_userdata "$move_data_source" "$move_data_target"
-
+							/DietPi/dietpi/func/dietpi-set_userdata "$move_data_source" "$move_data_target"
 							# - If sucessful, apply updated user data directory var.
-							if [ "$(/DietPi/dietpi/func/dietpi-move_userdata return_source)" = "$move_data_target" ]; then
+							if (( $? == 0 )); then
 
 								sed -i "/^dietpi_userdata_basedirectory=/c\dietpi_userdata_basedirectory=$dietpi_txt_entry" /DietPi/dietpi.txt
 								whiptail --title "$WHIP_TITLE" --msgbox "Your userdata has been sucessfuly moved from $move_data_source to $move_data_target" 12 70
 
 							else
 
-								whiptail --title "Data move failed:" --msgbox "$(cat /var/log/dietpi-move_userdata.log)\nNo changes have been applied." 10 70
+								whiptail --title "Data move failed:" --msgbox "$(cat /var/log/dietpi-move_userdata.log)\nNo changes have been applied." 12 70
 
 							fi
 
diff --git a/dietpi/func/dietpi-set_userdata b/dietpi/func/dietpi-set_userdata
--- a/dietpi/func/dietpi-set_userdata
+++ b/dietpi/func/dietpi-set_userdata
@@ -9,16 +9,19 @@
 	#////////////////////////////////////
 	#
 	# Info:
+	# - Setups up user data directory.
 	# - Allows automated moving of user data in DietPi. Automatically generates a symlink from /mnt/dietpi_userdata to target directory if needed.
 	# - Also moves the Dphys swapfile to $TARGET_DIRECTORY. Required to prevent locked .swapfile from allow us to delete $SOURCE_DIRECTORY.
 	#
 	# Usage:
-	# - /DietPi/dietpi/func/dietpi-move_userdata return_source							| Return current source directory
-	# - /DietPi/dietpi/func/dietpi-move_userdata sSOURCE_DIRECTORY sTARGET_DIRECTORY	| Move data
+	# - /DietPi/dietpi/func/dietpi-set_userdata return_source						| Return current user data directory
+	# - /DietPi/dietpi/func/dietpi-set_userdata sSOURCE_DIRECTORY sTARGET_DIRECTORY	| Setup user data directory, move data if needed. Returns 1 if failed.
 	#////////////////////////////////////
 
 	#Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
 	LANG=en_GB.UTF-8
+
+	EXIT_CODE=0
 
 	DIETPI_USERDATA_DIRECTORY='/mnt/dietpi_userdata' # Global, must match same var in dietpi-software in dietpi-uninstall. Probably a good idea to never change this.
 
@@ -66,6 +69,7 @@
 			else
 
 				LOGFILE_OUTPUT_TEXT="ERROR: Failed to copy $SOURCE_DIRECTORY/* to $TARGET_DIRECTORY."
+				EXIT_CODE=1
 				break
 
 			fi
@@ -97,7 +101,6 @@
 	# Main Loop
 	#/////////////////////////////////////////////////////////////////////////////////////
 	#init
-
 	# - If there is no directory or symlink for $DIETPI_USERDATA_DIRECTORY, always create a directory.
 	if [ ! -d "$DIETPI_USERDATA_DIRECTORY" ] && [ ! -L "$DIETPI_USERDATA_DIRECTORY" ]; then
 		mkdir -p "$DIETPI_USERDATA_DIRECTORY"
@@ -105,7 +108,7 @@
 
 	#-------------------------------------------------------------------------------------
 	#Returns
-	# - Return current source dir
+	# - Return current userdata dir
 	if [ "$1" = "return_source" ]; then
 
 		echo -e "$(readlink -f $DIETPI_USERDATA_DIRECTORY)"
@@ -123,12 +126,14 @@
 		if [ -z "$SOURCE_DIRECTORY" ] || [ -z "$TARGET_DIRECTORY" ]; then
 
 			LOGFILE_OUTPUT_TEXT="ERROR: Please provide a source and target directory for input."
+			EXIT_CODE=1
 			break
 
 		# - Check if symlink is already pointing to target directory.
 		elif [ "$(readlink -f $DIETPI_USERDATA_DIRECTORY)" = "$TARGET_DIRECTORY" ]; then
 
 			LOGFILE_OUTPUT_TEXT="INFO: $DIETPI_USERDATA_DIRECTORY is already symlinked to target directory."
+			EXIT_CODE=0 #return ok
 			break
 
 
@@ -136,6 +141,7 @@
 		elif [ ! -d "$SOURCE_DIRECTORY" ]; then
 
 			LOGFILE_OUTPUT_TEXT="ERROR: source directory $SOURCE_DIRECTORY does not exist."
+			EXIT_CODE=1
 			break
 
 
@@ -144,24 +150,39 @@
 			$(echo -e "$TARGET_DIRECTORY" | grep -ci -m1 "$SOURCE_DIRECTORY") )); then
 
 			LOGFILE_OUTPUT_TEXT="ERROR: $SOURCE_DIRECTORY and $TARGET_DIRECTORY cannot be within each other. Disallowed directory match."
+			EXIT_CODE=1
 			break
 
 		# - Only allow full filepaths
 		elif [ "${SOURCE_DIRECTORY:0:1}" != "/" ] || [ "${TARGET_DIRECTORY:0:1}" != "/" ]; then
 
-			LOGFILE_OUTPUT_TEXT="ERROR: Both source and target directories must contain the full filepath (eg: /mnt/drive1)"
+			LOGFILE_OUTPUT_TEXT="ERROR: Both source ($SOURCE_DIRECTORY) and target directories ($TARGET_DIRECTORY) must contain the full filepath (eg: /mnt/drive1)"
+			EXIT_CODE=1
 			break
 
-		# - Attempt to create the target directory and test
-		elif [ ! -d "$TARGET_DIRECTORY" ]; then
+		fi
 
-			mkdir -p "$TARGET_DIRECTORY"
+		#Ensure we can create and write to target directory
+		mkdir -p "$TARGET_DIRECTORY" &> /dev/null
+		if [ ! -d "$TARGET_DIRECTORY" ]; then
 
-			if [ ! -d "$TARGET_DIRECTORY" ]; then
+			LOGFILE_OUTPUT_TEXT="ERROR: Unable to create target directory $TARGET_DIRECTORY."
+			EXIT_CODE=1
+			break
 
-				LOGFILE_OUTPUT_TEXT="ERROR: Unable to create target directory $TARGET_DIRECTORY."
+		# - Create a test file inside target directory
+		else
+
+			test_file_name=".testfile_dietpi_userdata_basedirectory"
+
+			echo 0 > "$TARGET_DIRECTORY"/"$test_file_name"
+
+			if [ -f "$TARGET_DIRECTORY"/"$test_file_name" ]; then
+				rm "$TARGET_DIRECTORY"/"$test_file_name"
+			else
+				LOGFILE_OUTPUT_TEXT="ERROR: Unable to create test file in target directory $TARGET_DIRECTORY. Check permissions."
+				EXIT_CODE=1
 				break
-
 			fi
 
 		fi
@@ -178,6 +199,7 @@
 		if (( $FREESPACE_AVAILABLE_TARGET < $FREESPACE_REQUIRED_SOURCE )); then
 
 			LOGFILE_OUTPUT_TEXT="ERROR: Not enough free space in target directory $TARGET_DIRECTORY.\n - Available $FREESPACE_AVAILABLE_TARGET\n - Required $FREESPACE_REQUIRED_SOURCE"
+			EXIT_CODE=1
 			break
 
 		fi
@@ -202,6 +224,6 @@
 
 	fi
 	#-----------------------------------------------------------------------------------
-	exit
+	exit $EXIT_CODE
 	#-----------------------------------------------------------------------------------
 }
