v6.35
+ DietPi-CloudShell | Show more precise error message when Pi-hole FTL connection fails

diff --git a/dietpi/dietpi-cloudshell b/dietpi/dietpi-cloudshell
--- a/dietpi/dietpi-cloudshell
+++ b/dietpi/dietpi-cloudshell
@@ -682,19 +682,19 @@
 		# - https://docs.pi-hole.net/ftldns/telnet-api/
 
 		# Exit if Pi-hole FTL is not running
-		[[ -f '/run/pihole-FTL.port' ]] || return 1
+		[[ -f '/run/pihole-FTL.port' ]] || { first_line="${aCOLOUR[1]}$C_REVERSE Pi-hole not yet started  "; return; }
 
 		# Get FTL port
 		local port=$(</run/pihole-FTL.port)
 
 		# Exit if no valid integer contained
-		(( $port )) || return 2
+		(( $port )) || { first_line="${aCOLOUR[1]}$C_REVERSE Pi-hole has stopped      "; return; }
 
 		# Establish connection / Create file descriptors
      		exec 3<>"/dev/tcp/127.0.0.1/$port"
 
 		# Exit if connection fails
-		>&3 || return 3
+		>&3 || { first_line="${aCOLOUR[1]}$C_REVERSE Pi-hole connection failed"; return; }
 
 		# Ask FTL for last blocked domain and to quit when finished
 		echo '>recentBlocked >quit' >&3
@@ -1019,10 +1019,9 @@
 	# Pi-hole
 	Update_Scene_8(){
 
+		# Update data, replace first output line with error message in case of failure
 		local first_line=" $BANNER_PRINT"
-
-		# Update data, print warning if it fails
-		Obtain_PIHOLE || first_line="${aCOLOUR[1]}$C_REVERSE Updating data failed! ($?)"
+		Obtain_PIHOLE
 
 		# Clear screen
 		clear
