v142
+ Minor var naming: https://github.com/Fourdee/DietPi/issues/685

diff --git a/dietpi/dietpi-backup b/dietpi/dietpi-backup
--- a/dietpi/dietpi-backup
+++ b/dietpi/dietpi-backup
@@ -56,8 +56,8 @@
 	Menu_Main(){
 
 		local backup_last_completed='No previous backup found. Create one.'
-		if [ -f "$FP_TARGET_SYSTEM/$BACKUP_STATS_FILENAME" ]; then
-			backup_last_completed=$(grep '^Backup Completed' "$FP_TARGET_SYSTEM/$BACKUP_STATS_FILENAME" | tail -1 | awk '{print $3}')
+		if [ -f "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME" ]; then
+			backup_last_completed=$(grep '^Backup Completed' "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME" | tail -1 | awk '{print $3}')
 		fi
 
 		local text_include_userdata='Disabled | /mnt/dietpi_userdata NOT included in backups'
@@ -68,7 +68,7 @@
 		fi
 
 		WHIP_TITLE='- DietPi-Backup -'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Current backup and restore location:\n  $FP_TARGET_SYSTEM\n\nMost recent successful backup date:\n  $backup_last_completed" --cancel-button "Exit" --default-item "$MENU_LASTITEM" --backtitle "$WHIP_BACKTITLE" 17 83 5 \
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Current backup and restore location:\n  $FP_TARGET_BACKUP\n\nMost recent successful backup date:\n  $backup_last_completed" --cancel-button "Exit" --default-item "$MENU_LASTITEM" --backtitle "$WHIP_BACKTITLE" 17 83 5 \
 		"Help" "What does DietPi-Backup do?" \
 		"Location" "Change where your backup will be saved and restored from." \
 		"Include user data" ": $text_include_userdata" \
@@ -106,7 +106,7 @@
 				;;
 				Backup)
 					WHIP_TITLE=' Start system backup? '
-					whiptail --title "$WHIP_TITLE" --yesno "Your system will be backed up to:\n$FP_TARGET_SYSTEM\n\nDo you wish to continue?" --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 11 65
+					whiptail --title "$WHIP_TITLE" --yesno "Your system will be backed up to:\n$FP_TARGET_BACKUP\n\nDo you wish to continue?" --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 11 65
 					CHOICE=$?
 					if (( $CHOICE == 0 )); then
 						Run_Backup
@@ -114,7 +114,7 @@
 				;;
 				Restore)
 					WHIP_TITLE=' Start system restore? '
-					whiptail --title "$WHIP_TITLE" --yesno "Your system will be restored from:\n$FP_TARGET_SYSTEM\n\nDo you wish to continue?" --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 11 65
+					whiptail --title "$WHIP_TITLE" --yesno "Your system will be restored from:\n$FP_TARGET_BACKUP\n\nDo you wish to continue?" --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 11 65
 					CHOICE=$?
 					if (( $CHOICE == 0 )); then
 						Run_Restore
@@ -144,12 +144,12 @@
 	#TARGETMENUID=1
 	Menu_Set_Directory(){
 
-		local current_directory="$FP_TARGET_SYSTEM"
+		local current_directory="$FP_TARGET_BACKUP"
 
 		Check_Available_DietPi_Mounts
 
 		WHIP_TITLE='Select your backup and restore location'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Please select the location where your system backup will be saved, and, where it can be restored from.\n\nYour current location:\n$FP_TARGET_SYSTEM" --cancel-button "Back" --backtitle "$WHIP_BACKTITLE" 16 75 4 \
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Please select the location where your system backup will be saved, and, where it can be restored from.\n\nYour current location:\n$FP_TARGET_BACKUP" --cancel-button "Back" --backtitle "$WHIP_BACKTITLE" 16 75 4 \
 		"Search" "Find previous backups in /mnt/*" \
 		"Manual" "Manually type a directory to use." \
 		"USB HDD" "$USB_DRIVE_TEXT" 3>&1 1>&2 2>&3)
@@ -178,7 +178,7 @@
 						OPTION=$(whiptail --title "Backups found." --menu "Please select a previous backup to use:" --cancel-button "Back" --backtitle "$WHIP_BACKTITLE" 12 70 3 "${search_results_whiptail[@]}" 3>&1 1>&2 2>&3)
 						CHOICE=$?
 						if (( $CHOICE == 0 )); then
-							FP_TARGET_SYSTEM="$OPTION"
+							FP_TARGET_BACKUP="$OPTION"
 						fi
 
 						#delete[] array
@@ -194,7 +194,7 @@
 				;;
 				"USB HDD")
 					if (( $USB_DRIVE_AVAILABLE )); then
-						FP_TARGET_SYSTEM="$FP_USB_HDD"
+						FP_TARGET_BACKUP="$FP_USB_HDD"
 					else
 						whiptail --title "No USB HDD Found. Setup Now?" --yesno "$USB_DRIVE_TEXT\n\nWould you like DietPi to setup an external USB drive now?" --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 11 65
 						CHOICE=$?
@@ -214,17 +214,17 @@
 		Check_Supported_Directory_Location
 		# - Not supported, reset directory target to previous
 		if (( $TARGET_DIRECTORY_SUPPORTED == 0 )); then
-			FP_TARGET_SYSTEM="$current_directory"
+			FP_TARGET_BACKUP="$current_directory"
 		fi
 
 	}
 
 	Input_User_Directory(){
 
-		OPTION=$(whiptail --inputbox "Please enter the filepath to your directory. \neg: /mnt/dietpi-backup\n - Must be located inside /mnt/* \n - Must be symlink compatible filesystem (ext2/3/4)" 10 70 "$FP_TARGET_SYSTEM" --title "Manual backup directory" --backtitle "$WHIP_BACKTITLE" 3>&1 1>&2 2>&3)
+		OPTION=$(whiptail --inputbox "Please enter the filepath to your directory. \neg: /mnt/dietpi-backup\n - Must be located inside /mnt/* \n - Must be symlink compatible filesystem (ext2/3/4)" 10 70 "$FP_TARGET_BACKUP" --title "Manual backup directory" --backtitle "$WHIP_BACKTITLE" 3>&1 1>&2 2>&3)
 		CHOICE=$?
 		if (( $CHOICE == 0 )); then
-			FP_TARGET_SYSTEM="$OPTION"
+			FP_TARGET_BACKUP="$OPTION"
 		fi
 
 	}
@@ -234,30 +234,30 @@
 	#/////////////////////////////////////////////////////////////////////////////////////
 	Error_Filesystem_Not_Supported(){
 
-		/DietPi/dietpi/func/dietpi-notify 1 "Filesystem not supported in $FP_TARGET_SYSTEM"
+		/DietPi/dietpi/func/dietpi-notify 1 "Filesystem not supported in $FP_TARGET_BACKUP"
 
 		if (( $INPUT == 0 )); then
-			whiptail --title "Error" --msgbox "$FP_TARGET_SYSTEM Has a filesystem of: $TARGET_FILESYSTEM_TYPE, and is not supported.\n\nThe filesystem must be EXT2/3/4 for symlink compatibility." --backtitle "$WHIP_BACKTITLE" 11 70
+			whiptail --title "Error" --msgbox "$FP_TARGET_BACKUP Has a filesystem of: $TARGET_FILESYSTEM_TYPE, and is not supported.\n\nThe filesystem must be EXT2/3/4 for symlink compatibility." --backtitle "$WHIP_BACKTITLE" 11 70
 		fi
 
 	}
 
 	Error_Not_Mnt_Directory(){
 
-		/DietPi/dietpi/func/dietpi-notify 1 "Target directory is not inside /mnt ($FP_TARGET_SYSTEM)"
+		/DietPi/dietpi/func/dietpi-notify 1 "Target directory is not inside /mnt ($FP_TARGET_BACKUP)"
 
 		if (( $INPUT == 0 )); then
-			whiptail --title "Directory not supported" --msgbox "$FP_TARGET_SYSTEM\n\nYour current location is not supported.\nThe location must be inside the /mnt/* directory.\n - eg: /mnt/dietpi-backup" --backtitle "$WHIP_BACKTITLE" 11 70
+			whiptail --title "Directory not supported" --msgbox "$FP_TARGET_BACKUP\n\nYour current location is not supported.\nThe location must be inside the /mnt/* directory.\n - eg: /mnt/dietpi-backup" --backtitle "$WHIP_BACKTITLE" 11 70
 		fi
 
 	}
 
 	Error_DietpiUserdata_Directory(){
 
-		/DietPi/dietpi/func/dietpi-notify 1 "Target directory can not be contained within DietPi user data location ($FP_TARGET_SYSTEM)"
+		/DietPi/dietpi/func/dietpi-notify 1 "Target directory can not be contained within DietPi user data location ($FP_TARGET_BACKUP)"
 
 		if (( $INPUT == 0 )); then
-			whiptail --title "Directory not supported" --msgbox "$FP_TARGET_SYSTEM\n\nYour current location is not supported.\nTarget directory can not be contained within DietPi user data location (/mnt/dietpi_userdata)" --backtitle "$WHIP_BACKTITLE" 13 70
+			whiptail --title "Directory not supported" --msgbox "$FP_TARGET_BACKUP\n\nYour current location is not supported.\nTarget directory can not be contained within DietPi user data location (/mnt/dietpi_userdata)" --backtitle "$WHIP_BACKTITLE" 13 70
 		fi
 
 	}
@@ -266,7 +266,7 @@
 
 		/DietPi/dietpi/func/dietpi-notify 1 "Another Rsync process is already running."
 
-		echo -e "$RSYNC_MODE_TEXT failed: $(date +"%d-%m-%Y_%H%M"). Rsync is already running." >> "$FP_TARGET_SYSTEM/$BACKUP_STATS_FILENAME"
+		echo -e "$RSYNC_MODE_TEXT failed: $(date +"%d-%m-%Y_%H%M"). Rsync is already running." >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
 		#Menu
 		if (( $INPUT == 0 )); then
 			whiptail --title "$RSYNC_MODE_TEXT Error" --msgbox "A $RSYNC_MODE_TEXT could not be started as rsync is already running." --backtitle "$WHIP_BACKTITLE" 13 60
@@ -278,7 +278,7 @@
 
 		/DietPi/dietpi/func/dietpi-notify 1 "$RSYNC_MODE_TEXT failed."
 
-		echo -e "$RSYNC_MODE_TEXT Failed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET_SYSTEM/$BACKUP_STATS_FILENAME"
+		echo -e "$RSYNC_MODE_TEXT Failed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
 		#Menu
 		if (( $INPUT == 0 )); then
 			whiptail --title "$RSYNC_MODE_TEXT failed" --msgbox "Your $RSYNC_MODE_TEXT has failed. Please see the Log file for more information:\n\n$LOGFILE" --backtitle "$WHIP_BACKTITLE" 12 60
@@ -296,7 +296,7 @@
 
 	#Backup Filepaths
 	FP_SOURCE_SYSTEM="/"
-	FP_TARGET_SYSTEM="/mnt/dietpi-backup"
+	FP_TARGET_BACKUP="/mnt/dietpi-backup"
 	FP_SOURCE_USERDATA_GLOBAL="/mnt/dietpi_userdata"
 	FP_SOURCE_USERDATA_ACTUAL="$(readlink /mnt/dietpi_userdata)"
 	if [ -z "$FP_SOURCE_USERDATA_ACTUAL" ]; then
@@ -307,7 +307,7 @@
 
 	FP_USB_HDD="/mnt/usb_1/dietpi-backup"
 
-	#file applied to successful backups (stored in "$FP_TARGET_SYSTEM/$BACKUP_STATS_FILENAME"
+	#file applied to successful backups (stored in "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
 	BACKUP_STATS_FILENAME=".dietpi-backup_stats"
 
 	#Exclude/include file
@@ -360,7 +360,7 @@ _EOF_
 
 #EXCLUDE
 #Global - Folders
-- $FP_TARGET_SYSTEM/
+- $FP_TARGET_BACKUP/
 - /mnt/
 - /media/
 - /dev/
@@ -428,13 +428,13 @@ _EOF_
 		if (( $TARGET_DIRECTORY_SUPPORTED == 1 )); then
 
 			#Generate target dir.
-			mkdir -p "$FP_TARGET_SYSTEM"
+			mkdir -p "$FP_TARGET_BACKUP"
 
 			#Error: Unable to create target folder.
-			if [ ! -d "$FP_TARGET_SYSTEM" ]; then
+			if [ ! -d "$FP_TARGET_BACKUP" ]; then
 
 				if (( $INPUT == 0 )); then
-					whiptail --title "$RSYNC_MODE_TEXT failed." --msgbox "Unable to create $FP_TARGET_SYSTEM" --backtitle "$WHIP_BACKTITLE" 10 60
+					whiptail --title "$RSYNC_MODE_TEXT failed." --msgbox "Unable to create $FP_TARGET_BACKUP" --backtitle "$WHIP_BACKTITLE" 10 60
 				fi
 
 			#Error: Rsync is already running
@@ -453,14 +453,14 @@ _EOF_
 
 				Services_Stop
 
-				/DietPi/dietpi/func/dietpi-notify 2 "Backing up to: $FP_TARGET_SYSTEM"
+				/DietPi/dietpi/func/dietpi-notify 2 "Backing up to: $FP_TARGET_BACKUP"
 
-				rsync $RSYNC_RUN_OPTIONS_SYSTEM_BACKUP "$FP_SOURCE_SYSTEM" "$FP_TARGET_SYSTEM"/dietpi-backup_system/
+				rsync $RSYNC_RUN_OPTIONS_SYSTEM_BACKUP "$FP_SOURCE_SYSTEM" "$FP_TARGET_BACKUP"/dietpi-backup_system/
 
 				# - userdata?
 				if (( $INCLUDE_DIETPI_USERDATA_DIR )); then
 
-					rsync $RSYNC_RUN_OPTIONS_USERDATA_BACKUP "$FP_SOURCE_USERDATA_ACTUAL"/ "$FP_TARGET_SYSTEM"/dietpi-backup_userdata/
+					rsync $RSYNC_RUN_OPTIONS_USERDATA_BACKUP "$FP_SOURCE_USERDATA_ACTUAL"/ "$FP_TARGET_BACKUP"/dietpi-backup_userdata/
 
 				fi
 
@@ -469,10 +469,10 @@ _EOF_
 				#Success
 				if (( $? == 0 )); then
 					/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
-					echo -e "$RSYNC_MODE_TEXT Completed: $(date +"%d-%m-%Y_%H:%M")" >> "$FP_TARGET_SYSTEM/$BACKUP_STATS_FILENAME"
+					echo -e "$RSYNC_MODE_TEXT Completed: $(date +"%d-%m-%Y_%H:%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
 					#Menu
 					if (( $INPUT == 0 )); then
-						whiptail --title "$RSYNC_MODE_TEXT completed" --msgbox "Your $RSYNC_MODE_TEXT was saved to:\n$FP_TARGET_SYSTEM\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 11 60
+						whiptail --title "$RSYNC_MODE_TEXT completed" --msgbox "Your $RSYNC_MODE_TEXT was saved to:\n$FP_TARGET_BACKUP\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 11 60
 					fi
 
 				#Failed
@@ -501,12 +501,12 @@ _EOF_
 		if (( $TARGET_DIRECTORY_SUPPORTED == 1 )); then
 
 			#Error: Backup not found
-			if [ ! -f "$FP_TARGET_SYSTEM/$BACKUP_STATS_FILENAME" ]; then
+			if [ ! -f "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME" ]; then
 
-				/DietPi/dietpi/func/dietpi-notify 2 "No Backup was found in $FP_TARGET_SYSTEM"
+				/DietPi/dietpi/func/dietpi-notify 2 "No Backup was found in $FP_TARGET_BACKUP"
 				/DietPi/dietpi/func/dietpi-notify 1 "$RSYNC_MODE_TEXT Failed.\n"
 				if (( $INPUT == 0 )); then
-					whiptail --title "$RSYNC_MODE_TEXT failed." --msgbox "$FP_TARGET_SYSTEM/$BACKUP_STATS_FILENAME does not exist\n\nHave you created a backup?" --backtitle "$WHIP_BACKTITLE" 11 70
+					whiptail --title "$RSYNC_MODE_TEXT failed." --msgbox "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME does not exist\n\nHave you created a backup?" --backtitle "$WHIP_BACKTITLE" 11 70
 				fi
 
 			#Error: Rsync is already running
@@ -522,14 +522,14 @@ _EOF_
 
 				Services_Stop
 
-				/DietPi/dietpi/func/dietpi-notify 2 "Restoring from: $FP_TARGET_SYSTEM"
+				/DietPi/dietpi/func/dietpi-notify 2 "Restoring from: $FP_TARGET_BACKUP"
 
-				rsync $RSYNC_RUN_OPTIONS_SYSTEM_BACKUP "$FP_TARGET_SYSTEM"/dietpi-backup_system/ "$FP_SOURCE_SYSTEM"
+				rsync $RSYNC_RUN_OPTIONS_SYSTEM_BACKUP "$FP_TARGET_BACKUP"/dietpi-backup_system/ "$FP_SOURCE_SYSTEM"
 
 				# - userdata?
 				if (( $INCLUDE_DIETPI_USERDATA_DIR )); then
 
-					rsync $RSYNC_RUN_OPTIONS_USERDATA_BACKUP "$FP_TARGET_SYSTEM"/dietpi-backup_userdata/ "$FP_SOURCE_USERDATA_ACTUAL"/
+					rsync $RSYNC_RUN_OPTIONS_USERDATA_BACKUP "$FP_TARGET_BACKUP"/dietpi-backup_userdata/ "$FP_SOURCE_USERDATA_ACTUAL"/
 
 				fi
 
@@ -538,10 +538,10 @@ _EOF_
 				#Success
 				if (( $? == 0 )); then
 					/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
-					echo -e "$RSYNC_MODE_TEXT Completed: $(date +"%d-%m-%Y_%H:%M")" >> "$FP_TARGET_SYSTEM/$BACKUP_STATS_FILENAME"
+					echo -e "$RSYNC_MODE_TEXT Completed: $(date +"%d-%m-%Y_%H:%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
 					#Menu
 					if (( $INPUT == 0 )); then
-						whiptail --title "$RSYNC_MODE_TEXT completed" --msgbox "Your system has been restored from:\n$FP_TARGET_SYSTEM.\n\nA reboot is highly recommended." --backtitle "$WHIP_BACKTITLE" 11 60
+						whiptail --title "$RSYNC_MODE_TEXT completed" --msgbox "Your system has been restored from:\n$FP_TARGET_BACKUP.\n\nA reboot is highly recommended." --backtitle "$WHIP_BACKTITLE" 11 60
 					fi
 
 				#Failed
@@ -594,21 +594,21 @@ _EOF_
 		TARGET_DIRECTORY_SUPPORTED=0
 
 		#Disallow dietpi_userdata location, due to includes in that location
-		if [[ "$FP_TARGET_SYSTEM" == "$FP_SOURCE_USERDATA_GLOBAL"* ]] || [[ "$FP_TARGET_SYSTEM" == "$FP_SOURCE_USERDATA_ACTUAL"* ]] ; then
+		if [[ "$FP_TARGET_BACKUP" == "$FP_SOURCE_USERDATA_GLOBAL"* ]] || [[ "$FP_TARGET_BACKUP" == "$FP_SOURCE_USERDATA_ACTUAL"* ]] ; then
 
 			Error_DietpiUserdata_Directory
 
 		#Check location contains /mnt/
-		elif [[ "$FP_TARGET_SYSTEM" == "/mnt/"* ]]; then
+		elif [[ "$FP_TARGET_BACKUP" == "/mnt/"* ]]; then
 
 			#Generate the target directory if it doesnt exist. So we can check what filesystem it will be.
 			local directory_generated=0
-			if [ ! -d "$FP_TARGET_SYSTEM" ]; then
-				mkdir -p "$FP_TARGET_SYSTEM"
+			if [ ! -d "$FP_TARGET_BACKUP" ]; then
+				mkdir -p "$FP_TARGET_BACKUP"
 				directory_generated=1
 			fi
 
-			TARGET_FILESYSTEM_TYPE="$( df -T $FP_TARGET_SYSTEM | sed -n '2p' | awk '{print $2}')"
+			TARGET_FILESYSTEM_TYPE="$( df -T $FP_TARGET_BACKUP | sed -n '2p' | awk '{print $2}')"
 			for ((i=0; i<${#aSUPPORTED_FILESYSTEMS[@]}; i++))
 			do
 				if [ "$TARGET_FILESYSTEM_TYPE" = "${aSUPPORTED_FILESYSTEMS[$i]}" ]; then
@@ -619,7 +619,7 @@ _EOF_
 
 			#Delete directory if tested
 			if (( $directory_generated == 1 )); then
-				rm -R "$FP_TARGET_SYSTEM"
+				rm -R "$FP_TARGET_BACKUP"
 			fi
 
 			#Not ext2/3/4
@@ -643,7 +643,7 @@ _EOF_
 	Write_Settings_File(){
 
 		cat << _EOF_ > "$FP_DIETPIBACKUP_SETTINGS"
-FP_TARGET_SYSTEM=$FP_TARGET_SYSTEM
+FP_TARGET_BACKUP=$FP_TARGET_BACKUP
 INCLUDE_DIETPI_USERDATA_DIR=$INCLUDE_DIETPI_USERDATA_DIR
 _EOF_
 
@@ -671,7 +671,7 @@ _EOF_
 
 	# $2 Optional directory input.
 	if [ "$2" != "" ]; then
-		FP_TARGET_SYSTEM=$2
+		FP_TARGET_BACKUP=$2
 	fi
 
 	#-----------------------------------------------------------------------------
