v6.20
+ DietPi-Sync | Resolve doubled dry-run setting, quirk due to separate dry-run option and free space check dry-run

diff --git a/dietpi/dietpi-sync b/dietpi/dietpi-sync
--- a/dietpi/dietpi-sync
+++ b/dietpi/dietpi-sync
@@ -141,9 +141,6 @@ _EOF_
 			# - Compression?
 			(( $SYNC_COMPRESSION )) && rync_options+='z'
 
-			# - Dry Run?
-			(( $SYNC_DRY_RUN )) && rync_options+='n'
-
 			# - Delete mode?
 			(( $SYNC_DELETE_MODE )) && rync_options+=' --delete'
 
@@ -154,6 +151,7 @@ _EOF_
 			local old_backup_size=$(du -ks "$FP_TARGET" | awk '{print $1}')
 
 			rsync --dry-run --stats $rync_options "$FP_SOURCE"/ "$FP_TARGET"/ > /tmp/dietpi-sync_result
+			EXIT_CODE=$?
 			local new_backup_size=$(( $(grep -m1 'Total file size' /tmp/dietpi-sync_result | sed 's/[^0-9]*//g') / 1024 ))
 			local total_file_count=$(( $(grep -m1 'Number of files' /tmp/dietpi-sync_result | awk '{print $6}' | sed 's/[^0-9]*//g') ))
 			local total_folder_count=$(( $(grep -m1 'Number of files' /tmp/dietpi-sync_result | awk '{print $8}' | sed 's/[^0-9]*//g') ))
@@ -169,28 +167,33 @@ _EOF_
 				G_WHIP_YESNO 'The system sync target location appears to have insufficient free space to successfully finish the backup.\nHowever, this check is a rough estimation in reasonable time, thus it could be marginally incorrect.\n\nWould you like to override this warning and continue with the backup?'
 				if (( $? )); then
 
-					echo -e "$(date +"%d-%m-%Y_%H%M") [FAILED] Insufficient free space" >> "$FP_TARGET/$SYNC_STATS_FILENAME"
+					echo "$(date +"%d-%m-%Y_%H%M") [FAILED] Insufficient free space" >> "$FP_TARGET/$SYNC_STATS_FILENAME"
 					break
 
 				fi
 
 			fi
 
-			G_DIETPI-NOTIFY 2 "Sync | $FP_SOURCE > $FP_TARGET: in progress, please wait..."
+			if (( ! $SYNC_DRY_RUN )); then
 
-			#Sync
-			rsync $rync_options "$FP_SOURCE"/ "$FP_TARGET"/
-			EXIT_CODE=$?
+				G_DIETPI-NOTIFY 2 "Sync | $FP_SOURCE > $FP_TARGET: in progress, please wait..."
+
+				rsync $rync_options "$FP_SOURCE"/ "$FP_TARGET"/
+				EXIT_CODE=$?
+
+			fi
+
 			G_DIETPI-NOTIFY -1 $EXIT_CODE "$G_PROGRAM_NAME"
 			if (( $EXIT_CODE == 0 )); then
 
-				echo -e "$(date +"%d-%m-%Y_%H%M") [  OK  ] Sync completed" >> "$FP_TARGET/$SYNC_STATS_FILENAME"
 				if (( ! $SYNC_DRY_RUN )); then
 
+					echo -e "$(date +"%d-%m-%Y_%H%M") [  OK  ] Sync completed" >> "$FP_TARGET/$SYNC_STATS_FILENAME"
 					G_WHIP_MSG "[  OK  ] Sync completed:\n - $FP_SOURCE > $FP_TARGET"
 
 				else
 
+					echo -e "$(date +"%d-%m-%Y_%H%M") [  OK  ] Dry run completed" >> "$FP_TARGET/$SYNC_STATS_FILENAME"
 					G_WHIP_MSG "[  OK  ] Dry Run Sync completed (NO modifications):\n - $FP_SOURCE > $FP_TARGET"
 
 				fi
@@ -568,13 +571,13 @@ _EOF_
 		if (( $TARGETMENUID == 1 )); then
 
 			G_WHIP_DEFAULT_ITEM="$FP_TARGET"
-			G_WHIP_INPUTBOX 'Please enter a new filepath for the Target directory.\neg: /mnt/target' && FP_TARGET="$G_WHIP_RETURNED_VALUE"
+			G_WHIP_INPUTBOX 'Please enter a new filepath for the Target directory.\neg: /mnt/target' && FP_TARGET="${G_WHIP_RETURNED_VALUE%/}"
 
 		#Source
 		elif (( $TARGETMENUID == 2 )); then
 
 			G_WHIP_DEFAULT_ITEM="$FP_SOURCE"
-			G_WHIP_INPUTBOX 'Please enter a new filepath for the Source directory.\neg: /mnt/source' && FP_SOURCE="$G_WHIP_RETURNED_VALUE"
+			G_WHIP_INPUTBOX 'Please enter a new filepath for the Source directory.\neg: /mnt/source' && FP_SOURCE="${G_WHIP_RETURNED_VALUE%/}"
 
 		fi
 
