v118
Add missing code/changes which got cleared from recent commits

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -285,7 +285,7 @@ RPIMONITOR=${RPIMONITOR:=0}
 NETDATA=${NETDATA:=0}
 BAIKAL=${BAIKAL:=0}
 MUMBLESERVER=${MUMBLESERVER:=0}
-
+EMBYSERVER=${EMBYSERVER:=0}
 
 #Additional Linux Software
 VIMFULL=${VIMFULL:=0}
@@ -407,7 +407,7 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 		fi
 
 		# - Installs that require a MySQL stack:  WEBSERVER_L?[MA]P
-		if (( $OWNCLOUD || $PHPBB || $WORDPRESS || $AMPACHE || $PYDIO || $EMONCMS || $BAIKAL )); then
+		if (( $OWNCLOUD || $PHPBB || $WORDPRESS || $AMPACHE || $PYDIO || $EMONCMS || $BAIKAL || $WEBSERVER_MYADMINPHP )); then
 
 			# - Check for existing installations
 			if (( ! $WEBSERVER_LAMP && ! $WEBSERVER_LAAP && \
@@ -1853,6 +1853,55 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 
 		fi
 
+		#EMBYSERVER
+		if (( $EMBYSERVER == 1 )); then
+			INSTALL_DESCRIPTION='Emby Server'
+			Banner_Installing
+
+			local url_tests=0
+
+			#check is online
+			INSTALL_URL_ADDRESS='http://download.opensuse.org/repositories/home:/emby/Debian_8.0'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+			if (( $? == 0 )); then
+
+				INSTALL_URL_ADDRESS='http://download.mono-project.com/repo/debian'
+				/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+				if (( $? == 0 )); then
+
+					url_tests=1
+
+				fi
+
+			fi
+
+			#install
+			if (( $url_tests == 1 )); then
+
+				# - Alternative mono repo: https://github.com/Fourdee/DietPi/issues/310#issuecomment-216247879
+				apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
+				echo -e "deb http://download.mono-project.com/repo/debian wheezy main" > /etc/apt/sources.list.d/mono-xamarin.list
+				echo -e "deb http://download.mono-project.com/repo/debian wheezy-libjpeg62-compat main" >> /etc/apt/sources.list.d/mono-xamarin.list
+
+
+				# - Emby repo
+				wget http://download.opensuse.org/repositories/home:emby/Debian_8.0/Release.key
+				apt-key add - < Release.key
+				echo -e "deb http://download.opensuse.org/repositories/home:/emby/Debian_8.0/ /" > /etc/apt/sources.list.d/emby-server.list
+				apt-get update
+
+				AGI emby-server
+
+			else
+				Error_NoConnection_NoInstall
+
+				#Abort failed install
+				EMBYSERVER=0
+			fi
+
+		fi
 
 	}
 
@@ -3968,7 +4017,10 @@ _EOF_
 			#RPi 3 - WiFi hotspot. Internal Wifi fix.
 			# - Disable driver definition
 			if (( $HW_MODEL == 3 )); then
-				sed -i '/driver=/c\#driver=rtl871xdrv' /etc/hostapd/hostapd.conf
+				sed -i '/driver=/c\#driver=none' /etc/hostapd/hostapd.conf
+
+				# - Add Wireless N support
+				echo -e "ieee80211n=1" >> /etc/hostapd/hostapd.conf
 			fi
 
 
@@ -4299,6 +4351,13 @@ _EOF_
 			sed -i '/logdays=/c\logdays=-1' /etc/mumble-server.ini
 
 			MUMBLESERVER=2
+
+		fi
+
+		#EMBYSERVER
+		if (( $EMBYSERVER == 1 )); then
+
+			EMBYSERVER=2
 
 		fi
 
@@ -5842,6 +5901,16 @@ _EOF_
 			fi
 		fi
 
+		#EMBYSERVER
+		local embyserver_w="off"
+		if (( $EMBYSERVER > 0 )); then
+			embyserver_w="on"
+			#Reset to 0.  Menu checklists will apply back to 1
+			if (( $EMBYSERVER == 1 )); then
+				EMBYSERVER=0
+			fi
+		fi
+
 		#-----------------------------------------------------------------------------
 		WHIP_TITLE='DietPi Optimized Software Selection'
 
@@ -5916,6 +5985,7 @@ _EOF_
 			"SubSonic" "Web interface media streaming server." $subsonic_w \
 			"Ampache" "Web interface media streaming server." $ampache_w \
 			"Murmur" "Mumble VoIP server." $mumbleserver_w \
+			"Emby Server" "Web interface media streaming server." $embyserver_w \
 			"" "────BitTorrent─────────────────────────────" "off" \
 			"Transmission" "BitTorrent server with web interface." $transmission_w \
 			"Deluge" "BitTorrent server with web interface." $deluge_w \
@@ -5972,6 +6042,7 @@ _EOF_
 			"Ampache" "Web interface media streaming server." $ampache_w \
 			"Shairport Sync" "AirPlay audio player with multiroom sync" $shairportsync_w \
 			"Murmur" "Mumble VoIP server." $mumbleserver_w \
+			"Emby Server" "Web interface media streaming server." $embyserver_w \
 			"" "────BitTorrent──────────────────────────────" "off" \
 			"Transmission" "BitTorrent server with web interface." $transmission_w \
 			"Deluge" "BitTorrent server with web interface." $deluge_w \
@@ -6042,6 +6113,7 @@ _EOF_
 				"Shairport Sync" "AirPlay audio player with multiroom sync" $shairportsync_w \
 				"BruteFIR" "EQ and Digital Room Correction via ALSA." $brutefir_w \
 				"Murmur" "Mumble VoIP server." $mumbleserver_w \
+				"Emby Server" "Web interface media streaming server." $embyserver_w \
 				"" "────BitTorrent──────────────────────────────" "off" \
 				"Transmission" "BitTorrent server with web interface." $transmission_w \
 				"Deluge" "BitTorrent server with web interface." $deluge_w \
@@ -6180,88 +6252,94 @@ _EOF_
 		do
 			case $choice in
 
+			"Emby Server")
+				if (( $EMBYSERVER == 0 )); then
+					EMBYSERVER=1
+					INSTALL_DIETPI_CHOICESMADE=true
+				fi
+			;;
 			Murmur)
 				if (( $MUMBLESERVER == 0 )); then
 					MUMBLESERVER=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			"Tor Hotspot")
 				if (( $TORHOTSPOT == 0 )); then
 					TORHOTSPOT=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			BaiKal)
 				if (( $BAIKAL == 0 )); then
 					BAIKAL=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			"RPi-Monitor")
 				if (( $RPIMONITOR == 0 )); then
 					RPIMONITOR=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			EmonHUB|EmonPi)
 				if (( $EMONHUB == 0 )); then
 					EMONHUB=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			EmonCMS)
 				if (( $EMONCMS == 0 )); then
 					EMONCMS=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			Redis)
 				if (( $WEBSERVER_REDIS == 0 )); then
 					WEBSERVER_REDIS=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			SqueezeLite)
 				if (( $SQUEEZELITE == 0 )); then
 					SQUEEZELITE=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			Pydio)
 				if (( $PYDIO == 0 )); then
 					PYDIO=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			BruteFIR)
 				if (( $BRUTEFIR == 0 )); then
 					BRUTEFIR=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			"Shairport Sync")
 				if (( $SHAIRPORTSYNC == 0 )); then
 					SHAIRPORTSYNC=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			"WiFi Hotspot")
 				if (( $WIFIHOTSPOT == 0 )); then
 					WIFIHOTSPOT=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			RPi.GPIO)
 				if (( $RPIGPIO == 0 )); then
 					RPIGPIO=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			I2c)
 				if (( $RPII2C == 0 )); then
 					RPII2C=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			WiringPi)
@@ -6974,7 +7052,7 @@ _EOF_
 		"Emacs" "GNU Emacs editor." $gnuemacs_w \
 		"Jed" "Editor for programmers." $jed_w \
 		"Vim" "Vi Enhanced Text Editor." $vimfull_w \
-                "Vim-Tiny" "Compact release of Vim." $vimtiny_w \
+		"Vim-Tiny" "Compact release of Vim." $vimtiny_w \
 		"" "────File Managers────────────────────────────" "off" \
 		"MC" "Midnight Commander - a powerful file manager." $midnightcommander_w \
 		"" "────SSH Clients──────────────────────────────" "off" \
@@ -6985,7 +7063,7 @@ _EOF_
 		"" "────Development / Programming────────────────" "off" \
 		"Build" "Build-Essentials." $buildessential_w \
 		"Git" "Git Client." $gitclient_w \
-                "" "────Network Tools─────────────────────────────" "off" \
+		"" "────Network Tools─────────────────────────────" "off" \
 		"iftop" "Displays bandwidth usage information." $iftop_w \
 		"IPTraf" "Interactive Colorful IP LAN Monitor." $iptraf_w \
 		"Iperf" "Internet Protocol bandwidth measuring tool." $iperf_w \
@@ -7009,42 +7087,42 @@ _EOF_
 						INSTALL_LINUX_CHOICESMADE=true
 					fi
 				;;
-                                IPTraf)
-                                        if (( $IPTRAF == 0 )); then
-                                                IPTRAF=1
-                                                INSTALL_LINUX_CHOICESMADE=true
-                                        fi
-                                ;;
-                                "MTR-Tiny")
-                                        if (( $MTRTINY == 0 )); then
-                                                MTRTINY=1
-                                                INSTALL_LINUX_CHOICESMADE=true
-                                        fi
-                                ;;
-                                nLoad)
-                                        if (( $NLOAD == 0 )); then
-                                                NLOAD=1
-                                                INSTALL_LINUX_CHOICESMADE=true
-                                        fi
-                                ;;
-                                tcpdump)
-                                        if (( $TCPDUMP == 0 )); then
-                                                TCPDUMP=1
-                                                INSTALL_LINUX_CHOICESMADE=true
-                                        fi
-                                ;;
-                                "Node.js")
-                                        if (( $NODEJS == 0 )); then
-                                                NODEJS=1
-                                                INSTALL_LINUX_CHOICESMADE=true
-                                        fi
-                                ;;
-                                MC)
-                                        if (( $MIDNIGHTCOMMANDER == 0 )); then
-                                                MIDNIGHTCOMMANDER=1
-                                                INSTALL_LINUX_CHOICESMADE=true
-                                        fi
-                                ;;
+				IPTraf)
+					if (( $IPTRAF == 0 )); then
+						IPTRAF=1
+						INSTALL_LINUX_CHOICESMADE=true
+					fi
+				;;
+				"MTR-Tiny")
+					if (( $MTRTINY == 0 )); then
+						MTRTINY=1
+						INSTALL_LINUX_CHOICESMADE=true
+					fi
+				;;
+				nLoad)
+					if (( $NLOAD == 0 )); then
+						NLOAD=1
+						INSTALL_LINUX_CHOICESMADE=true
+					fi
+				;;
+				tcpdump)
+					if (( $TCPDUMP == 0 )); then
+						TCPDUMP=1
+						INSTALL_LINUX_CHOICESMADE=true
+					fi
+				;;
+				"Node.js")
+					if (( $NODEJS == 0 )); then
+						NODEJS=1
+						INSTALL_LINUX_CHOICESMADE=true
+					fi
+				;;
+				MC)
+					if (( $MIDNIGHTCOMMANDER == 0 )); then
+						MIDNIGHTCOMMANDER=1
+						INSTALL_LINUX_CHOICESMADE=true
+					fi
+				;;
 				Java)
 					if (( $ORACLEJAVA == 0 )); then
 						ORACLEJAVA=1
@@ -7063,12 +7141,12 @@ _EOF_
 						INSTALL_LINUX_CHOICESMADE=true
 					fi
 				;;
-                                Jed)
-                                        if (( $JED == 0 )); then
-                                                JED=1
-                                                INSTALL_LINUX_CHOICESMADE=true
-                                        fi
-                                ;;
+				Jed)
+					if (( $JED == 0 )); then
+						JED=1
+						INSTALL_LINUX_CHOICESMADE=true
+					fi
+				;;
 				Vim)
 					if (( $VIMFULL == 0 )); then
 						VIMFULL=1
@@ -7076,11 +7154,11 @@ _EOF_
 					fi
 				;;
 				"Vim-Tiny")
-                                        if (( $VIMTINY == 0 )); then
-                                                VIMTINY=1
-                                                INSTALL_LINUX_CHOICESMADE=true
-                                        fi
-                                ;;
+					if (( $VIMTINY == 0 )); then
+						VIMTINY=1
+						INSTALL_LINUX_CHOICESMADE=true
+					fi
+				;;
 				OpenSSH)
 					if (( $SSHCLIENT == 0 )); then
 						SSHCLIENT=1
