add microblog-pub

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -1533,6 +1533,12 @@ Available commands:
 		aSOFTWARE_DOCS[$software_id]='https://dietpi.com/docs/software/distributed_projects/#ipfs-node'
 		# - RISC-V: Missing package
 		aSOFTWARE_AVAIL_G_HW_ARCH[$software_id,11]=0
+		#-----------------
+		software_id=206
+		aSOFTWARE_NAME[$software_id]='microblog.pub'
+		aSOFTWARE_DESC[$software_id]='A self-hosted, single-user, ActivityPub powered microblog.'
+		aSOFTWARE_CATX[$software_id]=19
+		aSOFTWARE_DOCS[$software_id]='https://docs.microblog.pub/'
 
 		# SSH Clients
 		#--------------------------------------------------------------------------------
@@ -4134,6 +4140,111 @@ _EOF_
 			# Raise packet receive buffer: https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size
 			G_EXEC eval "echo 'net.core.rmem_max=2500000' > /etc/sysctl.d/dietpi-ipfs.conf"
 			G_EXEC sysctl -w net.core.rmem_max=2500000
+		fi
+
+		if To_Install 206 microblog-pub # microblog.pub
+		then
+			## 1. Create a python environment py3.10 via pyenc
+			##	  see: https://python-poetry.org/docs/managing-environments/
+			local micro_pyenv_dir="/home/dietpi/.pyenv_microblog"
+			local micro_pyenv_activate_file="$micro_pyenv_dir/pyenv-activate.sh"
+			local micro_python_version='3.10.7'
+			local micro_dir="/home/dietpi/microblog"
+			local micro_virtualenv="/home/dietpi/microblog/.virtual_path"
+			local micro_systemd="/etc/systemd/system/microblog-pub.service"
+			local micro_functions="/etc/bashrc.d/microblog_pub.sh"
+
+			if ! [ -d $micro_dir ]; then
+				G_EXEC_OUTPUT=1 G_EXEC git clone https://git.sr.ht/~tsileo/microblog.pub $micro_dir
+			fi
+			G_EXEC_OUTPUT=0 G_EXEC chown -R dietpi:dietpi $micro_dir
+
+			## 1. Clone the Repo into location, copy over default config
+			Download_Install 'https://github.com/pyenv/pyenv/archive/master.tar.gz'
+			# - Start with fresh instance, to allow clean pyenv and Python updates and fix broken instances.
+			[[ -d "$micro_pyenv_dir" ]] && G_EXEC rm -R "$micro_pyenv_dir"
+			G_EXEC mv pyenv-master $micro_pyenv_dir
+			G_EXEC chown -R dietpi:dietpi $micro_pyenv_dir
+
+			# 2. Generate script to activate pyenv
+			echo "#!/bin/dash
+cd $micro_pyenv_dir
+export PYENV_ROOT='$micro_pyenv_dir'
+export PATH=\"\$PYENV_ROOT/bin:\$PATH\"
+eval \"\$(pyenv init --path)\"
+eval \"\$(pyenv init -)\"
+cd $micro_dir
+PS1=\"(microblog.pub) \$PS1\" " > "$micro_pyenv_activate_file"
+			G_EXEC chown dietpi:dietpi $micro_pyenv_activate_file
+
+			## Install Python 3.10 and Poetry
+			G_EXEC_DESC='Installing Python with into pyenv'
+			G_EXEC_OUTPUT=1 G_EXEC sudo -u dietpi dash -c "
+source $micro_pyenv_activate_file
+pyenv install $micro_python_version
+pyenv local $micro_python_version
+pip3 install --no-cache-dir -U pip setuptools wheel
+exec pip3 install --no-cache-dir poetry"
+
+			G_EXEC_DESC='Installing Poetry dependencies (can take a while)'
+			G_EXEC_OUTPUT=0 G_EXEC sudo -u dietpi dash -c "
+source $micro_pyenv_activate_file
+pyenv local $micro_python_version
+poetry install
+## Skip these for now:
+## - poetry run inv configuration-wizard
+## - poetry run inv migrate-db
+poetry env info | grep -oP '(?<=^Path:\s).*/virtualenvs/.*' | xargs echo > $micro_virtualenv
+"
+			if [ "$(cat $micro_virtualenv)" = "" ]; then
+				echo "Unable to locate virtualenv" && exit 255
+			fi
+			## 3. Generate functions for later configuration and install to profile
+			cat << _EOF_ > $micro_functions
+#!/bin/bash
+
+microblog_pub (){
+	case \$1 in
+		v*) bash --init-file "$micro_pyenv_activate_file";;  ## venv
+		c*) bash -c "source $micro_pyenv_activate_file; poetry run inv configuration-wizard && poetry run inv migrate-db";; ## configure
+		u*) bash -c "source $micro_pyenv_activate_file; git pull && poetry run inv update";; ## update
+		*) echo "Micropub helper script
+
+    usage:  microblog_pub  <venv|configure|update>
+
+where:
+   configure   runs the configuration wizard and updates the microblog environment.
+   update      pulls the latest changes from the microblog repository and reconfigures.
+   venv        starts a virtual environment where the microblog can be configured.
+" && return;;
+	esac
+
+	sudo systemctl restart microblog-pub
+
+}
+
+_EOF_
+			## 4. Generate systemd script
+			cat << _EOF_ > $micro_systemd
+[Unit]
+Description=Microblog.pub Web Service
+Wants=network-online.target
+After=network-online.target
+
+[Service]
+User=dietpi
+SyslogIdentifier=Microblog.pub
+ExecStart=bash -c "source $micro_pyenv_activate_file; poetry run supervisord -c misc/supervisord.conf -n"
+WorkingDirectory=$micro_dir
+Environment="VENV_DIR=$(cat $micro_virtualenv)"
+RestartForceExitStatus=100
+
+[Install]
+WantedBy=multi-user.target
+_EOF_
+
+			G_EXEC systemctl enable --now microblog-pub
+			G_EXEC_DESC="In order to complete the microblog-pub installation, you need to run 'microblog_pub configure' in a new bash shell!"
 		fi
 
 		if To_Install 2 fahclient # Folding@Home
@@ -12750,6 +12861,23 @@ If no WireGuard (auto)start is included, but you require it, please do the follo
 		then
 			Remove_Service ipfs 1 1
 			G_EXEC rm -Rf /usr/local/bin/ipfs /etc/bashrc.d/dietpi-ipfs.sh /etc/sysctl.d/dietpi-ipfs.conf /mnt/dietpi_userdata/ipfs
+		fi
+
+		if To_Uninstall 206 # microblog.pub
+		then
+			local micro_pyenv="/home/dietpi/.pyenv_microblog"
+			local micro_dir="/home/dietpi/microblog"
+			local micro_systemd="/etc/systemd/system/microblog-pub.service"
+			local micro_functions="/etc/bashrc.d/microblog_pub.sh"
+
+			if [[ -f "$micro_systemd" ]]
+			then
+				G_EXEC systemctl disable --now microblog-pub
+				G_EXEC rm "$micro_systemd"
+			fi
+			[[ -f "$micro_functions" ]] && G_EXEC rm "$micro_functions"
+			[[ -d "$micro_pyenv" ]] && G_EXEC rm -R "$micro_pyenv"
+			G_DIETPI-NOTIFY 2 "All microblog.pub data and settings are still retained.\n - You can remove these manually: rm -R $micro_dir"
 		fi
 
 		if To_Uninstall 98 # HAProxy
