v119
+ dietpi-service status
+ In the process of converting /DietPi/dietpi/func/dietpi-i2c_control to
support all boards (not just RPi)

diff --git a/dietpi/dietpi-services b/dietpi/dietpi-services
--- a/dietpi/dietpi-services
+++ b/dietpi/dietpi-services
@@ -82,6 +82,7 @@
 
 	}
 
+
 	FP_TEMP="/tmp/.dietpi-services_installed"
 
 	#/////////////////////////////////////////////////////////////////////////////////////
@@ -89,7 +90,7 @@
 	#/////////////////////////////////////////////////////////////////////////////////////
 	#Info
 	echo -e "\n DietPi-Services"
-	echo -e " Mode: $1"
+	echo -e " Mode: \e[32m$1\e[0m"
 	echo -e " Please wait..."
 
 	#Find installed services
@@ -116,6 +117,11 @@
 				# - SystemD
 				elif (( $DISTRO == 3 )); then
 					systemctl $1 ${aSERVICE_NAME[$i]} &> /dev/null
+					if (( $? == 0 )); then
+						echo -e "\e[32mOk\e[0m | ${aSERVICE_NAME[$i]}"
+					else
+						echo -e "\e[31mFailed\e[0m | ${aSERVICE_NAME[$i]}"
+					fi
 
 				fi
 
@@ -128,7 +134,7 @@
 			systemctl daemon-reload &> /dev/null
 		fi
 
-		echo -e " Completed"
+		echo -e "\n \e[32mCompleted\e[0m\n"
 
 	#-----------------------------------------------------------------------------------
 	#start/stop/restart
@@ -159,6 +165,11 @@
 				# - SystemD
 				elif (( $DISTRO == 3 )); then
 					systemctl $1 ${aSERVICE_NAME[$i]} &> /dev/null
+					if (( $? == 0 )); then
+						echo -e "\e[32mOk\e[0m | ${aSERVICE_NAME[$i]}"
+					else
+						echo -e "\e[31mFailed\e[0m | ${aSERVICE_NAME[$i]}"
+					fi
 
 				fi
 
@@ -173,14 +184,15 @@
 		/etc/dietpi/dietpi-software/services/squeezeboxserver.service $1 &> /dev/null
 		/etc/dietpi/dietpi-software/services/openbazaar-server.service $1 &> /dev/null
 
-		echo -e " Completed"
+		echo -e "\n \e[32mCompleted\e[0m"
 
 		#Apply process tool settings
 		if [ "$1" = "start" ] ||
 			[ "$1" = "restart" ]; then
-			echo -e "\n DietPi-Process Tool\n Applying settings, please wait...\n"
+			echo -e "\n DietPi-Process Tool\n Applying settings, please wait..."
 			/DietPi/dietpi/dietpi-process_tool 1
-			echo -e " Completed\n"
+			echo -e "\n \e[32mCompleted\e[0m\n"
+
 		fi
 
 	#-----------------------------------------------------------------------------------
