v113

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -196,6 +196,7 @@
 	SQUEEZELITE=0
 	EMONCMS=0
 	EMONHUB=0
+	NODEJS=0
 
 	#Linux Software
 	INSTALL_LINUX_CHOICESMADE=false
@@ -328,6 +329,7 @@ PYDIO $PYDIO
 SQUEEZELITE $SQUEEZELITE
 EMONHUB $EMONHUB
 EMONCMS $EMONCMS
+NODEJS $NODEJS
 
 
 #Additional Linux Software
@@ -437,6 +439,7 @@ _EOF_
 		SQUEEZELITE=$(cat "$FP_INSTALLED_FILE" | grep -m1 'SQUEEZELITE ' | awk '{print $2}')
 		EMONHUB=$(cat "$FP_INSTALLED_FILE" | grep -m1 'EMONHUB ' | awk '{print $2}')
 		EMONCMS=$(cat "$FP_INSTALLED_FILE" | grep -m1 'EMONCMS ' | awk '{print $2}')
+		NODEJS=$(cat "$FP_INSTALLED_FILE" | grep -m1 'NODEJS ' | awk '{print $2}')
 
 		#Linux
 		VIMFULL=$(cat "$FP_INSTALLED_FILE" | grep -m1 'VIMFULL ' | awk '{print $2}')
@@ -1806,7 +1809,6 @@ _EOF_
 
 		fi
 
-
 	}
 
 	Install_Linux_Software(){
@@ -2187,6 +2189,38 @@ _EOF_
 
 		fi
 
+		#NODEJS
+		if (( $NODEJS == 1 )); then
+			INSTALL_DESCRIPTION='NodeJS - Javascript Runtime'
+			Banner_Installing
+
+			#check, is online
+			INSTALL_URL_ADDRESS='https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+			#Install
+			if (( $? == 0 )); then
+
+				# - Preqs
+				AGI apt-transport-https
+
+				# - Add repo
+				curl -s "$INSTALL_URL_ADDRESS" | apt-key add -
+				echo -e "deb https://deb.nodesource.com/node_5.x jessie main" > /etc/apt/sources.list.d/nodesource_nodejs.list
+				/DietPi/dietpi/dietpi-apt-get_update 1
+				apt-get update
+
+				# - install
+				AGI nodejs
+
+			else
+				Error_NoConnection_NoInstall
+
+				#Abort failed install
+				NODEJS=0
+			fi
+
+		fi
 
 	}
 
@@ -6289,6 +6323,15 @@ _EOF_
 			fi
 		fi
 
+		local nodejs_w="off"
+		if (( $NODEJS > 0 )); then
+			nodejs_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $NODEJS == 1 )); then
+				NODEJS=0
+			fi
+		fi
+
 		WHIP_TITLE='Linux - Software Selection'
 		whiptail --title "$WHIP_TITLE" --checklist --separate-output "Press the spacebar to select additional software for installation." --backtitle "$WHIP_BACKTITLE" 19 71 12 \
 		"" "────SSH Clients──────────────────────────────" "off" \
@@ -6303,6 +6346,7 @@ _EOF_
 		"" "────Shared Libraries──────────────────────────" "off" \
 		"FFmpeg" "Audio / Visual libary." $ffmpeg_w \
 		"Java" "Oracle Java 8 jdk/jre libary." $oraclejava_w \
+		"Node.js" "Javascript Runtime." $nodejs_w \
 		"" "────System───────────────────────────────────" "off" \
 		"ALSA" "Linux Sound System" $alsabase_w \
 		"Xserver" "Xinit / Xauth." $xserverxorg_w 2>/tmp/dietpi-software_results
@@ -6310,6 +6354,12 @@ _EOF_
 		while read choice
 		do
 			case $choice in
+				"Node.js")
+					if (( $NODEJS == 0 )); then
+						NODEJS=1
+						INSTALL_LINUX_CHOICESMADE=true
+					fi
+				;;
 				Java)
 					if (( $ORACLEJAVA == 0 )); then
 						ORACLEJAVA=1
