v7.0
+ DietPi-Software | Auto-restore backup: Reformat code (remove doubled indentation and such)
+ DietPi-Software | Only reboot when backup restore succeeded, inform user about it for three seconds
+ DietPi-Software | Downgrade auto-restore =2 to =1 in every case

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -16240,14 +16240,10 @@ _EOF_
 			# Find all software entries of AUTO_SETUP_INSTALL_SOFTWARE_ID= in dietpi.txt. Then set to state 1 for installation.
 			while read -r software_id
 			do
-
 				# Flag for installation
-				if [[ ${aSOFTWARE_NAME[$software_id]} ]]; then
-
-					aSOFTWARE_INSTALL_STATE[$software_id]=1
-					G_DIETPI-NOTIFY 2 "Automation: ${aSOFTWARE_NAME[$software_id]}. Flagged for installation."
-
-				fi
+				[[ ${aSOFTWARE_NAME[$software_id]} ]] || continue
+				aSOFTWARE_INSTALL_STATE[$software_id]=1
+				G_DIETPI-NOTIFY 2 "Automation: ${aSOFTWARE_NAME[$software_id]}. Flagged for installation."
 
 			done <<< "$(grep '^[[:blank:]]*AUTO_SETUP_INSTALL_SOFTWARE_ID=' /boot/dietpi.txt | mawk '{print $1}' | sed 's/[^0-9]*//g')"
 
@@ -17572,72 +17568,81 @@ List of installed software and their online documentation URLs:
 			# Load all automation vars
 			FirstRun_Automation_Init
 
+			# Restore DietPi-Backup
 			if (( $AUTOINSTALL_RESTORE )); then
 
-					# Find unmounted drives
-					lsblk -rnpo NAME,UUID,MOUNTPOINT | mawk '$2 && ! $3 {print $1}' > .lsblk_out_tmp
-					i=0
-					while read -r line
-					do
+				# Reboot only when backup restore succeeded
+				local restore_succeeded=0
 
-						# Mount drives to temporary mount points
-						mkdir "/mnt/dietpi-backup$i"
-						mount "$line" "/mnt/dietpi-backup$i"
+				G_DIETPI-NOTIFY 2 'DietPi-Backup restore selected, scanning and mounting attached drives...'
+				local i=0
+				while read -r line
+				do
+					# Mount drives to temporary mount points
+					mkdir -p "/mnt/dietpi-backup$i" && mount "$line" "/mnt/dietpi-backup$i"
+					((i++))
 
-						((i++))
+				done < <(lsblk -rnpo NAME,UUID,MOUNTPOINT | mawk '$2 && ! $3 {print $1}')
 
-					done < .lsblk_out_tmp
-					rm .lsblk_out_tmp
+				G_DIETPI-NOTIFY 2 'Searching all drives for DietPi-Backup instances...'
+				mapfile -t alist < <(find /mnt -type f -name '.dietpi-backup_stats')
 
-					mapfile -t alist < <(find /mnt -type f -name '.dietpi-backup_stats')
+				# Interactive restore
+				if [[ $AUTOINSTALL_RESTORE == 1 ]]; then
 
-					if [[ $AUTOINSTALL_RESTORE == 1 ]]; then
-						# Do we have any results?
-						if [[ ${alist[0]} ]]; then
-							# Create List for Whiptail
-							G_WHIP_MENU_ARRAY=()
-							for i in "${alist[@]}"
-							do
+					# Do we have any results?
+					if [[ ${alist[0]} ]]; then
 
-								last_backup_date=$(sed -n '/ompleted/s/^.*: //p' "$i" | tail -1) # Date of last backup for this backup
-								backup_directory=${i%/.dietpi-backup_stats} # Backup directory (minus the backup file), that we can use for target backup directory.
-								G_WHIP_MENU_ARRAY+=("$backup_directory" ": $last_backup_date")
+						# Create List for Whiptail
+						G_WHIP_MENU_ARRAY=()
+						for i in "${alist[@]}"
+						do
+							last_backup_date=$(sed -n '/ompleted/s/^.*: //p' "$i" | tail -1) # Date of last backup for this backup
+							backup_directory=${i%/.dietpi-backup_stats} # Backup directory (minus the backup file), that we can use for target backup directory.
+							G_WHIP_MENU_ARRAY+=("$backup_directory" ": $last_backup_date")
+						done
 
-							done
+						G_WHIP_MENU 'Please select a previous backup to restore:' && /boot/dietpi/dietpi-backup -1 "$G_WHIP_RETURNED_VALUE" && restore_succeeded=1
 
-							G_WHIP_MENU 'Please select a previous backup to use:'
-							/boot/dietpi/dietpi-backup -1 "$G_WHIP_RETURNED_VALUE"
+					else
 
-							# Boot into normal DietPi
-							sync
-							reboot
+						G_WHIP_MSG 'No previous backups were found in /mnt/*. Install will continue like normal.'
 
-						else
-							G_WHIP_MSG 'No previous backups were found in /mnt/*. Install will continue like normal.'
-						fi
-					elif [[ $AUTOINSTALL_RESTORE == 2 ]]; then
-						# Do we have any results?
-						if [[ ${alist[0]} ]]; then
-							# Restore first found backup
-							/boot/dietpi/dietpi-backup -1 "${alist[0]%/.dietpi-backup_stats}"
-
-							# Boot into normal DietPi
-							sync
-							reboot
-						else
-							G_DIETPI-NOTIFY 1 'DietPi-Backup auto-restore was selected but no backup has been found in /mnt/*. The dietpi.txt option will be downgraded to 1 (interactive restore).'
-							# Downgrade dietpi.txt option
-							G_CONFIG_INJECT 'AUTO_SETUP_BACKUP_RESTORE=' 'AUTO_SETUP_BACKUP_RESTORE=1' /boot/dietpi.txt
-						fi
 					fi
 
-				# Remove mounted drives
-				umount /mnt/dietpi-backup[0-9]*
-				rmdir /mnt/dietpi-backup[0-9]*
+				# Non-interactive restore
+				elif [[ $AUTOINSTALL_RESTORE == 2 ]]; then
 
-				# Boot into normal DietPi
-				sync
-				reboot
+					# Do we have any results?
+					if [[ ${alist[0]} ]]; then
+
+						# Restore first found backup
+						/boot/dietpi/dietpi-backup -1 "${alist[0]%/.dietpi-backup_stats}" && restore_succeeded=1
+
+					else
+
+						G_DIETPI-NOTIFY 1 'DietPi-Backup auto-restore was selected but no backup has been found in /mnt/*. Install will continue like normal.'
+
+					fi
+
+					# Downgrade dietpi.txt option
+					G_CONFIG_INJECT 'AUTO_SETUP_BACKUP_RESTORE=' 'AUTO_SETUP_BACKUP_RESTORE=1' /boot/dietpi.txt
+
+				fi
+
+				# Remove mounted drives and mount points
+				findmnt /mnt/dietpi-backup[0-9]* > /dev/null && umount /mnt/dietpi-backup[0-9]*
+				[[ -d '/mnt/dietpi-backup0' ]] && rmdir /mnt/dietpi-backup[0-9]*
+
+				# Reboot on successful restore
+				if (( $restore_succeeded )); then
+
+					G_DIETPI-NOTIFY 2 'The system will now reboot into the restored system'
+					sync # Failsafe
+					sleep 3
+					reboot
+
+				fi
 
 			fi
 
