v7.1
+ DietPi-Software | rTorrent: Adjust ruTorrent config so that it connects via RPC socket to rTorrent and additionally protect the RPC URL via HTTP authentication on Lighttpd. Additionally the global software password is used instead of hardcoded "dietpi".

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -11098,7 +11098,7 @@ _EOF_
 			# - Lighttpd
 			elif (( ${aSOFTWARE_INSTALL_STATE[84]} > 0 )); then
 
-				[[ -f '/etc/.rutorrent-htaccess' ]] || echo "root:rtorrent:$(echo -n 'root:rtorrent:dietpi' | md5sum | cut -b -32)" > /etc/.rutorrent-htaccess
+				[[ -f '/etc/.rutorrent-htaccess' ]] || echo "root:rtorrent:$(echo -n "root:rtorrent:$GLOBAL_PW" | md5sum | mawk '{print $1}')" > /etc/.rutorrent-htaccess
 
 				# Add to /etc/lighttpd/lighttpd.conf
 				if ! grep -q '^#RUTORRENT_DIETPI' /etc/lighttpd/lighttpd.conf; then
@@ -11111,7 +11111,13 @@ server.modules += ( "mod_auth" )
 auth.debug = 0
 auth.backend = "htdigest"
 auth.backend.htdigest.userfile = "/etc/.rutorrent-htaccess"
-auth.require = ( "/rutorrent/" =>
+auth.require = ( "/rutorrent" =>
+	(
+		"method"  => "digest",
+		"realm"   => "rtorrent",
+		"require" => "valid-user"
+	),
+	"/RPC2" =>
 	(
 		"method"  => "digest",
 		"realm"   => "rtorrent",
@@ -11149,7 +11155,9 @@ _EOF_
 			G_EXEC chmod 0400 /etc/.rutorrent-htaccess
 			G_EXEC chown www-data:www-data /etc/.rutorrent-htaccess
 
-			# Define curl location in config.php (for Lighttpd and Nginx)
+			# ruTorrent config
+			G_CONFIG_INJECT '\$scgi_port[[:blank:]]' '	$scgi_port = 0;' /var/www/rutorrent/conf/config.php
+			G_CONFIG_INJECT '\$scgi_host[[:blank:]]' '	$scgi_host = "unix:///mnt/dietpi_userdata/downloads/.session/rpc.socket";' /var/www/rutorrent/conf/config.php
 			G_CONFIG_INJECT '"curl"[[:blank:]]' '		"curl"	=> "/usr/bin/curl",' /var/www/rutorrent/conf/config.php
 
 			# Session dir
@@ -11183,7 +11191,7 @@ _EOF_
 
 			fi
 
-			# Default conf, do not overwrite if existent
+			# rTorrent config: Do not overwrite if existent
 			# - Example: https://github.com/rakshasa/rtorrent/blob/master/doc/rtorrent.rc
 			# - Deprecated commands:
 			#	https://github.com/rakshasa/rtorrent/wiki/rTorrent-0.9-Comprehensive-Command-list-(WIP)
@@ -11191,7 +11199,7 @@ _EOF_
 			G_EXEC mkdir -p /mnt/dietpi_userdata/rtorrent
 			if [[ -f '/mnt/dietpi_userdata/rtorrent/.rtorrent.rc' ]]
 			then
-				# Reinstall: Assire that rpi.socket is used
+				# Reinstall: Assure that rpi.socket is used, else ruTorrent connection would fail
 				G_EXEC sed -i '/^[[:blank:]]*network.scgi.open_port/d' /mnt/dietpi_userdata/rtorrent/.rtorrent.rc
 				G_CONFIG_INJECT 'network.scgi.open_local' 'network.scgi.open_local = /mnt/dietpi_userdata/downloads/.session/rpc.socket' /mnt/dietpi_userdata/rtorrent/.rtorrent.rc
 				G_CONFIG_INJECT 'execute.nothrow = chmod,666,/mnt/dietpi_userdata/downloads/.session/rpc.socket' 'execute.nothrow = chmod,666,/mnt/dietpi_userdata/downloads/.session/rpc.socket' /mnt/dietpi_userdata/rtorrent/.rtorrent.rc
