v160
+ Use func return value for handling AGX errors, instead of a global
+ Check_URL connection test now global command
https://github.com/Fourdee/DietPi/issues/1311

diff --git a/dietpi/dietpi-config b/dietpi/dietpi-config
--- a/dietpi/dietpi-config
+++ b/dietpi/dietpi-config
@@ -2832,7 +2832,7 @@ _EOF_
 		INTERNET_ONLINE=0 #Not tested
 
 		#Check for connection
-		/DietPi/dietpi/func/check_connection "$INTERNET_URL"
+		Check_URL "$INTERNET_URL"
 		if (( $? == 0 )); then
 			INTERNET_ONLINE=2 #Online
 		else
@@ -5003,9 +5003,10 @@ Custom     : Write = $CUSTOM_WRITE | Read = $CUSTOM_READ\
 						dietpi-notify 2 "Updating Apt, please wait..."
 
 						AGUP
-						if (( $EXITCODE_APT != 0 )); then
+						local exit_code=$?
+						if (( $exit_code != 0 )); then
 
-							whiptail --title "Apt Error:" --msgbox "Failed to update apt, exit code: $EXITCODE_APT\nPlease try another Apt mirror." --backtitle "$WHIP_BACKTITLE" 8 65
+							whiptail --title "Apt Error:" --msgbox "Failed to update apt, exit code: $exit_code\nPlease try another Apt mirror." --backtitle "$WHIP_BACKTITLE" 8 65
 
 						fi
 
