v6.29
+ DietPi-Update | Use new /run/dietpi runtime dir for update available flag
+ DietPi-Update | Download tarball update archive: less traffic, faster extraction
+ DietPi-Update | Use curl instead of wget, which executes faster, and since we might to drop wget dependency completely. It can be used in combination with G_RUN_CMD when using "-o" option instead of ">" STDOUT redirect
+ DietPi-Update | Minor coding

diff --git a/dietpi/dietpi-update b/dietpi/dietpi-update
--- a/dietpi/dietpi-update
+++ b/dietpi/dietpi-update
@@ -17,7 +17,7 @@
 	# Usage:
 	# - dietpi-update	= Check for updates and in case open interactive menu
 	# - dietpi-update 1	= Check for updates and in case apply noninteractively
-	# - dietpi-update 2	= Check for updates only and in case store result to /boot/dietpi/.update_available to be used by DietPi-Banner
+	# - dietpi-update 2	= Check for updates only and in case store result to /run/dietpi/.update_available to be used by DietPi-Banner
 	# - dietpi-update -1	= Like "1" but internally reduce subversion by 1 to reapply the last update, e.g. to apply latest dev branch changes
 	#////////////////////////////////////
 
@@ -91,10 +91,10 @@
 
 	)
 
-	aURL_MIRROR_ZIP=(
+	aURL_MIRROR_ARCHIVE=(
 
-		"https://github.com/$GITOWNER_TARGET/DietPi/archive/$GITBRANCH_TARGET.zip"
-		"https://dietpi.com/downloads/dietpi-update_mirror/$GITBRANCH_TARGET/DietPi-$GITBRANCH_TARGET.zip"
+		"https://github.com/$GITOWNER_TARGET/DietPi/archive/$GITBRANCH_TARGET.tar.gz"
+		"https://dietpi.com/downloads/dietpi-update_mirror/$GITBRANCH_TARGET/DietPi-$GITBRANCH_TARGET.tar.gz"
 
 	)
 
@@ -162,7 +162,7 @@ If this error persists, please report at: https://github.com/MichaIng/DietPi/iss
 		if (( $DIETPIUPDATE_VERSION_CORE < $COREVERSION_SERVER )); then
 
 			# Write "-1" to flag file for DietPi-Banner to show info about required new image
-			echo '-1' > /boot/dietpi/.update_available
+			echo '-1' > /run/dietpi/.update_available
 
 			G_DIETPI-NOTIFY 1 'The installed version of DietPi is now obsolete and cannot be updated.
 Please download the latest DietPi image from: https://dietpi.com/#download'
@@ -174,7 +174,7 @@ Please download the latest DietPi image from: https://dietpi.com/#download'
 			UPDATE_AVAILABLE=1
 
 			# Write available update version to flag file
-			echo "$COREVERSION_SERVER.$SUBVERSION_SERVER.$RCVERSION_SERVER" > /boot/dietpi/.update_available
+			echo "$COREVERSION_SERVER.$SUBVERSION_SERVER.$RCVERSION_SERVER" > /run/dietpi/.update_available
 
 			G_DIETPI-NOTIFY 0 'Update available:'
 
@@ -185,7 +185,7 @@ Please download the latest DietPi image from: https://dietpi.com/#download'
 			Apply_1st_Run_Update_Success
 
 			# Remove .update_available flag file
-			[[ -f '/boot/dietpi/.update_available' ]] && rm /boot/dietpi/.update_available
+			[[ -f '/run/dietpi/.update_available' ]] && rm /run/dietpi/.update_available
 
 			G_DIETPI-NOTIFY 0 'No update required, your DietPi installation is already up to date:'
 
@@ -212,8 +212,8 @@ Please download the latest DietPi image from: https://dietpi.com/#download'
 		fi
 
 		G_DIETPI-NOTIFY 3 "$G_PROGRAM_NAME" 'Applying pre-patches'
-		G_RUN_CMD wget "${aURL_MIRROR_PREPATCH[$URL_MIRROR_INDEX]}" -O pre-patch_file
-		chmod +x pre-patch_file
+		l_message='Downloading pre-patch file' G_RUN_CMD curl -sSL "${aURL_MIRROR_PREPATCH[$URL_MIRROR_INDEX]}" -o pre-patch_file
+		l_message='Applying execute permission' G_RUN_CMD chmod +x pre-patch_file
 		if ! ./pre-patch_file $G_DIETPI_VERSION_SUB; then
 
 			G_DIETPI-NOTIFY 1 "An error occured during pre-patch $?. Please check the above log or $FP_LOG for errors, and rerun \"dietpi-update\" after the cause has been solved."
@@ -227,65 +227,57 @@ Please download the latest DietPi image from: https://dietpi.com/#download'
 		G_AGUG
 
 		G_DIETPI-NOTIFY 3 "$G_PROGRAM_NAME" 'Installing new DietPi code'
-		if curl -L# "${aURL_MIRROR_ZIP[$URL_MIRROR_INDEX]}" > update.zip; then
+		l_message='Downloading update archive' G_RUN_CMD curl -sSL "${aURL_MIRROR_ARCHIVE[$URL_MIRROR_INDEX]}" -o update.tar.gz; then
 
-			l_message='Unpacking update archive' G_RUN_CMD unzip update.zip
-			rm update.zip
+		l_message='Unpacking update archive' G_RUN_CMD tar xf update.tar.gz
+		rm update.tar.gz
 
-			# Remove files from Git archive that are not to be installed on client
-			rm DietPi-"$GITBRANCH_TARGET"/dietpi/{pre-patch_file,server_version*}
+		# Remove files from Git archive that are not to be installed on client
+		rm DietPi-"$GITBRANCH_TARGET"/dietpi/{pre-patch_file,server_version*}
 
-			# Remove old code before updating, so we dont need to patch for removals
-			# - https://github.com/MichaIng/DietPi/issues/905#issuecomment-298241622
-			#rm -R /boot/dietpi/{func,misc,dietpi-*}
+		# Remove old code before updating, so we dont need to patch for removals
+		# - https://github.com/MichaIng/DietPi/issues/905#issuecomment-298241622
+		#rm -R /boot/dietpi/{func,misc,dietpi-*}
 
-			l_message='Installing new DietPi scripts' G_RUN_CMD cp -Rf DietPi-"$GITBRANCH_TARGET"/dietpi /boot/
-			l_message='Installing new DietPi system files' G_RUN_CMD cp -Rf DietPi-"$GITBRANCH_TARGET"/rootfs/. /
-			l_message='Setting execute permissions for DietPi scripts' G_RUN_CMD chmod -R +x /boot/dietpi /var/lib/dietpi/services /etc/cron.*/dietpi
+		l_message='Installing new DietPi scripts' G_RUN_CMD cp -Rf DietPi-"$GITBRANCH_TARGET"/dietpi /boot/
+		l_message='Installing new DietPi system files' G_RUN_CMD cp -Rf DietPi-"$GITBRANCH_TARGET"/rootfs/. /
+		l_message='Setting execute permissions for DietPi scripts' G_RUN_CMD chmod -R +x /boot/dietpi /var/lib/dietpi/services /etc/cron.*/dietpi
 
-			# Save version + Git info now for sub scripts to pull from correct branch
-			G_GITOWNER=$GITOWNER_TARGET
-			G_GITBRANCH=$GITBRANCH_TARGET
+		# Save version + Git info now for sub scripts to pull from correct branch
+		G_GITOWNER=$GITOWNER_TARGET
+		G_GITBRANCH=$GITBRANCH_TARGET
+		G_VERSIONDB_SAVE
+
+		# Verify/update dietpi.txt entries
+		/boot/dietpi/func/dietpi-set_software verify_dietpi.txt || exit 1
+
+		# Failsafe: Sync changes to disk
+		sync
+		systemctl daemon-reload
+
+		G_DIETPI-NOTIFY 3 "$G_PROGRAM_NAME" 'Applying incremental patches'
+		G_DIETPI-NOTIFY 2 "$INFO_CURRENT_VERSION"
+		G_DIETPI-NOTIFY 2 "$INFO_SERVER_VERSION"
+
+		# Apply subversion patches incrementally
+		while (( $G_DIETPI_VERSION_SUB < $SUBVERSION_SERVER )); do
+
+			G_DIETPI-NOTIFY 2 "Patching $G_DIETPI_VERSION_CORE.$G_DIETPI_VERSION_SUB to $COREVERSION_SERVER.$(( $G_DIETPI_VERSION_SUB + 1 ))"
+			/boot/dietpi/patch_file || exit 1
+			G_DIETPI_VERSION_SUB=$(( $G_DIETPI_VERSION_SUB + 1 ))
+			# Save reached version info, use RC version "0" before last patch has completed
+			(( $G_DIETPI_VERSION_SUB == $SUBVERSION_SERVER )) && G_DIETPI_VERSION_RC=$RCVERSION_SERVER || G_DIETPI_VERSION_RC=0
 			G_VERSIONDB_SAVE
 
-			# Verify/update dietpi.txt entries
-			/boot/dietpi/func/dietpi-set_software verify_dietpi.txt || exit 1
+		done
 
-			# Failsafe: Sync changes to disk
-			sync
-			systemctl daemon-reload
+		G_DIETPI-NOTIFY 0 "Incremental patching to v$COREVERSION_SERVER.$SUBVERSION_SERVER.$RCVERSION_SERVER completed"
 
-			G_DIETPI-NOTIFY 3 "$G_PROGRAM_NAME" 'Applying incremental patches'
-			G_DIETPI-NOTIFY 2 "$INFO_CURRENT_VERSION"
-			G_DIETPI-NOTIFY 2 "$INFO_SERVER_VERSION"
+		# Remove patch_file
+		rm /boot/dietpi/patch_file
 
-			# Apply subversion patches incrementally
-			while (( $G_DIETPI_VERSION_SUB < $SUBVERSION_SERVER )); do
-
-				G_DIETPI-NOTIFY 2 "Patching $G_DIETPI_VERSION_CORE.$G_DIETPI_VERSION_SUB to $COREVERSION_SERVER.$(( $G_DIETPI_VERSION_SUB + 1 ))"
-				/boot/dietpi/patch_file || exit 1
-				G_DIETPI_VERSION_SUB=$(( $G_DIETPI_VERSION_SUB + 1 ))
-				# Save reached version info, use RC version "0" before last patch has completed
-				(( $G_DIETPI_VERSION_SUB == $SUBVERSION_SERVER )) && G_DIETPI_VERSION_RC=$RCVERSION_SERVER || G_DIETPI_VERSION_RC=0
-				G_VERSIONDB_SAVE
-
-			done
-
-			G_DIETPI-NOTIFY 0 "Incremental patching to v$COREVERSION_SERVER.$SUBVERSION_SERVER.$RCVERSION_SERVER completed"
-
-			# Remove patch_file
-			rm /boot/dietpi/patch_file
-
-			# Update info strings
-			INFO_VERSIONS_UPDATE
-
-		# Unable to download file.
-		else
-
-			G_DIETPI-NOTIFY 1 'Download failed, unable to run update. Please try to rerun "dietpi-update".'
-			exit 1
-
-		fi
+		# Update info strings
+		INFO_VERSIONS_UPDATE
 
 	}
 
@@ -296,26 +288,22 @@ Please download the latest DietPi image from: https://dietpi.com/#download'
 
 		local fp_changelog='CHANGELOG.txt'
 
-		if (( ! $CHANGELOG_DOWNLOADED )); then
+		(( $CHANGELOG_DOWNLOADED )) || for i in ${!aURL_MIRROR_CHANGELOG[@]}
+		do
 
-			for i in ${!aURL_MIRROR_CHANGELOG[@]}
-			do
+			G_DIETPI-NOTIFY 2 "Checking mirror: ${aURL_MIRROR_CHANGELOG[$i]}"
+			if curl -sSL "${aURL_MIRROR_CHANGELOG[$i]}" > $fp_changelog; then
 
-				G_DIETPI-NOTIFY 2 "Checking mirror: ${aURL_MIRROR_CHANGELOG[$i]}"
-				if curl -sSL "${aURL_MIRROR_CHANGELOG[$i]}" > $fp_changelog; then
+				CHANGELOG_DOWNLOADED=1
+				break
 
-					CHANGELOG_DOWNLOADED=1
-					break
+			else
 
-				else
+				G_DIETPI-NOTIFY 2 "No response from: ${aURL_MIRROR_CHANGELOG[$i]}"
 
-					G_DIETPI-NOTIFY 2 "No response from: ${aURL_MIRROR_CHANGELOG[$i]}"
+			fi
 
-				fi
-
-			done
-
-		fi
+		done
 
 		if (( $CHANGELOG_DOWNLOADED )); then
 
@@ -424,7 +412,7 @@ Do you wish to continue and update DietPi to v$COREVERSION_SERVER.$SUBVERSION_SE
 
 	fi
 	#----------------------------------------------------------------
-	# Check for update and in case store result to /boot/dietpi/.update_available for use by DietPi-Banner
+	# Check for update and in case store result to /run/dietpi/.update_available for use by DietPi-Banner
 	Check_Update_Available
 	#----------------------------------------------------------------
 	# Update available and no check-only chosen
@@ -459,7 +447,7 @@ Do you wish to continue and update DietPi to v$COREVERSION_SERVER.$SUBVERSION_SE
 			Apply_1st_Run_Update_Success
 
 			# Remove .update_available flag file
-			rm /boot/dietpi/.update_available
+			rm /run/dietpi/.update_available
 
 			G_DIETPI-NOTIFY 3 "$G_PROGRAM_NAME" 'Completed'
 			G_DIETPI-NOTIFY 2 "$INFO_CURRENT_VERSION"
