v113

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -153,6 +153,7 @@
 	WEBSERVER_SQLITE=0
 	WEBSERVER_PHP=0
 	WEBSERVER_MYADMINPHP=0
+	WEBSERVER_REDIS=0
 
 	FILESERVER_PROFTP=0
 	FILESERVER_SAMBA=0
@@ -193,6 +194,8 @@
 	BRUTEFIR=0
 	PYDIO=0
 	SQUEEZELITE=0
+	EMONCMS=0
+	EMONHUB=0
 
 	#Linux Software
 	INSTALL_LINUX_CHOICESMADE=false
@@ -283,6 +286,8 @@ WEBSERVER_MARIADB $WEBSERVER_MARIADB
 WEBSERVER_SQLITE $WEBSERVER_SQLITE
 WEBSERVER_PHP $WEBSERVER_PHP
 WEBSERVER_MYADMINPHP $WEBSERVER_MYADMINPHP
+WEBSERVER_REDIS $WEBSERVER_REDIS
+
 OWNCLOUD $OWNCLOUD
 TRANSMISSION $TRANSMISSION
 PHPBB $PHPBB
@@ -321,6 +326,8 @@ SHAIRPORTSYNC $SHAIRPORTSYNC
 BRUTEFIR $BRUTEFIR
 PYDIO $PYDIO
 SQUEEZELITE $SQUEEZELITE
+EMONHUB $EMONHUB
+EMONCMS $EMONCMS
 
 
 #Additional Linux Software
@@ -388,6 +395,7 @@ _EOF_
 		WEBSERVER_SQLITE=$(cat "$FP_INSTALLED_FILE" | grep -m1 'WEBSERVER_SQLITE ' | awk '{print $2}')
 		WEBSERVER_PHP=$(cat "$FP_INSTALLED_FILE" | grep -m1 'WEBSERVER_PHP ' | awk '{print $2}')
 		WEBSERVER_MYADMINPHP=$(cat "$FP_INSTALLED_FILE" | grep -m1 'WEBSERVER_MYADMINPHP ' | awk '{print $2}')
+		WEBSERVER_REDIS=$(cat "$FP_INSTALLED_FILE" | grep -m1 'WEBSERVER_REDIS ' | awk '{print $2}')
 
 		FILESERVER_PROFTP=$(cat "$FP_INSTALLED_FILE" | grep -m1 'FILESERVER_PROFTP ' | awk '{print $2}')
 		FILESERVER_SAMBA=$(cat "$FP_INSTALLED_FILE" | grep -m1 'FILESERVER_SAMBA ' | awk '{print $2}')
@@ -427,7 +435,8 @@ _EOF_
 		BRUTEFIR=$(cat "$FP_INSTALLED_FILE" | grep -m1 'BRUTEFIR ' | awk '{print $2}')
 		PYDIO=$(cat "$FP_INSTALLED_FILE" | grep -m1 'PYDIO ' | awk '{print $2}')
 		SQUEEZELITE=$(cat "$FP_INSTALLED_FILE" | grep -m1 'SQUEEZELITE ' | awk '{print $2}')
-
+		EMONHUB=$(cat "$FP_INSTALLED_FILE" | grep -m1 'EMONHUB ' | awk '{print $2}')
+		EMONCMS=$(cat "$FP_INSTALLED_FILE" | grep -m1 'EMONCMS ' | awk '{print $2}')
 
 		#Linux
 		VIMFULL=$(cat "$FP_INSTALLED_FILE" | grep -m1 'VIMFULL ' | awk '{print $2}')
@@ -481,9 +490,8 @@ _EOF_
 		local info_2="Apache2"
 		local info_3="MySql"
 		local info_4="PHP"
-		#--------------------------------------------------------------
-		# Apply all "combo" installs that require webserver stack
 
+		# Apply all "combo" installs that require webserver stack
 		# - Installs that require WEBSERVER_LASP
 		if (( $GRASSHOPPER == 1 )); then
 			WEBSERVER_LASP=1
@@ -512,9 +520,10 @@ _EOF_
 			WEBSERVER_LAMP=1
 		elif (( $PYDIO == 1 )); then
 			WEBSERVER_LAMP=1
+		elif (( $EMONCMS == 1 )); then
+			WEBSERVER_LAMP=1
 		fi
 
-		#--------------------------------------------------------------
 		#Define extra DietPi install flags for WEBSERVER_STACKS
 		if (( $WEBSERVER_LLAP == 1 )); then
 			WEBSERVER_LIGHTTPD=1
@@ -609,7 +618,7 @@ _EOF_
 		#--------------------------------------------------------------
 		#Install Software
 
-		#VNC Server requires LXDE
+		#Installs that require DESKTOP_LXDE
 		if (( $TIGHTVNCSERVER == 1 )); then
 			DESKTOP_LXDE=1
 		fi
@@ -711,6 +720,19 @@ _EOF_
 			AGI sqlite3
 		fi
 
+		# - Installs that require WEBSERVER_REDIS
+		if (( $EMONCMS == 1 )); then
+			WEBSERVER_REDIS=1
+		fi
+
+		#WEBSERVER_REDIS
+		if (( $WEBSERVER_REDIS == 1 )); then
+
+			INSTALL_DESCRIPTION="Redis Server"
+			Banner_Installing
+			AGI redis-server
+		fi
+
 		#WEBSERVER_PHP
 		if (( $WEBSERVER_PHP == 1 )); then
 			INSTALL_DESCRIPTION="$info_1: $info_2 / $info_3 / ($info_4)"
@@ -723,7 +745,7 @@ _EOF_
 				AGI php5-fpm php5-cgi
 			fi
 
-			#Install php-SQL modules
+			#php-SQL modules
 			if (( $WEBSERVER_MYSQL == 1 )) ||
 				(( $WEBSERVER_MARIADB == 1 )); then
 				AGI php5-mysql
@@ -732,6 +754,12 @@ _EOF_
 			if (( $WEBSERVER_SQLITE == 1 )); then
 				AGI php5-sqlite
 			fi
+
+			#Redis php5 module
+			if (( $WEBSERVER_REDIS == 1 )); then
+				AGI php5-redis
+			fi
+
 
 			#Wheezy - APC
 			if (( $DISTRO == 1 )); then
@@ -1696,6 +1724,62 @@ _EOF_
 
 		fi
 
+		#EMONCMS
+		if (( $EMONCMS == 1 )); then
+			INSTALL_DESCRIPTION='EmonCMS'
+			Banner_Installing
+
+			#check folder is online
+			INSTALL_URL_ADDRESS='https://github.com/emoncms/emoncms/archive/stable.zip'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+			#Install
+			if (( $? == 0 )); then
+
+				# - Prereqs
+				AGI php5-curl php-pear php5-dev php5-mcrypt ufw
+
+				wget "$INSTALL_URL_ADDRESS" -O package.zip
+				unzip package.zip -d /var/www
+				rm package.zip
+
+				mv /var/www/emoncms* /var/www/emoncms
+
+			else
+				Error_NoConnection_NoInstall
+
+				#Abort failed install
+				EMONCMS=0
+			fi
+
+		fi
+
+		#EMONHUB
+		if (( $EMONHUB == 1 )); then
+			INSTALL_DESCRIPTION='EmonHub'
+			Banner_Installing
+
+			#check, is online
+			INSTALL_URL_ADDRESS='https://github.com/emonhub/dev-emonhub.git'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+			#Install
+			if (( $? == 0 )); then
+
+				# - Prereqs
+				git clone "$INSTALL_URL_ADDRESS" ~/dev-emonhub && ~/dev-emonhub/upgrade
+
+
+			else
+				Error_NoConnection_NoInstall
+
+				#Abort failed install
+				EMONHUB=0
+			fi
+
+		fi
+
+
 	}
 
 	Install_Linux_Software(){
@@ -1744,6 +1828,11 @@ _EOF_
 			AGI build-essential --no-install-recommends
 
 			BUILDESSENTIAL=2
+		fi
+
+		#DietPi software that requires GITCLIENT
+		if (( $EMONCMS == 1 )); then
+			GITCLIENT=1
 		fi
 
 		if (( $GITCLIENT == 1 )); then
@@ -2629,6 +2718,17 @@ _EOF_
 			fi
 
 			WEBSERVER_MYADMINPHP=2
+		fi
+
+		#WEBSERVER_REDIS
+		if (( $WEBSERVER_REDIS == 1 )); then
+
+			#Enable resdis extensions for all webstacks:
+			echo -e "extension=redis.so" > /etc/php5/cli/conf.d/20-redis.ini &> /dev/null
+			echo -e "extension=redis.so" > /etc/php5/apache2/conf.d/20-redis.ini &> /dev/null
+
+
+			WEBSERVER_REDIS=2
 		fi
 
 		#OwnCloud
@@ -3736,6 +3836,58 @@ _EOF_
 
 		fi
 
+		#EMONCMS
+		if (( $EMONCMS == 1 )); then
+
+			# - Enable extensions:
+			echo -e "extension=dio.so" > /etc/php5/apache2/conf.d/20-dio.ini
+			echo -e "extension=dio.so" > /etc/php5/cli/conf.d/20-dio.ini
+
+			# - Enable rewrite engine
+			a2enmod rewrite
+
+			# - Allow overrides and redirects
+			sed -i "/AllowOverride /c\    AllowOverride All" /etc/apache2/sites-enabled/000-default*
+			# - +Jessie
+			sed -i "/AllowOverride /c\    AllowOverride All" /etc/apache2/apache2.conf
+
+			# - Set www permissions
+			chown -R www-data:www-data /var/www/emoncms
+
+			# - Create mysql DB
+			/DietPi/dietpi/func/create_mysql_db emoncms dietpi root dietpi
+
+			# - Create data dirs for emoncms feed engines:
+			mkdir /var/lib/{phpfiwa,phpfina,phptimeseries}
+			chown www-data:root /var/lib/{phpfiwa,phpfina,phptimeseries}
+
+			# - Copy default emonCMS config file, apply our dietpi sql creds
+			cp /var/www/emoncms/default.settings.php /var/www/emoncms/settings.php
+			sed -i 's/_DB_USER_/root/g' /var/www/emoncms/settings.php
+			sed -i 's/_DB_PASSWORD_/dietpi/g' /var/www/emoncms/settings.php
+
+			# - Set write permissions for the emoncms logfile:
+			# NB: Create the file here. chmod 666 permissions are required. Has been added to dietpi-ramlog and applied during boot | Apply_Unique_Logfile_Permissions()
+			echo 0 > /var/log/emoncms.log
+
+
+			EMONCMS=2
+
+		fi
+
+		#EMONHUB
+		if (( $EMONHUB == 1 )); then
+
+			# - root
+			sed -i '/DAEMONUSER=/c\DAEMONUSER=\"root\"' ~/emonhub/service/emonhub
+
+			# - cleanup, whilst waving.
+			userdel -f emonhub
+
+			EMONHUB=2
+
+		fi
+
 	}
 
 	Install_Apply_GPU_Settings(){
@@ -4689,6 +4841,24 @@ _EOF_
 			fi
 		fi
 
+		local emoncms_w="off"
+		if (( $EMONCMS > 0 )); then
+			emoncms_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $EMONCMS == 1 )); then
+				EMONCMS=0
+			fi
+		fi
+
+		local emonhub_w="off"
+		if (( $EMONHUB > 0 )); then
+			emonhub_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $EMONHUB == 1 )); then
+				EMONHUB=0
+			fi
+		fi
+
 		local desktop_w="off"
 		if (( $DESKTOP_LXDE > 0 )); then
 			desktop_w="on"
@@ -4812,6 +4982,15 @@ _EOF_
 			#Reset to 0. Menu checklists will apply back to 1
 			if (( $WEBSERVER_MYADMINPHP == 1 )); then
 				WEBSERVER_MYADMINPHP=0
+			fi
+		fi
+
+		local webserver_redis_w="off"
+		if (( $WEBSERVER_REDIS > 0 )); then
+			webserver_redis_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $WEBSERVER_REDIS == 1 )); then
+				WEBSERVER_REDIS=0
 			fi
 		fi
 
@@ -5338,6 +5517,8 @@ _EOF_
 				"" "────WiFi Hotspot────────────────────────────" "off" \
 				"WiFi Hotspot" "Turn your device into a wifi hotspot." $wifihotspot_w \
 				"" "────Home Automation─────────────────────────" "off" \
+				"EmonCMS" "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx" $emoncms_w \
+				"EmonHUB" "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx" $emonhub_w \
 				"Grasshopper" "Web App to control Bticino MyHome." $grasshopper_w \
 				"" "────RPi Hardware Projects───────────────────" "off" \
 				"RPi.GPIO" "GPIO Interface library for RPi (python)." $rpigpio_w \
@@ -5363,6 +5544,7 @@ _EOF_
 				"LLSP" "Webserver: Lighttpd | SQLite  | Php." $webserver_llsp_w \
 				"LLAP" "Webserver: Lighttpd | MariaDB | Php." $webserver_llap_w \
 				"phpMyAdmin" "Optional MySql admin tools." $webserver_phpmyadmin_w \
+				"Redis" "Optional non-SQL database store." $webserver_redis_w \
 				"LetsEncrypt" "Free, auto SSL cert install allowing https://" $letsencrypt_w \
 				"" "────DNS Servers────────────────────────────" "off" \
 				"Pi-hole" "Block adverts for any device on your network." $pihole_w \
@@ -5450,6 +5632,24 @@ _EOF_
 		do
 			case $choice in
 
+			EmonHUB)
+				if (( $EMONHUB == 0 )); then
+					EMONHUB=1
+					INSTALL_LINUX_CHOICESMADE=true
+				fi
+			;;
+			EmonCMS)
+				if (( $EMONCMS == 0 )); then
+					EMONCMS=1
+					INSTALL_LINUX_CHOICESMADE=true
+				fi
+			;;
+			Redis)
+				if (( $WEBSERVER_REDIS == 0 )); then
+					WEBSERVER_REDIS=1
+					INSTALL_LINUX_CHOICESMADE=true
+				fi
+			;;
 			SqueezeLite)
 				if (( $SQUEEZELITE == 0 )); then
 					SQUEEZELITE=1
