v6.13
+ Check URL before sending survey: https://github.com/Fourdee/DietPi/issues/1968#issuecomment-408615457

diff --git a/dietpi/dietpi-survey b/dietpi/dietpi-survey
--- a/dietpi/dietpi-survey
+++ b/dietpi/dietpi-survey
@@ -105,44 +105,53 @@ _EOF_
 
 			echo '# 1st run update and setup. /DietPi/dietpi/.installed does not exist at this stage.' >> $UPLOAD_FILENAME
 
-		fi	
+		fi
 
 	}
 
 	Send_File(){
 
+		local info_failure_msg='Failed to connect to SFTP server. Please try again later or report this to DietPi forum or GitHub repo in the first place.'
+
 		#Check if we have a working internet connection beforehand
-		G_CHECK_URL "$SFTP_ADDR"
+		G_USER_INPUTS=0 G_RUN_CMD_INFO_ONLY=1 G_CHECK_URL "$SFTP_ADDR"
+		if (( $G_ERROR_HANDLER_EXITCODE_RETURN == 0 )); then
 
-		if (( $OPTED_IN )); then
+			if (( $OPTED_IN )); then
 
-			Generate_File
+				Generate_File
+
+			else
+
+				# Send empty file to overwrite existing data, rm is not possible due to missing file list permissions
+				> "$UPLOAD_FILENAME"
+
+			fi
+
+			#Upload to server
+			curl --connect-timeout 4 --retry 1 --retry-delay 4 -sT "$UPLOAD_FILENAME" sftp://"$SFTP_USER":"$SFTP_PASS"@"$SFTP_ADDR"/survey/
+			if (( $? )); then
+
+				# Silently fail, in case of non-interactive mode
+				(( ! $INPUT )) && G_DIETPI-NOTIFY 1 "$info_failure_msg"
+
+			# Successful upload + opted in
+			elif (( $OPTED_IN )); then
+
+				G_DIETPI-NOTIFY 0 'Successfully sent survey data'
+				# Increase sent count
+				((SURVEY_SENTCOUNT++))
+
+			# Successful upload + opted out + interactive
+			elif (( ! $INPUT )); then
+
+				G_DIETPI-NOTIFY 0 'Successfully purged survey data'
+
+			fi
 
 		else
 
-			# Send empty file to overwrite existing data, rm is not possible due to missing file list permissions
-			> "$UPLOAD_FILENAME"
-
-		fi
-
-		#Upload to server
-		curl --connect-timeout 4 --retry 1 --retry-delay 4 -sT "$UPLOAD_FILENAME" sftp://"$SFTP_USER":"$SFTP_PASS"@"$SFTP_ADDR"/survey/
-		if (( $? )); then
-
-			# Silently fail, in case of non-interactive mode
-			(( ! $INPUT )) && G_DIETPI-NOTIFY 1 'Failed to connect to SFTP server. Please try again later or report this to DietPi forum or GitHub repo in the first place.'
-
-		# Successful upload + opted in
-		elif (( $OPTED_IN )); then
-
-			G_DIETPI-NOTIFY 0 'Successfully sent survey data'
-			# Increase sent count
-			((SURVEY_SENTCOUNT++))
-
-		# Successful upload + opted out + interactive
-		elif (( ! $INPUT )); then
-
-			G_DIETPI-NOTIFY 0 'Successfully purged survey data'
+			G_DIETPI-NOTIFY 1 "$info_failure_msg"
 
 		fi
 
