V116 NETDATA

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -202,6 +202,7 @@
 	EMONCMS=0
 	EMONHUB=0
 	RPIMONITOR=0
+	NETDATA=0
 	BAIKAL=0
 
 	#Linux Software
@@ -344,6 +345,7 @@ SQUEEZELITE $SQUEEZELITE
 EMONHUB $EMONHUB
 EMONCMS $EMONCMS
 RPIMONITOR $RPIMONITOR
+NETDATA $NETDATA
 BAIKAL $BAIKAL
 
 
@@ -462,6 +464,7 @@ _EOF_
 		EMONHUB=$(cat "$FP_INSTALLED_FILE" | grep -m1 'EMONHUB ' | awk '{print $2}')
 		EMONCMS=$(cat "$FP_INSTALLED_FILE" | grep -m1 'EMONCMS ' | awk '{print $2}')
 		RPIMONITOR=$(cat "$FP_INSTALLED_FILE" | grep -m1 'RPIMONITOR ' | awk '{print $2}')
+		NETDATA=$(sed -n 's/^NETDATA\s*\(.*\)/\1/p' "$FP_INSTALLED_FILE")
 		BAIKAL=$(cat "$FP_INSTALLED_FILE" | grep -m1 'BAIKAL ' | awk '{print $2}')
 
 		#Linux
@@ -860,9 +863,9 @@ _EOF_
 			debconf-set-selections <<< "phpmyadmin	phpmyadmin/setup-password		password dietpi"
 			debconf-set-selections <<< "phpmyadmin	phpmyadmin/mysql/app-pass		password dietpi"
 
-			if (( $WEBSERVER_APACHE == 1 )); then
+			if (( $WEBSERVER_APACHE )); then
 				debconf-set-selections <<< "phpmyadmin	phpmyadmin/reconfigure-webserver	multiselect apache2"
-			elif (( $WEBSERVER_LIGHTTPD == 1 )); then
+			elif (( $WEBSERVER_LIGHTTPD )); then
 				debconf-set-selections <<< "phpmyadmin	phpmyadmin/reconfigure-webserver	multiselect lighttpd"
 			else
 				debconf-set-selections <<< "phpmyadmin	phpmyadmin/reconfigure-webserver	multiselect none"
@@ -1932,6 +1935,34 @@ _EOF_
 
 		fi
 
+		#NETDATA
+		if (( $NETDATA == 1 )); then
+			INSTALL_DESCRIPTION='netdata'
+			Banner_Installing
+
+			#check, is online
+			INSTALL_URL_ADDRESS='http://dietpi.com/downloads/testing/netdata_1.0.0_armhf.tgz'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+			#[ -f /boot/custom/netdata-armhf.tgz ]
+
+			#Install
+			if (( $? == 0 )); then
+
+				# AGI --no-install-recommends zlib1g-dev autoconf autogen automake nodejs
+				AGI --no-install-recommends zlib1g-dev nodejs
+				wget "$INSTALL_URL_ADDRESS" -O package.tgz
+				tar -xzvf package.tgz -C /
+				rm package.tgz
+
+			else
+				Error_NoConnection_NoInstall
+
+				#Abort failed install
+				NETDATA=0
+			fi
+
+		fi
+
 		#BAIKAL
 		if (( $BAIKAL == 1 )); then
 			INSTALL_DESCRIPTION='BaiKal'
@@ -1998,6 +2029,8 @@ _EOF_
 			BUILDESSENTIAL=1
 		elif (( $WIRINGPI == 1 )); then
 			BUILDESSENTIAL=1
+#		elif (( $NETDATA == 1 )); then
+#			BUILDESSENTIAL=1
 		fi
 
 		if (( $BUILDESSENTIAL == 1 )); then
@@ -4238,6 +4271,21 @@ _EOF_
 
 		fi
 
+		#NETDATA
+		if (( $NETDATA == 1 )); then
+
+			getent group netdata > /dev/null || groupadd -r netdata
+			getent passwd netdata > /dev/null || useradd -r -g netdata -c netdata -s /sbin/nologin -d / netdata
+
+			for x in /var/cache/netdata /usr/share/netdata/web /etc/netdata /var/log/netdata; do
+				chown -R netdata.netdata $x
+				chmod 0755 $x
+			done
+
+			NETDATA=2
+
+		fi
+
 		#BAIKAL
 		if (( $BAIKAL == 1 )); then
 
@@ -5807,6 +5855,16 @@ _EOF_
 			fi
 		fi
 
+		#NETDATA
+		local netdata_w="off"
+		if (( $NETDATA > 0 )); then
+			netdata_w="on"
+			#Reset to 0.  Menu checklists will apply back to 1
+			if (( $NETDATA == 1 )); then
+				NETDATA=0
+			fi
+		fi
+
 		#-----------------------------------------------------------------------------
 		WHIP_TITLE='DietPi Optimized Software Selection'
 
@@ -5840,6 +5898,7 @@ _EOF_
 			"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
 			"LinuxDash" "Web interface system stats." $linuxdash_w \
 			"PhpSysInfo" "Web interface system stats." $phpsysinfo_w \
+			"netdata" "real-time performance monitoring" $netdata_w \
 			"" "────System Security────────────────────────" "off" \
 			"Fail2Ban" "Prevents brute-force attacks with IP ban." $fail2ban_w \
 			"" "────Webserver Stacks───────────────────────" "off" \
@@ -5893,6 +5952,7 @@ _EOF_
 			"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
 			"LinuxDash" "Web interface system stats." $linuxdash_w \
 			"PhpSysInfo" "Web interface system stats." $phpsysinfo_w \
+			"netdata" "real-time performance monitoring" $netdata_w \
 			"" "────System Security────────────────────────" "off" \
 			"Fail2Ban" "Prevents brute-force attacks with IP ban." $fail2ban_w \
 			"" "────Webserver Stacks───────────────────────" "off" \
@@ -5953,6 +6013,7 @@ _EOF_
 			"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
 			"LinuxDash" "Web interface system stats." $linuxdash_w \
 			"PhpSysInfo" "Web interface system stats." $phpsysinfo_w \
+			"netdata" "real-time performance monitoring" $netdata_w \
 			"" "────System Security────────────────────────" "off" \
 			"Fail2Ban" "Prevents brute-force attacks with IP ban." $fail2ban_w \
 			"" "────Webserver Stacks───────────────────────" "off" \
@@ -6033,6 +6094,7 @@ _EOF_
 				"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
 				"LinuxDash" "Web interface system stats." $linuxdash_w \
 				"PhpSysInfo" "Web interface system stats." $phpsysinfo_w \
+				"netdata" "real-time performance monitoring" $netdata_w \
 				"RPi-Monitor" "Web interface system stats." $rpimonitor_w \
 				"" "────System Security────────────────────────" "off" \
 				"Fail2Ban" "Prevents brute-force attacks with IP ban." $fail2ban_w \
@@ -6105,6 +6167,7 @@ _EOF_
 				"Raspcontrol" "Web interface system stats." $raspcontrol_w \
 				"LinuxDash" "Web interface system stats." $linuxdash_w \
 				"PhpSysInfo" "Web interface system stats." $phpsysinfo_w \
+				"netdata" "real-time performance monitoring" $netdata_w \
 				"" "────System Security────────────────────────" "off" \
 				"Fail2Ban" "Prevents brute-force attacks with IP ban." $fail2ban_w \
 				"" "────Webserver Stacks───────────────────────" "off" \
@@ -6472,6 +6535,12 @@ _EOF_
 			Raspcontrol)
 				if (( $RASPCONTROL == 0 )); then
 					RASPCONTROL=1
+					INSTALL_DIETPI_CHOICESMADE=true
+				fi
+			;;
+			netdata)
+				if (( $NETDATA == 0 )); then
+					NETDATA=1
 					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
