v6.25
+ DietPi-Services | Merge single + all service modes, by adding the input service to the arrays only in case

diff --git a/dietpi/dietpi-services b/dietpi/dietpi-services
--- a/dietpi/dietpi-services
+++ b/dietpi/dietpi-services
@@ -13,14 +13,15 @@
 	# Usage:
 	# - /DietPi/dietpi/dietpi-services $AVAILABLE_OPTIONS
 	AVAILABLE_OPTIONS='
- - [No Input]				(Run Menu)
- - start/stop/restart/status		(all services, known to DietPi)
- - start/stop/restart <servicename>	(single service, systemd)
- - systemd_controlled/dietpi_controlled	(all services, known to DietPi)
- - enable/disable all			(all services, known to DietPi)
- - enable/disable <servicename>		(single service, systemd)
- - mask/unmask all			(all services, known to DietPi)
- - mask/unmask <servicename>		(single service, systemd)
+ - [No Input]						(Run Menu)
+ - start/stop/restart/status				(all services, known to DietPi)
+ - start/stop/restart/status <servicename>		(single service, systemd)
+ - systemd_controlled/dietpi_controlled			(all services, known to DietPi)
+ - systemd_controlled/dietpi_controlled <servicename>	(single service, systemd)
+ - enable/disable					(all services, known to DietPi)
+ - enable/disable <servicename>				(single service, systemd)
+ - mask/unmask						(all services, known to DietPi)
+ - mask/unmask <servicename>				(single service, systemd)
 
  - You can include/exclude custom services by editing the following file: /DietPi/dietpi/.dietpi-services_include_exclude'
 	#////////////////////////////////////
@@ -28,6 +29,8 @@
 	# Grab Inputs
 	INPUT_MODE=$1
 	INPUT_SERVICE=$2
+	# - pre-v6.25 compatibility
+	[[ $INPUT_SERVICE == 'all' ]] && unset INPUT_SERVICE
 
 	# - Optional input variables to prevent service handling
 	[[ $G_DIETPI_SERVICES_DISABLE == 1 ]] && exit 0
@@ -53,6 +56,9 @@
 		aIO_SCHEDULE_POLICY=()
 		aIO_PRIORITY=()
 
+		# Single service input, skip adding any further services to array
+		[[ $INPUT_SERVICE ]] && { aSERVICE_NAME=("$INPUT_SERVICE"); return; }
+
 		aCPU_SCHEDULE_POLICY_TYPE=('other' 'fifo' 'rr' 'batch' 'idle')
 		aCPU_SCHEDULE_POLICY_DESC=('Normal (Default)' 'First In, First Out (Real-time, time-critical)' 'Round Robin (Real-time, time-critical)' 'Batch style execution' 'Background Jobs (Very low priority)')
 
@@ -71,15 +77,15 @@
 			# - File servers
 			'proftpd'
 			'vsftpd'
-			'nmbd'
-				'smbd'
+			'nmbd' 'smbd'
 			'nfs-kernel-server'
 			# Core -----------------------------------------------------------------
 
 			# Backends -------------------------------------------------------------
 			# - Databases
 			'redis-server'
-			'mariadb' # 'mysql' applied on Jessie systems during availablility check: https://github.com/MichaIng/DietPi/issues/1000#issuecomment-30776051
+			'mariadb'
+			#'mysql' # Applied on Jessie systems during availablility check: https://github.com/MichaIng/DietPi/issues/1000#issuecomment-30776051
 
 			# - PHP
 			'php5-fpm'
@@ -107,8 +113,7 @@
 			'roonbridge'
 			'roonserver'
 			'roon-extension-manager'
-			'icecast2'
-				'darkice'
+			'icecast2' 'darkice'
 			'voice-recognizer'
 
 			# - Download/BitTorrent
@@ -134,10 +139,8 @@
 			'emby-server'
 			'spotify-connect-web'
 			'ubooquity'
-			#'moode-worker'
 
 			# - Download/BitTorrent
-			'sickrage' # pre-v6.20 compatibility
 			'medusa'
 			'aria2'
 			'sabnzbd'
@@ -152,8 +155,7 @@
 			# - Cloud/Backups
 			'bdd'
 			'minio'
-			'syncthing'
-				'syncthing-inotify'
+			'syncthing' 'syncthing-inotify'
 			'urbackupsrv'
 			'tonido'
 			'gogs'
@@ -169,8 +171,7 @@
 			'raspimjpeg'
 
 			# - Printing
-			'cups'
-				'cloudprintd'
+			'cups' 'cloudprintd'
 			'octoprint'
 
 			# - Social/Search
@@ -194,7 +195,6 @@
 			# - Network
 			'noip2'
 			'virtualhere'
-			#'pihole-FTL' # https://github.com/MichaIng/DietPi/issues/1696
 			'hostapd'
 
 			# - System stats / Management
@@ -203,7 +203,6 @@
 			'webmin'
 
 			# - Misc
-			#'openmediavault-engined'
 			'docker'
 			'cron'
 			'fahclient'
@@ -230,7 +229,7 @@
 			aSERVICE_NAME+=('vncserver') 			# DietPi vnc server service/script
 			aSERVICE_NAME+=('nxserver') 			# NoMachine
 			aSERVICE_NAME+=('xrdp') 			# XRDP Server
-			aSERVICE_NAME+=('amiberry') 			# DietPi AmiBerry run service
+			aSERVICE_NAME+=('amiberry') 			# DietPi Amiberry run service
 			#aSERVICE_NAME+=('wg-quick@wg0') 		# WireGuard: Currently instantiated services are not supported 
 
 			# - DietPi
@@ -249,6 +248,8 @@
 
 		fi
 
+		Process_Includes_Excludes
+
 	}
 
 
@@ -256,60 +257,72 @@
 	FP_INCLUDE_CUSTOM_SERVICES='/DietPi/dietpi/.dietpi-services_include_exclude'
 	Process_Includes_Excludes(){
 
-		if [[ -f $FP_INCLUDE_CUSTOM_SERVICES ]]; then
+		[[ -f $FP_INCLUDE_CUSTOM_SERVICES ]] || cat << _EOF_ > $FP_INCLUDE_CUSTOM_SERVICES
+# DietPi-Services Include/Exclude configuration
 
-			while read line
-			do
+# Include custom service (Use '+ servicename' without the comments to enable DietPi control of that service)
+#	Once completed, for DietPi to control the service, please run the following command, without quotes (')
+#	'dietpi-services dietpi_controlled'
+#+ myservice1
+#+ myservice2
 
-				[[ $line == '#'* ]] && continue
+# Exclude DietPi from controlling known services (Use '- servicename' without the comments to disable DietPi control for that service)
+#	The service will be in disabled form, and, you can start and stop it manually
+#- cron
+#- transmission-daemon
 
-				local scrape=${line: +2}
-				local i=''
+_EOF_
 
-				# - Include
-				if [[ $line == '+ '* ]]; then
+		while read line
+		do
 
-					local service_known_already_to_dietpi=0
-					for i in "${aSERVICE_NAME[@]}"
-					do
+			[[ ! $line || $line == '#'* ]] && continue
 
-						if [[ $scrape == "$i" ]]; then
+			local scrape=${line: +2}
+			local i=''
 
-							service_known_already_to_dietpi=1
-							break
+			# - Include
+			if [[ $line == '+ '* ]]; then
 
-						fi
+				local service_known_already_to_dietpi=0
+				for i in "${aSERVICE_NAME[@]}"
+				do
 
-					done
+					if [[ $scrape == "$i" ]]; then
 
-					if (( ! $service_known_already_to_dietpi )); then
-
-						[[ $G_DEBUG == 1 ]] && G_DIETPI-NOTIFY 2 "Including custom service: $scrape"
-						aSERVICE_NAME+=("$scrape")
+						service_known_already_to_dietpi=1
+						break
 
 					fi
 
-				# - Exclude
-				elif [[ $line == '- '* ]]; then
+				done
 
-					for i in ${!aSERVICE_NAME[@]}
-					do
+				if (( ! $service_known_already_to_dietpi )); then
 
-						if [[ $scrape == "${aSERVICE_NAME[$i]}" ]]; then
-
-							[[ $G_DEBUG == 1 ]] && G_DIETPI-NOTIFY 2 "Excluding service: $scrape"
-							unset aSERVICE_NAME[$i]
-							break
-
-						fi
-
-					done
+					[[ $G_DEBUG == 1 ]] && G_DIETPI-NOTIFY 2 "Including custom service: $scrape"
+					aSERVICE_NAME+=("$scrape")
 
 				fi
 
-			done < $FP_INCLUDE_CUSTOM_SERVICES
+			# - Exclude
+			elif [[ $line == '- '* ]]; then
 
-		fi
+				for i in ${!aSERVICE_NAME[@]}
+				do
+
+					if [[ $scrape == "${aSERVICE_NAME[$i]}" ]]; then
+
+						[[ $G_DEBUG == 1 ]] && G_DIETPI-NOTIFY 2 "Excluding service: $scrape"
+						unset aSERVICE_NAME[$i]
+						break
+
+					fi
+
+				done
+
+			fi
+
+		done < $FP_INCLUDE_CUSTOM_SERVICES
 
 	}
 
@@ -411,8 +424,6 @@ _EOF_
 
 		Init_Arrays
 
-		Process_Includes_Excludes
-
 		local i=0
 		for i in ${!aSERVICE_NAME[@]}
 		do
@@ -437,8 +448,13 @@ _EOF_
 
 			done
 
-			# Remove non-available services from array
-			[[ ${aCPU_NICE[$i]} ]] || unset aSERVICE_NAME[$i]
+			# Remove non-available services from array, print info in case of single service input mode
+			if [[ ! ${aCPU_NICE[$i]} ]]; then
+
+				unset aSERVICE_NAME[$i]
+				[[ $INPUT_SERVICE ]] && G_DIETPI-NOTIFY 1 "Service ($INPUT_SERVICE) could not be found."
+
+			fi
 
 		done
 
@@ -450,9 +466,8 @@ _EOF_
 		# $2 = name
 		# $3 = exit code
 
-		# - NB: systemd exit code 5 = not loaded/active, so don't trigger a failed result.
-
 		# Ok
+		# - NB: systemd exit code 5 = not loaded/active, so don't trigger a failed result.
 		if [[ $3 == [05] ]]; then
 
 			G_DIETPI-NOTIFY 0 "$1 : $2"
@@ -472,8 +487,8 @@ _EOF_
 		local target_state=$1
 		local i=''
 
-		# Enable ownCloud and Nextcloud maintenance mode
-		if [[ $target_state == 'stop' || $target_state == 'restart' ]]; then
+		# Enable ownCloud and Nextcloud maintenance mode before all services being stopped or restarted
+		if [[ $target_state == 'stop' || $target_state == 'restart' && ! $INPUT_SERVICE ]]; then
 
 			[[ -f '/var/www/owncloud/config/config.php' ]] && grep -q "'maintenance' => false," /var/www/owncloud/config/config.php && G_USER_INPUTS=0 G_ERROR_HANDLER_INFO_ONLY=1 G_RUN_CMD occ maintenance:mode --on
 			[[ -f '/var/www/nextcloud/config/config.php' ]] && grep -q "'maintenance' => false," /var/www/nextcloud/config/config.php && G_USER_INPUTS=0 G_ERROR_HANDLER_INFO_ONLY=1 G_RUN_CMD ncc maintenance:mode --on
@@ -494,29 +509,30 @@ _EOF_
 			for i in $reverse
 			do
 
-				G_DIETPI-NOTIFY -2 ${aSERVICE_NAME[$i]}
-				systemctl $target_state ${aSERVICE_NAME[$i]} &> /dev/null
-				Print_Status $target_state ${aSERVICE_NAME[$i]} $?
+				G_DIETPI-NOTIFY -2 "${aSERVICE_NAME[$i]}"
+				systemctl $target_state "${aSERVICE_NAME[$i]}" &> /dev/null
+				Print_Status $target_state "${aSERVICE_NAME[$i]}" $?
 
 				aSERVICE_RESTART_REQUIRED[$i]=0
 
 			done
 
-		# EG: START/RESTART: Standard service order
+		# START/RESTART: Standard service order
 		else
 
 			for i in ${!aSERVICE_NAME[@]}
 			do
 
-				G_DIETPI-NOTIFY -2 ${aSERVICE_NAME[$i]}
-				systemctl $target_state ${aSERVICE_NAME[$i]} &> /dev/null
-				Print_Status $target_state ${aSERVICE_NAME[$i]} $?
+				G_DIETPI-NOTIFY -2 "${aSERVICE_NAME[$i]}"
+				systemctl $target_state "${aSERVICE_NAME[$i]}" &> /dev/null
+				Print_Status $target_state "${aSERVICE_NAME[$i]}" $?
 
 				aSERVICE_RESTART_REQUIRED[$i]=0
 
 			done
 
-			# - Disable ownCloud and Nextcloud maintenance mode
+			# - Disable ownCloud and Nextcloud maintenance mode before all services being started or restarted
+			[[ $INPUT_SERVICE ]] && return
 			[[ -f '/var/www/owncloud/config/config.php' ]] && grep -q "'maintenance' => true," /var/www/owncloud/config/config.php && G_USER_INPUTS=0 G_ERROR_HANDLER_INFO_ONLY=1 G_RUN_CMD occ maintenance:mode --off
 			[[ -f '/var/www/nextcloud/config/config.php' ]] && grep -q "'maintenance' => true," /var/www/nextcloud/config/config.php && G_USER_INPUTS=0 G_ERROR_HANDLER_INFO_ONLY=1 G_RUN_CMD ncc maintenance:mode --off
 
@@ -528,7 +544,6 @@ _EOF_
 	Apply_Service_States(){
 
 		local mode=$1
-		local service=$2
 		local systemd_cmd='disable'
 
 		# dietpi_controlled/systemd_controlled
@@ -539,44 +554,29 @@ _EOF_
 			for i in "${aSERVICE_NAME[@]}"
 			do
 
-				G_DIETPI-NOTIFY -2 "$i"
 				systemctl $systemd_cmd "$i" &> /dev/null
 				Print_Status $mode "$i" $?
 
 			done
 
-			systemctl daemon-reload &> /dev/null
-
 		# mask/unmask/enable/disable
 		elif [[ $mode == 'enable' || $mode == 'disable' || $mode == 'unmask' || $mode == 'mask' ]]; then
 
-			# - Switch to mask, as DietPi_Controlled uses disable to take over from systemd
+			# - Switch to mask, as DietPi_controlled uses disable to take over from systemd
 			[[ $mode == 'enable' || $mode == 'unmask' ]] && systemd_cmd='unmask' || systemd_cmd='mask'
 
-			# - Process ALL known services
-			if [[ $service == 'all' ]]; then
+			# - Stop services before disable or mask them
+			[[ $mode == 'disable' || $mode == 'mask' ]] && Set_Running_State stop
 
-				[[ $mode == 'disable' || $mode == 'mask' ]] && Set_Running_State stop
-
-				for i in "${aSERVICE_NAME[@]}"
-				do
-
-					G_DIETPI-NOTIFY 0 "$mode $service: $i"
-					systemctl $systemd_cmd "$i"
-
-				done
-
-
-			# - Process user defined single entry via cmd input
-			else
-
-				[[ $mode == 'disable' || $mode == 'mask' ]] && systemctl stop $service
+			for i in "${aSERVICE_NAME[@]}"
+			do
 
 				local notify_index=0
 				systemctl $systemd_cmd "$service" || notify_index=1
-				G_DIETPI-NOTIFY $notify_index "$mode $service"
+				G_DIETPI-NOTIFY $notify_index "$mode $i"
 
-			fi
+			done
+
 
 		# status
 		elif [[ $mode == 'status' ]]; then
@@ -584,7 +584,6 @@ _EOF_
 			for i in "${aSERVICE_NAME[@]}"
 			do
 
-				# Apply
 				local status="$i\t$(systemctl status "$i" | grep -m1 'Active' | cut -c12-)"
 				if [[ $status =~ 'failed' ]]; then
 
@@ -606,25 +605,7 @@ _EOF_
 		# start/stop/restart
 		elif [[ $mode == 'start' || $mode == 'stop' || $mode == 'restart' ]]; then
 
-			# Single use case, basically a alias for systemd
-			if [[ $service ]]; then
-
-				if systemctl $mode "$service" &> /dev/null; then
-
-					G_DIETPI-NOTIFY 0 "$mode $service"
-
-				else
-
-					G_DIETPI-NOTIFY 1 "$mode $service"
-
-				fi
-
-			# All services controlled
-			else
-
-				Set_Running_State $mode
-
-			fi
+			Set_Running_State $mode
 
 		else
 
@@ -708,10 +689,10 @@ _EOF_
 
 			if [[ $G_WHIP_RETURNED_VALUE == 'Restart' || $G_WHIP_RETURNED_VALUE == 'Stop' ]]; then
 
-				Apply_Service_States ${G_WHIP_RETURNED_VALUE,,}
+				Set_Running_State ${G_WHIP_RETURNED_VALUE,,}
 				sleep 0.5
 
-			else
+			elif [[ $G_WHIP_RETURNED_VALUE ]]; then
 
 				# Find selected program index
 				MENU_SELECTED_SERVICE_INDEX=-1
@@ -901,7 +882,6 @@ _EOF_
 					if G_WHIP_MENU "Please select the desired IO Scheduling Class for :\n${aSERVICE_NAME[$MENU_SELECTED_SERVICE_INDEX]}"; then
 
 						aIO_SCHEDULE_POLICY[$MENU_SELECTED_SERVICE_INDEX]=$G_WHIP_RETURNED_VALUE
-
 						Save_Process_Tool $MENU_SELECTED_SERVICE_INDEX
 
 					fi
@@ -951,8 +931,12 @@ _EOF_
 					local target_mode='restart'
 					[[ ${service_state,,} == 'active' ]] && target_mode='stop'
 
-					Apply_Service_States $target_mode "${aSERVICE_NAME[$MENU_SELECTED_SERVICE_INDEX]}"
+					G_DIETPI-NOTIFY -2 "${aSERVICE_NAME[$i]}"
+					systemctl $target_state "${aSERVICE_NAME[$i]}" &> /dev/null
+					Print_Status $target_state "${aSERVICE_NAME[$i]}" $?
 					sleep 0.5
+
+					aSERVICE_RESTART_REQUIRED[$i]=0
 
 				;;
 
@@ -1074,7 +1058,6 @@ Info:\n - Negative values have a higher priority (eg: -10).\n - Positive values 
 					if G_WHIP_MENU "Please select the desired CPU Scheduling Policy for :\n${aSERVICE_NAME[$MENU_SELECTED_SERVICE_INDEX]}"; then
 
 						aCPU_SCHEDULE_POLICY[$MENU_SELECTED_SERVICE_INDEX]=$G_WHIP_RETURNED_VALUE
-
 						Save_Process_Tool $MENU_SELECTED_SERVICE_INDEX
 
 					fi
@@ -1093,7 +1076,7 @@ Info:\n - Negative values have a higher priority (eg: -10).\n - Positive values 
 					local scale_value_medium=$(( $scale_value_highest / 6 * 3 ))
 					local scale_value_high=$(( $scale_value_highest / 6 * 4 ))
 					local scale_value_higher=$(( $scale_value_highest / 6 * 5 ))
-					for ((i=0; i<$(( $scale_value_highest + 1 )); i++))
+					for ((i=0; i<=$scale_value_highest; i++))
 					do
 
 						local description=''
@@ -1136,7 +1119,6 @@ Info:\n - Negative values have a higher priority (eg: -10).\n - Positive values 
 - Lower values are low priority\n - Higher values are high priority"; then
 
 						aCPU_SCHEDULE_PRIORITY[$MENU_SELECTED_SERVICE_INDEX]=$G_WHIP_RETURNED_VALUE
-
 						Save_Process_Tool $MENU_SELECTED_SERVICE_INDEX
 
 					fi
@@ -1157,24 +1139,7 @@ Info:\n - Negative values have a higher priority (eg: -10).\n - Positive values 
 	# Main
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Info
-	G_DIETPI-NOTIFY 3 "$G_PROGRAM_NAME" "$INPUT_MODE"
-
-	[[ -f $FP_INCLUDE_CUSTOM_SERVICES ]] || cat << _EOF_ > $FP_INCLUDE_CUSTOM_SERVICES
-# DietPi-Services Include/Exclude configuration
-
-# Include custom service (Use '+ servicename' without the comments to enable DietPi control of that service)
-#	Once completed, for DietPi to control the service, please run the following command, without quotes (')
-#	'dietpi-services dietpi_controlled'
-#+ myservice1
-#+ myservice2
-
-# Exclude DietPi from controlling known services (Use '- servicename' without the comments to disable DietPi control for that service)
-#	The service will be in disabled form, and, you can start and stop it manually
-#- cron
-#- transmission-daemon
-
-_EOF_
-
+	G_DIETPI-NOTIFY 3 "$G_PROGRAM_NAME" "$INPUT_MODE $INPUT_SERVICE"
 	#-----------------------------------------------------------------------------------
 	# Load array of available services
 	Populate_Available_Array
@@ -1182,7 +1147,7 @@ _EOF_
 	# Direct service control mode
 	if [[ $INPUT_MODE ]]; then
 
-		Apply_Service_States $INPUT_MODE $INPUT_SERVICE
+		Apply_Service_States $INPUT_MODE
 
 	#-----------------------------------------------------------------------------------
 	# Men You!
