v7.1
+ DietPi-Drive_Manager | Unmount drive automatically on format, so that it does not need to be unmounted manually. Use Unmount_Drive function, so that the mount point directory is removed as well.
+ DietPi-Drive_Manager | Unmount drive and stop service on fsck after a supported filesystem type has been detected to minimise the cases where services are stopped unnecessarily.

diff --git a/dietpi/dietpi-drive_manager b/dietpi/dietpi-drive_manager
--- a/dietpi/dietpi-drive_manager
+++ b/dietpi/dietpi-drive_manager
@@ -538,7 +538,7 @@ Do you wish to ignore this warning, and, mount the drive regardless?" || return 
 		local i text_desc info_format_fs_type
 		local info_format_type_output='Drive format' # Used in complete message
 
-		# No partition table, force drive wipe
+		# Failsafe: No partition table, force drive wipe - actually done in parent menu already
 		(( ${aDRIVE_ISPARTITIONTABLE[$MENU_DRIVE_INDEX]} )) || FORMAT_MODE=0
 
 		if (( $FORMAT_MODE )); then
@@ -559,7 +559,7 @@ Do you wish to ignore this warning, and, mount the drive regardless?" || return 
 				info_format_type_output='Single partition format'
 
 				# Unmount
-				umount "${aDRIVE_MOUNT_SOURCE[$MENU_DRIVE_INDEX]}"
+				(( ${aDRIVE_ISMOUNTED[$MENU_DRIVE_INDEX]} )) && { Unmount_Drive "${aDRIVE_MOUNT_TARGET[$MENU_DRIVE_INDEX]}" || return 1; }
 
 				# Clear partition from device
 				G_DIETPI-NOTIFY 2 "Writing zeros to partition ${aDRIVE_MOUNT_SOURCE[$MENU_DRIVE_INDEX]}"
@@ -573,13 +573,14 @@ Do you wish to ignore this warning, and, mount the drive regardless?" || return 
 				for i in "/dev/${aDRIVE_SOURCE_DEVICE[$MENU_DRIVE_INDEX]}"?*
 				do
 					[[ -b $i ]] || continue
-					findmnt "$i" > /dev/null && G_EXEC umount "$i"
+					local target=$(findmnt -no TARGET "$i")
+					[[ $target ]] && { Unmount_Drive "$target"  || return 1; }
 					G_DIETPI-NOTIFY 2 "Writing zeros to partition: $i"
 					G_EXEC dd if=/dev/zero of="$i" bs=4K count=10
 				done
 
 				# Unmount whole drive in case of fs on drive without partition table
-				findmnt "${aDRIVE_MOUNT_SOURCE[$MENU_DRIVE_INDEX]}" > /dev/null && G_EXEC umount "${aDRIVE_MOUNT_SOURCE[$MENU_DRIVE_INDEX]}"
+				(( ${aDRIVE_ISMOUNTED[$MENU_DRIVE_INDEX]} )) && { Unmount_Drive "${aDRIVE_MOUNT_TARGET[$MENU_DRIVE_INDEX]}" || return 1; }
 
 				# Clear partition table from device
 				G_DIETPI-NOTIFY 2 "Writing zeros to partition table: /dev/${aDRIVE_SOURCE_DEVICE[$MENU_DRIVE_INDEX]}"
@@ -919,7 +920,7 @@ Do you wish to ignore this warning, and, mount the drive regardless?" || return 
 
 			elif [[ $G_WHIP_RETURNED_VALUE == 'Add network drive' ]]; then
 
-				TARGETMENUID=3
+				TARGETMENUID=3 # Add network drive menu
 
 			elif [[ $G_WHIP_RETURNED_VALUE == 'Idle Spindown' ]]; then
 
@@ -974,7 +975,7 @@ Do you wish to ignore this warning, and, mount the drive regardless?" || return 
 			# Edit drive
 			elif [[ $G_WHIP_RETURNED_VALUE ]]; then
 
-				TARGETMENUID=1
+				TARGETMENUID=1 # Drive menu
 				MENU_DRIVE_TARGET=$G_WHIP_RETURNED_VALUE
 				Update_Menu_Drive_Index
 
@@ -1002,6 +1003,7 @@ Do you wish to ignore this warning, and, mount the drive regardless?" || return 
 
 	}
 
+	# TARGETMENUID=1
 	Menu_Drive(){
 
 		G_WHIP_MENU_ARRAY=()
@@ -1216,7 +1218,7 @@ Do you wish to ignore this warning, and, mount the drive regardless?" || return 
 \nNB: You can add additional network shares at a later date through the 'dietpi-drive_manager' main menu."; then
 
 						Unmount_Drive "${aDRIVE_MOUNT_TARGET[$MENU_DRIVE_INDEX]}"
-						TARGETMENUID=0
+						TARGETMENUID=0 # Main menu
 
 					fi
 
@@ -1318,14 +1320,9 @@ Please enter the desired percentage of reserved blocks, e.g. "0.05" for 0.05% or
 
 					Notification 1
 
-				# User must unmount partition on this drive, before we can format, this ensures a valid unmount check
-				elif (( ${aDRIVE_ISMOUNTED[$MENU_DRIVE_INDEX]} )); then
-
-					G_WHIP_MSG "The partition (${aDRIVE_MOUNT_SOURCE[$MENU_DRIVE_INDEX]}) must be unmounted, before formatting is allowed.\n\nPlease use the option 'Unmount' on the next screen, then retry the 'Format' option."
-
 				else
 
-					TARGETMENUID=2
+					TARGETMENUID=2 # Format menu
 
 				fi
 
@@ -1361,12 +1358,10 @@ We recommend \"ext4\" as filesystem type for the RootFS."
 \n - Odroid: RootFS transfer supports ONLY EXT4 format\n\n - RPi: RootFS transfer supports EXT4, BTRFS and F2FS'
 
 						# NB: We dont enter main loop in this func
-						TARGETMENUID=2
+						TARGETMENUID=2 # Format menu
 						while (( $TARGETMENUID == 2 ))
 						do
-
 							Menu_Format
-
 						done
 
 						(( $FORMAT_COMPLETED )) && RootFS_Move
@@ -1406,21 +1401,6 @@ We recommend \"ext4\" as filesystem type for the RootFS."
 
 					fi
 					return
-
-				fi
-
-				if (( ${aDRIVE_ISMOUNTED[$MENU_DRIVE_INDEX]} )); then
-
-					G_WHIP_YESNO 'For safe check and repair, the drive needs to be unmounted.
-\nDo you want to continue with the drive being unmounted automatically?' || { TARGETMENUID=1; return; }
-
-					(( $SERVICES_STOPPED )) || { /boot/dietpi/dietpi-services stop; SERVICES_STOPPED=1; }
-
-					# Disable swap
-					(( $partition_contains_swapfile )) && G_EXEC swapoff -a
-
-					# Unmount drive
-					G_EXEC umount "${aDRIVE_MOUNT_SOURCE[$MENU_DRIVE_INDEX]}"
 
 				fi
 
@@ -1473,8 +1453,22 @@ We recommend \"ext4\" as filesystem type for the RootFS."
 				else
 
 					G_WHIP_MSG "Filesystem checks are currently not supported for '${aDRIVE_FSTYPE[$MENU_DRIVE_INDEX]}'. Aborting..."
-					TARGETMENUID=1
-					return
+					return 1
+
+				fi
+
+				if (( ${aDRIVE_ISMOUNTED[$MENU_DRIVE_INDEX]} )); then
+
+					G_WHIP_YESNO 'For safe check and repair, the drive needs to be unmounted.
+\nDo you want to continue with the drive being unmounted automatically?' || return 1
+
+					(( $SERVICES_STOPPED )) || { /boot/dietpi/dietpi-services stop; SERVICES_STOPPED=1; }
+
+					# Disable swap
+					(( $partition_contains_swapfile )) && G_EXEC swapoff -a
+
+					# Unmount drive
+					G_EXEC umount "${aDRIVE_MOUNT_SOURCE[$MENU_DRIVE_INDEX]}"
 
 				fi
 
@@ -1537,12 +1531,13 @@ Read more about I/O scheduling: https://wiki.archlinux.org/index.php/Improving_p
 
 		else
 
-			TARGETMENUID=0 # Exit
+			TARGETMENUID=0 # Main menu
 
 		fi
 
 	}
 
+	# TARGETMENUID=2
 	Menu_Format(){
 
 		FORMAT_COMPLETED=0
@@ -1610,8 +1605,7 @@ Read more about I/O scheduling: https://wiki.archlinux.org/index.php/Improving_p
 
 			if [[ $G_WHIP_RETURNED_VALUE == 'Partition Type' ]]; then
 
-				G_WHIP_BUTTON_OK_TEXT='MBR'
-				G_WHIP_BUTTON_CANCEL_TEXT='GPT'
+				G_WHIP_BUTTON_OK_TEXT='MBR' G_WHIP_BUTTON_CANCEL_TEXT='GPT'
 				G_WHIP_YESNO 'Would you like to use GPT or MBR parition table?\n - GPT is required for 2TB+ drives\n - MBR does NOT support 2TB+ drives\n\nIf unsure, select GPT (default)' && FORMAT_GPT=0 || FORMAT_GPT=1
 
 			elif [[ $G_WHIP_RETURNED_VALUE == 'Format Mode' ]]; then
@@ -1696,13 +1690,13 @@ NB: If you are planning to dedicate the drive to this system, it is recommended 
 			elif [[ $G_WHIP_RETURNED_VALUE == 'Format' ]]; then
 
 				Run_Format
-				TARGETMENUID=1
+				TARGETMENUID=1 # Drive menu
 
 			fi
 
 		else
 
-			TARGETMENUID=1
+			TARGETMENUID=1 # Drive menu
 
 		fi
 
@@ -1772,7 +1766,7 @@ NB: If you are planning to dedicate the drive to this system, it is recommended 
 
 				MENU_DRIVE_TARGET=$samba_fp_mount_target
 				Init_Drives_and_Refresh
-				TARGETMENUID=1
+				TARGETMENUID=1 # Drive menu
 
 				G_WHIP_MSG "Mount completed. The new mount can be accessed via:\n - $samba_fp_mount_target\n - CIFS vers=$i"
 				rm $fp_tmp
@@ -1834,7 +1828,7 @@ NB: If you are planning to dedicate the drive to this system, it is recommended 
 
 			MENU_DRIVE_TARGET=$nfs_fp_mount_target
 			Init_Drives_and_Refresh
-			TARGETMENUID=1
+			TARGETMENUID=1 # Drive menu
 
 			G_WHIP_MSG "Mount completed. The new mount can be accessed via:\n - $nfs_fp_mount_target"
 			rm $fp_tmp
@@ -1857,7 +1851,7 @@ NB: If you are planning to dedicate the drive to this system, it is recommended 
 
 				MENU_DRIVE_TARGET=$nfs_fp_mount_target
 				Init_Drives_and_Refresh
-				TARGETMENUID=1
+				TARGETMENUID=1 # Drive menu
 
 				G_WHIP_MSG "Mount completed. The new mount can be accessed via:\n - $nfs_fp_mount_target"
 				rm $fp_tmp
@@ -1875,6 +1869,7 @@ NB: If you are planning to dedicate the drive to this system, it is recommended 
 
 	}
 
+	# TARGETMENUID=3
 	Menu_Add_Network_Drive(){
 
 		G_WHIP_MENU_ARRAY=(
