v8.14
- Network | Mark wireless-regdb as manually installed in any case, so it doesn't get accidentally autoremoved whenever CRDA is uninstalled for another reason
- Network | Use upstream regulatory database in any case from Bullseye on, to be compatible with any non-Debian kernel. The reason for the Debian-only variant is to be found out: https://bugs.debian.org/969897
- Network | When applying a country code, do not restart the network and check back anymore. If CRDA is even still supported by the kernel (otherwise manually applying the country code cannot work), and is not overridden by the kernel's "new" (since Linux 4.15 on Bullseye an up) builtin feature, there are various reasons it can fail or require a WiFi reconnection. This reconnetion is however done when selecting "Apply" for IP settings already.
- DietPi-Set_hardware | wificountrycode: Apply dietpi.txt setting if not input is given. Adjust function to gracefully handle missing CRDA and missing hostapd, just apply to what is there

diff --git a/dietpi/dietpi-config b/dietpi/dietpi-config
--- a/dietpi/dietpi-config
+++ b/dietpi/dietpi-config
@@ -2019,7 +2019,7 @@ Current setting: $user_frequency_min_text" && G_CONFIG_INJECT 'CONFIG_CPU_MIN_FR
 
 		(( $WIFI_DISABLED )) && G_WHIP_BUTTON_CANCEL_TEXT='Skip' G_WHIP_YESNO 'Would you like to purge all WiFi related APT packages?
  \nThis will free up space, but an internet-capable Ethernet connection is required to re-enable WiFi functionality.
- \nAffected packages: iw wireless-tools crda wireless-regdb wpasupplicant' && G_AGP 'iw' 'wireless-tools' 'crda' 'wireless-regdb' 'wpasupplicant'
+ \nAffected packages: iw wireless-tools wpasupplicant wireless-regdb crda' && G_AGP 'iw' 'wireless-tools' 'wpasupplicant' 'wireless-regdb' 'crda'
 
 		# Drop connections
 		G_DIETPI-NOTIFY 2 'Dropping network connections, please wait...'
@@ -2248,8 +2248,8 @@ _EOF_
 
 	}
 
-	Change_WifiCountryCode(){
-
+	Change_WifiCountryCode()
+	{
 		G_WHIP_MENU_ARRAY=(
 
 			'GB' ': Great Britain'
@@ -2262,35 +2262,22 @@ _EOF_
 		)
 
 		G_WHIP_DEFAULT_ITEM=$WIFI_COUNTRYCODE
-		G_WHIP_MENU 'Please select a country, to enable WiFi channels and power ratings allowed in your country.' || return 0
+		G_WHIP_MENU 'Please select your country to enable WiFi channels and power ratings allowed in your region.
+\nNB: Depending on your system, it may be required to disable and re-enable your WiFi connection for the change to take effect, or the kernel may override your choice with the info it gets from the access point. Verify that the correct code is returned by:
+# iw reg get' || return 0
 
 		if [[ $G_WHIP_RETURNED_VALUE == 'Manual' ]]
 		then
+			local error
 			G_WHIP_DEFAULT_ITEM=$WIFI_COUNTRYCODE
-			G_WHIP_INPUTBOX 'Please enter a 2 character country code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2' || return 0
-			[[ $G_WHIP_RETURNED_VALUE == [[:upper:]][[:upper:]] ]] || { G_WHIP_MSG "[FAILED] Invalid country code ($G_WHIP_RETURNED_VALUE). Aborting..."; return 1; }
-		fi
-		local wifi_country_code_target=$G_WHIP_RETURNED_VALUE
-
-		# CRDA is not available from Debian Bookworm on and irrelevant from Linux 4.15 on: https://bugs.debian.org/1003903
-		if [[ -f '/lib/crda/crda' ]]
-		then
-			/boot/dietpi/func/dietpi-set_hardware wificountrycode "$wifi_country_code_target"
-
-			Network_Restart
-
-			# Check if country code was successfully applied
-			WIFI_COUNTRYCODE=$(iw reg get | mawk '/country/{print $2;exit}'); WIFI_COUNTRYCODE=${WIFI_COUNTRYCODE%:}
-			[[ $WIFI_COUNTRYCODE == "$wifi_country_code_target" ]] && return 0
-			G_WHIP_MSG "[FAILED] Country code \"$wifi_country_code_target\" could not be applied.\n\nPlease check the country code and try again.\n\nIf problems persist, this may be a limitation with the driver/chipset."
-			return 1
-		else
-			# Apply for WiFi Hotspot only if CRDA is not available
-			WIFI_COUNTRYCODE=$wifi_country_code_target
-			G_CONFIG_INJECT 'country_code=' "country_code=$WIFI_COUNTRYCODE" /etc/hostapd/hostapd.conf
-			G_CONFIG_INJECT 'AUTO_SETUP_NET_WIFI_COUNTRY_CODE=' "AUTO_SETUP_NET_WIFI_COUNTRY_CODE=$WIFI_COUNTRYCODE" /boot/dietpi.txt
+			until [[ $G_WHIP_RETURNED_VALUE == [[:upper:]][[:upper:]] ]]
+			do
+				G_WHIP_INPUTBOX "${error}Please enter a 2 capital letter country code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2" || return 0
+				error="[FAILED] Invalid country code ($G_WHIP_RETURNED_VALUE)"
+			done
 		fi
 
+		/boot/dietpi/func/dietpi-set_hardware wificountrycode "$G_WHIP_RETURNED_VALUE"
 	}
 
 	Wifi_Reconnect(){
@@ -2855,7 +2842,7 @@ NB: Auto-negotiation is highly recommended as long as you do not have issues wit
 		fi
 
 		G_WHIP_MENU_ARRAY+=('' '●─ Additional Options ')
-		# Country code: Not available from Debian Bookworm on and irrelevant from Linux 4.15 on, aside of for hostapd: https://bugs.debian.org/1003903
+		# Country code: On Debian Bookworm and from Linux 4.15 on, this setting is relevant for the WiFi Hotspot (hostapd) installation only: https://bugs.debian.org/1003903
 		if (( $WIFI_HOTSPOT )) || [[ -f '/lib/crda/crda' ]]
 		then
 			if [[ $WIFI_COUNTRYCODE == '00' ]]
