dietpi-drive_manager: fix benchmark call
dietpi-benchmark runs "dietpi-drive_manager 1" to select the mountpoint to benchmark. This shouldn't be done if the test file path is passed, but it does not hurt to allow concurrent "dietpi-drive_manager 1" calls.

Also remove "dietpi-drive_manager 3", which became a noop now that we do not rewrite /etc/fstab anymore. It is not used anywhere in our scripts. One idea was do use it to auto-mounted drives to /etc/fstab. But those are better not added at all there, keeping them temporary, same with drives manually mounted via "mount".

The main loop has been restructured more logically.

diff --git a/dietpi/dietpi-drive_manager b/dietpi/dietpi-drive_manager
--- a/dietpi/dietpi-drive_manager
+++ b/dietpi/dietpi-drive_manager
@@ -14,15 +14,19 @@
 	# Usage:
 	# - <empty>	= Interactive menu
 	# - 1		= Select an available drive mount which is then saved to: /tmp/dietpi-drive_manager_selmnt
-	# - 3		= Scan for new drives and update fstab non-interactively, then exit
 	# - 4		= Reset /etc/fstab with currently attached local drives and /tmp + /var/log tmpfs mount. Used by: DietPi-Installer
 	#
 	#////////////////////////////////////
+
+	# Grab input
+	# shellcheck disable=SC2015
+	[[ $1 == [14] ]] && readonly INPUT=$1 || readonly INPUT=0
 
 	# Import DietPi-Globals --------------------------------------------------------------
 	. /boot/dietpi/func/dietpi-globals
 	readonly G_PROGRAM_NAME='DietPi-Drive_Manager'
 	G_CHECK_ROOT_USER "$@"
+	[[ $INPUT == 1 ]] && G_INIT_ALLOW_CONCURRENT=1
 	G_INIT
 	# Import DietPi-Globals --------------------------------------------------------------
 
@@ -30,10 +34,6 @@
 	SERVICES_STOPPED=0
 	# shellcheck disable=SC2329
 	G_EXIT_CUSTOM(){ (( $SERVICES_STOPPED )) && /boot/dietpi/dietpi-services start; }
-
-	# Grab input
-	# shellcheck disable=SC2015
-	[[ $1 == [134] ]] && readonly INPUT=$1 || readonly INPUT=0
 
 	EXIT_CODE=0
 
@@ -1653,40 +1653,40 @@ _EOF_
 
 		G_DIETPI-NOTIFY 0 "Drive mount selected: $G_WHIP_RETURNED_VALUE"
 		echo "$G_WHIP_RETURNED_VALUE" > "$fp_mount_selection"
-		exit 0
 	}
 
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Main Loop
 	#/////////////////////////////////////////////////////////////////////////////////////
-	# Mode 1: Select an active mount and return value, exits from within function
-	(( $INPUT == 1 )) && Menu_Select_Mount_Location
-	#-----------------------------------------------------------------------------------
-	# Offer to do a reboot if required as of missing kernel modules and not called for resetting fstab from DietPi-Installer
-	if (( $INPUT != 4 )) && ! G_CHECK_KERNEL
-	then
-		G_WHIP_BUTTON_CANCEL_TEXT='Skip' G_WHIP_YESNO "[ INFO ] A reboot is recommended
+	case $INPUT in
+		1) Menu_Select_Mount_Location;; # Select an active mount and return value
+		4) Init_Drives_and_Refresh;; # Force fstab reset and exit (DietPi-Installer)
+		*)
+			# Offer to do a reboot if required as of missing kernel modules and not called for resetting fstab from DietPi-Installer
+			if ! G_CHECK_KERNEL
+			then
+				G_WHIP_BUTTON_CANCEL_TEXT='Skip' G_WHIP_YESNO "[ INFO ] A reboot is recommended
 \nKernel modules for the loaded kernel at /lib/modules/$(uname -r) are missing. This is most likely the case as of a recently applied kernel upgrade where a reboot is required to load the new kernel.
 \nWe recommend to perform a reboot now for the system to be able to load kernel modules, like filesystem drivers, ondemand. If your kernel does not use dedicated modules, please create the mentioned directory manually to mute this info in the future.
 \nDo you want to reboot now?" && { reboot; exit 0; }
-	fi
-	#-----------------------------------------------------------------------------------
-	# Init drives, update /etc/fstab for current physical drive mounts
-	Init_Drives_and_Refresh
-	#-----------------------------------------------------------------------------------
-	# Mode 3: Scan for new drives, update fstab and exit
-	# Mode 4: Force fstab reset and exit (DietPi-Installer)
-	# Else  : Run menus
-	[[ $INPUT == [34] ]] || until (( $TARGETMENUID < 0 ))
-	do
-		case $TARGETMENUID in
-			1) Menu_Drive;;
-			2) Menu_Format;;
-			3) Menu_Add_Network_Drive;;
-			*) Menu_Main;;
-		esac
-	done
-	#-----------------------------------------------------------------------------------
+			fi
+
+			# Init drives, update /etc/fstab for current physical drive mounts
+			Init_Drives_and_Refresh
+
+			# Run menus
+			until (( $TARGETMENUID < 0 ))
+			do
+				case $TARGETMENUID in
+					1) Menu_Drive;;
+					2) Menu_Format;;
+					3) Menu_Add_Network_Drive;;
+					*) Menu_Main;;
+				esac
+			done
+		;;
+	esac
+	#-------------------------------------------------------------------------------------
 	exit "$EXIT_CODE"
-	#-----------------------------------------------------------------------------------
+	#-------------------------------------------------------------------------------------
 }
