v7.9
+ DietPi-Software | Add a dependant loop when unmarking conflicts, so that all dependants and in case their dependants are unmarked as well. Currently there is no actual case where this is required, but it doesn't hurt to be failsafe.

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -2058,12 +2058,30 @@ INDEX_BROWSER=$INDEX_BROWSER"
 		fi
 	}
 
+	# Unmark all dependants of a software title
+	# $1: software ID
+	Unmark_Dependants()
+	{
+		aSOFTWARE_INSTALL_STATE[$1]=0
+		local i
+		for i in "${!aSOFTWARE_NAME[@]}"
+		do
+			# NB: This does not work for dependencies given as "webserver", "desktop" or "browser". However, there are no conflicts among desktops and browser, and webservers only conflict with other webservers, hence obviously one is installed already which satisfies the dependency.
+			[[ ${aSOFTWARE_INSTALL_STATE[$i]} == 1 && ${aSOFTWARE_DEPS[$i]} =~ (^|[[:blank:]])$1([[:blank:]]|$) ]] || continue
+			aSOFTWARE_INSTALL_STATE[$i]=0
+			[[ $dependants_text ]] || dependants_text='\n\nThe following dependants will be unmarked as well:'
+			dependants_text+="\n\n - ${aSOFTWARE_NAME[$i]}: It depends on ${aSOFTWARE_NAME[$1]}."
+			# Recursive call to unmark all dependants of this dependant
+			Unmark_Dependants "$i"
+		fi
+	}
+
 	# Unmark conflicting software titles
 	CONFLICTS_RESOLVED=0
 	Unmark_Conflicts()
 	{
 		# Loop through marked software
-		local i j unmarked_text
+		local i j unmarked_text dependants_text
 		for i in "${!aSOFTWARE_NAME[@]}"
 		do
 			(( ${aSOFTWARE_INSTALL_STATE[$i]} == 1 )) || continue
@@ -2074,14 +2092,15 @@ INDEX_BROWSER=$INDEX_BROWSER"
 				(( ${aSOFTWARE_INSTALL_STATE[$j]} > 0 )) || continue
 
 				# At least one conflict is installed or marked: Unmark software
-				(( ${aSOFTWARE_INSTALL_STATE[$i]} == 1 )) && aSOFTWARE_INSTALL_STATE[$i]=0 unmarked_text+="\n\n${aSOFTWARE_NAME[$i]} install will be skipped as it conflicts with:"
+				(( ${aSOFTWARE_INSTALL_STATE[$i]} == 1 )) && { unmarked_text+="\n\n${aSOFTWARE_NAME[$i]} won't be installed, as it conflicts with:"; Unmark_Dependants "$i"; }
 
 				# Unmark all marked conflicts
 				if (( ${aSOFTWARE_INSTALL_STATE[$j]} == 1 ))
 				then
-					aSOFTWARE_INSTALL_STATE[$j]=0 unmarked_text+="\n - the newly selected ${aSOFTWARE_NAME[$j]} which will be deselected as well"
+					unmarked_text+="\n\n - ${aSOFTWARE_NAME[$j]}: It won't be installed either."
+					Unmark_Dependants "$j"
 				else
-					unmarked_text+="\n - the already installed ${aSOFTWARE_NAME[$j]} which remains installed"
+					unmarked_text+="\n\n - ${aSOFTWARE_NAME[$j]}: It is installed already."
 				fi
 			done
 		done
@@ -2090,10 +2109,10 @@ INDEX_BROWSER=$INDEX_BROWSER"
 		[[ $unmarked_text ]] || return 0
 
 		# Conflicts have been unmarked: Inform user!
-		G_WHIP_MSG "[WARNING] Conflicting installs have been detected!$unmarked_text"
+		G_WHIP_MSG "[WARNING] Conflicting installs have been detected!$unmarked_text$dependants_text"
 	}
 
-	# $1 : software ID
+	# $1: software ID
 	Resolve_Dependencies(){
 
 		# Loop through dependencies
@@ -2568,7 +2587,7 @@ _EOF_
 		# Validate input
 		# - User name needs to be given
 		G_EXEC_DESC="Verifying user \"${user:-<missing!>}\" to run ${aSOFTWARE_NAME[$software_id]}" G_EXEC test "$user"
-		# - Pre-create given primary group as useradd and usermod fail if it does not exist
+		# - Pre-create given primary group, as useradd and usermod fail if it does not exist
 		[[ $group_primary ]] && ! getent group "$group_primary" > /dev/null && G_EXEC groupadd -r "$group_primary"
 		# - Only add to supplementary groups that do exist
 		local group groups
