v8.6 (#5567)
- DietPi-Software | ZeroTier: The free easy to deploy cloud-hosted VPN service has been added to the DietPi software catalogue. Many thanks to @AAS-Crypt for implementing this software option: https://github.com/MichaIng/DietPi/pull/5567
- DietPi-Software | Jellyfin: Avoid doubled service stop when waiting for config file and do not wait for config file if we do not touch it anyway

Co-authored-by: MichaIng <micha@dietpi.com>

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -1407,6 +1407,12 @@ Available commands:
 		aSOFTWARE_DESC[$software_id]='Zero config VPN'
 		aSOFTWARE_CATX[$software_id]=15
 		aSOFTWARE_DOCS[$software_id]='https://dietpi.com/docs/software/vpn/#tailscale'
+		#-----------------
+		software_id=201
+		aSOFTWARE_NAME[$software_id]='ZeroTier'
+		aSOFTWARE_DESC[$software_id]='Free easy to deploy cloud-hosted VPN service'
+		aSOFTWARE_CATX[$software_id]=15
+		aSOFTWARE_DOCS[$software_id]='https://dietpi.com/docs/software/vpn/#zerotier'
 
 		# Advanced Networking
 		#--------------------------------------------------------------------------------
@@ -2480,12 +2486,12 @@ _EOF_
 	# Start a service and wait for a default config file to be created.
 	Create_Config()
 	{
-		local file=$1 service=$2
-		local timeout=${3:-25} # Optional
+		local file=$1 service=$2 # Config file path and service name
+		local timeout=${3:-25} # Optional [s]
 		local output=$4 pid # Optional, if timeout is set, hence for startups which may take long so that showing some process becomes reasonable
 		# shellcheck disable=SC2154
-		local content=$CREATE_CONFIG_CONTENT # Optional
-		unset -v CREATE_CONFIG_CONTENT
+		local content=$CREATE_CONFIG_CONTENT stop=$CC_STOP # Optional required config file content and whether to stop service afterwards (!= 0)
+		unset -v CREATE_CONFIG_CONTENT CC_STOP
 
 		# If file exists already and contains required content, continue install
 		[[ -f $file ]] && { [[ ! $content ]] || grep -q "$content" "$file"; } && return 0
@@ -2512,9 +2518,12 @@ _EOF_
 		[[ $output ]] && { kill "$pid"; wait "$pid"; } 2> /dev/null
 
 		# Stop service
-		G_SLEEP 1
-		G_EXEC_NOHALT=1 G_EXEC systemctl stop "$service"
-		G_SLEEP 1
+		if [[ $stop != 0 ]]
+		then
+			G_SLEEP 1
+			G_EXEC_NOHALT=1 G_EXEC systemctl stop "$service"
+			G_SLEEP 1
+		fi
 
 		# If file exists already and contains required content, continue install
 		if [[ -f $file ]] && { [[ ! $content ]] || grep -q "$content" "$file"; }
@@ -7633,10 +7642,10 @@ case "$1" in
 		fi
 	;;
 
-        *)
-                echo "[FAILED] Invalid command ($1), please use \"start\" or \"stop\""
-                exit 1
-        ;;
+	*)
+		echo "[FAILED] Invalid command ($1), please use \"start\" or \"stop\""
+		exit 1
+	;;
 
 esac
 
@@ -8230,6 +8239,28 @@ _EOF_
 			G_EXEC_OUTPUT=1 G_EXEC_NOEXIT=1 G_EXEC ./install.bash "${options[@]}" || aSOFTWARE_INSTALL_STATE[$software_id]=0
 			G_EXEC_NOHALT=1 G_EXEC rm install.bash
 			[[ -f '/boot/unattended_pivpn.conf' ]] && G_EXEC_NOHALT=1 G_EXEC mv /boot/unattended_pivpn.conf{,.applied}
+
+		fi
+
+		software_id=201 # ZeroTier
+		if (( ${aSOFTWARE_INSTALL_STATE[$software_id]} == 1 )); then
+
+			Banner_Installing
+
+			# APT key: Download from GitHub instead of https://download.zerotier.com/contact%40zerotier.com.gpg for enhanced protection against corrupted download server
+			G_EXEC eval 'curl -sSLf '\''https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg'\'' | gpg --dearmor -o /etc/apt/trusted.gpg.d/dietpi-zerotier.gpg --yes'
+
+			# APT list
+			G_EXEC eval "echo 'deb https://download.zerotier.com/debian/$G_DISTRO_NAME/ $G_DISTRO_NAME main' > /etc/apt/sources.list.d/dietpi-zerotier.list"
+			G_AGUP
+
+			# APT package
+			G_AGI zerotier-one
+
+			Remove_SysV zerotier-one
+
+			# Wait for and print ZeroTier address
+			CC_STOP=0 Create_Config '/var/lib/zerotier-one/identity.secret' 'zerotier-one' && G_DIETPI-NOTIFY 0 "Your ZeroTier address is: $(mawk -F: '{print $1}' /var/lib/zerotier-one/identity.public)"
 
 		fi
 
@@ -11710,8 +11741,12 @@ _EOF_
 
 			# APT meta package: Server, web component and FFmpeg implementation
 			G_AGI jellyfin
-			[[ -f '/etc/jellyfin/network.xml' ]] || CREATE_CONFIG_CONTENT='AddPeopleQueryIndex' Create_Config '/etc/jellyfin/migrations.xml' jellyfin 60
-			G_EXEC systemctl stop jellyfin
+			if [[ -d '/mnt/dietpi_userdata/jellyfin' || -f '/etc/jellyfin/network.xml' ]]
+			then
+				G_EXEC systemctl stop jellyfin
+			else
+				CREATE_CONFIG_CONTENT='AddPeopleQueryIndex' Create_Config '/etc/jellyfin/migrations.xml' jellyfin 60
+			fi
 
 			# Grant dietpi group permissions and assure video access
 			Create_User -G dietpi,video,render -d /mnt/dietpi_userdata/jellyfin jellyfin
@@ -14372,6 +14407,17 @@ If no WireGuard (auto)start is included, but you require it, please do the follo
 			getent passwd pivpn > /dev/null && G_EXEC userdel pivpn
 			getent group pivpn > /dev/null && G_EXEC groupdel pivpn
 			[[ -f '/etc/apt/sources.list.d/swupdate.openvpn.net.list' ]] && G_EXEC rm /etc/apt/sources.list.d/swupdate.openvpn.net.list # Not part of current installer anymore
+
+		fi
+
+		software_id=201 # ZeroTier
+		if (( ${aSOFTWARE_INSTALL_STATE[$software_id]} == -1 )); then
+
+			Banner_Uninstalling
+			G_AGP zerotier-one
+			[[ -f '/etc/apt/sources.list.d/dietpi-zerotier.list' ]] && G_EXEC rm /etc/apt/sources.list.d/dietpi-zerotier.list
+			[[ -f '/etc/apt/trusted.gpg.d/dietpi-zerotier.gpg' ]] && G_EXEC rm /etc/apt/trusted.gpg.d/dietpi-zerotier.gpg
+			[[ -d '/var/lib/zerotier-one' ]] && G_EXEC rm -R /var/lib/zerotier-one
 
 		fi
 
