v104

diff --git a/dietpi/dietpi-cloudshell b/dietpi/dietpi-cloudshell
--- a/dietpi/dietpi-cloudshell
+++ b/dietpi/dietpi-cloudshell
@@ -9,14 +9,12 @@
 	#////////////////////////////////////
 	#
 	# Info:
-	# - Lightweight System stats for your Cloudshell or monitor/terminal
+	# - System Stats for Cloudshell (or monitor/terminal)
 	#
 	# Usage:
-	# - setsid sh -c 'exec /DietPi/dietpi/dietpi-cloudshell 0' &> /dev/tty1
-	# dietpi-cloudshell 0/no input	= Menu
-	# dietpi-cloudshell 1			= Run + Intro
-	# dietpi-cloudshell 2			= Run
-	#
+	# dietpi-cloudshell				= Config Menu
+	# dietpi-cloudshell 1			= Run
+	# dietpi-cloudshell 2			= Run + Skip intro
 	#////////////////////////////////////
 
 	#Grab Input (valid interger)
@@ -25,19 +23,11 @@
 		INPUT=$1
 	fi
 
-	#PIDfile
-	PID_FILE="/run/dietpi-cloudshell.pid"
-	if (( $INPUT != 0 )); then
-		echo $$ > $PID_FILE
-	fi
-
-	#Obtain hwmodel from dietpi system
 	HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)
-
 	CPU_CORES=$(nproc --all)
 
 	#Version
-	DIETPI_CLOUDSHELL_VERSION=3
+	DIETPI_CLOUDSHELL_VERSION=4
 
 	#/tmp/.* files used throughout this script.
 	FP_TEMP="/tmp/dietpi-cloudshell"
@@ -135,6 +125,18 @@
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Obtain Data
 	#/////////////////////////////////////////////////////////////////////////////////////
+	TEMPERATURE_CONVERSION_VALUE=0
+	Obtain_Temperature_Conversion(){
+
+		if (( $TEMPERATURE_OUTPUT_TYPE == 0 )); then
+			TEMPERATURE_CONVERSION_VALUE=$(awk "BEGIN {printf \"%.0f\",$TEMPERATURE_CONVERSION_VALUE * 1.8 + 32"})
+			TEMPERATURE_CONVERSION_VALUE+="'f"
+		else
+			TEMPERATURE_CONVERSION_VALUE+="'c"
+		fi
+
+	}
+
 	DATE_TIME=0
 	Obtain_DATE_TIME(){
 
@@ -197,6 +199,11 @@
 			C_CPUTEMP=${aCOLOUR[4]}
 		fi
 
+		#Set 'c or 'f output
+		TEMPERATURE_CONVERSION_VALUE=$CPU_TEMP
+		Obtain_Temperature_Conversion
+		CPU_TEMP=$TEMPERATURE_CONVERSION_VALUE
+
 		CPU_FREQ_1=$(( $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq) / 1000 ))
 		CPU_FREQ_2="N/A"
 
@@ -208,12 +215,11 @@
 		CPU_USAGE=0
 		FP_TEMP="/tmp/.cpu_usage"
 
-		ps -xo %cpu | sed '1d' > "$FP_TEMP"
+		ps -xo %cpu | sed '1d' | sed 's/ //' > "$FP_TEMP"
 		while read -r line
 		do
-			CPU_USAGE=$(echo | awk "{print $CPU_USAGE + $line}")
+			CPU_USAGE=$(awk "BEGIN {printf \"%.2f\",$CPU_USAGE + $line"})
 		done < $FP_TEMP
-		rm $FP_TEMP
 
 		#ps returns usage of each core, so we devide the total by #n cores
 		CPU_USAGE=$(echo | awk "{print $CPU_USAGE / $CPU_CORES}")
@@ -265,7 +271,6 @@
 			STORAGE_USB_PERCENT=" Not installed."
 		fi
 
-		rm $FP_TEMP
 	}
 
 	#DietPi
@@ -344,8 +349,6 @@
 			NETWORK_DETAILS_SIGNAL_STRENGTH="N/A"
 		fi
 
-		rm $FP_TEMP
-
 	}
 
 	#Network Usage (MB)
@@ -416,8 +419,6 @@
 		Percent_To_Graph $(printf %.0f $MEMORY_SWAPERCENT)
 		MEMORY_SWAPERCENT=$C_PERCENT_GRAPH
 
-		rm $FP_TEMP
-
 	}
 
 	#PI-HOLE STATS!
@@ -482,6 +483,9 @@
 	#Refresh rate (every X seconds)
 	REFRESH_RATE=5
 
+	#0='f | 1='c
+	TEMPERATURE_OUTPUT_TYPE=1
+
 	#Enabled Scenes
 	aEnabledScenes=()
 	for ((i=0; i<$SCENE_HARDLIMIT; i++))
@@ -498,7 +502,7 @@
 	   #'--------------------------'
 		clear
 
-		local -a aAnimation=(
+		local aAnimation=(
 			'                          '
 			'i         -              c'
 			'P  i      -            c l'
@@ -514,7 +518,7 @@
 			'    DietPi-cloudshell     '
 		)
 
-		local -a aBar=(
+		local aBar=(
 			' '
 			'  '
 			'    '
@@ -545,7 +549,7 @@
 			echo -e "       Loading..."
 			echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE${aBar[$i]}"
 
-			sleep 0.27
+			sleep 0.2
 		done
 
 		#delete[] array
@@ -597,7 +601,7 @@
 		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE CPU Usage:               "
 		echo -e "$C_RESET$CPU_USAGE"
 		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE CPU Stats:               "
-		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Temp      ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $C_CPUTEMP$CPU_TEMP'c"
+		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Temp      ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $C_CPUTEMP$CPU_TEMP"
 		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Processes ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $CPU_TOTALPROCESSES"
 		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Governor  ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $CPU_GOV"
 
@@ -758,6 +762,7 @@
 		REFRESH_RATE=$(sed -n 1p $FILEPATH_SETTINGS)
 		USER_COLOUR_INDEX=$(sed -n 2p $FILEPATH_SETTINGS)
 		STORAGE_USB_PATH=$(sed -n 3p $FILEPATH_SETTINGS)
+		TEMPERATURE_OUTPUT_TYPE=$(sed -n 4p $FILEPATH_SETTINGS)
 
 		#10-19	Enabled Scenes
 		local sed_index=11
@@ -775,7 +780,7 @@
 		echo -e "$REFRESH_RATE" > $FILEPATH_SETTINGS
 		echo -e "$USER_COLOUR_INDEX" >> $FILEPATH_SETTINGS
 		echo -e "$STORAGE_USB_PATH" >> $FILEPATH_SETTINGS
-		echo -e "" >> $FILEPATH_SETTINGS
+		echo -e "$TEMPERATURE_OUTPUT_TYPE" >> $FILEPATH_SETTINGS
 		echo -e "" >> $FILEPATH_SETTINGS
 		echo -e "" >> $FILEPATH_SETTINGS
 		echo -e "" >> $FILEPATH_SETTINGS
@@ -842,69 +847,62 @@
 
 		fi
 
-		#--------------------------------------------------------------------------------
-		#Start Display system if we are not running menu.
-		if (( $INPUT != 0 )); then
+	}
 
-			#prevent sleep - moved to login
-			#set font - moved to login
-			#Disable Cursor - moved to login
+	#/////////////////////////////////////////////////////////////////////////////////////
+	# Start/Stop Control for Menu
+	#/////////////////////////////////////////////////////////////////////////////////////
+	#-1=none 0=tty1 1=current
+	OUTPUT_TO=-1
 
-			#Start Intro
-			if (( $RUN_INTRO == 1 )); then
-				Run_Intro
-			fi
+	Stop(){
 
-			#Set Nice to +10 (not critical)
-			renice -n 10 $$ &> /dev/null
+		#Kill all , excluding Menu.
+		ps ax | grep '[d]ietpi-cloudshell [1-9]' | awk '{print $1}' > "$FP_TEMP"
+		while read -r line
+		do
+			kill $line &> /dev/null
+		done < $FP_TEMP
+
+		#Reset screens
+		clear
+		clear &> /dev/tty1
+		setfont /usr/share/consolefonts/Lat7-Terminus16 &> /dev/tty1
+		#Cursor
+		tput reset &> /dev/tty1
+
+	}
+
+	Start(){
+
+		#Start tty1
+		if (( $OUTPUT_TO == 0 )); then
+
+			#setterm -blank 0 -powersave off &> /dev/tty1 #Doesnt work &> /dev/tty1. Must be run from tty1.
+			setfont /usr/share/consolefonts/Lat7-TerminusBold24x12.psf &> /dev/tty1
+			#Cursor
+			tput civis &> /dev/tty1
+
+			/DietPi/dietpi/dietpi-cloudshell 1 &> /dev/tty1 &
+			sleep 0.1
+
+		#start current screen
+		elif (( $OUTPUT_TO == 1 )); then
+
+			#Inform user to press CTRL+C to exit
+			echo -e ""
+			read -p "Use CTRL+C to exit. Press any key to continue..."
+			/DietPi/dietpi/dietpi-cloudshell 1
+
 		fi
 
 	}
 
-	#Unused function (contains code to restart / test dietpi-cloudshell)
-	Test(){
-
-		#Commands to restart DietPi-Cloudshell
-		killall -w dietpi-cloudshell
-		/DietPi/dietpi/dietpi-cloudshell 0 &> /dev/tty1 &
-
-		#Reset Config
-		rm /DietPi/dietpi/.dietpi-cloudshell
-		killall -w dietpi-cloudshell
-		/DietPi/dietpi/dietpi-cloudshell 0 &> /dev/tty1 &
-
-		#test non-dietpi system
-		mv /DietPi/dietpi.txt /DietPi/dietpi.bak
-		killall -w dietpi-cloudshell
-		/DietPi/dietpi/dietpi-cloudshell 0 &> /dev/tty1 &
-		mv /DietPi/dietpi.bak /DietPi/dietpi.txt
-
-		#Launch in current screen/terminal
-		killall -w dietpi-cloudshell
-		/DietPi/dietpi/dietpi-cloudshell 1
-		#/DietPi/dietpi/dietpi-cloudshell 0
-
-	}
-
-	#/////////////////////////////////////////////////////////////////////////////////////
-	# Apply new Config
-	#/////////////////////////////////////////////////////////////////////////////////////
-	#Applies new config file and restarts DietPi-Cloudshell on tty1
-	Apply_Config(){
-
-		#kill current dietpi-cloudshell display process
-		if [ -f "$PID_FILE" ]; then
-			kill $(cat "$PID_FILE") &> /dev/null
-		fi
-
+	#Save settings and restart
+	Restart(){
 		Write_Settings_File
-
-		#Start her up
-		#/DietPi/dietpi/dietpi-cloudshell 1 &> /dev/tty1 &
-		#Start her up (no intro)
-		/DietPi/dietpi/dietpi-cloudshell 2 &> /dev/tty1 &
-		sleep 0.1
-
+		Stop
+		Start
 	}
 
 	#/////////////////////////////////////////////////////////////////////////////////////
@@ -915,6 +913,7 @@
 	WHIP_QUESTION=0
 	CHOICE=0
 	TARGETMENUID=0
+	LASTSELECTED_ITEM=""
 
 	Menu_Exit(){
 			WHIP_TITLE='Exit DietPi-Cloudshell?'
@@ -937,14 +936,45 @@
 		WHIP_TITLE='- DietPi-Cloudshell -'
 		WHIP_QUESTION='Configure DietPi-Cloudshell'
 
-		OPTION=$(whiptail --title "$WHIP_TITLE" --backtitle "$WHIP_BACKTITLE" --menu "$WHIP_QUESTION" --cancel-button "Exit" 10 60 3 \
-		"Colour" "Change the colour scheme." \
-		"Update Rate" "Control the time between screen updates." \
-		"Scenes" "Toggle which scenes are shown."  3>&1 1>&2 2>&3)
+		local temp_output_text="Fahrenheit"
+		if (( $TEMPERATURE_OUTPUT_TYPE == 1 )); then
+			temp_output_text="Celsius"
+		fi
+
+		OPTION=$(whiptail --title "$WHIP_TITLE" --backtitle "$WHIP_BACKTITLE" --menu "$WHIP_QUESTION" --cancel-button "Exit" --default-item "$LASTSELECTED_ITEM" 15 70 7 \
+		"Colour" "Settings: Change the colour scheme." \
+		"Update Rate" "Settings: Control the time between screen updates." \
+		"Scenes" "Settings: Toggle which scenes are shown." \
+		"Temperature" "Settings: Output = $temp_output_text" \
+		"Start 1" "Launch DietPi-Cloudshell on main monitor." \
+		"Start 2" "Launch DietPi-Cloudshell on current screen/terminal." \
+		"Stop" "Stops DietPi-Cloudshell."  3>&1 1>&2 2>&3)
 
 		CHOICE=$?
 		if (( $CHOICE == 0 )); then
+
+			LASTSELECTED_ITEM="$OPTION"
+
 			case "$OPTION" in
+
+				Temperature)
+					((TEMPERATURE_OUTPUT_TYPE++))
+					if (( $TEMPERATURE_OUTPUT_TYPE > 1 )); then
+						TEMPERATURE_OUTPUT_TYPE=0
+					fi
+					Restart
+				;;
+				"Start 1")
+					OUTPUT_TO=0
+					Restart
+				;;
+				"Start 2")
+					OUTPUT_TO=1
+					Restart
+				;;
+				"Stop")
+					Stop
+				;;
 				Colour)
 					TARGETMENUID=1
 				;;
@@ -990,7 +1020,8 @@
 
 			if (( $OPTION != $USER_COLOUR_INDEX )); then
 				USER_COLOUR_INDEX=$OPTION
-				Apply_Config &> /dev/null
+
+				Restart
 			fi
 
 		else
@@ -1020,7 +1051,8 @@
 
 			if (( $OPTION != $REFRESH_RATE )); then
 				REFRESH_RATE=$OPTION
-				Apply_Config &> /dev/null
+
+				Restart
 			fi
 
 		else
@@ -1085,12 +1117,9 @@
 			done
 
 			#Save
-			Apply_Config
+			Restart
 
 		fi
-
-		#Clean up temp files
-		rm "$FP_TEMP" &> /dev/null
 
 		#Delete[] array
 		unset aWhiptailLine
@@ -1104,16 +1133,16 @@
 	#Init
 	Init
 	#-----------------------------------------------------------------------------------
-	#Run config menu
+	#Run menu
 	if (( $INPUT == 0 )); then
 
-		#--------------------------------------------------------------------------------------
-		#Start DietPi Menu
+		Read_Settings_File
+
+		#Start Menu
 		while (( $TARGETMENUID > -1 )); do
 
 			clear
 
-			Read_Settings_File
 
 			if (( $TARGETMENUID == 0 )); then
 				Menu_Main
@@ -1126,11 +1155,23 @@
 			fi
 		done
 
+	#-----------------------------------------------------------------------------------
 	#Run DietPi-Cloudshell
 	else
 
-		#-----------------------------------------------------------------------------------
-		#Loop
+		#prevent sleep - moved to login
+		#set font - moved to login
+		#Disable Cursor - moved to login
+
+		#Start Intro
+		if (( $RUN_INTRO == 1 )); then
+			Run_Intro
+		fi
+
+		#Set Nice to +10 (not critical)
+		renice -n 10 $$ &> /dev/null
+
+		#Start display updates
 		while (( $RUN_LOOP == 1 ))
 		do
 
@@ -1156,6 +1197,9 @@
 		done
 	fi
 
+	#-----------------------------------------------------------------------------------
+	#Clean up temp files
+	rm "$FP_TEMP" &> /dev/null
 	#-----------------------------------------------------------------------------------
 	#Delete[] Global arrays
 	unset aCOLOUR
