general: enforce change of default passwords (#7543)
DietPi will now enforce the change of the default user and software passwords for security reasons. This also applies retrospectively during DietPi update, showing a prompt, if one of the two default users or dietpi-software still use the default password. However, the password set in dietpi.txt will now be applied in any case (before it is removed from that file), also without "AUTO_SETUP_AUTOMATED=1", and if it does not equal the default, no further prompt will be shown.

In dietpi-config security options, user and login passwords can now be changed with two separate menu entires.

Password prompts have now a cancel button as long as no default password must be changed.

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -135,39 +135,27 @@ Available commands:
 	GLOBAL_PW=
 	Update_Global_Pw()
 	{
-		local encrypt=0
+		# Loop until password is valid or dietpi-set_software fails
+		while :
+		do
+			# Read encrypted password
+			if [[ -f '/var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin' ]]
+			then
+				# In case of error, assure empty password to fallback to default
+				GLOBAL_PW=$(openssl enc -d -a -md sha256 -aes-256-cbc -iter 10000 -salt -pass pass:'DietPiRocks!' -in /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin) || GLOBAL_PW=
 
-		# Read encrypted password
-		if [[ -f '/var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin' ]]
-		then
-			# In case of error, assure empty password to fallback to default and re-encrypt it
-			GLOBAL_PW=$(openssl enc -d -a -md sha256 -aes-256-cbc -iter 10000 -salt -pass pass:'DietPiRocks!' -in /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin) || encrypt=1 GLOBAL_PW=
+				# Return on valid password
+				[[ $GLOBAL_PW && $GLOBAL_PW != 'dietpi' ]] && return 0
 
-		# If encryption has not yet been done, do it now!
-		else
-			encrypt=1
-			GLOBAL_PW=$(sed -n '/^[[:blank:]]*AUTO_SETUP_GLOBAL_PASSWORD=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
-			grep -q '^[[:blank:]]*AUTO_SETUP_GLOBAL_PASSWORD=' /boot/dietpi.txt && G_EXEC sed --follow-symlinks -i '/^[[:blank:]]*AUTO_SETUP_GLOBAL_PASSWORD=/c\#AUTO_SETUP_GLOBAL_PASSWORD= # Password has been encrypted and saved to rootfs' /boot/dietpi.txt
-		fi
+				G_DIETPI-NOTIFY 1 'Global software password failed to be read, is empty, or still the default. Asking to set a new one ...'
+			fi
 
-		# Fallback
-		if [[ ! $GLOBAL_PW ]]
-		then
-			encrypt=1
-			GLOBAL_PW='dietpi'
-			G_WHIP_MSG "[FAILED] Unable to obtain your global software password
-\nThe following fallback password will be used:\n - $GLOBAL_PW
-\nYou can change it via:\n - dietpi-config > Security Options > Change Passwords"
-		fi
+			# Apply default password as fallback if empty
+			[[ $GLOBAL_PW ]] || GLOBAL_PW='dietpi'
 
-		# Encrypt
-		# https://github.com/koalaman/shellcheck/issues/1009
-		# shellcheck disable=SC2086
-		[[ $encrypt == 1 ]] && openssl enc -e -a -md sha256 -aes-256-cbc -iter 10000 -salt -pass pass:'DietPiRocks!' -out /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin <<< $GLOBAL_PW
-
-		# Apply safe permissions
-		chown 0:0 /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin
-		chmod 0600 /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin
+			# In case ask for and apply new valid password
+			/boot/dietpi/func/dietpi-set_software password software check || return 1
+		done
 	}
 
 	# Total physical system RAM: Used to calculate percentage based value for software cache limits, e.g.: OPcache/APCu
@@ -14359,19 +14347,20 @@ _EOF_
 			SKIP_APT_UPDATE=1
 		fi
 
-		# Global PW
-		# - Automation: Apply from dietpi.txt
-		if (( $AUTOINSTALL_ENABLED ))
+		# Change password if default has not been changed via dietpi.txt
+		# - Non-automated interactive first run setup: Show password prompts
+		if (( ! $AUTOINSTALL_ENABLED && $G_INTERACTIVE ))
 		then
-			Update_Global_Pw
-			# Set again to apply for UNIX users as well
-			/boot/dietpi/func/dietpi-set_software passwords "$GLOBAL_PW"
-
-		# - Prompt to change global software password and login passwords for root and dietpi users
-		else
 			# Local console: Prompt to select keyboard layout first if default is still set: https://github.com/MichaIng/DietPi/issues/5925
 			[[ $(tty) == '/dev/tty1' ]] && grep -q '^XKBLAYOUT="gb"' /etc/default/keyboard && /boot/dietpi/func/dietpi-set_hardware keyboard
-			/boot/dietpi/func/dietpi-set_software passwords
+			/boot/dietpi/func/dietpi-set_software password users check
+			Update_Global_Pw
+
+		# - Automated or non-interactive first run setup
+		else
+			# Update_Global_Pw is always executed right before installs start and in case forces users to change the default on any next interactive execution.
+			# Set flag for dietpi-login to check user passwords to in case enforce a change on next interactive login.
+			G_EXEC touch /var/lib/dietpi/.check_user_passwords
 		fi
 
 		# Disable serial console?
diff --git a/dietpi/func/dietpi-globals b/dietpi/func/dietpi-globals
--- a/dietpi/func/dietpi-globals
+++ b/dietpi/func/dietpi-globals
@@ -657,7 +657,7 @@ $grey─────────────────────────
 		fi
 
 		G_WHIP_DESTROY
-		return "${result:-1}"
+		return "$result"
 	}
 
 	# G_WHIP_YESNO "message"
@@ -678,13 +678,13 @@ $grey─────────────────────────
 		fi
 
 		G_WHIP_DESTROY
-		return "${result:-1}"
+		return "$result"
 	}
 
 	# G_WHIP_INPUTBOX "message"
 	# - Prompt user to input text and save it to G_WHIP_RETURNED_VALUE
 	# - G_WHIP_INPUTBOX_REGEX/G_WHIP_INPUTBOX_REGEX_TEXT: Regular expression and description about allowed input. Defaults to the requirement that the input is not empty.
-	# - Exit code: 0=input done, else=user cancelled or noninteractive
+	# - Exit code: 0=input matches G_WHIP_INPUTBOX_REGEX, else=non-interactive, user cancelled, or whiptail error
 	G_WHIP_INPUTBOX()
 	{
 		local result=1
@@ -700,8 +700,8 @@ $grey─────────────────────────
 			do
 				G_WHIP_INIT
 				# shellcheck disable=SC2086
-				G_WHIP_RETURNED_VALUE=$(whiptail ${G_PROGRAM_NAME:+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --inputbox "$WHIP_ERROR$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" "${NOCANCEL[@]}" $WHIP_SCROLLTEXT "$WHIP_SIZE_Y" "$WHIP_SIZE_X" "$G_WHIP_DEFAULT_ITEM" 3>&1 1>&2 2>&3-; echo $? > /tmp/.G_WHIP_INPUTBOX_RESULT)
-				read -r result < /tmp/.G_WHIP_INPUTBOX_RESULT; rm -f /tmp/.G_WHIP_INPUTBOX_RESULT
+				G_WHIP_RETURNED_VALUE=$(whiptail ${G_PROGRAM_NAME:+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --inputbox "$WHIP_ERROR$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" "${NOCANCEL[@]}" $WHIP_SCROLLTEXT "$WHIP_SIZE_Y" "$WHIP_SIZE_X" "$G_WHIP_DEFAULT_ITEM" 3>&1 1>&2 2>&3-)
+				result=$?
 				[[ $result == 0 && ! $G_WHIP_RETURNED_VALUE =~ $G_WHIP_INPUTBOX_REGEX ]] && { WHIP_ERROR="[FAILED] Input must $G_WHIP_INPUTBOX_REGEX_TEXT, please try again ...\n\n"; continue; }
 				break
 			done
@@ -710,13 +710,13 @@ $grey─────────────────────────
 		fi
 
 		G_WHIP_DESTROY
-		return "${result:-1}"
+		return "$result"
 	}
 
 	# G_WHIP_PASSWORD "message"
 	# - Prompt user to input password and save it in variable "result"
-	# - Originating script must "unset result" after value has been handled for security reasons!
-	# - Exit code: 0=input done + passwords match, else=noninteractive (Cancelling is disabled since no password in originating script can cause havoc!)
+	# - Originating script must "unset -v result" after value has been handled for security reasons!
+	# - Exit code: 0=input matches G_WHIP_INPUTBOX_REGEX and has been confirmed, else=non-interactive, user cancelled, or whiptail error
 	G_WHIP_PASSWORD()
 	{
 		local return_value=1
@@ -724,23 +724,31 @@ $grey─────────────────────────
 
 		if [[ $G_INTERACTIVE == 1 ]]
 		then
-			local WHIP_ERROR WHIP_BACKTITLE WHIP_SCROLLTEXT WHIP_SIZE_X WHIP_SIZE_Y WHIP_MESSAGE=$*
+			local WHIP_ERROR WHIP_BACKTITLE WHIP_SCROLLTEXT WHIP_SIZE_X WHIP_SIZE_Y WHIP_MESSAGE=$* NOCANCEL=() password_0 password_1
+			G_WHIP_INPUTBOX_REGEX=${G_WHIP_INPUTBOX_REGEX:-'.'}
+			G_WHIP_INPUTBOX_REGEX_TEXT=${G_WHIP_INPUTBOX_REGEX_TEXT:-'not be empty'}
+			[[ $G_WHIP_NOCANCEL == 1 ]] && NOCANCEL=('--nocancel')
 			while :
 			do
 				G_WHIP_INIT
 				# shellcheck disable=SC2086
-				local password_0=$(whiptail ${G_PROGRAM_NAME:+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --passwordbox "$WHIP_ERROR$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --nocancel $WHIP_SCROLLTEXT "$WHIP_SIZE_Y" "$WHIP_SIZE_X" 3>&1 1>&2 2>&3-)
-				[[ $password_0 ]] || { WHIP_ERROR='[FAILED] No input made, please try again...\n\n'; continue; }
-				local password_1=$(whiptail ${G_PROGRAM_NAME:+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --passwordbox 'Please retype and confirm your input:' --ok-button "$G_WHIP_BUTTON_OK_TEXT" --nocancel 7 "$WHIP_SIZE_X" 3>&1 1>&2 2>&3-)
+				password_0=$(whiptail ${G_PROGRAM_NAME:+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --passwordbox "$WHIP_ERROR$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" "${NOCANCEL[@]}" $WHIP_SCROLLTEXT "$WHIP_SIZE_Y" "$WHIP_SIZE_X" 3>&1 1>&2 2>&3-)
+				return_value=$?
+				(( $return_value )) && break # Exit loop on error or cancel/ESC
+				# Check regex via grep perl method to allow negative lookahead pattern for password exclusion
+				grep -Pq "$G_WHIP_INPUTBOX_REGEX" <<< "$password_0" || { WHIP_ERROR="[FAILED] Input must $G_WHIP_INPUTBOX_REGEX_TEXT, please try again ...\n\n"; continue; }
+
+				password_1=$(whiptail ${G_PROGRAM_NAME:+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --passwordbox 'Please retype and confirm your input:' --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" "${NOCANCEL[@]}" 7 "$WHIP_SIZE_X" 3>&1 1>&2 2>&3-)
+				return_value=$?
+				(( $return_value )) && break # Exit loop on error or cancel/ESC
 				[[ $password_0 == "$password_1" ]] || { WHIP_ERROR='[FAILED] Inputs do not match, please try again...\n\n'; continue; }
 				result=$password_0
-				return_value=0
 				break
 			done
 		fi
 
 		G_WHIP_DESTROY
-		return "${return_value:-1}"
+		return "$return_value"
 	}
 
 	# G_WHIP_MENU "message"
@@ -760,16 +768,16 @@ $grey─────────────────────────
 			do
 				G_WHIP_INIT 2
 				# shellcheck disable=SC2086
-				G_WHIP_RETURNED_VALUE=$(whiptail ${G_PROGRAM_NAME:+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --menu "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" "${NOCANCEL[@]}" --default-item "$G_WHIP_DEFAULT_ITEM" $WHIP_SCROLLTEXT "$WHIP_SIZE_Y" "$WHIP_SIZE_X" "$WHIP_SIZE_Z" -- "${G_WHIP_MENU_ARRAY[@]}" 3>&1 1>&2 2>&3-; echo $? > /tmp/.WHIP_MENU_RESULT)
-				read -r result < /tmp/.WHIP_MENU_RESULT; rm -f /tmp/.WHIP_MENU_RESULT
-				[[ ${result:=1} == 0 ]] || break # Exit loop in case of cancel button selection or error or if .WHIP_MENU_RESULT could not be created
+				G_WHIP_RETURNED_VALUE=$(whiptail ${G_PROGRAM_NAME:+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE" --menu "$WHIP_MESSAGE" --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" "${NOCANCEL[@]}" --default-item "$G_WHIP_DEFAULT_ITEM" $WHIP_SCROLLTEXT "$WHIP_SIZE_Y" "$WHIP_SIZE_X" "$WHIP_SIZE_Z" -- "${G_WHIP_MENU_ARRAY[@]}" 3>&1 1>&2 2>&3-)
+				result=$?
+				(( $result )) && break # Exit loop on error or cancel/ESC
 			done
 		else
 			G_WHIP_RETURNED_VALUE=$G_WHIP_DEFAULT_ITEM
 		fi
 
 		G_WHIP_DESTROY
-		return "${result:-1}"
+		return "$result"
 	}
 
 	# G_WHIP_CHECKLIST "message"
@@ -787,15 +795,15 @@ $grey─────────────────────────
 			G_WHIP_BUTTON_OK_TEXT=${G_WHIP_BUTTON_OK_TEXT:-Confirm}
 			G_WHIP_INIT 3
 			# shellcheck disable=SC2086
-			G_WHIP_RETURNED_VALUE=$(whiptail ${G_PROGRAM_NAME:+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE | Use spacebar to toggle selection" --checklist "$WHIP_MESSAGE" --separate-output --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" "${NOCANCEL[@]}" --default-item "$G_WHIP_DEFAULT_ITEM" $WHIP_SCROLLTEXT "$WHIP_SIZE_Y" "$WHIP_SIZE_X" "$WHIP_SIZE_Z" -- "${G_WHIP_CHECKLIST_ARRAY[@]}" 3>&1 1>&2 2>&3-; echo $? > /tmp/.WHIP_CHECKLIST_RESULT)
+			G_WHIP_RETURNED_VALUE=$(whiptail ${G_PROGRAM_NAME:+--title "$G_PROGRAM_NAME"} --backtitle "$WHIP_BACKTITLE | Use spacebar to toggle selection" --checklist "$WHIP_MESSAGE" --separate-output --ok-button "$G_WHIP_BUTTON_OK_TEXT" --cancel-button "$G_WHIP_BUTTON_CANCEL_TEXT" "${NOCANCEL[@]}" --default-item "$G_WHIP_DEFAULT_ITEM" $WHIP_SCROLLTEXT "$WHIP_SIZE_Y" "$WHIP_SIZE_X" "$WHIP_SIZE_Z" -- "${G_WHIP_CHECKLIST_ARRAY[@]}" 3>&1 1>&2 2>&3-)
+			result=$?
 			G_WHIP_RETURNED_VALUE=$(echo -e "$G_WHIP_RETURNED_VALUE" | tr '\n' ' ')
-			read -r result < /tmp/.WHIP_CHECKLIST_RESULT; rm -f /tmp/.WHIP_CHECKLIST_RESULT
 		else
 			G_WHIP_RETURNED_VALUE=$G_WHIP_DEFAULT_ITEM
 		fi
 
 		G_WHIP_DESTROY
-		return "${result:-1}"
+		return "$result"
 	}
 
 	# G_BUG_REPORT [-c COMMAND] [-? EXIT_CODE]
