v120
+ MineOS: https://github.com/Fourdee/DietPi/issues/358

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -55,7 +55,7 @@
 	FP_DIETPIAUTOMATION_LOG="/root/DietPi-Automation.log"
 
 	#Used to set user/personal data directories (eg: usbdrive /mnt/usb_1)
-	USERDATA_DIRECTORY="/mnt/dietpi_userdata"
+	USERDATA_DIRECTORY='/mnt/dietpi_userdata'
 
 	#Uninstall temp file
 	UNINSTALL_FILE='/tmp/dietpi_uninstall_list'
@@ -327,6 +327,8 @@ EMBYSERVER=${EMBYSERVER:=0}
 OPENBAZAAR=${OPENBAZAAR:=0}
 PLEXMEDIASERVER=${PLEXMEDIASERVER:=0}
 CUBERITE=${CUBERITE:=0}
+MINEOS=${MINEOS:=0}
+
 
 #Additional Linux Software
 VIMFULL=${VIMFULL:=0}
@@ -2185,6 +2187,42 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 
 		fi
 
+		#MINEOS
+		if (( $MINEOS == 1 )); then
+			INSTALL_DESCRIPTION='MineOS (Minecraft Servers)'
+			Banner_Installing
+
+			#check folder is online
+
+			INSTALL_URL_ADDRESS='http://github.com/hexparrot/mineos-node.git'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+			#Install
+			if (( $? == 0 )); then
+
+				#prereqs
+				apt-get install -y python python3 supervisor rdiff-backup screen
+
+				mkdir -p "$USERDATA_DIRECTORY"/mineos
+				cd "$USERDATA_DIRECTORY"/mineos
+				git clone https://github.com/hexparrot/mineos-node.git minecraft
+
+				cd minecraft
+				git config core.filemode false
+				chmod +x service.js mineos_console.js generate-sslcert.sh webui.js
+
+				npm install
+
+				cd "$HOME"
+
+			else
+				Error_NoConnection_NoInstall
+
+				#Abort failed install
+				MINEOS=0
+			fi
+
+		fi
 
 	}
 
@@ -2343,6 +2381,8 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 			BUILDESSENTIAL=1
 		elif (( $OPENBAZAAR == 1 )); then
 			BUILDESSENTIAL=1
+		elif (( $MINEOS == 1 )); then
+			BUILDESSENTIAL=1
 		fi
 
 		if (( $BUILDESSENTIAL == 1 )); then
@@ -2357,6 +2397,8 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 		if (( $AMPACHE == 1 )); then
 			GITCLIENT=1
 		elif (( $OPENBAZAAR == 1 )); then
+			GITCLIENT=1
+		elif (( $MINEOS == 1 )); then
 			GITCLIENT=1
 		fi
 
@@ -2642,6 +2684,8 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 			ORACLEJAVA=1
 		elif (( $SUBSONIC6 == 1 )); then
 			ORACLEJAVA=1
+		elif (( $MINEOS == 1 )); then
+			ORACLEJAVA=1
 		fi
 
 		if (( $ORACLEJAVA == 1 )); then
@@ -2679,6 +2723,8 @@ _EOF_
 		#Programs that require NODEJS
 		if (( $NETDATA == 1 )); then
 			NODEJS=1
+		elif (( $MINEOS == 1 )); then
+			NODEJS=1
 		fi
 
 		#NODEJS
@@ -2686,8 +2732,8 @@ _EOF_
 			INSTALL_DESCRIPTION='NodeJS - Javascript Runtime'
 			Banner_Installing
 
-			#arm64 (Odroid C2 and PineA64) - Not currently available via nodesource.com
-			if (( ( $HW_MODEL == 12 ) || ( $HW_MODEL >= 40 && $HW_MODEL < 50 ) )); then
+			#arm64 - Not currently available via nodesource.com or https://raw.githubusercontent.com/taaem/nodejs-linux-installer/master/node-install.sh
+			if (( $HW_ARCH == 10 )); then
 
 				#check, is online
 				INSTALL_URL_ADDRESS='http://dietpi.com/downloads/binaries/c2/nodejs_5-1_arm64.deb'
@@ -2714,20 +2760,18 @@ _EOF_
 			else
 
 				#check, is online
-				INSTALL_URL_ADDRESS='https://deb.nodesource.com/setup_5.x'
+				INSTALL_URL_ADDRESS='http://raw.githubusercontent.com/taaem/nodejs-linux-installer/master/node-install.sh'
 				/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
 
 				#Install
 				if (( $? == 0 )); then
 
 					# - Preqs
-					AGI apt-transport-https
+					wget "$INSTALL_URL_ADDRESS" -O node_install.sh
+					chmod +x node_install.sh
+					./node_install.sh
 
-					# - Add repo (use their install script)
-					curl -sL "$INSTALL_URL_ADDRESS" | -E bash -
-
-					# - install
-					AGI nodejs
+					rm node_install.sh
 
 					NODEJS=2
 
@@ -4875,6 +4919,35 @@ systemctl daemon-reload
 
 		fi
 
+		#MINEOS
+		if (( $MINEOS == 1 )); then
+
+			ln -s "$USERDATA_DIRECTORY"/mineos/minecraft/mineos_console.js /usr/local/bin/mineos
+
+			cp "$USERDATA_DIRECTORY"/mineos/minecraft/mineos.conf /etc/mineos.conf
+
+			# - setup SSL cert
+			cd "$USERDATA_DIRECTORY"/mineos/minecraft
+			./generate-sslcert.sh
+
+			# - Supervisor service
+			cp "$USERDATA_DIRECTORY"/mineos/minecraft/init/supervisor_conf /etc/supervisor/conf.d/mineos.conf
+
+			cd "$HOME"
+
+			# - correct the node filepath for supervisor mineos
+			sed -i '/^command=/c\command=/usr/local/bin/node webui.js' /etc/supervisor/conf.d/mineos.conf
+
+			# - Set directory to dietpi_userdata
+			sed -i "/^directory=/c\directory=$USERDATA_DIRECTORY/mineos/minecraft" /etc/supervisor/conf.d/mineos.conf
+
+			supervisorctl reload
+
+
+			MINEOS=2
+
+		fi
+
 	}
 
 	Install_Apply_GPU_Settings(){
@@ -5004,7 +5077,7 @@ systemctl daemon-reload
 
 		#------------------------------------------------------------
 		#Set target user/personal data base directory
-		USERDATA_DIRECTORY="/mnt/dietpi_userdata"
+		USERDATA_DIRECTORY='/mnt/dietpi_userdata'
 
 		mkdir -p "$USERDATA_DIRECTORY" &> /dev/null
 
@@ -5392,8 +5465,8 @@ systemctl daemon-reload
 		if (( $USBDRIVE == 0 )) &&
 			(( $AUTOINSTALL_SKIPUSBDRIVEPROMPT == 0 )); then
 			WHIP_TITLE='Setup USB Dedicated Drive?'
-			WHIP_QUESTION='Will you be using a dedicated USB hard drive with this DietPi installation? \n \n(NOTICE) Your decision now is final and cannot be changed at a later date. DietPi will automatically setup your future software installations to utilize the USB drive instead of MicroSD.\nAs USB hard drives are generally faster than MicroSD, using a USB drive can vastly improve system performance.\n\n This is recommended for: \n - BitTorrent (Store downloads) \n - OwnCloud \n - Kodi (Store Media Files)\n - Hifi (Store Music)'
-			whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --backtitle "$WHIP_BACKTITLE" --defaultno 22 70
+			WHIP_QUESTION='If you choose to setup a dedicated USB drive, DietPi will automatically configure your future software installations to utilize the USB drive for data storage, instead of SD.\nAs USB hard drives can be faster than most SD cards, using a USB drive can vastly improve system performance.\n\nExamples of software, that will benefit from a USB drive: \n - BitTorrent (Store downloads) \n - OwnCloud (Larger data storage)\n - Kodi / Plex / Emby etc (Store Media Files)\n\nWould you like to setup a USB drive now?'
+			whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --backtitle "$WHIP_BACKTITLE" --defaultno 19 70
 			CHOICE=$?
 			if (( $CHOICE == 0 )); then
 
@@ -6539,6 +6612,15 @@ systemctl daemon-reload
 			fi
 		fi
 
+		local mineos_w="off"
+		if (( $MINEOS > 0 )); then
+			mineos_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $MINEOS == 1 )); then
+				MINEOS=0
+			fi
+		fi
+
 		#-----------------------------------------------------------------------------
 		WHIP_TITLE='DietPi Optimized Software Selection'
 
@@ -6567,6 +6649,8 @@ systemctl daemon-reload
 			"" "────Cloud / Backups─────────────────────────" "off" \
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
+			"" "────Gaming──────────────────────────────────" "off" \
+			"MineOS" "Minecraft Servers with web interface" $mineos_w \
 			"" "────Social Media───────────────────────────" "off" \
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
@@ -6640,6 +6724,7 @@ systemctl daemon-reload
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
 			"" "────Gaming──────────────────────────────────" "off" \
 			"Cuberite" "Minecraft Server (C++)" $cuberite_w \
+			"MineOS" "Minecraft Servers with web interface" $mineos_w \
 			"" "────Social Media───────────────────────────" "off" \
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
@@ -6709,6 +6794,7 @@ systemctl daemon-reload
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
 			"" "────Gaming──────────────────────────────────" "off" \
 			"Cuberite" "Minecraft Server (C++)" $cuberite_w \
+			"MineOS" "Minecraft Servers with web interface" $mineos_w \
 			"" "────Social Media───────────────────────────" "off" \
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
@@ -6777,6 +6863,7 @@ systemctl daemon-reload
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
 			"" "────Gaming──────────────────────────────────" "off" \
 			"Cuberite" "Minecraft Server (C++)" $cuberite_w \
+			"MineOS" "Minecraft Servers with web interface" $mineos_w \
 			"" "────Social Media───────────────────────────" "off" \
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
@@ -6860,6 +6947,7 @@ systemctl daemon-reload
 				"" "────Gaming──────────────────────────────────" "off" \
 				"OpenTyrian" "Gaming: A classic retro game, addictive." $opentyrian_w \
 				"Cuberite" "Minecraft Server (C++)" $cuberite_w \
+				"MineOS" "Minecraft Servers with web interface" $mineos_w \
 				"" "────Social Media───────────────────────────" "off" \
 				"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 				"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
@@ -6989,6 +7077,12 @@ systemctl daemon-reload
 		do
 			case $choice in
 
+			MineOS)
+				if (( $MINEOS == 0 )); then
+					MINEOS=1
+					INSTALL_DIETPI_CHOICESMADE=1
+				fi
+			;;
 			Cuberite)
 				if (( $CUBERITE == 0 )); then
 					CUBERITE=1
