v6.15
+ Sync and cleanup: https://github.com/Fourdee/DietPi/issues/2044#issuecomment-417088505

diff --git a/dietpi/dietpi-sync b/dietpi/dietpi-sync
--- a/dietpi/dietpi-sync
+++ b/dietpi/dietpi-sync
@@ -460,8 +460,8 @@
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Sync System
 	#/////////////////////////////////////////////////////////////////////////////////////
-	#LOGFILE
-	LOGFILE='/var/log/dietpi-sync.log'
+	EXIT_CODE=0
+	FP_LOG='/var/log/dietpi-sync.log'
 
 	#Sync Filepaths
 	FP_SOURCE='/mnt/Source'
@@ -501,7 +501,7 @@
 		echo -e "/run/*" >> $FP_EXCLUDE_GLOBAL
 
 		#Global - Files
-		echo -e "$LOGFILE" >> $FP_EXCLUDE_GLOBAL
+		echo -e $FP_LOG >> $FP_EXCLUDE_GLOBAL
 		echo -e $FP_DIETPISYNC_SETTINGS >> $FP_EXCLUDE_GLOBAL
 		echo -e "$FP_EXCLUDE_USER" >> $FP_EXCLUDE_GLOBAL
 		echo -e "$FP_INCLUDE_USER" >> $FP_EXCLUDE_GLOBAL
@@ -589,38 +589,42 @@
 			Create_Exclude_File
 			Create_Include_File
 
-			#Archive mode
+			#Rsync options
+			# - Archive mode
 			local rync_options='-a'
-			#verbose
+			# - verbose
 			rync_options+='v'
-			#Keep partial files + Progress. (eg: if file is interupted, it will resume where it left off, rather than resending the whole file.
+			# - Keep partial files + Progress. (eg: if file is interupted, it will resume where it left off, rather than resending the whole file.
 			rync_options+='P'
-			#Prefer IPv4
+			# - Prefer IPv4
 			rync_options+='4'
 
-			#Compression?
+			# - Compression?
 			if (( $SYNC_COMPRESSION )); then
 
 				rync_options+='z'
 
 			fi
 
-			#Dry Run?
+			# - Dry Run?
 			if (( $SYNC_DRY_RUN )); then
 
 				rync_options+='n'
 
 			fi
 
-			#Delete mode?
+			# - Delete mode?
 			if (( $SYNC_DELETE_MODE )); then
 
 				rync_options+=' --delete'
 
 			fi
 
-			#Write new logfile
-			echo -e "DietPi-Sync Log File.\n$(date +%d-%m-%Y_%H%M)\nSYNC_DRY_RUN=$SYNC_DRY_RUN\n\n" > "$LOGFILE"
+			# - Add progress info for user
+			rync_options+=' --info=name0 --info=progress2 --human-readable'
+
+			# - Add final options
+			rync_options+=" --log-file=$FP_LOG --exclude-from=$FP_EXCLUDE_GLOBAL --include-from=$FP_INCLUDE_GLOBAL"
 
 			#Verify enough space
 			#	NB: working in KiB until end MiB conversion, as, don't like using long long int, and, KiB should offer a good end result.
@@ -650,20 +654,30 @@
 			fi
 
 			#Sync
-			G_RUN_CMD rsync $rync_options --log-file=$LOGFILE --exclude-from=$FP_EXCLUDE_GLOBAL --include-from=$FP_INCLUDE_GLOBAL "$FP_SOURCE"/ "$FP_TARGET"/
-			echo -e "Sync completed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$SYNC_STATS_FILENAME"
+			rsync $rync_options "$FP_SOURCE"/ "$FP_TARGET"/
+			EXIT_CODE=$?
+			G_DIETPI-NOTIFY -1 $EXIT_CODE "$G_PROGRAM_NAME"
+			if (( $EXIT_CODE == 0 )); then
 
-			if (( ! $SYNC_DRY_RUN )); then
+				echo -e "Sync completed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$SYNC_STATS_FILENAME"
+				if (( ! $SYNC_DRY_RUN )); then
 
-				G_WHIP_MSG "Sync completed:\n\n$FP_SOURCE\n\nHas been synced to:\n$FP_TARGET\n\nLog file: $LOGFILE"
+					G_WHIP_MSG "Sync completed:\n - $FP_SOURCE > $FP_TARGET"
+
+				else
+
+					G_WHIP_MSG "Dry Run Sync completed (NO modifications):\n - $FP_SOURCE > $FP_TARGET"
+
+				fi
 
 			else
 
-				G_WHIP_MSG "Dry Run Sync completed:\n\n$FP_SOURCE\n\nHas been synced with a Dry Run (NO modifications) to:\n$FP_TARGET\n\nLog file: $LOGFILE"
+				echo -e "Sync failed: please see the log file for more information ($FP_LOG): $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$SYNC_STATS_FILENAME"
+				G_WHIP_MSG "Sync failed:\n - $FP_SOURCE > $FP_TARGET\n\nYou will given an option to view the logfile on the next screen. Please check it for information and/or errors."
 
 			fi
 
-			G_WHIP_VIEWLOG "$LOGFILE"
+			G_WHIP_VIEWLOG $FP_LOG
 
 			#return to main menu
 			TARGETMENUID=0
