v7.3
+ DietPi-Software | Unbound: On uninstall, add Quad9 to system resolver if only Unbound was used

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -677,7 +677,7 @@ INDEX_BROWSER_TARGET=$INDEX_BROWSER_TARGET"
 		aSOFTWARE_CATX[$software_id]=2
 		aSOFTWARE_DOCS[$software_id]='https://dietpi.com/docs/software/media/#snapcast-client'
 		aSOFTWARE_DEPS[$software_id]='5'
-		aSOFTWARE_INTERACTIVE[$software_id]=1		
+		aSOFTWARE_INTERACTIVE[$software_id]=1
 		# Not currently available on arm64: https://github.com/badaix/snapcast/issues/706
 		aSOFTWARE_AVAIL_G_HW_ARCH[$software_id,3]=0
 
@@ -7634,10 +7634,10 @@ _EOF_
 
 ## Start an FastCGI server using php-fpm
 fastcgi.server += ( ".php" =>
-        ((
-                "socket" => "/run/php/${PHP_NAME}-fpm.sock",
-                "broken-scriptfilename" => "enable"
-        ))
+	((
+		"socket" => "/run/php/$PHP_NAME-fpm.sock",
+		"broken-scriptfilename" => "enable"
+	))
 )
 _EOF_
 			# - Enable modules
@@ -13193,8 +13193,7 @@ _EOF_
 		local gpu_memory=0
 
 		# Kodi, Jellyfin
-		if (( ${aSOFTWARE_INSTALL_STATE[31]} == 1 ||
-		      ${aSOFTWARE_INSTALL_STATE[178]} == 1 )); then
+		if (( ${aSOFTWARE_INSTALL_STATE[31]} == 1 || ${aSOFTWARE_INSTALL_STATE[178]} == 1 )); then
 
 			gpu_memory=320
 			(( ${G_HW_MEMORY_SIZE:-0} > 512 )) || gpu_memory=256
@@ -13513,7 +13512,8 @@ _EOF_
 		if (( ${aSOFTWARE_INSTALL_STATE[$software_id]} == -1 )); then
 
 			Banner_Uninstalling
-			# Stop  Lighttpd service
+
+			# Stop Lighttpd service, as it may keep running on package removal
 			[[ -f '/lib/systemd/system/lighttpd.service' ]] && systemctl disable --now lighttpd
 
 			G_AGP lighttpd
@@ -13990,13 +13990,18 @@ _EOF_
 			[[ -f '/etc/pihole/setupVars.conf' ]] && grep -q '^[[:blank:]]*PIHOLE_DNS_1=127.0.0.1' /etc/pihole/setupVars.conf && G_CONFIG_INJECT 'PIHOLE_DNS_1=' 'PIHOLE_DNS_1=9.9.9.9' /etc/pihole/setupVars.conf
 
 			# AdGuard Home: Assure that it does not resolve via Unbound anymore
-			if [[ -f '/mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf' ]]; then
-
+			if [[ -f '/mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf' ]]
+			then
 				G_DIETPI-NOTIFY 2 'AdGuard Home upstream DNS server has been changed back to default settings due to Unbound being uninstalled.'
 				G_CONFIG_INJECT 'upstream_dns_file:[[:blank:]]' '  upstream_dns_file: ""' /mnt/dietpi_userdata/adguardhome/AdGuardHome.yaml
 				[[ -f '/mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf' ]]  && G_EXEC_NOEXIT=1 G_EXEC rm /mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf
 				systemctl -q is-active adguardhome && G_EXEC_NOEXIT=1 G_EXEC systemctl restart adguardhome
+			fi
 
+			# Failsafe: Add Quad9 to system resolver if only Unbound was used
+			if [[ -f '/etc/unbound/unbound.conf.d/dietpi.conf' ]] && grep -Eq '^[[:blank:]]*port:[[:blank:]]+53$' /etc/unbound/unbound.conf.d/dietpi.conf
+			then
+				grep '^[[:blank:]]*nameserver[[:blank:]]' /etc/resolv.conf | grep -qvE '[[:blank:]]127.0.0.1(:53)?$' || echo 'nameserver 9.9.9.9' >> /etc/resolv.conf # Failsafe
 			fi
 
 			G_AGP unbound
@@ -14497,7 +14502,7 @@ _EOF_
 			[[ -d '/etc/nginx/sites-dietpi' ]] && rm -f /etc/nginx/sites-dietpi/dietpi-pihole*
 
 			# Unbound: Switch port to 53 if it is still installed
-			if (( ${aSOFTWARE_INSTALL_STATE[182]} == 2 )) && grep -q '^[[:blank:]]*port:[[:blank:]][[:blank:]]*5335$' /etc/unbound/unbound.conf.d/dietpi.conf
+			if (( ${aSOFTWARE_INSTALL_STATE[182]} == 2 )) && grep -Eq '^[[:blank:]]*port:[[:blank:]]+5335$' /etc/unbound/unbound.conf.d/dietpi.conf
 			then
 				G_DIETPI-NOTIFY 2 'Reconfiguring Unbound to work on its own'
 				G_CONFIG_INJECT 'port:[[:blank:]]' '	port: 53' /etc/unbound/unbound.conf.d/dietpi.conf
@@ -14527,7 +14532,7 @@ _EOF_
 			[[ -d '/mnt/dietpi_userdata/adguardhome' ]] && G_EXEC rm -R /mnt/dietpi_userdata/adguardhome
 
 			# Unbound: Switch port to 53 if it is still installed
-			if (( ${aSOFTWARE_INSTALL_STATE[182]} == 2 )) && grep -q '^[[:blank:]]*port:[[:blank:]][[:blank:]]*5335$' /etc/unbound/unbound.conf.d/dietpi.conf
+			if (( ${aSOFTWARE_INSTALL_STATE[182]} == 2 )) && grep -Eq '^[[:blank:]]*port:[[:blank:]]+5335$' /etc/unbound/unbound.conf.d/dietpi.conf
 			then
 				G_DIETPI-NOTIFY 2 'Reconfiguring Unbound to work on its own'
 				G_CONFIG_INJECT 'port:[[:blank:]]' '	port: 53' /etc/unbound/unbound.conf.d/dietpi.conf
@@ -16148,7 +16153,7 @@ _EOF_
 		then
 			Banner_Uninstalling
 			G_AGP snapclient
-		fi		
+		fi
 
 		G_DIETPI-NOTIFY 3 "$G_PROGRAM_NAME" 'Finalise uninstall'
 
