v6.8
+ DietPi-LetsEncrypt | Syntax fix (whoopsie) + replace "ps aux | grep" by "pgrep"

diff --git a/dietpi/dietpi-letsencrypt b/dietpi/dietpi-letsencrypt
--- a/dietpi/dietpi-letsencrypt
+++ b/dietpi/dietpi-letsencrypt
@@ -59,7 +59,7 @@
 
 		#------------------------------------------------------------------------------------------------------
 		#Apache2
-		if ps aux | grep -qi '[a]pache'; then
+		if pgrep -i '[a]pache' &> /dev/null; then
 
 			G_DIETPI-NOTIFY 0 'Apache2 webserver detected'
 			local fp_defaultsite='/etc/apache2/sites-available/000-default.conf'
@@ -88,7 +88,7 @@
 
 		#------------------------------------------------------------------------------------------------------
 		#Lighttpd
-		elif ps aux | grep -qi '[l]ighttpd'; then
+		elif pgrep -i '[l]ighttpd' &> /dev/null; then
 
 			G_DIETPI-NOTIFY 0 'Lighttpd webserver detected'
 
@@ -183,7 +183,7 @@ _EOF_
 
 		#------------------------------------------------------------------------------------------------------
 		# Nginx
-		elif ps aux | grep -qi '[n]ginx'; then
+		elif pgrep -i '[n]ginx' &> /dev/null; then
 
 			G_DIETPI-NOTIFY 0 'Nginx webserver detected'
 			local fp_defaultsite='/etc/nginx/sites-available/default'
@@ -205,14 +205,14 @@ _EOF_
 			if (( $? )); then
 	
 				echo -e "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..." | tee "$FP_LOGFILE"
-				(( ! $INPUT )); then && G_WHIP_MSG "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..."
+				(( ! $INPUT )) && G_WHIP_MSG "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..."
 				return 1
 	
 			fi
 
 		#------------------------------------------------------------------------------------------------------
 		#Minio
-		elif ps aux | grep -qi '[m]inio'; then
+		elif pgrep -i '[m]inio' &> /dev/null; then
 
 			G_DIETPI-NOTIFY 0 'Minio S3 server detected'
 	
@@ -222,7 +222,7 @@ _EOF_
 			if (( $? )); then
 	
 				echo -e "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..." | tee "$FP_LOGFILE"
-				(( ! $INPUT )); then && G_WHIP_MSG "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..."
+				(( ! $INPUT )) && G_WHIP_MSG "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..."
 				return 1
 	
 			fi
@@ -286,7 +286,7 @@ _EOF_
 		else
 
 			echo -e '[FAILURE] No compatible and/or active webserver was found. Aborting...' | tee "$FP_LOGFILE"
-			(( ! $INPUT )); && G_WHIP_MSG '[FAILURE] No compatible and/or active webserver was found. Aborting...'
+			(( ! $INPUT )) && G_WHIP_MSG '[FAILURE] No compatible and/or active webserver was found. Aborting...'
 			return 1
 
 		fi
