v6.20
+ DietPi-Software | WireGuard: Install kernel meta packages via G_AGI to force install of new dependencies; Check whether a reboot is required due to upgraded kernel, before starting WireGuard, otherwise inform user.

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -4928,17 +4928,18 @@ _EOF_
 
 			Banner_Installing
 
-			# Kernel headers required for wireguard-dkms to build the wireguard kernel module
-			local kernel_header=''
+			# Kernel headers and matching kernel image required for wireguard-dkms to build the wireguard kernel module
+			# - Since G_AGUG does not upgrade packages with changed dependencies, in case of kernel image meta packages, those need to be installed via G_AGI.
+			local kernel_packages=''
 			# - x86_64
 			if (( $G_HW_ARCH == 10 )); then
 
-				kernel_headers='linux-headers-amd64'
+				kernel_packages='linux-image-amd64 linux-headers-amd64'
 
 			# - RPi
 			elif (( $G_HW_MODEL < 10 )); then
 
-				kernel_headers='raspberrypi-kernel-headers'
+				kernel_packages='raspberrypi-kernel-headers'
 
 			fi
 
@@ -4950,9 +4951,9 @@ _EOF_
 
 			# iptables required to forward incoming VPN traffic to internet interface
 			# qrencode required to create client config QR code on console
-			G_AGI $kernel_headers wireguard iptables qrencode
+			G_AGI $kernel_packages wireguard iptables qrencode
 
-			unset kernel_headers
+			unset kernel_packages
 
 		fi
 
@@ -10130,13 +10131,18 @@ _EOF_
 
 			unset domain port invalid_text
 
+			# Enable the kernel module
+			# - If this fails, current active kernel and headers do not match and a reboot is required.
+			local module_active=1
+			modprobe wireguard || { module_active=0; G_DIETPI_NOTIFY 0 'WireGuard has been successfully installed, but a reboot is required, before it can be started.'; }
+
 			# Enable IPv4 forwarding
-			sysctl net.ipv4.ip_forward=1
+			(( $module_active )) && sysctl net.ipv4.ip_forward=1
 			# - persistent
 			echo 'net.ipv4.ip_forward=1' > /etc/sysctl.d/dietpi-wireguard.conf
 
 			# Start WireGuard interface via systemd unit
-			systemctl start wg-quick@wg0
+			(( $module_active )) && systemctl start wg-quick@wg0
 			# - persistent
 			systemctl enable wg-quick@wg0
 
