v116
Disable screen blanking during dietpi-software installs.

ARM64.deb for Node JS

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -2392,32 +2392,58 @@ _EOF_
 			INSTALL_DESCRIPTION='NodeJS - Javascript Runtime'
 			Banner_Installing
 
-			#check, is online
-			INSTALL_URL_ADDRESS='https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
-			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+			#ARM64 (Odroid C2) - Not currently available via nodesource.com
+			if (( $HW_MODEL == 12 )); then
 
-			#Install
-			if (( $? == 0 )); then
+				#check, is online
+				INSTALL_URL_ADDRESS='http://dietpi.com/downloads/binaries/c2/nodejs_5-1_arm64.deb'
+				/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
 
-				# - Preqs
-				AGI apt-transport-https
+				#Install
+				if (( $? == 0 )); then
 
-				# - Add repo
-				curl -s "$INSTALL_URL_ADDRESS" | apt-key add -
-				echo -e "deb https://deb.nodesource.com/node_5.x jessie main" > /etc/apt/sources.list.d/nodesource_nodejs.list
-				/DietPi/dietpi/dietpi-apt-get_update 1
-				apt-get update
+					# - Preqs
+					wget "$INSTALL_URL_ADDRESS" -O package.deb
+					dpkg -i package.deb
+					rm package.deb
 
-				# - install
-				AGI nodejs
+					NODEJS=2
 
-				NODEJS=2
+				else
+					Error_NoConnection_NoInstall
 
+					#Abort failed install
+					NODEJS=0
+				fi
+
+			#Everything else
 			else
-				Error_NoConnection_NoInstall
 
-				#Abort failed install
-				NODEJS=0
+				#check, is online
+				INSTALL_URL_ADDRESS='https://deb.nodesource.com/setup_5.x'
+				/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+				#Install
+				if (( $? == 0 )); then
+
+					# - Preqs
+					AGI apt-transport-https
+
+					# - Add repo (use their install script)
+					curl -sL "$INSTALL_URL_ADDRESS" | -E bash -
+
+					# - install
+					AGI nodejs
+
+					NODEJS=2
+
+				else
+					Error_NoConnection_NoInstall
+
+					#Abort failed install
+					NODEJS=0
+				fi
+
 			fi
 
 		fi
@@ -4440,6 +4466,10 @@ _EOF_
 	Run_Installations(){
 
 		#------------------------------------------------------------
+		#Disable powersaving on Main screen during installation
+		setterm -blank 0 -powersave off 2> /dev/null
+
+		#------------------------------------------------------------
 		#Set target user/personal data base directory
 		# - Flash (default)
 		TARGET_DIRECTORY="/root"
@@ -4795,6 +4825,9 @@ _EOF_
 	}
 
 	FirstRun_DietPi_Update(){
+
+		#Disable powersaving on main screen
+		setterm -blank 0 -powersave off 2> /dev/null
 
 		#-1 = 1st run | 0 = Reboot, updates applied | 1 = Idle, No updates
 		#Update .update_stage file to completed
