Adding to software list "ZeroTier"
I've added Zerotier, can someone please explain what exactly is "aSOFTWARE_DEPS" and "aSOFTWARE_INTERACTIVE" stands for?

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -1407,6 +1407,12 @@ Available commands:
 		aSOFTWARE_DESC[$software_id]='Zero config VPN'
 		aSOFTWARE_CATX[$software_id]=15
 		aSOFTWARE_DOCS[$software_id]='https://dietpi.com/docs/software/vpn/#tailscale'
+		#-----------------
+		software_id=201
+		aSOFTWARE_NAME[$software_id]='ZeroTier'
+		aSOFTWARE_DESC[$software_id]='Free easy to deploy Cloud-hosted VPN service'
+		aSOFTWARE_CATX[$software_id]=15
+		aSOFTWARE_DOCS[$software_id]='https://dietpi.com/docs/software/vpn/#zerotier'
 
 		# Advanced Networking
 		#--------------------------------------------------------------------------------
@@ -7633,10 +7639,10 @@ case "$1" in
 		fi
 	;;
 
-        *)
-                echo "[FAILED] Invalid command ($1), please use \"start\" or \"stop\""
-                exit 1
-        ;;
+	*)
+		echo "[FAILED] Invalid command ($1), please use \"start\" or \"stop\""
+		exit 1
+	;;
 
 esac
 
@@ -8230,6 +8236,26 @@ _EOF_
 			G_EXEC_OUTPUT=1 G_EXEC_NOEXIT=1 G_EXEC ./install.bash "${options[@]}" || aSOFTWARE_INSTALL_STATE[$software_id]=0
 			G_EXEC_NOHALT=1 G_EXEC rm install.bash
 			[[ -f '/boot/unattended_pivpn.conf' ]] && G_EXEC_NOHALT=1 G_EXEC mv /boot/unattended_pivpn.conf{,.applied}
+
+		fi
+
+		software_id=201 # ZeroTier
+		if (( ${aSOFTWARE_INSTALL_STATE[$software_id]} == 1 )); then
+
+			Banner_Installing
+
+			# APT key: Download from GitHub instead of https://download.zerotier.com/contact%40zerotier.com.gpg for enhanced protection against corrupted download server
+			G_EXEC eval 'curl -sSLf '\''https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg'\'' | gpg --dearmor -o /etc/apt/trusted.gpg.d/dietpi-zerotier.gpg --yes'
+
+			# APT list
+			G_EXEC eval "echo 'deb https://download.zerotier.com/debian/$G_DISTRO_NAME/ $G_DISTRO_NAME main' > /etc/apt/sources.list.d/dietpi-zerotier.list"
+			G_AGUP
+
+			# APT package
+			G_AGI zerotier-one
+
+			# Wait for and print ZeroTier address
+			Create_Config '/var/lib/zerotier-one/identity.secret' 'zerotier-one' && G_DIETPI-NOTIFY 0 "Your ZeroTier address $(mawk -F: '{print $1}' /var/lib/zerotier-one/identity.public)."
 
 		fi
 
@@ -14372,6 +14398,16 @@ If no WireGuard (auto)start is included, but you require it, please do the follo
 			getent passwd pivpn > /dev/null && G_EXEC userdel pivpn
 			getent group pivpn > /dev/null && G_EXEC groupdel pivpn
 			[[ -f '/etc/apt/sources.list.d/swupdate.openvpn.net.list' ]] && G_EXEC rm /etc/apt/sources.list.d/swupdate.openvpn.net.list # Not part of current installer anymore
+
+		fi
+
+		software_id=201 # ZeroTier
+		if (( ${aSOFTWARE_INSTALL_STATE[$software_id]} == -1 )); then
+
+			Banner_Uninstalling
+			G_AGP zerotier-one
+			[[ -f '/etc/apt/sources.list.d/dietpi-zerotier.list' ]] && G_EXEC rm /etc/apt/sources.list.d/dietpi-zerotier.list
+			[[ -f '/etc/apt/trusted.gpg.d/dietpi-zerotier.gpg' ]] && G_EXEC rm /etc/apt/trusted.gpg.d/dietpi-zerotier.gpg
 
 		fi
 
