v110

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -3800,12 +3800,11 @@ _EOF_
 
 	Run_Installations(){
 
-		#Set target data install directory
-		TARGET_DIRECTORY="$HOME"
+		#Set target data install directory (If different to $HOME)
 
 		# - dietpi.txt custom override? (dietpi_userdata_basedirectory=)
 		local dietpi_userdata_basedirectory=$(cat /DietPi/dietpi.txt | grep -m1 'dietpi_userdata_basedirectory=' | sed 's/.*=//')
-		if [ "$dietpi_userdata_basedirectory" != "auto" ]; then
+		if [ "$dietpi_userdata_basedirectory" != "Auto" ]; then
 
 			# - Attempt to create the directory
 			mkdir -p "$dietpi_userdata_basedirectory" &> /dev/null
@@ -4246,6 +4245,7 @@ _EOF_
 	WHIP_BACKTITLE='DietPi-Software'
 	WHIP_TITLE=0
 	WHIP_QUESTION=0
+	MENU_MAIN_LASTITEM=""
 	TARGETMENUID=0
 
 	Menu_No_Internet(){
@@ -4298,27 +4298,36 @@ _EOF_
 		#Hold our string that tells the user what software will be removed when using Index based choice systems
 		local toberemoved_text=""
 
-		WHIP_TITLE='---------- DietPi - Software Setup ----------'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --backtitle "$WHIP_BACKTITLE" --menu " Hardware Detected : $HW_MODEL_DESCRIPTION" --cancel-button "Exit" 15 60 8 \
-		"1" "Select DietPi Optimized Software." \
-		"2" "Select Additional Linux Software." \
-		"3" "SSH Server  : $index_sshserver_text" \
-		"4" "File Server : $index_fileserver_text" \
-		"5" "Log System  : $index_logging_text" \
-		"6" "DietPi-Config" \
-		"7" "Help!" \
-		"Go" "Start Install"  3>&1 1>&2 2>&3)
+		#User/Personal Data override
+		local user_data_path=$(cat /DietPi/dietpi.txt | grep -m1 '^dietpi_userdata_basedirectory=' | sed 's/.*=//')
+
+		WHIP_TITLE='DietPi-Software'
+		WHIP_BACKTITLE="DietPi-Software | IP address: $(sed -n 4p /DietPi/dietpi/.network)"
+
+		OPTION=$(whiptail --title "$WHIP_TITLE" --backtitle "$WHIP_BACKTITLE" --menu " Hardware Detected : $HW_MODEL_DESCRIPTION" --default-item "$MENU_MAIN_LASTITEM" --cancel-button "Exit" 16 75 9 \
+		"Software Optimized" "Select DietPi Optimized Software for installation." \
+		"Software Additional " "Select Additional Linux Software for installation." \
+		"SSH Server" ": $index_sshserver_text" \
+		"File Server" ": $index_fileserver_text" \
+		"Log System" ": $index_logging_text" \
+		"User Data Location" ": $user_data_path" \
+		"DietPi-Config" "Feature-rich configuration tool for your device." \
+		"Help!" "Links to online guides and information." \
+		"Go" ">> Start Installation."  3>&1 1>&2 2>&3)
 
 		CHOICE=$?
 		if (( $CHOICE == 0 )); then
+
+			MENU_MAIN_LASTITEM="$OPTION"
+
 			case "$OPTION" in
-			  1)
+			  "Software Optimized")
 				TARGETMENUID=1
 				;;
-			  2)
+			  "Software Additional"*)
 				TARGETMENUID=2
 				;;
-			  3)
+			  "SSH Server")
 				WHIP_TITLE='SSH Server Choices'
 				OPTION=$(whiptail --title "$WHIP_TITLE" --menu "> None\nSelecting this option will uninstall all SSH servers. This reduces system resources and improves performance. Useful for users who do NOT require networked/remote terminal access.\n\n> Dropbear (Recommended)\nLightweight SSH server, installed by default on DietPi systems.\n\n> OpenSSH\nA feature rich SSH server with SFTP/SCP support, at the cost of increased resource usage." --cancel-button "Back" --default-item "$index_sshserver_text" 21 75 3 \
 				"None" "Not required / manual setup." \
@@ -4352,12 +4361,12 @@ _EOF_
 
 				fi
 			  ;;
-			  4)
+			  "File Server")
 				WHIP_TITLE='Fileserver Choices'
 				OPTION=$(whiptail --title "$WHIP_TITLE" --menu "> None\nSelect this option if you do NOT require a method of accessing or sharing files and folders on this device.\n\n> ProFTP (Recommended for RPi v1)\nAllows you to access/share files on this device efficiently with minimal cpu usage. Uses FTP protocol.\n\n> Samba (Recommended for RPi v2)\nAllows you to easily access/share files on this device, at the cost of higher cpu usage.\n\nMore info: http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=15#p19" --cancel-button "Back" --default-item "$index_fileserver_text" 23 75 3 \
 				"None" "Not required / manual setup." \
 				"ProFTP" "Efficient, lightweight fileserver (recommended)." \
-				"Samba" "Feature rich fileserver." 3>&1 1>&2 2>&3)
+				"Samba" "Feature-rich fileserver." 3>&1 1>&2 2>&3)
 
 				#Assign target index
 				if [ "$OPTION" = "None" ]; then
@@ -4386,7 +4395,7 @@ _EOF_
 
 				fi
 				;;
-			  5)
+			  "Log System")
 				WHIP_TITLE='Logging System Choices'
 				OPTION=$(whiptail --title "$WHIP_TITLE" --menu "> None\nSelecting this option will uninstall DietPi-Ramlog, Logrotate, Rsyslog.\n\n> DietPi-Ramlog #1 (Max performance)\nMounts /var/log to RAM, reducing filesystem IO. Logfiles are cleared every hour. Does NOT save logfiles to disk.\n\n> DietPi-Ramlog #2\nSame as #1, with the added feature of saving logfile contents to disk ($HOME/logfile_storage/*), before being cleared.\n\n> Full (Reduces performance)\nMounts /var/log to DISK, reduces SDcard lifespan. Full logging system with Logrotate and Rsyslog." --cancel-button "Back" --default-item "$index_logging_text" 25 75 4 \
 				"None" " Not required / manual setup." \
@@ -4423,11 +4432,52 @@ _EOF_
 					whiptail --title "$WHIP_TITLE" --msgbox "$WHIP_QUESTION" --backtitle "$WHIP_BACKTITLE" 11 75
 				fi
 				;;
-			  6)
+			  "User Data Location")
+				WHIP_TITLE='User Data Location'
+
+				OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Choose where to store your user/personal data. User/personal data includes software such as Owncloud data, BitTorrent downloads etc. Your fileserver choice (eg: samba, proftp) will also point to this location.\n\nNB: Changes will only affect NEW software that you install with DietPi-Software. Existing software will use the previous location.\n\n > Auto (Recommended)\nIf dedicated USB drive is setup, /mnt/usb_1, else /root\n\n> Manual\nInput a custom directory that will be used for your user/personal data." --cancel-button "Back" --default-item "$index_fileserver_text" 21 75 2 \
+				"Auto" "Default (recommended)" \
+				"Manual" "Input a custom directory." 3>&1 1>&2 2>&3)
+				CHOICE=$?
+
+				if (( $CHOICE == 0 )); then
+
+					if [ "$OPTION" = "Auto" ]; then
+						sed -i "/^dietpi_userdata_basedirectory=/c\dietpi_userdata_basedirectory=Auto" /DietPi/dietpi.txt
+					elif [ "$OPTION" = "Manual" ]; then
+
+						local default_item=$user_data_path
+						if [ "$default_item" = "Auto" ]; then
+							default_item=""
+						fi
+
+						OPTION=$(whiptail --inputbox "Please input a base directory. Your user/personal data will be stored inside this location.\n eg: /mnt/MyDrive/MyData" 11 60 "$default_item" --title "User/Personal Data Base Directory" --backtitle "$WHIP_BACKTITLE" 3>&1 1>&2 2>&3)
+						CHOICE=$?
+						if (( $CHOICE == 0 )); then
+
+							#Need better sanity check
+							#  - Check for / at start of value?
+							#  - Generate test file as per Run_Install section?
+
+							#Generate dir, check for valid.
+							mkdir -p "$OPTION"
+
+							if [ -d "$OPTION" ]; then
+								sed -i "/^dietpi_userdata_basedirectory=/c\dietpi_userdata_basedirectory=$OPTION" /DietPi/dietpi.txt
+							else
+								whiptail --title "Error: Invalid Path" --msgbox "Unable to create directory:\n - $OPTION\nNo changes have been applied." 10 60
+							fi
+						fi
+
+					fi
+				fi
+
+				;;
+			  "DietPi-Config")
 				#Launch DietPi-config
 				/DietPi/dietpi/dietpi-config
 				;;
-			  7)
+			  "Help!")
 				whiptail --title "DietPi - Help" --msgbox "Welcome to DietPi.\n\nEasy to follow, step by step guides for installing DietPi:\nhttp://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=9\n\nFor a list of all installation options and their details:\nhttp://dietpi.com/software" --backtitle "$WHIP_BACKTITLE" 16 75
 				;;
 			  Go)
@@ -5045,7 +5095,7 @@ _EOF_
 			"" "────File Servers───────────────────────────" "off" \
 			"ProFTP" "Lightweight FTP / file server." $fileserver_proftp_w \
 			"vsFTPD" "Alternative FTP / file server." $fileserver_vsftpd_w \
-			"Samba" "Feature rich file server." $fileserver_samba_w \
+			"Samba" "Feature-rich file server." $fileserver_samba_w \
 			"" "────VPN Servers────────────────────────────" "off" \
 			"OpenVPN" "VPN server." $openvpnserver_w \
 			"" "────Network Load Balancing─────────────────" "off" \
@@ -5097,7 +5147,7 @@ _EOF_
 			"" "────File Servers───────────────────────────" "off" \
 			"ProFTP" "Lightweight FTP / file server." $fileserver_proftp_w \
 			"vsFTPD" "Alternative FTP / file server." $fileserver_vsftpd_w \
-			"Samba" "Feature rich file server." $fileserver_samba_w \
+			"Samba" "Feature-rich file server." $fileserver_samba_w \
 			"" "────VPN Servers────────────────────────────" "off" \
 			"OpenVPN" "VPN server." $openvpnserver_w \
 			"" "────Network Load Balancing─────────────────" "off" \
@@ -5156,7 +5206,7 @@ _EOF_
 			"" "────File Servers───────────────────────────" "off" \
 			"ProFTP" "Lightweight FTP / file server." $fileserver_proftp_w \
 			"vsFTPD" "Alternative FTP / file server." $fileserver_vsftpd_w \
-			"Samba" "Feature rich file server." $fileserver_samba_w \
+			"Samba" "Feature-rich file server." $fileserver_samba_w \
 			"" "────VPN Servers────────────────────────────" "off" \
 			"OpenVPN" "VPN server." $openvpnserver_w \
 			"" "────Network Load Balancing─────────────────" "off" \
@@ -5233,7 +5283,7 @@ _EOF_
 				"" "────File Servers───────────────────────────" "off" \
 				"ProFTP" "Lightweight FTP / file server." $fileserver_proftp_w \
 				"vsFTPD" "Alternative FTP / file server." $fileserver_vsftpd_w \
-				"Samba" "Feature rich file server." $fileserver_samba_w \
+				"Samba" "Feature-rich file server." $fileserver_samba_w \
 				"" "────VPN Servers────────────────────────────" "off" \
 				"OpenVPN" "VPN server." $openvpnserver_w \
 				"" "────Network Load Balancing─────────────────" "off" \
@@ -5297,7 +5347,7 @@ _EOF_
 				"" "────File Servers───────────────────────────" "off" \
 				"ProFTP" "Lightweight FTP / file server." $fileserver_proftp_w \
 				"vsFTPD" "Alternative FTP / file server." $fileserver_vsftpd_w \
-				"Samba" "Feature rich file server." $fileserver_samba_w \
+				"Samba" "Feature-rich file server." $fileserver_samba_w \
 				"" "────VPN Servers────────────────────────────" "off" \
 				"OpenVPN" "VPN server." $openvpnserver_w \
 				"" "────Network Load Balancing─────────────────" "off" \
