v7.1
+ DietPi-LetsEncrypt | Fix input boxes, remove dedicated function
+ DietPi-LetsEncrypt | Do not store settings before anything has been changed or applied. If Cerbot is not executed, its better to load fresh (DietPi version based) defaults on next execution rather than the probably changed previously stored defaults.
+ DietPi-LetsEncrypt | Use exit codes when executing non-interactively

diff --git a/dietpi/dietpi-letsencrypt b/dietpi/dietpi-letsencrypt
--- a/dietpi/dietpi-letsencrypt
+++ b/dietpi/dietpi-letsencrypt
@@ -356,22 +356,13 @@ _EOF_
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Menu
 	#/////////////////////////////////////////////////////////////////////////////////////
-	TARGETMENUID=0
-	PREVIOUS_MENU_SELECTION='Domain'
+	TARGETMENUID=0 # Main menu
+	PREVIOUS_MENU_SELECTION='Domains'
 
 	Menu_Exit(){
 
 		G_WHIP_SIZE_X_MAX=50
 		G_WHIP_YESNO "Exit $G_PROGRAM_NAME?" && TARGETMENUID=-1 # Exit
-
-	}
-
-	Input_Box(){
-
-		local input_value=$1 input_desc=$2
-
-		G_WHIP_DEFAULT_ITEM=$input_value
-		G_WHIP_INPUTBOX "Please enter your $input_desc" || return 1
 
 	}
 
@@ -409,27 +400,29 @@ _EOF_
 
 				'Domains')
 
-					local new=$LETSENCRYPT_DOMAINS error=
-					while new=$(Input_Box "$new" "public domain name, or a comma-separated list of multiple domains this certificate shall be valid for.
-The first entered domain will be the primary domain, applied as server name for the webserver, in case one is installed.$error")
+					local error
+					while G_WHIP_DEFAULT_ITEM=$LETSENCRYPT_DOMAINS G_WHIP_INPUTBOX "${error}Please enter your public domain name, or a comma-separated list of multiple domains this certificate shall be valid for.
+\nThe first entered domain will be the primary domain, applied as server name for the webserver, in case one is installed.")
 					do
 						# Must contain at least one dot with leading secondary domain and trailing top domain
 						# Must not be an IP address with integers and dots only
-						if [[ $new == *?.?* && $new == *[^0-9.]* ]]; then
+						if [[ $G_WHIP_RETURNED_VALUE == *?.?* && $G_WHIP_RETURNED_VALUE == *[^0-9.]* ]]; then
 
-							LETSENCRYPT_DOMAINS=$new
+							LETSENCRYPT_DOMAINS=$G_WHIP_RETURNED_VALUE
 							break
 
 						else
 
-							error="\n\n[FAILED] \"$new\" is no valid domain name.\n\nNote that raw IP addresses are not allowed by Let's Encrypt, thus a domain name is required.\nYou can install No-IP with DietPi-Software to aquire one.\n\nPlease retry..."
+							error="[FAILED] \"$G_WHIP_RETURNED_VALUE\" is no valid domain name.
+\nNote that raw IP addresses are not allowed by Let's Encrypt, thus a domain name is required.
+You can install No-IP with DietPi-Software to aquire one.\n\nPlease try again...\n\n"
 
 						fi
 					done
 
 				;;
 
-				'Email') LETSENCRYPT_EMAIL=$(Input_Box "$LETSENCRYPT_EMAIL" "email address, to allow Let's Encrypt sending you important or security-relevant information, regarding your certificate.");;
+				'Email') G_WHIP_DEFAULT_ITEM=$LETSENCRYPT_EMAIL G_WHIP_INPUTBOX "Please enter your email address, to allow Let's Encrypt sending you important or security-relevant information, regarding your certificate." && LETSENCRYPT_EMAIL=$G_WHIP_RETURNED_VALUE;;
 
 				'Key Size') (( $LETSENCRYPT_KEYSIZE == 4096 )) && LETSENCRYPT_KEYSIZE=2048 || LETSENCRYPT_KEYSIZE=4096;;
 
@@ -470,7 +463,6 @@ Enabling HSTS will prevent access to applications which use a standalone webserv
 - NB: This process can take a long time, please be patient.
       This does not apply to applications which use their own webserver, which usually have their own :port number. These will need to be configured manually.
 \nWould you like to continue?'; then
-
 						Write_Settings
 						Run_Certbot
 						# When started from menu, allow for user reviewing console output
@@ -493,19 +485,11 @@ Press any key to continue...'
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Main Loop
 	#/////////////////////////////////////////////////////////////////////////////////////
-	# Load settings file. Generate if required.
-	if [[ -f $FP_SETTINGS ]]; then
-
-		Read_Settings
-
-	else
-
-		Write_Settings
-
-	fi
+	# Load settings file, if present
+	[[ -f $FP_SETTINGS ]] && Read_Settings
 
 	#-----------------------------------------------------------------------------------
-	# Check installed
+	# Check for and in case offer Certbot install
 	until command -v certbot > /dev/null
 	do
 		# Menu
@@ -534,17 +518,18 @@ Press any key to continue...'
 	# Run
 	elif [[ $INPUT == 1 ]]; then
 
-		Run_Certbot
+		Run_Certbot || exit 1
 
 	#-----------------------------------------------------------------------------------
 	# Invalid
 	else
 
 		G_DIETPI-NOTIFY 1 "Invalid input argument\n\n$USAGE"
+		exit 1
 
 	fi
 
 	#-----------------------------------------------------------------------------------
-	exit
+	exit 0
 	#-----------------------------------------------------------------------------------
 }
