v6.31
+ DietPi-Cleaner | Reduce output length, allowing better review in case of many matches

diff --git a/dietpi/dietpi-cleaner b/dietpi/dietpi-cleaner
--- a/dietpi/dietpi-cleaner
+++ b/dietpi/dietpi-cleaner
@@ -448,23 +448,22 @@ $G_PROGRAM_NAME simulation has finished: Press any key to continue..."
 
 			if [[ ! -s $FP_TMP ]]; then
 
-				echo -e '\nNo matching filenames were found.\n'
+				echo -e '\nNo matching files were found.\n'
 
 			else
 
-				echo -e '\nFound the following matching files:\n'
+				echo -e '\nFound the following matching files:'
 
 			fi
 
-			# Remove files
+			# Process matches
 			while read -r line
 			do
 
-				echo "- Filepath: $line"
-				(( $DRY_RUN )) && continue
-
-				rm "$line"
-				echo -e 'Deleted.\n'
+				# Dry run: Print matches only
+				(( $DRY_RUN )) && { echo "- $line"; continue; }
+				# Else remove and print result
+				rm "$line" && echo "- $line ..Deleted!" || echo "- $line ..Failed!"
 
 			done < $FP_TMP
 
