v148
+ DietPi-Software | CloudPrint (Google): Now available for installation.
Print server with support for Google cloud printing:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=100#p6630

https://github.com/Fourdee/DietPi/issues/855

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -245,7 +245,7 @@ _EOF_
 	# - Software
 	#NB: All software has a unique index that must not be changed (eg: DESKTOP_LXDE = 23)
 	TOTAL_SOFTWARE_INDEXS=0
-	TOTAL_SOFTWARE_INDEXS_HARDLIMIT=137	#Increase as needed. Must be higher than TOTAL_SOFTWARE_INDEXS once calculated in Software_Arrays_Init
+	TOTAL_SOFTWARE_INDEXS_HARDLIMIT=138	#Increase as needed. Must be higher than TOTAL_SOFTWARE_INDEXS once calculated in Software_Arrays_Init
 
 	INSTALLING_INDEX=0					#Which software index is currently being installed?
 
@@ -961,6 +961,19 @@ _EOF_
 
 		# - Disabled for armv6
 		aSOFTWARE_AVAIL_HW_ARCH[$index_current,1]=0
+
+		# - Disabled for arm64
+		aSOFTWARE_AVAIL_HW_ARCH[$index_current,10]=0
+
+		#------------------
+		index_current=137
+
+				 aSOFTWARE_WHIP_NAME[$index_current]='CloudPrint'
+				 aSOFTWARE_WHIP_DESC[$index_current]='print server for google cloud print'
+			aSOFTWARE_CATEGORY_INDEX[$index_current]=4
+					  aSOFTWARE_TYPE[$index_current]=0
+			 aSOFTWARE_ONLINEDOC_URL[$index_current]='f=8&t=5&p=6630#p6630'
+ 		  aSOFTWARE_REQUIRES_RSYSLOG[$index_current]=1 #Not required, but comes in as package dep
 
 		# - Disabled for arm64
 		aSOFTWARE_AVAIL_HW_ARCH[$index_current,10]=0
@@ -5934,6 +5947,34 @@ _EOF_
 
 		fi
 
+		#CloudPrint
+		INSTALLING_INDEX=137
+		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
+
+			Banner_Installing
+
+			INSTALL_URL_ADDRESS='http://davesteele.github.io/cloudprint-service'
+
+			#url/redirect fails wget spider test...
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+			if (( $? == 0 )); then
+
+				INSTALL_URL_ADDRESS+='/repo'
+
+				echo -e "deb $INSTALL_URL_ADDRESS cloudprint-jessie main" > /etc/apt/sources.list.d/cloudprint.list
+				wget -q -O - https://davesteele.github.io/key-366150CE.pub.txt | apt-key add -
+				apt-get update
+
+				AGI cloudprint-service
+
+			else
+
+				Error_NoConnection_NoInstall
+
+			fi
+
+		fi
+
 	}
 
 	Install_Linux_Software(){
@@ -9891,6 +9932,16 @@ _EOF_
 			cp /usr/local/share/motioneye/extra/motioneye.systemd-unit-local /etc/systemd/system/motioneye.service
 
 		fi
+
+		#CloudPrint
+		INSTALLING_INDEX=137
+		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
+
+			# - Enable web admin
+			cupsctl --remote-admin
+			usermod -a -G lpadmin root
+
+		fi
 		#-------------------------------------------------------------------
 
 	}
@@ -10233,6 +10284,13 @@ _EOF_
 			systemctl daemon-reload
 
 			pip uninstall -y motioneye
+
+		elif (( $1 == 137 )); then
+
+			AGP cloudprint-service
+
+			rm /etc/apt/sources.list.d/cloudprint.list
+			apt-get update
 
 		elif (( $1 == 119 )); then
 
