v119
+ Finishing off VNC servers
+ Optimized dietpi-services print_ code

diff --git a/dietpi/dietpi-services b/dietpi/dietpi-services
--- a/dietpi/dietpi-services
+++ b/dietpi/dietpi-services
@@ -17,6 +17,8 @@
 	#Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
 	LANG=en_GB.UTF-8
 
+	INPUT_MODE="$1"
+
 	DISTRO=$(sed -n 3p /DietPi/dietpi/.hw_model)
 
 	aSERVICE_NAME=(
@@ -61,7 +63,11 @@
 	done
 
 	#Check if service name is available on system.
-	Populate_Available_Array(){
+	Populate_Available_Array()
+	{
+
+		#Find dpkg program names
+		dpkg --get-selections | awk '{print $1}' > "$FP_TEMP"
 
 		for ((i=0; i<${#aSERVICE_NAME[@]}; i++))
 		do
@@ -82,6 +88,34 @@
 
 	}
 
+	Print_Status()
+	{
+
+		#$1 = name
+		#$2 = exit code
+
+		#ok
+		if (( $2 == 0 )); then
+
+			echo -e "\e[1A\e[32mOk\e[0m \e[90m|\e[0m $1"
+
+		#failed
+		else
+
+			echo -e "\e[1A\e[31Failed\e[0m \e[90m|\e[0m $1"
+
+		fi
+
+	}
+
+	Print_Banner()
+	{
+
+		echo -e "\n \e[38;5;93mDietPi-Services\e[0m"
+		echo -e " \e[90mMode:\e[0m $INPUT_MODE"
+		echo -e " \e[90mPlease wait...\e[0m"
+
+	}
 
 	FP_TEMP="/tmp/.dietpi-services_installed"
 
@@ -89,20 +123,15 @@
 	# Main
 	#/////////////////////////////////////////////////////////////////////////////////////
 	#Info
-	echo -e "\n \e[38;5;93mDietPi-Services\e[0m"
-	echo -e " \e[90mMode:\e[0m $1"
-	echo -e " \e[90mPlease wait...\e[0m"
+	Print_Banner
 
-	#Find installed services
-	dpkg --get-selections | awk '{print $1}' > "$FP_TEMP"
+	#Obtain an array of available services installed on system.
+	Populate_Available_Array
 
 	#-----------------------------------------------------------------------------------
 	#disable/enable
-	if [ "$1" = "disable" ] ||
-		[ "$1" = "enable" ]; then
-
-		#Check if service name is available on system.
-		Populate_Available_Array
+	if [ "$INPUT_MODE" = "disable" ] ||
+		[ "$INPUT_MODE" = "enable" ]; then
 
 		for ((i=0; i<${#aSERVICE_NAME[@]}; i++))
 		do
@@ -110,19 +139,17 @@
 			#Apply
 			if (( ${aSERVICE_AVAILABLE[$i]} == 1 )); then
 
+				echo -e "${aSERVICE_NAME[$i]}"
+
 				# - LSB
 				if (( $DISTRO == 1 )); then
 					update-rc.d -f ${aSERVICE_NAME[$i]} $1 &> /dev/null
+					Print_Status ${aSERVICE_NAME[$i]} $?
 
 				# - SystemD
 				elif (( $DISTRO == 3 )); then
-					echo -e "${aSERVICE_NAME[$i]}"
 					systemctl $1 ${aSERVICE_NAME[$i]} &> /dev/null
-					if (( $? == 0 )); then
-						echo -e "\e[1A\e[32mOk\e[0m \e[90m|\e[0m ${aSERVICE_NAME[$i]}"
-					else
-						echo -e "\e[1A\e[31Failed\e[0m \e[90m|\e[0m ${aSERVICE_NAME[$i]}"
-					fi
+					Print_Status ${aSERVICE_NAME[$i]} $?
 
 				fi
 
@@ -139,13 +166,12 @@
 
 	#-----------------------------------------------------------------------------------
 	#start/stop/restart
-	elif [ "$1" = "start" ] ||
-		[ "$1" = "stop" ] ||
-		[ "$1" = "restart" ]; then
+	elif [ "$INPUT_MODE" = "start" ] ||
+		[ "$INPUT_MODE" = "stop" ] ||
+		[ "$INPUT_MODE" = "restart" ]; then
 
 		#????????????????????????????????????????????????????????????????????????
 		# Although this allows for simple service control without using SystemD, we really should convert these to SystemD services. To keep everything consistent, clean, and obtain a correct exit code.
-
 		#DietPi: Non-service based control for specific dietpi-software installed programs.
 		# - Start order first
 		index=0
@@ -163,11 +189,7 @@
 				echo -e "${aDIETPISERVICE_NAME[$i]}"
 
 				${aDIETPISERVICE_FP[$i]} $1 &> /dev/null
-				if (( $? == 0 )); then
-					echo -e "\e[1A\e[32mOk\e[0m \e[90m|\e[0m ${aDIETPISERVICE_NAME[$i]}"
-				else
-					echo -e "\e[1A\e[31Failed\e[0m \e[90m|\e[0m ${aDIETPISERVICE_NAME[$i]}"
-				fi
+				Print_Status ${aDIETPISERVICE_NAME[$i]} $?
 
 			fi
 
@@ -177,9 +199,6 @@
 		unset aDIETPISERVICE_FP
 		#????????????????????????????????????????????????????????????????????????
 
-		#Check if service name is available on system.
-		Populate_Available_Array
-
 		#Linux: installed services
 		for ((i=0; i<${#aSERVICE_NAME[@]}; i++))
 		do
@@ -187,21 +206,21 @@
 			#Apply
 			if (( ${aSERVICE_AVAILABLE[$i]} == 1 )); then
 
+				echo -e "${aSERVICE_NAME[$i]}"
+
 				# - LSB
 				if (( $DISTRO == 1 )); then
-					update-rc.d -f ${aSERVICE_NAME[$i]} $1 &> /dev/null
+
+					service ${aSERVICE_NAME[$i]} $1 &> /dev/null
 
 				# - SystemD
 				elif (( $DISTRO == 3 )); then
-					echo -e "${aSERVICE_NAME[$i]}"
+
 					systemctl $1 ${aSERVICE_NAME[$i]} &> /dev/null
-					if (( $? == 0 )); then
-						echo -e "\e[1A\e[32mOk\e[0m \e[90m|\e[0m ${aSERVICE_NAME[$i]}"
-					else
-						echo -e "\e[1A\e[31Failed\e[0m \e[90m|\e[0m ${aSERVICE_NAME$i]}"
-					fi
 
 				fi
+
+				Print_Status ${aSERVICE_NAME[$i]} $?
 
 			fi
 
@@ -209,7 +228,6 @@
 
 		#????????????????????????????????????????????????????????????????????????
 		# Although this allows for simple service control without using SystemD, we really should convert these to SystemD services. To keep everything consistent, clean, and obtain a correct exit code.
-
 		#DietPi: Non-service based control for specific dietpi-software installed programs.
 		# - Start prority last
 		index=0
@@ -228,11 +246,7 @@
 				echo -e "${aDIETPISERVICE_NAME[$i]}"
 
 				${aDIETPISERVICE_FP[$i]} $1 &> /dev/null
-				if (( $? == 0 )); then
-					echo -e "\e[1A\e[32mOk\e[0m \e[90m|\e[0m ${aDIETPISERVICE_NAME[$i]}"
-				else
-					echo -e "\e[1A\e[31Failed\e[0m \e[90m|\e[0m ${aDIETPISERVICE_NAME[$i]}"
-				fi
+				Print_Status ${aDIETPISERVICE_NAME[$i]} $?
 
 			fi
 
