v133
+ dietpi-config apt mirror: https://github.com/Fourdee/DietPi/issues/519

diff --git a/dietpi/dietpi-config b/dietpi/dietpi-config
--- a/dietpi/dietpi-config
+++ b/dietpi/dietpi-config
@@ -3509,8 +3509,17 @@ _EOF_
 
 		fi
 
+		#Apt mirror
+		local apt_mirror_current=$(sed -n 1p /etc/apt/sources.list | awk '{print $2}')
+		if [ ! -n "$apt_mirror_current" ]; then
+
+			apt_mirror_current='Unknown, no string from scrape'
+
+		fi
+
 		WHIP_TITLE='DietPi - Network Options: NAS/Misc'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "\n Samba client : $sambaclient_status\n FTP client   : $curlftpfs_status\n NFS client   : $nfsclient_status\n NoIp status  : $noip_status" --cancel-button "$TEXT_MENU_BACK" --backtitle "$WHIP_BACKTITLE" 17 75 4 \
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "\n Apt mirror   : $apt_mirror_current\n Samba client : $sambaclient_status\n FTP client   : $curlftpfs_status\n NFS client   : $nfsclient_status\n NoIp status  : $noip_status" --cancel-button "$TEXT_MENU_BACK" --backtitle "$WHIP_BACKTITLE" 18 100 5 \
+		"Apt Mirror" "Select a different Apt mirror for sources.list" \
 		"Samba Client" "$sambaclient_menutext" \
 		"FTP Client" "$curlftpfs_menutext" \
 		"NFS Client" "$nfsclient_menutext" \
@@ -3519,6 +3528,73 @@ _EOF_
 		CHOICE=$?
 		if (( $CHOICE == 0 )); then
 			case "$OPTION" in
+
+				"Apt Mirror")
+
+					#Create Menu List for Whiptail
+					local whiptail_menu_array=(
+						"Custom" "Manually enter Apt mirror"
+					)
+
+					# - Raspbian
+					if (( $HW_MODEL < 10 )); then
+
+						whiptail_menu_array+=("http://mirrordirector.raspbian.org/raspbian" "Global")
+						whiptail_menu_array+=("http://mirror.ox.ac.uk/sites/archive.raspbian.org/archive/raspbian" "UK")
+						whiptail_menu_array+=("http://ftp.fu-berlin.de/linux/raspbian/raspbian" "Germany")
+						whiptail_menu_array+=("http://mirror.umd.edu/raspbian/raspbian" "US")
+						whiptail_menu_array+=("http://mirrors.ustc.edu.cn/raspbian/raspbian" "China")
+						whiptail_menu_array+=("http://raspbian.mirror.digitalpacific.com.au/raspbian" "Australia")
+
+					# - Debian
+					else
+
+						whiptail_menu_array+=("http://ftp.debian.org/debian" "Global")
+						whiptail_menu_array+=("http://ftp.uk.debian.org/debian" "UK")
+						whiptail_menu_array+=("http://ftp.us.debian.org/debian" "US")
+						whiptail_menu_array+=("http://ftp.cn.debian.org/debian" "China")
+						whiptail_menu_array+=("http://ftp.au.debian.org/debian" "Australia")
+
+					fi
+
+					OPTION=$(whiptail --title "Choose Apt Mirror" --menu "Please select a Apt mirror, or choose custom for manual entry." --default-item "$apt_mirror_current" --cancel-button "$TEXT_MENU_BACK" --backtitle "$WHIP_BACKTITLE" 15 100 7 "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
+					CHOICE=$?
+					if (( $CHOICE == 0 )); then
+						case $OPTION in
+							Custom)
+								OPTION=$(whiptail --inputbox "Enter Your Apt Mirror\n - eg: http://ftp.debian.org/debian" 9 100 "$apt_mirror_current" --title "Set Apt Mirror" 3>&1 1>&2 2>&3)
+								CHOICE=$?
+								if (( $CHOICE == 0 )); then
+									return_value=$OPTION
+								fi
+							;;
+							*)
+								return_value=$OPTION
+							;;
+						esac
+
+						/DietPi/dietpi/func/dietpi-set_software apt-mirror $OPTION
+
+						# - test it
+						/DietPi/dietpi/func/dietpi-notify 2 "Updating Apt, please wait..."
+
+						apt-get update
+						local result=$?
+						if (( $result != 0 )); then
+
+							whiptail --title "Apt Error:" --msgbox "Failed to update apt, exit code: $result\nPlease try another Apt mirror." --backtitle "$WHIP_BACKTITLE" 8 65
+
+						fi
+
+						#Return to this Menu
+						TARGETMENUID=16
+
+					fi
+
+					#delete []
+					unset whiptail_menu_array
+
+				;;
 
 				"NFS Client")
 
