v110

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -73,8 +73,8 @@
 	FP_INSTALLED_FILE="/DietPi/dietpi/.installed"
 	FP_DIETPIAUTOMATION_LOG="/root/DietPi-Automation.log"
 
-	#Used to set data directories (eg: usbdrive /mnt/usb_1)
-	TARGET_DIRECTORY="$HOME"
+	#Used to set user/personal data directories (eg: usbdrive /mnt/usb_1)
+	TARGET_DIRECTORY="/root"
 
 	#Uninstall temp file
 	UNINSTALL_FILE='/tmp/dietpi_uninstall_list'
@@ -3802,32 +3802,37 @@ _EOF_
 
 	Run_Installations(){
 
-		#Set target data install directory (If different to $HOME)
+		#------------------------------------------------------------
+		#Set target user/personal data base directory
+		# - Flash (default)
+		TARGET_DIRECTORY="/root"
 
-		# - dietpi.txt custom override? (dietpi_userdata_basedirectory=)
+		# - dietpi.txt custom override (dietpi_userdata_basedirectory=)
 		local dietpi_userdata_basedirectory=$(cat /DietPi/dietpi.txt | grep -m1 'dietpi_userdata_basedirectory=' | sed 's/.*=//')
 		if [ "$dietpi_userdata_basedirectory" != "Auto" ]; then
-
-			# - Attempt to create the directory
-			mkdir -p "$dietpi_userdata_basedirectory" &> /dev/null
-
-			# - Generate a test file inside the target directory, and check it exists.
-			local test_file_name=".testfile_dietpi_userdata_basedirectory"
-			echo 0 > "$dietpi_userdata_basedirectory"/"$test_file_name"
-
-			if [ -f "$dietpi_userdata_basedirectory"/"$test_file_name" ]; then
-				TARGET_DIRECTORY="$dietpi_userdata_basedirectory"
-				rm "$dietpi_userdata_basedirectory"/"$test_file_name" &> /dev/null
-			else
-				whiptail --title "Error: Creating custom data directory" --msgbox "DietPi was unable to create your custom user/personal data directory (dietpi_userdata_basedirectory= set in dietpi.txt):\n\n - $dietpi_userdata_basedirectory\n\nDietPi-Software will now exit. Please correct the value of dietpi_userdata_basedirectory in dietpi.txt before trying again." 15 70
-				exit
-			fi
+			TARGET_DIRECTORY="$dietpi_userdata_basedirectory"
 
 		# - USB
 		elif (( $USBDRIVE > 0 )); then
 			TARGET_DIRECTORY="/mnt/usb_1"
+
 		fi
 
+		#Attempt to create user/personal data directory
+		mkdir -p "$TARGET_DIRECTORY" &> /dev/null
+
+		# - Generate a test file inside the target directory, and check it exists.
+		local test_file_name=".testfile_dietpi_userdata_basedirectory"
+		echo 0 > "$TARGET_DIRECTORY"/"$test_file_name"
+
+		if [ -f "$TARGET_DIRECTORY"/"$test_file_name" ]; then
+			rm "$TARGET_DIRECTORY"/"$test_file_name" &> /dev/null
+		else
+			Error_Create_UserDataDirectory
+			exit
+		fi
+
+		#------------------------------------------------------------
 		#Set current path to home folder
 		cd "$HOME"/
 
@@ -4223,7 +4228,7 @@ _EOF_
 		if (( $DIETPI_INSTALL_STAGE == 0 )) && (( $AUTOINSTALL_IGNOREERRORS == 1 )); then
 			echo -e "Error: $ERROR_TEXT" >> "$FP_DIETPIAUTOMATION_LOG"
 		else
-			whiptail --title "Error" --msgbox "$ERROR_TEXT" 14 70
+			whiptail --title "Error" --msgbox "$ERROR_TEXT" 16 70
 		fi
 
 	}
@@ -4238,7 +4243,12 @@ _EOF_
 
 		ERROR_TEXT"Apt-get has failed:\n - Apt string = $string\n - Error code = $result\n - Software Title = $INSTALL_DESCRIPTION"
 		Error_Display
+	}
 
+	Error_Create_UserDataDirectory(){
+
+		ERROR_TEXT="DietPi was unable to create your custom user/personal data directory (dietpi_userdata_basedirectory= set in dietpi.txt):\n\n - $(cat /DietPi/dietpi.txt | grep -m1 'dietpi_userdata_basedirectory=' | sed 's/.*=//')\n\nDietPi-Software will now exit. Please correct the value of dietpi_userdata_basedirectory in dietpi.txt before trying again."
+		Error_Display
 	}
 
 	#/////////////////////////////////////////////////////////////////////////////////////
@@ -4303,6 +4313,18 @@ _EOF_
 		#User/Personal Data override
 		local user_data_path=$(cat /DietPi/dietpi.txt | grep -m1 '^dietpi_userdata_basedirectory=' | sed 's/.*=//')
 
+		# - Add location info for Auto
+		local user_data_auto_location=""
+		if [ "$user_data_path" = "Auto" ]; then
+
+			if (( $USBDRIVE == 2 )); then
+				user_data_auto_location="| USB Drive"
+			else
+				user_data_auto_location="| Flash (SD/EMMC)"
+			fi
+
+		fi
+
 		WHIP_TITLE='DietPi-Software'
 		WHIP_BACKTITLE="DietPi-Software | IP address: $(sed -n 4p /DietPi/dietpi/.network)"
 
@@ -4312,7 +4334,7 @@ _EOF_
 		"SSH Server" ": $index_sshserver_text" \
 		"File Server" ": $index_fileserver_text" \
 		"Log System" ": $index_logging_text" \
-		"User Data Location" ": $user_data_path" \
+		"User Data Location" ": $user_data_path $user_data_auto_location" \
 		"DietPi-Config" "Feature-rich configuration tool for your device." \
 		"Help!" "Links to online guides and information." \
 		"Go" ">> Start Installation."  3>&1 1>&2 2>&3)
@@ -4437,8 +4459,8 @@ _EOF_
 			  "User Data Location")
 				WHIP_TITLE='User Data Location'
 
-				OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Choose where to store your user/personal data. User/personal data includes software such as Owncloud data, BitTorrent downloads etc. Your fileserver choice (eg: samba, proftp) will also point to this location.\n\nNB: Changes will only affect NEW software that you install with DietPi-Software. Existing software will use the previous location.\n\n > Auto (Recommended)\nIf dedicated USB drive is setup, /mnt/usb_1, else /root\n\n> Manual\nInput a custom directory that will be used for your user/personal data." --cancel-button "Back" --default-item "$index_fileserver_text" 21 75 2 \
-				"Auto" "Default (recommended)" \
+				OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Choose where to store your user/personal data. User/personal data includes software such as Owncloud data, BitTorrent downloads etc. Your fileserver choice (eg: samba, proftp) will also point to this location.\n\nNB: Changes will only affect NEW software that you install with DietPi-Software. Existing software will use the previous location.\n\n > Auto $user_data_auto_location\nIf dedicated USB drive is setup /mnt/usb_1. Else /root\n\n> Manual\nInput a custom directory that will be used for your user/personal data." --cancel-button "Back" --default-item "$index_fileserver_text" 21 75 2 \
+				"Auto" "Default (recommended)." \
 				"Manual" "Input a custom directory." 3>&1 1>&2 2>&3)
 				CHOICE=$?
 
@@ -4453,22 +4475,29 @@ _EOF_
 							default_item=""
 						fi
 
-						OPTION=$(whiptail --inputbox "Please input a base directory. Your user/personal data will be stored inside this location.\n eg: /mnt/MyDrive/MyData" 11 60 "$default_item" --title "User/Personal Data Base Directory" --backtitle "$WHIP_BACKTITLE" 3>&1 1>&2 2>&3)
+						OPTION=$(whiptail --inputbox "Please input a base directory. Your user/personal data will be stored inside this location.\n - eg: /mnt/MyDrive/MyData" 11 60 "$default_item" --title "User/Personal Data Base Directory" --backtitle "$WHIP_BACKTITLE" 3>&1 1>&2 2>&3)
 						CHOICE=$?
 						if (( $CHOICE == 0 )); then
 
-							#Need better sanity check
-							#  - Check for / at start of value?
-							#  - Generate test file as per Run_Install section?
+							local path_valid=0
 
-							#Generate dir, check for valid.
-							mkdir -p "$OPTION"
+							#Check for / at start of value
+							if [ "${OPTION:0:1}" = "/" ]; then
 
-							if [ -d "$OPTION" ]; then
-								sed -i "/^dietpi_userdata_basedirectory=/c\dietpi_userdata_basedirectory=$OPTION" /DietPi/dietpi.txt
-							else
-								whiptail --title "Error: Invalid Path" --msgbox "Unable to create directory:\n - $OPTION\nNo changes have been applied." 10 60
+								# - Generate dir, check for valid.
+								mkdir -p "$OPTION"
+
+								if [ -d "$OPTION" ]; then
+									path_valid=1
+									sed -i "/^dietpi_userdata_basedirectory=/c\dietpi_userdata_basedirectory=$OPTION" /DietPi/dietpi.txt
+								fi
 							fi
+
+							# - Invalid path
+							if (( $path_valid == 0 )); then
+								whiptail --title "Error: Invalid Path" --msgbox "Unable to create directory:\n - $OPTION\n\nNo changes have been applied." 11 60
+							fi
+
 						fi
 
 					fi
