v140
Syncthing: https://github.com/Fourdee/DietPi/issues/652
+ inotify
+ update to latest ver
+ service update

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -4949,7 +4949,7 @@ _EOF_
 					#ARM32
 					else
 
-						AGI plexmediaserver
+						AGI plexmediaserver-installer
 
 					fi
 
@@ -5180,20 +5180,20 @@ _EOF_
 
 			Banner_Installing
 
-			#armv6+
+			# - armv6+
 			if (( $HW_ARCH >= 1 && $HW_ARCH < 10 )); then
 
-				INSTALL_URL_ADDRESS='https://github.com/syncthing/syncthing/releases/download/v0.14.9/syncthing-linux-arm-v0.14.9.tar.gz'
+				INSTALL_URL_ADDRESS='https://github.com/syncthing/syncthing/releases/download/v0.14.15/syncthing-linux-arm-v0.14.15.tar.gz'
 
-			#arm64
+			# - arm64
 			elif (( $HW_ARCH == 10 )); then
 
-				INSTALL_URL_ADDRESS='https://github.com/syncthing/syncthing/releases/download/v0.14.9/syncthing-linux-arm64-v0.14.9.tar.gz'
+				INSTALL_URL_ADDRESS='https://github.com/syncthing/syncthing/releases/download/v0.14.15/syncthing-linux-arm64-v0.14.15.tar.gz'
 
-			#x86_64
+			# - x86_64
 			elif (( $HW_ARCH == 21 )); then
 
-				INSTALL_URL_ADDRESS='https://github.com/syncthing/syncthing/releases/download/v0.14.9/syncthing-linux-amd64-v0.14.9.tar.gz'
+				INSTALL_URL_ADDRESS='https://github.com/syncthing/syncthing/releases/download/v0.14.15/syncthing-linux-amd64-v0.14.15.tar.gz'
 
 			fi
 
@@ -5202,8 +5202,6 @@ _EOF_
 
 			#/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
 			/DietPi/dietpi/func/check_connection https://github.com/syncthing/syncthing
-
-			#Install
 			if (( $? == 0 )); then
 
 				wget "$INSTALL_URL_ADDRESS" -O package.tar
@@ -5212,6 +5210,42 @@ _EOF_
 
 				mv syncthing-*/syncthing /usr/bin/
 				rm -R syncthing-*
+
+			else
+
+				Error_NoConnection_NoInstall
+
+			fi
+
+			#inotify
+			# - armv6+
+			if (( $HW_ARCH >= 1 && $HW_ARCH < 10 )); then
+
+				INSTALL_URL_ADDRESS='https://github.com/syncthing/syncthing-inotify/releases/download/v0.8.4/syncthing-inotify-linux-arm-v0.8.4.tar.gz'
+
+			# - arm64
+			elif (( $HW_ARCH == 10 )); then
+
+				INSTALL_URL_ADDRESS='https://github.com/syncthing/syncthing-inotify/releases/download/v0.8.4/syncthing-inotify-linux-arm-v0.8.4.tar.gz'
+
+			# - x86_64
+			elif (( $HW_ARCH == 21 )); then
+
+				INSTALL_URL_ADDRESS='https://github.com/syncthing/syncthing-inotify/releases/download/v0.8.4/syncthing-inotify-linux-amd64-v0.8.4.tar.gz'
+
+			fi
+
+			#??
+			#For some reason checking connection (spider) against the files above fails.
+
+			#/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+			/DietPi/dietpi/func/check_connection https://github.com/syncthing/syncthing-inotify
+
+			if (( $? == 0 )); then
+
+				wget "$INSTALL_URL_ADDRESS" -O package.tar
+				tar xzvf package.tar -C /usr/bin
+				rm package.tar
 
 			else
 
@@ -7261,11 +7295,11 @@ Type=forking
 StandardOutput=tty
 
 # These are run from dietpi-cloudshell and autostart
-ExecStartPre=/bin/bash -c 'setterm --term linux --blank 0 --powersave off' # Fails to set powersaving, must originate from tty
-ExecStartPre=/bin/bash -c 'tput civis'
+ExecStartPre=/usr/bin/setterm --term linux --blank 0 --powersave off
+ExecStartPre=/usr/bin/tput civis
 
 ExecStart=/bin/bash -c '/DietPi/dietpi/dietpi-cloudshell 1 &'
-ExecStop=/bin/bash -c 'setterm -reset'
+ExecStop=/usr/bin/setterm -reset
 ExecStop=/bin/bash -c '/DietPi/dietpi/func/dietpi-notify 0 DietPi-Cloudshell terminated, have a nice day!'
 
 [Install]
@@ -8730,23 +8764,44 @@ _EOF_
 			# - Disable browser starting
 			sed -i '/<\/startBrowser>/c\        <startBrowser>false<\/startBrowser>' "$HOME"/.config/syncthing/config.xml
 
-			# service
+			# services
 			cat << _EOF_ > /etc/systemd/system/syncthing.service
 [Unit]
 Description=Syncthing
+After=network.target
 
 [Service]
-Type=oneshot
-ExecStart=/bin/bash -c '/usr/bin/syncthing > /var/log/syncthing.log &'
-ExecStop=/usr/bin/killall -w syncthing
-RemainAfterExit=yes
+Type=simple
+ExecStart=/usr/bin/syncthing -logfile=/var/log/syncthing.log -logflags=3
 User=root
 
 [Install]
 WantedBy=multi-user.target
 _EOF_
-			systemctl enable syncthing.service
+
+			cat << _EOF_ > /etc/systemd/system/syncthing-inotify.service
+[Unit]
+Description=Syncthing Inotify File Watcher
+After=network.target syncthing.service
+Requires=syncthing.service
+
+[Service]
+User=root
+ExecStart=/usr/bin/syncthing-inotify -logfile=/var/log/syncthing-inotify.log -logflags=3
+SuccessExitStatus=2
+RestartForceExitStatus=3
+Restart=on-failure
+ProtectSystem=full
+ProtectHome=read-only
+
+[Install]
+WantedBy=multi-user.target
+_EOF_
+
 			systemctl daemon-reload
+
+			# - Increase open file limit:
+			echo -e "fs.inotify.max_user_watches=204800" | tee -a /etc/sysctl.conf
 
 		fi
 
