v124
+ Syncthing: https://github.com/Fourdee/DietPi/issues/422

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -426,6 +426,7 @@ CUBERITE=${CUBERITE:=0}
 MINEOS=${MINEOS:=0}
 GOGS=${GOGS:=0}
 QBITTORRENT=${QBITTORRENT:=0}
+SYNCTHING=${SYNCTHING:=0}
 
 #Additional Linux Software
 VIMFULL=${VIMFULL:=0}
@@ -2439,6 +2440,54 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 		if (( $QBITTORRENT == 1 )); then
 
 			AGI qbittorrent-nox
+
+		fi
+
+		#SYNCTHING
+		if (( $SYNCTHING == 1 )); then
+
+			INSTALL_DESCRIPTION='Syncthing'
+			Banner_Installing
+
+			#armv6+
+			if (( $HW_ARCH >= 1 && $HW_ARCH < 10 )); then
+
+				INSTALL_URL_ADDRESS='http://github.com/syncthing/syncthing/releases/download/v0.14.0/syncthing-linux-arm-v0.14.0.tar.gz'
+
+			#arm64
+			elif (( $HW_ARCH == 10 )); then
+
+				INSTALL_URL_ADDRESS='http://github.com/syncthing/syncthing/releases/download/v0.14.0/syncthing-linux-arm64-v0.14.0.tar.gz'
+
+			#x86_64
+			elif (( $HW_ARCH == 21 )); then
+
+				INSTALL_URL_ADDRESS='http://github.com/syncthing/syncthing/releases/download/v0.14.0/syncthing-linux-amd64-v0.14.0.tar.gz'
+			fi
+
+			#??
+			#For some reason checking connection (spider) against the files above fails.
+
+			#/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+			/DietPi/dietpi/func/check_connection http://github.com/syncthing/syncthing
+
+			#Install
+			if (( $? == 0 )); then
+
+				wget "$INSTALL_URL_ADDRESS" -O package.tar
+				tar xzvf package.tar
+				rm package.tar
+
+				mv syncthing-*/syncthing /usr/bin/
+				rm -R syncthing-*
+
+			else
+				Error_NoConnection_NoInstall
+
+				#Abort failed install
+				SYNCTHING=0
+			fi
+
 
 		fi
 
@@ -5501,6 +5550,42 @@ _EOF_
 
 		fi
 
+		#SYNCTHING
+		if (( $SYNCTHING == 1 )); then
+
+			# - run syncthing to create cert/config and exit
+			syncthing -generate="/$HOME/.config/syncthing"
+
+			# - Allow external access (LAN).
+			sed -i '/:8384<\/address>/c\        <address>0.0.0.0:8384<\/address>' "$HOME"/.config/syncthing/config.xml
+
+			# - Set default folder
+			sed -i '/label=\"Default Folder/c\    <folder id=\"0000-0000\" label=\"DietPi user data\" path=\"/mnt/dietpi_userdata/\" type=\"readwrite\" rescanIntervalS=\"60\" ignorePerms=\"false\" autoNormalize=\"true\">' "$HOME"/.config/syncthing/config.xml
+
+
+			# service
+			cat << _EOF_ > /etc/systemd/system/syncthing.service
+[Unit]
+Description=Syncthing
+
+[Service]
+Type=oneshot
+ExecStart=/bin/bash -c '/usr/bin/syncthing > /var/log/syncthing.log &'
+ExecStop=/usr/bin/killall -w syncthing
+RemainAfterExit=yes
+User=root
+
+[Install]
+WantedBy=multi-user.target
+_EOF_
+systemctl enable syncthing.service
+systemctl daemon-reload
+
+
+			SYNCTHING=2
+
+		fi
+
 	}
 
 	Install_Apply_GPU_Settings(){
@@ -7273,6 +7358,15 @@ _EOF_
 			fi
 		fi
 
+		local syncthing_w="off"
+		if (( $SYNCTHING > 0 )); then
+			syncthing_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $SYNCTHING == 1 )); then
+				SYNCTHING=0
+			fi
+		fi
+
 		#-----------------------------------------------------------------------------
 		WHIP_TITLE='DietPi Optimized Software Selection'
 
@@ -7304,6 +7398,7 @@ _EOF_
 			"" "────Cloud / Backups─────────────────────────" "off" \
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
+			"Syncthing" "Backup and sync server with web interface." $syncthing_w \
 			"" "────Gaming──────────────────────────────────" "off" \
 			"MineOS" "Minecraft Servers with web interface (Java)" $mineos_w \
 			"" "────Social Media───────────────────────────" "off" \
@@ -7380,6 +7475,7 @@ _EOF_
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
 			"Gogs" "Personal GitHub server with web interface" $gogs_w \
+			"Syncthing" "Backup and sync server with web interface." $syncthing_w \
 			"" "────Gaming──────────────────────────────────" "off" \
 			"Cuberite" "Minecraft Server with web interface (C++)" $cuberite_w \
 			"MineOS" "Minecraft Servers with web interface (Java)" $mineos_w \
@@ -7456,6 +7552,7 @@ _EOF_
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
 			"Gogs" "Personal GitHub server with web interface" $gogs_w \
+			"Syncthing" "Backup and sync server with web interface." $syncthing_w \
 			"" "────Gaming──────────────────────────────────" "off" \
 			"Cuberite" "Minecraft Server with web interface (C++)" $cuberite_w \
 			"MineOS" "Minecraft Servers with web interface (Java)" $mineos_w \
@@ -7528,6 +7625,7 @@ _EOF_
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
 			"Gogs" "Personal GitHub server with web interface" $gogs_w \
+			"Syncthing" "Backup and sync server with web interface." $syncthing_w \
 			"" "────Gaming──────────────────────────────────" "off" \
 			"Cuberite" "Minecraft Server with web interface (C++)" $cuberite_w \
 			"MineOS" "Minecraft Servers with web interface (Java)" $mineos_w \
@@ -7614,6 +7712,7 @@ _EOF_
 				"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 				"Pydio" "Feature-rich backup and sync server" $pydio_w \
 				"Gogs" "Personal GitHub server with web interface" $gogs_w \
+				"Syncthing" "Backup and sync server with web interface." $syncthing_w \
 				"" "────Gaming──────────────────────────────────" "off" \
 				"OpenTyrian" "Gaming: A classic retro game, addictive." $opentyrian_w \
 				"Cuberite" "Minecraft Server with web interface (C++)" $cuberite_w \
@@ -7747,6 +7846,12 @@ _EOF_
 		do
 			case $choice in
 
+			Syncthing)
+				if (( $SYNCTHING == 0 )); then
+					SYNCTHING=1
+					INSTALL_DIETPI_CHOICESMADE=1
+				fi
+			;;
 			qBitTorrent)
 				if (( $QBITTORRENT == 0 )); then
 					QBITTORRENT=1
