v142
+ DietPi-Backup additional modifications:
https://github.com/Fourdee/DietPi/issues/685

diff --git a/dietpi/dietpi-backup b/dietpi/dietpi-backup
--- a/dietpi/dietpi-backup
+++ b/dietpi/dietpi-backup
@@ -55,23 +55,30 @@
 	#TARGETMENUID=0
 	Menu_Main(){
 
-		local backup_last_completed='No previous backup found. Create one.'
-		if [ -f "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME" ]; then
-			backup_last_completed=$(grep '^Backup Completed' "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME" | tail -1 | awk '{print $3}')
+		local backup_last_completed_system='System backup not found. Create one.'
+		if [ -f "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM" ]; then
+			backup_last_completed_system=$(grep 'Completed' "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM" | tail -1)
 		fi
 
-		local text_include_userdata='Disabled | /mnt/dietpi_userdata NOT included in backups'
-		if (( $INCLUDE_DIETPI_USERDATA_DIR )); then
+		local backup_last_completed_userdata='User data backup not found (requires "Full" backup mode)'
+		if [ -f "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA" ]; then
+			backup_last_completed_userdata=$(grep 'Completed' "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA" | tail -1)
+		fi
 
-			text_include_userdata='Enabled | /mnt/dietpi_userdata included in backups'
+		local text_backup_mode='System only'
+		local text_start_mode_desc='system'
+		if (( $BACKUP_MODE == 1 )); then
+
+			text_backup_mode='Full'
+			text_start_mode_desc='system and user data'
 
 		fi
 
 		WHIP_TITLE='- DietPi-Backup -'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Current backup and restore location:\n  $FP_TARGET_BACKUP\n\nMost recent successful backup date:\n  $backup_last_completed" --cancel-button "Exit" --default-item "$MENU_LASTITEM" --backtitle "$WHIP_BACKTITLE" 17 83 5 \
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Current backup and restore location:\n  $FP_TARGET_BACKUP\n\nMost recent successful backup dates:\n  $backup_last_completed_system\n  $backup_last_completed_userdata" --cancel-button "Exit" --default-item "$MENU_LASTITEM" --backtitle "$WHIP_BACKTITLE" 18 80 5 \
 		"Help" "What does DietPi-Backup do?" \
 		"Location" "Change where your backup will be saved and restored from." \
-		"Include user data" ": $text_include_userdata" \
+		"Backup mode" ": $text_backup_mode" \
 		"Backup" "Create (or update) a backup of this system." \
 		"Restore" "Restore this system from a previous backup." 3>&1 1>&2 2>&3)
 
@@ -84,19 +91,15 @@
 				Location)
 					TARGETMENUID=1
 				;;
-				"Include user data")
+				"Backup mode")
 
-					((INCLUDE_DIETPI_USERDATA_DIR++))
-					if (( $INCLUDE_DIETPI_USERDATA_DIR >= 2 )); then
+					OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Please select a backup mode:\n\n - System Only\nOnly the system is backed up and restored, this does not include your DietPi user data (/mnt/dietpi_userdata).\n\n - Full:\nSystem and user data (/mnt/dietpi_userdata) is backed up and restored.\n\nMore information on what DietPi user data is:\nhttp://dietpi.com/phpbb/viewtopic.php?f=8&t=478#p2087" --cancel-button "Exit" --default-item "$BACKUP_MODE" --backtitle "$WHIP_BACKTITLE" 20 80 2 \
+					"0" "System only" \
+					"1" "Full (includes user data)" 3>&1 1>&2 2>&3)
+					CHOICE=$?
+					if (( $CHOICE == 0 )); then
 
-						INCLUDE_DIETPI_USERDATA_DIR=0
-
-					fi
-
-					# - inform user
-					if (( $INCLUDE_DIETPI_USERDATA_DIR )); then
-
-						whiptail --title "User Data Enabled" --msgbox "DietPi User data will be included in future backups:\n - /mnt/dietpi_userdata" --backtitle "$WHIP_BACKTITLE" 10 75
+						BACKUP_MODE=$OPTION
 
 					fi
 
@@ -105,16 +108,16 @@
 					whiptail --title "DietPi-Backup Help" --msgbox "DietPi-Backup is a program that allows you to Backup and Restore your DietPi system.\n\nIf you have broken your system, or want to reset your system to an eariler date, this can all be done with DietPi-Backup.\n\nSimply choose a location where you want to save and restore your backups from, then, select Backup or Restore.\n\nMore information:\n - http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=256#p255" --backtitle "$WHIP_BACKTITLE" 20 75
 				;;
 				Backup)
-					WHIP_TITLE=' Start system backup? '
-					whiptail --title "$WHIP_TITLE" --yesno "Your system will be backed up to:\n$FP_TARGET_BACKUP\n\nDo you wish to continue?" --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 11 65
+					WHIP_TITLE=' Start backup? '
+					whiptail --title "$WHIP_TITLE" --yesno "Your $text_start_mode_desc will be backed up to:\n$FP_TARGET_BACKUP\n\nDo you wish to continue?" --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 11 65
 					CHOICE=$?
 					if (( $CHOICE == 0 )); then
 						Run_Backup
 					fi
 				;;
 				Restore)
-					WHIP_TITLE=' Start system restore? '
-					whiptail --title "$WHIP_TITLE" --yesno "Your system will be restored from:\n$FP_TARGET_BACKUP\n\nDo you wish to continue?" --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 11 65
+					WHIP_TITLE=' Start restore? '
+					whiptail --title "$WHIP_TITLE" --yesno "Your $text_start_mode_desc will be restored from:\n$FP_TARGET_BACKUP\n\nDo you wish to continue?" --yes-button "Ok" --no-button "Back" --defaultno --backtitle "$WHIP_BACKTITLE" 11 65
 					CHOICE=$?
 					if (( $CHOICE == 0 )); then
 						Run_Restore
@@ -161,7 +164,7 @@
 				Search)
 					local fp_search_results="/tmp/.dietpi-backup_search_results"
 					echo -e "\n\nSearching /mnt/* for previous backups, please wait... \n \n"
-					find /mnt -type f -name "$BACKUP_STATS_FILENAME" > "$fp_search_results"
+					find /mnt -type f -name "$BACKUP_STATS_FILENAME_SYSTEM" > "$fp_search_results"
 
 					#Do we have any results?
 					if (( $(cat "$fp_search_results" | wc -l) > 0 )); then
@@ -171,7 +174,7 @@
 						for ((i=0; i<${#search_results_list[@]}; i++))
 						do
 							local last_backup_date=$( grep '^Backup Completed' ${search_results_list[$i]} | tail -1 | awk '{print $3}' ) # Date of last backup for this backup
-							local backup_directory=$( echo -e ${search_results_list[$i]} | sed 's/\/'"$BACKUP_STATS_FILENAME"'//g' ) # Backup directory (minus the backup file), that we can use for target backup directory.
+							local backup_directory=$( echo -e ${search_results_list[$i]} | sed 's/\/'"$BACKUP_STATS_FILENAME_SYSTEM"'//g' ) # Backup directory (minus the backup file), that we can use for target backup directory.
 							search_results_whiptail+=("$backup_directory" ": $last_backup_date")
 						done
 
@@ -266,7 +269,7 @@
 
 		/DietPi/dietpi/func/dietpi-notify 1 "Another Rsync process is already running."
 
-		echo -e "$RSYNC_MODE_TEXT failed: $(date +"%d-%m-%Y_%H%M"). Rsync is already running." >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
+		echo -e "$RSYNC_MODE_TEXT failed: $(date +"%d-%m-%Y_%H%M"). Rsync is already running." >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
 		#Menu
 		if (( $INPUT == 0 )); then
 			whiptail --title "$RSYNC_MODE_TEXT Error" --msgbox "A $RSYNC_MODE_TEXT could not be started as rsync is already running." --backtitle "$WHIP_BACKTITLE" 13 60
@@ -278,7 +281,7 @@
 
 		/DietPi/dietpi/func/dietpi-notify 1 "$RSYNC_MODE_TEXT failed."
 
-		echo -e "$RSYNC_MODE_TEXT Failed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
+		echo -e "$RSYNC_MODE_TEXT Failed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
 		#Menu
 		if (( $INPUT == 0 )); then
 			whiptail --title "$RSYNC_MODE_TEXT failed" --msgbox "Your $RSYNC_MODE_TEXT has failed. Please see the Log file for more information:\n\n$LOGFILE" --backtitle "$WHIP_BACKTITLE" 12 60
@@ -290,6 +293,7 @@
 	# Backup System
 	#/////////////////////////////////////////////////////////////////////////////////////
 	RSYNC_MODE_TEXT=0
+	BACKUP_MODE=0 #0=system only, 1=full (system and userdata)
 
 	#LOGFILE
 	LOGFILE="/var/log/dietpi-backup.log"
@@ -298,23 +302,18 @@
 	FP_SOURCE_SYSTEM="/"
 	FP_TARGET_BACKUP="/mnt/dietpi-backup"
 	FP_SOURCE_USERDATA_GLOBAL="/mnt/dietpi_userdata"
-	FP_SOURCE_USERDATA_ACTUAL="$(readlink /mnt/dietpi_userdata)"
-	if [ -z "$FP_SOURCE_USERDATA_ACTUAL" ]; then
-
-		FP_SOURCE_USERDATA_ACTUAL="$FP_SOURCE_USERDATA_GLOBAL"
-
-	fi
+	FP_SOURCE_USERDATA_ACTUAL="$(readlink -f /mnt/dietpi_userdata)"
 
 	FP_USB_HDD="/mnt/usb_1/dietpi-backup"
 
-	#file applied to successful backups (stored in "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
-	BACKUP_STATS_FILENAME=".dietpi-backup_stats"
+	#file applied to successful backups (stored in "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
+	BACKUP_STATS_FILENAME_SYSTEM=".dietpi-backup_system_stats"
+	BACKUP_STATS_FILENAME_USERDATA=".dietpi-backup_userdata_stats"
 
 	#Exclude/include file
 	FP_FILTER_INCLUDE_EXCLUDE_SYSTEM_BACKUP="/tmp/.dietpi-backup_filter_inc_exc"
 	FP_EXCLUDE_USER="/DietPi/dietpi/.dietpi-backup_exclude"
 	FP_INCLUDE_USER="/DietPi/dietpi/.dietpi-backup_include"
-	INCLUDE_DIETPI_USERDATA_DIR=0
 
 	#Supported filesystems
 	TARGET_FILESYSTEM_TYPE=0
@@ -331,6 +330,10 @@
 	#rsync options
 	RSYNC_RUN_OPTIONS_SYSTEM_BACKUP="-alHpvP --delete --log-file=$LOGFILE --include-from=$FP_FILTER_INCLUDE_EXCLUDE_SYSTEM_BACKUP"
 	RSYNC_RUN_OPTIONS_USERDATA_BACKUP="-alHpvP --delete --log-file=$LOGFILE"
+
+	#Sucessful backup/restore states
+	BACKUP_RESTORE_SYSTEM_SUCCESS=0
+	BACKUP_RESTORE_USERDATA_SUCCESS=0
 
 	Create_Filter_Include_Exclude(){
 
@@ -379,7 +382,7 @@ _EOF_
 #Global - Files
 - $LOGFILE
 - $FP_DIETPIBACKUP_SETTINGS
-- $BACKUP_STATS_FILENAME
+- $BACKUP_STATS_FILENAME_SYSTEM
 - /var/swap
 - fake-hwclock.data
 - *.tmp
@@ -455,30 +458,58 @@ _EOF_
 
 				/DietPi/dietpi/func/dietpi-notify 2 "Backing up to: $FP_TARGET_BACKUP"
 
-				rsync $RSYNC_RUN_OPTIONS_SYSTEM_BACKUP "$FP_SOURCE_SYSTEM" "$FP_TARGET_BACKUP"/dietpi-backup_system/
+				# - system
+				RSYNC_MODE_TEXT='Backup (system)'
+				BACKUP_RESTORE_SYSTEM_SUCCESS=1
 
-				# - userdata?
-				if (( $INCLUDE_DIETPI_USERDATA_DIR )); then
+				rsync $RSYNC_RUN_OPTIONS_SYSTEM_BACKUP "$FP_SOURCE_SYSTEM" "$FP_TARGET_BACKUP"/dietpi-backup_system/
+				if (( $? == 0 )); then
+
+
+					/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
+					echo -e "$RSYNC_MODE_TEXT Completed    : $(date +"%d-%m-%Y %H:%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
+
+				else
+
+					BACKUP_RESTORE_SYSTEM_SUCCESS=0
+					Error_Rsync_Failed
+
+				fi
+
+				# - userdata
+				RSYNC_MODE_TEXT='Backup (user data)'
+				BACKUP_RESTORE_USERDATA_SUCCESS=1
+
+				if (( $BACKUP_MODE == 1 )); then
 
 					rsync $RSYNC_RUN_OPTIONS_USERDATA_BACKUP "$FP_SOURCE_USERDATA_ACTUAL"/ "$FP_TARGET_BACKUP"/dietpi-backup_userdata/
+					if (( $? == 0 )); then
+
+
+						/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
+						echo -e "$RSYNC_MODE_TEXT Completed : $(date +"%d-%m-%Y %H:%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
+
+					else
+
+						Error_Rsync_Failed
+						BACKUP_RESTORE_USERDATA_SUCCESS=0
+
+					fi
+
+				fi
+
+				RSYNC_MODE_TEXT='Backup'
+				if (( $BACKUP_RESTORE_SYSTEM_SUCCESS && $BACKUP_RESTORE_USERDATA_SUCCESS )); then
+
+					if (( $INPUT == 0 )); then
+
+						whiptail --title "$RSYNC_MODE_TEXT completed" --msgbox "Your $RSYNC_MODE_TEXT was saved to:\n$FP_TARGET_BACKUP\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 11 60
+
+					fi
 
 				fi
 
 				Services_Start
-
-				#Success
-				if (( $? == 0 )); then
-					/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
-					echo -e "$RSYNC_MODE_TEXT Completed: $(date +"%d-%m-%Y_%H:%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
-					#Menu
-					if (( $INPUT == 0 )); then
-						whiptail --title "$RSYNC_MODE_TEXT completed" --msgbox "Your $RSYNC_MODE_TEXT was saved to:\n$FP_TARGET_BACKUP\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 11 60
-					fi
-
-				#Failed
-				else
-					Error_Rsync_Failed
-				fi
 
 				#return to main menu
 				TARGETMENUID=0
@@ -501,12 +532,12 @@ _EOF_
 		if (( $TARGET_DIRECTORY_SUPPORTED == 1 )); then
 
 			#Error: Backup not found
-			if [ ! -f "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME" ]; then
+			if [ ! -f "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM" ]; then
 
 				/DietPi/dietpi/func/dietpi-notify 2 "No Backup was found in $FP_TARGET_BACKUP"
 				/DietPi/dietpi/func/dietpi-notify 1 "$RSYNC_MODE_TEXT Failed.\n"
 				if (( $INPUT == 0 )); then
-					whiptail --title "$RSYNC_MODE_TEXT failed." --msgbox "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME does not exist\n\nHave you created a backup?" --backtitle "$WHIP_BACKTITLE" 11 70
+					whiptail --title "$RSYNC_MODE_TEXT failed." --msgbox "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM does not exist\n\nHave you created a backup?" --backtitle "$WHIP_BACKTITLE" 11 70
 				fi
 
 			#Error: Rsync is already running
@@ -524,30 +555,56 @@ _EOF_
 
 				/DietPi/dietpi/func/dietpi-notify 2 "Restoring from: $FP_TARGET_BACKUP"
 
-				rsync $RSYNC_RUN_OPTIONS_SYSTEM_BACKUP "$FP_TARGET_BACKUP"/dietpi-backup_system/ "$FP_SOURCE_SYSTEM"
+				# - System
+				RSYNC_MODE_TEXT='Restore (system)'
+				BACKUP_RESTORE_SYSTEM_SUCCESS=1
 
-				# - userdata?
-				if (( $INCLUDE_DIETPI_USERDATA_DIR )); then
+				rsync $RSYNC_RUN_OPTIONS_SYSTEM_BACKUP "$FP_TARGET_BACKUP"/dietpi-backup_system/ "$FP_SOURCE_SYSTEM"
+				if (( $? == 0 )); then
+
+					/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
+					echo -e "$RSYNC_MODE_TEXT Completed    : $(date +"%d-%m-%Y %H:%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
+
+				else
+
+					BACKUP_RESTORE_SYSTEM_SUCCESS=0
+					Error_Rsync_Failed
+
+				fi
+
+				# - User data
+				RSYNC_MODE_TEXT='Restore (user data)'
+				BACKUP_RESTORE_USERDATA_SUCCESS=1
+
+				if (( $BACKUP_MODE == 1 )); then
 
 					rsync $RSYNC_RUN_OPTIONS_USERDATA_BACKUP "$FP_TARGET_BACKUP"/dietpi-backup_userdata/ "$FP_SOURCE_USERDATA_ACTUAL"/
+					if (( $? == 0 )); then
+
+						/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
+						echo -e "$RSYNC_MODE_TEXT Completed : $(date +"%d-%m-%Y %H:%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
+
+					else
+
+						BACKUP_RESTORE_USERDATA_SUCCESS=0
+						Error_Rsync_Failed
+
+					fi
+
+				fi
+
+				RSYNC_MODE_TEXT='Restore'
+				if (( $BACKUP_RESTORE_SYSTEM_SUCCESS && $BACKUP_RESTORE_USERDATA_SUCCESS )); then
+
+					if (( $INPUT == 0 )); then
+
+						whiptail --title "$RSYNC_MODE_TEXT completed" --msgbox "$RSYNC_MODE_TEXT completed from:\n$FP_TARGET_BACKUP\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 11 60
+
+					fi
 
 				fi
 
 				Services_Start
-
-				#Success
-				if (( $? == 0 )); then
-					/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
-					echo -e "$RSYNC_MODE_TEXT Completed: $(date +"%d-%m-%Y_%H:%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
-					#Menu
-					if (( $INPUT == 0 )); then
-						whiptail --title "$RSYNC_MODE_TEXT completed" --msgbox "Your system has been restored from:\n$FP_TARGET_BACKUP.\n\nA reboot is highly recommended." --backtitle "$WHIP_BACKTITLE" 11 60
-					fi
-
-				#Failed
-				else
-					Error_Rsync_Failed
-				fi
 
 				#return to main menu
 				TARGETMENUID=0
@@ -644,7 +701,7 @@ _EOF_
 
 		cat << _EOF_ > "$FP_DIETPIBACKUP_SETTINGS"
 FP_TARGET_BACKUP=$FP_TARGET_BACKUP
-INCLUDE_DIETPI_USERDATA_DIR=$INCLUDE_DIETPI_USERDATA_DIR
+BACKUP_MODE=$BACKUP_MODE
 _EOF_
 
 	}
