v113

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -196,7 +196,8 @@
 	SQUEEZELITE=0
 	EMONCMS=0
 	EMONHUB=0
-	NODEJS=0
+	RPIMONITOR=0
+	BAIKAL=0
 
 	#Linux Software
 	INSTALL_LINUX_CHOICESMADE=false
@@ -210,6 +211,7 @@
 	CURLFTPFS=0
 	FFMPEG=0
 	ORACLEJAVA=0
+	NODEJS=0
 	SSHSERVER_DROPBEAR=2
 	SSHSERVER_OPENSSH=0
 	LOGGING_LOGROTATE=0
@@ -329,7 +331,8 @@ PYDIO $PYDIO
 SQUEEZELITE $SQUEEZELITE
 EMONHUB $EMONHUB
 EMONCMS $EMONCMS
-NODEJS $NODEJS
+RPIMONITOR $RPIMONITOR
+BAIKAL $BAIKAL
 
 
 #Additional Linux Software
@@ -344,6 +347,7 @@ XSERVERXORG $XSERVERXORG
 CURLFTPFS $CURLFTPFS
 FFMPEG $FFMPEG
 ORACLEJAVA $ORACLEJAVA
+NODEJS $NODEJS
 
 SSHSERVER_DROPBEAR $SSHSERVER_DROPBEAR
 SSHSERVER_OPENSSH $SSHSERVER_OPENSSH
@@ -439,7 +443,8 @@ _EOF_
 		SQUEEZELITE=$(cat "$FP_INSTALLED_FILE" | grep -m1 'SQUEEZELITE ' | awk '{print $2}')
 		EMONHUB=$(cat "$FP_INSTALLED_FILE" | grep -m1 'EMONHUB ' | awk '{print $2}')
 		EMONCMS=$(cat "$FP_INSTALLED_FILE" | grep -m1 'EMONCMS ' | awk '{print $2}')
-		NODEJS=$(cat "$FP_INSTALLED_FILE" | grep -m1 'NODEJS ' | awk '{print $2}')
+		RPIMONITOR=$(cat "$FP_INSTALLED_FILE" | grep -m1 'RPIMONITOR ' | awk '{print $2}')
+		BAIKAL=$(cat "$FP_INSTALLED_FILE" | grep -m1 'BAIKAL ' | awk '{print $2}')
 
 		#Linux
 		VIMFULL=$(cat "$FP_INSTALLED_FILE" | grep -m1 'VIMFULL ' | awk '{print $2}')
@@ -452,6 +457,7 @@ _EOF_
 		CURLFTPFS=$(cat "$FP_INSTALLED_FILE" | grep -m1 'CURLFTPFS ' | awk '{print $2}')
 		FFMPEG=$(cat "$FP_INSTALLED_FILE" | grep -m1 'FFMPEG ' | awk '{print $2}')
 		ORACLEJAVA=$(cat "$FP_INSTALLED_FILE" | grep -m1 'ORACLEJAVA ' | awk '{print $2}')
+		NODEJS=$(cat "$FP_INSTALLED_FILE" | grep -m1 'NODEJS ' | awk '{print $2}')
 
 		SSHSERVER_DROPBEAR=$(cat "$FP_INSTALLED_FILE" | grep -m1 'SSHSERVER_DROPBEAR ' | awk '{print $2}')
 		SSHSERVER_OPENSSH=$(cat "$FP_INSTALLED_FILE" | grep -m1 'SSHSERVER_OPENSSH ' | awk '{print $2}')
@@ -524,6 +530,8 @@ _EOF_
 		elif (( $PYDIO == 1 )); then
 			WEBSERVER_LAMP=1
 		elif (( $EMONCMS == 1 )); then
+			WEBSERVER_LAMP=1
+		elif (( $BAIKAL == 1 )); then
 			WEBSERVER_LAMP=1
 		fi
 
@@ -1805,6 +1813,60 @@ _EOF_
 
 				#Abort failed install
 				EMONHUB=0
+			fi
+
+		fi
+
+		#RPIMONITOR
+		if (( $RPIMONITOR == 1 )); then
+			INSTALL_DESCRIPTION='Rpi-Monitor'
+			Banner_Installing
+
+			#check, is online
+			INSTALL_URL_ADDRESS='https://github.com/XavierBerger/RPi-Monitor-deb/raw/master/packages/rpimonitor_2.9.1-1_all.deb'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+			#Install
+			if (( $? == 0 )); then
+
+				wget "$INSTALL_URL_ADDRESS" -O package.deb
+				dpkg -i package.deb
+				rm package.deb
+
+				# - Prereqs
+				apt-get -f -y install
+
+			else
+				Error_NoConnection_NoInstall
+
+				#Abort failed install
+				RPIMONITOR=0
+			fi
+
+		fi
+
+		#BAIKAL
+		if (( $BAIKAL == 1 )); then
+			INSTALL_DESCRIPTION='BaiKal'
+			Banner_Installing
+
+			#check folder is online
+			INSTALL_URL_ADDRESS='https://github.com/fruux/Baikal/archive/master.zip'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+			#Install
+			if (( $? == 0 )); then
+
+				wget "$INSTALL_URL_ADDRESS" -O package.zip
+				unzip package.zip -d /var/www
+				rm package.zip
+				mv /var/www/Baikal* /var/www/baikal
+
+			else
+				Error_NoConnection_NoInstall
+
+				#Abort failed install
+				BAIKAL=0
 			fi
 
 		fi
@@ -3974,6 +4036,44 @@ _EOF_
 
 		fi
 
+		#RPIMONITOR
+		if (( $RPIMONITOR == 1 )); then
+
+			# - Update apt package stats
+			/usr/share/rpimonitor/scripts/updatePackagesStatus.pl
+
+			# - Create a cron job to check this daily?
+
+			RPIMONITOR=2
+
+		fi
+
+		#BAIKAL
+		if (( $BAIKAL == 1 )); then
+
+			# - Permissions
+			chown -R www-data:www-data /var/www/baikal
+
+			# - install/run composer | Also run for ampache. Move this to a global function....
+			php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
+			php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === '41e71d86b40f28e771d4bb662b997f79625196afcca95a5abf44391188c695c6c1456e16154c75a211d238cc3bc5cb47') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
+			php composer-setup.php
+			php -r "unlink('composer-setup.php');"
+
+			mv composer.phar /usr/local/bin/composer
+
+			cd /var/www/baikal
+			composer install --no-interaction
+			cd ~/
+
+			# - Mysql DB
+			/DietPi/dietpi/func/create_mysql_db baikal dietpi root dietpi
+
+			BAIKAL=2
+
+		fi
+
+
 	}
 
 	Install_Apply_GPU_Settings(){
@@ -5401,6 +5501,26 @@ _EOF_
 			fi
 		fi
 
+		#RPIMONITOR
+		local rpimonitor_w="off"
+		if (( $RPIMONITOR > 0 )); then
+			rpimonitor_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $RPIMONITOR == 1 )); then
+				RPIMONITOR=0
+			fi
+		fi
+
+		#BAIKAL
+		local baikal_w="off"
+		if (( $BAIKAL > 0 )); then
+			baikal_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $BAIKAL == 1 )); then
+				BAIKAL=0
+			fi
+		fi
+
 		#-----------------------------------------------------------------------------
 		WHIP_TITLE='DietPi Optimized Software Selection'
 
@@ -5427,6 +5547,7 @@ _EOF_
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
 			"Image Gallery" "Website to host / browse your images." $phpimagegallery_w \
+			"BaiKal" "Lightweight CalDAV + CardDAV server." $baikal_w \
 			"" "────Remote Access───────────────────────────" "off" \
 			"Weaved" "Access your device over the internet." $weaved_w \
 			"" "────System Stats / Management──────────────" "off" \
@@ -5481,6 +5602,7 @@ _EOF_
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
 			"Image Gallery" "Website to host / browse your images." $phpimagegallery_w \
+			"BaiKal" "Lightweight CalDAV + CardDAV server." $baikal_w \
 			"" "────System Stats / Management──────────────" "off" \
 			"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
 			"LinuxDash" "Web interface system stats." $linuxdash_w \
@@ -5535,6 +5657,7 @@ _EOF_
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
 			"Image Gallery" "Website to host / browse your images." $phpimagegallery_w \
+			"BaiKal" "Lightweight CalDAV + CardDAV server." $baikal_w \
 			"" "────WiFi Hotspot────────────────────────────" "off" \
 			"WiFi Hotspot" "Turn your device into a wifi hotspot." $wifihotspot_w \
 			"" "────Remote Access───────────────────────────" "off" \
@@ -5603,6 +5726,7 @@ _EOF_
 				"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 				"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
 				"Image Gallery" "Website to host / browse your images." $phpimagegallery_w \
+				"BaiKal" "Lightweight CalDAV + CardDAV server." $baikal_w \
 				"" "────Camera / Surveillance───────────────────" "off" \
 				"DietPiCam" "RPi Cam Control / Web Interface Surveillance." $dietpicam_w \
 				"" "────WiFi Hotspot────────────────────────────" "off" \
@@ -5622,6 +5746,7 @@ _EOF_
 				"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
 				"LinuxDash" "Web interface system stats." $linuxdash_w \
 				"PhpSysInfo" "Web interface system stats." $phpsysinfo_w \
+				"RPi-Monitor" "Web interface system stats." $rpimonitor_w \
 				"" "────System Security────────────────────────" "off" \
 				"Fail2Ban" "Prevents brute-force attacks with IP ban." $fail2ban_w \
 				"" "────Webserver Stacks───────────────────────" "off" \
@@ -5723,6 +5848,18 @@ _EOF_
 		do
 			case $choice in
 
+			BaiKal)
+				if (( $BAIKAL == 0 )); then
+					BAIKAL=1
+					INSTALL_LINUX_CHOICESMADE=true
+				fi
+			;;
+			"RPi-Monitor")
+				if (( $RPIMONITOR == 0 )); then
+					RPIMONITOR=1
+					INSTALL_LINUX_CHOICESMADE=true
+				fi
+			;;
 			EmonHUB)
 				if (( $EMONHUB == 0 )); then
 					EMONHUB=1
