v100

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -215,6 +215,14 @@
 	INDEX_LOGGING_CURRENT=-1
 	INDEX_LOGGING_TARGET=-1
 
+	#apt-get install
+	AGI(){
+		apt-get install -y
+		if (( $? != 0 )); then
+			whiptail --title "apt-get error" --msgbox "Apt-get has failed:\n - Error code = $?\n - Software = $INSTALL_DESCRIPTION" --backtitle "$WHIP_BACKTITLE" 13 70
+		fi
+	}
+
 	Write_InstallFileList(){
 
 		##Write_InstallFileList   = write to /DietPi/dietpi/.installed
@@ -511,7 +519,7 @@
 			INSTALL_DESCRIPTION='Desktop (LXDE)'
 			Banner_Installing
 
-			apt-get install lxde upower policykit-1 iceweasel p7zip-full --no-install-recommends -y
+			$AGI lxde upower policykit-1 iceweasel p7zip-full --no-install-recommends
 			#upower policykit-1. Needed for LXDE logout menu item to show shutdown/restart ......
 
 		fi
@@ -520,7 +528,7 @@
 		if (( $TRANSMISSION == 1 )); then
 			INSTALL_DESCRIPTION='BitTorrent (Transmission)'
 			Banner_Installing
-			apt-get install transmission-daemon -y
+			$AGI transmission-daemon
 		fi
 
 		#ProFTPd
@@ -529,14 +537,14 @@
 			Banner_Installing
 
 			echo -e "proftpd-basic shared/proftpd/inetd_or_standalone select standalone" | debconf-set-selections
-			apt-get install proftpd-basic -y
+			$AGI proftpd-basic
 		fi
 
 		#Samba Server
 		if (( $FILESERVER_SAMBA == 1 )); then
 			INSTALL_DESCRIPTION='Samba File Server'
 			Banner_Installing
-			apt-get install samba samba-common-bin --no-install-recommends -y
+			$AGI samba samba-common-bin --no-install-recommends
 
 		fi
 
@@ -545,7 +553,7 @@
 			INSTALL_DESCRIPTION='FTP Server (vsFTPD)'
 			Banner_Installing
 
-			apt-get install vsftpd --no-install-recommends -y
+			$AGI vsftpd --no-install-recommends
 
 		fi
 
@@ -554,7 +562,7 @@
 
 			INSTALL_DESCRIPTION="$info_1: ($info_2) / $info_3 / $info_4"
 			Banner_Installing
-			apt-get install apache2 -y
+			$AGI apache2
 		fi
 
 		#WEBSERVER_NGINX
@@ -562,7 +570,7 @@
 
 			INSTALL_DESCRIPTION="$info_1: ($info_2) / $info_3 / $info_4"
 			Banner_Installing
-			apt-get install nginx xml-core --no-install-recommends -y
+			$AGI nginx xml-core --no-install-recommends
 		fi
 
 
@@ -574,14 +582,14 @@
 			echo -e "mysql-server mysql-server/root_password password raspberry" | debconf-set-selections
 			echo -e "mysql-server mysql-server/root_password_again password raspberry" | debconf-set-selections
 
-			apt-get install mysql-server -y
+			$AGI mysql-server
 		fi
 
 		#WEBSERVER_SQLITE
 		if (( $WEBSERVER_SQLITE == 1 )); then
 			INSTALL_DESCRIPTION="$info_1: $info_2 / ($info_3) / $info_4"
 			Banner_Installing
-			apt-get install sqlite3 -y
+			$AGI sqlite3
 		fi
 
 		#WEBSERVER_PHP
@@ -591,21 +599,21 @@
 
 			#Apache2 / Nginx
 			if (( $WEBSERVER_APACHE == 1 )); then
-				apt-get install php5 libapache2-mod-php5 -y
+				$AGI php5 libapache2-mod-php5
 			elif (( $WEBSERVER_NGINX == 1 )); then
-				apt-get install php5-fpm -y
+				$AGI php5-fpm
 			fi
 
 			#MySQL / SQLite
 			if (( $WEBSERVER_MYSQL == 1 )); then
-				apt-get install php5-mysql -y
+				$AGI php5-mysql
 			elif (( $WEBSERVER_SQLITE == 1 )); then
-				apt-get install php5-sqlite -y
+				$AGI php5-sqlite
 			fi
 
 			#Debian Wheezy - php-apc
 			if (( $DISTRO == 1 )); then
-				apt-get install php-apc -y
+				$AGI php-apc
 			fi
 
 		fi
@@ -627,7 +635,7 @@
 			echo -e "phpmyadmin      phpmyadmin/mysql/app-pass       password raspberry" | debconf-set-selections
 			echo -e "phpmyadmin      phpmyadmin/reconfigure-webserver        multiselect     apache2" | debconf-set-selections
 
-			apt-get install phpmyadmin -y
+			$AGI phpmyadmin
 
 		fi
 
@@ -639,7 +647,7 @@
 			#Mysql must be running during install to allow debconf setup.
 			service mysql start &> /dev/null
 
-			apt-get install phpbb3 -y
+			$AGI phpbb3
 		fi
 
 		#OwnCloud
@@ -669,7 +677,7 @@
 					/DietPi/dietpi/dietpi-apt-get_update 2
 				fi
 
-				apt-get install owncloud --force-yes -y
+				$AGI owncloud --force-yes
 
 			else
 				Info_NoConnection_NoInstall
@@ -693,7 +701,7 @@
 			if (( $? == 0 )); then
 
 				#Install MPD
-				apt-get install mpd libmpdclient2 -y
+				$AGI mpd libmpdclient2
 
 				#Setup ympd
 				wget "$INSTALL_URL_ADDRESS"
@@ -737,7 +745,7 @@
 						INSTALL_DESCRIPTION='Kodi (Michael Gorven Repo)'
 						Banner_Installing
 
-						apt-get install kodi -y
+						$AGI kodi
 
 					else
 						Info_NoConnection_NoInstall
@@ -750,13 +758,13 @@
 			#14.04
 			elif (( $DISTRO == 2 )); then
 
-				apt-get install libcurl4-gnutls-dev --no-install-recommends -y
-				apt-get install kodi -y
+				$AGI libcurl4-gnutls-dev --no-install-recommends
+				$AGI kodi
 
 			#Jessie
 			elif (( $DISTRO == 3 )); then
 
-				apt-get install kodi -y
+				$AGI kodi
 
 			fi
 		fi
@@ -765,7 +773,7 @@
 		if (( $MINIDLNA == 1 )); then
 			INSTALL_DESCRIPTION='DLNA/UPnP Media Server (MiniDLNA)'
 			Banner_Installing
-			apt-get install minidlna -y
+			$AGI minidlna
 		fi
 
 		#NoIp
@@ -857,7 +865,7 @@
 
 			#Install
 			if (( $? == 0 )); then
-				apt-get install ibsdl1.2debian libsdl-net1.2 --no-install-recommends -y
+				$AGI ibsdl1.2debian libsdl-net1.2 --no-install-recommends
 
 				#Download binaries and source
 				wget "$INSTALL_URL_ADDRESS"
@@ -889,7 +897,7 @@
 			if (( $? == 0 )); then
 
 				#Install pre-reqs
-				apt-get install gpac motion -y
+				$AGI gpac motion
 
 				#Get source/binaries and extract
 				wget "$INSTALL_URL_ADDRESS" -O File.zip
@@ -931,7 +939,7 @@
 		if (( $DELUGE == 1 )); then
 			INSTALL_DESCRIPTION='Deluge (BitTorrent Server, Web Interface)'
 			Banner_Installing
-			apt-get install deluged deluge-web deluge-webui deluge-console -y
+			$AGI deluged deluge-web deluge-webui deluge-console
 		fi
 
 		#GRASSHOPPER
@@ -939,7 +947,7 @@
 			INSTALL_DESCRIPTION='Grasshopper'
 			Banner_Installing
 
-			apt-get install python -y
+			$AGI python
 
 			#Download Grasshopper
 			local grasshopper_directory=$(cat /DietPi/dietpi.txt | grep -m1 'grasshopper_directory=' | sed 's/grasshopper_directory=//g')
@@ -1016,7 +1024,7 @@
 			if (( $? == 0 )); then
 
 				#Install DNS server
-				apt-get install dnsmasq -y
+				$AGI dnsmasq
 				service dnsmasq stop
 
 				#Generate PiHole Dirs
@@ -1067,15 +1075,15 @@
 			if (( $? == 0 )); then
 
 				#Install Pre-reqs
-				apt-get install lame -y
+				$AGI lame
 
 				#Java
 				# - 14.04
 				if (( $DISTRO == 2 )); then
-					apt-get install oracle-java8-installer --no-install-recommends -y
+					$AGI oracle-java8-installer --no-install-recommends
 				# - Wheezy/Jessie
 				else
-					apt-get install oracle-java8-jdk -y
+					$AGI oracle-java8-jdk
 				fi
 
 				#Install SubSonic
@@ -1123,7 +1131,7 @@
 			if (( $? == 0 )); then
 
 				#Python dev, pre-reqs
-				apt-get install python-dev python-setuptools --no-install-recommends -y
+				$AGI python-dev python-setuptools --no-install-recommends
 
 				#Install WEBIOPI
 				wget "$INSTALL_URL_ADDRESS" -O package.tar
@@ -1185,7 +1193,7 @@
 				cd haproxy-*
 
 				#Pre-reqs
-				apt-get install libpcre3-dev libssl-dev -y
+				$AGI libpcre3-dev libssl-dev
 				#Compile and install
 				#make -j "$(nproc)" TARGET=linux2628 CPU=generic USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_LINUX_SPLICE=1
 				make TARGET=linux2628 CPU=generic USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_LINUX_SPLICE=1
@@ -1270,7 +1278,7 @@
 			INSTALL_DESCRIPTION='VNC Server (Tight)'
 			Banner_Installing
 
-			apt-get install tightvncserver --no-install-recommends -y
+			$AGI tightvncserver --no-install-recommends
 
 		fi
 
@@ -1279,7 +1287,7 @@
 			INSTALL_DESCRIPTION='Fail2Ban'
 			Banner_Installing
 
-			apt-get install fail2ban --no-install-recommends -y
+			$AGI fail2ban --no-install-recommends
 
 		fi
 
@@ -1318,7 +1326,7 @@
 
 			#Install
 			if (( $? == 0 )); then
-				apt-get install php5-gd -y
+				$AGI php5-gd
 				wget "$INSTALL_URL_ADDRESS" -O package.zip
 				unzip package.zip -d /var/www/gallery
 				rm package.zip
@@ -1344,7 +1352,7 @@
 			#Install
 			if (( $? == 0 )); then
 
-				apt-get install php5-curl -y
+				$AGI php5-curl
 
 				wget "$INSTALL_URL_ADDRESS" -O package.tar
 				tar -xvf package.tar
@@ -1367,7 +1375,7 @@
 			INSTALL_DESCRIPTION='OpenVPN Server'
 			Banner_Installing
 
-			apt-get install openvpn easy-rsa iptables -y
+			$AGI openvpn easy-rsa iptables
 
 		fi
 
@@ -1381,7 +1389,7 @@
 		if (( $VIMFULL == 1 )); then
 			INSTALL_DESCRIPTION='Vim'
 			Banner_Installing
-			apt-get install vim -y
+			$AGI vim
 
 			VIMFULL=2
 		fi
@@ -1389,7 +1397,7 @@
 		if (( $SSHCLIENT == 1 )); then
 			INSTALL_DESCRIPTION='OpenSSH Client'
 			Banner_Installing
-			apt-get install openssh-client -y
+			$AGI openssh-client
 
 			SSHCLIENT=2
 		fi
@@ -1401,7 +1409,7 @@
 			#Remove Information file
 			rm /mnt/samba/readme.txt &> /dev/null
 
-			apt-get install smbclient cifs-utils -y --no-install-recommends
+			$AGI smbclient cifs-utils --no-install-recommends
 
 			SMBCLIENT=2
 		fi
@@ -1417,11 +1425,11 @@
 
 			#Wheezy
 			if (( $DISTRO == 1 )); then
-				apt-get install python-rpi.gpio python3-rpi.gpio -y
+				$AGI python-rpi.gpio python3-rpi.gpio
 
 			#Jessie - Use pip, as offical repo = python3-rpi.gpio: Depends: python3 (< 3.3) but 3.4.2-2 is to be installed
 			elif (( $DISTRO == 3 )); then
-				apt-get install python3-pip -y
+				$AGI python3-pip
 				pip3 install RPi.GPIO
 			fi
 
@@ -1448,7 +1456,7 @@
 		if (( $BUILDESSENTIAL == 1 )); then
 			INSTALL_DESCRIPTION='Build Essential'
 			Banner_Installing
-			 apt-get install build-essential --no-install-recommends -y
+			 $AGI build-essential --no-install-recommends
 
 			BUILDESSENTIAL=2
 		fi
@@ -1456,7 +1464,7 @@
 		if (( $GITCLIENT == 1 )); then
 			INSTALL_DESCRIPTION='Git'
 			Banner_Installing
-			apt-get install git --no-install-recommends -y
+			$AGI git --no-install-recommends
 
 			GITCLIENT=2
 		fi
@@ -1485,7 +1493,7 @@
 		if (( $ALSABASE == 1 )); then
 			INSTALL_DESCRIPTION='ALSA (Linux Sound System)'
 			Banner_Installing
-			apt-get install alsa-base alsa-utils -y
+			$AGI alsa-base alsa-utils
 
 			#rpi , enable HQ audio
 			sed -i '/avoid_pwm_pll=/c\avoid_pwm_pll=0' /DietPi/config.txt
@@ -1542,7 +1550,7 @@ _EOF_
 			#Xserver Prereqs (ALL)
 			INSTALL_DESCRIPTION='Xserver (Xinit / Xauth)'
 			Banner_Installing
-			apt-get install xinit xauth xserver-xorg xfonts-base x11-xserver-utils x11-common x11-utils --no-install-recommends -y
+			$AGI xinit xauth xserver-xorg xfonts-base x11-xserver-utils x11-common x11-utils --no-install-recommends
 
 			#RPI
 			if (( $HW_MODEL < 10 )); then
@@ -1551,7 +1559,7 @@ _EOF_
 
 				#Wheezy
 				if (( $DISTRO == 1 )); then
-					apt-get install xserver-xorg-video-fbturbo xserver-xorg-video-fbdev  --no-install-recommends -y
+					$AGI xserver-xorg-video-fbturbo xserver-xorg-video-fbdev  --no-install-recommends
 
 				#Jessie. Appears fbturbo is now apart of xserver-core. Either way, we dont need to install fbturbo for HW accel.
 				elif (( $DISTRO == 3 )); then
@@ -1562,7 +1570,7 @@ _EOF_
 			elif (( $HW_MODEL == 10 )); then
 				INSTALL_DESCRIPTION='Xserver (AMLogic VPU / MALI)'
 				Banner_Installing
-				apt-get install xterm aml-libs mali-x11 xserver-xorg-video-mali --no-install-recommends -y
+				$AGI xterm aml-libs mali-x11 xserver-xorg-video-mali --no-install-recommends
 
 				#cp /DietPi/dietpi/conf/xorg_c1-hk /etc/X11/xorg.conf
 
@@ -1602,7 +1610,7 @@ _EOF_
 			#Remove information file
 			rm /mnt/ftp_client/readme.txt &> /dev/null
 
-			apt-get install curlftpfs -y
+			$AGI curlftpfs
 
 			CURLFTPFS=2
 		fi
@@ -1612,7 +1620,7 @@ _EOF_
 
 			INSTALL_DESCRIPTION='Dropbear SSH Server'
 			Banner_Installing
-			apt-get install dropbear -y
+			$AGI dropbear
 
 			#set to start on next boot
 			sed -i '/NO_START=1/c\NO_START=0' /etc/default/dropbear
@@ -1625,7 +1633,7 @@ _EOF_
 
 			INSTALL_DESCRIPTION='OpenSSH Server'
 			Banner_Installing
-			apt-get install openssh-server --no-install-recommends -y
+			$AGI openssh-server --no-install-recommends
 
 			#14.04 and Jessie, must enable root login
 			if (( $DISTRO == 2 )) || (( $DISTRO == 3 )); then
@@ -1655,7 +1663,7 @@ _EOF_
 
 			INSTALL_DESCRIPTION='Logrotate'
 			Banner_Installing
-			apt-get install logrotate -y
+			$AGI logrotate
 
 			LOGGING_LOGROTATE=2
 		fi
@@ -1671,7 +1679,7 @@ _EOF_
 
 			INSTALL_DESCRIPTION='Rsyslog'
 			Banner_Installing
-			apt-get install rsyslog --no-install-recommends -y
+			$AGI rsyslog --no-install-recommends
 
 			LOGGING_RSYSLOG=2
 
@@ -1692,7 +1700,7 @@ _EOF_
 			#Wheezy
 			if (( $DISTRO == 1 )); then
 
-				apt-get install ffmpeg -y
+				$AGI ffmpeg
 
 			#Ubuntu 14.04 (Odroid's armv7)
 			elif (( $DISTRO == 2 )); then
@@ -1704,7 +1712,7 @@ _EOF_
 				#Skip Compile if binary is already installed
 				if [ ! -f /usr/local/bin/ffmpeg ]; then
 
-					apt-get install build-essential libmp3lame-dev libvorbis-dev libtheora-dev libspeex-dev yasm pkg-config libfaac-dev libopenjpeg-dev libx264-dev -y
+					$AGI build-essential libmp3lame-dev libvorbis-dev libtheora-dev libspeex-dev yasm pkg-config libfaac-dev libopenjpeg-dev libx264-dev
 
 					INSTALL_URL_ADDRESS='http://ffmpeg.org/releases/ffmpeg-2.7.2.tar.bz2'
 					wget "$INSTALL_URL_ADDRESS" -O package.tar
@@ -1741,16 +1749,16 @@ _EOF_
 					rm package.deb
 
 					#Install pre-reqs
-					apt-get install libogg0 libvorbisenc2 libtheora0 libspeex1 libopencore-amrwb0 libopencore-amrnb0 libass5 -y
+					$AGI libogg0 libvorbisenc2 libtheora0 libspeex1 libopencore-amrwb0 libopencore-amrnb0 libass5
 
 				#Add Deb Multimedia repo for ffmpeg
 				elif (( $(cat /etc/apt/sources.list | grep -ci -m1 "http://www.deb-multimedia.org") == 0 )); then
 
 					echo -e "deb http://www.deb-multimedia.org jessie main non-free" >> /etc/apt/sources.list
 					/DietPi/dietpi/dietpi-apt-get_update 2
-					apt-get install deb-multimedia-keyring -y --force-yes
+					$AGI deb-multimedia-keyring --force-yes
 					/DietPi/dietpi/dietpi-apt-get_update 2
-					apt-get install ffmpeg -y
+					$AGI ffmpeg
 
 				fi
 			fi
@@ -1967,6 +1975,7 @@ _EOF_
 			ln -sf /DietPi/dietpi/conf/desktop/dietpi-sync.desktop /usr/share/applications/dietpi-sync.desktop
 			ln -sf /DietPi/dietpi/conf/desktop/dietpi-bugreport.desktop /usr/share/applications/dietpi-bugreport.desktop
 			ln -sf /DietPi/dietpi/conf/desktop/dietpi-nice.desktop /usr/share/applications/dietpi-nice.desktop
+			ln -sf /DietPi/dietpi/conf/desktop/dietpi-cleaner.desktop /usr/share/applications/dietpi-cleaner.desktop
 
 			DESKTOP_LXDE=2
 		fi
@@ -3025,8 +3034,8 @@ _EOF_
 			#Client config
 			cat << _EOF_ > /etc/openvpn/easy-rsa/keys/DietPi_OpenVPN_Client.ovpn
 client
-dev tun
 proto udp
+dev tun
 
 #Ip/Domain name of DietPi system, running OpenVPN server.
 remote mywebsite.com 1194
@@ -3187,7 +3196,7 @@ _EOF_
 		#Upgrade Apt
 		Banner_Setup
 		Banner_Apt_Update
-		apt-get upgrade -y
+		apt-get upgrade
 
 		#Apply DietPi choice systems
 		Apply_FileServer_Choices
