v6.3
+ DietPi-Software | NTPD check will now run after the internet
connection test, to prevent unnecessary delay when network is not yet
configured

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -150,71 +150,73 @@ _EOF_
 
 	}
 
-	Check_NTPD_Status(){
+	Check_Internet_and_NTPD(){
 
-		if (( $(route | awk '{print $4}' | grep -ci -m1 'UG') )); then
+		#Internet
+		# - Use /etc/apt/sources.list for connection test
+		local internet_url_test=$(grep -m1 'deb ' /etc/apt/sources.list | awk '{print $2}')
+		G_CHECK_URL "$internet_url_test" #will exit on failure here then prompt user to configure network
 
-			while true
-			do
+		#NTPD
+		while true
+		do
 
-				/DietPi/dietpi/func/run_ntpd status
-				if (( $? != 0 )); then
+			/DietPi/dietpi/func/run_ntpd status
+			if (( $? != 0 )); then
 
-					#	Endless retry
-					if (( ! $G_USER_INPUTS )); then
+				#	Endless retry
+				if (( ! $G_USER_INPUTS )); then
 
-						Reset_NTPD
+					Reset_NTPD
 
-					#	Ask
-					else
+				#	Ask
+				else
 
-						G_WHIP_MENU_ARRAY=(
+					G_WHIP_MENU_ARRAY=(
 
-							'Retry' ': (Recommended) Runs the NTPD update again'
-							'Mirror' ': Allows you to change the NTPD mirror used'
-							'NTPD Mode' ': Change NTPD mode (eg: Systemd-timesyncd)'
-							'Override' ': (NOT RECOMMENDED) override NTPD and system clock update'
+						'Retry' ': (Recommended) Runs the NTPD update again'
+						'Mirror' ': Allows you to change the NTPD mirror used'
+						'NTPD Mode' ': Change NTPD mode (eg: Systemd-timesyncd)'
+						'Override' ': (NOT RECOMMENDED) override NTPD and system clock update'
 
-						)
+					)
 
-						G_WHIP_MENU "NTPD timesync has not yet completed, or, failed to update.\nTo prevent issues with outdated system time during installations, please select an option below.\n\nNB: We highly recommend choosing 'Retry' first. Failing that, 'mirror' then 'mode'.\n'Override' is a last resort and may cause future issues due to incorrect system clock time."
-						if (( $? == 0 )); then
+					G_WHIP_MENU "NTPD timesync has not yet completed, or, failed to update.\nTo prevent issues with outdated system time during installations, please select an option below.\n\nNB: We highly recommend choosing 'Retry' first. Failing that, 'mirror' then 'mode'.\n'Override' is a last resort and may cause future issues due to incorrect system clock time."
+					if (( $? == 0 )); then
 
-							if [ "$G_WHIP_RETURNED_VALUE" = 'Retry' ]; then
+						if [ "$G_WHIP_RETURNED_VALUE" = 'Retry' ]; then
 
-								Reset_NTPD
+							Reset_NTPD
 
-							elif [ "$G_WHIP_RETURNED_VALUE" = 'Mirror' ]; then
+						elif [ "$G_WHIP_RETURNED_VALUE" = 'Mirror' ]; then
 
-								G_WHIP_MSG 'DietPi-Config will now be launched, on the next screen:\n - Select "NTPD Mirror"\n - Select a different NTPD mirror\n\nOnce completed, exit dietpi-config to resume setup'
-								/DietPi/dietpi/dietpi-config 16 1
+							G_WHIP_MSG 'DietPi-Config will now be launched, on the next screen:\n - Select "NTPD Mirror"\n - Select a different NTPD mirror\n\nOnce completed, exit dietpi-config to resume setup'
+							/DietPi/dietpi/dietpi-config 16 1
 
-							elif [ "$G_WHIP_RETURNED_VALUE" = 'NTPD Mode' ]; then
+						elif [ "$G_WHIP_RETURNED_VALUE" = 'NTPD Mode' ]; then
 
-								G_WHIP_MSG 'DietPi-Config will now be launched, on the next screen:\n - Select "Time Sync Mode"\n - Select a different time sync mode (eg: Daemon + Drift)\n\nOnce completed, exit dietpi-config to resume setup'
-								/DietPi/dietpi/dietpi-config 3 1
+							G_WHIP_MSG 'DietPi-Config will now be launched, on the next screen:\n - Select "Time Sync Mode"\n - Select a different time sync mode (eg: Daemon + Drift)\n\nOnce completed, exit dietpi-config to resume setup'
+							/DietPi/dietpi/dietpi-config 3 1
 
-							elif [ "$G_WHIP_RETURNED_VALUE" = 'Override' ]; then
+						elif [ "$G_WHIP_RETURNED_VALUE" = 'Override' ]; then
 
-								Reset_NTPD
-								echo 0 > /var/lib/dietpi/.ntpd_exit_status
-								echo 1 > /var/lib/dietpi/.ntpd_override
-
-							fi
+							Reset_NTPD
+							echo 0 > /var/lib/dietpi/.ntpd_exit_status
+							echo 1 > /var/lib/dietpi/.ntpd_override
 
 						fi
 
 					fi
 
-				else
-
-					break
-
 				fi
 
-			done
+			else
 
-		fi
+				break
+
+			fi
+
+		done
 
 	}
 
@@ -13607,8 +13609,8 @@ _EOF_
 	Run_Installations(){
 
 		#------------------------------------------------------------
-		#Abort if time sync is incomplete
-		Check_NTPD_Status
+		#Prevent continue if no Network or NTPD is not completed: https://github.com/Fourdee/DietPi/issues/786
+		Check_Internet_and_NTPD
 		#------------------------------------------------------------
 		#Disable powersaving on Main screen during installation
 		setterm -blank 0 -powersave off 2> /dev/null
@@ -13925,18 +13927,6 @@ _EOF_
 			Exit_Destroy
 
 		fi
-
-	}
-
-	#/////////////////////////////////////////////////////////////////////////////////////
-	# Internet Connection Test Vars
-	#/////////////////////////////////////////////////////////////////////////////////////
-	#Use /etc/apt/sources.list for connection test
-	INTERNET_URL_TEST=$(grep -m1 'deb ' /etc/apt/sources.list | awk '{print $2}')
-
-	Check_Internet_Connection(){
-
-		G_CHECK_URL "$INTERNET_URL_TEST" #will exit on failure here
 
 	}
 
@@ -15555,14 +15545,11 @@ _EOF_
 
 		Banner_Setup
 
-		#Prevent continue if NTPD is not completed: https://github.com/Fourdee/DietPi/issues/786
-		Check_NTPD_Status
+		# - Prevent continue if no Network or NTPD is not completed: https://github.com/Fourdee/DietPi/issues/786
+		Check_Internet_and_NTPD
 
-		#1st run Connection test and DietPi updates
-		#NB: Contains EXIT path
+		#1st run DietPi updates
 		if (( $(cat /DietPi/dietpi/.update_stage) == -1 )); then
-
-			Check_Internet_Connection
 
 			FirstRun_DietPi_Update
 
@@ -15614,8 +15601,6 @@ _EOF_
 			Exit_Destroy
 
 		fi
-
-		Check_Internet_Connection
 
 		#Start installations for software
 		Run_Installations
