v118

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -285,6 +285,7 @@ RPIMONITOR=${RPIMONITOR:=0}
 NETDATA=${NETDATA:=0}
 BAIKAL=${BAIKAL:=0}
 MUMBLESERVER=${MUMBLESERVER:=0}
+EMBYSERVER=${EMBYSERVER:=0}
 
 
 #Additional Linux Software
@@ -326,7 +327,7 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 
 "
 
-		echo "$output"_ > "$FP_INSTALLED_FILE"
+		echo "$output" > "$FP_INSTALLED_FILE"
 	}
 
 	Read_InstallFileList(){
@@ -1843,6 +1844,55 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 
 		fi
 
+		#EMBYSERVER
+		if (( $EMBYSERVER == 1 )); then
+			INSTALL_DESCRIPTION='Emby Server'
+			Banner_Installing
+
+			local url_tests=0
+
+			#check is online
+			INSTALL_URL_ADDRESS='http://download.opensuse.org/repositories/home:/emby/Debian_8.0'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+			if (( $? == 0 )); then
+
+				INSTALL_URL_ADDRESS='http://download.mono-project.com/repo/debian'
+				/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+				if (( $? == 0 )); then
+
+					url_tests=1
+
+				fi
+
+			fi
+
+			#install
+			if (( $url_tests == 1 )); then
+
+				# - Alternative mono repo: https://github.com/Fourdee/DietPi/issues/310#issuecomment-216247879
+				apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
+				echo -e "deb http://download.mono-project.com/repo/debian wheezy main" > /etc/apt/sources.list.d/mono-xamarin.list
+				echo -e "deb http://download.mono-project.com/repo/debian wheezy-libjpeg62-compat main" >> /etc/apt/sources.list.d/mono-xamarin.list
+
+
+				# - Emby repo
+				wget http://download.opensuse.org/repositories/home:emby/Debian_8.0/Release.key
+				apt-key add - < Release.key
+				echo -e "deb http://download.opensuse.org/repositories/home:/emby/Debian_8.0/ /" > /etc/apt/sources.list.d/emby-server.list
+				apt-get update
+
+				AGI emby-server
+
+			else
+				Error_NoConnection_NoInstall
+
+				#Abort failed install
+				EMBYSERVER=0
+			fi
+
+		fi
 
 	}
 
@@ -4220,6 +4270,13 @@ _EOF_
 
 		fi
 
+		#EMBYSERVER
+		if (( $EMBYSERVER == 1 )); then
+
+			EMBYSERVER=2
+
+		fi
+
 	}
 
 	Install_Apply_GPU_Settings(){
@@ -5758,6 +5815,16 @@ _EOF_
 			fi
 		fi
 
+		#EMBYSERVER
+		local embyserver_w="off"
+		if (( $EMBYSERVER > 0 )); then
+			embyserver_w="on"
+			#Reset to 0.  Menu checklists will apply back to 1
+			if (( $EMBYSERVER == 1 )); then
+				EMBYSERVER=0
+			fi
+		fi
+
 		#-----------------------------------------------------------------------------
 		WHIP_TITLE='DietPi Optimized Software Selection'
 
@@ -5832,6 +5899,7 @@ _EOF_
 			"SubSonic" "Web interface media streaming server." $subsonic_w \
 			"Ampache" "Web interface media streaming server." $ampache_w \
 			"Murmur" "Mumble VoIP server." $mumbleserver_w \
+			"Emby Server" "Web interface media streaming server." $embyserver_w \
 			"" "────BitTorrent─────────────────────────────" "off" \
 			"Transmission" "BitTorrent server with web interface." $transmission_w \
 			"Deluge" "BitTorrent server with web interface." $deluge_w \
@@ -5958,6 +6026,7 @@ _EOF_
 				"Shairport Sync" "AirPlay audio player with multiroom sync" $shairportsync_w \
 				"BruteFIR" "EQ and Digital Room Correction via ALSA." $brutefir_w \
 				"Murmur" "Mumble VoIP server." $mumbleserver_w \
+				"Emby Server" "Web interface media streaming server." $embyserver_w \
 				"" "────BitTorrent──────────────────────────────" "off" \
 				"Transmission" "BitTorrent server with web interface." $transmission_w \
 				"Deluge" "BitTorrent server with web interface." $deluge_w \
@@ -6096,88 +6165,94 @@ _EOF_
 		do
 			case $choice in
 
+			"Emby Server")
+				if (( $EMBYSERVER == 0 )); then
+					EMBYSERVER=1
+					INSTALL_DIETPI_CHOICESMADE=true
+				fi
+			;;
 			Murmur)
 				if (( $MUMBLESERVER == 0 )); then
 					MUMBLESERVER=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			"Tor Hotspot")
 				if (( $TORHOTSPOT == 0 )); then
 					TORHOTSPOT=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			BaiKal)
 				if (( $BAIKAL == 0 )); then
 					BAIKAL=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			"RPi-Monitor")
 				if (( $RPIMONITOR == 0 )); then
 					RPIMONITOR=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			EmonHUB|EmonPi)
 				if (( $EMONHUB == 0 )); then
 					EMONHUB=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			EmonCMS)
 				if (( $EMONCMS == 0 )); then
 					EMONCMS=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			Redis)
 				if (( $WEBSERVER_REDIS == 0 )); then
 					WEBSERVER_REDIS=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			SqueezeLite)
 				if (( $SQUEEZELITE == 0 )); then
 					SQUEEZELITE=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			Pydio)
 				if (( $PYDIO == 0 )); then
 					PYDIO=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			BruteFIR)
 				if (( $BRUTEFIR == 0 )); then
 					BRUTEFIR=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			"Shairport Sync")
 				if (( $SHAIRPORTSYNC == 0 )); then
 					SHAIRPORTSYNC=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			"WiFi Hotspot")
 				if (( $WIFIHOTSPOT == 0 )); then
 					WIFIHOTSPOT=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			RPi.GPIO)
 				if (( $RPIGPIO == 0 )); then
 					RPIGPIO=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			I2c)
 				if (( $RPII2C == 0 )); then
 					RPII2C=1
-					INSTALL_LINUX_CHOICESMADE=true
+					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
 			WiringPi)
