v121
+ Gogs: https://github.com/Fourdee/DietPi/issues/391
+ c2 updated boot.ini (to patch or not to patch, that is the question)?

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -329,6 +329,7 @@ OPENBAZAAR=${OPENBAZAAR:=0}
 PLEXMEDIASERVER=${PLEXMEDIASERVER:=0}
 CUBERITE=${CUBERITE:=0}
 MINEOS=${MINEOS:=0}
+GOGS=${GOGS:=0}
 
 
 #Additional Linux Software
@@ -714,6 +715,15 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 			INSTALL_DESCRIPTION="$info_1: ($info_2) / $info_3 / $info_4"
 			Banner_Installing
 			AGI lighttpd
+		fi
+
+		#Programs that require just MYSQL or MARIADB
+		if (( ! $WEBSERVER_MYSQL && ! $WEBSERVER_MARIADB )); then
+
+			if (( $GOGS == 1 )); then
+				WEBSERVER_MYSQL=1
+			fi
+
 		fi
 
 		#WEBSERVER_MYSQL
@@ -2252,6 +2262,47 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 
 		fi
 
+		#GOGS
+		if (( $GOGS == 1 )); then
+			INSTALL_DESCRIPTION='Gogs (Personal GitHub)'
+			Banner_Installing
+
+			#armv6
+			if (( $HW_ARCH == 1 )); then
+
+				INSTALL_URL_ADDRESS='http://dl.gogs.io/gogs_v0.9.13_linux_arm.zip'
+
+			#armv7+
+			elif (( $HW_ARCH >= 2 && $HW_ARCH < 10 )); then
+
+				INSTALL_URL_ADDRESS='http://dl.gogs.io/gogs_v0.9.13_raspi2.zip'
+
+			#x86_64
+			elif (( $HW_ARCH == 21 )); then
+
+				INSTALL_URL_ADDRESS='http://dl.gogs.io/gogs_v0.9.13_linux_amd64.zip'
+			fi
+
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+			#Install
+			if (( $? == 0 )); then
+
+				wget "$INSTALL_URL_ADDRESS" -O package.zip
+				unzip package.zip
+				rm package.zip
+
+				mv gogs* /etc/gogs
+
+			else
+				Error_NoConnection_NoInstall
+
+				#Abort failed install
+				GOGS=0
+			fi
+
+		fi
+
 	}
 
 	Install_Linux_Software(){
@@ -2461,6 +2512,8 @@ _EOF_
 		elif (( $OPENBAZAAR == 1 )); then
 			GITCLIENT=1
 		elif (( $MINEOS == 1 )); then
+			GITCLIENT=1
+		elif (( $GOGS == 1 )); then
 			GITCLIENT=1
 		fi
 
@@ -5081,6 +5134,47 @@ _EOF_
 
 		fi
 
+		#GOGS
+		if (( $GOGS == 1 )); then
+
+			# - Data storage / user data
+			mkdir -p "$DIETPI_USERDATA_DIRECTORY"/gogs-repo
+
+			# - sqldb
+			/DietPi/dietpi/func/create_mysql_db gogs dietpi root dietpi
+
+			# - service (couldnt get this to run as a new thread with systemD (&). so bash script ftw.
+			cat << _EOF_ > /etc/gogs/start.sh
+#!/bin/bash
+#Simple script to start gogs for DietPi systems
+/etc/gogs/gogs web &> /var/log/gogs_daemon.log &
+exit
+_EOF_
+
+			chmod +x /etc/gogs/start.sh
+
+			cat << _EOF_ > /etc/systemd/system/gogs.service
+[Unit]
+Description=DietPi Gogs service
+DefaultDependencies=no
+
+[Service]
+Type=oneshot
+RemainAfterExit=yes
+User=root
+ExecStart=/bin/bash /etc/gogs/start.sh
+ExecStop=/usr/bin/killall -w gogs
+StandardOutput=tty
+
+[Install]
+WantedBy=multi-user.target
+_EOF_
+
+
+			GOGS=2
+
+		fi
+
 	}
 
 	Install_Apply_GPU_Settings(){
@@ -5117,67 +5211,104 @@ _EOF_
 		#Mode 3
 		if (( $memory_split_mode == 3 )); then
 
+			#Odroid C2
+			if (( $HW_MODEL == 12 )); then
+
+				sed -i '/setenv nographics /c\setenv nographics "0"' /DietPi/boot.ini
+
 			#odroid C1
-			if (( $HW_MODEL == 10 )); then
+			elif (( $HW_MODEL == 10 )); then
+
 				sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
 				sed -i '/setenv vpu /c\setenv vpu "1"' /DietPi/boot.ini
 				sed -i '/setenv m_bpp /c\setenv m_bpp "32"' /DietPi/boot.ini
+
 			#rpi
 			elif (( $HW_MODEL < 10 )); then
+
 				sed -i '/gpu_mem_256=/c\gpu_mem_256=128' /DietPi/config.txt
 				sed -i '/gpu_mem_512=/c\gpu_mem_512=128' /DietPi/config.txt
 				sed -i '/gpu_mem_1024=/c\gpu_mem_1024=128' /DietPi/config.txt
 				sed -i "/rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt
+
 			fi
 
 		#Mode 2
 		elif (( $memory_split_mode == 2 )); then
 
+			#Odroid C2
+			if (( $HW_MODEL == 12 )); then
+
+				sed -i '/setenv nographics /c\setenv nographics "0"' /DietPi/boot.ini
+
 			#odroid C1
-			if (( $HW_MODEL == 10 )); then
+			elif (( $HW_MODEL == 10 )); then
+
 				sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
 				sed -i '/setenv vpu /c\setenv vpu "1"' /DietPi/boot.ini
 				sed -i '/setenv m_bpp /c\setenv m_bpp "32"' /DietPi/boot.ini
+
 			#rpi
 			elif (( $HW_MODEL < 10 )); then
+
 				sed -i '/gpu_mem_256=/c\gpu_mem_256=64' /DietPi/config.txt
 				sed -i '/gpu_mem_512=/c\gpu_mem_512=64' /DietPi/config.txt
 				sed -i '/gpu_mem_1024=/c\gpu_mem_1024=64' /DietPi/config.txt
 				sed -i "/rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt
+
 			fi
 
 		#Mode 1 - DietPi-Cloudshell
 		elif (( $memory_split_mode == 1 )); then
 
+			#Odroid C2
+			if (( $HW_MODEL == 12 )); then
+
+				sed -i '/setenv nographics /c\setenv nographics "0"' /DietPi/boot.ini
+
 			#odroid C1
-			if (( $HW_MODEL == 10 )); then
+			elif (( $HW_MODEL == 10 )); then
+
 				sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
 				sed -i '/setenv m_bpp /c\setenv m_bpp "16"' /DietPi/boot.ini
+
 			#rpi
 			elif (( $HW_MODEL < 10 )); then
+
 				sed -i '/framebuffer_width=/c\framebuffer_width=320' /DietPi/config.txt
 				sed -i '/framebuffer_height=/c\framebuffer_height=240' /DietPi/config.txt
 				sed -i '/gpu_mem_256=/c\gpu_mem_256=16' /DietPi/config.txt
 				sed -i '/gpu_mem_512=/c\gpu_mem_512=16' /DietPi/config.txt
 				sed -i '/gpu_mem_1024=/c\gpu_mem_1024=16' /DietPi/config.txt
 				sed -i "/rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt
+
 			fi
 
 		#Mode 0
 		elif (( $memory_split_mode == 0 )); then
 
+			#Odroid C2
+			if (( $HW_MODEL == 12 )); then
+
+				echo -e "nothing here" &> /dev/null
+				#sed -i '/setenv nographics /c\setenv nographics "1"' /DietPi/boot.ini
+				#nographics is actually "headless", no output.
+
 			#odroid C1
-			if (( $HW_MODEL == 10 )); then
+			elif (( $HW_MODEL == 10 )); then
+
 				#sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
 				sed -i '/setenv vpu /c\setenv vpu "0"' /DietPi/boot.ini
 				sed -i '/setenv m_bpp /c\setenv m_bpp "16"' /DietPi/boot.ini
 
 			#rpi
 			elif (( $HW_MODEL < 10 )); then
+
 				sed -i '/gpu_mem_256=/c\gpu_mem_256=16' /DietPi/config.txt
 				sed -i '/gpu_mem_512=/c\gpu_mem_512=16' /DietPi/config.txt
 				sed -i '/gpu_mem_1024=/c\gpu_mem_1024=16' /DietPi/config.txt
 				#sed -i "/rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt
+
 			fi
 
 		fi
@@ -6796,6 +6927,15 @@ _EOF_
 			fi
 		fi
 
+		local gogs_w="off"
+		if (( $GOGS > 0 )); then
+			gogs_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $GOGS == 1 )); then
+				GOGS=0
+			fi
+		fi
+
 		#-----------------------------------------------------------------------------
 		WHIP_TITLE='DietPi Optimized Software Selection'
 
@@ -6856,7 +6996,7 @@ _EOF_
 			"LLSP" "Webserver: Lighttpd | SQLite  | Php." $webserver_llsp_w \
 			"LLAP" "Webserver: Lighttpd | MariaDB | Php." $webserver_llap_w \
 			"phpMyAdmin" "Optional MySql admin tools." $webserver_phpmyadmin_w \
-			"LetsEncrypt" "Free, auto SSL cert install allowing https://" $letsencrypt_w \
+			"CertBot" "Free, auto SSL cert install allowing https://" $letsencrypt_w \
 			"" "────DNS Servers────────────────────────────" "off" \
 			"Pi-hole" "Block adverts for any device on your network." $pihole_w \
 			"" "────File Servers───────────────────────────" "off" \
@@ -6898,6 +7038,7 @@ _EOF_
 			"" "────Cloud / Backups─────────────────────────" "off" \
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
+			"Gogs" "Personal GitHub server with web interface" $gogs_w \
 			"" "────Gaming──────────────────────────────────" "off" \
 			"Cuberite" "Minecraft Server with web interface (C++)" $cuberite_w \
 			"MineOS" "Minecraft Servers with web interface (Java)" $mineos_w \
@@ -6927,7 +7068,7 @@ _EOF_
 			"LLSP" "Webserver: Lighttpd | SQLite  | Php." $webserver_llsp_w \
 			"LLAP" "Webserver: Lighttpd | MariaDB | Php." $webserver_llap_w \
 			"phpMyAdmin" "Optional MySql admin tools." $webserver_phpmyadmin_w \
-			"LetsEncrypt" "Free, auto SSL cert install allowing https://" $letsencrypt_w \
+			"CertBot" "Free, auto SSL cert install allowing https://" $letsencrypt_w \
 			"" "────DNS Servers────────────────────────────" "off" \
 			"Pi-hole" "Block adverts for any device on your network." $pihole_w \
 			"" "────File Servers───────────────────────────" "off" \
@@ -6968,6 +7109,7 @@ _EOF_
 			"" "────Cloud / Backups────────────────────────" "off" \
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
+			"Gogs" "Personal GitHub server with web interface" $gogs_w \
 			"" "────Gaming──────────────────────────────────" "off" \
 			"Cuberite" "Minecraft Server with web interface (C++)" $cuberite_w \
 			"MineOS" "Minecraft Servers with web interface (Java)" $mineos_w \
@@ -6994,7 +7136,7 @@ _EOF_
 			"LLSP" "Webserver: Lighttpd | SQLite  | Php." $webserver_llsp_w \
 			"LLAP" "Webserver: Lighttpd | MariaDB | Php." $webserver_llap_w \
 			"phpMyAdmin" "Optional MySql admin tools." $webserver_phpmyadmin_w \
-			"LetsEncrypt" "Free, auto SSL cert install allowing https://" $letsencrypt_w \
+			"CertBot" "Free, auto SSL cert install allowing https://" $letsencrypt_w \
 			"" "────DNS Servers────────────────────────────" "off" \
 			"Pi-hole" "Block adverts for any device on your network." $pihole_w \
 			"" "────File Servers───────────────────────────" "off" \
@@ -7037,6 +7179,7 @@ _EOF_
 			"" "────Cloud / Backups─────────────────────────" "off" \
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
+			"Gogs" "Personal GitHub server with web interface" $gogs_w \
 			"" "────Gaming──────────────────────────────────" "off" \
 			"Cuberite" "Minecraft Server with web interface (C++)" $cuberite_w \
 			"MineOS" "Minecraft Servers with web interface (Java)" $mineos_w \
@@ -7069,7 +7212,7 @@ _EOF_
 			"LLSP" "Webserver: Lighttpd | SQLite  | Php." $webserver_llsp_w \
 			"LLAP" "Webserver: Lighttpd | MariaDB | Php." $webserver_llap_w \
 			"phpMyAdmin" "Optional MySql admin tools." $webserver_phpmyadmin_w \
-			"LetsEncrypt" "Free, auto SSL cert install allowing https://" $letsencrypt_w \
+			"CertBot" "Free, auto SSL cert install allowing https://" $letsencrypt_w \
 			"" "────DNS Servers────────────────────────────" "off" \
 			"Pi-hole" "Block adverts for any device on your network." $pihole_w \
 			"" "────File Servers───────────────────────────" "off" \
@@ -7120,6 +7263,7 @@ _EOF_
 				"" "────Cloud / Backups─────────────────────────" "off" \
 				"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 				"Pydio" "Feature-rich backup and sync server" $pydio_w \
+				"Gogs" "Personal GitHub server with web interface" $gogs_w \
 				"" "────Gaming──────────────────────────────────" "off" \
 				"OpenTyrian" "Gaming: A classic retro game, addictive." $opentyrian_w \
 				"Cuberite" "Minecraft Server with web interface (C++)" $cuberite_w \
@@ -7165,7 +7309,7 @@ _EOF_
 				"LLAP" "Webserver: Lighttpd | MariaDB | Php." $webserver_llap_w \
 				"phpMyAdmin" "Optional MySql admin tools." $webserver_phpmyadmin_w \
 				"Redis" "Optional non-SQL database store." $webserver_redis_w \
-				"LetsEncrypt" "Free, auto SSL cert install allowing https://" $letsencrypt_w \
+				"CertBot" "Free, auto SSL cert install allowing https://" $letsencrypt_w \
 				"" "────DNS Servers────────────────────────────" "off" \
 				"Pi-hole" "Block adverts for any device on your network." $pihole_w \
 				"" "────File Servers───────────────────────────" "off" \
@@ -7253,6 +7397,12 @@ _EOF_
 		do
 			case $choice in
 
+			Gogs)
+				if (( $GOGS == 0 )); then
+					GOGS=1
+					INSTALL_DIETPI_CHOICESMADE=1
+				fi
+			;;
 			MineOS)
 				if (( $MINEOS == 0 )); then
 					MINEOS=1
@@ -7391,7 +7541,7 @@ _EOF_
 					INSTALL_DIETPI_CHOICESMADE=1
 				fi
 			;;
-			LetsEncrypt)
+			CertBot)
 				if (( $LETSENCRYPT == 0 )); then
 					LETSENCRYPT=1
 					INSTALL_DIETPI_CHOICESMADE=1
@@ -7830,7 +7980,7 @@ _EOF_
 		#LetsEncrypt
 		if (( $LETSENCRYPT == 1 )); then
 			WHIP_TITLE='Lets Encrypt Info'
-			WHIP_QUESTION='Currently, the DietPi installation of Lets Encrypt supports Apache2 (LAMP / LASP) only.\n\nOnce the installation has finished, you can setup your free SSL cert with:\n - DietPi-LetsEncrypt\n\nThis is a easy to use frontend for Lets Encrypt and allows intergration into DietPi systems.\n\nMore information:\n - http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=1061#p1062'
+			WHIP_QUESTION='Currently, the DietPi installation of CertBot supports Apache2 (LAMP / LASP) only.\n\nOnce the installation has finished, you can setup your free SSL cert with:\n - DietPi-LetsEncrypt\n\nThis is a easy to use frontend for CertBot and allows intergration into DietPi systems.\n\nMore information:\n - http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=1061#p1062'
 			whiptail --title "$WHIP_TITLE" --msgbox "$WHIP_QUESTION" --backtitle "$WHIP_BACKTITLE" 18 70
 		fi
 
