dietpi-software: LazyLibrarian: polish
* Add to software test script
* Add to dietpi-survey report page
* Add changelog entry
* Align intentations
* Download better compressed bzip2 archive instead of gzip
* Install static files and venv to /opt/lazylibrarian, since LazyLibrarian does not require write, and it allows simpler clean updates
* Use /mnt/dietpi_userdata/lazylibrarian as data directory instead
* Skip service user home directory and service working directory, since both do not seem to have any effect
* Use "dietpi" as primary group to grant access to default DietPi downloads and ebooks directories, as well as downloads
* Do not permit the "dietpi" group access to the LazyLibrarian data directory
* Create a default config with download/ebooks/audiobooks directory suggestions, and logs to /var/log/lazylibrarian
* Start service after download servers and add permissions/sandbox hardening to align with Servarr applications
* Add credits link to readme
* Add workarounds for unnecessary update attempt on first start and attempt to remove (nonexisting) bundled libraries on shutdown.
* piwheels provides Debian Trixie/Python 3.13 wheels now, hence update dependencies

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -737,13 +737,13 @@ Available commands:
 		aSOFTWARE_CATX[$software_id]=3
 		aSOFTWARE_DOCS[$software_id]='https://dietpi.com/docs/software/bittorrent/#youtube-dl'
 		aSOFTWARE_DEPS[$software_id]='7'
-    #------------------
-    software_id=169
-    aSOFTWARE_NAME[$software_id]='LazyLibrarian'
-    aSOFTWARE_DESC[$software_id]='Ebook and audiobook collection manager'
-    aSOFTWARE_CATX[$software_id]=3
-    aSOFTWARE_DOCS[$software_id]='https://dietpi.com/docs/software/' # TBD: add docs
-    aSOFTWARE_DEPS[$software_id]='130'
+		#------------------
+		software_id=169
+		aSOFTWARE_NAME[$software_id]='LazyLibrarian'
+		aSOFTWARE_DESC[$software_id]='Ebook and audiobook collection manager'
+		aSOFTWARE_CATX[$software_id]=3
+		aSOFTWARE_DOCS[$software_id]='https://dietpi.com/docs/software/bittorrent/#lazylibrarian'
+		aSOFTWARE_DEPS[$software_id]='130'
 
 		# Cloud & Backup
 		#--------------------------------------------------------------------------------
@@ -2604,13 +2604,13 @@ sudo sysctl -p /etc/sysctl.d/dietpi-$1.conf"
 			local install=0 user rust=0 piwheels=0
 
 			# Can piwheels be used?
-			if (( $G_HW_MODEL < 3 ))
+			if (( $G_HW_ARCH < 3 ))
 			then
 				if [[ $PYTHON_VERSION ]]
 				then
-					dpkg --compare-version "$PYTHON_VERSION" lt '3.12' && piwheels=1
+					dpkg --compare-version "$PYTHON_VERSION" lt '3.14' && piwheels=1
 				else
-					(( $G_DISTRO < 8 )) && piwheels=1
+					piwheels=1
 				fi
 			fi
 			unset -v PYTHON_VERSION
@@ -2625,9 +2625,9 @@ sudo sysctl -p /etc/sysctl.d/dietpi-$1.conf"
 					'av') (( $G_HW_ARCH < 3 || $G_HW_ARCH == 11 )) && aDEPS+=('libavdevice-dev');;
 					'bcrypt') (( $G_HW_ARCH == 11 )) && rust=1;;
 					'brotli'|'sabctools'|'ujson') (( $G_HW_ARCH == 11 || ( $G_HW_ARCH < 3 && ! $piwheels ) )) && aDEPS+=('g++');;
-					'cffi') (( $G_HW_ARCH == 11 || ( $G_HW_ARCH < 3 && ! $piwheels ) )) && aDEPS+=('gcc' 'libffi-dev');;
+					'cffi') (( $G_HW_ARCH == 11 || ( $G_HW_ARCH < 3 && ( ! $piwheels || $G_DISTRO > 7 ) ) )) && aDEPS+=('gcc' 'libffi-dev');; # piwheels Trixie build failed
 					'cryptography')
-						if (( $G_HW_ARCH == 1 || $G_HW_ARCH == 11 ))
+						if (( ( $G_HW_ARCH == 1 && ! $piwheels ) || $G_HW_ARCH == 11 ))
 						then
 							aDEPS+=('pkg-config' 'libssl-dev')
 							rust=1
@@ -2644,7 +2644,14 @@ sudo sysctl -p /etc/sysctl.d/dietpi-$1.conf"
 						# cmake > ninja > meson-python > numpy
 						(( $G_HW_ARCH == 1 || $G_HW_ARCH == 11 )) && aDEPS+=('cmake' 'make' 'automake')
 					;;
-					'pillow') (( $G_HW_ARCH < 3 || $G_HW_ARCH == 11 )) && aDEPS+=('gcc' 'libjpeg62-turbo-dev');;
+					'pillow')
+						(( $G_HW_ARCH == 11 || ( $G_HW_ARCH < 3 && ! $piwheels ) )) && aDEPS+=('gcc' 'libjpeg62-turbo-dev')
+						if (( $piwheels ))
+						then
+							aDEPS+=('libopenjp2-7' 'libxcb1')
+							(( $G_DISTRO > 6 )) && aDEPS+=('libtiff6') || aDEPS+=('libtiff5')
+						fi
+					;;
 					'poetry')
 						# cryptography > SecretStorage > keyring > poetry
 						set -- "$@" cryptography
@@ -2654,7 +2661,7 @@ sudo sysctl -p /etc/sysctl.d/dietpi-$1.conf"
 					'pycurl') (( $G_HW_ARCH == 11 || ( $G_HW_ARCH < 3 && ! $piwheels ) )) && aDEPS+=('gcc' 'libcurl4-openssl-dev' 'libssl-dev');;
 					'pydantic')
 						# pydantic_core > pydantic
-						(( $G_HW_ARCH == 1 || $G_HW_ARCH == 11 )) && rust=1
+						(( ( $G_HW_ARCH == 1 && ! $piwheels ) || $G_HW_ARCH == 11 )) && rust=1
 					;;
 					'pyenv')
 						# Required: gcc libc6-dev make libssl-dev zlib1g-dev
@@ -12028,48 +12035,78 @@ WantedBy=multi-user.target
 _EOF_
 		fi
 
-    if To_Install 169 lazylibrarian # LazyLibrarian
-    then
-      # Dependencies for venv
-      aDEPS=('python3-venv')
+		if To_Install 169 lazylibrarian # LazyLibrarian
+		then
+			# Dependencies
+			aDEPS=('python3-venv')
+			Python_Deps cryptography pillow
 
-      # Create user and data dir
+			# Download
+			Download_Install 'https://gitlab.com/LazyLibrarian/LazyLibrarian/-/archive/master/LazyLibrarian-master.tar.bz2'
+
+			# Add dummy unbundled.libs to prevent unnecessary attempt to remove bundled libraries which do not exist. It is falsely determined since the venv is inside the install dir.
+			> LazyLibrarian-master/unbundled.libs
+
+			# Install: Clear existing instance
+			[[ -d '/opt/lazylibrarian' ]] && G_EXEC rm -R /opt/lazylibrarian
+			G_EXEC mv LazyLibrarian-master /opt/lazylibrarian
+
+			# Python venv
+			G_EXEC python3 -m venv /opt/lazylibrarian/venv
+			G_EXEC_OUTPUT=1 G_EXEC /opt/lazylibrarian/venv/bin/pip install /opt/lazylibrarian
+
+			# User
+			Create_User -g dietpi lazylibrarian
+
+			# Data directory
 			G_EXEC mkdir -p /mnt/dietpi_userdata/lazylibrarian
-			Create_User -d /mnt/dietpi_userdata/lazylibrarian lazylibrarian
+			G_EXEC chmod 0750 /mnt/dietpi_userdata/lazylibrarian
 
-      # Download and unpack to /mnt/dietpi_userdata/lazylibrarian/LazyLibrarian-master
-			Download_Install 'https://gitlab.com/LazyLibrarian/LazyLibrarian/-/archive/master/LazyLibrarian-master.tar.gz' /mnt/dietpi_userdata/lazylibrarian
-      # Set permissions
-      G_EXEC chown -R 'lazylibrarian:lazylibrarian' -R /mnt/dietpi_userdata/lazylibrarian
-			G_EXEC chmod 0770 /mnt/dietpi_userdata/lazylibrarian
+			# Config: Preserve existing
+			[[ -f '/mnt/dietpi_userdata/lazylibrarian/config.ini' ]] || G_EXEC eval 'cat << '\''_EOF_'\'' > /mnt/dietpi_userdata/lazylibrarian/config.ini
+[GENERAL]
+ebook_dir = /mnt/dietpi_userdata/ebooks
+audio_dir = /mnt/dietpi_userdata/audiobooks
+download_dir = /mnt/dietpi_userdata/downloads
 
-      # Python venv and install
-      G_EXEC sudo -u lazylibrarian python3 -m venv /mnt/dietpi_userdata/lazylibrarian/venv
-      G_EXEC_OUTPUT=1 sudo -u lazylibrarian /mnt/dietpi_userdata/lazylibrarian/venv/bin/python3 -m pip install -e /mnt/dietpi_userdata/lazylibrarian/LazyLibrarian-master
+[LOGGING]
+logdir = /var/log/lazylibrarian
+_EOF_'
+			# Add version info to prevent unnecessary update attempt on first service start of fresh install and make update checks meaningful
+			G_EXEC mkdir -p /mnt/dietpi_userdata/lazylibrarian/cache
+			curl -sSfL 'https://gitlab.com/api/v4/projects/9317860/repository/commits?per_page=1' | mawk -F\" '{print $8}' > /mnt/dietpi_userdata/lazylibrarian/cache/version.txt
 
-      # Service
-cat << '_EOF_' > /etc/systemd/system/lazylibrarian.service
+			# Permissions
+			G_EXEC chown -R 'lazylibrarian' /mnt/dietpi_userdata/lazylibrarian
+
+			# Service: https://gitlab.com/LazyLibrarian/LazyLibrarian/-/blob/master/init
+			cat << '_EOF_' > /etc/systemd/system/lazylibrarian.service
 [Unit]
 Description=LazyLibrarian
 Documentation=https://lazylibrarian.gitlab.io
 Wants=network-online.target
-After=network-online.target
+After=network-online.target remote-fs.target transmission-daemon.service qbittorrent.service rtorrent.service nzbget.service deluged.service aria2.service sabnzbd.service
 
 [Service]
+SyslogIdentifier=LazyLibrarian
 User=lazylibrarian
-Group=lazylibrarian
-WorkingDirectory=/mnt/dietpi_userdata/lazylibrarian/LazyLibrarian-master
-ExecStart=/mnt/dietpi_userdata/lazylibrarian/venv/bin/python3 /mnt/dietpi_userdata/lazylibrarian/LazyLibrarian-master/LazyLibrarian.py
-Restart=always
+UMask=002
+LogsDirectory=lazylibrarian
+ExecStart=/opt/lazylibrarian/venv/bin/python /opt/lazylibrarian/LazyLibrarian.py --datadir=/mnt/dietpi_userdata/lazylibrarian --nolaunch
 
-StandardOutput=journal
-StandardError=journal
+# Hardening
+ProtectSystem=strict
+ProtectHome=true
+PrivateDevices=true
+PrivateTmp=true
+ProtectKernelTunables=true
+ProtectControlGroups=true
+ReadWritePaths=-/opt/lazylibrarian -/mnt -/media -/var/log/lazylibrarian -/tmp
 
 [Install]
 WantedBy=multi-user.target
 _EOF_
-
-    fi
+		fi
 	}
 
 	# $1: 0=None -1=Dropbear -2=OpenSSH
@@ -14187,11 +14224,13 @@ _EOF_
 			[[ -d '/mnt/dietpi_userdata/soju' ]] &&	G_EXEC rm -Rf /mnt/dietpi_userdata/soju
 		fi
 
-    if To_Uninstall 169 # LazyLibrarian
-    then
-      Remove_Service lazylibrarian 1 1
-      [[ -d '/mnt/dietpi_userdata/lazylibrarian' ]] && G_EXEC rm -Rf /mnt/dietpi_userdata/lazylibrarian
-    fi
+		if To_Uninstall 169 # LazyLibrarian
+		then
+			Remove_Service lazylibrarian 1 1
+			G_EXEC rm -Rf /opt/lazylibrarian
+			G_EXEC rm -Rf /var/log/lazylibrarian
+			G_EXEC rm -Rf /mnt/dietpi_userdata/lazylibrarian
+		fi
 
 		G_DIETPI-NOTIFY 3 "$G_PROGRAM_NAME" 'Finalising uninstall'
 
