v118
- Seperate Odroid C2 optimized software list
- Finishing off OpenBazaar

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -743,33 +743,60 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 			INSTALL_DESCRIPTION='OpenBazaar'
 			Banner_Installing
 
-			AGI autoconf pkg-config libtool libssl-dev libffi-dev python-dev openssl python-pip libzmq3-dev
+			INSTALL_URL_ADDRESS='https://github.com/OpenBazaar/OpenBazaar-Server.git'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+			#Install
 
-			#Not required.
-			#AGI software-properties-common
-			#add-apt-repository -y ppa:chris-lea/libsodium
-			#apt-get update
+			if (( $? == 0 )); then
 
-			AGI libsodium-dev
+				AGI libsodium-dev autoconf pkg-config libtool libssl-dev libffi-dev python-dev openssl python-pip libzmq3-dev
 
-			pip install cryptography
+				#Not required.
+				#AGI software-properties-common
+				#add-apt-repository -y ppa:chris-lea/libsodium
+				#apt-get update
 
-			cd "$HOME"
-			git clone --depth 1 https://github.com/zeromq/libzmq
-			git clone --depth 1 https://github.com/pyca/pynacl/
-			git clone --depth 1 https://github.com/OpenBazaar/OpenBazaar-Server.git
+				pip install cryptography
 
-			cd libzmq
-			./autogen.sh && ./configure && make -j "$(nproc --all)"
-			make check && make install && ldconfig
 
-			cd "$HOME"
-			cd pynacl
-			python setup.py build && python setup.py install
+				cd "$HOME"
+				git clone --depth 1 https://github.com/zeromq/libzmq
+				git clone --depth 1 https://github.com/pyca/pynacl/
+				git clone --depth 1 "$INSTALL_URL_ADDRESS"
 
-			cd "$HOME"
-			cd OpenBazaar-Server
-			pip install -r requirements.txt
+				# - compile
+				cd "$HOME"/libzmq
+				./autogen.sh && ./configure && make -j "$(nproc --all)"
+				make check && make install && ldconfig
+
+				cd "$HOME"/pynacl
+				python setup.py build && python setup.py install
+
+				cd "$HOME"
+
+				# - Move OpenBazaar to a 'better' location
+				mkdir -p /etc/openbazaar-server
+				mv "$HOME"/OpenBazaar-Server/* /etc/openbazaar-server/
+				rm -R "$HOME"/OpenBazaar-Server
+
+				# - install OpenBazaar
+				cd /etc/openbazaar-server
+				pip install -r requirements.txt
+
+				cd "$HOME"
+
+				# - Clean up, remove source libaries
+				rm -R "$HOME"/libzmq
+				rm -R "$HOME"/pynacl
+
+
+			else
+
+				Error_NoConnection_NoInstall
+				OPENBAZAAR=0
+
+			fi
+
 
 		fi
 
@@ -3115,7 +3142,12 @@ _EOF_
 		#OPENBAZAAR
 		if (( $OPENBAZAAR == 1 )); then
 
+			# - service
+			cp /DietPi/dietpi/conf/openbazaar-server.service /etc/dietpi/dietpi-software/services/openbazaar-server.service
+			chmod +x /etc/dietpi/dietpi-software/services/openbazaar-server.service
+
 			OPENBAZAAR=2
+
 		fi
 
 
@@ -6068,7 +6100,6 @@ _EOF_
 			"Transmission" "BitTorrent server with web interface." $transmission_w \
 			"Deluge" "BitTorrent server with web interface." $deluge_w \
 			"" "────Cloud / Backups─────────────────────────" "off" \
-			"OpenBazaar" "Your very own store (eg: ebay)." $openbazaar_w \
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
 			"" "────Social Media───────────────────────────" "off" \
@@ -6076,6 +6107,7 @@ _EOF_
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
 			"Image Gallery" "Website to host / browse your images." $phpimagegallery_w \
 			"BaiKal" "Lightweight CalDAV + CardDAV server." $baikal_w \
+			"OpenBazaar" "Decentralized peer to peer Bitcoin market." $openbazaar_w \
 			"" "────Remote Access───────────────────────────" "off" \
 			"Weaved" "Access your device over the internet." $weaved_w \
 			"" "────System Stats / Management──────────────" "off" \
@@ -6128,7 +6160,6 @@ _EOF_
 			"Transmission" "BitTorrent server with web interface." $transmission_w \
 			"Deluge" "BitTorrent server with web interface." $deluge_w \
 			"" "────Cloud / Backups────────────────────────" "off" \
-			"OpenBazaar" "Your very own store (eg: ebay)." $openbazaar_w \
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
 			"" "────Social Media───────────────────────────" "off" \
@@ -6136,6 +6167,7 @@ _EOF_
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
 			"Image Gallery" "Website to host / browse your images." $phpimagegallery_w \
 			"BaiKal" "Lightweight CalDAV + CardDAV server." $baikal_w \
+			"OpenBazaar" "Decentralized peer to peer Bitcoin market." $openbazaar_w \
 			"" "────System Stats / Management──────────────" "off" \
 			"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
 			"LinuxDash" "Web interface system stats." $linuxdash_w \
@@ -6168,8 +6200,71 @@ _EOF_
 			"NoIp" "URL website address for your device." $noipdyndns_w 2>/tmp/dietpi-software_results
 
 		#-----------------------------------------------------------------------------
-		#Odroid XU4 + C1/C2 Software Installation
-		elif (( $HW_MODEL >= 10 )) && (( $HW_MODEL < 20 )); then
+		#Odroid C2 Software Installation
+		elif (( $HW_MODEL == 12 )); then
+			whiptail --title "$WHIP_TITLE" --checklist --separate-output "Please use the spacebar to select the software you wish to install.\nSoftware details: http://dietpi.com/software" --backtitle "$WHIP_BACKTITLE" 20 78 12 \
+			"" "────Desktops────────────────────────────────" "off" \
+			"LXDE: Desktop" "Ultra lightweight desktop." $desktop_w \
+			"LXDE: VNC Server" "LXDE Desktop for remote connection." $tightvncserver_w \
+			"" "────Media Systems───────────────────────────" "off" \
+			"Kodi" "Your very own media centre / player." $kodi_w \
+			"MiniDLNA" "Media streaming server (DLNA, UPnP)." $minidlna_w \
+			"SubSonic 5" "Web interface media streaming server." $subsonic5_w \
+			"SubSonic 6" "(NEW) Web interface media streaming server." $subsonic6_w \
+			"Ampache" "Web interface media streaming server." $ampache_w \
+			"Shairport Sync" "AirPlay audio player with multiroom sync" $shairportsync_w \
+			"Murmur" "Mumble VoIP server." $mumbleserver_w \
+			"" "────BitTorrent──────────────────────────────" "off" \
+			"Transmission" "BitTorrent server with web interface." $transmission_w \
+			"Deluge" "BitTorrent server with web interface." $deluge_w \
+			"" "────Cloud / Backups─────────────────────────" "off" \
+			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
+			"Pydio" "Feature-rich backup and sync server" $pydio_w \
+			"" "────Social Media───────────────────────────" "off" \
+			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
+			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
+			"Image Gallery" "Website to host / browse your images." $phpimagegallery_w \
+			"BaiKal" "Lightweight CalDAV + CardDAV server." $baikal_w \
+			"" "────WiFi Hotspot────────────────────────────" "off" \
+			"WiFi Hotspot" "Turn your device into a WiFi hotspot." $wifihotspot_w \
+			"Tor Hotspot" "Optional: Route HotSpot traffic through Tor." $torhotspot_w \
+			"" "────Remote Access───────────────────────────" "off" \
+			"Weaved" "Access your device over the internet." $weaved_w \
+			"" "────System Stats / Management──────────────" "off" \
+			"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
+			"LinuxDash" "Web interface system stats." $linuxdash_w \
+			"PhpSysInfo" "Web interface system stats." $phpsysinfo_w \
+			"netdata" "real-time performance monitoring" $netdata_w \
+			"" "────System Security────────────────────────" "off" \
+			"Fail2Ban" "Prevents brute-force attacks with IP ban." $fail2ban_w \
+			"" "────Webserver Stacks───────────────────────" "off" \
+			"LAMP" "Webserver: Apache2  | MySql   | Php." $webserver_lamp_w \
+			"LASP" "Webserver: Apache2  | SQLite  | Php." $webserver_lasp_w \
+			"LAAP" "Webserver: Apache2  | MariaDB | Php." $webserver_laap_w \
+			"LEMP" "Webserver: Nginx    | MySql   | Php." $webserver_lemp_w \
+			"LESP" "Webserver: Nginx    | SQLite  | Php." $webserver_lesp_w \
+			"LEAP" "Webserver: Nginx    | MariaDB | Php." $webserver_leap_w \
+			"LLMP" "Webserver: Lighttpd | MySql   | Php." $webserver_llmp_w \
+			"LLSP" "Webserver: Lighttpd | SQLite  | Php." $webserver_llsp_w \
+			"LLAP" "Webserver: Lighttpd | MariaDB | Php." $webserver_llap_w \
+			"phpMyAdmin" "Optional MySql admin tools." $webserver_phpmyadmin_w \
+			"LetsEncrypt" "Free, auto SSL cert install allowing https://" $letsencrypt_w \
+			"" "────DNS Servers────────────────────────────" "off" \
+			"Pi-hole" "Block adverts for any device on your network." $pihole_w \
+			"" "────File Servers───────────────────────────" "off" \
+			"ProFTP" "Lightweight FTP / file server." $fileserver_proftp_w \
+			"vsFTPD" "Alternative FTP / file server." $fileserver_vsftpd_w \
+			"Samba" "Feature-rich file server." $fileserver_samba_w \
+			"" "────VPN Servers────────────────────────────" "off" \
+			"OpenVPN" "VPN server." $openvpnserver_w \
+			"" "────Network Load Balancing─────────────────" "off" \
+			"HaProxy" "High performance TCP/HTTP load balancer." $haproxy_w \
+			"" "────Website URLs───────────────────────────" "off" \
+			"NoIp" "URL website address for your device." $noipdyndns_w 2>/tmp/dietpi-software_results
+
+		#-----------------------------------------------------------------------------
+		#Odroid XU4 + C1 Software Installation
+		elif (( $HW_MODEL == 10 || $HW_MODEL == 11 )); then
 			whiptail --title "$WHIP_TITLE" --checklist --separate-output "Please use the spacebar to select the software you wish to install.\nSoftware details: http://dietpi.com/software" --backtitle "$WHIP_BACKTITLE" 20 78 12 \
 			"" "────Desktops────────────────────────────────" "off" \
 			"LXDE: Desktop" "Ultra lightweight desktop." $desktop_w \
@@ -6187,7 +6282,6 @@ _EOF_
 			"Transmission" "BitTorrent server with web interface." $transmission_w \
 			"Deluge" "BitTorrent server with web interface." $deluge_w \
 			"" "────Cloud / Backups─────────────────────────" "off" \
-			"OpenBazaar" "Your very own store (eg: ebay)." $openbazaar_w \
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
 			"" "────Social Media───────────────────────────" "off" \
@@ -6195,6 +6289,7 @@ _EOF_
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
 			"Image Gallery" "Website to host / browse your images." $phpimagegallery_w \
 			"BaiKal" "Lightweight CalDAV + CardDAV server." $baikal_w \
+			"OpenBazaar" "Decentralized peer to peer Bitcoin market." $openbazaar_w \
 			"" "────WiFi Hotspot────────────────────────────" "off" \
 			"WiFi Hotspot" "Turn your device into a WiFi hotspot." $wifihotspot_w \
 			"Tor Hotspot" "Optional: Route HotSpot traffic through Tor." $torhotspot_w \
@@ -6260,7 +6355,6 @@ _EOF_
 				"Transmission" "BitTorrent server with web interface." $transmission_w \
 				"Deluge" "BitTorrent server with web interface." $deluge_w \
 				"" "────Cloud / Backups─────────────────────────" "off" \
-				"OpenBazaar" "Your very own store (eg: ebay)." $openbazaar_w \
 				"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 				"Pydio" "Feature-rich backup and sync server" $pydio_w \
 				"" "────Gaming──────────────────────────────────" "off" \
@@ -6270,6 +6364,7 @@ _EOF_
 				"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
 				"Image Gallery" "Website to host / browse your images." $phpimagegallery_w \
 				"BaiKal" "Lightweight CalDAV + CardDAV server." $baikal_w \
+				"OpenBazaar" "Decentralized peer to peer Bitcoin market." $openbazaar_w \
 				"" "────Camera / Surveillance───────────────────" "off" \
 				"DietPi Cam" "RPi Cam Control / Web Interface Surveillance." $dietpicam_w \
 				"" "────WiFi Hotspot────────────────────────────" "off" \
@@ -6582,12 +6677,6 @@ _EOF_
 					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
-			SubSonic)
-				if (( $SUBSONIC == 0 )); then
-					SUBSONIC=1
-					INSTALL_DIETPI_CHOICESMADE=true
-				fi
-			;;
 			"Pi-hole")
 				if (( $PIHOLE == 0 )); then
 					PIHOLE=1
@@ -6774,16 +6863,6 @@ _EOF_
 
 		#-----------------------------------------------------------------------------
 		#Install Info/Warnings
-
-		#Emby server (mono libary), not available for ARM64: https://github.com/Fourdee/DietPi/issues/310#issuecomment-217946474
-		if (( $EMBYSERVER == 1 && $HW_MODEL == 12 )); then
-			WHIP_TITLE='Emby Server'
-			WHIP_QUESTION='Emby Server is not currently available for ARM64 (Odroid C2) and will not be installed. Your choice has been removed.\n\nhttps://github.com/Fourdee/DietPi/issues/310#issuecomment-217946474'
-			whiptail --title "$WHIP_TITLE" --msgbox "$WHIP_QUESTION" --backtitle "$WHIP_BACKTITLE" 13 75
-
-			EMBYSERVER=0
-
-		fi
 
 		#Webserver stacks, please let DietPi install them for you...
 		# - == 1 to prevent installed stacks appearing
