v85

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -163,6 +163,7 @@
 	WEAVED=0
 	WEBIOPI=0
 	DIETPICLOUDSHELL=0
+	HAPROXY=0
 
 	#Linux Software
 	INSTALL_LINUX_CHOICESMADE=false
@@ -243,6 +244,7 @@
 		echo -e "WEAVED $WEAVED" >> "$FILEPATH_INSTALLED_FILE"
 		echo -e "WEBIOPI $WEBIOPI" >> "$FILEPATH_INSTALLED_FILE"
 		echo -e "DIETPICLOUDSHELL $DIETPICLOUDSHELL" >> "$FILEPATH_INSTALLED_FILE"
+		echo -e "HAPROXY $HAPROXY" >> "$FILEPATH_INSTALLED_FILE"
 
 		echo -e "#Additional Linux Software" >> "$FILEPATH_INSTALLED_FILE"
 		echo -e "VIMFULL $VIMFULL" >> "$FILEPATH_INSTALLED_FILE"
@@ -314,6 +316,7 @@
 		WEAVED=$(cat "$FILEPATH_INSTALLED_FILE" | grep 'WEAVED ' | awk '{print $2}')
 		WEBIOPI=$(cat "$FILEPATH_INSTALLED_FILE" | grep 'WEBIOPI ' | awk '{print $2}')
 		DIETPICLOUDSHELL=$(cat "$FILEPATH_INSTALLED_FILE" | grep 'DIETPICLOUDSHELL ' | awk '{print $2}')
+		HAPROXY=$(cat "$FILEPATH_INSTALLED_FILE" | grep 'HAPROXY ' | awk '{print $2}')
 
 		#Linux
 		VIMFULL=$(cat "$FILEPATH_INSTALLED_FILE" | grep 'VIMFULL ' | awk '{print $2}')
@@ -1103,6 +1106,64 @@
 			#echo "fbtft_device" >> /etc/modules
 			
 		fi
+		
+		#HAPROXY
+		if (( $HAPROXY == 1 )); then
+			INSTALL_DESCRIPTION='HaProxy - High Performance TCP/HTTP Load Balancer'
+			Banner_Installing
+
+			#check source is online
+			INSTALL_URL_ADDRESS='http://www.haproxy.org/download/1.5/src/haproxy-1.5.14.tar.gz'
+			/DietPi/dietpi/func/check_connection 5 2 "$INSTALL_URL_ADDRESS"
+
+			#Install
+			if (( $? == 0 )); then
+				
+				#Download HAPROXY			
+				wget "$INSTALL_URL_ADDRESS"
+				tar -xvf haproxy-*
+				cd haproxy-*
+				
+				#Compile
+				# I've added HAPROXY to the list of software that will automatically install build-essential.
+				# Are there any further pre-reqs for building?
+				make TARGET=linux2628 CPU=generic USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_LINUX_SPLICE=1
+				make install
+
+				#Are we creating a config file for this?
+				mkdir /etc/haproxy
+				
+				#Exit directory
+				cd ..
+
+				#Clean up (removes both files and folders)
+				rm -R haproxy-*
+
+				#Install init script as service
+				cp /DietPi/dietpi/conf/haproxy_init /etc/init.d/haproxy
+				
+				#chmod 755 /etc/init.d/haproxy >> this does the same, but keeping the +x standard used throughout DietPi
+				chmod +x /etc/init.d/haproxy
+				
+				#This applies the script to the system services
+				update-rc.d haproxye defaults 20 20
+
+				#If this is important for the user 
+				# - we can make a whiptail prompt, or, 
+				# - add these references to the online documentation http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=5
+				#echo 'Check HAPROXY documentation before use http://www.haproxy.org/#doc1.5'
+				#echo 'Write config file haproxy.cfg in /etc/haproxy folder'
+				
+			else
+				Info_NoConnection_NoInstall
+
+				#Abort Install, prevent configs being applied
+				HAPROXY=0
+			fi
+			
+
+			
+		fi
 
 	}
 
@@ -1154,6 +1215,8 @@
 		
 		#DietPi software that requires Build-Essential
 		if (( $VPNSERVER == 1 )); then
+			BUILDESSENTIAL=1
+		elif (( $HAPROXY == 1 )); then
 			BUILDESSENTIAL=1
 		fi
 		
@@ -2326,6 +2389,11 @@ _EOF_
 			DIETPICLOUDSHELL=2
 		fi
 		
+		#HAPROXY
+		if (( $HAPROXY == 1 )); then
+
+			HAPROXY=2
+		fi
 		
 	}
 
@@ -3188,6 +3256,15 @@ _EOF_
 			fi
 		fi
 
+		local haproxy_w="off"
+		if (( $HAPROXY > 0 )); then
+			haproxy_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $HAPROXY == 1 )); then
+				HAPROXY=0
+			fi
+		fi
+
 		#-----------------------------------------------------------------------------
 		WHIP_TITLE='DietPi Optimized Software Selection'
 
@@ -3287,6 +3364,8 @@ _EOF_
 			"WebIOPi" "Web interface to control RPi GPIO." $webiopi_w \
 			"" "────Remote Access───────────────────────────" "off" \
 			"Weaved" "Access your device over the internet." $weaved_w \
+			"" "────Network Load Balancing─────────────────" "off" \
+			"HaProxy" "High performance TCP/HTTP load balancer" $haproxy_a \
 			"" "────System Management──────────────────────" "off" \
 			"Raspcontrol" "Web interface system stats." $raspcontrol_w \
 			"LinuxDash" "Web interface system stats." $linuxdash_w \
@@ -3314,6 +3393,12 @@ _EOF_
 		while read choice
 		do
 			case $choice in
+			HaProxy)
+				if (( $HAPROXY == 0 )); then
+					HAPROXY=1
+					INSTALL_DIETPI_CHOICESMADE=true
+				fi
+			;;
 			"DietPi-Cs")
 				if (( $DIETPICLOUDSHELL == 0 )); then
 					DIETPICLOUDSHELL=1
