v78

diff --git a/dietpi/dietpi-bugreport b/dietpi/dietpi-bugreport
--- a/dietpi/dietpi-bugreport
+++ b/dietpi/dietpi-bugreport
@@ -144,15 +144,26 @@ _EOF_
 	}
 
 	Generate_Unique_Id(){
-		#Get unique ID by using eth0 mac address
-		if (( $(ifconfig | grep -ci -m1 'eth0') == 1 )); then
-			UNIQUE_ID_HW=$(ifconfig | grep eth0 | awk '{print $NF}' | sed 's/://g')
-		#Get unique ID by using wlan0 mac address
-		elif (( $(ifconfig | grep -ci -m1 'wlan0') == 1 )); then
-			UNIQUE_ID_HW=$(ifconfig | grep wlan0 | awk '{print $NF}' | sed 's/://g')
-		#No Network hardware found, unable to use MAC address as UUID.
-		else
-			UNIQUE_ID_HW="failed"
+
+		#Set default to failed.
+		UNIQUE_ID_HW="failed"
+		
+		#Obtain active network index.
+		local eth_index=$(sed -n 1p /DietPi/dietpi/.network_device_index)
+		local wlan_index=$(sed -n 2p /DietPi/dietpi/.network_device_index)
+	
+		#Check if we have a working internet connection beforehand
+		/DietPi/dietpi/func/check_connection 10 2 "google.com"
+		if (( $? == 0 )); then
+			#Online
+			#Get unique ID by using eth mac address
+			if (( $(ifconfig | grep -ci -m1 "eth$eth_index") == 1 )); then
+				UNIQUE_ID_HW=$(ifconfig | grep "eth$eth_index" | awk '{print $NF}' | sed 's/://g')
+			#Get unique ID by using wlan mac address
+			elif (( $(ifconfig | grep -ci -m1 "wlan$wlan_index") == 1 )); then
+				UNIQUE_ID_HW=$(ifconfig | grep "wlan$wlan_index" | awk '{print $NF}' | sed 's/://g')
+			fi
+
 		fi
 
 	}
