v6.12
+DietPi-Drive_Manager | Samba/CIFS mounting: Now automatically uses the highest available CIFS version supported on client and server: https://github.com/Fourdee/DietPi/issues/1893#issuecomment-403034799

+DietPi-Drive_Manager | Resolved an issue where the program could remove a non-empty directory in rare situations.

diff --git a/dietpi/dietpi-drive_manager b/dietpi/dietpi-drive_manager
--- a/dietpi/dietpi-drive_manager
+++ b/dietpi/dietpi-drive_manager
@@ -450,6 +450,23 @@ _EOF_
 
 	}
 
+	Rm_Empty_Dir(){
+
+		local fp_dir="$1"
+		if [[ -n $fp_dir && -z $(ls -A $fp_dir) ]]; then
+
+			rm -R "$fp_dir"
+
+			G_DIETPI-NOTIFY 2 "Removed empty directory: $fp_dir"
+
+		else
+
+			G_DIETPI-NOTIFY 2 "Not removing directory, as it contains data: $fp_dir"
+
+		fi
+
+	}
+
 	Return_Drive_Without_Partitions(){
 
 		#$1 = dev source
@@ -513,7 +530,7 @@ _EOF_
 		if (( $? == 0 )); then
 
 			sed -i "\#[[:space:]]$target[[:space:]]#d" /etc/fstab #Only needed for networked drives currently...
-			rm -R $target
+			Rm_Empty_Dir "$target"
 
 		fi
 
@@ -1680,7 +1697,8 @@ NB:
 				break
 
 			fi
-			samba_clientshare="$G_WHIP_RETURNED_VALUE"
+			#	NB: Convert spaces into '\040': https://github.com/Fourdee/DietPi/issues/1201#issuecomment-339720271
+			samba_clientshare=$(echo -e "$G_WHIP_RETURNED_VALUE" | sed 's/ /\\\\040/g')
 
 			G_WHIP_DEFAULT_ITEM="$samba_clientuser"
 			G_WHIP_INPUTBOX 'Please enter the fileservers username\n - eg: JoeBloggs'
@@ -1710,28 +1728,50 @@ NB:
 
 			G_AG_CHECK_INSTALL_PREREQ smbclient cifs-utils
 
-			#NB: Convert spaces into '\040': https://github.com/Fourdee/DietPi/issues/1201#issuecomment-339720271
-			local space_to_040=$(echo -e "$samba_clientshare" | sed 's/ /\\\\040/g')
-
 			#Mount now
 			mkdir -p $samba_fp_mount_target
 
-			G_RUN_CMD_INFO_ONLY=1 G_RUN_CMD mount -t cifs -o username="$samba_clientuser",password="$samba_clientpassword" //"$samba_clientname"/"$space_to_040" "$samba_fp_mount_target"
-			if (( ! $G_ERROR_HANDLER_EXITCODE_RETURN )); then
+			# - Mount from highest SMB version to lowest, until we find a successful one
+			local acifs_versions=(
 
-				#Apply to fstab
-				sed -i "\#[[:space:]]$samba_fp_mount_target[[:space:]]#d" /etc/fstab
-				cat << _EOF_ >> /etc/fstab
-//$samba_clientname/$space_to_040 $samba_fp_mount_target cifs username=$samba_clientuser,password=$samba_clientpassword,iocharset=utf8,vers=1.0,nofail 0 0
+				'3.1'
+				'3.0'
+				'2.1'
+				'2.0'
+				'1.0'
+
+			)
+
+			for ((i=0; i<${#acifs_versions[@]}; i++))
+			do
+				G_DIETPI-NOTIFY 2 "Attempting to mount with CIFS version: ${acifs_versions[$i]}"
+				mount -t cifs -o username="$samba_clientuser",password="$samba_clientpassword",vers=${acifs_versions[$i]} //"$samba_clientname"/"$samba_clientshare" "$samba_fp_mount_target" &> /dev/null
+				if (( $? == 0 )); then
+
+					# - Apply to fstab
+					sed -i "\#[[:space:]]$samba_fp_mount_target[[:space:]]#d" /etc/fstab
+					cat << _EOF_ >> /etc/fstab
+//$samba_clientname/$samba_clientshare $samba_fp_mount_target cifs username=$samba_clientuser,password=$samba_clientpassword,iocharset=utf8,vers=${acifs_versions[$i]},nofail 0 0
 _EOF_
 
-				G_WHIP_MSG "Mount completed. The new mount can be accessed via:\n - $samba_fp_mount_target"
+					G_WHIP_MSG "Mount completed. The new mount can be accessed via:\n - $samba_fp_mount_target\n - CIFS vers=${acifs_versions[$i]}"
+					break
 
-			else
+				fi
 
-				rm -R "$samba_fp_mount_target"
+				# - Last item already failed, re-run for user info
+				if (( $i == ( ${#acifs_versions[@]} - 1 ) )); then
 
-			fi
+					# - Run mount again, allow user to see error
+					G_RUN_CMD_INFO_ONLY=1 G_RUN_CMD mount -t cifs -o username="$samba_clientuser",password="$samba_clientpassword",vers=${acifs_versions[$i]} //"$samba_clientname"/"$samba_clientshare" "$samba_fp_mount_target"
+					Rm_Empty_Dir "$samba_fp_mount_target"
+					break
+
+				fi
+
+			done
+
+			unset acifs_versions
 
 			break
 
@@ -1788,7 +1828,7 @@ _EOF_
 
 			else
 
-				rm -R $nfs_fp_mount_target
+				Rm_Empty_Dir "$nfs_fp_mount_target"
 
 			fi
 
