v104

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -3325,11 +3325,19 @@ _EOF_
 				/DietPi/dietpi/func/dietpi-set_curlftpfs 1
 			fi
 
+			local run_custom_script=0
+			#Custom 1st run Script (Local file)
+			if [ -f /boot/Automation_Custom_Script.sh ]; then
+				INSTALL_DESCRIPTION='Automation - Local Custom Script'
+				Banner_Installing
 
-			#Exec Custom 1st run Script
-			if [ "$AUTOINSTALL_CUSTOMSCRIPTURL" != "0" ]; then
+				cp /boot/Automation_Custom_Script.sh /root/AUTO_CustomScript.sh
+				run_custom_script=1
 
-				INSTALL_DESCRIPTION='Automation - Run Custom Script'
+			#Custom 1st run Script (Online file)
+			elif [ "$AUTOINSTALL_CUSTOMSCRIPTURL" != "0" ]; then
+
+				INSTALL_DESCRIPTION='Automation - Online Custom Script'
 				Banner_Installing
 
 				#check source is online
@@ -3340,18 +3348,22 @@ _EOF_
 				if (( $? == 0 )); then
 
 					#Get script and execute
-					wget "$INSTALL_URL_ADDRESS" -O /root/AUTO_CustomScriptURL.sh
-					chmod +x /root/AUTO_CustomScriptURL.sh
-					/root/AUTO_CustomScriptURL.sh
-					local result=$?
-					if (( $result == 0 )); then
-						echo -e "Automated custom script executed succesfully:\nURL = $AUTOINSTALL_CUSTOMSCRIPTURL" >> "$FP_DIETPIAUTOMATION_LOG"
-					else
-						echo -e "Automated Custom Script Error:\n - Exit code = $result\n - URL = $AUTOINSTALL_CUSTOMSCRIPTURL" >> "$FP_DIETPIAUTOMATION_LOG"
-					fi
+					wget "$INSTALL_URL_ADDRESS" -O /root/AUTO_CustomScript.sh
+					run_custom_script=1
 
 				else
 					echo -e "Automated Custom Script URL Error:\n $AUTOINSTALL_CUSTOMSCRIPTURL is offline and/or unreachable" >> "$FP_DIETPIAUTOMATION_LOG"
+				fi
+			fi
+
+			if (( $run_custom_script == 1 )); then
+				chmod +x /root/AUTO_CustomScript.sh
+				/root/AUTO_CustomScript.sh
+				local result=$?
+				if (( $result == 0 )); then
+					echo -e "Automated custom script executed succesfully:\n - Filepath = /root/AUTO_CustomScript.sh\n - URL = $AUTOINSTALL_CUSTOMSCRIPTURL" >> "$FP_DIETPIAUTOMATION_LOG"
+				else
+					echo -e "Automated Custom Script Error:\n - Exit code = $result\n - Filepath = /root/AUTO_CustomScript.sh\n - URL = $AUTOINSTALL_CUSTOMSCRIPTURL" >> "$FP_DIETPIAUTOMATION_LOG"
 				fi
 			fi
 
