v64

diff --git a/dietpi/dietpi-update b/dietpi/dietpi-update
--- a/dietpi/dietpi-update
+++ b/dietpi/dietpi-update
@@ -14,6 +14,7 @@
 	#
 	# Usage:
 	# - dietpi-update 1 = forced update
+	# - dietpi-update 2 = Check for updates. version to /tmp/dietpi/update_available file
 	#////////////////////////////////////
 	INPUT=0
 	
@@ -34,7 +35,7 @@
 	DISTRO=$(sed -n 3p /tmp/dietpi/.hw_model)
 
 	#/////////////////////////////////////////////////////////////////////////////////////
-	#VERSION CODES
+	#UPDATE Vars
 	#/////////////////////////////////////////////////////////////////////////////////////
 	DIETPIUPDATE_VERSION_CURRENT=3 # Version of dietpi-update / set server_version line two to value++ and obsolete previous dietpi-update scripts
 	DIETPIUPDATE_VERSION_REQUIRED=0
@@ -46,8 +47,15 @@
 		VERSION_CURRENT=$(cat /boot/dietpi/.version)
 	}
 
-	SERVER_ONLINE=false
-	RUN_UPDATE=false
+	UPDATE_CHECKONLY=0
+	if (( $? == 2 )); then
+		UPDATE_CHECKONLY=1
+	fi	
+
+	SERVER_ONLINE=0
+	UPDATE_AVAILABLE=0
+	UPDATE_REQUIRESNEWIMAGE=0
+	RUN_UPDATE=0
 
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# MENUS
@@ -65,7 +73,7 @@
 		CHOICE=$?
 		#Confirm action
 		if (( $CHOICE == 0 )); then
-			RUN_UPDATE=true
+			RUN_UPDATE=1
 		fi
 	}
 
@@ -110,7 +118,7 @@
 		#Remove temp files
 		rm -R ~/DietPi-"$GITBRANCH" &> /dev/null
 
-		RUN_UPDATE=false
+		RUN_UPDATE=0
 		
 	}
 
@@ -126,7 +134,8 @@
 	#Check gitbranch is online
 	/boot/dietpi/func/check_connection 5 2 https://raw.githubusercontent.com/Fourdee/DietPi/"$GITBRANCH"/dietpi/server_version
 	if (( $? == 0 )); then
-		SERVER_ONLINE=true
+
+		SERVER_ONLINE=1
 
 		#Work from home directory
 		cd ~/
@@ -140,84 +149,111 @@
 		
 		#Check if Version_Server is valid?
 		if [[ $VERSION_SERVER =~ ^-?[0-9]+$ ]]; then
-			echo -e "valid" &> /dev/null
+
+			#Update Requires new image?
+			if (( $DIETPIUPDATE_VERSION_CURRENT < $DIETPIUPDATE_VERSION_REQUIRED )); then
+				UPDATE_REQUIRESNEWIMAGE=1
+			#Update available
+			else if (( $VERSION_CURRENT < $VERSION_SERVER )); then 
+				UPDATE_AVAILABLE=1
+			fi
+
 		else
-			echo -e "\nError: Obtained server version value from github is invalid. Please try running dietpi-update again."
-			exit
+			echo -e "\nError: Obtained server version value from github is invalid. Please try running dietpi-update again.\n"
 		fi
 
-		
 		#Remove temp file
 		rm server_version
+
 	fi
 
 	#----------------------------------------------------------------
-	#Check we can apply this update. Provide prompts.
-	if [ "$SERVER_ONLINE" = false ]; then
-		whiptail --title "Error - Server Offline" --msgbox "http://github.com is either offline, or, unable to connect \n \n No updates applied." 12 60
+	#Check for updates only
+	if (( $UPDATE_CHECKONLY == 1 )); then
 
-	elif (( $DIETPIUPDATE_VERSION_CURRENT < $DIETPIUPDATE_VERSION_REQUIRED )); then 
-		#Cannot update, Image required
-		whiptail --title "Unable to update image" --msgbox " Your version of DietPi is now obsolete and cannot be updated. \n Please download the latest DietPi image:\n http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=6 \n\n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n " 18 70
+		#Write update available version to file.
+		if (( $UPDATE_AVAILABLE == 1 )); then
+			echo -e "$VERSION_SERVER" > /tmp/dietpi/update_available
+		fi
 
-		clear
-		/tmp/dietpi/dietpi-banner 0
-		echo -e " Your version of DietPi is now obsolete and cannot be updated. \n Please download the latest DietPi image:\n http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=6 \n\n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+	#----------------------------------------------------------------
+	#Run menus / prompts / update core.
+	else
 
-	elif (( $VERSION_CURRENT < $VERSION_SERVER )); then 
-		#Forced update
-		if (( $INPUT == 1 )); then
+		#----------------------------------------------------------------
+		#Server offline
+		if (( $SERVER_ONLINE == 0 )); then
+			whiptail --title "Error - Server Offline" --msgbox "http://github.com is either offline, or, unable to connect \n \n No updates applied." 12 60
+
+		#Update requires new DietPi image
+		elif (( $UPDATE_REQUIRESNEWIMAGE == 1 )); then 
+			#Cannot update, Image required
+			whiptail --title "Unable to update image" --msgbox " Your version of DietPi is now obsolete and cannot be updated. \n Please download the latest DietPi image:\n http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=6 \n\n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n " 18 70
+
+			clear
+			/tmp/dietpi/dietpi-banner 0
+			echo -e " Your version of DietPi is now obsolete and cannot be updated. \n Please download the latest DietPi image:\n http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=6 \n\n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+
+		#Update available
+		elif (( $UPDATE_AVAILABLE == 1 )); then 
+			#Forced update
+			if (( $INPUT == 1 )); then
+				clear
+				/tmp/dietpi/dietpi-banner 0
+				
+				echo -e "Updates have been found and are being applied, please wait.... \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+				sleep 2
+				RUN_UPDATE=1
+			
+			#Ask for update
+			else
+				Menu_Update
+			fi
+		else
+			#No Updates
+			clear
+			/tmp/dietpi/dietpi-banner 0
+			echo -e " DietPi Update - No updates required \n Your DietPi installation is upto date \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+			sleep 2
+		fi
+
+		#----------------------------------------------------------------
+		#Run Update
+		if (( $RUN_UPDATE == 1 )); then
+		
+			#Stop Services
+			/boot/dietpi/dietpi-services stop
+			
+			#Update Apt
+			apt-get update
+			
+			#Run update and patcher
+			clear
+			Run_DietPi_Update
+			
+			#.update file stage (only used on 1st run of dietpi-software to check/apply updates, 0 tells dietpi-software to reboot)
+			echo 0 > /boot/dietpi/.update_stage
+			
+			#update dietpi-copy_to_ram
+			/boot/dietpi/dietpi-copy_to_ram
+			
+			#Remove update_available file
+			rm /tmp/dietpi/update_available &> /dev/null
+			
+			#Done
 			clear
 			/tmp/dietpi/dietpi-banner 0
 			
-			echo -e "Updates have been found and are being applied, please wait.... \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
-			sleep 2
-			RUN_UPDATE=true
-		
-		#Ask for update
-		else
-			Menu_Update
+			echo -e "DietPi Update Completed. \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+			echo -e "Please reboot your system, using the command reboot"
 		fi
-	else
-		#No Updates
-		clear
-		/tmp/dietpi/dietpi-banner 0
-		echo -e " DietPi Update - No updates required \n Your DietPi installation is upto date \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
-		sleep 2
-	fi
 
-	#----------------------------------------------------------------
-	#Run Update
-	if [ "$RUN_UPDATE" = true ]; then
-	
-		#Stop Services
-		/boot/dietpi/dietpi-services stop
-		
-		#Update Apt
-		apt-get update
-		
-		#Run update and patcher
-		clear
-		Run_DietPi_Update
-		
-		#.update file stage (only used on 1st run of dietpi-software to check/apply updates, 0 tells dietpi-software to reboot)
-		echo 0 > /boot/dietpi/.update_stage
-		
-		#update dietpi-copy_to_ram
-		/boot/dietpi/dietpi-copy_to_ram
-		
-		#Done
-		clear
-		/tmp/dietpi/dietpi-banner 0
-		
-		echo -e "DietPi Update Completed. \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
-		echo -e "Please reboot your system, using the command reboot"
-	fi
+		#----------------------------------------------------------------
+		#Desktop Run, exit key prompt
+		if (( $(ps aux | grep -ci -m1 '[l]xpanel') == 1 )); then
+			read -p "Press any key to exit DietPi-Update..."
+		fi
 
-	#----------------------------------------------------------------
-	#Desktop Run, exit key prompt
-	if (( $(ps aux | grep -ci -m1 '[l]xpanel') == 1 )); then
-		read -p "Press any key to exit DietPi-Update..."
 	fi
 
 	#----------------------------------------------------------------
