v6.17
+ testing https://github.com/Fourdee/DietPi/issues/1927#issuecomment-405711847

diff --git a/dietpi/dietpi-survey b/dietpi/dietpi-survey
--- a/dietpi/dietpi-survey
+++ b/dietpi/dietpi-survey
@@ -30,6 +30,8 @@
 	G_INIT
 	#Import DietPi-Globals ---------------------------------------------------------------
 
+	EXIT_CODE=1 # 1=failed to send survey, 0=survey sent, 2=opted out and sent
+
 	#Grab Input (valid interger)
 	INPUT=0
 	disable_error=1 G_CHECK_VALIDINT $1 && INPUT=$1
@@ -152,7 +154,7 @@ _EOF_
 			fi
 
 			#Upload to server
-			curl --connect-timeout 4 --retry 1 --retry-delay 4 -sT "$UPLOAD_FILENAME" sftp://"$SFTP_USER":"$SFTP_PASS"@"$SFTP_ADDR"/survey/
+			curl --connect-timeout 8 --retry 1 --retry-delay 4 -sT "$UPLOAD_FILENAME" sftp://"$SFTP_USER":"$SFTP_PASS"@"$SFTP_ADDR"/survey/
 			if (( $? )); then
 
 				# Silently fail, in case of non-interactive mode
@@ -161,6 +163,7 @@ _EOF_
 			# Successful upload + opted in
 			elif (( $OPTED_IN )); then
 
+				EXIT_CODE=0
 				G_DIETPI-NOTIFY 0 'Successfully sent survey data'
 				# Increase sent count
 				((SURVEY_SENTCOUNT++))
@@ -168,6 +171,7 @@ _EOF_
 			# Successful upload + opted out + interactive
 			elif (( ! $INPUT )); then
 
+				EXIT_CODE=2
 				G_DIETPI-NOTIFY 0 'Successfully purged survey data'
 
 			fi
@@ -238,7 +242,7 @@ Would you like to join DietPi-Survey?"
 	fi
 
 	#-----------------------------------------------------------------------------------
-	exit 0
+	exit $EXIT_CODE
 	#-----------------------------------------------------------------------------------
 
 }
