v131
+ HFSplus for Drive Manager:
https://github.com/Fourdee/DietPi/issues/271
+ See changelog

diff --git a/dietpi/dietpi-drive_manager b/dietpi/dietpi-drive_manager
--- a/dietpi/dietpi-drive_manager
+++ b/dietpi/dietpi-drive_manager
@@ -39,7 +39,7 @@
 
 	MAX_DRIVES=5
 	FORMAT_GPT=0
-	FORMAT_FILESYSTEM_TYPE=0 #0=ext4 1=ntfs 2=fat32 #3!=hfs
+	FORMAT_FILESYSTEM_TYPE=0 #0=ext4 1=ntfs 2=fat32 3=hfs+
 
 	INDEX_DRIVE_BEING_EDITED=0
 
@@ -91,7 +91,7 @@
 		for ((i=0; i<$MAX_DRIVES; i++))
 		do
 			# - init
-			aDRIVE_UUID[$i]='None'
+			aDRIVE_UUID[$i]='NULL'
 			aDRIVE_FSTYPE[$i]='No filesystem'
 			aDRIVE_SIZE_TOTAL[$i]='NULL'
 			aDRIVE_SIZE_USED[$i]='NULL'
@@ -222,7 +222,8 @@
 		# - Format HFS?
 		elif (( $FORMAT_FILESYSTEM_TYPE == 3 )); then
 
-			echo -e "nothing here"
+			mkfs.hfsplus ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}
+			hformat -f ${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}
 
 		fi
 
@@ -577,6 +578,7 @@
 
 				fi
 
+
 			else
 
 				whiptail_desc+="Status:       Drive is not mounted and can be unplugged\n"
@@ -620,18 +622,27 @@
 
 			elif [ "$OPTION" = "Mount Method" ]; then
 
-				if (( ${aDRIVE_ISUUIDMOUNT[$INDEX_DRIVE_BEING_EDITED]} )); then
+				#UUID exists?
+				if [ "${aDRIVE_UUID[$INDEX_DRIVE_BEING_EDITED]}" = "NULL" ]; then
 
-					sed -i "s@^UUID=${aDRIVE_UUID[$INDEX_DRIVE_BEING_EDITED]}@${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}@g" /etc/fstab
+					whiptail --title "Error: No UUID" --msgbox "This drive does not have a UUID assigned. Unable to proceed." --backtitle "$PROGRAM_NAME" 8 60
 
 				else
 
-					sed -i "s@^${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}@UUID=${aDRIVE_UUID[$INDEX_DRIVE_BEING_EDITED]}@g" /etc/fstab
+					if (( ${aDRIVE_ISUUIDMOUNT[$INDEX_DRIVE_BEING_EDITED]} )); then
+
+						sed -i "s@^UUID=${aDRIVE_UUID[$INDEX_DRIVE_BEING_EDITED]}@${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}@g" /etc/fstab
+
+					else
+
+						sed -i "s@^${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}@UUID=${aDRIVE_UUID[$INDEX_DRIVE_BEING_EDITED]}@g" /etc/fstab
+
+					fi
+
+					# - update systemd to use fstab UUID changes
+					systemctl daemon-reload
 
 				fi
-
-				# - update systemd to use fstab UUID changes
-				systemctl daemon-reload
 
 			elif [ "$OPTION" = "Move Userdata" ]; then
 
@@ -690,7 +701,7 @@
 
 		elif (( $FORMAT_FILESYSTEM_TYPE == 3 )); then
 
-			format_type_text='HFS'
+			format_type_text='HFS+'
 
 		fi
 
@@ -727,16 +738,26 @@
 
 				whiptail_menu_array=()
 				whiptail_menu_array+=("0" ": EXT4 (Recommended)")
-				whiptail_menu_array+=("1" ": NTFS (High CPU usage)")
-				whiptail_menu_array+=("2" ": FAT32 (4GB filesize limit)")
+				whiptail_menu_array+=("1" ": NTFS")
+				whiptail_menu_array+=("2" ": FAT32")
+				whiptail_menu_array+=("3" ": HFS+ (Mac? We got you covered ;))")
 
 				WHIP_TITLE='Filesystem Type?'
-				OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Please select a filesystem type for this format:\n\nEXT4\nHighly recommended if you plan to use this drive soley on this system (dedicated drive).\n\nNTFS:\nRecommended if you plan to use this drive on a Windows system. High CPU usage during transfers.\n\nFAT32\nGood all-round filesystem supported on multiple OS'es. Warning: Has a 4GB filesize limit and 2TB drive limit." --cancel-button "Back" --default-item "$FORMAT_FILESYSTEM_TYPE" --backtitle "$PROGRAM_NAME" 23 70 3 "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
+				OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Please select a filesystem type for this format:\n\nEXT4\nHighly recommended if you plan to use this drive soley on this system (dedicated drive).\n\nNTFS:\nRecommended if you plan to use this drive on a Windows system. High CPU usage during transfers.\n\nFAT32\nGood all-round filesystem supported on multiple OS'es. Warning: Has a 4GB filesize limit and 2TB drive limit." --cancel-button "Back" --default-item "$FORMAT_FILESYSTEM_TYPE" --backtitle "$PROGRAM_NAME" 24 70 4 "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
 				CHOICE=$?
 
 				unset whiptail_menu_array
 
 				if (( $CHOICE == 0 )); then
+
+					# - HFS install packages
+					if (( $OPTION == 3 &&
+						! $(dpkg --get-selections | awk '{print $1}' | grep -ci -m1 'hfsutils') )); then
+
+						/DietPi/dietpi/func/dietpi-notify 2 "Installing additional packages for $OPTION support, please wait..."
+						apt-get install -y hfsplus hfsprogs hfsutils
+
+					fi
 
 					FORMAT_FILESYSTEM_TYPE=$OPTION
 
