v89

diff --git a/dietpi/dietpi-backup b/dietpi/dietpi-backup
--- a/dietpi/dietpi-backup
+++ b/dietpi/dietpi-backup
@@ -41,8 +41,9 @@
 
 
 		WHIP_TITLE='--- DietPi-Backup ---'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Current backup and restore location:\n\n$FP_TARGET" --cancel-button "Exit" --backtitle "$WHIP_BACKTITLE" 13 73 3 \
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Current backup and restore location:\n\n$FP_TARGET" --cancel-button "Exit" --backtitle "$WHIP_BACKTITLE" 14 73 4 \
 		"Location" "Change where your backup will be saved and restored from." \
+		"Help" "What does DietPi-Backup do?" \
 		"Backup" "Create (or update) a backup of this system." \
 		"Restore" "Restore this system from a previous backup." 3>&1 1>&2 2>&3)
 
@@ -52,6 +53,9 @@
 			case "$OPTION" in
 				Location)
 					TARGETMENUID=1
+				;;
+				Help)
+					whiptail --title "DietPi-Backup Help" --msgbox "DietPi-Backup is a program that allows you to Backup and Restore your DietPi system.\n\nIf you have broken your system, or want to reset your system to an eariler date, this can all be done with DietPi-Backup.\n\nSimply choose a location where you want to save and restore your backups from, then, select Backup or Restore.\n\nNotice for dedicated USB HDD installations:\n - DietPi-Backup does not backup any USB HDD data.\n\nMore information:\n - http://fuzon.co.uk" --backtitle "$WHIP_BACKTITLE" 20 75
 				;;
 				Backup)
 					WHIP_TITLE=' Start system backup? '
@@ -223,6 +227,9 @@
 		"ext3"
 		"ext2"
 	)
+	
+	#rsync options
+	RSYNC_RUN_OPTIONS="-alHv --delete --checksum --log-file=$LOGFILE --exclude-from=$FP_EXCLUDE_GLOBAL --include-from=$FP_INCLUDE_GLOBAL"
 
 	Create_Exclude_File(){
 
@@ -243,8 +250,6 @@
 		#Global - Files
 		echo -e "$LOGFILE" >> "$FP_EXCLUDE_GLOBAL"		
 		echo -e "$FP_DIETPIBACKUP_SETTINGS" >> "$FP_EXCLUDE_GLOBAL"
-		echo -e "$FP_EXCLUDE_USER" >> "$FP_EXCLUDE_GLOBAL"
-		echo -e "$FP_INCLUDE_USER" >> "$FP_EXCLUDE_GLOBAL"
 		echo -e "$BACKUP_STATS_FILENAME" >> "$FP_EXCLUDE_GLOBAL"
 		echo -e "/var/swap" >> "$FP_EXCLUDE_GLOBAL"
 		echo -e "fake-hwclock.data" >> "$FP_EXCLUDE_GLOBAL"
@@ -303,24 +308,36 @@
 
 			#Generate target dir.
 			mkdir -p "$FP_TARGET"
-		
-			#Remove previous logfile
-			rm "$LOGFILE" &> /dev/null
-
-			echo -e "DietPi-Backup Log File. $(date +"%d-%m-%Y_%H%M")\n\n" > "$LOGFILE"
 
 			#Start Backup
 			if [ -d "$FP_TARGET" ]; then
-				#Backup
-				rsync -alHv --delete --checksum --log-file=$LOGFILE --exclude-from="$FP_EXCLUDE_GLOBAL" --include-from="$FP_INCLUDE_GLOBAL" "$FP_SOURCE" "$FP_TARGET"/
-				echo -e "Backup Completed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
 
-				#Menu
-				if (( $INPUT == 0 )); then
-					whiptail --title "Backup completed" --msgbox "Your backup was saved to:\n$FP_TARGET\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 11 60
-					#return to main menu
-					TARGETMENUID=0
+				#Remove previous logfile
+				rm "$LOGFILE" &> /dev/null
+				echo -e "DietPi-Backup Log File. $(date +"%d-%m-%Y_%H%M")\n\n" > "$LOGFILE"
+
+				#Backup
+				rsync $RSYNC_RUN_OPTIONS "$FP_SOURCE" "$FP_TARGET"/
+
+				#Success
+				if (( $? == 0 )); then
+					echo -e "Backup Completed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
+					#Menu
+					if (( $INPUT == 0 )); then
+						whiptail --title "Backup completed" --msgbox "Your backup was saved to:\n$FP_TARGET\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 11 60
+					fi
+
+				#Failed
+				else
+					echo -e "Backup Failed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
+					#Menu
+					if (( $INPUT == 0 )); then
+						whiptail --title "Backup failed" --msgbox "Your backup has failed. Please see the Log file for more information:\n\n$LOGFILE" --backtitle "$WHIP_BACKTITLE" 12 60
+					fi
 				fi
+
+				#return to main menu
+				TARGETMENUID=0
 
 			#error Folder not found
 			else
@@ -351,15 +368,27 @@
 
 			#Restore
 			if [ -f "$FP_TARGET/$BACKUP_STATS_FILENAME" ]; then
-				rsync -alHv --delete --checksum --exclude-from="$FP_EXCLUDE_GLOBAL" --include-from="$FP_INCLUDE_GLOBAL" "$FP_TARGET"/ "$FP_SOURCE" 
-				echo -e "Restore Completed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
+				rsync $RSYNC_RUN_OPTIONS "$FP_TARGET"/ "$FP_SOURCE" 
 
-				#Menu
-				if (( $INPUT == 0 )); then
-					whiptail --title "Restore completed" --msgbox "Your system has been restored from:\n$FP_TARGET" --backtitle "$WHIP_BACKTITLE" 10 60
-					#return to main menu
-					TARGETMENUID=0
+				#Success
+				if (( $? == 0 )); then
+					echo -e "Restore Completed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
+					#Menu
+					if (( $INPUT == 0 )); then
+						whiptail --title "Restore completed" --msgbox "Your system has been restored from:\n$FP_TARGET" --backtitle "$WHIP_BACKTITLE" 10 60
+					fi
+
+				#Failed
+				else
+					echo -e "Restore Failed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$BACKUP_STATS_FILENAME"
+					#Menu
+					if (( $INPUT == 0 )); then
+						whiptail --title "Restore failed" --msgbox "Your restore has failed. Please see the Log file for more information:\n\n$LOGFILE" --backtitle "$WHIP_BACKTITLE" 12 60
+					fi
 				fi
+
+				#return to main menu
+				TARGETMENUID=0
 
 			#error backup not found
 			else
diff --git a/dietpi/dietpi-sync b/dietpi/dietpi-sync
--- a/dietpi/dietpi-sync
+++ b/dietpi/dietpi-sync
@@ -52,10 +52,11 @@
 		fi
 
 		WHIP_TITLE='--- DietPi-Sync ---'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Source location:\n$FP_SOURCE\n\nTarget location:\n$FP_TARGET" --cancel-button "Exit" --backtitle "$WHIP_BACKTITLE" 17 73 5 \
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Source location:\n$FP_SOURCE\n\nTarget location:\n$FP_TARGET" --cancel-button "Exit" --backtitle "$WHIP_BACKTITLE" 18 73 6 \
 		"Source Location" "Change the Source directory." \
 		"Target Location" "Change the Target directory." \
 		"Delete Mode" "$SYNC_MODE_TEXT" \
+		"Help" "What does DietPi-Sync do?" \
 		"Dry Run" "Run a test Sync without modifying any data." \
 		"Sync" "Sync the Source location to the Target location." 3>&1 1>&2 2>&3)
 
@@ -68,6 +69,9 @@
 				;;
 				"Target Location")
 					TARGETMENUID=1
+				;;
+				Help)
+					whiptail --title "DietPi-Sync Help" --msgbox "DietPi-Sync is a program that allows you to duplicate a directory (Source) to a another location (Target).\n\nFor example: If we want to duplicate (sync) the data on our external USB HDD to another location, we simply select the USB HDD as the source, then, select a target location. The target location can be anything from a networked samba fileserver, or even a FTP server.\n\nIf you would like to test a sync without modifiying any data, simply select Dry Run.\n\nMore information:\n - http://fuzon.co.uk" --backtitle "$WHIP_BACKTITLE" 19 75
 				;;
 				"Dry Run")
 					WHIP_TITLE=' Test Dry Run Sync? '
@@ -333,7 +337,11 @@
 		echo -e "$SYNC_STATS_FILENAME" >> "$FP_EXCLUDE_GLOBAL"
 		echo -e "/var/swap" >> "$FP_EXCLUDE_GLOBAL"
 		echo -e "*.tmp" >> "$FP_EXCLUDE_GLOBAL"
+		# - MS Windows specific
 		echo -e "Thumbs.db" >> "$FP_EXCLUDE_GLOBAL"
+		echo -e "desktop.ini" >> "$FP_EXCLUDE_GLOBAL"
+		#   - causes error code 23 (permission denied)
+		echo -e "System Volume Information" >> "$FP_EXCLUDE_GLOBAL"	
 		
 		#Add users additional list
 		if [ -f "$FP_EXCLUDE_USER" ]; then
@@ -387,18 +395,10 @@
 		
 			#Archive mode
 			local rync_options="-a"
-
 			#verbose
-			rync_options+="v"
-			
-			#Itemize summary
-			#rync_options+="i"
-			
+			rync_options+="v"			
 			#Prefer IPv4
 			rync_options+="4"
-			
-			#Checksum mode (extremly slow, sends and recieves in blocks, allows resuming. Always ensures files are exact copies using 128bit hash)
-			#rync_options+="c"
 			
 			#Dry Run?
 			if (( $SYNC_DRY_RUN == 1 )); then
@@ -408,31 +408,48 @@
 			#Keep partial files (eg: if file is interupted, it will resume where it left off, rather than resending the whole file.
 			rync_options+=" --partial"
 			
+			#Delete mode?
 			if (( $SYNC_DELETE_MODE == 1 )); then
 				rync_options+=" --delete"
 			fi
 			
 			#Remove previous logfile
 			rm "$LOGFILE" &> /dev/null
-
 			echo -e "DietPi-Sync Log File.\n$(date +%d-%m-%Y_%H%M)\nSYNC_DRY_RUN=$SYNC_DRY_RUN\n\n" > "$LOGFILE"
 
 			#Sync
-			rsync $rync_options --log-file=$LOGFILE --exclude-from="$FP_EXCLUDE_GLOBAL" --include-from="$FP_INCLUDE_GLOBAL" "$FP_SOURCE"/ "$FP_TARGET"/			
+			local rsync_exit_code=0
+			rsync $rync_options --log-file=$LOGFILE --exclude-from="$FP_EXCLUDE_GLOBAL" --include-from="$FP_INCLUDE_GLOBAL" "$FP_SOURCE"/ "$FP_TARGET"/
 
-			echo -e "Sync Completed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$SYNC_STATS_FILENAME"
-
-			#Menu
-			if (( $INPUT == 0 )); then
-			
-				if (( $SYNC_DRY_RUN == 0 )); then
-					whiptail --title "Sync completed" --msgbox "$FP_SOURCE\n\nHas been synced to:\n$FP_TARGET\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 13 60
-				else
-					whiptail --title "Dry Run Sync completed" --msgbox "$FP_SOURCE\n\nHas been synced with a Dry Run (NO modifications) to:\n$FP_TARGET\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 13 60
+			#Success
+			if (( $? == 0 )); then
+				echo -e "Sync completed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$SYNC_STATS_FILENAME"
+				#Menu
+				if (( $INPUT == 0 )); then
+				
+					if (( $SYNC_DRY_RUN == 0 )); then
+						whiptail --title "Sync completed" --msgbox "$FP_SOURCE\n\nHas been synced to:\n$FP_TARGET\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 13 60
+					else
+						whiptail --title "Dry Run Sync completed" --msgbox "$FP_SOURCE\n\nHas been synced with a Dry Run (NO modifications) to:\n$FP_TARGET\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 13 60
+					fi
 				fi
-				#return to main menu
-				TARGETMENUID=0
+
+			#Failed
+			else
+				echo -e "Sync failed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET/$SYNC_STATS_FILENAME"
+				#Menu
+				if (( $INPUT == 0 )); then
+				
+					if (( $SYNC_DRY_RUN == 0 )); then
+						whiptail --title "Sync failed" --msgbox "Your sync has failed. Please see the Log file for more information:\n\n$LOGFILE" --backtitle "$WHIP_BACKTITLE" 13 60
+					else
+						whiptail --title "Dry Run Sync failed" --msgbox "Your sync has failed. Please see the Log file for more information:\n\n$LOGFILE" --backtitle "$WHIP_BACKTITLE" 13 60
+					fi
+				fi
 			fi
+
+			#return to main menu
+			TARGETMENUID=0
 
 		#error Folder not found
 		else
