v6.12
+ DietPi-RAMlog | Removed special folder creation and permissions, as "cp -R -p --attributes-only" handles all of this, creates empty folders as well
+ DietPi-RAMlog | Switch to "cp folder/." (with dot), which copies hidden files (<dot>filename) as well and creates target folder, if needed
+ DietPi-RAMlog | Remove default script argument/input to avoid accidents, giving meaningful error output in case
+ DietPi-RAMlog | Add error handling and exit code

diff --git a/dietpi/dietpi-ramlog b/dietpi/dietpi-ramlog
--- a/dietpi/dietpi-ramlog
+++ b/dietpi/dietpi-ramlog
@@ -19,96 +19,72 @@
 	# - /DietPi/dietpi/dietpi-ramlog 1				= Shutdown Phase (saves /var/log)
 	#////////////////////////////////////
 
-	#-----------------------------------------------------------------------------------
+	#-------------------------------------------------------------------------------------
 	#Set locale for all scripts, prevents incorrect scraping
 	export LANG=en_GB.UTF-8
 	export LC_ALL=en_GB.UTF-8
 	#Ensure we are in users home dir: https://github.com/Fourdee/DietPi/issues/905#issuecomment-298223705
 	cd $HOME
-	#-----------------------------------------------------------------------------------
-
-	INPUT=0
-	if [[ $1 =~ ^-?[0-9]+$ ]]; then
-
-		INPUT=$1
-
-	fi
+	#-------------------------------------------------------------------------------------
 
 	#Import DietPi-Globals ---------------------------------------------------------------
 	#. /DietPi/dietpi/func/dietpi-globals # Not compatible until dietpi-boot.service
 	#Import DietPi-Globals ---------------------------------------------------------------
 
 	FILEPATH_DIETPI_RAMLOG_SAVE='/var/lib/dietpi/dietpi-ramlog/storage'
-
-	#/////////////////////////////////////////////////////////////////////////////////////
-	#Funcs
-	#/////////////////////////////////////////////////////////////////////////////////////
-	Apply_Unique_Logfile_Permissions(){
-
-		# - Pihole
-		chown www-data:www-data /var/log/pihole.log
-
-		# - Mongodb
-		chown -R mongodb:mongodb /var/log/mongodb
-
-		# - EmonCMS
-		chmod 666 /var/log/emoncms.log
-
-		# - Tor notices
-		chown -R debian-tor:nogroup /var/log/tor/notices.log
-
-	}
+	EXIT_CODE=0
 
 	#/////////////////////////////////////////////////////////////////////////////////////
 	#Main Loop
 	#/////////////////////////////////////////////////////////////////////////////////////
 	#Startup Phase (restore /var/log directory structure and files)
-	if (( $INPUT == 0 )); then
+	if [[ $INPUT == 0 ]]; then
 
-		echo 'DietPi-Ramlog: Starting'
+		echo 'DietPi-Ramlog: Startup - Restoring log folder structure to ramdisk...'
 
-		#Create core directories, regardless of Logging mode.
-		# - This prevents core system programs failing to write to their logfile (eg: logsave process will not terminate if the /fsck directory does not exist).
-		mkdir -p /var/log/apt &> /dev/null
-		mkdir -p /var/log/apache2 &> /dev/null
-		mkdir -p /var/log/fsck &> /dev/null
-		mkdir -p /var/log/news &> /dev/null
-		mkdir -p /var/log/samba &> /dev/null
-		mkdir -p /var/log/ntpstats &> /dev/null
+		#Set bit permission
+		chmod 775 /var/log
 
 		#Apply previous attributes and ownerships. Generates empty file if it doesnt exist.
-		if [[ -d $FILEPATH_DIETPI_RAMLOG_SAVE ]]; then
+		[[ -d $FILEPATH_DIETPI_RAMLOG_SAVE ]] && cp -R -p --attributes-only $FILEPATH_DIETPI_RAMLOG_SAVE/. /var/log/
+		EXIT_CODE=$?; if (( $EXIT_CODE )); then
 
-			cp -R -p --attributes-only $FILEPATH_DIETPI_RAMLOG_SAVE/* /var/log/
+			echo "DietPi-Ramlog: Startup failed with exit code $EXIT_CODE"
+
+		else
+
+			echo 'DietPi-Ramlog: Startup completed'
 
 		fi
 
-		#Set bit permission
-		chmod -R 775 /var/log
-
-		#Apply any unique permission for software based log files.
-		Apply_Unique_Logfile_Permissions &> /dev/null
-
-		echo 'DietPi-Ramlog: Completed'
-
 	#Shutdown Phase (saves /var/log directory structure and filenames)
-	elif (( $INPUT == 1 )); then
+	elif [[ $INPUT == 1 ]]; then
 
-		echo 'DietPi-Ramlog: Stopping'
+		echo 'DietPi-Ramlog: Shutdown - Saving log folder structure to disk...'
 
 		#Clear previous storage data
-		rm -R $FILEPATH_DIETPI_RAMLOG_SAVE
-
-		#Generate Storage Directory
-		mkdir -p $FILEPATH_DIETPI_RAMLOG_SAVE
+		[[ -d $FILEPATH_DIETPI_RAMLOG_SAVE ]] && rm -R $FILEPATH_DIETPI_RAMLOG_SAVE
 
 		#Copy logfile attributes and ownership to storage (not file contents)
-		cp -R -p --attributes-only /var/log/* $FILEPATH_DIETPI_RAMLOG_SAVE/
+		cp -R -p --attributes-only /var/log/. $FILEPATH_DIETPI_RAMLOG_SAVE/
+		EXIT_CODE=$?; if (( $EXIT_CODE )); then
 
-		echo 'DietPi-Ramlog: Completed'
+			echo "DietPi-Ramlog: Shutdown failed with exit code $EXIT_CODE"
+
+		else
+
+			echo 'DietPi-Ramlog: Shutdown completed'
+
+		fi
+
+	#Unknown argument
+	else
+
+		EXIT_CODE=1
+		echo 'DietPi-Ramlog: Aborted - Unknown input mode'
 
 	fi
 	#-----------------------------------------------------------------------------------
-	exit
+	exit $EXIT_CODE
 	#-----------------------------------------------------------------------------------
 }
