v148
+ DietPi-Software | MotionEye: Now available for installation (RPi
only). Web interface and surveillance for your RPi/USB camera. Mainly
focused towards motion detection usage:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=100

+ DietPi-Set_Hardware | RPi Camera: Now enables bcm2835-v4l2 by default.
Required for /dev/video0 stream (mainly for motioneye).

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -245,7 +245,7 @@ _EOF_
 	# - Software
 	#NB: All software has a unique index that must not be changed (eg: DESKTOP_LXDE = 23)
 	TOTAL_SOFTWARE_INDEXS=0
-	TOTAL_SOFTWARE_INDEXS_HARDLIMIT=136	#Increase as needed. Must be higher than TOTAL_SOFTWARE_INDEXS once calculated in Software_Arrays_Init
+	TOTAL_SOFTWARE_INDEXS_HARDLIMIT=137	#Increase as needed. Must be higher than TOTAL_SOFTWARE_INDEXS once calculated in Software_Arrays_Init
 
 	INSTALLING_INDEX=0					#Which software index is currently being installed?
 
@@ -1128,6 +1128,24 @@ _EOF_
 					  aSOFTWARE_TYPE[$index_current]=0
 		aSOFTWARE_REQUIRES_WEBSERVER[$index_current]=1
 			 aSOFTWARE_ONLINEDOC_URL[$index_current]='f=8&t=5#p48'
+
+		# - Disabled for All non-rpi
+		for ((i=10; i<=$MAX_HW_MODEL; i++))
+		do
+
+			aSOFTWARE_AVAIL_HW_MODEL[$index_current,$i]=0
+
+		done
+
+		#------------------
+		index_current=136
+
+				 aSOFTWARE_WHIP_NAME[$index_current]='MotionEye'
+				 aSOFTWARE_WHIP_DESC[$index_current]='web interface & surveillance for your camera'
+			aSOFTWARE_CATEGORY_INDEX[$index_current]=7
+					  aSOFTWARE_TYPE[$index_current]=0
+			 aSOFTWARE_ONLINEDOC_URL[$index_current]='f=8&t=5&p=6610#p6610'
+ 		   aSOFTWARE_REQUIRES_FFMPEG[$index_current]=1
 
 		# - Disabled for All non-rpi
 		for ((i=10; i<=$MAX_HW_MODEL; i++))
@@ -2515,7 +2533,8 @@ _EOF_
 		#Software that requires Python-Pip: https://github.com/Fourdee/DietPi/issues/784
 		if (( ${aSOFTWARE_INSTALL_STATE[58]} == 1 ||
 			${aSOFTWARE_INSTALL_STATE[99]} == 1 ||
-			${aSOFTWARE_INSTALL_STATE[118]} == 1 )); then
+			${aSOFTWARE_INSTALL_STATE[118]} == 1 ||
+			${aSOFTWARE_INSTALL_STATE[136]} == 1 )); then
 
 			if (( ${aSOFTWARE_INSTALL_STATE[130]} == 0 )); then
 
@@ -2531,13 +2550,18 @@ _EOF_
 		#	HiFi
 		#	Cava
 		#	OMPD
-		if (( ( ${aSOFTWARE_INSTALL_STATE[32]} == 1 ||  ${aSOFTWARE_INSTALL_STATE[119]} == 1 || ${aSOFTWARE_INSTALL_STATE[129]} == 1 ) &&
-			${aSOFTWARE_INSTALL_STATE[128]} == 0 )); then
+		if (( ${aSOFTWARE_INSTALL_STATE[32]} == 1 ||
+			${aSOFTWARE_INSTALL_STATE[119]} == 1 ||
+			${aSOFTWARE_INSTALL_STATE[129]} == 1 )); then
 
-			# - Flag for install
-			aSOFTWARE_INSTALL_STATE[128]=1
+			if (( ${aSOFTWARE_INSTALL_STATE[128]} == 0 )); then
 
-			/DietPi/dietpi/func/dietpi-notify 2 "MPD will be installed"
+				# - Flag for install
+				aSOFTWARE_INSTALL_STATE[128]=1
+
+				/DietPi/dietpi/func/dietpi-notify 2 "MPD will be installed"
+
+			fi
 
 		fi
 
@@ -5870,6 +5894,37 @@ _EOF_
 
 				# - Prevent Debian repo from replacing our chromium packages: https://github.com/Fourdee/DietPi/issues/658
 				apt-mark hold chromium chromedriver
+
+			else
+
+				Error_NoConnection_NoInstall
+
+			fi
+
+		fi
+
+		#MotionEye
+		INSTALLING_INDEX=136
+		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
+
+			Banner_Installing
+
+			INSTALL_URL_ADDRESS='http://github.com/Motion-Project/motion/releases/download/release-4.0.1/pi_jessie_motion_4.0.1-1_armhf.deb'
+
+			#url/redireect always fails wget spider test...
+			/DietPi/dietpi/func/check_connection "http://github.com/Motion-Project/motion"
+			if (( $? == 0 )); then
+
+				# - Prereqs
+				AGI v4l-utils python python-dev curl libssl-dev libcurl4-openssl-dev libjpeg-dev libx264-142 libavcodec56 libavformat56 libmysqlclient18 libswscale3 libpq5
+
+				# - Motion
+				wget "$INSTALL_URL_ADDRESS" -O package.deb
+				dpkg -i package.deb
+				rm package.deb
+
+				# - Motioneye
+				pip install motioneye
 
 			else
 
@@ -9814,6 +9869,28 @@ WantedBy=multi-user.target
 _EOF_
 
 		fi
+
+		#MotionEye
+		INSTALLING_INDEX=136
+		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
+
+			#Enable RPi cam
+			if (( $HW_MODEL < 10 )); then
+
+				/DietPi/dietpi/func/dietpi-set_hardware rpi-camera enable
+
+			fi
+
+			mkdir -p /etc/motioneye
+			cp /usr/local/share/motioneye/extra/motioneye.conf.sample /etc/motioneye/motioneye.conf
+
+			mkdir -p "$FP_DIETPI_USERDATA_DIRECTORY"/motioneye
+			sed -i "/^media_path/c\media_path $FP_DIETPI_USERDATA_DIRECTORY/motioneye" /etc/motioneye/motioneye.conf
+
+			#	service
+			cp /usr/local/share/motioneye/extra/motioneye.systemd-unit-local /etc/systemd/system/motioneye.service
+
+		fi
 		#-------------------------------------------------------------------
 
 	}
@@ -10145,6 +10222,17 @@ _EOF_
 			AGP darkice icecast2
 			rm /etc/systemd/system/darkice.service
 			systemctl daemon-reload
+
+		elif (( $1 == 136 )); then
+
+			AGP motion
+
+			rm -R /etc/motioneye
+
+			rm /etc/systemd/system/motioneye.service
+			systemctl daemon-reload
+
+			pip uninstall -y motioneye
 
 		elif (( $1 == 119 )); then
 
