v6.29
+ DietPi-Update | Remove /DietPi mount point usage and related RAMdisk sync tasks

diff --git a/dietpi/dietpi-update b/dietpi/dietpi-update
--- a/dietpi/dietpi-update
+++ b/dietpi/dietpi-update
@@ -1,5 +1,4 @@
 #!/bin/bash
-# Load the whole script into memory
 {
 	#////////////////////////////////////
 	# DietPi Update
@@ -10,7 +9,7 @@
 	#////////////////////////////////////
 	#
 	# Info:
-	# - Location: /{DietPi,boot}/dietpi/dietpi-update
+	# - Location: /boot/dietpi/dietpi-update
 	# - Updates DietPi from Git or dietpi.com repo
 	# - Uses pre-patch_file for patches that need to be done prior to APT calls and DietPi code update
 	# - Uses patch_file for incremental patching after APT calls and DietPi code update
@@ -18,12 +17,12 @@
 	# Usage:
 	# - dietpi-update	= Check for updates and in case open interactive menu
 	# - dietpi-update 1	= Check for updates and in case apply noninteractively
-	# - dietpi-update 2	= Check for updates only and in case store result to /DietPi/dietpi/.update_available to be used by DietPi-Banner
+	# - dietpi-update 2	= Check for updates only and in case store result to /boot/dietpi/.update_available to be used by DietPi-Banner
 	# - dietpi-update -1	= Like "1" but internally reduce subversion by 1 to reapply the last update, e.g. to apply latest dev branch changes
 	#////////////////////////////////////
 
 	# Import DietPi-Globals --------------------------------------------------------------
-	. /DietPi/dietpi/func/dietpi-globals
+	. /boot/dietpi/func/dietpi-globals
 	G_PROGRAM_NAME='DietPi-Update'
 	G_CHECK_ROOT_USER
 	G_CHECK_ROOTFS_RW
@@ -52,17 +51,17 @@
 	UPDATE_AVAILABLE=0
 	RUN_UPDATE=0
 
-	GITOWNER_TARGET=$(sed -n '/^[[:blank:]]*DEV_GITOWNER=/{s/^[^=]*=//p;q}' /DietPi/dietpi.txt)
+	GITOWNER_TARGET=$(sed -n '/^[[:blank:]]*DEV_GITOWNER=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
 	GITOWNER_TARGET=${GITOWNER_TARGET:-MichaIng}
-	GITBRANCH_TARGET=$(sed -n '/^[[:blank:]]*DEV_GITBRANCH=/{s/^[^=]*=//p;q}' /DietPi/dietpi.txt)
+	GITBRANCH_TARGET=$(sed -n '/^[[:blank:]]*DEV_GITBRANCH=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
 	GITBRANCH_TARGET=${GITBRANCH_TARGET:-master}
 
 	COREVERSION_SERVER=0
 	SUBVERSION_SERVER=0
 	RCVERSION_SERVER=0
 
-	INFO_CURRENT_VERSION=''
-	INFO_SERVER_VERSION=''
+	INFO_CURRENT_VERSION=
+	INFO_SERVER_VERSION=
 	INFO_VERSIONS_UPDATE(){
 
 		INFO_CURRENT_VERSION="Current version : v$G_DIETPI_VERSION_CORE.$G_DIETPI_VERSION_SUB.$G_DIETPI_VERSION_RC"
@@ -155,7 +154,7 @@ If this error persists, please report at: https://github.com/MichaIng/DietPi/iss
 
 	}
 
-	Apply_1st_Run_Update_Success(){ [[ $G_DIETPI_INSTALL_STAGE == [12] ]] || echo 1 > /DietPi/dietpi/.install_stage; }
+	Apply_1st_Run_Update_Success(){ [[ $G_DIETPI_INSTALL_STAGE == [12] ]] || echo 1 > /boot/dietpi/.install_stage; }
 
 	Check_Update_Available(){
 
@@ -163,7 +162,7 @@ If this error persists, please report at: https://github.com/MichaIng/DietPi/iss
 		if (( $DIETPIUPDATE_VERSION_CORE < $COREVERSION_SERVER )); then
 
 			# Write "-1" to flag file for DietPi-Banner to show info about required new image
-			echo '-1' > /DietPi/dietpi/.update_available
+			echo '-1' > /boot/dietpi/.update_available
 
 			G_DIETPI-NOTIFY 1 'The installed version of DietPi is now obsolete and cannot be updated.
 Please download the latest DietPi image from: https://dietpi.com/#download'
@@ -175,7 +174,7 @@ Please download the latest DietPi image from: https://dietpi.com/#download'
 			UPDATE_AVAILABLE=1
 
 			# Write available update version to flag file
-			echo "$COREVERSION_SERVER.$SUBVERSION_SERVER.$RCVERSION_SERVER" > /DietPi/dietpi/.update_available
+			echo "$COREVERSION_SERVER.$SUBVERSION_SERVER.$RCVERSION_SERVER" > /boot/dietpi/.update_available
 
 			G_DIETPI-NOTIFY 0 'Update available:'
 
@@ -185,8 +184,8 @@ Please download the latest DietPi image from: https://dietpi.com/#download'
 			# Mark 1st run update as completed
 			Apply_1st_Run_Update_Success
 
-			# Remove .update_available flag file (from disk as well, to prevent update notification after reboot)
-			rm -f /{DietPi,boot}/dietpi/.update_available
+			# Remove .update_available flag file
+			[[ -f '/boot/dietpi/.update_available' ]] && rm /boot/dietpi/.update_available
 
 			G_DIETPI-NOTIFY 0 'No update required, your DietPi installation is already up to date:'
 
@@ -238,11 +237,11 @@ Please download the latest DietPi image from: https://dietpi.com/#download'
 
 			# Remove old code before updating, so we dont need to patch for removals
 			# - https://github.com/MichaIng/DietPi/issues/905#issuecomment-298241622
-			#rm -R /DietPi/dietpi/{func,misc,dietpi-*}
+			#rm -R /boot/dietpi/{func,misc,dietpi-*}
 
-			l_message='Installing new DietPi scripts to RAMdisk' G_RUN_CMD cp -Rf DietPi-"$GITBRANCH_TARGET"/dietpi /DietPi/
-			l_message='Installing new DietPi system files to disk' G_RUN_CMD cp -Rf DietPi-"$GITBRANCH_TARGET"/rootfs/. /
-			l_message='Setting execute permissions for DietPi scripts' G_RUN_CMD chmod -R +x /DietPi/dietpi /var/lib/dietpi/services /etc/cron.*/dietpi
+			l_message='Installing new DietPi scripts' G_RUN_CMD cp -Rf DietPi-"$GITBRANCH_TARGET"/dietpi /boot/
+			l_message='Installing new DietPi system files' G_RUN_CMD cp -Rf DietPi-"$GITBRANCH_TARGET"/rootfs/. /
+			l_message='Setting execute permissions for DietPi scripts' G_RUN_CMD chmod -R +x /boot/dietpi /var/lib/dietpi/services /etc/cron.*/dietpi
 
 			# Save version + Git info now for sub scripts to pull from correct branch
 			G_GITOWNER=$GITOWNER_TARGET
@@ -250,7 +249,7 @@ Please download the latest DietPi image from: https://dietpi.com/#download'
 			G_VERSIONDB_SAVE
 
 			# Verify/update dietpi.txt entries
-			/DietPi/dietpi/func/dietpi-set_software verify_dietpi.txt || exit 1
+			/boot/dietpi/func/dietpi-set_software verify_dietpi.txt || exit 1
 
 			# Failsafe: Sync changes to disk
 			sync
@@ -264,7 +263,7 @@ Please download the latest DietPi image from: https://dietpi.com/#download'
 			while (( $G_DIETPI_VERSION_SUB < $SUBVERSION_SERVER )); do
 
 				G_DIETPI-NOTIFY 2 "Patching $G_DIETPI_VERSION_CORE.$G_DIETPI_VERSION_SUB to $COREVERSION_SERVER.$(( $G_DIETPI_VERSION_SUB + 1 ))"
-				/DietPi/dietpi/patch_file || exit 1
+				/boot/dietpi/patch_file || exit 1
 				G_DIETPI_VERSION_SUB=$(( $G_DIETPI_VERSION_SUB + 1 ))
 				# Save reached version info, use RC version "0" before last patch has completed
 				(( $G_DIETPI_VERSION_SUB == $SUBVERSION_SERVER )) && G_DIETPI_VERSION_RC=$RCVERSION_SERVER || G_DIETPI_VERSION_RC=0
@@ -275,7 +274,7 @@ Please download the latest DietPi image from: https://dietpi.com/#download'
 			G_DIETPI-NOTIFY 0 "Incremental patching to v$COREVERSION_SERVER.$SUBVERSION_SERVER.$RCVERSION_SERVER completed"
 
 			# Remove patch_file
-			rm /DietPi/dietpi/patch_file
+			rm /boot/dietpi/patch_file
 
 			# Update info strings
 			INFO_VERSIONS_UPDATE
@@ -337,7 +336,7 @@ Please download the latest DietPi image from: https://dietpi.com/#download'
 
 			local auto_updates_enabled=0
 			local auto_updates_text='Off'
-			if grep -qi '^[[:blank:]]*CONFIG_AUTO_DIETPI_UPDATES=1' /DietPi/dietpi.txt; then
+			if grep -qi '^[[:blank:]]*CONFIG_AUTO_DIETPI_UPDATES=1' /boot/dietpi.txt; then
 
 				auto_updates_enabled=1
 				auto_updates_text='On'
@@ -383,7 +382,7 @@ Do you wish to continue and update DietPi to v$COREVERSION_SERVER.$SUBVERSION_SE
 \nWe highly recommend you create a system backup with "DietPi-Backup" if using this feature, as automated updates will not prompt user if a failure occurs.
 \nWhen DietPi applies updates, all system services will be temporarily stopped. Do NOT power off the unit during updates as this could render the system in a unrecoverable state.'
 
-					G_CONFIG_INJECT 'CONFIG_AUTO_DIETPI_UPDATES=' "CONFIG_AUTO_DIETPI_UPDATES=$auto_updates_enabled" /DietPi/dietpi.txt
+					G_CONFIG_INJECT 'CONFIG_AUTO_DIETPI_UPDATES=' "CONFIG_AUTO_DIETPI_UPDATES=$auto_updates_enabled" /boot/dietpi.txt
 
 				elif [[ $G_WHIP_RETURNED_VALUE == 'Changelog' ]]; then
 
@@ -425,7 +424,7 @@ Do you wish to continue and update DietPi to v$COREVERSION_SERVER.$SUBVERSION_SE
 
 	fi
 	#----------------------------------------------------------------
-	# Check for update and in case store result to /DietPi/dietpi/.update_available for use by DietPi-Banner
+	# Check for update and in case store result to /boot/dietpi/.update_available for use by DietPi-Banner
 	Check_Update_Available
 	#----------------------------------------------------------------
 	# Update available and no check-only chosen
@@ -450,7 +449,7 @@ Do you wish to continue and update DietPi to v$COREVERSION_SERVER.$SUBVERSION_SE
 			setterm -blank 0 -powersave off 2> /dev/null
 
 			# Stop Services
-			/DietPi/dietpi/dietpi-services stop
+			/boot/dietpi/dietpi-services stop
 
 			# Run_Update: https://github.com/MichaIng/DietPi/issues/1877#issuecomment-403866204
 			# - Log to file by redirecting to subshell instead of piping, else G_ERROR_HANDLER cannot exit the script via "kill -INT $$": https://github.com/MichaIng/DietPi/issues/3127
@@ -459,24 +458,21 @@ Do you wish to continue and update DietPi to v$COREVERSION_SERVER.$SUBVERSION_SE
 			# Mark 1st run update as completed
 			Apply_1st_Run_Update_Success
 
-			# Remove .update_available flag file (from disk as well, to prevent update notification after reboot)
-			rm -f /{DietPi,boot}/dietpi/.update_available
+			# Remove .update_available flag file
+			rm /boot/dietpi/.update_available
 
 			G_DIETPI-NOTIFY 3 "$G_PROGRAM_NAME" 'Completed'
 			G_DIETPI-NOTIFY 2 "$INFO_CURRENT_VERSION"
 			G_DIETPI-NOTIFY 2 "$INFO_SERVER_VERSION"
 
 			# Update DietPi-Survey
-			/DietPi/dietpi/dietpi-survey 1
+			/boot/dietpi/dietpi-survey 1
 
-			# Failsafe: Store RAMdisk to disk which includes "sync"
-			# - https://github.com/MichaIng/DietPi/issues/2473#issuecomment-458874222
-			# - https://dietpi.com/phpbb/viewtopic.php?f=9&t=2591
-			l_message='Syncing new DietPi scripts to disk' G_RUN_CMD /DietPi/dietpi/func/dietpi-ramdisk 1
-			> /DietPi/.ramdisk
+			# Failsafe: Force sync to disk
+			sync
 
 			# Start services only on finished install state, else dietpi-software will follow immediately
-			(( $G_DIETPI_INSTALL_STAGE == 2 )) && /DietPi/dietpi/dietpi-services restart
+			(( $G_DIETPI_INSTALL_STAGE == 2 )) && /boot/dietpi/dietpi-services restart
 
 		fi
 
