v120
+ Cuberite: https://github.com/Fourdee/DietPi/issues/358

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -326,6 +326,7 @@ MUMBLESERVER=${MUMBLESERVER:=0}
 EMBYSERVER=${EMBYSERVER:=0}
 OPENBAZAAR=${OPENBAZAAR:=0}
 PLEXMEDIASERVER=${PLEXMEDIASERVER:=0}
+CUBERITE=${CUBERITE:=0}
 
 #Additional Linux Software
 VIMFULL=${VIMFULL:=0}
@@ -2143,6 +2144,43 @@ INDEX_WEBSERVER_TARGET=${INDEX_WEBSERVER_TARGET:=-2}
 
 				#Abort failed install
 				PLEXMEDIASERVER=0
+			fi
+
+		fi
+
+		#CUBERITE
+		if (( $CUBERITE == 1 )); then
+			INSTALL_DESCRIPTION='Cuberite (Minecraft Server)'
+			Banner_Installing
+
+			#check folder is online
+
+			#x86_64
+			if (( $HW_ARCH == 21 )); then
+				INSTALL_URL_ADDRESS='http://builds.cuberite.org/job/Cuberite%20Linux%20x64%20Master/lastSuccessfulBuild/artifact/Cuberite.tar.gz'
+			#32bit ARM
+			elif (( $HW_ARCH >= 1 && $HW_ARCH < 10 )); then
+				INSTALL_URL_ADDRESS='http://builds.cuberite.org/job/Cuberite%20Linux%20raspi-armhf%20Master/lastSuccessfulBuild/artifact/Cuberite.tar.gz'
+			fi
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+			#Install
+			if (( $? == 0 )); then
+
+				wget "$INSTALL_URL_ADDRESS" -O package.tar
+				mkdir -p /etc/cubrite
+				tar xzvf package.tar -C /etc/cubrite
+				rm package.tar
+
+				# - Move everything into base directory (cuberite)
+				mv /etc/cubrite/Server/* /etc/cubrite/
+				rm -R /etc/cuberite/Server
+
+			else
+				Error_NoConnection_NoInstall
+
+				#Abort failed install
+				CUBERITE=0
 			fi
 
 		fi
@@ -4811,6 +4849,32 @@ _EOF_
 
 		fi
 
+		#CUBERITE
+		if (( $CUBERITE == 1 )); then
+
+			cat << _EOF_ > /etc/systemd/system/cuberite.service
+[Unit]
+Description=Cuberite Server
+
+[Service]
+Type=oneshot
+WorkingDirectory=/etc/cubrite
+ExecStart=/etc/cubrite/Cuberite --service
+ExecStop=/usr/bin/killall -w Cuberite
+RemainAfterExit=yes
+User=root
+
+[Install]
+WantedBy=multi-user.target
+_EOF_
+systemctl enable cuberite.service
+systemctl daemon-reload
+
+
+			CUBERITE=2
+
+		fi
+
 	}
 
 	Install_Apply_GPU_Settings(){
@@ -6477,6 +6541,15 @@ _EOF_
 			fi
 		fi
 
+		local cuberite_w="off"
+		if (( $CUBERITE > 0 )); then
+			cuberite_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $CUBERITE == 1 )); then
+				CUBERITE=0
+			fi
+		fi
+
 		#-----------------------------------------------------------------------------
 		WHIP_TITLE='DietPi Optimized Software Selection'
 
@@ -6576,6 +6649,8 @@ _EOF_
 			"" "────Cloud / Backups─────────────────────────" "off" \
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
+			"" "────Gaming──────────────────────────────────" "off" \
+			"Cuberite" "Minecraft Server (C++)" $cuberite_w \
 			"" "────Social Media───────────────────────────" "off" \
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
@@ -6643,6 +6718,8 @@ _EOF_
 			"" "────Cloud / Backups────────────────────────" "off" \
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
+			"" "────Gaming──────────────────────────────────" "off" \
+			"Cuberite" "Minecraft Server (C++)" $cuberite_w \
 			"" "────Social Media───────────────────────────" "off" \
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
@@ -6709,6 +6786,8 @@ _EOF_
 			"" "────Cloud / Backups─────────────────────────" "off" \
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Pydio" "Feature-rich backup and sync server" $pydio_w \
+			"" "────Gaming──────────────────────────────────" "off" \
+			"Cuberite" "Minecraft Server (C++)" $cuberite_w \
 			"" "────Social Media───────────────────────────" "off" \
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 			"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
@@ -6791,6 +6870,7 @@ _EOF_
 				"Pydio" "Feature-rich backup and sync server" $pydio_w \
 				"" "────Gaming──────────────────────────────────" "off" \
 				"OpenTyrian" "Gaming: A classic retro game, addictive." $opentyrian_w \
+				"Cuberite" "Minecraft Server (C++)" $cuberite_w \
 				"" "────Social Media───────────────────────────" "off" \
 				"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 				"Wordpress" "Website Blog and Publishing platform." $wordpress_w \
@@ -6920,6 +7000,12 @@ _EOF_
 		do
 			case $choice in
 
+			Cuberite)
+				if (( $CUBERITE == 0 )); then
+					CUBERITE=1
+					INSTALL_DIETPI_CHOICESMADE=1
+				fi
+			;;
 			"MATE: Desktop")
 				if (( $DESKTOP_MATE == 0 )); then
 					DESKTOP_MATE=1
