v6.26 (#3000)
+ DietPi-Set_hardware | RPi: Fix deprecated or renamed dtoverlays/params: https://github.com/raspberrypi/firmware/commit/d36bde339b067bf13b610fd9741d6351c1dafc38#diff-32265084aeae5fd34fbaf894f22fb20f
+ DietPi-Set_hardware | RPi: Disable Onboard WiFi and Bluetooth via dtoverlay
+ DietPi-Set_hardware | Add "dietpi-" prefix to WiFi and Bluetooth blacklist files to show they are from us
+ DietPi-Set_hardware | wifimodules: Merge WiFi powersaving settings into a single file with "dietpi-" prefix, to simplify and show it's from us
+ DietPi-Set_hardware | wifimodules: Offer to purge WiFi APT packages on disable
+ DietPi-Set_hardware | wifimodules: Enable modules first, install APT packages afterwards, to allow possible auto-configuration
+ DietPi-Set_hardware | wifimodules: Do not exit immediately when APT installs fail, instead set $EXIT_CODE=1 to have .network file updated and print script failure for user info
+ DietPi-Config | Adjust RPi onboard WiFi state detection based on dtoverlay=disable_wifi
+ DietPi-Config | Adjust Bluetooth state detection based on renamed blacklist file
+ DietPi-Config | Minor coding wording and visual
+ DietPi-Patch | WiFi+BT config file renaming, method changes and config.txt fixes due to changes in recent firmware

diff --git a/dietpi/dietpi-config b/dietpi/dietpi-config
--- a/dietpi/dietpi-config
+++ b/dietpi/dietpi-config
@@ -1321,7 +1321,7 @@ NB: You now need to run "apt update" or "G_AGUP" once after each reboot, before 
 
 			local bluetooth_state_text='On'
 			local bluetooth_state=1
-			if [[ -f '/etc/modprobe.d/disable_bt.conf' ]]; then
+			if [[ -f '/etc/modprobe.d/dietpi-disable_bluetooth.conf' ]]; then
 
 				bluetooth_state=0
 				bluetooth_state_text='Off'
@@ -1620,7 +1620,7 @@ Please reboot this system once, the HW bit which allows USB boot support will th
 		# Define CPU scaling frequency or percent
 		local type_cpu_freq_info='MHz'
 		# - Intel
-		[[ -f /sys/devices/system/cpu/intel_pstate/max_perf_pct ]] && type_cpu_freq_info='%'
+		[[ -f '/sys/devices/system/cpu/intel_pstate/max_perf_pct' ]] && type_cpu_freq_info='%'
 
 		# - User Scaling Max Freq limit.
 		local user_frequency_max_current=$(grep -m1 '^[[:blank:]]*CONFIG_CPU_MAX_FREQ=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')
@@ -1655,8 +1655,7 @@ Please reboot this system once, the HW bit which allows USB boot support will th
 
 				'Intel Turbo/Boost'*)
 
-					(( intel_boost_disabled++ ))
-					(( $intel_boost_disabled > 1 )) && intel_boost_disabled=0
+					(( $intel_boost_disabled )) && intel_boost_disabled=0 || intel_boost_disabled=1
 					G_CONFIG_INJECT 'CONFIG_CPU_DISABLE_TURBO=' "CONFIG_CPU_DISABLE_TURBO=$intel_boost_disabled" /DietPi/dietpi.txt
 					/DietPi/dietpi/func/dietpi-set_cpu
 
@@ -2115,8 +2114,8 @@ Current setting: $user_frequency_min_text" && G_CONFIG_INJECT 'CONFIG_CPU_MIN_FR
 
 	NET_RX_BYTE=0
 	NET_TX_BYTE=0
-	NET_RX_MB='Unknown'
-	NET_TX_MB='Unknown'
+	NET_RX_MB='N/A'
+	NET_TX_MB='N/A'
 
 	# $1 = device+index
 	Net_Update_UsageStats(){
@@ -2128,23 +2127,13 @@ Current setting: $user_frequency_min_text" && G_CONFIG_INJECT 'CONFIG_CPU_MIN_FR
 		NET_RX_MB='N/A'
 		NET_TX_MB='N/A'
 
-		if [[ -f /sys/class/net/$input/statistics/rx_bytes && -f /sys/class/net/$input/statistics/tx_bytes ]]; then
+		if [[ -f '/sys/class/net/$input/statistics/rx_bytes' && -f '/sys/class/net/$input/statistics/tx_bytes' ]]; then
 
 			NET_RX_BYTE=$(</sys/class/net/$input/statistics/rx_bytes)
+			disable_error=1 G_CHECK_VALIDINT "$NET_RX_BYTE" 1 && NET_RX_MB="$(( $NET_RX_BYTE / 1024 / 1024 )) MiB"
+
 			NET_TX_BYTE=$(</sys/class/net/$input/statistics/tx_bytes)
-			NET_RX_MB='Unknown'
-			if disable_error=1 G_CHECK_VALIDINT "$NET_RX_BYTE" 1; then
-
-				NET_RX_MB="$(( $NET_RX_BYTE / 1024 / 1024 ))MB"
-
-			fi
-
-			NET_TX_MB='Unknown'
-			if disable_error=1 G_CHECK_VALIDINT "$NET_TX_BYTE" 1; then
-
-				NET_TX_MB="$(( $NET_TX_BYTE / 1024 / 1024 ))MB"
-
-			fi
+			disable_error=1 G_CHECK_VALIDINT "$NET_TX_BYTE" 1 && NET_TX_MB="$(( $NET_TX_BYTE / 1024 / 1024 )) MiB"
 
 		fi
 
@@ -2163,7 +2152,7 @@ Current setting: $user_frequency_min_text" && G_CONFIG_INJECT 'CONFIG_CPU_MIN_FR
 	ETH_GATEWAY='0.0.0.0'
 	ETH_MASK='0.0.0.0'
 	ETH_DNS='0.0.0.0'
-	ETH_MODE=1 #0=static 1=dhcp
+	ETH_MODE=1 # 0=static 1=dhcp
 	ETH_MODE_TARGET=0
 
 	WIFI_IP_STATIC='0.0.0.0'
@@ -2266,10 +2255,10 @@ Current setting: $user_frequency_min_text" && G_CONFIG_INJECT 'CONFIG_CPU_MIN_FR
 
 		G_DIETPI-NOTIFY 0 'Network restarted'
 
-		if ( (( $ETH_MODE_TARGET == 0 )) && [[ $ETH_IP != $ETH_IP_STATIC ]] ) ||
-			( (( $WIFI_MODE_TARGET == 0 )) && [[ $WIFI_IP != $WIFI_IP_STATIC ]] ); then
+		if [[ $ETH_MODE_TARGET == 0 && $ETH_IP != $ETH_IP_STATIC ]] ||
+			[[ $WIFI_MODE_TARGET == 0 && $WIFI_IP != $WIFI_IP_STATIC ]]; then
 
-			G_WHIP_MSG "IP STATIC address change detected. A reboot is required to apply the new IP.\n\nPlease reboot the system."
+			G_WHIP_MSG 'IP STATIC address change detected. A reboot is required to apply the new IP.\n\nPlease reboot the system.'
 			REBOOT_REQUIRED=1
 
 		fi
@@ -2279,7 +2268,7 @@ Current setting: $user_frequency_min_text" && G_CONFIG_INJECT 'CONFIG_CPU_MIN_FR
 	Network_ApplyChanges(){
 
 		# Eth
-		local eth_enabled_text=''
+		local eth_enabled_text
 		(( $ETH_DISABLED )) && eth_enabled_text='#'
 
 		local eth_dhcp_static_text='dhcp'
@@ -2296,7 +2285,7 @@ Current setting: $user_frequency_min_text" && G_CONFIG_INJECT 'CONFIG_CPU_MIN_FR
 		fi
 
 		# WiFi
-		local wifi_enabled_text=''
+		local wifi_enabled_text
 		(( $WIFI_DISABLED )) && wifi_enabled_text='#'
 
 		local wifi_dhcp_static_text='dhcp'
@@ -2384,13 +2373,13 @@ _EOF_
 		if (( $1 == 0 )); then
 
 			G_WHIP_DEFAULT_ITEM=$ETH_IP_STATIC
-			G_WHIP_INPUTBOX 'Please enter a new static IP address' && ETH_IP_STATIC=$G_WHIP_RETURNED_VALUE
+			G_WHIP_INPUTBOX 'Please enter a new static Ethernet IP address:' && ETH_IP_STATIC=$G_WHIP_RETURNED_VALUE
 
 		# WiFi
 		elif (( $1 == 1 )); then
 
 			G_WHIP_DEFAULT_ITEM=$WIFI_IP_STATIC
-			G_WHIP_INPUTBOX 'Please enter a new static IP address' && WIFI_IP_STATIC=$G_WHIP_RETURNED_VALUE
+			G_WHIP_INPUTBOX 'Please enter a new static WiFi IP address:' && WIFI_IP_STATIC=$G_WHIP_RETURNED_VALUE
 
 		fi
 
@@ -2402,13 +2391,13 @@ _EOF_
 		if (( $1 == 0 )); then
 
 			G_WHIP_DEFAULT_ITEM=$ETH_GATEWAY_STATIC
-			G_WHIP_INPUTBOX 'Please enter a new static Gateway address' && ETH_GATEWAY_STATIC=$G_WHIP_RETURNED_VALUE
+			G_WHIP_INPUTBOX 'Please enter a new static Ethernet gateway address:' && ETH_GATEWAY_STATIC=$G_WHIP_RETURNED_VALUE
 
 		# WiFi
 		elif (( $1 == 1 )); then
 
 			G_WHIP_DEFAULT_ITEM=$WIFI_GATEWAY_STATIC
-			G_WHIP_INPUTBOX 'Please enter a new static Gateway address' && WIFI_GATEWAY_STATIC=$G_WHIP_RETURNED_VALUE
+			G_WHIP_INPUTBOX 'Please enter a new static WiFi gateway address:' && WIFI_GATEWAY_STATIC=$G_WHIP_RETURNED_VALUE
 
 		fi
 
@@ -2420,13 +2409,13 @@ _EOF_
 		if (( $1 == 0 )); then
 
 			G_WHIP_DEFAULT_ITEM=$ETH_MASK_STATIC
-			G_WHIP_INPUTBOX 'Please enter a new static Mask address' && ETH_MASK_STATIC=$G_WHIP_RETURNED_VALUE
+			G_WHIP_INPUTBOX 'Please enter a new static Ethernet network mask:' && ETH_MASK_STATIC=$G_WHIP_RETURNED_VALUE
 
 		# WiFi
 		elif (( $1 == 1 )); then
 
 			G_WHIP_DEFAULT_ITEM=$WIFI_MASK_STATIC
-			G_WHIP_INPUTBOX 'Please enter a new static Mask address' && WIFI_MASK_STATIC=$G_WHIP_RETURNED_VALUE
+			G_WHIP_INPUTBOX 'Please enter a new static WiFi network mask:' && WIFI_MASK_STATIC=$G_WHIP_RETURNED_VALUE
 
 		fi
 
@@ -2456,7 +2445,7 @@ _EOF_
 		# Create Menu List for Whiptail
 		G_WHIP_MENU_ARRAY=(
 
-			'Custom' 'Manually enter your DNS server'
+			'Custom' ': Manually enter your DNS server'
 			'8.8.8.8 8.8.4.4' ': Google'
 			'208.67.222.222 208.67.220.220' ': OpenDNS'
 			'209.244.0.3 209.244.0.4' ': Level3'
@@ -2469,27 +2458,25 @@ _EOF_
 		)
 
 		G_WHIP_DEFAULT_ITEM=$current_value
-		if G_WHIP_MENU 'Please select a DNS server, or choose custom for manual entry.'; then
+		G_WHIP_MENU 'Please select a DNS server, or choose "Custom" for manual entry:' || return
 
-			case $G_WHIP_RETURNED_VALUE in
+		case $G_WHIP_RETURNED_VALUE in
 
-				'Custom')
+			'Custom')
 
-					G_WHIP_DEFAULT_ITEM=$current_value
-					G_WHIP_INPUTBOX 'Please enter a new DNS server address\n - 2 maximum, seperated by a space.\n - eg: 8.8.8.8 8.8.4.4'
-					(( $? )) || return_value=$G_WHIP_RETURNED_VALUE
+				G_WHIP_DEFAULT_ITEM=$current_value
+				G_WHIP_INPUTBOX 'Please enter a new DNS server address\n - 2 maximum, seperated by a space.\n - eg: 8.8.8.8 8.8.4.4' || return
+				return_value=$G_WHIP_RETURNED_VALUE
 
-				;;
+			;;
 
-				*)
+			*)
 
-					return_value=$G_WHIP_RETURNED_VALUE
+				return_value=$G_WHIP_RETURNED_VALUE
 
-				;;
+			;;
 
-			esac
-
-		fi
+		esac
 
 		# Apply new value
 		# - Ethernet
@@ -2512,44 +2499,42 @@ _EOF_
 
 		G_WHIP_MENU_ARRAY=(
 
-			'GB' 'Europe / Great Britain'
-			'US' 'United States'
-			'JP' 'Japan'
-			'CN' 'China'
-			'Manual' 'Enter a custom country code'
+			'GB' ': Europe / Great Britain'
+			'US' ': United States'
+			'JP' ': Japan'
+			'CN' ': China'
+			'Manual' ': Enter a custom country code'
 
 		)
 
 		G_WHIP_DEFAULT_ITEM=$WIFI_COUNTRYCODE
-		if G_WHIP_MENU 'Please select a country, to enable WiFi channels and power ratings allowed in your country.'; then
+		G_WHIP_MENU 'Please select a country, to enable WiFi channels and power ratings allowed in your country.' || return
 
-			if [[ $G_WHIP_RETURNED_VALUE == 'Manual' ]]; then
+		if [[ $G_WHIP_RETURNED_VALUE == 'Manual' ]]; then
 
-				G_WHIP_DEFAULT_ITEM=$WIFI_COUNTRYCODE
-				G_WHIP_INPUTBOX 'Please enter a 2 character country code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2' || return
-				[[ $G_WHIP_RETURNED_VALUE == [[:upper:]][[:upper:]] ]] || { G_WHIP_MSG "[ERROR] Invalid country code ($G_WHIP_RETURNED_VALUE). Aborting..."; return; }
+			G_WHIP_DEFAULT_ITEM=$WIFI_COUNTRYCODE
+			G_WHIP_INPUTBOX 'Please enter a 2 character country code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2' || return
+			[[ $G_WHIP_RETURNED_VALUE == [[:upper:]][[:upper:]] ]] || { G_WHIP_MSG "[ERROR] Invalid country code ($G_WHIP_RETURNED_VALUE). Aborting..."; return; }
 
-			fi
-			wifi_country_code_target=$G_WHIP_RETURNED_VALUE
+		fi
+		wifi_country_code_target=$G_WHIP_RETURNED_VALUE
 
-			/DietPi/dietpi/func/dietpi-set_hardware wificountrycode "$wifi_country_code_target"
+		/DietPi/dietpi/func/dietpi-set_hardware wificountrycode "$wifi_country_code_target"
 
-			# - Restart networking
-			Network_Restart
+		# - Restart networking
+		Network_Restart
 
-			# - Additional fallback for (older kernel?) devices that fail with wpa_supplicant.conf https://github.com/MichaIng/DietPi/issues/838
-			#	NB: Requires adapter up... hence, not in dietpi-set_hardware
-			iw reg set $wifi_country_code_target
+		# - Additional fallback for (older kernel?) devices that fail with wpa_supplicant.conf https://github.com/MichaIng/DietPi/issues/838
+		#	NB: Requires adapter up... hence, not in dietpi-set_hardware
+		iw reg set $wifi_country_code_target
 
-			# - Check if country code was successfully applied
-			#	Wait a bid until setting got applied
-			sleep 0.1
-			WIFI_COUNTRYCODE=$(iw reg get | mawk '/country/ {print $2;exit}' | tr -d ':')
-			if [[ $WIFI_COUNTRYCODE != $wifi_country_code_target ]]; then
+		# - Check if country code was successfully applied
+		#	Wait a bid until setting got applied
+		sleep 0.1
+		WIFI_COUNTRYCODE=$(iw reg get | mawk '/country/ {print $2;exit}' | tr -d ':')
+		if [[ $WIFI_COUNTRYCODE != $wifi_country_code_target ]]; then
 
-				G_WHIP_MSG "Country code ($wifi_country_code_target) could not been applied. Please check the country code and try again.\n\nIf problems persist, this may be a limitation with the driver/chipset."
-
-			fi
+			G_WHIP_MSG "Country code ($wifi_country_code_target) could not been applied. Please check the country code and try again.\n\nIf problems persist, this may be a limitation with the driver/chipset."
 
 		fi
 
@@ -2557,20 +2542,15 @@ _EOF_
 
 	Wifi_Reconnect(){
 
-		G_WHIP_YESNO 'WiFi will connect to the strongest configured SSID that is secure, with an open SSID being the last priority.\n\nSave all changes and restart networking?\n\nNB: All WiFi connections will be dropped!'
-		(( $? == 0 )) && Network_ApplyChanges
+		G_WHIP_YESNO 'WiFi will connect to the strongest configured SSID that is secure, with an open SSID being the last priority.\n
+Save all changes and restart networking?\n\nNB: All WiFi connections will be dropped!' && Network_ApplyChanges
 
 	}
 
 	Ethernet_Reconnect(){
 
-		if G_WHIP_YESNO 'Do you wish to apply settings and reconnect network now? \n\n(NOTICE) All Ethernet connections will be dropped!'; then
-
-			printf '\ec' # clear current terminal screen
-			echo 'Reconnecting Ethernet , please wait...'
-			Network_ApplyChanges
-
-		fi
+		G_WHIP_YESNO 'Do you wish to apply settings and reconnect network now?\n
+(NOTICE) All Ethernet connections will be dropped!' && Network_ApplyChanges
 
 	}
 
@@ -2622,7 +2602,7 @@ _EOF_
 		WIFI_MODE=1
 		WIFI_MODE_TARGET=$WIFI_MODE
 		command -v iwgetid &> /dev/null && WIFI_SSID_CURRENT=$(iwgetid -r)
-		[[ ! $WIFI_SSID_CURRENT ]] && WIFI_SSID_CURRENT='Disconnected / No SSID'
+		[[ $WIFI_SSID_CURRENT ]] || WIFI_SSID_CURRENT='Disconnected / No SSID'
 		WIFI_CRED_INDEX=0 # Which index of SSID/KEY etc we are editing
 
 		# Get extra WiFi stats
@@ -2630,7 +2610,7 @@ _EOF_
 		WIFI_SIGNALSTRENGTH=0
 		# - Hotspot enabled?
 		WIFI_HOTSPOT=0
-		[[ -f /usr/sbin/hostapd ]] && WIFI_HOTSPOT=1
+		[[ -f '/usr/sbin/hostapd' ]] && WIFI_HOTSPOT=1
 
 		WIFI_COUNTRYCODE='GB'
 		# - Prevent "nl80211 not found" message, when running this command with cfg80211 module disabled.
@@ -2639,7 +2619,7 @@ _EOF_
 		# Convert CIDR integer to net mask, e.g. "192.168.0.100/24" (take "24") to "255.255.255.0"
 		cidr2mask() {
 
-			local i mask=''
+			local i mask
 			local full_octets=$(( $1 / 8 ))
 			local partial_octet=$(( $1%8 ))
 
@@ -2788,12 +2768,12 @@ _EOF_
 		G_WHIP_MENU_ARRAY+=('Ethernet' ": $eth_hardware_text | [$eth_disabled_text] | $eth_connected_text")
 		G_WHIP_MENU_ARRAY+=('WiFi' ": $wlan_hardware_text | [$wlan_disabled_text] | $wlan_connected_text")
 
-		# - Onboard WiFi
-		#	RPi 3/Zero W
+		# Onboard WiFi
+		# - RPi 3/4/Zero W
 		if (( $HW_ONBOARD_WIFI )); then
 
 			local onboard_wifi_enabled=1
-			if [[ -f '/etc/modprobe.d/disable_wifi_rpi3_onboard.conf' ]]; then
+			if grep -q '^[[:blank:]]*dtoverlay=disable-wifi' /DietPi/config.txt; then
 
 				onboard_wifi_enabled=0
 				G_WHIP_MENU_ARRAY+=('Onboard WiFi' ': [Off]')
@@ -2809,11 +2789,10 @@ _EOF_
 		G_WHIP_MENU_ARRAY+=('' '●─ Additional Options ')
 
 		# IPv6
-		local ipv6_status_text='[WARNING] Not supported or disabled on kernel level!'
 		if [[ -d '/proc/sys/net/ipv6' ]]; then
 
 			local ipv6_enabled=0
-			ipv6_status_text='Off'
+			local ipv6_status_text='Off'
 			if [[ $(ip -6 a) ]]; then
 
 				ipv6_enabled=1
@@ -2826,7 +2805,7 @@ _EOF_
 
 				local ipv4_preferred=0
 				local ipv4_status_text='Off'
-				if [[ -f /etc/apt/apt.conf.d/99-dietpi-force-ipv4 ]]; then
+				if [[ -f '/etc/apt/apt.conf.d/99-dietpi-force-ipv4' ]]; then
 
 					ipv4_preferred=1
 					ipv4_status_text='On'
@@ -2854,10 +2833,9 @@ _EOF_
 					else
 
 						/DietPi/dietpi/func/dietpi-set_hardware wifimodules onboard_enable
+						G_WHIP_MSG '[ INFO ] Onboard WiFi enabled\n\nNB: A reboot is required for the change to take effect.'
 
 					fi
-
-					G_WHIP_MSG 'Onboard WiFi modules setting applied\n\nNB: A reboot is required for the changes to take effect.'
 
 				;;
 
@@ -3050,8 +3028,7 @@ Would you like to disable WiFi? \n - (NOTICE) Connections may drop!'; then
 
 				'Disable')
 
-					G_WHIP_YESNO 'Would you like to disable the Ethernet adapter?\n - (NOTICE) All Ethernet connections will be dropped.'
-					if (( $? == 0 )); then
+					if G_WHIP_YESNO 'Would you like to disable the Ethernet adapter?\n - (NOTICE) All Ethernet connections will be dropped.'; then
 
 						ETH_DISABLED=1
 						Network_ApplyChanges
@@ -3107,17 +3084,9 @@ Would you like to disable WiFi? \n - (NOTICE) Connections may drop!'; then
 	HOTSPOT_CHANNEL=''
 	HOTSPOT_KEY=''
 
-	WiFi_Monitor_Disable(){
+	WiFi_Monitor_Disable(){ systemctl disable --now dietpi-wifi-monitor; }
 
-		systemctl disable --now dietpi-wifi-monitor
-
-	}
-
-	WiFi_Monitor_Enable(){
-
-		G_RUN_CMD systemctl enable --now dietpi-wifi-monitor
-
-	}
+	WiFi_Monitor_Enable(){ G_RUN_CMD systemctl enable --now dietpi-wifi-monitor; }
 
 	# TARGETMENUID=10
 	Menu_NetworkAdapters_Wifi(){
@@ -3302,14 +3271,7 @@ Would you like to disable WiFi? \n - (NOTICE) Connections may drop!'; then
 
 				'802.11 N')
 
-					((hotspot_n_enabled++))
-
-					if (( $hotspot_n_enabled >= 2 )); then
-
-						hotspot_n_enabled=0
-
-					fi
-
+					(( $hotspot_n_enabled )) && hotspot_n_enabled=0 || hotspot_n_enabled=1
 					G_CONFIG_INJECT 'ieee80211n=' "ieee80211n=$hotspot_n_enabled" /etc/hostapd/hostapd.conf
 
 				;;
@@ -3322,16 +3284,11 @@ Would you like to disable WiFi? \n - (NOTICE) Connections may drop!'; then
 
 				'Disable')
 
-					G_WHIP_YESNO 'Would you like to disable the WiFi adapter?\n - (NOTICE) All WiFi connections will be dropped.'
-					if (( $? == 0 )); then
-
-						WIFI_DISABLED=1
-						WiFi_Monitor_Disable
-						Network_ApplyChanges
-
-						TARGETMENUID=8
-
-					fi
+					G_WHIP_YESNO 'Would you like to disable the WiFi adapter?\n - (NOTICE) All WiFi connections will be dropped.' || return
+					WIFI_DISABLED=1
+					WiFi_Monitor_Disable
+					Network_ApplyChanges
+					TARGETMENUID=8
 
 				;;
 
