v82

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -155,6 +155,8 @@
 	LINUXDASH=0
 	PIHOLE=0
 	SUBSONIC=0
+	WEAVED=0
+	WEBIOPI=0
 
 	#Linux Software
 	INSTALL_LINUX_CHOICESMADE=false
@@ -232,6 +234,8 @@
 		echo -e "LINUXDASH $LINUXDASH" >> "$FILEPATH_INSTALLED_FILE"
 		echo -e "PIHOLE $PIHOLE" >> "$FILEPATH_INSTALLED_FILE"
 		echo -e "SUBSONIC $SUBSONIC" >> "$FILEPATH_INSTALLED_FILE"
+		echo -e "WEAVED $WEAVED" >> "$FILEPATH_INSTALLED_FILE"
+		echo -e "WEBIOPI $WEBIOPI" >> "$FILEPATH_INSTALLED_FILE"
 
 		echo -e "#Additional Linux Software" >> "$FILEPATH_INSTALLED_FILE"
 		echo -e "VIMFULL $VIMFULL" >> "$FILEPATH_INSTALLED_FILE"
@@ -300,6 +304,8 @@
 		LINUXDASH=$(cat "$FILEPATH_INSTALLED_FILE" | grep 'LINUXDASH ' | awk '{print $2}')
 		PIHOLE=$(cat "$FILEPATH_INSTALLED_FILE" | grep 'PIHOLE ' | awk '{print $2}')
 		SUBSONIC=$(cat "$FILEPATH_INSTALLED_FILE" | grep 'SUBSONIC ' | awk '{print $2}')
+		WEAVED=$(cat "$FILEPATH_INSTALLED_FILE" | grep 'WEAVED ' | awk '{print $2}')
+		WEBIOPI=$(cat "$FILEPATH_INSTALLED_FILE" | grep 'WEBIOPI ' | awk '{print $2}')
 
 		#Linux
 		VIMFULL=$(cat "$FILEPATH_INSTALLED_FILE" | grep 'VIMFULL ' | awk '{print $2}')
@@ -1014,6 +1020,67 @@
 			fi
 
 		fi
+		
+		#WEAVED
+		if (( $WEAVED == 1 )); then
+			INSTALL_DESCRIPTION='Weaved (Access your device over the internet)'
+			Banner_Installing
+
+			INSTALL_URL_ADDRESS='https://github.com/weaved/installer/raw/master/binaries/weaved-nixinstaller_1.2.13.bin'
+			/DietPi/dietpi/func/check_connection 5 2 "$INSTALL_URL_ADDRESS"
+			if (( $? == 0 )); then
+				
+				#Install WEAVED
+				wget "$INSTALL_URL_ADDRESS" -O weaved_setup.bin
+				chmod +x weaved_setup.bin
+				
+				##Dont run this, let the user run it for "1st time setup"
+				#./weaved_setup.bin
+				
+			else
+				Info_NoConnection_NoInstall
+				WEAVED=0
+			fi
+
+		fi
+
+		#WEBIOPI
+		if (( $WEBIOPI == 1 )); then
+			INSTALL_DESCRIPTION='WebIOPi (Control RPi GPIO from a web interface)'
+			Banner_Installing
+
+			INSTALL_URL_ADDRESS='http://sourceforge.net/projects/webiopi/files/WebIOPi-0.7.1.tar.gz/download'
+			/DietPi/dietpi/func/check_connection 5 2 "$INSTALL_URL_ADDRESS"
+			if (( $? == 0 )); then
+				
+				#Python dev, pre-reqs
+				apt-get install python-dev python-setuptools --no-install-recommends -y
+
+				#Install WEBIOPI
+				wget "$INSTALL_URL_ADDRESS" -O package.tar
+				tar xvzf package.tar
+				rm package.tar
+				
+				cd WebIOPi*
+
+				#Automate Weaved prompt
+				sed -i '/read response/c\response="n"' setup.sh
+				
+				#Run setup script
+				./setup.sh skip-apt
+				clear
+
+				cd ..
+
+				#Cleanup
+				rm -R WebIOPi*
+
+			else
+				Info_NoConnection_NoInstall
+				WEBIOPI=0
+			fi
+
+		fi
 
 	}
 
@@ -1048,6 +1115,11 @@
 			apt-get install smbclient cifs-utils -y --no-install-recommends
 			
 			SMBCLIENT=2
+		fi
+
+		#DietPi software that requires RPI GPIO
+		if (( $WEBIOPI == 1 )); then
+			RPIGPIO=1
 		fi
 		
 		if (( $RPIGPIO == 1 )); then
@@ -1249,6 +1321,10 @@
 		if (( $RASPCONTROL == 1 )); then
 			SUDO_AUTH=1
 		elif (( $PIHOLE == 1 )); then
+			SUDO_AUTH=1
+		elif (( $WEAVED == 1 )); then
+			SUDO_AUTH=1
+		elif (( $WEBIOPI == 1 )); then
 			SUDO_AUTH=1
 		fi
 
@@ -2080,17 +2156,34 @@ _EOF_
 			#Optimize memory limit (total / 6)
 			local subsonic_memory_max=$(( $(free -m -o | grep 'Mem:' | awk '{print $2}') / 6 ))
 			cat << _EOF_ > /etc/default/subsonic
+SUBSONIC_USER=root
 SUBSONIC_ARGS="--quiet --pidfile=/run/subsonic.pid --max-memory=$subsonic_memory_max --default-music-folder=$TARGET_DIRECTORY/$FOLDER_MUSIC --default-podcast-folder=$TARGET_DIRECTORY/$FOLDER_MUSIC --default-playlist-folder=$TARGET_DIRECTORY/$FOLDER_MUSIC"
 _EOF_
 
 			#Grab our test media for user
 			Download_Test_Media
+			
+			#Enable Dedicated PWM pll (HQ Audio)
+			sed -i '/avoid_pwm_pll=/c\avoid_pwm_pll=0' /DietPi/config.txt
 
 			SUBSONIC=2
 
 		fi
 
+		#WEBIOPI
+		if (( $WEBIOPI == 1 )); then
+			#auto start
+			update-rc.d webiopi defaults
 
+			WEBIOPI=2
+		fi
+
+		#WEAVED
+		if (( $WEAVED == 1 )); then
+
+			WEAVED=2
+		fi
+		
 	}
 
 	Install_Apply_GPU_Settings(){
@@ -2924,6 +3017,25 @@ _EOF_
 				SUBSONIC=0
 			fi
 		fi
+
+		local webiopi_w="off"
+		if (( $WEBIOPI > 0 )); then
+			webiopi_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $WEBIOPI == 1 )); then
+				WEBIOPI=0
+			fi
+		fi
+
+		local weaved_w="off"
+		if (( $WEAVED > 0 )); then
+			weaved_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $WEAVED == 1 )); then
+				WEAVED=0
+			fi
+		fi
+
 		#-----------------------------------------------------------------------------
 		WHIP_TITLE='DietPi Optimized Software Selection'
 
@@ -2935,7 +3047,6 @@ _EOF_
 			"" "────Media Systems───────────────────────────" "off" \
 			"Kodi" "Your very own media centre/player." $kodi_w \
 			"HiFi" "Web interface music / radio player." $hifi_w \
-			"SubSonic" "Web interface media streaming server." $subsonic_w \
 			"" "────BitTorrent──────────────────────────────" "off" \
 			"Transmission" "BitTorrent server with web interface." $transmission_w \
 			"" "────Cloud / Backups─────────────────────────" "off" \
@@ -2947,8 +3058,8 @@ _EOF_
 			"LinuxDash" "Web interface system stats." $linuxdash_w \
 			"" "────Webserver Stacks───────────────────────" "off" \
 			"LAMP" "Webserver: Apache2 / MySql  / Php." $webserver_lamp_w \
-			"LEMP" "Webserver: Nginx   / MySql  / Php." $webserver_lemp_w \
 			"LASP" "Webserver: Apache2 / SQLite / Php." $webserver_lasp_w \
+			"LEMP" "Webserver: Nginx   / MySql  / Php." $webserver_lemp_w \
 			"LESP" "Webserver: Nginx   / SQLite / Php." $webserver_lesp_w \
 			"phpMyAdmin" "Webserver: Optional MySql admin tools." $webserver_phpmyadmin_w \
 			"" "────DNS Servers────────────────────────────" "off" \
@@ -2972,7 +3083,6 @@ _EOF_
 			"Kodi" "Your very own media centre / player." $kodi_w \
 			"HiFi" "Web interface music / radio player." $hifi_w \
 			"MiniDLNA" "Media streaming server (DLNA, UPnP)." $minidlna_w \
-			"SubSonic" "Web interface media streaming server." $subsonic_w \
 			"" "────BitTorrent──────────────────────────────" "off" \
 			"Transmission" "BitTorrent server with web interface." $transmission_w \
 			"Deluge" "BitTorrent server with web interface." $deluge_w \
@@ -2981,19 +3091,22 @@ _EOF_
 			"OpenTyrian" "Gaming: A classic retro game, addictive." $opentyrian_w \
 			"" "────Cloud / Backups─────────────────────────" "off" \
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
+			"Weaved" "Access your device over the internet." $weaved_w \
 			"" "────Forums / Blogs─────────────────────────" "off" \
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 			"" "────Camera / Surveillance───────────────────" "off" \
 			"DietPiCam" "RPi Cam Control / Web Interface Surveillance." $dietpicam_w \
 			"" "────Home Automation─────────────────────────" "off" \
 			"Grasshopper" "Web App to control Bticino MyHome." $grasshopper_w \
+			"" "────RPi-GPIO Related Software───────────────" "off" \
+			"WebIOPi" "Web interface to control RPi GPIO." $webiopi_w \
 			"" "────System Management──────────────────────" "off" \
 			"Raspcontrol" "Web interface system stats." $raspcontrol_w \
 			"LinuxDash" "Web interface system stats." $linuxdash_w \
 			"" "────Webserver Stacks───────────────────────" "off" \
 			"LAMP" "Webserver: Apache2 / MySql  / Php." $webserver_lamp_w \
-			"LEMP" "Webserver: Nginx   / MySql  / Php." $webserver_lemp_w \
 			"LASP" "Webserver: Apache2 / SQLite / Php." $webserver_lasp_w \
+			"LEMP" "Webserver: Nginx   / MySql  / Php." $webserver_lemp_w \
 			"LESP" "Webserver: Nginx   / SQLite / Php." $webserver_lesp_w \
 			"phpMyAdmin" "Webserver: Optional MySql admin tools." $webserver_phpmyadmin_w \
 			"" "────DNS Servers────────────────────────────" "off" \
@@ -3007,10 +3120,25 @@ _EOF_
 			"" "────Website URLs───────────────────────────" "off" \
 			"NoIp" "URL website address for your device." $noipdyndns_w 2>/tmp/dietpi-software_results
 		fi
+		
+			##DISABLED
+			#"SubSonic" "Web interface media streaming server." $subsonic_w \
 
 		while read choice
 		do
 			case $choice in
+			WebIOPi)
+				if (( $WEBIOPI == 0 )); then
+					WEBIOPI=1
+					INSTALL_DIETPI_CHOICESMADE=true
+				fi
+			;;
+			Weaved)
+				if (( $WEAVED == 0 )); then
+					WEAVED=1
+					INSTALL_DIETPI_CHOICESMADE=true
+				fi
+			;;
 			SubSonic)
 				if (( $SUBSONIC == 0 )); then
 					SUBSONIC=1
