Added conventional commandline options This has replaced the old commandline options (1/-1, and a path), with a new, more traditional set of options: -b [directory] to backup -r [directory] to restore -q to stop WHIP dialogues wherever possible, so that dietpi-backup can be safely automated -h to give help with the aforementioned flags

diff --git a/dietpi/dietpi-backup b/dietpi/dietpi-backup
--- a/dietpi/dietpi-backup
+++ b/dietpi/dietpi-backup
@@ -32,14 +32,10 @@
 
 	G_EXIT_CUSTOM(){
 
-		# Cleaup left over tmp files
+		# Cleanup left over tmp files
 		[[ -f $FP_FILTER_INCLUDE_EXCLUDE ]] && rm $FP_FILTER_INCLUDE_EXCLUDE
 
 	}
-
-	#Grab Input
-	INPUT=0
-	disable_error=1 G_CHECK_VALIDINT "$1" && INPUT=$1
 
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Backup System
@@ -161,8 +157,11 @@ _EOF_
 
 			#Error: Unable to create target folder.
 			if [[ ! -d $FP_TARGET_BACKUP ]]; then
-
-				G_WHIP_MSG "$RSYNC_MODE_TEXT Failed:\n\nUnable to create $FP_TARGET_BACKUP"
+				if [[ QUIET_MODE -eq 1 ]]; then
+				    G_WHIP_MSG "$RSYNC_MODE_TEXT Failed:\n\nUnable to create $FP_TARGET_BACKUP"
+                else
+				    echo "$RSYNC_MODE_TEXT Failed:Unable to create $FP_TARGET_BACKUP" >&2
+                fi
 
 			#Error: Rsync is already running
 			elif pgrep 'rsync' &> /dev/null; then
@@ -217,13 +216,20 @@ _EOF_
 					EXIT_CODE=$?
 					G_DIETPI-NOTIFY -1 $EXIT_CODE "$G_PROGRAM_NAME: $RSYNC_MODE_TEXT"
 					if (( $EXIT_CODE == 0 )); then
-
 						echo -e "$RSYNC_MODE_TEXT Completed    : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
-						G_WHIP_MSG "$RSYNC_MODE_TEXT Completed:\n - $FP_TARGET_BACKUP"
-
+						
+						if [[ QUIET_MODE -eq 1 ]]; then
+						    G_WHIP_MSG "$RSYNC_MODE_TEXT Completed:\n - $FP_TARGET_BACKUP"
+                        else
+                            echo "$RSYNC_MODE_TEXT Completed: $FP_TARGET_BACKUP"
+                        fi
 					else
 
-						G_WHIP_MSG "$RSYNC_MODE_TEXT Failed:\n - $FP_TARGET_BACKUP\n\nYou will given an option to view the logfile on the next screen. Please check it for information and/or errors."
+						if [[ QUIET_MODE -eq 1 ]]; then
+						    G_WHIP_MSG "$RSYNC_MODE_TEXT Failed:\n - $FP_TARGET_BACKUP\n\nYou will given an option to view the logfile on the next screen. Please check it for information and/or errors."
+						else
+						    echo "$RSYNC_MODE_TEXT Failed: $FP_TARGET_BACKUP. Check the log" >&2
+						fi
 
 					fi
 
@@ -232,7 +238,7 @@ _EOF_
 
 				done
 
-				log=1 G_WHIP_VIEWFILE $FP_LOG
+				[[ QUIET_MODE -eq 1 ]] && log=1 G_WHIP_VIEWFILE $FP_LOG
 
 				#return to main menu
 				TARGETMENUID=0
@@ -265,7 +271,7 @@ _EOF_
 				G_DIETPI-NOTIFY 2 "No Backup was found in $FP_TARGET_BACKUP"
 				G_DIETPI-NOTIFY 1 "$RSYNC_MODE_TEXT Failed.\n"
 
-				G_WHIP_MSG "$RSYNC_MODE_TEXT Failed:\n\n$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME does not exist\n\nHave you created a backup?"
+				[[ QUIET_MODE -eq 1 ]] && G_WHIP_MSG "$RSYNC_MODE_TEXT Failed:\n\n$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME does not exist\n\nHave you created a backup?"
 
 			#Error: Rsync is already running
 			elif pgrep 'rsync' &> /dev/null; then
@@ -287,15 +293,24 @@ _EOF_
 				if (( $EXIT_CODE == 0 )); then
 
 					echo -e "$RSYNC_MODE_TEXT Completed    : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
-					G_WHIP_MSG "$RSYNC_MODE_TEXT Completed:\n - $FP_TARGET_BACKUP\n\nNB: A Reboot is highly recommended."
+					
+					if [[ QUIET_MODE -eq 1 ]]; then
+					    G_WHIP_MSG "$RSYNC_MODE_TEXT Completed:\n - $FP_TARGET_BACKUP\n\nNB: A reboot is highly recommended."
+                    else
+                        echo "$RSYNC_MODE_TEXT Completed: $FP_TARGET_BACKUP NB: A reboot is highly recommended."
+                    fi
 
 				else
 
-					G_WHIP_MSG "$RSYNC_MODE_TEXT Failed:\n - $FP_TARGET_BACKUP\n\nYou will given an option to view the logfile on the next screen. Please check it for information and/or errors."
+					if [[ QUIET_MODE -eq 1 ]]; then
+					    G_WHIP_MSG "$RSYNC_MODE_TEXT Failed:\n - $FP_TARGET_BACKUP\n\nYou will given an option to view the logfile on the next screen. Please check it for information and/or errors."
+                    else
+                        echo "$RSYNC_MODE_TEXT Failed: $FP_TARGET_BACKUP. Check the log." >&2
+                    fi
 
 				fi
 
-				log=1 G_WHIP_VIEWFILE $FP_LOG
+				[[ QUIET_MODE -eq 1 ]] && log=1 G_WHIP_VIEWFILE $FP_LOG
 
 				# - done
 				TARGETMENUID=0
@@ -592,7 +607,7 @@ _EOF_
 
 		G_DIETPI-NOTIFY 1 "Filesystem not supported in $FP_TARGET_BACKUP"
 
-		G_WHIP_MSG "Error:\n\n$FP_TARGET_BACKUP Has a filesystem of: $TARGET_FILESYSTEM_TYPE, and is not supported.\n\nThe filesystem must be EXT2/3/4 for symlink compatibility."
+		[[ QUIET_MODE -eq 1 ]] && G_WHIP_MSG "Error:\n\n$FP_TARGET_BACKUP Has a filesystem of: $TARGET_FILESYSTEM_TYPE, and is not supported.\n\nThe filesystem must be EXT2/3/4 for symlink compatibility."
 
 	}
 
@@ -600,7 +615,7 @@ _EOF_
 
 		G_DIETPI-NOTIFY 1 "Target directory is not inside /mnt ($FP_TARGET_BACKUP)"
 
-		G_WHIP_MSG "Directory not supported:\n- $FP_TARGET_BACKUP\n\nThe location must be inside the /mnt/* directory.\n - eg: /mnt/dietpi-backup"
+		[[ QUIET_MODE -eq 1 ]] && G_WHIP_MSG "Directory not supported:\n- $FP_TARGET_BACKUP\n\nThe location must be inside the /mnt/* directory.\n - eg: /mnt/dietpi-backup"
 
 	}
 
@@ -608,7 +623,7 @@ _EOF_
 
 		G_DIETPI-NOTIFY 1 "Target directory can not be contained within DietPi user data location ($FP_TARGET_BACKUP)"
 
-		G_WHIP_MSG "Directory not supported:\n- $FP_TARGET_BACKUP\n\nTarget directory can not be contained within DietPi user data location ($G_FP_DIETPI_USERDATA)"
+		[[ QUIET_MODE -eq 1 ]] && G_WHIP_MSG "Directory not supported:\n- $FP_TARGET_BACKUP\n\nTarget directory can not be contained within DietPi user data location ($G_FP_DIETPI_USERDATA)"
 
 	}
 
@@ -618,7 +633,7 @@ _EOF_
 
 		echo -e "$RSYNC_MODE_TEXT failed: $(date +"%d-%m-%Y_%H%M"). Rsync is already running." >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
 
-		G_WHIP_MSG "$RSYNC_MODE_TEXT Error:\n\nA $RSYNC_MODE_TEXT could not be started as rsync is already running."
+		[[ QUIET_MODE -eq 1 ]] && G_WHIP_MSG "$RSYNC_MODE_TEXT Error:\n\nA $RSYNC_MODE_TEXT could not be started as rsync is already running."
 
 	}
 
@@ -630,11 +645,8 @@ _EOF_
 
 	#Read settings file
 	Read_Settings_File
-
-	# $2 Optional directory input.
-	[[ $2 ]] && FP_TARGET_BACKUP=$2
-
-	#Create user inc/exc templates
+	
+		#Create user inc/exc templates
 	# - Add users filter list
 	if [[ ! -f $FP_USER_FILTER_INCLUDE_EXCLUDE_BACKUP ]]; then
 
@@ -654,42 +666,98 @@ _EOF_
 _EOF_
 
 	fi
+	
+    # Check flags ------------------------------------------------------------------------
+    MUTEX_FLAG=0 # to ensure -b and -r aren't both given
+    QUIET_MODE=1 # ensure no user interaction is required if set to 0
+    # Quiet mode will fail to suppress certain dialogues if they aren't created by dietpi-backup
+    # Known instances:
+    # G_CHECK_USERDATA - upon fail
+    # G_CHECK_FREESPACE - upon not having enough space TODO: Go back to line 205 and try coercing it around to working with QUIET_MODE
+    
+	while getopts ":hb:r:q" opt; do
+        case $opt in
+            q) # Suppresses as many WHIP dialogues as possible, replacing with echos where appropriate
+                QUIET_MODE=0
+                ;;
+            b) # mutually exclusive to restore
+                if [[ MUTEX_FLAG -eq 1 ]]; then
+                    echo "Can't use -b and -r flags together! Exiting" >&2
+                    exit 1
+                fi
+                
+                echo "Backup to $OPTARG"
+        
+                MUTEX_FLAG=1
+                
+                FP_TARGET_BACKUP=$OPTARG # Run_Backup validates the path
+                Run_Backup
+                exit "$EXIT_CODE"
+                ;; 
+            r) # mutually exclusive to backup
+                echo "Restore from $OPTARG"
+                
+                if [[ MUTEX_FLAG -eq 1 ]]; then
+                    echo "Can't use -b and -r flags together! Exiting" >&2
+                    exit 1
+                fi
+                
+                MUTEX_FLAG=1
+                
+                FP_TARGET_BACKUP=$OPTARG # Run_Backup validates the path
+                Run_Restore
+                exit "$EXIT_CODE"
+                ;;
+            \?)
+                echo "Invalid option $OPTARG. Use -h for help" >&2
+                exit 1
+                ;;
+            :)
+                echo "Required argument for $OPTARG not found. Use -h for help" >&2
+                exit 1
+                ;;
+            h|*)
+                cat << _EOF_
 
-	#-----------------------------------------------------------------------------
-	#Run Backup
-	if (( $INPUT == 1 )); then
+Help for dietpi-backup
+Run with no options to access the dietpi-backup GUI
 
-		Run_Backup
+Options:
+    -h                  Display this help and exit
+    -r [directory]      Restore from directory
+    -b [directory]      Backup to directory
+    -q                  Suppress user interaction (some errors will still trigger a prompt)
+_EOF_
+                exit 2
+                ;;
+        esac
+    done
+    
+    QUIET_MODE=1 # If a backup/restore hasn't been given as an argument, ignore -q flag if set
+    
+	# Check flags ------------------------------------------------------------------------
 
-	#Run Restore
-	elif (( $INPUT == -1 )); then
+	# Run menu if flags haven't otherwise started a backup
 
-		Run_Restore
+    while (( $TARGETMENUID > -1 )); do
 
-	#-----------------------------------------------------------------------------
-	#Run menu
-	else
+        printf '\ec' # clear current terminal screen
 
-		while (( $TARGETMENUID > -1 )); do
+        if (( $TARGETMENUID == 1 )); then
 
-			printf '\ec' # clear current terminal screen
+            Menu_Set_Directory
 
-			if (( $TARGETMENUID == 1 )); then
+        else
 
-				Menu_Set_Directory
+            Menu_Main
 
-			else
+        fi
 
-				Menu_Main
+    done
 
-			fi
+    #Save settings
+    Write_Settings_File
 
-		done
-
-		#Save settings
-		Write_Settings_File
-
-	fi
 	#-----------------------------------------------------------------------------------
 	exit $EXIT_CODE
 	#-----------------------------------------------------------------------------------
