v6.20
+ DietPi-Software | WireGuard: Allow choice between server and client setup. In case of client setup, skip all config steps, instead inform user to follow VPN provider instructions. Add VPN (auto)start info as well, in case the VPN provider does not include it.

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -10058,61 +10058,85 @@ _EOF_
 		software_id=172
 		if (( ${aSOFTWARE_INSTALL_STATE[$software_id]} == 1 )); then
 
-			# User inputs: Ask user for servers public IP/domain and desired WireGuard server port
-			local invalid_text=''
-			local domain=$(hostname)
-			while :
+			# Try to enable module, if it fails, a reboot is required
+			local module_active=0
+			modprobe wireguard 2> /dev/null && module_active=1
+
+			# Server/Client choice
+			G_WHIP_MENU_ARRAY=(
+
+				'Server' ': Use this machine as VPN server and allow clients to connect to it.'
+				'Client' ': Use this machine as VPN client, e.g. to connect to a VPN service provider.'
+
+			)
+
+			local choice_required=''
+			while:
 			do
 
-				G_WHIP_DEFAULT_ITEM="$domain"
-				G_WHIP_INPUTBOX "${invalid_text}Please enter your servers public IP/domain for WireGuard client access:"
-				if (( $? == 0 )) && [[ $G_WHIP_RETURNED_VALUE ]]; then
-
-					domain="${G_WHIP_RETURNED_VALUE#http*://}"
-					break
-
-				else
-
-					invalid_text='[ERROR] No valid entry found. Please retry...\n\n'
-
-				fi
+				G_WHIP_MENU "${choice_required}Please choose, if this machine should be set up as VPN server or client:" && break
+				choice_required='[ERROR] A choice is required to finish the WireGuard install.\n\n'
 
 			done
-			invalid_text=''
-			local port=51820
-			while :
-			do
 
-				G_WHIP_DEFAULT_ITEM=$port
-				G_WHIP_INPUTBOX "${invalid_text}Please enter the network port, that should be used to access your WireGuard server:\n
+			# Server choice
+			if [[ $G_WHIP_RETURNED_VALUE == 'Server' ]]; then
+
+				# - Public IP/domain and desired WireGuard server port
+				local invalid_text=''
+				local domain=$(hostname)
+				while :
+				do
+
+					G_WHIP_DEFAULT_ITEM="$domain"
+					G_WHIP_INPUTBOX "${invalid_text}Please enter your servers public IP/domain for WireGuard client access:"
+					if (( $? == 0 )) && [[ $G_WHIP_RETURNED_VALUE ]]; then
+
+						domain="${G_WHIP_RETURNED_VALUE#http*://}"
+						break
+
+					else
+
+						invalid_text='[ERROR] No valid entry found. Please retry...\n\n'
+
+					fi
+
+				done
+				invalid_text=''
+				local port=51820
+				while :
+				do
+
+					G_WHIP_DEFAULT_ITEM=$port
+					G_WHIP_INPUTBOX "${invalid_text}Please enter the network port, that should be used to access your WireGuard server:\n
 NB: This port needs to be forwarded by your router and/or opened in your firewall settings. Default value is: 51820"
-				if (( $? == 0 )) && disable_error=1 G_CHECK_VALIDINT "$G_WHIP_RETURNED_VALUE" 0; then
+					if (( $? == 0 )) && disable_error=1 G_CHECK_VALIDINT "$G_WHIP_RETURNED_VALUE" 0; then
 
-					port=$G_WHIP_RETURNED_VALUE
-					break
+						port=$G_WHIP_RETURNED_VALUE
+						break
 
-				else
+					else
 
-					invalid_text='[ERROR] No valid entry found, value needs to be a sequence of integers. Please retry...\n\n'
+						invalid_text='[ERROR] No valid entry found, value needs to be a sequence of integers. Please retry...\n\n'
 
-				fi
+					fi
 
-			done
+				done
 
-			# Create everything inside WireGuard config dir
-			cd /etc/wireguard
+				# - Create everything inside WireGuard config dir
+				cd /etc/wireguard
 
-			# For securiy reasons set umask to 077
-			umask 077
+				# - For securiy reasons set umask to 077
+				umask 077
 
-			# Create server and client keys
-			[[ -f server_private.key ]] || wg genkey > server_private.key
-			[[ -f server_public.key ]] || wg pubkey < server_private.key > server_public.key
-			[[ -f client_private.key ]] || wg genkey > client_private.key
-			[[ -f client_public.key ]] || wg pubkey < client_private.key > client_public.key
+				# - Create server and client keys
+				[[ -f server_private.key ]] || wg genkey > server_private.key
+				[[ -f server_public.key ]] || wg pubkey < server_private.key > server_public.key
+				[[ -f client_private.key ]] || wg genkey > client_private.key
+				[[ -f client_public.key ]] || wg pubkey < client_private.key > client_public.key
 
-			# Server config
-			[[ -f wg0.conf ]] || cat << _EOF_ > wg0.conf
+				# - Server config
+				[[ -f wg0.conf ]] || cat << _EOF_ > wg0.conf
 [Interface]
 Address = 10.8.0.1/24
 PrivateKey = $(<server_private.key)
@@ -10126,11 +10150,11 @@ PublicKey = $(<client_public.key)
 AllowedIPs = 10.8.0.0/24
 _EOF_
 
-			# Server local network IP
-			local server_ip=$(sed -n 4p /DietPi/dietpi/.network)
+				# - Server local network IP
+				local server_ip=$(sed -n 4p /DietPi/dietpi/.network)
 
-			# Client config
-			[[ -f wg0-client.conf ]] || cat << _EOF_ > wg0-client.conf
+				# - Client config
+				[[ -f wg0-client.conf ]] || cat << _EOF_ > wg0-client.conf
 [Interface]
 # The address must be unique for each client, use "10.8.0.3/24" for the second client and so on.
 Address = 10.8.0.2/24
@@ -10153,27 +10177,43 @@ Endpoint = $domain:51820
 #PersistentKeepalive = 25
 _EOF_
 
-			# Try to enable module, if it fails, a reboot is required
-			local module_active=1
-			modprobe wireguard 2> /dev/null || { module_active=0; [[ $DISABLE_REBOOT == 1 ]] && G_WHIP_MSG '[[ INFO ]] WireGuard\n\nWireGuard has been successfully installed, but a reboot is required, before it can be started.'; }
+				# - Enable IPv4 + IPv6 forwarding
+				(( $module_active )) && sysctl net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1 net.ipv6.conf.default.forwarding=1
+				#	persistent
+				echo -e 'net.ipv4.ip_forward=1\nnet.ipv6.conf.all.forwarding=1\nnet.ipv6.conf.default.forwarding=1' > /etc/sysctl.d/dietpi-wireguard.conf
 
-			# Enable IPv4 + IPv6 forwarding
-			(( $module_active )) && sysctl net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1 net.ipv6.conf.default.forwarding=1
-			# - persistent
-			echo -e 'net.ipv4.ip_forward=1\nnet.ipv6.conf.all.forwarding=1\nnet.ipv6.conf.default.forwarding=1' > /etc/sysctl.d/dietpi-wireguard.conf
+				# - Start WireGuard interface via systemd unit
+				(( $module_active )) && systemctl start wg-quick@wg0
+				#	persistent
+				systemctl enable wg-quick@wg0
 
-			# Start WireGuard interface via systemd unit
-			(( $module_active )) && systemctl start wg-quick@wg0
-			# - persistent
-			systemctl enable wg-quick@wg0
+				# - Set umask back to default 022
+				umask 022
 
-			# Set umask back to default 022
-			umask 022
+				# - Navigate back to DietPi-Software working dir
+				cd /tmp/$G_PROGRAM_NAME
 
-			# Navigate back to DietPi-Software working dir
-			cd /tmp/$G_PROGRAM_NAME
+			# Client choice
+			elif [[ $G_WHIP_RETURNED_VALUE == 'Client' ]]; then
 
-			unset domain port invalid_text server_ip module_active
+				G_WHIP_MSG '[ INFO ] WireGuard client setup has been chosen\n
+Please follow the instructions of your VPN provider to configure WireGuard.\n
+If no WireGuard (auto)start is included, but you require it, please do the following:
+1. Check for the created config file/interface name:
+	ls -Al /etc/wireguard/
+   It has a ".conf" file ending, lets assume "wg0-client.conf".
+2. To start the VPN interface, run:
+	systemctl start wg0-client
+3. To autostart the VPN interface on boot, run:
+	systemctl enable wg0-client
+4. To disable autostart again, run:
+	systemctl disable wg0-client'
+
+			fi
+
+			(( $module_active )) || { [[ $DISABLE_REBOOT == 1 ]] && G_WHIP_MSG '[[ INFO ]] WireGuard install finished\n\nNB: WireGuard has been successfully installed, but a reboot is required, before it can be started.'; }
+
+			unset module_active choice_required domain port invalid_text server_ip
 
 		fi
 
