v50

diff --git a/dietpi/dietpi-external_drive_setup b/dietpi/dietpi-external_drive_setup
--- a/dietpi/dietpi-external_drive_setup
+++ b/dietpi/dietpi-external_drive_setup
@@ -1,101 +1,106 @@
 #!/bin/bash
-# ////////////////////////////////////
-# DietPi External drive mount
-#
-#////////////////////////////////////
-# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
-#
-#////////////////////////////////////
-#
-# Info: - Formats and Mounts /dev/sda1 /mnt/usb_1
-#////////////////////////////////////
+{
+	# ////////////////////////////////////
+	# DietPi External drive mount
+	#
+	#////////////////////////////////////
+	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
+	#
+	#////////////////////////////////////
+	#
+	# Info: - Formats and Mounts /dev/sda1 /mnt/usb_1
+	#////////////////////////////////////
 
-usb_hdd_connected=0
-usb_hdd_filesystem="None"
-CheckDriveConnected(){
+	usb_hdd_connected=0
+	usb_hdd_filesystem="None"
+	CheckDriveConnected(){
 
-    usb_hdd_connected=$(blkid | grep -ci '/dev/sda1')
-	usb_hdd_filesystem=$(blkid | grep '/dev/sda1' | awk '{ print $3 }' | tr -d '"TYPE=')
-}
+		usb_hdd_connected=$(blkid | grep -ci '/dev/sda1')
+		usb_hdd_filesystem=$(blkid | grep '/dev/sda1' | awk '{ print $3 }' | tr -d '"TYPE=')
+	}
 
-#/////////////////////////////////////////////////////////////////////////////////////
-# Main Loop
-#/////////////////////////////////////////////////////////////////////////////////////
+	#/////////////////////////////////////////////////////////////////////////////////////
+	# Main Loop
+	#/////////////////////////////////////////////////////////////////////////////////////
 
-    clear
-    # Stop Services
-    /boot/dietpi/dietpi-services stop &> /dev/null
+	clear
+	# Stop Services
+	/boot/dietpi/dietpi-services stop &> /dev/null
 
-    #Unmount all connected drives
-    umount /dev/sd[a-z][1-9]
+	#Unmount all connected drives
+	umount /dev/sd[a-z][1-9]
 
-    # Wait for drive to be connected
-    clear
-    echo -e " --------------------------------\n D I E T - P I \n External Drive Setup \n --------------------------------"
-    echo -e " Please Insert a USB Drive into your Raspberry Pi"
-    echo -e " \n Waiting for Device to be connected. Press CTRL+C to cancel \n If canceled, you can restart the DietPi Installation by running /boot/dietpi/dietpi-software"
+	# Wait for drive to be connected
+	clear
+	echo -e " --------------------------------\n D I E T - P I \n External Drive Setup \n --------------------------------"
+	echo -e " Please Insert a USB Drive into your Raspberry Pi"
+	echo -e " \n Waiting for Device to be connected. Press CTRL+C to cancel \n If canceled, you can restart the DietPi Installation by running /boot/dietpi/dietpi-software"
 
-    while true; do
-        if [ -d /sys/block/sda ]; then
-            break
-        else
-            sleep 1
-        fi
-    done
+	while true; do
+		if [ -d /sys/block/sda ]; then
+			break
+		else
+			sleep 1
+		fi
+	done
 
-    #Check if filesystem already exists and is mountable
+	#Check if filesystem already exists and is mountable
 	mount -a
-    CheckDriveConnected
+	CheckDriveConnected
 	#override connected status with a filesystem df -h check
 	usb_hdd_connected=$(df -h | grep -ci -m1 '/dev/sda1')
-    if (( $usb_hdd_connected == 1 )); then
-        clear
-        echo -e " --------------------------------\n D I E T - P I \n External Drive Setup \n --------------------------------"
-        echo -e " An Existing $usb_hdd_filesystem Drive has Been Found \n"
-        df /dev/sda1 -h
-        echo -e ""
+	if (( $usb_hdd_connected == 1 )); then
+		clear
+		echo -e " --------------------------------\n D I E T - P I \n External Drive Setup \n --------------------------------"
+		echo -e " An Existing $usb_hdd_filesystem Drive has Been Found \n"
+		df /dev/sda1 -h
+		echo -e ""
 		
 		if [ "$usb_hdd_filesystem" = "ntfs" ]; then
-		    echo -e " (WARNING): \n - NTFS is not recommended as it requires alot more cpu processing \n - EXT4 will maximise the filesystem performance of your Pi \n \n If you have data (eg: movies) on this drive you want to keep, press enter \n "
+			echo -e " (WARNING): \n - NTFS is not recommended as it requires alot more cpu processing \n - EXT4 will maximise the filesystem performance of your Pi \n \n If you have data (eg: movies) on this drive you want to keep, press enter \n "
 			read -r -p " Would you like to format this drive to EXT4? [y/N] " response
 		else
 			read -r -p " Would you like to format this drive? [y/N] " response
 		fi
 		
-        case $response in
-            [yY][eE][sS]|[yY])
-                # Continue script
-                ;;
-                # Terminate Script
-            *)  exit
-                ;;
-        esac
-    fi
+		case $response in
+			[yY][eE][sS]|[yY])
+				# Continue script
+				;;
+				# Terminate Script
+			*)  exit
+				;;
+		esac
+	fi
 	
-    #Confirm user wants to wipe this drive
-    clear
-    echo -e " --------------------------------\n D I E T - P I \n External Drive Setup \n --------------------------------"
-    echo -e " Drive ready to be formatted to EXT4"
-    echo -e " \n WARNING: This will delete all data on the USB drive \n \n"
-    read -r -p " Do you wish to Format this drive? [y/N] " response
-    case $response in
-        [yY][eE][sS]|[yY])
- 			#Unmount all connected drives
+	#Confirm user wants to wipe this drive
+	clear
+	echo -e " --------------------------------\n D I E T - P I \n External Drive Setup \n --------------------------------"
+	echo -e " Drive ready to be formatted to EXT4"
+	echo -e " \n WARNING: This will delete all data on the USB drive \n \n"
+	read -r -p " Do you wish to Format this drive? [y/N] " response
+	case $response in
+		[yY][eE][sS]|[yY])
+			#Unmount all connected drives
 			umount /dev/sd[a-z][1-9]
-           # Create New partition on /dev/sda
-            echo -e "o\nn\np\n1\n\n\nw" | fdisk /dev/sda && mkfs.ext4 /dev/sda1 || true && resize2fs /dev/sda1 || true && mount -a || true && chown -R root:root /mnt/usb_1 || true && df -h
-            ;;
-        *) #do nothing
-            ;;
-    esac
+		   # Create New partition on /dev/sda
+			echo -e "o\nn\np\n1\n\n\nw" | fdisk /dev/sda && mkfs.ext4 /dev/sda1 || true && resize2fs /dev/sda1 || true && mount -a || true && chown -R root:root /mnt/usb_1 || true && df -h
+			;;
+		*) #do nothing
+			;;
+	esac
 
-    #Test the new drive
-    clear
+	#Test the new drive
+	clear
 	CheckDriveConnected
 	if (( $usb_hdd_connected == 1 )); then
-        echo -e " --------------------------------\n D I E T - P I \n External Drive Setup \n Completed \n -----------------------------\n You can access the drive with cd /mnt/usb_1\n"
-    else
-        echo -e " --------------------------------\n D I E T - P I \n External Drive Setup \n FAILED \n --------------------------------"
-    fi
+		echo -e " --------------------------------\n D I E T - P I \n External Drive Setup \n Completed \n -----------------------------\n You can access the drive with cd /mnt/usb_1\n"
+	else
+		echo -e " --------------------------------\n D I E T - P I \n External Drive Setup \n FAILED \n --------------------------------"
+	fi
 
-    sleep 2
+	sleep 2
+
+	#Run whole script in a function. Loads into memory, allows for online file patching.
+	exit
+}
diff --git a/dietpi/dietpi-update b/dietpi/dietpi-update
--- a/dietpi/dietpi-update
+++ b/dietpi/dietpi-update
@@ -1,171 +1,207 @@
 #!/bin/bash
-#////////////////////////////////////
-# DietPi Updater
-#
-#////////////////////////////////////
-# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
-#
-#////////////////////////////////////
-#
-# Info:
-# - Updates DietPi from Git
-#////////////////////////////////////
+{
+	#////////////////////////////////////
+	# DietPi Updater
+	#
+	#////////////////////////////////////
+	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
+	#
+	#////////////////////////////////////
+	#
+	# Info:
+	# - Updates DietPi from Git
+	# - Uses patch_file for online pactching
+	#
+	# Usage:
+	# - dietpi-update 1 = forced update
+	#////////////////////////////////////
+	INPUT=$1
 
-#/////////////////////////////////////////////////////////////////////////////////////
-#Obtain Hardware Details
-#/////////////////////////////////////////////////////////////////////////////////////
-HW_MODEL=$(sed -n 1p /boot/dietpi/.hw_model)
-HW_MODEL_DESCRIPTION=$(sed -n 2p /boot/dietpi/.hw_model)
-DISTRO=$(sed -n 3p /boot/dietpi/.hw_model)
+	#/////////////////////////////////////////////////////////////////////////////////////
+	#Obtain Hardware Details
+	#/////////////////////////////////////////////////////////////////////////////////////
+	HW_MODEL=$(sed -n 1p /boot/dietpi/.hw_model)
+	HW_MODEL_DESCRIPTION=$(sed -n 2p /boot/dietpi/.hw_model)
+	DISTRO=$(sed -n 3p /boot/dietpi/.hw_model)
 
-#/////////////////////////////////////////////////////////////////////////////////////
-#VERSION CODES
-#/////////////////////////////////////////////////////////////////////////////////////
-DIETPIUPDATE_VERSION_CURRENT=2 # Version of dietpi-update / set server_version line two to value++ and obsolete previous dietpi-update scripts
-DIETPIUPDATE_VERSION_REQUIRED=0
+	#/////////////////////////////////////////////////////////////////////////////////////
+	#VERSION CODES
+	#/////////////////////////////////////////////////////////////////////////////////////
+	DIETPIUPDATE_VERSION_CURRENT=3 # Version of dietpi-update / set server_version line two to value++ and obsolete previous dietpi-update scripts
+	DIETPIUPDATE_VERSION_REQUIRED=0
 
-VERSION_CURRENT=0
-VERSION_SERVER=0
+	VERSION_CURRENT=0
+	VERSION_SERVER=0
 
-Get_Current_Version(){
-	VERSION_CURRENT=$(cat /boot/dietpi/.version)
-}
+	Get_Current_Version(){
+		VERSION_CURRENT=$(cat /boot/dietpi/.version)
+	}
 
-SERVER_ONLINE=false
-RUN_UPDATE=false
+	SERVER_ONLINE=false
+	RUN_UPDATE=false
 
-#/////////////////////////////////////////////////////////////////////////////////////
-#Obtain Install Stage Index
-#/////////////////////////////////////////////////////////////////////////////////////
-# see /boot/dietpi/boot for info
-DIETPI_INSTALL_STAGE=$(cat /boot/dietpi/.install_stage)
+	#/////////////////////////////////////////////////////////////////////////////////////
+	#Obtain Install Stage Index
+	#/////////////////////////////////////////////////////////////////////////////////////
+	# see /boot/dietpi/boot for info
+	DIETPI_INSTALL_STAGE=$(cat /boot/dietpi/.install_stage)
 
-#/////////////////////////////////////////////////////////////////////////////////////
-# MENUS
-#/////////////////////////////////////////////////////////////////////////////////////
-WHIP_BACKTITLE='DietPi - Update'
-WHIP_TITLE='DietPi - Update'
-WHIP_QUESTION='DietPi - Update'
-CHOICE=0
-OPTION=0
-TARGETMENUID=0
+	#/////////////////////////////////////////////////////////////////////////////////////
+	# MENUS
+	#/////////////////////////////////////////////////////////////////////////////////////
+	WHIP_BACKTITLE='DietPi - Update'
+	WHIP_TITLE='DietPi - Update'
+	WHIP_QUESTION='DietPi - Update'
+	CHOICE=0
+	OPTION=0
+	TARGETMENUID=0
 
-#TARGETMENUID=0
-Menu_Update(){
+	#TARGETMENUID=0
+	Menu_Update(){
 
-    WHIP_TITLE='---------- DietPi - Update ----------'
-	whiptail --title "$WHIP_TITLE" --yesno " DietPi Version: $VERSION_CURRENT \n Latest Version: $VERSION_SERVER \n \n Would you like to update DietPi?" --defaultno --yes-button "Update" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 14 60
-	CHOICE=$?
-	#Confirm action
-	if [ "$CHOICE" = 0 ]; then
-		RUN_UPDATE=true
-	fi
-}
+		WHIP_TITLE='---------- DietPi - Update ----------'
+		whiptail --title "$WHIP_TITLE" --yesno " DietPi Version: $VERSION_CURRENT \n Latest Version: $VERSION_SERVER \n \n Update available, would you like to update DietPi?" --yes-button "Update" --no-button "Abort" --backtitle "$WHIP_BACKTITLE" 12 60
+		CHOICE=$?
+		#Confirm action
+		if [ "$CHOICE" = 0 ]; then
+			RUN_UPDATE=true
+		fi
+	}
 
-Run_DietPi_Update(){
+	Run_DietPi_Update(){
 
-	#Remove Files from git that are not to be updated
-	rm ~/Dietpi/dietpi/.* &> /dev/null
-	rm ~/Dietpi/dietpi/dietpi-update &> /dev/null	
-
-	#Copy to Fat16/32 partition
-	cp -Rfu ~/Dietpi/dietpi /boot
-	
-	#Run Patch file
-	local bRunPatch=true
-	while "$bRunPatch"; do	
-		bRunPatch=false;
-		Get_Current_Version
+		#Remove any previous cloned files
+		rm -R ~/DietPi-master &> /dev/null
 		
-		clear
-		/boot/dietpi/dietpi-banner 0
-		echo -e "DietPi-Update is running the update process, please wait.... \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
-				
-		if (( $VERSION_CURRENT < $VERSION_SERVER )); then
+		#git clone Zip method (no longer need to install GIT)
+		wget https://github.com/Fourdee/DietPi/archive/master.zip
+		unzip master.zip
+		rm master.zip
+		
+		#Remove Files from git that are not to be updated
+		rm ~/DietPi-master/dietpi/.* &> /dev/null
+		#rm ~/DietPi-master/dietpi/dietpi-update &> /dev/null	
+
+		#Copy to Fat16/32 partition
+		cp -Rf ~/DietPi-master/dietpi /boot
+		
+		#Run Patch file
+		while (( $VERSION_CURRENT < $VERSION_SERVER )); do	
+			
+			clear
+			/boot/dietpi/dietpi-banner 0
+			
+			echo -e "DietPi-Update is running the update process, please wait.... \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+					
 			/boot/dietpi/patch_file "$VERSION_CURRENT" "$VERSION_SERVER"
-			((VERSION_CURRENT++))
 			
 			#Update Local Version ID
+			((VERSION_CURRENT++))
 			echo -e "$VERSION_CURRENT" > /boot/dietpi/.version
-			
-			bRunPatch=true
-		fi
-	done
-	
-	#Remove Patch file
-	rm /boot/dietpi/patch_file
+			Get_Current_Version
+				
+		done
+		
+		#Remove Patch files
+		rm /boot/dietpi/patch_file &> /dev/null
+		rm /boot/dietpi/server_version &> /dev/null
+		
+		#Remove temp files
+		rm -R ~/DietPi-master &> /dev/null
 
-	RUN_UPDATE=false
-	
-}
+		RUN_UPDATE=false
+		
+	}
 
-#/////////////////////////////////////////////////////////////////////////////////////
-# Main Loop
-#/////////////////////////////////////////////////////////////////////////////////////
-/boot/dietpi/dietpi-banner 0
-echo -e " DietPi-Update: \n Please wait.................."
+	#/////////////////////////////////////////////////////////////////////////////////////
+	# Main Loop
+	#/////////////////////////////////////////////////////////////////////////////////////
+	/boot/dietpi/dietpi-banner 0
+	echo -e " DietPi-Update: \n Checking for DietPi updates, Please wait..."
 
-#Get Local Version
-Get_Current_Version
+	#Get Local Version
+	Get_Current_Version
 
-#Check Server is online
-wget -q --spider https://github.com
-if [ $? -eq 0 ]; then
-	SERVER_ONLINE=true
-	
-	#Check git is installed
-	if [ ! -f /usr/bin/git ]; then
-		clear
-		echo -e "Installing Git"
-		apt-get update
-		apt-get upgrade -y
-		apt-get install git -y --no-install-recommends	
+	#Check Server is online
+	wget -q --spider https://github.com
+	if [ $? -eq 0 ]; then
+		SERVER_ONLINE=true
+
+		#Work from home directory
+		cd ~/
+		
+		#Get server version file
+		wget https://raw.githubusercontent.com/Fourdee/DietPi/master/dietpi/server_version
+		
+		#Get server Version info
+		VERSION_SERVER=$(sed -n 1p ~/server_version)
+		DIETPIUPDATE_VERSION_REQUIRED=$(sed -n 2p ~/server_version)
+		
+		#Remove temp file
+		rm server_version
 	fi
 
-	#Remove any previous cloned files
-	rm -R ~/Dietpi &> /dev/null
-	#Get update
-	cd ~/
-	git clone https://github.com/Fourdee/Dietpi
+	if [ "$SERVER_ONLINE" = false ]; then
+		whiptail --title "Error - Server Offline" --msgbox "http://github.com is either offline, or, unable to connect \n \n No updates applied." 12 60
+	elif (( $DIETPIUPDATE_VERSION_CURRENT < $DIETPIUPDATE_VERSION_REQUIRED )); then 
+		#Cannot update, Image required
+		whiptail --title "Unable to update image" --msgbox " Your version of DietPi is now obsolete and cannot be updated. \n Please download the latest DietPi image:\n http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=6 \n\n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n " 18 70
 
-	#Get server Version
-	VERSION_SERVER=$(sed -n 1p ~/Dietpi/dietpi/server_version)
-	DIETPIUPDATE_VERSION_REQUIRED=$(sed -n 2p ~/Dietpi/dietpi/server_version)
-fi
+		clear
+		/boot/dietpi/dietpi-banner 0
+		echo -e " Your version of DietPi is now obsolete and cannot be updated. \n Please download the latest DietPi image:\n http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=6 \n\n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
 
-if [ "$SERVER_ONLINE" = false ]; then
-	whiptail --title "Error - Server Offline" --msgbox "http://github.com is either offline, or, unable to connect \n \n No updates applied." 12 60
-elif (( $DIETPIUPDATE_VERSION_CURRENT < $DIETPIUPDATE_VERSION_REQUIRED )); then 
-	#Cannot update, Image required
-	/boot/dietpi/dietpi-banner 0
-	echo -e " Your version of DietPi is now obsolete and cannot be updated. \n Please download the latest DietPi image:\n http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=6 \n\n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
-elif (( $VERSION_CURRENT < $VERSION_SERVER )); then 
-	#Ask for update
-	Menu_Update
-else
-	#No Updates
-	/boot/dietpi/dietpi-banner 0
-	echo -e " DietPi Update - No updates required \n Your DietPi installation is upto date \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
-fi
-
-#Run Update
-if [ "$RUN_UPDATE" = true ]; then
-	#Stop Services
-	/boot/dietpi/dietpi-services stop
+	elif (( $VERSION_CURRENT < $VERSION_SERVER )); then 
 	
-	#Update Apt
-	apt-get update
-	
-	#Run update and patcher
-	clear
-	Run_DietPi_Update
-	
-	#Done
-	clear
-	/boot/dietpi/dietpi-banner 0
-	echo -e "DietPi Update Completed. \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
-	echo -e "Please reboot your system, using the command reboot"
-fi
+		#Forced update
+		if (( $INPUT == 1 )); then
+			clear
+			/boot/dietpi/dietpi-banner 0
+			
+			echo -e "Updates have been found and are being applied, please wait.... \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+			sleep 1
+			RUN_UPDATE=true
+		
+		#Ask for update
+		else
+			#Ask for update
+			Menu_Update
+		fi
+	else
+		#No Updates
+		/boot/dietpi/dietpi-banner 0
+		echo -e " DietPi Update - No updates required \n Your DietPi installation is upto date \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+	fi
 
-#Clear files
-rm -R ~/Dietpi &> /dev/null
+	#Run Update
+	if [ "$RUN_UPDATE" = true ]; then
+	
+		#Stop Services
+		/boot/dietpi/dietpi-services stop
+		
+		#Update Apt
+		apt-get update
+		
+		#Run update and patcher
+		clear
+		Run_DietPi_Update
+		
+		#.update file stage (only used on 1st run of dietpi-software to check/apply updates, 0 tells dietpi-software to reboot)
+		echo 0 > /boot/dietpi/.update_stage		
+		
+		#Done
+		clear
+		/boot/dietpi/dietpi-banner 0
+		
+		echo -e "DietPi Update Completed. \n \n - Current Version : $VERSION_CURRENT \n - Server Version  : $VERSION_SERVER \n "
+		echo -e "Please reboot your system, using the command reboot"
+	fi
+
+	#Desktop Run, exit key prompt
+	if (( $(ps aux | grep -ci -m1 '[l]xpanel') == 1 )); then
+		read -p "Press any key to exit DietPi-Update..."
+	fi
+
+	#Run whole script in a function. Loads into memory, allows for online file patching.
+	exit
+}
