v150
+ DietPi-Drive_Manager | Added support for setting Read Only/Read Write
filesystems: https://github.com/Fourdee/DietPi/issues/229

diff --git a/dietpi/dietpi-drive_manager b/dietpi/dietpi-drive_manager
--- a/dietpi/dietpi-drive_manager
+++ b/dietpi/dietpi-drive_manager
@@ -16,6 +16,7 @@
 	# 	  = Drive Manager
 	#	1 = Selectadrive! Provides a list of available drive mount locations, with value on selection saved to: /tmp/dietpi-drive_manager_selmnt
 	#	2 = Returns exit 1 if low on freespace
+	#	3 = Returns exit 1 if rootfs is currently RO (NB: simple check via mount cmd, does not init full drive manager vars, for quicker loading/processing)
 	#////////////////////////////////////
 
 	#Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
@@ -37,6 +38,7 @@
 	HW_NAME=$(sed -n 2p /DietPi/dietpi/.hw_model)
 	if (( $HW_MODEL == 20 )); then
 		echo -e "\nThis script does not support the Virtual Machine image.\n"
+		Destroy
 		exit
 	fi
 
@@ -61,7 +63,7 @@
 
 	FP_ROOTFS_SOURCE=0
 
-	#EXTERNAL
+	#Drives
 	MAX_DRIVES=5
 	FORMAT_GPT=1 # default GPT: https://github.com/Fourdee/DietPi/issues/531. 0=MBR
 	FORMAT_FILESYSTEM_TYPE=0 #0=ext4 1=ntfs 2=fat32 3=hfs+ 4=btrfs 5=f2fs
@@ -70,6 +72,8 @@
 	FORMAT_PREVIOUS_MOUNT_SOURCE=0 #Used to obtain previous mount source fp, before a format, for rootfs transfer
 
 	INDEX_DRIVE_BEING_EDITED=0
+
+	ROOTFS_RW_CHECKED=0
 
 	aDRIVE_UUID=()
 	aDRIVE_PART_UUID=()
@@ -85,6 +89,8 @@
 	aDRIVE_ISFILESYSTEM=()
 	aDRIVE_ISMOUNTED=()
 	aDRIVE_ISUUIDMOUNT=()
+	aDRIVE_ISREADONLY_FSTAB=()
+	aDRIVE_ISREADONLY_CURRENTLY=()
 
 	INIT_FSTAB_SLOTS_ENABLED=0
 
@@ -93,169 +99,257 @@
 	Init_Drives_and_Refresh(){
 
 		#---------------------------------------------------------------
-		/DietPi/dietpi/func/dietpi-notify 2 "Detecting drives, please wait..."
+		local init=1
 
-		#Copy FSTAB to ram, faster exe
-		cp /etc/fstab "$FP_TEMP_FSTAB"
-
-		#Get list of all attached drives:
-		MAX_DRIVES=$(blkid -o device | wc -l)
-		local fp_temp='/tmp/.dietpi-drive_manager_devlist'
-		blkid -o device > $fp_temp
-		readarray -t aDRIVE_MOUNT_SOURCE < $fp_temp
-
-		#	UUID
-		blkid -s UUID -o value > $fp_temp
-		readarray -t aDRIVE_UUID < $fp_temp
-
-		#	PARTUUID
-		blkid -s PARTUUID -o value > $fp_temp
-		readarray -t aDRIVE_PART_UUID < $fp_temp
-
-		#	TYPE
-		blkid -s TYPE -o value > $fp_temp
-		readarray -t aDRIVE_FSTYPE < $fp_temp
-
-		# - Check fstab for existing entries and mount locations
-		local mount_index=1
-		for ((i=0; i<$MAX_DRIVES; i++))
+		while (( $init ))
 		do
 
-			aDRIVE_ISAVAILABLE[$i]=0
-			aDRIVE_ISUUIDMOUNT[$i]=0
-			aDRIVE_MOUNT_TARGET[$i]='NULL'
+			init=0
 
-			# - check /dev/sdX
-			aDRIVE_MOUNT_TARGET[$i]=$(cat "$FP_TEMP_FSTAB" | grep -m1 "${aDRIVE_MOUNT_SOURCE[$i]}[[:space:]]" | awk '{print $2}')
-			if [ -n "${aDRIVE_MOUNT_TARGET[$i]}" ]; then
+			/DietPi/dietpi/func/dietpi-notify 2 "Detecting drives, please wait..."
 
-				aDRIVE_ISAVAILABLE[$i]=1
+			#Copy FSTAB to ram, faster exe
+			cp /etc/fstab "$FP_TEMP_FSTAB"
 
-				#DEBUG
-				/DietPi/dietpi/func/dietpi-notify 2 "Detected non-UUID mount: ${aDRIVE_MOUNT_SOURCE[$i]}"
+			#Get list of all attached drives:
+			MAX_DRIVES=$(blkid -o device | wc -l)
+			local fp_temp='/tmp/.dietpi-drive_manager_devlist'
+			blkid -o device > $fp_temp
+			readarray -t aDRIVE_MOUNT_SOURCE < $fp_temp
 
-			# - check UUID
-			else
+			#	UUID
+			blkid -s UUID -o value > $fp_temp
+			readarray -t aDRIVE_UUID < $fp_temp
 
-				aDRIVE_MOUNT_TARGET[$i]=$(cat "$FP_TEMP_FSTAB" | grep -m1 "UUID=${aDRIVE_UUID[$i]}[[:space:]]" | awk '{print $2}')
+			#	PARTUUID
+			blkid -s PARTUUID -o value > $fp_temp
+			readarray -t aDRIVE_PART_UUID < $fp_temp
+
+			#	TYPE
+			blkid -s TYPE -o value > $fp_temp
+			readarray -t aDRIVE_FSTYPE < $fp_temp
+
+			# - Check fstab for existing entries and mount locations
+			local mount_index=1
+			for ((i=0; i<$MAX_DRIVES; i++))
+			do
+
+				aDRIVE_ISAVAILABLE[$i]=0
+				aDRIVE_ISUUIDMOUNT[$i]=0
+				aDRIVE_MOUNT_TARGET[$i]='NULL'
+
+				# - check /dev/sdX
+				aDRIVE_MOUNT_TARGET[$i]=$(grep -m1 "${aDRIVE_MOUNT_SOURCE[$i]}[[:space:]]" "$FP_TEMP_FSTAB" | awk '{print $2}')
 				if [ -n "${aDRIVE_MOUNT_TARGET[$i]}" ]; then
+
+					aDRIVE_ISAVAILABLE[$i]=1
+
+					#DEBUG
+					/DietPi/dietpi/func/dietpi-notify 2 "Detected non-UUID mount: ${aDRIVE_MOUNT_SOURCE[$i]}"
+
+				# - check UUID
+				else
+
+					aDRIVE_MOUNT_TARGET[$i]=$(grep -m1 "UUID=${aDRIVE_UUID[$i]}[[:space:]]" "$FP_TEMP_FSTAB" | awk '{print $2}')
+					if [ -n "${aDRIVE_MOUNT_TARGET[$i]}" ]; then
+
+						aDRIVE_ISAVAILABLE[$i]=1
+						aDRIVE_ISUUIDMOUNT[$i]=1
+
+						#DEBUG
+						/DietPi/dietpi/func/dietpi-notify 2 "Detected UUID mount: ${aDRIVE_MOUNT_SOURCE[$i]}"
+
+					fi
+
+				fi
+
+				#	Drive mount does not exist
+				if (( ! ${aDRIVE_ISAVAILABLE[$i]} )) &&
+					[ -n "${aDRIVE_UUID[$i]}" ]; then #Ignore master partition tables / drives with no UUID
+
+					#	create one
+					local fp_target="/mnt/${aDRIVE_UUID[$i]}"
+
+					#DEBUG
+					/DietPi/dietpi/func/dietpi-notify 2 "Creating UUID fstab entry: ${aDRIVE_MOUNT_SOURCE[$i]}"
+
+					#	remove any previous/disabled entries for drive
+					sed -i "\@^${aDRIVE_MOUNT_SOURCE[$i]}[[:space:]]@d" "$FP_TEMP_FSTAB"
+					sed -i "\@^UUID=${aDRIVE_UUID[$i]}[[:space:]]@d" "$FP_TEMP_FSTAB"
+
+					echo -e "UUID=${aDRIVE_UUID[$i]}       $fp_target      auto     defaults,noatime,nofail,x-systemd.automount  0 0" >> "$FP_TEMP_FSTAB"
+
+					aDRIVE_MOUNT_TARGET[$i]="$fp_target"
 
 					aDRIVE_ISAVAILABLE[$i]=1
 					aDRIVE_ISUUIDMOUNT[$i]=1
 
-					#DEBUG
-					/DietPi/dietpi/func/dietpi-notify 2 "Detected UUID mount: ${aDRIVE_MOUNT_SOURCE[$i]}"
+				fi
+
+				#create mount folders
+				if (( ${aDRIVE_ISAVAILABLE[$i]} )) &&
+					[ ! -d "${aDRIVE_MOUNT_TARGET[$i]}" ]; then
+
+					/DietPi/dietpi/func/dietpi-notify 2 "Creating mount folder for ${aDRIVE_MOUNT_TARGET[$i]}"
+					mkdir -p "${aDRIVE_MOUNT_TARGET[$i]}"
 
 				fi
 
+				#debug
+				#echo -e "${aDRIVE_MOUNT_SOURCE[$i]} | ${aDRIVE_UUID[$i]} | ${aDRIVE_MOUNT_TARGET[$i]}"
+
+			done
+
+			cp "$FP_TEMP_FSTAB" /etc/fstab
+			systemctl daemon-reload
+
+			rm "$FP_TEMP_FSTAB"
+
+			mount -a
+
+			#---------------------------------------------------------------
+
+			/DietPi/dietpi/func/dietpi-notify 2 "Processing drive information, please wait..."
+
+			#ROOTFS location
+			FP_ROOTFS_SOURCE=$(df -P | grep -m1 '[[:space:]]/$' | awk '{print $1}')
+
+			#Get data on mounted drives
+			for ((i=0; i<$MAX_DRIVES; i++))
+			do
+				# - init
+				aDRIVE_FSTYPE[$i]='No filesystem'
+				aDRIVE_SIZE_TOTAL[$i]='NULL'
+				aDRIVE_SIZE_USED[$i]='NULL'
+				aDRIVE_SIZE_FREE[$i]='NULL'
+				aDRIVE_SIZE_PERCENTUSED[$i]='NULL'
+
+				aDRIVE_ISMOUNTED[$i]=0
+				aDRIVE_ISFILESYSTEM[$i]=0
+				aDRIVE_ISREADONLY_FSTAB[$i]=0
+				aDRIVE_ISREADONLY_CURRENTLY[$i]=0
+
+				cmd_scrape_string=$(blkid "${aDRIVE_MOUNT_SOURCE[$i]}" -s TYPE -o value)
+				if [ -n "$cmd_scrape_string" ]; then
+
+					aDRIVE_ISFILESYSTEM[$i]=1
+					aDRIVE_FSTYPE[$i]="$cmd_scrape_string"
+
+				fi
+
+				#mounted drive, pull size data
+				cmd_scrape_string=$(df -Ph | grep -m1 "${aDRIVE_MOUNT_TARGET[$i]}$" | awk '{print $2}')
+				if [ -n "$cmd_scrape_string" ]; then
+
+					aDRIVE_SIZE_TOTAL[$i]="$cmd_scrape_string"
+					aDRIVE_ISMOUNTED[$i]=1
+
+				fi
+
+				cmd_scrape_string=$(df -Ph | grep -m1 "${aDRIVE_MOUNT_TARGET[$i]}$" | awk '{print $3}')
+				if [ -n "$cmd_scrape_string" ]; then
+
+					aDRIVE_SIZE_USED[$i]="$cmd_scrape_string"
+
+				fi
+
+				cmd_scrape_string=$(df -Ph | grep -m1 "${aDRIVE_MOUNT_TARGET[$i]}$" | awk '{print $4}')
+				if [ -n "$cmd_scrape_string" ]; then
+
+					aDRIVE_SIZE_FREE[$i]="$cmd_scrape_string"
+
+				fi
+
+				cmd_scrape_string=$(df -Ph | grep -m1 "${aDRIVE_MOUNT_TARGET[$i]}$" | awk '{print $5}')
+				if [ -n "$cmd_scrape_string" ]; then
+
+					aDRIVE_SIZE_PERCENTUSED[$i]="$cmd_scrape_string"
+
+				fi
+
+				cmd_scrape_string=$(grep -m1 "[[:space:]]${aDRIVE_MOUNT_TARGET[$i]}[[:space:]]" /etc/fstab | grep -m1 ',ro,')
+				if [ -n "$cmd_scrape_string" ]; then
+
+					aDRIVE_ISREADONLY_FSTAB[$i]=1
+
+				fi
+
+				cmd_scrape_string=$(grep -m1 "^${aDRIVE_MOUNT_SOURCE[$i]}" /proc/mounts | grep '[[:space:]]ro,')
+				if [ -n "$cmd_scrape_string" ]; then
+
+					aDRIVE_ISREADONLY_CURRENTLY[$i]=1
+
+				fi
+
+			done
+
+			#Check for RO on rootfs and enable RW before this script can run
+			if (( ! $ROOTFS_RW_CHECKED )); then
+
+				ROOTFS_RW_CHECKED=1
+
+				for ((i=0; i<$MAX_DRIVES; i++))
+				do
+
+					if [ "${aDRIVE_MOUNT_TARGET[$i]}" = "/" ] &&
+						(( ${aDRIVE_ISREADONLY_CURRENTLY[$i]} )); then
+
+						INDEX_DRIVE_BEING_EDITED=$i
+
+						/DietPi/dietpi/func/dietpi-notify 1 "RootFS is currently set to R/O. $PROGRAM_NAME requires R/W access."
+
+						whiptail --title "RootFS is R/O" --yesno "RootFS is currently set to 'Read Only'. DietPi-Drive_Manager requires 'Read Write' access to function.\n\nWould you like to renable 'Read Write' access on RootFS?" --backtitle "$PROGRAM_NAME" --defaultno 14 75
+						if (( $? == 0 )); then
+
+							Toggle_WriteMode
+							/DietPi/dietpi/func/dietpi-notify 0 "RootFS R/W now enabled."
+
+							#	reinit
+							init=1
+
+						else
+
+							/DietPi/dietpi/dietpi-services start
+							/DietPi/dietpi/func/dietpi-notify 1 "Please run 'dietpi-drive_manager' again to enable RootFS R/W."
+							Destroy
+							exit
+
+						fi
+
+
+					fi
+
+				done
+
+
 			fi
 
-			#	Drive mount does not exist
-			if (( ! ${aDRIVE_ISAVAILABLE[$i]} )) &&
-				[ -n "${aDRIVE_UUID[$i]}" ]; then #Ignore master partition tables / drives with no UUID
-
-				#	create one
-				local fp_target="/mnt/${aDRIVE_UUID[$i]}"
-
-				#DEBUG
-				/DietPi/dietpi/func/dietpi-notify 2 "Creating UUID fstab entry: ${aDRIVE_MOUNT_SOURCE[$i]}"
-
-				#	remove any previous/disabled entries for drive
-				sed -i "\@^${aDRIVE_MOUNT_SOURCE[$i]}[[:space:]]@d" "$FP_TEMP_FSTAB"
-				sed -i "\@^UUID=${aDRIVE_UUID[$i]}[[:space:]]@d" "$FP_TEMP_FSTAB"
-
-				echo -e "UUID=${aDRIVE_UUID[$i]}       $fp_target      auto     defaults,noatime,nofail,x-systemd.automount  0 0" >> "$FP_TEMP_FSTAB"
-
-				aDRIVE_MOUNT_TARGET[$i]="$fp_target"
-
-				aDRIVE_ISAVAILABLE[$i]=1
-				aDRIVE_ISUUIDMOUNT[$i]=1
-
-			fi
-
-			#create mount folders
-			if (( ${aDRIVE_ISAVAILABLE[$i]} )) &&
-				[ ! -d "${aDRIVE_MOUNT_TARGET[$i]}" ]; then
-
-				/DietPi/dietpi/func/dietpi-notify 2 "Creating mount folder for ${aDRIVE_MOUNT_TARGET[$i]}"
-				mkdir -p "${aDRIVE_MOUNT_TARGET[$i]}"
-
-			fi
-
-			#debug
-			#echo -e "${aDRIVE_MOUNT_SOURCE[$i]} | ${aDRIVE_UUID[$i]} | ${aDRIVE_MOUNT_TARGET[$i]}"
+			#User data location
+			FP_USERDATA_CURRENT=$(/DietPi/dietpi/func/dietpi-set_userdata return_source)
 
 		done
 
-		cp "$FP_TEMP_FSTAB" /etc/fstab
-		systemctl daemon-reload
+	}
 
-		rm "$FP_TEMP_FSTAB"
+	Destroy(){
 
-		mount -a
+		#Delete []
+		unset aDRIVE_MOUNT_SOURCE
+		unset aDRIVE_MOUNT_TARGET
+		unset aDRIVE_FSTYPE
+		unset aDRIVE_SIZE_TOTAL
+		unset aDRIVE_SIZE_USED
+		unset aDRIVE_SIZE_PERCENTUSED
+		unset aDRIVE_SIZE_FREE
+		unset aDRIVE_PART_UUID
+		unset aDRIVE_UUID
 
-		#---------------------------------------------------------------
-
-		/DietPi/dietpi/func/dietpi-notify 2 "Processing drive information, please wait..."
-
-		#ROOTFS location
-		FP_ROOTFS_SOURCE=$(df -P | grep -m1 '[[:space:]]/$' | awk '{print $1}')
-
-		#Get data on mounted drives
-		for ((i=0; i<$MAX_DRIVES; i++))
-		do
-			# - init
-			aDRIVE_FSTYPE[$i]='No filesystem'
-			aDRIVE_SIZE_TOTAL[$i]='NULL'
-			aDRIVE_SIZE_USED[$i]='NULL'
-			aDRIVE_SIZE_FREE[$i]='NULL'
-			aDRIVE_SIZE_PERCENTUSED[$i]='NULL'
-
-			aDRIVE_ISMOUNTED[$i]=0
-			aDRIVE_ISFILESYSTEM[$i]=0
-
-			cmd_scrape_string=$(blkid "${aDRIVE_MOUNT_SOURCE[$i]}" -s TYPE -o value)
-			if [ -n "$cmd_scrape_string" ]; then
-
-				aDRIVE_ISFILESYSTEM[$i]=1
-				aDRIVE_FSTYPE[$i]="$cmd_scrape_string"
-
-			fi
-
-			#mounted drive, pull size data
-			cmd_scrape_string=$(df -Ph | grep -m1 "${aDRIVE_MOUNT_TARGET[$i]}$" | awk '{print $2}')
-			if [ -n "$cmd_scrape_string" ]; then
-
-				aDRIVE_SIZE_TOTAL[$i]="$cmd_scrape_string"
-				aDRIVE_ISMOUNTED[$i]=1
-
-			fi
-
-			cmd_scrape_string=$(df -Ph | grep -m1 "${aDRIVE_MOUNT_TARGET[$i]}$" | awk '{print $3}')
-			if [ -n "$cmd_scrape_string" ]; then
-
-				aDRIVE_SIZE_USED[$i]="$cmd_scrape_string"
-
-			fi
-
-			cmd_scrape_string=$(df -Ph | grep -m1 "${aDRIVE_MOUNT_TARGET[$i]}$" | awk '{print $4}')
-			if [ -n "$cmd_scrape_string" ]; then
-
-				aDRIVE_SIZE_FREE[$i]="$cmd_scrape_string"
-
-			fi
-
-			cmd_scrape_string=$(df -Ph | grep -m1 "${aDRIVE_MOUNT_TARGET[$i]}$" | awk '{print $5}')
-			if [ -n "$cmd_scrape_string" ]; then
-
-				aDRIVE_SIZE_PERCENTUSED[$i]="$cmd_scrape_string"
-
-			fi
-
-		done
-
-		#User data location
-		FP_USERDATA_CURRENT=$(/DietPi/dietpi/func/dietpi-set_userdata return_source)
+		unset aDRIVE_ISMOUNTED
+		unset aDRIVE_ISFILESYSTEM
+		unset aDRIVE_ISAVAILABLE
+		unset aDRIVE_ISUUIDMOUNT
+		unset aDRIVE_ISREADONLY_FSTAB
+		unset aDRIVE_ISREADONLY_CURRENTLY
 
 	}
 
@@ -415,7 +509,7 @@
 			sed -i "s#$rootfs_current#root=PARTUUID=${aDRIVE_PART_UUID[$INDEX_DRIVE_BEING_EDITED]}#g" /boot/cmdline.txt
 
 			#	Add root delay
-			if (( ! $(cat /boot/cmdline.txt | grep -ci -m1 '[[:space:]]rootdelay=') )); then
+			if (( ! $(grep -ci -m1 '[[:space:]]rootdelay=' /boot/cmdline.txt) )); then
 
 				sed -i "s#console=tty1#console=tty1 rootdelay=10#g" /boot/cmdline.txt
 
@@ -487,6 +581,64 @@
 		#Still waiting for Freespace 3 :(
 
 	}
+
+	RootFS_RW_Check(){
+
+		# local fp_test_file="$HOME/dietpi-drive_manager_rw_test"
+		# echo 0 > "$fp_test_file"
+		# if (( $? != 0 )); then
+
+			# /DietPi/dietpi/func/dietpi-notify 1 "RootFS is currently set to R/O."
+			# EXIT_CODE=1
+
+		# fi
+
+		# rm "$fp_test_file" &> /dev/null
+
+		if (( $(mount | grep -m1 '[[:space:]]/[[:space:]]' | grep -ci -m1 '(ro,') )); then
+
+			/DietPi/dietpi/func/dietpi-notify 1 "RootFS is currently set to R/O."
+			/DietPi/dietpi/func/dietpi-notify 2 "DietPi requires RootFS R/W access. Please run 'dietpi-drive_manager' to re-enable."
+			EXIT_CODE=1
+
+		fi
+
+	}
+
+	Toggle_WriteMode(){
+
+		local line_number=$(grep -m1 -n "[[:space:]]${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]}[[:space:]]" /etc/fstab |cut -f1 -d:)
+		local exit_status=0
+		local message_result=0
+		if (( ${aDRIVE_ISREADONLY_FSTAB[$INDEX_DRIVE_BEING_EDITED]} || ${aDRIVE_ISREADONLY_CURRENTLY[$INDEX_DRIVE_BEING_EDITED]} )); then
+
+			message_result=$(mount -v -o rw,remount "${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}" 2>&1)
+			exit_status=$?
+
+			#	Apply this only if no ,ro, exists?
+			sed -i "${line_number}s/[[:space:]]defaults,ro,/ defaults,/" /etc/fstab
+
+		else
+
+
+			sed -i "${line_number}s/[[:space:]]defaults,/ defaults,ro,/" /etc/fstab
+
+			message_result=$(mount -v -o ro,remount "${aDRIVE_MOUNT_SOURCE[$INDEX_DRIVE_BEING_EDITED]}" 2>&1)
+			exit_status=$?
+
+		fi
+
+		systemctl daemon-reload
+		mount -a
+
+		if (( $exit_status != 0 )); then
+
+			whiptail --title "Failed to apply now" --msgbox "Due to:\n - $message_result\n\nIf you have set to read only, this will be active on next reboot" --backtitle "$PROGRAM_NAME" 14 70
+
+		fi
+
+	}
+
 
 	TARGETMENUID=0
 	MENU_LASTITEM=''
@@ -659,7 +811,7 @@
 
 				whiptail_desc+="Capacity:     ${aDRIVE_SIZE_TOTAL[$INDEX_DRIVE_BEING_EDITED]}b\n"
 				whiptail_desc+="Used:         ${aDRIVE_SIZE_USED[$INDEX_DRIVE_BEING_EDITED]}b (${aDRIVE_SIZE_PERCENTUSED[$INDEX_DRIVE_BEING_EDITED]})\n"
-				whiptail_desc+="Status:       Drive is online and ready for use (${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]})"
+				whiptail_desc+="Status:       Drive is online and ready for use"
 
 				# - Disable mount control for /boot /rootfs
 				if [ "${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]}" != "/" ] && [ "${aDRIVE_MOUNT_TARGET[$INDEX_DRIVE_BEING_EDITED]}" != "/boot" ]; then
@@ -690,6 +842,20 @@
 
 				fi
 
+				#Read only?
+				if (( ${aDRIVE_ISREADONLY_FSTAB[$INDEX_DRIVE_BEING_EDITED]} )); then
+
+					whiptail_menu_array+=("Read Only" ": Enabled | Select to allow R/W")
+					whiptail_desc+="\nRead only:    Enabled"
+
+				else
+
+					whiptail_menu_array+=("Read Only" ": Disabled | Select to set read only")
+					whiptail_desc+="\nRead only:    Disabled"
+
+				fi
+
+
 			else
 
 				whiptail_desc+="Status:       Drive is not mounted and can be unplugged\n"
@@ -716,7 +882,7 @@
 		fi
 
 		WHIP_TITLE="$PROGRAM_NAME"
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "$whiptail_desc" --default-item "$MENU_LASTITEM" --cancel-button "Back" --backtitle "$PROGRAM_NAME" 20 90 5 "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "$whiptail_desc" --default-item "$MENU_LASTITEM" --cancel-button "Back" --backtitle "$PROGRAM_NAME" 22 90 6 "${whiptail_menu_array[@]}" 3>&1 1>&2 2>&3)
 
 		CHOICE=$?
 
@@ -854,6 +1020,11 @@
 					fi
 
 				fi
+
+			elif [ "$OPTION" = "Read Only" ]; then
+
+				Toggle_WriteMode
+				ROOTFS_RW_CHECKED=0
 
 			fi
 
@@ -1085,20 +1256,27 @@
 
 	fi
 	#-----------------------------------------------------------------------------------
-	Init_Drives_and_Refresh
-	#-----------------------------------------------------------------------------------
-	#Return for low free space check
-	if (( $INPUT == 2 )); then
+	#Return 1 if RootFS is RO
+	if (( $INPUT == 3 )); then
 
+		RootFS_RW_Check
+
+	#Return for low free space check
+	elif (( $INPUT == 2 )); then
+
+		Init_Drives_and_Refresh
 		RootFS_Low_Free_Space_Check
 
 	#Menu system for user to select an active mount and return value
 	elif (( $INPUT == 1 )); then
 
+		Init_Drives_and_Refresh
 		Menu_Select_Mount_Location
 
 	#Drive Manager
 	else
+
+		Init_Drives_and_Refresh
 
 		while (( $TARGETMENUID > -1 )); do
 
@@ -1127,23 +1305,7 @@
 	fi
 	#-----------------------------------------------------------------------------------
 	#Destroy
-	Init_Drives_and_Refresh
-
-	#Delete []
-	unset aDRIVE_MOUNT_SOURCE
-	unset aDRIVE_MOUNT_TARGET
-	unset aDRIVE_FSTYPE
-	unset aDRIVE_SIZE_TOTAL
-	unset aDRIVE_SIZE_USED
-	unset aDRIVE_SIZE_PERCENTUSED
-	unset aDRIVE_SIZE_FREE
-	unset aDRIVE_PART_UUID
-	unset aDRIVE_UUID
-
-	unset aDRIVE_ISMOUNTED
-	unset aDRIVE_ISFILESYSTEM
-	unset aDRIVE_ISAVAILABLE
-	unset aDRIVE_ISUUIDMOUNT
+	Destroy
 
 	#-----------------------------------------------------------------------------------
 	# Start Services
