v6.31
+ DietPi-Services | Minor coding enhancements

diff --git a/dietpi/dietpi-services b/dietpi/dietpi-services
--- a/dietpi/dietpi-services
+++ b/dietpi/dietpi-services
@@ -261,7 +261,7 @@ _EOF_
 		aSERVICE_EXCLUDED=()
 		local i
 
-		while read line
+		while read -r line
 		do
 
 			# Include
@@ -294,7 +294,7 @@ _EOF_
 						if [[ $INPUT_CMD ]]; then
 
 							[[ $G_DEBUG == 1 ]] && G_DIETPI-NOTIFY 2 "Excluding service: $line"
-							unset aSERVICE_NAME[$i]
+							unset "aSERVICE_NAME[$i]"
 
 						else
 
@@ -329,7 +329,7 @@ _EOF_
 		for i in ${!aSERVICE_NAME[@]}
 		do
 
-			[[ ${aSERVICE_NAME[$i]} ]] || { unset aSERVICE_NAME[$i]; continue; } # Failsafe
+			[[ ${aSERVICE_NAME[$i]} ]] || { unset "aSERVICE_NAME[$i]"; continue; } # Failsafe
 
 			# Check for sysvinit services from systemd-sysv-generator dir: /run/systemd/generator.late/
 			for j in /{{etc,usr/local/lib,lib,usr/lib}/systemd/system,run/systemd/generator.late}/"${aSERVICE_NAME[$i]}.service"
@@ -346,7 +346,7 @@ _EOF_
 			done
 
 			# Remove non-available services from array
-			[[ ${aFP_SERVICE[$i]} ]] || unset aSERVICE_NAME[$i]
+			[[ ${aFP_SERVICE[$i]} ]] || unset "aSERVICE_NAME[$i]"
 
 		done
 
@@ -384,7 +384,7 @@ _EOF_
 		# - start/restart: Standard service order
 		else
 
-			services=${!aSERVICE_NAME[@]}
+			services=${!aSERVICE_NAME[*]}
 
 		fi
 
@@ -425,7 +425,7 @@ _EOF_
 		local index=$2
 		local services i
 
-		[[ $index ]] && services=$index || services=${!aSERVICE_NAME[@]}
+		[[ $index ]] && services=$index || services=${!aSERVICE_NAME[*]}
 
 		# start/stop/restart
 		if [[ $command == 'start' || $command == 'stop' || $command == 'restart' ]]; then
@@ -540,14 +540,14 @@ _EOF_
 		# Reset all process tool settings
 		if [[ $setting == 'reset' ]]; then
 
-			for i in {0..5}; do unset ${aarray[$i]}[$index]; done
+			for i in {0..5}; do unset "${aarray[$i]}[$index]"; done
 			[[ -f $fp ]] && G_EXEC rm "$fp"
 			[[ -d $dp ]] && G_EXEC rmdir --ignore-fail-on-non-empty "$dp"
 
 		# Reset single process tool setting
 		elif [[ $value == 'reset' ]]; then
 
-			unset ${aarray[$setting]}[$index]
+			unset "${aarray[$setting]}[$index]"
 			[[ -f $fp ]] && G_EXEC sed -i "/^${asetting[$setting]}=/d" "$fp"
 
 		# Apply process tool setting
@@ -858,7 +858,7 @@ _EOF_
 
 					(( $SYSTEMD_RELOAD_REQUIRED )) && G_EXEC systemctl daemon-reload && SYSTEMD_RELOAD_REQUIRED=0
 					Set_Running_State $command $MENU_SERVICE_INDEX
-					unset aSERVICE_RESTART_REQUIRED[$MENU_SERVICE_INDEX]
+					unset "aSERVICE_RESTART_REQUIRED[$MENU_SERVICE_INDEX]"
 					sleep 0.5
 
 				;;
@@ -913,7 +913,7 @@ This affects starts/stops/restarts during DietPi-Software installs, DietPi-Updat
 							if grep -q "^+ ${aSERVICE_NAME[$MENU_SERVICE_INDEX]}" $FP_INCLUDE_EXCLUDE; then
 
 								sed -i "/^+ ${aSERVICE_NAME[$MENU_SERVICE_INDEX]}/d" $FP_INCLUDE_EXCLUDE
-								unset aSERVICE_NAME[$MENU_SERVICE_INDEX]
+								unset "aSERVICE_NAME[$MENU_SERVICE_INDEX]"
 								# Service needs to be re-added from main menu
 								MENU_TARGETID=0 # Return to main menu
 
