Move script to dietpi/, update menu keys, capitalize boot status, update path refs
Co-authored-by: StephanStS <57687516+StephanStS@users.noreply.github.com>

diff --git a/dietpi/dietpi-servarr_to_ram b/dietpi/dietpi-servarr_to_ram
--- a/dietpi/dietpi-servarr_to_ram
+++ b/dietpi/dietpi-servarr_to_ram
@@ -158,7 +158,7 @@ $USAGE"; exit 1; }
 			then
 				Print "Creating $FP_DISK/dietpi-servarr_to_ram.sh to be used as ${i^} custom script"
 				# shellcheck disable=SC2320
-				echo -e '#!/bin/dash\n/boot/dietpi/misc/dietpi-servarr_to_ram 2 '"$i" > "$FP_DISK/dietpi-servarr_to_ram.sh" || { error=$? Print "Creating $FP_DISK/dietpi-servarr_to_ram.sh failed."; }
+				echo -e '#!/bin/dash\n/boot/dietpi/dietpi-servarr_to_ram 2 '"$i" > "$FP_DISK/dietpi-servarr_to_ram.sh" || { error=$? Print "Creating $FP_DISK/dietpi-servarr_to_ram.sh failed."; }
 				chmod +x "$FP_DISK/dietpi-servarr_to_ram.sh" || { error=$? Print "Applying $FP_DISK/dietpi-servarr_to_ram.sh execute permissions failed."; }
 				chown "$i:dietpi" "$FP_DISK/dietpi-servarr_to_ram.sh" || { error=$? Print "Applying $FP_DISK/dietpi-servarr_to_ram.sh ownership failed."; }
 			fi
@@ -311,8 +311,8 @@ Before=sonarr.service radarr.service lidarr.service prowlarr.service
 Type=oneshot
 RemainAfterExit=yes
 # We want to preserve logs from the last service stop, to know whether there were issues storing the database back to disk.
-ExecStart=-/bin/dash -c '/boot/dietpi/misc/dietpi-servarr_to_ram 1 2>&1 >> /var/tmp/dietpi/logs/dietpi-servarr_to_ram.log'
-ExecStop=/bin/dash -c '/boot/dietpi/misc/dietpi-servarr_to_ram 0 2>&1 > /var/tmp/dietpi/logs/dietpi-servarr_to_ram.log'
+ExecStart=-/bin/dash -c '/boot/dietpi/dietpi-servarr_to_ram 1 2>&1 >> /var/tmp/dietpi/logs/dietpi-servarr_to_ram.log'
+ExecStop=/bin/dash -c '/boot/dietpi/dietpi-servarr_to_ram 0 2>&1 > /var/tmp/dietpi/logs/dietpi-servarr_to_ram.log'
 
 [Install]
 WantedBy=multi-user.target
@@ -386,20 +386,20 @@ _EOF_
 
 			G_WHIP_MENU_ARRAY=(
 				'' '●─ Database '
-				'link' ': Link Servarr databases to RAM'
-				'store' ': Store databases back to disk'
-				'backup' ': Update database backups'
+				'Link to RAM' ': Link Servarr databases to RAM'
+				'Store to disk' ': Store databases back to disk'
+				'Backup' ': Update database backups'
 				'' '●─ Boot service '
-				'boot' "[${boot_status^}] Enable/disable link to RAM on system boot"
+				'Service' "[${boot_status^}] Enable/disable link to RAM on system boot"
 			)
 
 			G_WHIP_BUTTON_CANCEL_TEXT='Exit'
 			G_WHIP_MENU "DietPi-Servarr_to_RAM: Link Sonarr, Radarr, Lidarr and Prowlarr databases to RAM
-\nBoot service: $boot_status" || return 1
+\nBoot service: ${boot_status^}" || return 1
 
 			case $G_WHIP_RETURNED_VALUE in
 
-				'link')
+				'Link to RAM')
 					Menu_Program || return 0
 					INPUT=1
 					Toggle_Link_To_Ram
@@ -407,7 +407,7 @@ _EOF_
 					EXIT_CODE=0
 				;;
 
-				'store')
+				'Store to disk')
 					Menu_Program || return 0
 					INPUT=0
 					Toggle_Link_To_Ram
@@ -415,7 +415,7 @@ _EOF_
 					EXIT_CODE=0
 				;;
 
-				'backup')
+				'Backup')
 					Menu_Program || return 0
 					INPUT=2
 					Toggle_Link_To_Ram
@@ -423,7 +423,7 @@ _EOF_
 					EXIT_CODE=0
 				;;
 
-				'boot')
+				'Service')
 					if [[ $boot_status == 'enabled' ]]; then
 						Disable_On_Boot
 					else
