v134
+ Start of stretch support and implimentations:
https://github.com/Fourdee/DietPi/issues/475
+ Dont terminate DietPi-Software if libcec fails to install:
https://github.com/Fourdee/DietPi/issues/554

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -187,6 +187,9 @@ _EOF_
 	WIFIHOTSPOT_RTL8188C_DEVICE=0
 	USER_LINUX_AUTOINSTALL_PROMPT_DISPLAYED=0
 
+	#PHP5/7
+	FP_PHP_BASE_DIR='/etc/php5'
+
 	#
 	USBDRIVE=0
 
@@ -2275,7 +2278,14 @@ _EOF_
 	AGI(){
 
 		local string="$@"
-		DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes $string
+
+		local force_yes='--force-yes'
+		#PHP7
+		# if (( $DISTRO == 4 )): then
+			# force_yes='--allow'
+		# fi
+
+		DEBIAN_FRONTEND=noninteractive apt-get install -y $force_yes $string
 
 		local result=$?
 		if (( $result != 0 )); then
@@ -2324,7 +2334,7 @@ _EOF_
 		#Cache size (MB) 1/7th of total mem
 		if (( $1 == 0 )); then
 
-			output=$(( $(free -m -o | grep -m1 'Mem:' | awk '{print $2}') / 7 ))
+			output=$(( $(free -m | grep -m1 'Mem:' | awk '{print $2}') / 7 ))
 
 		#Max active downloads
 		elif (( $1 == 1 )); then
@@ -2623,43 +2633,56 @@ _EOF_
 
 			Banner_Installing
 
+			if (( $DISTRO == 4 )); then
+
+				FP_PHP_BASE_DIR='/etc/php/7.0'
+
+			fi
+
+			local php_package_name='php'
+			if (( $DISTRO == 3 )); then
+
+				php_package_name='php5'
+
+			fi
+
 			#Install base PHP packages/modules.
 			if (( ${aSOFTWARE_INSTALL_STATE[83]} == 1 )); then
 
-				AGI php5 libapache2-mod-php5
+				AGI "$php_package_name" libapache2-mod-"$php_package_name"
 
 			else
 
-				AGI php5-fpm php5-cgi php5-xsl
+				AGI "$php_package_name"-fpm "$php_package_name"-cgi "$php_package_name"-xsl
 
 			fi
 
 			#php-SQL modules
 			if (( ${aSOFTWARE_INSTALL_STATE[86]} == 1 )); then
 
-				AGI php5-mysql
+				AGI "$php_package_name"-mysql
 
 			elif (( ${aSOFTWARE_INSTALL_STATE[88]} == 1 )); then
 
-				AGI php5-mysqlnd
+				AGI "$php_package_name"-mysqlnd
 
 			fi
 
 			if (( ${aSOFTWARE_INSTALL_STATE[87]} == 1 )); then
 
-				AGI php5-sqlite
+				AGI "$php_package_name"-sqlite* #wildcard for version (eg:3)
 
 			fi
 
-			#Redis php5 module | >= 1 to check for existing installs (2)
+			#Redis php module | >= 1 to check for existing installs (2)
 			if (( ${aSOFTWARE_INSTALL_STATE[91]} >= 1 )); then
 
-				AGI php5-redis
+				AGI "$php_package_name"-redis
 
 			fi
 
-			#Jessie - APCu
-			AGI php5-apcu
+			#APCu
+			AGI "$php_package_name"-apcu
 
 		fi
 
@@ -2828,7 +2851,11 @@ _EOF_
 			#Install
 			if (( $? == 0 )); then
 
-				AGI php5-curl php5-gd
+				if (( $DISTRO == 3 )); then
+					AGI php5-curl php5-gd
+				else
+					AGI php-curl php-gd php-zip php-mbstring
+				fi
 
 				wget "$INSTALL_URL_ADDRESS" -O package.zip
 				unzip package.zip -d /var/www
@@ -2930,8 +2957,22 @@ _EOF_
 
 			# - libcurl3-gnutls required for C2. But lets apply to all: https://github.com/Fourdee/DietPi/issues/446
 			# - Add NFS support for kodi
+			AGI libcurl3-gnutls libnfs4
+
 			# - CEC support | * due to C2 having libcec3v4, rpi has libcec3.
-			AGI libcurl3-gnutls libnfs4 libcec3*
+			#	XU4 package conflict: https://github.com/Fourdee/DietPi/issues/554
+			#	Due to the vast differences in libcec naming across devices, if CEC fails to install, do not terminate DietPi install.
+			apt-get install -y libcec3*
+			if (( $? != 0 )); then
+
+				apt-get install -y libcec3
+				if (( $? != 0 )); then
+
+					/DietPi/dietpi/func/dietpi-notify 2 "libcec3 failed to install."
+
+				fi
+
+			fi
 
 		fi
 
@@ -3378,7 +3419,7 @@ _EOF_
 				cp /etc/pihole/adlists.default /etc/.pihole/adlists.default
 
 				#Check free available memory. Increase swapfile size to prevent gravity running out of mem.
-				if (( $(free -m -o | grep -m1 'Mem:' | awk '{print $4}') < 512 )); then
+				if (( $(free -m | grep -m1 'Mem:' | awk '{print $4}') < 512 )); then
 
 					if [ -f /etc/dphys-swapfile ] &&
 						(( $(cat /etc/dphys-swapfile | grep 'CONF_SWAPSIZE=' | sed 's/.*=//') < 512 )); then
@@ -3799,7 +3840,12 @@ _EOF_
 			#Install
 			if (( $? == 0 )); then
 
-				AGI php5-gd
+				if (( $DISTRO == 3 )); then
+					AGI php5-gd
+				else
+					AGI php-gd
+				fi
+
 				wget "$INSTALL_URL_ADDRESS" -O package.zip
 				unzip package.zip -d /var/www/gallery
 				rm package.zip
@@ -3826,7 +3872,11 @@ _EOF_
 			#Install
 			if (( $? == 0 )); then
 
-				AGI php5-curl
+				if (( $DISTRO == 3 )); then
+					AGI php5-curl
+				else
+					AGI php-curl
+				fi
 
 				wget "$INSTALL_URL_ADDRESS" -O package.zip
 				unzip package.zip
@@ -4088,7 +4138,11 @@ _EOF_
 			if (( $? == 0 )); then
 
 				# - Prereqs
-				AGI php5-mcrypt php5-gd
+				if (( $DISTRO == 3 )); then
+					AGI php5-mcrypt php5-gd
+				else
+					AGI php-mcrypt php-gd
+				fi
 
 				wget "$INSTALL_URL_ADDRESS" -O package.zip
 				unzip package.zip -d /var/www
@@ -4508,7 +4562,13 @@ _EOF_
 			#Install
 			if (( $? == 0 )); then
 
-				AGI rtorrent screen php5-curl #mediainfo
+				AGI rtorrent screen #mediainfo
+
+				if (( $DISTRO == 3 )); then
+					AGI php5-curl
+				else
+					AGI php-curl
+				fi
 
 				#Raspbian unrar free
 				if (( $HW_MODEL < 10 )); then
@@ -5420,6 +5480,11 @@ _EOF_
 			sed -i '/^server.document-root/c\server.document-root        = "/var/www"' /etc/lighttpd/lighttpd.conf
 
 			#Configure fastcgi for PHP-FPM
+			local fp_php_fpm_sock='/var/run/php/php7.0-fpm.sock'
+			if (( $DISTRO == 3 )); then
+				fp_php_fpm_sock='/var/run/php5-fpm.sock'
+			fi
+
 			cat << _EOF_ > /etc/lighttpd/conf-available/15-fastcgi-php.conf
 # -*- depends: fastcgi -*-
 # /usr/share/doc/lighttpd/fastcgi.txt.gz
@@ -5428,7 +5493,7 @@ _EOF_
 ## Start an FastCGI server using php-fpm
 fastcgi.server += ( ".php" =>
         ((
-                "socket" => "/var/run/php5-fpm.sock",
+                "socket" => "$fp_php_fpm_sock",
                 "broken-scriptfilename" => "enable"
         ))
 )
@@ -5458,30 +5523,28 @@ _EOF_
 			else
 
 				# - Php-FPM confs
-				cp /DietPi/dietpi/conf/php-fpm.conf /etc/php5/fpm/php-fpm.conf
-				cp /DietPi/dietpi/conf/php-fpm_pool.conf /etc/php5/fpm/pool.d/www.conf
-				sed -i '/cgi.fix_pathinfo=/c\cgi.fix_pathinfo=1' /etc/php5/fpm/php.ini
+				sed -i '/cgi.fix_pathinfo=/c\cgi.fix_pathinfo=1' "$FP_PHP_BASE_DIR"/fpm/php.ini
 
-				# - PHP5-fpm optimizations based on total cores
-				sed -i "/pm.max_children = /c\pm.max_children = $CPU_CORES_TOTAL" /etc/php5/fpm/pool.d/www.conf
-				sed -i "/pm.start_servers = /c\pm.start_servers = $CPU_CORES_TOTAL" /etc/php5/fpm/pool.d/www.conf
-				sed -i "/pm.min_spare_servers = /c\pm.min_spare_servers = $CPU_CORES_TOTAL" /etc/php5/fpm/pool.d/www.conf
-				sed -i "/pm.max_spare_servers = /c\pm.max_spare_servers = $CPU_CORES_TOTAL" /etc/php5/fpm/pool.d/www.conf
+				# - PHP-fpm optimizations based on total cores
+				sed -i "/pm.max_children = /c\pm.max_children = $CPU_CORES_TOTAL" "$FP_PHP_BASE_DIR"/fpm/pool.d/www.conf
+				sed -i "/pm.start_servers = /c\pm.start_servers = $CPU_CORES_TOTAL" "$FP_PHP_BASE_DIR"/fpm/pool.d/www.conf
+				sed -i "/pm.min_spare_servers = /c\pm.min_spare_servers = $CPU_CORES_TOTAL" "$FP_PHP_BASE_DIR"/fpm/pool.d/www.conf
+				sed -i "/pm.max_spare_servers = /c\pm.max_spare_servers = $CPU_CORES_TOTAL" "$FP_PHP_BASE_DIR"/fpm/pool.d/www.conf
 
 				# - Enviroment PHP settings:
-				sed -i "/env\[HOSTNAME\]/c\env\[HOSTNAME\] = \$HOSTNAME" /etc/php5/fpm/pool.d/www.conf
-				sed -i "/env\[PATH\]/c\env\[PATH\] = /usr/local/bin:/usr/bin:/bin" /etc/php5/fpm/pool.d/www.conf
+				sed -i "/env\[HOSTNAME\]/c\env\[HOSTNAME\] = \$HOSTNAME" "$FP_PHP_BASE_DIR"/fpm/pool.d/www.conf
+				sed -i "/env\[PATH\]/c\env\[PATH\] = /usr/local/bin:/usr/bin:/bin" "$FP_PHP_BASE_DIR"/fpm/pool.d/www.conf
 
 				#	/tmp is mounted to RAM, so use DISK (/var/tmp) instead
-				sed -i "/env\[TMP\]/c\env\[TMP\] = /var/tmp" /etc/php5/fpm/pool.d/www.conf
-				sed -i "/env\[TMPDIR\]/c\env\[TMPDIR\] = /var/tmp" /etc/php5/fpm/pool.d/www.conf
-				sed -i "/env\[TEMP\]/c\env\[TEMP\] = /var/tmp" /etc/php5/fpm/pool.d/www.conf
+				sed -i "/env\[TMP\]/c\env\[TMP\] = /var/tmp" "$FP_PHP_BASE_DIR"/fpm/pool.d/www.conf
+				sed -i "/env\[TMPDIR\]/c\env\[TMPDIR\] = /var/tmp" "$FP_PHP_BASE_DIR"/fpm/pool.d/www.conf
+				sed -i "/env\[TEMP\]/c\env\[TEMP\] = /var/tmp" "$FP_PHP_BASE_DIR"/fpm/pool.d/www.conf
 
 			fi
 
 			#php APC/u settings
 			local target_php_ini=0
-			local target_php_cachesize=$(( $(free -m -o | grep -m1 'Mem:' | awk '{print $2}') / 30 ))
+			local target_php_cachesize=$(( $(free -m | grep -m1 'Mem:' | awk '{print $2}') / 30 ))
 			if (( $target_php_cachesize < 10 )); then
 
 				target_php_cachesize=10
@@ -5492,15 +5555,19 @@ _EOF_
 			local target_apc_ttl='259200'
 
 			#PHP OPcache
-			php5enmod opcache
+			if (( $DISTRO == 3 )); then
+				php5enmod opcache
+			else
+				phpenmod opcache
+			fi
 
 			if (( ${aSOFTWARE_INSTALL_STATE[83]} >= 1 )); then
 
-				target_php_ini='/etc/php5/apache2/php.ini'
+				target_php_ini="$FP_PHP_BASE_DIR/apache2/php.ini"
 
 			else
 
-				target_php_ini='/etc/php5/fpm/php.ini'
+				target_php_ini="$FP_PHP_BASE_DIR/fpm/php.ini"
 
 			fi
 
@@ -5511,11 +5578,15 @@ _EOF_
 			wget https://raw.githubusercontent.com/rlerdorf/opcache-status/master/opcache.php -O /var/www/opcache.php
 
 			#APCu
-			php5enmod apcu
+			if (( $DISTRO == 3 )); then
+				php5enmod apcu
+			else
+				phpenmod apcu
+			fi
 
 			# - apc.shm_size= requires M at end to prevent warning: https://github.com/Fourdee/DietPi/issues/218
 			target_php_cachesize+="M"
-			target_php_ini='/etc/php5/mods-available/apcu.ini'
+			target_php_ini="$FP_PHP_BASE_DIR/mods-available/apcu.ini"
 
 			cat << _EOF_ > "$target_php_ini"
 extension=apcu.so
@@ -5523,14 +5594,21 @@ apc.shm_size=$target_php_cachesize
 apc.ttl=$target_apc_ttl
 _EOF_
 
-			cp /usr/share/doc/php5-apcu/apc.php /var/www/apc.php
+			if (( $DISTRO == 3 )); then
+
+				cp /usr/share/doc/php5-apcu/apc.php /var/www/apc.php
+
+				#PHP7?
+
+			fi
+
 
 			#Array to store known locations of php.ini, so we can apply same settings to all of them.
 			local afp_php_ini=(
-				"/etc/php5/apache2/php.ini"
-				"/etc/php5/cli/php.ini"
-				"/etc/php5/cgi/php.ini"
-				"/etc/php5/fpm/php.ini"
+				"$FP_PHP_BASE_DIR/apache2/php.ini"
+				"$FP_PHP_BASE_DIR/cli/php.ini"
+				"$FP_PHP_BASE_DIR/cgi/php.ini"
+				"$FP_PHP_BASE_DIR/fpm/php.ini"
 			)
 
 			# - temp dir
@@ -5597,8 +5675,8 @@ _EOF_
 		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
 
 			#Enable resdis extensions for all webstacks:
-			echo -e "extension=redis.so" > /etc/php5/cli/conf.d/20-redis.ini &> /dev/null
-			echo -e "extension=redis.so" > /etc/php5/apache2/conf.d/20-redis.ini &> /dev/null
+			echo -e "extension=redis.so" > "$FP_PHP_BASE_DIR"/cli/conf.d/20-redis.ini &> /dev/null
+			echo -e "extension=redis.so" > "$FP_PHP_BASE_DIR"/apache2/conf.d/20-redis.ini &> /dev/null
 
 		fi
 
@@ -5631,13 +5709,6 @@ _EOF_
 			rm -R "$target_data_symlink" &> /dev/null
 			ln -fs "$target_data_dir" "$target_data_symlink"
 
-			#Php env
-			sed -i "/env\[HOSTNAME\] = /c\env\[HOSTNAME\] = \$HOSTNAME" /etc/php5/fpm/pool.d/www.conf
-			sed -i "/env\[PATH\] = /c\env\[PATH\] = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" /etc/php5/fpm/pool.d/www.conf
-			sed -i "/env\[TMP\] = /c\env\[TMP\] = /tmp" /etc/php5/fpm/pool.d/www.conf
-			sed -i "/env\[TMPDIR\] = /c\env\[TMPDIR\] = /tmp" /etc/php5/fpm/pool.d/www.conf
-			sed -i "/env\[TEMP\] = /c\env\[TEMP\] = /tmp" /etc/php5/fpm/pool.d/www.conf
-
 ##################################################################################################
 			#Currently in user docs:
 
@@ -5650,8 +5721,8 @@ _EOF_
 			# sed -i "/upload_max_filesize=/c\upload_max_filesize=2048M" /var/www/owncloud/.user.ini
 			# sed -i "/post_max_size=/c\post_max_size=2048M" /var/www/owncloud/.user.ini
 
-			# local memory_limit_max="$(( $(free -m -o | grep -m1 'Mem:' | awk '{print $2}') / 4 ))M"
-			# sed -i "/memory_limit=/c\memory_limit=$(( $(free -m -o | grep -m1 'Mem:' | awk '{print $2}') / 4 ))M" /var/www/owncloud/.user.ini
+			# local memory_limit_max="$(( $(free -m | grep -m1 'Mem:' | awk '{print $2}') / 4 ))M"
+			# sed -i "/memory_limit=/c\memory_limit=$(( $(free -m | grep -m1 'Mem:' | awk '{print $2}') / 4 ))M" /var/www/owncloud/.user.ini
 
 			#APCu Memcache
 			#NB: /var/www/owncloud/config/config.php does not exist until after 1st run setup.
@@ -5684,8 +5755,6 @@ _EOF_
 
 			service mysql start
 
-			cd /var/www/nextcloud
-
 			local username=$(cat /DietPi/dietpi.txt | grep -m1 '^dietpi_nextcloud_username=' | sed 's/.*=//')
 			if [ ! -n "$username" ]; then
 
@@ -5693,6 +5762,7 @@ _EOF_
 
 			fi
 
+			cd /var/www/nextcloud
 			sudo -u www-data php occ maintenance:install --no-interaction --database "mysql" --database-name "nextcloud" --database-user "root" --database-pass "$GLOBAL_PW" --admin-user "$username" --admin-pass "$GLOBAL_PW" --data-dir "$FP_DIETPI_USERDATA_DIRECTORY/nextcloud_data"
 			cd "$HOME"
 
@@ -5711,8 +5781,8 @@ _EOF_
 			sed -i "/post_max_size=/c\post_max_size=$php_max_upload_size" /var/www/nextcloud/.user.ini
 
 			# - Memory limit, total / 4
-			local memory_limit_max="$(( $(free -m -o | grep -m1 'Mem:' | awk '{print $2}') / 4 ))M"
-			sed -i "/memory_limit=/c\memory_limit=$(( $(free -m -o | grep -m1 'Mem:' | awk '{print $2}') / 4 ))M" /var/www/nextcloud/.user.ini
+			local memory_limit_max="$(( $(free -m | grep -m1 'Mem:' | awk '{print $2}') / 4 ))M"
+			sed -i "/memory_limit=/c\memory_limit=$(( $(free -m | grep -m1 'Mem:' | awk '{print $2}') / 4 ))M" /var/www/nextcloud/.user.ini
 
 			# - APCu Memcache
 			if (( ! $(cat /var/www/nextcloud/config/config.php | grep -ci -m1 "'memcache.local'") )); then
@@ -6310,7 +6380,7 @@ _EOF_
 			Create_UserContent_Folders
 
 			#Optimize memory limit
-			local subsonic_memory_max=$(( $(free -m -o | grep -m1 'Mem:' | awk '{print $2}') / 5 ))
+			local subsonic_memory_max=$(( $(free -m | grep -m1 'Mem:' | awk '{print $2}') / 5 ))
 			#Minimum cap 150mb
 			if (( $subsonic_memory_max < 150 )); then
 
@@ -7020,7 +7090,7 @@ _EOF_
 
 			#Configure apache2
 			# - Disable php output_buffering =
-			sed -i '/output_buffering = /c\output_buffering = Off/' /etc/php5/apache2/php.ini
+			sed -i '/output_buffering = /c\output_buffering = Off/' "$FP_PHP_BASE_DIR"/apache2/php.ini
 			# - Allow overrides and redirects
 			sed -i "/AllowOverride /c\    AllowOverride All" /etc/apache2/sites-enabled/000-default*
 			# - +Jessie
@@ -7030,8 +7100,11 @@ _EOF_
 			a2enmod rewrite
 
 			# - Enable PHP mods
-			php5enmod mcrypt
-			php5enmod gd
+			if (( $DISTRO == 3 )); then
+				php5enmod mcrypt gd
+			else
+				phpenmod mcrypt gd
+			fi
 
 			#Create Mysql DB
 			/DietPi/dietpi/func/create_mysql_db pydio dietpi root dietpi
@@ -8036,11 +8109,16 @@ _EOF_
 
 		elif (( $1 == 89 )); then
 
-			AGP php5 libapache2-mod-php5 php5-fpm php5-cgi php5-mysql php5-curl php5-sqlite php-apc php5-apcu
+			if (( $DISTRO == 3 )); then
+				AGP php5-* libapache2-mod-php5
+			else
+				AGP php-* libapache2-mod-php
+			fi
+
 			rm /var/www/phpinfo.php
 			rm /var/www/apc.php
 			rm /var/www/opcache.php
-			rm /etc/php5/fpm/pool.d/www.conf
+			rm "$FP_PHP_BASE_DIR"/fpm/pool.d/www.conf
 			#temp php uploads
 			rm -R /var/tmp/php_upload_tmp
 
