v142
+ DietPi-Backup. Do not restore userdata if a userdata backup does not
exist, and minor notify corrections:
https://github.com/Fourdee/DietPi/issues/685

diff --git a/dietpi/dietpi-backup b/dietpi/dietpi-backup
--- a/dietpi/dietpi-backup
+++ b/dietpi/dietpi-backup
@@ -481,7 +481,7 @@ _EOF_
 
 					else
 
-						/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT FAILED.\n"
+						/DietPi/dietpi/func/dietpi-notify 1 "$RSYNC_MODE_TEXT FAILED.\n"
 						echo -e "$RSYNC_MODE_TEXT FAILED       : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
 						BACKUP_RESTORE_FAILED=1
 						break
@@ -502,7 +502,7 @@ _EOF_
 
 						else
 
-							/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT FAILED.\n"
+							/DietPi/dietpi/func/dietpi-notify 1 "$RSYNC_MODE_TEXT FAILED.\n"
 							echo -e "$RSYNC_MODE_TEXT FAILED    : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
 							BACKUP_RESTORE_FAILED=1
 							break
@@ -559,7 +559,7 @@ _EOF_
 				/DietPi/dietpi/func/dietpi-notify 2 "No Backup was found in $FP_TARGET_BACKUP"
 				/DietPi/dietpi/func/dietpi-notify 1 "$RSYNC_MODE_TEXT Failed.\n"
 				if (( $INPUT == 0 )); then
-					whiptail --title "$RSYNC_MODE_TEXT failed." --msgbox "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM does not exist\n\nHave you created a backup?" --backtitle "$WHIP_BACKTITLE" 11 70
+					whiptail --title "$RSYNC_MODE_TEXT failed" --msgbox "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM does not exist\n\nHave you created a backup?" --backtitle "$WHIP_BACKTITLE" 11 70
 				fi
 
 			#Error: Rsync is already running
@@ -605,18 +605,27 @@ _EOF_
 
 					if (( $BACKUP_MODE == 1 )); then
 
-						rsync $RSYNC_RUN_OPTIONS_USERDATA_BACKUP "$FP_TARGET_BACKUP"/dietpi-backup_userdata/ "$FP_SOURCE_USERDATA_ACTUAL"/
-						if (( $? == 0 )); then
+						# - Only restore userdata if a backup exists
+						if [ -f "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA" ]; then
 
-							/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
-							echo -e "$RSYNC_MODE_TEXT Completed : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
+							rsync $RSYNC_RUN_OPTIONS_USERDATA_BACKUP "$FP_TARGET_BACKUP"/dietpi-backup_userdata/ "$FP_SOURCE_USERDATA_ACTUAL"/
+							if (( $? == 0 )); then
+
+								/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
+								echo -e "$RSYNC_MODE_TEXT Completed : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
+
+							else
+
+								/DietPi/dietpi/func/dietpi-notify 1 "$RSYNC_MODE_TEXT FAILED.\n"
+								echo -e "$RSYNC_MODE_TEXT FAILED    : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
+								BACKUP_RESTORE_FAILED=1
+								break
+
+							fi
 
 						else
 
-							/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT FAILED.\n"
-							echo -e "$RSYNC_MODE_TEXT FAILED    : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
-							BACKUP_RESTORE_FAILED=1
-							break
+							/DietPi/dietpi/func/dietpi-notify 2 "$RSYNC_MODE_TEXT: No backup exists, skipping...\n"
 
 						fi
 
