v126
+ See changelog

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -13,6 +13,10 @@
 	# - Installs "ready to run" software with optimizations unique to the device.
 	# - Runs dietpi-update during 1st run setup.
 	# - Generates and uses /DietPi/dietpi/.installed (software list) # 0=not installed, 1=selected for install, 2=installed
+	#
+	# Usage:
+	# - dietpi-software
+	# - /DietPi/dietpi/dietpi-software install		sPROGRAMTOINSTALL=1 	(OR) 	sINDEX_{SSHSERVER,FILESERVER,LOGGING,WEBSERVER}_TARGET=-int
 	#////////////////////////////////////
 
 	#Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
@@ -70,6 +74,12 @@
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Installation System Vars
 	#/////////////////////////////////////////////////////////////////////////////////////
+	#Reboot after installation has finished.
+	DISABLE_REBOOT=0
+
+	#Enable all user inputs (eg: prompts)
+	USER_INPUTS=1
+
 	#Run Instalation Flag (1 = run installs)
 	GOSTARTINSTALL=0
 	INSTALL_URL_ADDRESS=""
@@ -99,12 +109,6 @@
 	# First Run / Automation functions Vars (eg: on a fresh install)
 	#/////////////////////////////////////////////////////////////////////////////////////
 	AUTOINSTALL_INDEX=0
-
-	AUTOINSTALL_SKIPUSBDRIVEPROMPT=0
-	AUTOINSTALL_SKIPQUESTIONS=0
-	AUTOINSTALL_IGNOREERRORS=0
-
-	AUTOINSTALL_DEDICATEDUSBDRIVEFORMAT=0
 
 	AUTOINSTALL_SSHINDEX=0
 	AUTOINSTALL_FILESERVERINDEX=0
@@ -149,7 +153,7 @@
 			/DietPi/dietpi/func/check_connection "$INTERNET_URL_TEST"
 			if (( $? == 0 )); then
 				INTERNET_CONNECTED=1
-			else
+			elif (( $USER_INPUTS )); then
 				Menu_No_Internet
 			fi
 
@@ -5901,18 +5905,20 @@ systemctl daemon-reload
 		Write_InstallFileList
 
 		#DietPi-Automation
-		if (( $DIETPI_INSTALL_STAGE == 0 )) &&
-			(( $AUTOINSTALL_INDEX == 1 )); then
+		if (( $DIETPI_INSTALL_STAGE == 0 )); then
 
 			#Apply Timezone
 			if [ "$AUTOINSTALL_TIMEZONE" != "Europe/London" ]; then
+
 				echo -e "\nDietPi: Setting Timezone = $AUTOINSTALL_TIMEZONE"
 				echo -e "$AUTOINSTALL_TIMEZONE" > /etc/timezone
 				dpkg-reconfigure -f noninteractive tzdata
+
 			fi
 
 			#Apply Language (Locale)
 			if [ "$AUTOINSTALL_LANGUAGE" != "en_GB" ]; then
+
 				/DietPi/dietpi/func/dietpi-notify 2 "Setting Locale $AUTOINSTALL_LANGUAGE. Please wait....\n"
 
 				#Disable en_GB
@@ -5928,6 +5934,7 @@ systemctl daemon-reload
 
 			#Apply Keyboard
 			if [ "$AUTOINSTALL_KEYBOARD" != "gb" ]; then
+
 				/DietPi/dietpi/func/dietpi-notify 2 "Setting Keyboard $AUTOINSTALL_KEYBOARD. Please wait....\n"
 				sed -i '/XKBLAYOUT=/c XKBLAYOUT="'"$AUTOINSTALL_KEYBOARD"'"' /etc/default/keyboard
 				#systemctl restart keyboard-setup
@@ -5936,16 +5943,21 @@ systemctl daemon-reload
 
 			#Apply & Mount Network drives if installed
 			if (( $SMBCLIENT == 2 )); then
+
 				/DietPi/dietpi/func/dietpi-set_smbclient 1
+
 			fi
 
 			if (( $CURLFTPFS == 2 )); then
+
 				/DietPi/dietpi/func/dietpi-set_curlftpfs 1
+
 			fi
 
 			local run_custom_script=0
 			#Custom 1st run Script (Local file)
 			if [ -f /boot/Automation_Custom_Script.sh ]; then
+
 				INSTALL_DESCRIPTION='Automation - Local Custom Script'
 				Banner_Installing
 
@@ -5970,19 +5982,28 @@ systemctl daemon-reload
 					run_custom_script=1
 
 				else
+
 					echo -e "Automated Custom Script URL Error:\n $AUTOINSTALL_CUSTOMSCRIPTURL is offline and/or unreachable" >> "$FP_DIETPIAUTOMATION_LOG"
+
 				fi
+
 			fi
 
 			if (( $run_custom_script == 1 )); then
+
 				chmod +x /root/AUTO_CustomScript.sh
 				/root/AUTO_CustomScript.sh
 				local result=$?
 				if (( $result == 0 )); then
+
 					echo -e "Automated custom script executed succesfully:\n - Filepath = /root/AUTO_CustomScript.sh\n - URL = $AUTOINSTALL_CUSTOMSCRIPTURL" >> "$FP_DIETPIAUTOMATION_LOG"
+
 				else
+
 					echo -e "Automated Custom Script Error:\n - Exit code = $result\n - Filepath = /root/AUTO_CustomScript.sh\n - URL = $AUTOINSTALL_CUSTOMSCRIPTURL" >> "$FP_DIETPIAUTOMATION_LOG"
+
 				fi
+
 			fi
 
 			#Apply AutoStart
@@ -6000,12 +6021,6 @@ systemctl daemon-reload
 		#Get settings
 		AUTOINSTALL_INDEX=$(cat /DietPi/dietpi.txt | grep -m1 '^AUTO_Install_Index=' | sed 's/.*=//')
 
-		AUTOINSTALL_SKIPUSBDRIVEPROMPT=$(cat /DietPi/dietpi.txt | grep -ci -m1 '^AUTO_DietpiSoftware_SkipUsbDrive=1')
-		AUTOINSTALL_SKIPQUESTIONS=$(cat /DietPi/dietpi.txt | grep -ci -m1 '^AUTO_DietpiSoftware_SkipQuestions=1')
-		AUTOINSTALL_IGNOREERRORS=$(cat /DietPi/dietpi.txt | grep -ci -m1 '^AUTO_DietpiSoftware_IgnoreErrors=1')
-
-		AUTOINSTALL_DEDICATEDUSBDRIVEFORMAT=0
-
 		AUTOINSTALL_AUTOSTARTTARGET=$(cat /DietPi/dietpi.txt | grep -m1 '^AUTO_AutoStartTarget=' | sed 's/.*=//' )
 
 		AUTOINSTALL_SSHINDEX=$(cat /DietPi/dietpi.txt | grep -m1 '^AUTO_DietpiSoftware_SSHServerIndex=' | sed 's/.*=//')
@@ -6019,8 +6034,8 @@ systemctl daemon-reload
 
 		AUTOINSTALL_CUSTOMSCRIPTURL=$(cat /DietPi/dietpi.txt | grep -m1 '^AUTO_CustomScriptURL=' | sed 's/AUTO_CustomScriptURL=//')
 
-		#Automated install based on index
-		if (( $AUTOINSTALL_INDEX > 0 )); then
+		#Automated install
+		if (( $AUTOINSTALL_INDEX >= 1 )); then
 
 			/DietPi/dietpi/dietpi-banner 0
 			echo -e "\n Running Automated Installation:\n"
@@ -6028,93 +6043,20 @@ systemctl daemon-reload
 			#Skip dietpi-software menu
 			TARGETMENUID=-1
 
+			#Disable user inputs and prompts.
+			USER_INPUTS=0
+
 			#Set start install
 			GOSTARTINSTALL=1
 
 			#Auto format/setup USB drive
 			if [ -f /boot/Automation_Format_My_Usb_Drive ]; then
 
-				#Skip USB drive prompt
-				AUTOINSTALL_SKIPUSBDRIVEPROMPT=1
-
 				#Run Format
 				/DietPi/dietpi/dietpi-external_drive_setup 1
 
 			fi
 
-			#Define Install indexs
-			#DietPi-Automated (from dietpi.txt)
-			if (( $AUTOINSTALL_INDEX == 1 )); then
-				echo -e " - DietPi-Automated\n"
-				/DietPi/dietpi/dietpi-funtime 0
-
-				#Override automation options?
-				# - Leave this down to the user and their settings in dietpi.txt
-
-				#Find if user has enabled at least 1 installation option in dietpi.txt
-				if (( $(cat /DietPi/dietpi.txt | grep '^AUTO_DietpiSoftware_Install' | grep -ci -m1 '=1') )); then
-
-					#Save current vars to .installed file
-					Write_InstallFileList
-
-					#Obtain the .installed names of all software which has been selected for install
-					cat /DietPi/dietpi.txt | grep '^AUTO_DietpiSoftware_Install' | grep '=1' | sed 's/AUTO_DietpiSoftware_Install_//' | sed 's/1.*//' > /tmp/.dietpi-software_autoinstall_choices
-					while read line
-					do
-
-						#Update.installed file and set to 1 (to be installed)
-						sed -i "/^$line/c $line\1" "$FP_INSTALLED_FILE"
-
-					done < /tmp/.dietpi-software_autoinstall_choices
-					rm /tmp/.dietpi-software_autoinstall_choices
-
-					#Read the .installed file to update vars.
-					Read_InstallFileList
-
-				fi
-
-			#Grasshopper
-			elif (( $AUTOINSTALL_INDEX == 2 )); then
-				echo -e " - Grasshopper\n"
-				/DietPi/dietpi/dietpi-funtime 0
-
-				#Required DietPi Software
-				GRASSHOPPER=1
-
-				#Override automation options
-				AUTOINSTALL_SKIPUSBDRIVEPROMPT=1
-				AUTOINSTALL_SKIPQUESTIONS=1
-				AUTOINSTALL_SSHINDEX=-2
-				AUTOINSTALL_LOGGINGINDEX=-2
-
-				#Inform user to setup STATIC IP
-				WHIP_TITLE='DietPi - Setup static IP'
-				WHIP_QUESTION='DietPi-Config will now be launched, this will allow you to setup a STATIC IP for this device.\nSimply select your Ethernet or Wifi connection from the menu to access the IP address settings.\n\nThe "copy current address to STATIC" menu option can be used to quickly setup your static IP. Please ensure you change the mode "DHCP" to "STATIC".\n\nWhen you are done, select "Apply, Save Changes", then, exit DietPi-Config to resume setup.'
-				whiptail --title "$WHIP_TITLE" --msgbox "$WHIP_QUESTION" 19 70
-
-				#Launch DietPi-config networking menu
-				/DietPi/dietpi/dietpi-config 8 1
-
-			elif (( $AUTOINSTALL_INDEX == 3 )); then
-				echo -e " - Pi-hole\n"
-				/DietPi/dietpi/dietpi-funtime 0
-
-				#Required DietPi Software
-				PIHOLE=1
-
-				#Override automation options
-				AUTOINSTALL_SKIPUSBDRIVEPROMPT=1
-				AUTOINSTALL_SKIPQUESTIONS=1
-
-				#Inform user to setup STATIC IP
-				WHIP_TITLE='DietPi - Setup static IP'
-				WHIP_QUESTION='DietPi-Config will now be launched, this will allow you to setup a STATIC IP for this device.\nSimply select your Ethernet or Wifi connection from the menu to access the IP address settings.\n\nThe "copy current address to STATIC" menu option can be used to quickly setup your static IP. Please ensure you change the mode "DHCP" to "STATIC".\n\nWhen you are done, select "Apply, Save Changes", then, exit DietPi-Config to resume setup.'
-				whiptail --title "$WHIP_TITLE" --msgbox "$WHIP_QUESTION" 19 70
-
-				#Launch DietPi-config networking menu
-				/DietPi/dietpi/dietpi-config 8 1
-
-			fi
 		fi
 
 		#Further Automated options. (Applied regardless of AUTOINSTALL_INDEX)
@@ -6122,12 +6064,6 @@ systemctl daemon-reload
 		INDEX_FILESERVER_TARGET=$AUTOINSTALL_FILESERVERINDEX
 		INDEX_LOGGING_TARGET=$AUTOINSTALL_LOGGINGINDEX
 		INDEX_WEBSERVER_TARGET=$AUTOINSTALL_WEBSERVERINDEX
-
-		#VM - Disable external drive question/setup
-		if (( $HW_MODEL == 20 )); then
-			AUTOINSTALL_SKIPUSBDRIVEPROMPT=1
-			AUTOINSTALL_SKIPQUESTIONS=1
-		fi
 
 	}
 
@@ -6151,11 +6087,13 @@ systemctl daemon-reload
 
 			clear
 			/DietPi/dietpi/dietpi-banner 0
-			WHIP_TITLE='DietPi Update Completed'
 
-			#Prompt user for reboot, if not overridden by automation flag
-			if (( $(cat /DietPi/dietpi.txt | grep -ci -m1 '^AUTO_DietpiSoftware_SkipUpdateRebootPrompt=1') == 0 )); then
+			#Prompt user for reboot
+			if (( $USER_INPUTS )); then
+
+				WHIP_TITLE='DietPi Update Completed'
 				whiptail --title "$WHIP_TITLE" --msgbox "DietPi has been updated to the latest version.\nYour system will now reboot. Once completed, simply login to resume DietPi Setup. \n\nPress Enter to Continue." 13 65
+
 			fi
 
 			#Make sure apt-get_update thread is finished
@@ -6170,34 +6108,34 @@ systemctl daemon-reload
 
 	FirstRun_Questions(){
 
-		#Questions Start (Ask our inital questions, before allowing access to the software selection menus)
-		if (( $AUTOINSTALL_SKIPQUESTIONS == 0 )); then
+		if (( $USER_INPUTS )); then
+
+			#Questions Start (Ask our inital questions, before allowing access to the software selection menus)
 			WHIP_TITLE='DietPi - Welcome'
 			whiptail --title "$WHIP_TITLE" --msgbox "Welcome to the DietPi Installation System. \n \nBefore we can begin, we need to ask you a few questions regarding this installation. \n \nPress Enter to begin." 14 70
-		fi
 
-		#Request for Dedicated External Drive installation.
-		if (( $USBDRIVE == 0 )) &&
-			(( $AUTOINSTALL_SKIPUSBDRIVEPROMPT == 0 )); then
-			WHIP_TITLE='Setup USB Dedicated Drive?'
-			WHIP_QUESTION='If you choose to setup a dedicated USB drive, DietPi will automatically configure your future software installations to utilize the USB drive for user data storage, instead of SD.\nAs USB hard drives can be faster than most SD cards, using a USB drive can vastly improve system performance.\n\nExamples of software, that will benefit from a USB drive: \n - BitTorrent (Store downloads) \n - OwnCloud (Larger data storage)\n - Kodi / Plex / Emby etc (Store Media Files)\n\nMore information on user data in DietPi:\n - http://dietpi.com/phpbb/viewtopic.php?f=8&t=478&p=2087\n\nWould you like to setup a USB drive now?'
-			whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --backtitle "$WHIP_BACKTITLE" --defaultno 21 70
-			CHOICE=$?
-			if (( $CHOICE == 0 )); then
+			#Request for Dedicated External Drive installation.
+			if (( $USBDRIVE == 0 && $HW_MODEL != 20 )); then
+				WHIP_TITLE='Setup USB Dedicated Drive?'
+				WHIP_QUESTION='If you choose to setup a dedicated USB drive, DietPi will automatically configure your future software installations to utilize the USB drive for user data storage, instead of SD.\nAs USB hard drives can be faster than most SD cards, using a USB drive can vastly improve system performance.\n\nExamples of software, that will benefit from a USB drive: \n - BitTorrent (Store downloads) \n - OwnCloud (Larger data storage)\n - Kodi / Plex / Emby etc (Store Media Files)\n\nMore information on user data in DietPi:\n - http://dietpi.com/phpbb/viewtopic.php?f=8&t=478&p=2087\n\nWould you like to setup a USB drive now?'
+				whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --backtitle "$WHIP_BACKTITLE" --defaultno 21 70
+				CHOICE=$?
+				if (( $CHOICE == 0 )); then
 
-				# XENFOMATION: Place holder to wrap up 2 USB dedicated drives
+					# XENFOMATION: Place holder to wrap up 2 USB dedicated drives
 
-				#Run external drive setup script
-				/DietPi/dietpi/dietpi-external_drive_setup
+					#Run external drive setup script
+					/DietPi/dietpi/dietpi-external_drive_setup
 
+				fi
 			fi
-		fi
 
-		#Questions End
-		if (( $AUTOINSTALL_SKIPQUESTIONS == 0 )) &&
-			(( $AUTOINSTALL_INDEX == 0 )); then
-			WHIP_TITLE='DietPi - Questions Completed'
-			whiptail --title "$WHIP_TITLE" --msgbox "The DietPi-Software menu will now appear with the following options: \n\n- Select DietPi Optimized Software\nThis will allow you to select Optimized and Ready to Run software.\nhttp://dietpi.com/software\n\n- Select Additional Linux Software.\nThis will allow you to select standard linux software relative to this installation. \n\n- DietPi-Config\nA feature rich configuration tool for your device.\n \n- Go Start Install\nThis will start the installation process for your selected items." 21 75
+			#Questions End
+			if (( $AUTOINSTALL_INDEX == 0 )); then
+				WHIP_TITLE='DietPi - Questions Completed'
+				whiptail --title "$WHIP_TITLE" --msgbox "The DietPi-Software menu will now appear with the following options: \n\n- Select DietPi Optimized Software\nThis will allow you to select Optimized and Ready to Run software.\nhttp://dietpi.com/software\n\n- Select Additional Linux Software.\nThis will allow you to select standard linux software relative to this installation. \n\n- DietPi-Config\nA feature rich configuration tool for your device.\n \n- Go Start Install\nThis will start the installation process for your selected items." 21 75
+			fi
+
 		fi
 
 	}
@@ -6208,10 +6146,15 @@ systemctl daemon-reload
 	Error_Display(){
 
 		#Automation | Save to logfile if errors are being ignored
-		if (( $DIETPI_INSTALL_STAGE == 0 )) && (( $AUTOINSTALL_IGNOREERRORS == 1 )); then
-			echo -e "Error: $ERROR_TEXT" >> "$FP_DIETPIAUTOMATION_LOG"
-		else
+
+		if (( $USER_INPUTS )); then
+
 			whiptail --title "Error" --msgbox "$ERROR_TEXT" 16 70
+
+		else
+
+			echo -e "Error: $ERROR_TEXT" >> "$FP_DIETPIAUTOMATION_LOG"
+
 		fi
 
 	}
@@ -9069,27 +9012,42 @@ systemctl daemon-reload
 	# Banner Print
 	#/////////////////////////////////////////////////////////////////////////////////////
 	Banner_Setup(){
+
 		/DietPi/dietpi/dietpi-banner 0
 		echo -e "\n DietPi-Software \n"
+
 	}
 
 	Banner_Installing(){
+
 		/DietPi/dietpi/dietpi-banner 0
 		echo -e "\n Installing Software: $INSTALL_DESCRIPTION \n Please Wait, this may take some time... \n "
 		/DietPi/dietpi/dietpi-funtime 0
+
 	}
 
 	Banner_Apt_Update(){
+
 		/DietPi/dietpi/dietpi-banner 0
 		echo -e "\n Please Wait: \n Updating and Upgrading APT, this may take some time... \n"
 		sleep 1
+
 	}
 
 	Banner_Reboot(){
-		/DietPi/dietpi/dietpi-banner 0
-		echo -e "\n The system will now reboot. \n This completes the DietPi-Software installation.\n"
-		/DietPi/dietpi/dietpi-funtime 0
-		sleep 3
+
+		if (( ! $DISABLE_REBOOT )); then
+
+			/DietPi/dietpi/dietpi-banner 0
+			echo -e "\n The system will now reboot. \n This completes the DietPi-Software installation.\n"
+			/DietPi/dietpi/dietpi-funtime 0
+			sleep 3
+
+		else
+
+			/DietPi/dietpi/func/dietpi-notify 0 "Installation completed."
+
+		fi
 	}
 
 	Banner_Configs(){
@@ -9109,9 +9067,70 @@ systemctl daemon-reload
 		fi
 	}
 
+	Input_Modes(){
+
+		# - Skip menu
+		TARGETMENUID=-1
+
+		local ainput=("$@")
+
+		#Install software and exit.
+		if [ "$1" = "install" ]; then
+
+			GOSTARTINSTALL=1
+
+			DISABLE_REBOOT=1
+
+			# - Disable all user inputs/prompts
+			USER_INPUTS=0
+
+			for i in "${ainput[@]}" # NB: need a way to skip the 1st entry. Could do if != install, but rather find a better method.
+			do
+
+				# - grab the name to use in sed pattern match
+				local target_name=$(echo -e "$i" | cut -f1 -d "=")
+				target_name+='='
+
+				# - grab the target value
+				local target_value=$(echo -e "$i" | sed 's/.*=//')
+				#	If input doesnt contain a "=" , Assume user wants to install it and add "=1". Saves us having to use KODI=1, where KODI will do the same.
+				#	NB: we must ensure "INDEX_*_TARGET" entries have a value eg: "=-1"
+				if (( ! $(echo -e "$target_value" | grep -ci -m1 '=') )); then
+
+					target_value+="=1"
+
+				fi
+
+				sed -i "/^$target_name/c $target_name$target_value" "$FP_INSTALLED_FILE"
+
+			done
+
+			Read_InstallFileList
+
+		else
+
+			/DietPi/dietpi/func/dietpi-notify 2 "Unknown command $1"
+
+			unset ainput
+
+			exit
+
+		fi
+
+		unset ainput
+
+	}
+
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Main Loop
 	#/////////////////////////////////////////////////////////////////////////////////////
+	#--------------------------------------------------------------------------------------
+	#GPL compliance prompt
+	if (( $DIETPI_INSTALL_STAGE == 0 && $USER_INPUTS )); then
+
+		whiptail --title "DietPi - GPLv2 License" --msgbox "This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or any later version.\n\nThis program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this program.  If not, see http://www.gnu.org/licenses/" --backtitle "DietPi - GPLv2 Compliance" 18 70
+
+	fi
 	#--------------------------------------------------------------------------------------
 	Banner_Setup
 
@@ -9124,7 +9143,9 @@ systemctl daemon-reload
 	#Check for DietPi updates on 1st run
 	#NB: Contains EXIT path
 	if (( $(cat /DietPi/dietpi/.update_stage) == -1 )); then
+
 		FirstRun_DietPi_Update
+
 	fi
 
 	clear
@@ -9151,6 +9172,18 @@ systemctl daemon-reload
 	#--------------------------------------------------------------------------------------
 	#Enable USBDRIVE flag for this system if its mounted/available.
 	Dedicated_Usb_Drive_Enable
+
+	#--------------------------------------------------------------------------------------
+	#Input mode
+	if (( $DIETPI_INSTALL_STAGE >= 1 )); then
+
+		if [ -n "$1" ]; then
+
+			Input_Modes "$@"
+
+		fi
+
+	fi
 
 	#--------------------------------------------------------------------------------------
 	#Start DietPi Menu
@@ -9184,7 +9217,12 @@ systemctl daemon-reload
 
 			#Reboot
 			Banner_Reboot
-			reboot
+
+			if (( ! $DISABLE_REBOOT )); then
+
+				reboot
+
+			fi
 
 		fi
 
