v6.15
+ General cleanup
+ Dietpi-sync more like dietpi-backup rsync options
+ new save file for dietpi-sync

https://github.com/Fourdee/DietPi/issues/2044#issuecomment-417088505

diff --git a/dietpi/dietpi-backup b/dietpi/dietpi-backup
--- a/dietpi/dietpi-backup
+++ b/dietpi/dietpi-backup
@@ -35,263 +35,6 @@
 	disable_error=1 G_CHECK_VALIDINT $1 && INPUT=$1
 
 	#/////////////////////////////////////////////////////////////////////////////////////
-	# MENUS
-	#/////////////////////////////////////////////////////////////////////////////////////
-	MENU_LASTITEM=''
-	TARGETMENUID=0
-
-	EXIT_CODE=-1 #Used for 1 time automated running only (eg: G_BACKUP)
-
-	#TARGETMENUID=0
-	Menu_Main(){
-
-		local backup_last_completed='Backup not found. Please create one.'
-
-		G_WHIP_MENU_ARRAY=()
-		G_WHIP_MENU_ARRAY+=('Help' 'What does DietPi-Backup do?')
-		G_WHIP_MENU_ARRAY+=('' '●─ Options ')
-		G_WHIP_MENU_ARRAY+=('Location' ': Change where your backup will be saved and restored from.')
-		G_WHIP_MENU_ARRAY+=('Custom Filters' ': Modify custom include/exclude filters for backups.')
-		if [[ -f $FP_TARGET_BACKUP'/'$BACKUP_STATS_FILENAME ]]; then
-
-			G_WHIP_MENU_ARRAY+=('Delete' ": Remove backup ($FP_TARGET_BACKUP)")
-			backup_last_completed=$(grep 'Completed' "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME" | tail -1)
-
-		fi
-		G_WHIP_MENU_ARRAY+=('' '●─ Run ')
-		G_WHIP_MENU_ARRAY+=('Backup' 'Create (or update) a backup of this device.')
-		G_WHIP_MENU_ARRAY+=('Restore' 'Restore this device from a previous backup.')
-
-		G_WHIP_DEFAULT_ITEM="$MENU_LASTITEM"
-		G_WHIP_BUTTON_CANCEL_TEXT='Exit'
-		G_WHIP_MENU "Current backup and restore location:\n - $FP_TARGET_BACKUP\n - $backup_last_completed"
-		if (( $? == 0 )); then
-
-			MENU_LASTITEM="$G_WHIP_RETURNED_VALUE"
-
-			case "$G_WHIP_RETURNED_VALUE" in
-
-				'Location')
-
-					TARGETMENUID=1
-
-				;;
-
-				'Custom Filters')
-
-					nano $FP_USER_FILTER_INCLUDE_EXCLUDE_BACKUP
-
-				;;
-
-				'Help')
-
-					G_WHIP_MSG "DietPi-Backup is a program that allows you to Backup and Restore your DietPi system.\n\nIf you have broken your system, or want to reset your system to an earlier date, this can all be done with DietPi-Backup.\n\nSimply choose a location where you want to save and restore your backups from, then, select Backup or Restore.\n\nMore information:\n - https://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=256#p255"
-
-				;;
-
-				'Delete')
-
-					G_WHIP_YESNO "Do you wish to DELETE the following backup?\n - $FP_TARGET_BACKUP"
-					if (( $? == 0 )); then
-
-						rm -R "$FP_TARGET_BACKUP"
-
-					fi
-
-				;;
-
-				'Backup')
-
-					G_WHIP_YESNO "The $text_start_mode_desc will be backed up to:\n$FP_TARGET_BACKUP\n\nDo you wish to continue and start the backup?"
-					if (( $? == 0 )); then
-
-						Run_Backup
-
-					fi
-
-				;;
-
-				'Restore')
-
-					G_WHIP_YESNO "The $text_start_mode_desc will be restored from:\n$FP_TARGET_BACKUP\n\nDo you wish to continue and start the restore?"
-					if (( $? == 0 )); then
-
-						Run_Restore
-
-					fi
-
-				;;
-
-			esac
-
-		else
-
-			Menu_Exit
-
-		fi
-
-	}
-
-	Menu_Exit(){
-
-		G_WHIP_SIZE_X_MAX=50
-		G_WHIP_YESNO "Exit $G_PROGRAM_NAME?"
-		if (( $? == 0 )); then
-
-			EXIT_CODE=0
-			TARGETMENUID=-1
-
-		fi
-
-	}
-
-	#TARGETMENUID=1
-	Menu_Set_Directory(){
-
-		local current_directory="$FP_TARGET_BACKUP"
-
-		G_WHIP_MENU_ARRAY=(
-
-			'Search' 'Find previous backups in /mnt/*'
-			'List' 'Select from a list of available mounts/drives'
-			'Manual' 'Manually type a directory to use.'
-
-		)
-
-		G_WHIP_MENU "Please select the location where the backup will be saved, and restored from.\n\nYour current location:\n$FP_TARGET_BACKUP"
-		if (( $? == 0 )); then
-
-			case "$G_WHIP_RETURNED_VALUE" in
-
-				'Search')
-
-					local fp_search_results="/tmp/.dietpi-backup_search_results"
-					echo -e "\n\nSearching /mnt/* for previous backups, please wait... \n \n"
-					find /mnt -type f -name "$BACKUP_STATS_FILENAME" > "$fp_search_results"
-
-					#Do we have any results?
-					if (( $(cat "$fp_search_results" | wc -l) > 0 )); then
-
-						readarray search_results_list < "$fp_search_results"
-						#Create List for Whiptail
-						G_WHIP_MENU_ARRAY=()
-						for ((i=0; i<${#search_results_list[@]}; i++))
-						do
-
-							local last_backup_date=$( grep 'Completed' ${search_results_list[$i]} | tail -1 | sed 's/.*: //' ) # Date of last backup for this backup
-							local backup_directory=$( echo -e ${search_results_list[$i]} | sed 's/\/'"$BACKUP_STATS_FILENAME"'//g' ) # Backup directory (minus the backup file), that we can use for target backup directory.
-							G_WHIP_MENU_ARRAY+=("$backup_directory" ": $last_backup_date")
-
-						done
-
-						G_WHIP_MENU 'Please select a previous backup to use:'
-						if (( $? == 0 )); then
-
-							FP_TARGET_BACKUP="$G_WHIP_RETURNED_VALUE"
-
-						fi
-
-						#delete[] array
-						unset search_results_list
-						rm "$fp_search_results" &> /dev/null
-
-					else
-
-						G_WHIP_MSG 'No previous backups were found in /mnt/*'
-
-					fi
-
-				;;
-
-				'Manual')
-
-					Input_User_Directory
-
-				;;
-
-				'List')
-
-					/DietPi/dietpi/dietpi-drive_manager 1
-					FP_TARGET_BACKUP="$(cat /tmp/dietpi-drive_manager_selmnt)"
-					if [[ $FP_TARGET_BACKUP == '/' ]]; then
-
-						FP_TARGET_BACKUP='/mnt'
-
-					fi
-
-					FP_TARGET_BACKUP+='/dietpi-backup'
-
-				;;
-
-			esac
-
-		else
-
-			#Return to main menu
-			TARGETMENUID=0
-
-		fi
-
-		Check_Supported_Directory_Location
-		# - Not supported, reset directory target to previous
-		if (( ! $TARGET_DIRECTORY_SUPPORTED )); then
-
-			FP_TARGET_BACKUP="$current_directory"
-
-		fi
-
-	}
-
-	Input_User_Directory(){
-
-		G_WHIP_DEFAULT_ITEM="$FP_TARGET_BACKUP"
-		G_WHIP_INPUTBOX "Please enter the filepath to your directory. \neg: /mnt/dietpi-backup\n - Must be located inside /mnt/* \n - Must be symlink compatible filesystem (ext2/3/4)"
-		if (( $? == 0 )); then
-
-			FP_TARGET_BACKUP="$G_WHIP_RETURNED_VALUE"
-
-		fi
-
-	}
-
-	#/////////////////////////////////////////////////////////////////////////////////////
-	# Errors
-	#/////////////////////////////////////////////////////////////////////////////////////
-	Error_Filesystem_Not_Supported(){
-
-		G_DIETPI-NOTIFY 1 "Filesystem not supported in $FP_TARGET_BACKUP"
-
-		G_WHIP_MSG "Error:\n\n$FP_TARGET_BACKUP Has a filesystem of: $TARGET_FILESYSTEM_TYPE, and is not supported.\n\nThe filesystem must be EXT2/3/4 for symlink compatibility."
-
-	}
-
-	Error_Not_Mnt_Directory(){
-
-		G_DIETPI-NOTIFY 1 "Target directory is not inside /mnt ($FP_TARGET_BACKUP)"
-
-		G_WHIP_MSG "Directory not supported:\n- $FP_TARGET_BACKUP\n\nThe location must be inside the /mnt/* directory.\n - eg: /mnt/dietpi-backup"
-
-	}
-
-	Error_DietpiUserdata_Directory(){
-
-		G_DIETPI-NOTIFY 1 "Target directory can not be contained within DietPi user data location ($FP_TARGET_BACKUP)"
-
-		G_WHIP_MSG "Directory not supported:\n- $FP_TARGET_BACKUP\n\nTarget directory can not be contained within DietPi user data location ($G_FP_DIETPI_USERDATA)"
-
-	}
-
-	Error_Rsync_Already_Running(){
-
-		G_DIETPI-NOTIFY 1 "Another Rsync process is already running."
-
-		echo -e "$RSYNC_MODE_TEXT failed: $(date +"%d-%m-%Y_%H%M"). Rsync is already running." >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
-
-		G_WHIP_MSG "$RSYNC_MODE_TEXT Error:\n\nA $RSYNC_MODE_TEXT could not be started as rsync is already running."
-
-	}
-
-	#/////////////////////////////////////////////////////////////////////////////////////
 	# Backup System
 	#/////////////////////////////////////////////////////////////////////////////////////
 	RSYNC_MODE_TEXT=0
@@ -650,6 +393,264 @@ _EOF_
 	}
 
 	#/////////////////////////////////////////////////////////////////////////////////////
+	# MENUS
+	#/////////////////////////////////////////////////////////////////////////////////////
+	MENU_LASTITEM=''
+	TARGETMENUID=0
+
+	EXIT_CODE=-1 #Used for 1 time automated running only (eg: G_BACKUP)
+
+	#TARGETMENUID=0
+	Menu_Main(){
+
+		local backup_last_completed='Backup not found. Please create one.'
+
+		G_WHIP_MENU_ARRAY=()
+		G_WHIP_MENU_ARRAY+=('' '●─ Info ')
+		G_WHIP_MENU_ARRAY+=('Help' "What does $G_PROGRAM_NAME do?")
+		G_WHIP_MENU_ARRAY+=('' '●─ Options ')
+		G_WHIP_MENU_ARRAY+=('Location' ': Change where your backup will be saved and restored from.')
+		G_WHIP_MENU_ARRAY+=('Custom Filters' ': Modify custom include/exclude filters for backups.')
+		if [[ -f $FP_TARGET_BACKUP'/'$BACKUP_STATS_FILENAME ]]; then
+
+			G_WHIP_MENU_ARRAY+=('Delete' ": Remove backup ($FP_TARGET_BACKUP)")
+			backup_last_completed=$(grep 'Completed' "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME" | tail -1)
+
+		fi
+		G_WHIP_MENU_ARRAY+=('' '●─ Run ')
+		G_WHIP_MENU_ARRAY+=('Backup' 'Create (or update) a backup of this device.')
+		G_WHIP_MENU_ARRAY+=('Restore' 'Restore this device from a previous backup.')
+
+		G_WHIP_DEFAULT_ITEM="$MENU_LASTITEM"
+		G_WHIP_BUTTON_CANCEL_TEXT='Exit'
+		G_WHIP_MENU "Current backup and restore location:\n - $FP_TARGET_BACKUP\n - $backup_last_completed"
+		if (( $? == 0 )); then
+
+			MENU_LASTITEM="$G_WHIP_RETURNED_VALUE"
+
+			case "$G_WHIP_RETURNED_VALUE" in
+
+				'Location')
+
+					TARGETMENUID=1
+
+				;;
+
+				'Custom Filters')
+
+					nano $FP_USER_FILTER_INCLUDE_EXCLUDE_BACKUP
+
+				;;
+
+				'Help')
+
+					G_WHIP_MSG "DietPi-Backup is a program that allows you to Backup and Restore your DietPi system.\n\nIf you have broken your system, or want to reset your system to an earlier date, this can all be done with DietPi-Backup.\n\nSimply choose a location where you want to save and restore your backups from, then, select Backup or Restore.\n\nMore information:\n - https://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=256#p255"
+
+				;;
+
+				'Delete')
+
+					G_WHIP_YESNO "Do you wish to DELETE the following backup?\n - $FP_TARGET_BACKUP"
+					if (( $? == 0 )); then
+
+						rm -R "$FP_TARGET_BACKUP"
+
+					fi
+
+				;;
+
+				'Backup')
+
+					G_WHIP_YESNO "The $text_start_mode_desc will be backed up to:\n$FP_TARGET_BACKUP\n\nDo you wish to continue and start the backup?"
+					if (( $? == 0 )); then
+
+						Run_Backup
+
+					fi
+
+				;;
+
+				'Restore')
+
+					G_WHIP_YESNO "The $text_start_mode_desc will be restored from:\n$FP_TARGET_BACKUP\n\nDo you wish to continue and start the restore?"
+					if (( $? == 0 )); then
+
+						Run_Restore
+
+					fi
+
+				;;
+
+			esac
+
+		else
+
+			Menu_Exit
+
+		fi
+
+	}
+
+	Menu_Exit(){
+
+		G_WHIP_SIZE_X_MAX=50
+		G_WHIP_YESNO "Exit $G_PROGRAM_NAME?"
+		if (( $? == 0 )); then
+
+			EXIT_CODE=0
+			TARGETMENUID=-1
+
+		fi
+
+	}
+
+	#TARGETMENUID=1
+	Menu_Set_Directory(){
+
+		local current_directory="$FP_TARGET_BACKUP"
+
+		G_WHIP_MENU_ARRAY=(
+
+			'Search' 'Find previous backups in /mnt/*'
+			'List' 'Select from a list of available mounts/drives'
+			'Manual' 'Manually type a directory to use.'
+
+		)
+
+		G_WHIP_MENU "Please select the location where the backup will be saved, and restored from.\n\nYour current location:\n$FP_TARGET_BACKUP"
+		if (( $? == 0 )); then
+
+			case "$G_WHIP_RETURNED_VALUE" in
+
+				'Search')
+
+					local fp_search_results="/tmp/.dietpi-backup_search_results"
+					echo -e "\n\nSearching /mnt/* for previous backups, please wait... \n \n"
+					find /mnt -type f -name "$BACKUP_STATS_FILENAME" > "$fp_search_results"
+
+					#Do we have any results?
+					if (( $(cat "$fp_search_results" | wc -l) > 0 )); then
+
+						readarray search_results_list < "$fp_search_results"
+						#Create List for Whiptail
+						G_WHIP_MENU_ARRAY=()
+						for ((i=0; i<${#search_results_list[@]}; i++))
+						do
+
+							local last_backup_date=$( grep 'Completed' ${search_results_list[$i]} | tail -1 | sed 's/.*: //' ) # Date of last backup for this backup
+							local backup_directory=$( echo -e ${search_results_list[$i]} | sed 's/\/'"$BACKUP_STATS_FILENAME"'//g' ) # Backup directory (minus the backup file), that we can use for target backup directory.
+							G_WHIP_MENU_ARRAY+=("$backup_directory" ": $last_backup_date")
+
+						done
+
+						G_WHIP_MENU 'Please select a previous backup to use:'
+						if (( $? == 0 )); then
+
+							FP_TARGET_BACKUP="$G_WHIP_RETURNED_VALUE"
+
+						fi
+
+						#delete[] array
+						unset search_results_list
+						rm "$fp_search_results" &> /dev/null
+
+					else
+
+						G_WHIP_MSG 'No previous backups were found in /mnt/*'
+
+					fi
+
+				;;
+
+				'Manual')
+
+					Input_User_Directory
+
+				;;
+
+				'List')
+
+					/DietPi/dietpi/dietpi-drive_manager 1
+					FP_TARGET_BACKUP="$(cat /tmp/dietpi-drive_manager_selmnt)"
+					if [[ $FP_TARGET_BACKUP == '/' ]]; then
+
+						FP_TARGET_BACKUP='/mnt'
+
+					fi
+
+					FP_TARGET_BACKUP+='/dietpi-backup'
+
+				;;
+
+			esac
+
+		else
+
+			#Return to main menu
+			TARGETMENUID=0
+
+		fi
+
+		Check_Supported_Directory_Location
+		# - Not supported, reset directory target to previous
+		if (( ! $TARGET_DIRECTORY_SUPPORTED )); then
+
+			FP_TARGET_BACKUP="$current_directory"
+
+		fi
+
+	}
+
+	Input_User_Directory(){
+
+		G_WHIP_DEFAULT_ITEM="$FP_TARGET_BACKUP"
+		G_WHIP_INPUTBOX "Please enter the filepath to your directory. \neg: /mnt/dietpi-backup\n - Must be located inside /mnt/* \n - Must be symlink compatible filesystem (ext2/3/4)"
+		if (( $? == 0 )); then
+
+			FP_TARGET_BACKUP="$G_WHIP_RETURNED_VALUE"
+
+		fi
+
+	}
+
+	#/////////////////////////////////////////////////////////////////////////////////////
+	# Errors
+	#/////////////////////////////////////////////////////////////////////////////////////
+	Error_Filesystem_Not_Supported(){
+
+		G_DIETPI-NOTIFY 1 "Filesystem not supported in $FP_TARGET_BACKUP"
+
+		G_WHIP_MSG "Error:\n\n$FP_TARGET_BACKUP Has a filesystem of: $TARGET_FILESYSTEM_TYPE, and is not supported.\n\nThe filesystem must be EXT2/3/4 for symlink compatibility."
+
+	}
+
+	Error_Not_Mnt_Directory(){
+
+		G_DIETPI-NOTIFY 1 "Target directory is not inside /mnt ($FP_TARGET_BACKUP)"
+
+		G_WHIP_MSG "Directory not supported:\n- $FP_TARGET_BACKUP\n\nThe location must be inside the /mnt/* directory.\n - eg: /mnt/dietpi-backup"
+
+	}
+
+	Error_DietpiUserdata_Directory(){
+
+		G_DIETPI-NOTIFY 1 "Target directory can not be contained within DietPi user data location ($FP_TARGET_BACKUP)"
+
+		G_WHIP_MSG "Directory not supported:\n- $FP_TARGET_BACKUP\n\nTarget directory can not be contained within DietPi user data location ($G_FP_DIETPI_USERDATA)"
+
+	}
+
+	Error_Rsync_Already_Running(){
+
+		G_DIETPI-NOTIFY 1 "Another Rsync process is already running."
+
+		echo -e "$RSYNC_MODE_TEXT failed: $(date +"%d-%m-%Y_%H%M"). Rsync is already running." >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME"
+
+		G_WHIP_MSG "$RSYNC_MODE_TEXT Error:\n\nA $RSYNC_MODE_TEXT could not be started as rsync is already running."
+
+	}
+
+	#/////////////////////////////////////////////////////////////////////////////////////
 	# Main Loop
 	#/////////////////////////////////////////////////////////////////////////////////////
 	#pre-reqs, install if required.
@@ -670,7 +671,7 @@ _EOF_
 	if [[ ! -f $FP_USER_FILTER_INCLUDE_EXCLUDE_BACKUP ]]; then
 
 		cat << _EOF_ > $FP_USER_FILTER_INCLUDE_EXCLUDE_BACKUP
-#DietPi-Backup | Custom include/exclude filters
+#$_PROGRAM_NAME | Custom include/exclude filters
 #
 #To INCLUDE (+) a file/folder:
 #	NB: dietpi_userdata is included by default, as well, if moved to a custom location.
@@ -724,7 +725,7 @@ _EOF_
 
 	#-----------------------------------------------------------------------------------
 	#Cleaup left over tmp files
-	rm "$FP_FILTER_INCLUDE_EXCLUDE" &> /dev/null
+	rm $FP_FILTER_INCLUDE_EXCLUDE &> /dev/null
 	#-----------------------------------------------------------------------------------
 	#delete[] array
 	unset aSUPPORTED_FILESYSTEMS
