v6.8
+ DietPi-LetsEncrypt | Syntax fix: Exit code "$?" will be overwritten by check, thus needs to be assigned to variable before check and further use.

diff --git a/dietpi/dietpi-letsencrypt b/dietpi/dietpi-letsencrypt
--- a/dietpi/dietpi-letsencrypt
+++ b/dietpi/dietpi-letsencrypt
@@ -78,10 +78,11 @@
 
 			#Cert me up Apache2
 			$FP_BINARY $options --agree-tos --rsa-key-size "$LETSENCRYPT_KEYSIZE" -m "$LETSENCRYPT_EMAIL" -d "$LETSENCRYPT_DOMAIN"
-			if (( $? )); then
+			local exit_code=$?
+			if (( $exit_code )); then
 	
-				echo -e "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..." | tee "$FP_LOGFILE"
-				(( ! $INPUT )) && G_WHIP_MSG "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..."
+				echo -e "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..." | tee "$FP_LOGFILE"
+				(( ! $INPUT )) && G_WHIP_MSG "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..."
 				return 1
 	
 			fi
@@ -95,10 +96,11 @@
 			# - Cert me up
 			/DietPi/dietpi/dietpi-services stop
 			$FP_BINARY certonly --standalone --agree-tos --rsa-key-size "$LETSENCRYPT_KEYSIZE" -m "$LETSENCRYPT_EMAIL" -d "$LETSENCRYPT_DOMAIN"
-			if (( $? )); then
+			local exit_code=$?
+			if (( $exit_code )); then
 	
-				echo -e "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..." | tee "$FP_LOGFILE"
-				(( ! $INPUT )) && G_WHIP_MSG "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..."
+				echo -e "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..." | tee "$FP_LOGFILE"
+				(( ! $INPUT )) && G_WHIP_MSG "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..."
 				return 1
 	
 			fi
@@ -202,10 +204,11 @@ _EOF_
 
 			#Cert me up Nginx
 			$FP_BINARY $options --agree-tos --rsa-key-size "$LETSENCRYPT_KEYSIZE" -m "$LETSENCRYPT_EMAIL" -d "$LETSENCRYPT_DOMAIN"
-			if (( $? )); then
+			local exit_code=$?
+			if (( $exit_code )); then
 	
-				echo -e "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..." | tee "$FP_LOGFILE"
-				(( ! $INPUT )) && G_WHIP_MSG "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..."
+				echo -e "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..." | tee "$FP_LOGFILE"
+				(( ! $INPUT )) && G_WHIP_MSG "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..."
 				return 1
 	
 			fi
@@ -219,10 +222,11 @@ _EOF_
 			# - Cert me up
 			/DietPi/dietpi/dietpi-services stop
 			$FP_BINARY certonly --standalone --staple-ocsp --agree-tos --rsa-key-size "$LETSENCRYPT_KEYSIZE" -m "$LETSENCRYPT_EMAIL" -d "$LETSENCRYPT_DOMAIN"
-			if (( $? )); then
+			local exit_code=$?
+			if (( $exit_code )); then
 	
-				echo -e "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..." | tee "$FP_LOGFILE"
-				(( ! $INPUT )) && G_WHIP_MSG "[FAILURE] CertBot failed with error code ($?), please check it's terminal output. Aborting..."
+				echo -e "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..." | tee "$FP_LOGFILE"
+				(( ! $INPUT )) && G_WHIP_MSG "[FAILURE] CertBot failed with error code ($exit_code), please check it's terminal output. Aborting..."
 				return 1
 	
 			fi
