v142
+ Halt backup/restores on failures:
https://github.com/Fourdee/DietPi/issues/685

diff --git a/dietpi/dietpi-backup b/dietpi/dietpi-backup
--- a/dietpi/dietpi-backup
+++ b/dietpi/dietpi-backup
@@ -75,7 +75,7 @@
 		fi
 
 		WHIP_TITLE='- DietPi-Backup -'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Current backup and restore location:\n  $FP_TARGET_BACKUP\n\nMost recent successful backup dates:\n  $backup_last_completed_system\n  $backup_last_completed_userdata" --cancel-button "Exit" --default-item "$MENU_LASTITEM" --backtitle "$WHIP_BACKTITLE" 18 80 5 \
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Current backup and restore location:\n - $FP_TARGET_BACKUP\n - $backup_last_completed_system\n - $backup_last_completed_userdata" --cancel-button "Exit" --default-item "$MENU_LASTITEM" --backtitle "$WHIP_BACKTITLE" 16 80 5 \
 		"Help" "What does DietPi-Backup do?" \
 		"Location" "Change where your backup will be saved and restored from." \
 		"Backup mode" ": $text_backup_mode" \
@@ -93,7 +93,7 @@
 				;;
 				"Backup mode")
 
-					OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Please select a backup mode:\n\n - System Only\nOnly the system is backed up and restored, this does not include your DietPi user data (/mnt/dietpi_userdata).\n\n - Full:\nSystem and user data (/mnt/dietpi_userdata) is backed up and restored.\n\nMore information on what DietPi user data is:\nhttp://dietpi.com/phpbb/viewtopic.php?f=8&t=478#p2087" --cancel-button "Exit" --default-item "$BACKUP_MODE" --backtitle "$WHIP_BACKTITLE" 20 80 2 \
+					OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Please select a backup mode:\n\n - System only\nOnly the system is backed up and restored, this does not include your DietPi user data (/mnt/dietpi_userdata).\n\n - Full:\nSystem and user data (/mnt/dietpi_userdata) is backed up and restored.\n\nMore information on what DietPi user data is:\nhttp://dietpi.com/phpbb/viewtopic.php?f=8&t=478#p2087" --cancel-button "Exit" --default-item "$BACKUP_MODE" --backtitle "$WHIP_BACKTITLE" 20 80 2 \
 					"0" "System only" \
 					"1" "Full (includes user data)" 3>&1 1>&2 2>&3)
 					CHOICE=$?
@@ -152,7 +152,7 @@
 		Check_Available_DietPi_Mounts
 
 		WHIP_TITLE='Select your backup and restore location'
-		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Please select the location where your system backup will be saved, and, where it can be restored from.\n\nYour current location:\n$FP_TARGET_BACKUP" --cancel-button "Back" --backtitle "$WHIP_BACKTITLE" 16 75 4 \
+		OPTION=$(whiptail --title "$WHIP_TITLE" --menu "Please select the location where your system backup will be saved, and restored from.\n\nYour current location:\n$FP_TARGET_BACKUP" --cancel-button "Back" --backtitle "$WHIP_BACKTITLE" 16 75 4 \
 		"Search" "Find previous backups in /mnt/*" \
 		"Manual" "Manually type a directory to use." \
 		"USB HDD" "$USB_DRIVE_TEXT" 3>&1 1>&2 2>&3)
@@ -173,7 +173,7 @@
 						local search_results_whiptail=()
 						for ((i=0; i<${#search_results_list[@]}; i++))
 						do
-							local last_backup_date=$( grep '^Backup Completed' ${search_results_list[$i]} | tail -1 | awk '{print $3}' ) # Date of last backup for this backup
+							local last_backup_date=$( grep 'Completed' ${search_results_list[$i]} | tail -1 | sed 's/.*: //' ) # Date of last backup for this backup
 							local backup_directory=$( echo -e ${search_results_list[$i]} | sed 's/\/'"$BACKUP_STATS_FILENAME_SYSTEM"'//g' ) # Backup directory (minus the backup file), that we can use for target backup directory.
 							search_results_whiptail+=("$backup_directory" ": $last_backup_date")
 						done
@@ -281,7 +281,6 @@
 
 		/DietPi/dietpi/func/dietpi-notify 1 "$RSYNC_MODE_TEXT failed."
 
-		echo -e "$RSYNC_MODE_TEXT Failed: $(date +"%d-%m-%Y_%H%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
 		#Menu
 		if (( $INPUT == 0 )); then
 			whiptail --title "$RSYNC_MODE_TEXT failed" --msgbox "Your $RSYNC_MODE_TEXT has failed. Please see the Log file for more information:\n\n$LOGFILE" --backtitle "$WHIP_BACKTITLE" 12 60
@@ -332,8 +331,14 @@
 	RSYNC_RUN_OPTIONS_USERDATA_BACKUP="-alHpvP --delete --log-file=$LOGFILE"
 
 	#Sucessful backup/restore states
-	BACKUP_RESTORE_SYSTEM_SUCCESS=0
-	BACKUP_RESTORE_USERDATA_SUCCESS=0
+	BACKUP_RESTORE_FAILED=0
+
+	#Date format for logs
+	Print_Date(){
+
+		echo -e "$(date +"%d-%m-%Y %H:%M")"
+
+	}
 
 	Create_Filter_Include_Exclude(){
 
@@ -383,6 +388,7 @@ _EOF_
 - $LOGFILE
 - $FP_DIETPIBACKUP_SETTINGS
 - $BACKUP_STATS_FILENAME_SYSTEM
+- $BACKUP_STATS_FILENAME_USERDATA
 - /var/swap
 - fake-hwclock.data
 - *.tmp
@@ -458,48 +464,63 @@ _EOF_
 
 				/DietPi/dietpi/func/dietpi-notify 2 "Backing up to: $FP_TARGET_BACKUP"
 
-				# - system
-				RSYNC_MODE_TEXT='Backup (system)'
-				BACKUP_RESTORE_SYSTEM_SUCCESS=1
+				BACKUP_RESTORE_FAILED=0
 
-				rsync $RSYNC_RUN_OPTIONS_SYSTEM_BACKUP "$FP_SOURCE_SYSTEM" "$FP_TARGET_BACKUP"/dietpi-backup_system/
-				if (( $? == 0 )); then
+				while true
+				do
 
+					# - system
+					RSYNC_MODE_TEXT='Backup (system)'
 
-					/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
-					echo -e "$RSYNC_MODE_TEXT Completed    : $(date +"%d-%m-%Y %H:%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
-
-				else
-
-					BACKUP_RESTORE_SYSTEM_SUCCESS=0
-					Error_Rsync_Failed
-
-				fi
-
-				# - userdata
-				RSYNC_MODE_TEXT='Backup (user data)'
-				BACKUP_RESTORE_USERDATA_SUCCESS=1
-
-				if (( $BACKUP_MODE == 1 )); then
-
-					rsync $RSYNC_RUN_OPTIONS_USERDATA_BACKUP "$FP_SOURCE_USERDATA_ACTUAL"/ "$FP_TARGET_BACKUP"/dietpi-backup_userdata/
+					rsync $RSYNC_RUN_OPTIONS_SYSTEM_BACKUP "$FP_SOURCE_SYSTEM" "$FP_TARGET_BACKUP"/dietpi-backup_system/
 					if (( $? == 0 )); then
 
 
 						/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
-						echo -e "$RSYNC_MODE_TEXT Completed : $(date +"%d-%m-%Y %H:%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
+						echo -e "$RSYNC_MODE_TEXT Completed    : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
 
 					else
 
-						Error_Rsync_Failed
-						BACKUP_RESTORE_USERDATA_SUCCESS=0
+						/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT FAILED.\n"
+						echo -e "$RSYNC_MODE_TEXT FAILED       : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
+						BACKUP_RESTORE_FAILED=1
+						break
 
 					fi
 
-				fi
+					# - userdata
+					RSYNC_MODE_TEXT='Backup (user data)'
 
-				RSYNC_MODE_TEXT='Backup'
-				if (( $BACKUP_RESTORE_SYSTEM_SUCCESS && $BACKUP_RESTORE_USERDATA_SUCCESS )); then
+					if (( $BACKUP_MODE == 1 )); then
+
+						rsync $RSYNC_RUN_OPTIONS_USERDATA_BACKUP "$FP_SOURCE_USERDATA_ACTUAL"/ "$FP_TARGET_BACKUP"/dietpi-backup_userdata/
+						if (( $? == 0 )); then
+
+
+							/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
+							echo -e "$RSYNC_MODE_TEXT Completed : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
+
+						else
+
+							/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT FAILED.\n"
+							echo -e "$RSYNC_MODE_TEXT FAILED    : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
+							BACKUP_RESTORE_FAILED=1
+							break
+
+						fi
+
+					fi
+
+					# - done
+					break
+
+				done
+
+				if (( $BACKUP_RESTORE_FAILED )); then
+
+					Error_Rsync_Failed
+
+				else
 
 					if (( $INPUT == 0 )); then
 
@@ -555,50 +576,65 @@ _EOF_
 
 				/DietPi/dietpi/func/dietpi-notify 2 "Restoring from: $FP_TARGET_BACKUP"
 
-				# - System
-				RSYNC_MODE_TEXT='Restore (system)'
-				BACKUP_RESTORE_SYSTEM_SUCCESS=1
+				BACKUP_RESTORE_FAILED=0
 
-				rsync $RSYNC_RUN_OPTIONS_SYSTEM_BACKUP "$FP_TARGET_BACKUP"/dietpi-backup_system/ "$FP_SOURCE_SYSTEM"
-				if (( $? == 0 )); then
+				while true
+				do
 
-					/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
-					echo -e "$RSYNC_MODE_TEXT Completed    : $(date +"%d-%m-%Y %H:%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
+					# - System
+					RSYNC_MODE_TEXT='Restore (system)'
 
-				else
-
-					BACKUP_RESTORE_SYSTEM_SUCCESS=0
-					Error_Rsync_Failed
-
-				fi
-
-				# - User data
-				RSYNC_MODE_TEXT='Restore (user data)'
-				BACKUP_RESTORE_USERDATA_SUCCESS=1
-
-				if (( $BACKUP_MODE == 1 )); then
-
-					rsync $RSYNC_RUN_OPTIONS_USERDATA_BACKUP "$FP_TARGET_BACKUP"/dietpi-backup_userdata/ "$FP_SOURCE_USERDATA_ACTUAL"/
+					rsync $RSYNC_RUN_OPTIONS_SYSTEM_BACKUP "$FP_TARGET_BACKUP"/dietpi-backup_system/ "$FP_SOURCE_SYSTEM"
 					if (( $? == 0 )); then
 
 						/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
-						echo -e "$RSYNC_MODE_TEXT Completed : $(date +"%d-%m-%Y %H:%M")" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
+						echo -e "$RSYNC_MODE_TEXT Completed    : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
 
 					else
 
-						BACKUP_RESTORE_USERDATA_SUCCESS=0
-						Error_Rsync_Failed
+						/DietPi/dietpi/func/dietpi-notify 1 "$RSYNC_MODE_TEXT FAILED.\n"
+						echo -e "$RSYNC_MODE_TEXT FAILED       : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_SYSTEM"
+						BACKUP_RESTORE_FAILED=1
+						break
 
 					fi
 
-				fi
+					# - User data
+					RSYNC_MODE_TEXT='Restore (user data)'
 
-				RSYNC_MODE_TEXT='Restore'
-				if (( $BACKUP_RESTORE_SYSTEM_SUCCESS && $BACKUP_RESTORE_USERDATA_SUCCESS )); then
+					if (( $BACKUP_MODE == 1 )); then
+
+						rsync $RSYNC_RUN_OPTIONS_USERDATA_BACKUP "$FP_TARGET_BACKUP"/dietpi-backup_userdata/ "$FP_SOURCE_USERDATA_ACTUAL"/
+						if (( $? == 0 )); then
+
+							/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT Completed.\n"
+							echo -e "$RSYNC_MODE_TEXT Completed : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
+
+						else
+
+							/DietPi/dietpi/func/dietpi-notify 0 "$RSYNC_MODE_TEXT FAILED.\n"
+							echo -e "$RSYNC_MODE_TEXT FAILED    : $(Print_Date)" >> "$FP_TARGET_BACKUP/$BACKUP_STATS_FILENAME_USERDATA"
+							BACKUP_RESTORE_FAILED=1
+							break
+
+						fi
+
+					fi
+
+					# - done
+					break
+
+				done
+
+				if (( $BACKUP_RESTORE_FAILED )); then
+
+					Error_Rsync_Failed
+
+				else
 
 					if (( $INPUT == 0 )); then
 
-						whiptail --title "$RSYNC_MODE_TEXT completed" --msgbox "$RSYNC_MODE_TEXT completed from:\n$FP_TARGET_BACKUP\n\nLog file: $LOGFILE" --backtitle "$WHIP_BACKTITLE" 11 60
+						whiptail --title "$RSYNC_MODE_TEXT completed" --msgbox "$RSYNC_MODE_TEXT completed from:\n$FP_TARGET_BACKUP\n\nLog file: $LOGFILE\n\nA Reboot is required." --backtitle "$WHIP_BACKTITLE" 13 60
 
 					fi
 
