v119
+ dietpi-software | |VNC4SERVER is now split into its own install
+ VNC4SERVER and TIGHTVNCSERVER both automatically start during boot.
+ VNC now has global x/y/z/display options in dietpi.txt. Used by both
VNC4SERVER and TIGHTVNCSERVER
+ Fun with colours.

diff --git a/dietpi/dietpi-services b/dietpi/dietpi-services
--- a/dietpi/dietpi-services
+++ b/dietpi/dietpi-services
@@ -135,7 +135,7 @@
 			systemctl daemon-reload &> /dev/null
 		fi
 
-		echo -e "\n \e[32mCompleted\e[0m\n"
+		echo -e ""
 
 	#-----------------------------------------------------------------------------------
 	#start/stop/restart
@@ -143,11 +143,39 @@
 		[ "$1" = "stop" ] ||
 		[ "$1" = "restart" ]; then
 
+		#????????????????????????????????????????????????????????????????????????
+		# Although this allows for simple service control without using SystemD, we really should convert these to SystemD services. To keep everything consistent, clean, and obtain a correct exit code.
+
 		#DietPi: Non-service based control for specific dietpi-software installed programs.
 		# - Start order first
-		/etc/dietpi/dietpi-software/services/brutefir.service $1 &> /dev/null
-		/etc/dietpi/dietpi-software/services/jackd.service $1 &> /dev/null
-		/etc/dietpi/dietpi-software/services/jconvolver.service $1 &> /dev/null
+		index=0
+		aDIETPISERVICE_FP=()
+		aDIETPISERVICE_NAME=()
+		aDIETPISERVICE_NAME[$index]='BruteFIR';aDIETPISERVICE_FP[$index]='/etc/dietpi/dietpi-software/services/brutefir.service';((index++));
+		aDIETPISERVICE_NAME[$index]='JackD';aDIETPISERVICE_FP[$index]='/etc/dietpi/dietpi-software/services/jackd.service';((index++));
+		aDIETPISERVICE_NAME[$index]='Jconvolver';aDIETPISERVICE_FP[$index]='/etc/dietpi/dietpi-software/services/jconvolver.service';((index++));
+
+		for ((i=0; i<${#aDIETPISERVICE_NAME[@]}; i++))
+		do
+
+			if [ -f ${aDIETPISERVICE_FP[$i]} ]; then
+
+				echo -e "${aDIETPISERVICE_NAME[$i]}"
+
+				${aDIETPISERVICE_FP[$i]} $1 &> /dev/null
+				if (( $? == 0 )); then
+					echo -e "\e[1A\e[32mOk\e[0m \e[90m|\e[0m ${aDIETPISERVICE_NAME[$i]}"
+				else
+					echo -e "\e[1A\e[31Failed\e[0m \e[90m|\e[0m ${aDIETPISERVICE_NAME[$i]}"
+				fi
+
+			fi
+
+		done
+
+		unset aDIETPISERVICE_NAME
+		unset aDIETPISERVICE_FP
+		#????????????????????????????????????????????????????????????????????????
 
 		#Check if service name is available on system.
 		Populate_Available_Array
@@ -179,14 +207,42 @@
 
 		done
 
+		#????????????????????????????????????????????????????????????????????????
+		# Although this allows for simple service control without using SystemD, we really should convert these to SystemD services. To keep everything consistent, clean, and obtain a correct exit code.
+
 		#DietPi: Non-service based control for specific dietpi-software installed programs.
 		# - Start prority last
-		/etc/dietpi/dietpi-software/services/raspimjpeg.service $1 &> /dev/null
-		/etc/dietpi/dietpi-software/services/deluge.service $1 &> /dev/null
-		/etc/dietpi/dietpi-software/services/squeezeboxserver.service $1 &> /dev/null
-		/etc/dietpi/dietpi-software/services/openbazaar-server.service $1 &> /dev/null
+		index=0
+		aDIETPISERVICE_FP=()
+		aDIETPISERVICE_NAME=()
+		aDIETPISERVICE_NAME[$index]='RaspimJpeg';aDIETPISERVICE_FP[$index]='/etc/dietpi/dietpi-software/services/raspimjpeg.service';((index++));
+		aDIETPISERVICE_NAME[$index]='Deluge';aDIETPISERVICE_FP[$index]='/etc/dietpi/dietpi-software/services/deluge.service';((index++));
+		aDIETPISERVICE_NAME[$index]='SqueezeBox Server';aDIETPISERVICE_FP[$index]='/etc/dietpi/dietpi-software/services/squeezeboxserver.service';((index++));
+		aDIETPISERVICE_NAME[$index]='OpenBazaar';aDIETPISERVICE_FP[$index]='/etc/dietpi/dietpi-software/services/openbazaar-server.service';((index++));
 
-		echo -e "\n \e[32mCompleted\e[0m\n"
+		for ((i=0; i<${#aDIETPISERVICE_NAME[@]}; i++))
+		do
+
+			if [ -f ${aDIETPISERVICE_FP[$i]} ]; then
+
+				echo -e "${aDIETPISERVICE_NAME[$i]}"
+
+				${aDIETPISERVICE_FP[$i]} $1 &> /dev/null
+				if (( $? == 0 )); then
+					echo -e "\e[1A\e[32mOk\e[0m \e[90m|\e[0m ${aDIETPISERVICE_NAME[$i]}"
+				else
+					echo -e "\e[1A\e[31Failed\e[0m \e[90m|\e[0m ${aDIETPISERVICE_NAME[$i]}"
+				fi
+
+			fi
+
+		done
+
+		unset aDIETPISERVICE_NAME
+		unset aDIETPISERVICE_FP
+		#????????????????????????????????????????????????????????????????????????
+
+		echo -e ""
 
 		#Apply process tool settings
 		if [ "$1" = "start" ] ||
