v58
Finalization of v58.

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -270,7 +270,7 @@
 		#WEBSERVER_APACHE
 		if (( $WEBSERVER_APACHE == 1 )); then
 		
-			INSTALL_DESCRIPTION='(Apache2) / MySql / Php'
+			INSTALL_DESCRIPTION='LAMP: (Apache2) / MySql / Php'
 			Banner_Installing
 			apt-get install apache2 -y
 		fi
@@ -278,7 +278,7 @@
 		#WEBSERVER_NGINX
 		if (( $WEBSERVER_NGINX == 1 )); then
 		
-			INSTALL_DESCRIPTION='(Nginx) / MySql / Php'
+			INSTALL_DESCRIPTION='LEMP: (Nginx) / MySql / Php'
 			Banner_Installing
 			apt-get install nginx xml-core --no-install-recommends -y
 		fi
@@ -287,9 +287,9 @@
 		#WEBSERVER_MYSQL
 		if (( $WEBSERVER_MYSQL == 1 )); then
 			if (( $WEBSERVER_APACHE == 1 )); then
-				INSTALL_DESCRIPTION='Apache2 / (MySql) / Php'
+				INSTALL_DESCRIPTION='LAMP: Apache2 / (MySql) / Php'
 			elif (( $WEBSERVER_NGINX == 1 )); then
-				INSTALL_DESCRIPTION='Nginx / (MySql) / Php'
+				INSTALL_DESCRIPTION='LEMP: Nginx / (MySql) / Php'
 			fi
 			Banner_Installing
 			apt-get install mysql-server -y
@@ -298,12 +298,12 @@
 		#WEBSERVER_PHP
 		if (( $WEBSERVER_PHP == 1 )); then
 			if (( $WEBSERVER_APACHE == 1 )); then
-				INSTALL_DESCRIPTION='Apache2 / MySql / (Php)'
+				INSTALL_DESCRIPTION='LAMP: Apache2 / MySql / (Php)'
 				Banner_Installing
 				apt-get install php5 libapache2-mod-php5 -y
 				
 			elif (( $WEBSERVER_NGINX == 1 )); then
-				INSTALL_DESCRIPTION='Nginx / MySql / (Php)'
+				INSTALL_DESCRIPTION='LEMP: Nginx / MySql / (Php)'
 				Banner_Installing
 				apt-get install php5-fpm php5-mysql -y
 			fi
@@ -319,15 +319,24 @@
 
 		#WEBSERVER_PHPMYADMIN
 		if (( $WEBSERVER_PHPMYADMIN == 1 )); then
-			INSTALL_DESCRIPTION='PhpMyAdmin'
+			INSTALL_DESCRIPTION='phpMyAdmin'
 			Banner_Installing
+			
+			#Mysql must be running during install to allow debconf setup.
+			service mysql start &> /dev/null
+
 			apt-get install phpmyadmin -y
+
 		fi
 			
 		#Forums PHPBB
 		if (( $PHPBB == 1 )); then
 			INSTALL_DESCRIPTION='PHPbb3 Forums'
 			Banner_Installing
+			
+			#Mysql must be running during install to allow debconf setup.
+			service mysql start &> /dev/null
+	
 			apt-get install phpbb3 -y
 		fi
 
@@ -336,6 +345,9 @@
 			INSTALL_DESCRIPTION='OwnCloud'
 			Banner_Installing
 		
+			#Mysql must be running during install to allow debconf setup.
+			service mysql start &> /dev/null
+
 			#Debian
 			if (( $DISTRO == 1 )); then
 				apt-get install owncloud -y
@@ -849,6 +861,11 @@
 				cp /boot/dietpi/conf/apache2_p1.conf /etc/apache2/apache2.conf
 			fi
 
+			#Workaround to prevent ramlog failing to start due to apache2.
+			#update.rcd name start/stop priorities are not being applied, needs looking into.
+			#In the mean time, we will use /boot/dietpi/boot which calls dietpi-services start.
+			update-rc.d apache2 disable &> /dev/null
+
 			WEBSERVER_APACHE=2
 		fi
 			
@@ -973,7 +990,7 @@
 
 		#WEBSERVER_PHPMYADMIN
 		if (( $WEBSERVER_PHPMYADMIN == 1 )); then
-
+		
 			if (( $WEBSERVER_NGINX == 2 )); then
 				ln -s /usr/share/phpmyadmin /var/www
 			fi
@@ -1778,7 +1795,7 @@
 			"OwnCloud" "Your very own cloud (eg: dropbox)." $owncloud_w \
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
 			"LAMP" "Webserver: Apache2 / mysql / php5." $webserver_lamp_w \
-			"PhpMyAdmin" "Webserver: Optional SQL admin tools." $webserver_phpmyadmin_w \
+			"phpMyAdmin" "Webserver: Optional SQL admin tools." $webserver_phpmyadmin_w \
 			"Proftp" "Lightweight FTP and file server." $proftp_w \
 			"Samba" "File server." $smbserver_w \
 			"SoftEther" "VPN server." $vpnserver_w \
@@ -1799,9 +1816,9 @@
 			"MiniDLNA" "Media streaming server (DLNA, UPnP)." $minidlna_w \
 			"HiFi" "Web interface music / radio player." $ympd_w \
 			"Forums" "Your very own website forums (Phpbb3)." $phpbb_w \
-			"LAMP" "Webserver: Apache2 / mysql / php5." $webserver_lamp_w \
-			"LEMP" "Webserver: Nginx   / mysql / php5." $webserver_lemp_w \
-			"PhpMyAdmin" "Webserver: Optional SQL admin tools." $webserver_phpmyadmin_w \
+			"LAMP" "Webserver: Apache2 / MySql / Php." $webserver_lamp_w \
+			"LEMP" "Webserver: Nginx   / MySql / Php." $webserver_lemp_w \
+			"phpMyAdmin" "Webserver: Optional SQL admin tools." $webserver_phpmyadmin_w \
 			"Proftp" "Lightweight FTP and file server." $proftp_w \
 			"Samba" "File server." $smbserver_w \
 			"SoftEther" "VPN server." $vpnserver_w \
@@ -1891,7 +1908,7 @@
 					INSTALL_DIETPI_CHOICESMADE=true
 				fi
 			;;
-			PhpMyAdmin)
+			phpMyAdmin)
 				if (( $WEBSERVER_PHPMYADMIN == 0 )); then
 					WEBSERVER_PHPMYADMIN=1
 					INSTALL_DIETPI_CHOICESMADE=true
@@ -1927,6 +1944,27 @@
 
 		#-----------------------------------------------------------------------------
 		#Install Info/Warnings
+
+		#LEMP warning
+		if (( $WEBSERVER_LEMP == 1 )); then
+			WHIP_TITLE=' DietPi - LEMP Notice'
+			WHIP_QUESTION='DietPi LEMP (Nginx) stack uses the same folder as LAMP (Apache2) /var/www.\n\nDietPi-Software currently uses LAMP (apache2) for all web based installations (eg: owncloud/forums/etc).\n\n- WARNING:\nYou MUST ensure you do NOT have installed, or plan to install LAMP / Apache2 / Owncloud / PHPBB / DietPiCam.\n\nIf you are unsure, say No.\n\nDo you wish to continue with your LEMP selection?'
+			whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --defaultno --backtitle "$WHIP_TITLE" 19 75
+			CHOICE=$?
+			if (( $CHOICE == 0 )); then
+				WEBSERVER_LEMP=1
+			else
+				WEBSERVER_LEMP=0
+			fi
+		fi
+
+		#phpMyAdmin (only available for install if LAMP or LEMP is to be installed also.)
+		if (( $WEBSERVER_PHPMYADMIN == 1 )) && (( $WEBSERVER_LAMP == 0 )) && (( $WEBSERVER_LEMP == 0 )); then
+			WHIP_TITLE='phpMyAdmin - Requires webserver'
+			WHIP_QUESTION='phpMyAdmin cannot be installed as it requires a webserver stack.\n\nOne of the following must be either selected for install, or, already installed:\n- LAMP (Apache2). \n- LEMP (Nginx).\n\nYour phpMyAdmin selection has been removed.'
+			whiptail --title "$WHIP_TITLE" --msgbox "$WHIP_QUESTION" --backtitle "$WHIP_BACKTITLE" 15 70
+			WEBSERVER_PHPMYADMIN=0
+		fi
 
 		#oDroid c1
 		if (( $HW_MODEL == 10 )); then
@@ -1968,7 +2006,7 @@
 		if [ "$bootchoices_available" = true ]; then
 			# Set Boot Order
 			WHIP_TITLE=' DietPi - Boot Options'
-			WHIP_QUESTION=' Would you like to configure the auto boot options for DietPi? \n This will allow you to choose what program loads automatically after booting (eg: Desktop)'
+			WHIP_QUESTION='Would you like to configure the auto boot options for DietPi? \nThis will allow you to choose what program loads automatically after booting (eg: Desktop)'
 			whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --backtitle "$WHIP_TITLE" 12 62
 			CHOICE=$?
 			if (( $CHOICE == 0 )); then
