v100

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -217,9 +217,10 @@
 
 	#apt-get install
 	AGI(){
-		apt-get install -y
-		if (( $? != 0 )); then
-			whiptail --title "apt-get error" --msgbox "Apt-get has failed:\n - Error code = $?\n - Software = $INSTALL_DESCRIPTION" --backtitle "$WHIP_BACKTITLE" 13 70
+		apt-get install -y "$@"
+		local result=$?
+		if (( $result != 0 )); then
+			whiptail --title "apt-get error" --msgbox "Apt-get has failed:\n - Error code = $result\n - Software = $INSTALL_DESCRIPTION" --backtitle "$WHIP_BACKTITLE" 10 65
 		fi
 	}
 
@@ -519,7 +520,7 @@
 			INSTALL_DESCRIPTION='Desktop (LXDE)'
 			Banner_Installing
 
-			$AGI lxde upower policykit-1 iceweasel p7zip-full --no-install-recommends
+			AGI lxde upower policykit-1 iceweasel p7zip-full --no-install-recommends
 			#upower policykit-1. Needed for LXDE logout menu item to show shutdown/restart ......
 
 		fi
@@ -528,7 +529,7 @@
 		if (( $TRANSMISSION == 1 )); then
 			INSTALL_DESCRIPTION='BitTorrent (Transmission)'
 			Banner_Installing
-			$AGI transmission-daemon
+			AGI transmission-daemon
 		fi
 
 		#ProFTPd
@@ -537,14 +538,14 @@
 			Banner_Installing
 
 			echo -e "proftpd-basic shared/proftpd/inetd_or_standalone select standalone" | debconf-set-selections
-			$AGI proftpd-basic
+			AGI proftpd-basic
 		fi
 
 		#Samba Server
 		if (( $FILESERVER_SAMBA == 1 )); then
 			INSTALL_DESCRIPTION='Samba File Server'
 			Banner_Installing
-			$AGI samba samba-common-bin --no-install-recommends
+			AGI samba samba-common-bin --no-install-recommends
 
 		fi
 
@@ -553,7 +554,7 @@
 			INSTALL_DESCRIPTION='FTP Server (vsFTPD)'
 			Banner_Installing
 
-			$AGI vsftpd --no-install-recommends
+			AGI vsftpd --no-install-recommends
 
 		fi
 
@@ -562,7 +563,7 @@
 
 			INSTALL_DESCRIPTION="$info_1: ($info_2) / $info_3 / $info_4"
 			Banner_Installing
-			$AGI apache2
+			AGI apache2
 		fi
 
 		#WEBSERVER_NGINX
@@ -570,7 +571,7 @@
 
 			INSTALL_DESCRIPTION="$info_1: ($info_2) / $info_3 / $info_4"
 			Banner_Installing
-			$AGI nginx xml-core --no-install-recommends
+			AGI nginx xml-core --no-install-recommends
 		fi
 
 
@@ -582,14 +583,14 @@
 			echo -e "mysql-server mysql-server/root_password password raspberry" | debconf-set-selections
 			echo -e "mysql-server mysql-server/root_password_again password raspberry" | debconf-set-selections
 
-			$AGI mysql-server
+			AGI mysql-server
 		fi
 
 		#WEBSERVER_SQLITE
 		if (( $WEBSERVER_SQLITE == 1 )); then
 			INSTALL_DESCRIPTION="$info_1: $info_2 / ($info_3) / $info_4"
 			Banner_Installing
-			$AGI sqlite3
+			AGI sqlite3
 		fi
 
 		#WEBSERVER_PHP
@@ -599,21 +600,21 @@
 
 			#Apache2 / Nginx
 			if (( $WEBSERVER_APACHE == 1 )); then
-				$AGI php5 libapache2-mod-php5
+				AGI php5 libapache2-mod-php5
 			elif (( $WEBSERVER_NGINX == 1 )); then
-				$AGI php5-fpm
+				AGI php5-fpm
 			fi
 
 			#MySQL / SQLite
 			if (( $WEBSERVER_MYSQL == 1 )); then
-				$AGI php5-mysql
+				AGI php5-mysql
 			elif (( $WEBSERVER_SQLITE == 1 )); then
-				$AGI php5-sqlite
+				AGI php5-sqlite
 			fi
 
 			#Debian Wheezy - php-apc
 			if (( $DISTRO == 1 )); then
-				$AGI php-apc
+				AGI php-apc
 			fi
 
 		fi
@@ -635,7 +636,7 @@
 			echo -e "phpmyadmin      phpmyadmin/mysql/app-pass       password raspberry" | debconf-set-selections
 			echo -e "phpmyadmin      phpmyadmin/reconfigure-webserver        multiselect     apache2" | debconf-set-selections
 
-			$AGI phpmyadmin
+			AGI phpmyadmin
 
 		fi
 
@@ -647,7 +648,7 @@
 			#Mysql must be running during install to allow debconf setup.
 			service mysql start &> /dev/null
 
-			$AGI phpbb3
+			AGI phpbb3
 		fi
 
 		#OwnCloud
@@ -677,7 +678,7 @@
 					/DietPi/dietpi/dietpi-apt-get_update 2
 				fi
 
-				$AGI owncloud --force-yes
+				AGI owncloud --force-yes
 
 			else
 				Info_NoConnection_NoInstall
@@ -701,7 +702,7 @@
 			if (( $? == 0 )); then
 
 				#Install MPD
-				$AGI mpd libmpdclient2
+				AGI mpd libmpdclient2
 
 				#Setup ympd
 				wget "$INSTALL_URL_ADDRESS"
@@ -745,7 +746,7 @@
 						INSTALL_DESCRIPTION='Kodi (Michael Gorven Repo)'
 						Banner_Installing
 
-						$AGI kodi
+						AGI kodi
 
 					else
 						Info_NoConnection_NoInstall
@@ -758,13 +759,13 @@
 			#14.04
 			elif (( $DISTRO == 2 )); then
 
-				$AGI libcurl4-gnutls-dev --no-install-recommends
-				$AGI kodi
+				AGI libcurl4-gnutls-dev --no-install-recommends
+				AGI kodi
 
 			#Jessie
 			elif (( $DISTRO == 3 )); then
 
-				$AGI kodi
+				AGI kodi
 
 			fi
 		fi
@@ -773,7 +774,7 @@
 		if (( $MINIDLNA == 1 )); then
 			INSTALL_DESCRIPTION='DLNA/UPnP Media Server (MiniDLNA)'
 			Banner_Installing
-			$AGI minidlna
+			AGI minidlna
 		fi
 
 		#NoIp
@@ -865,7 +866,7 @@
 
 			#Install
 			if (( $? == 0 )); then
-				$AGI ibsdl1.2debian libsdl-net1.2 --no-install-recommends
+				AGI ibsdl1.2debian libsdl-net1.2 --no-install-recommends
 
 				#Download binaries and source
 				wget "$INSTALL_URL_ADDRESS"
@@ -897,7 +898,7 @@
 			if (( $? == 0 )); then
 
 				#Install pre-reqs
-				$AGI gpac motion
+				AGI gpac motion
 
 				#Get source/binaries and extract
 				wget "$INSTALL_URL_ADDRESS" -O File.zip
@@ -939,7 +940,7 @@
 		if (( $DELUGE == 1 )); then
 			INSTALL_DESCRIPTION='Deluge (BitTorrent Server, Web Interface)'
 			Banner_Installing
-			$AGI deluged deluge-web deluge-webui deluge-console
+			AGI deluged deluge-web deluge-webui deluge-console
 		fi
 
 		#GRASSHOPPER
@@ -947,7 +948,7 @@
 			INSTALL_DESCRIPTION='Grasshopper'
 			Banner_Installing
 
-			$AGI python
+			AGI python
 
 			#Download Grasshopper
 			local grasshopper_directory=$(cat /DietPi/dietpi.txt | grep -m1 'grasshopper_directory=' | sed 's/grasshopper_directory=//g')
@@ -1024,7 +1025,7 @@
 			if (( $? == 0 )); then
 
 				#Install DNS server
-				$AGI dnsmasq
+				AGI dnsmasq
 				service dnsmasq stop
 
 				#Generate PiHole Dirs
@@ -1075,15 +1076,15 @@
 			if (( $? == 0 )); then
 
 				#Install Pre-reqs
-				$AGI lame
+				AGI lame
 
 				#Java
 				# - 14.04
 				if (( $DISTRO == 2 )); then
-					$AGI oracle-java8-installer --no-install-recommends
+					AGI oracle-java8-installer --no-install-recommends
 				# - Wheezy/Jessie
 				else
-					$AGI oracle-java8-jdk
+					AGI oracle-java8-jdk
 				fi
 
 				#Install SubSonic
@@ -1131,7 +1132,7 @@
 			if (( $? == 0 )); then
 
 				#Python dev, pre-reqs
-				$AGI python-dev python-setuptools --no-install-recommends
+				AGI python-dev python-setuptools --no-install-recommends
 
 				#Install WEBIOPI
 				wget "$INSTALL_URL_ADDRESS" -O package.tar
@@ -1193,7 +1194,7 @@
 				cd haproxy-*
 
 				#Pre-reqs
-				$AGI libpcre3-dev libssl-dev
+				AGI libpcre3-dev libssl-dev
 				#Compile and install
 				#make -j "$(nproc)" TARGET=linux2628 CPU=generic USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_LINUX_SPLICE=1
 				make TARGET=linux2628 CPU=generic USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_LINUX_SPLICE=1
@@ -1278,7 +1279,7 @@
 			INSTALL_DESCRIPTION='VNC Server (Tight)'
 			Banner_Installing
 
-			$AGI tightvncserver --no-install-recommends
+			AGI tightvncserver --no-install-recommends
 
 		fi
 
@@ -1287,7 +1288,7 @@
 			INSTALL_DESCRIPTION='Fail2Ban'
 			Banner_Installing
 
-			$AGI fail2ban --no-install-recommends
+			AGI fail2ban --no-install-recommends
 
 		fi
 
@@ -1326,7 +1327,7 @@
 
 			#Install
 			if (( $? == 0 )); then
-				$AGI php5-gd
+				AGI php5-gd
 				wget "$INSTALL_URL_ADDRESS" -O package.zip
 				unzip package.zip -d /var/www/gallery
 				rm package.zip
@@ -1352,7 +1353,7 @@
 			#Install
 			if (( $? == 0 )); then
 
-				$AGI php5-curl
+				AGI php5-curl
 
 				wget "$INSTALL_URL_ADDRESS" -O package.tar
 				tar -xvf package.tar
@@ -1375,7 +1376,7 @@
 			INSTALL_DESCRIPTION='OpenVPN Server'
 			Banner_Installing
 
-			$AGI openvpn easy-rsa iptables
+			AGI openvpn easy-rsa iptables
 
 		fi
 
@@ -1389,7 +1390,7 @@
 		if (( $VIMFULL == 1 )); then
 			INSTALL_DESCRIPTION='Vim'
 			Banner_Installing
-			$AGI vim
+			AGI vim
 
 			VIMFULL=2
 		fi
@@ -1397,7 +1398,7 @@
 		if (( $SSHCLIENT == 1 )); then
 			INSTALL_DESCRIPTION='OpenSSH Client'
 			Banner_Installing
-			$AGI openssh-client
+			AGI openssh-client
 
 			SSHCLIENT=2
 		fi
@@ -1409,7 +1410,7 @@
 			#Remove Information file
 			rm /mnt/samba/readme.txt &> /dev/null
 
-			$AGI smbclient cifs-utils --no-install-recommends
+			AGI smbclient cifs-utils --no-install-recommends
 
 			SMBCLIENT=2
 		fi
@@ -1425,11 +1426,11 @@
 
 			#Wheezy
 			if (( $DISTRO == 1 )); then
-				$AGI python-rpi.gpio python3-rpi.gpio
+				AGI python-rpi.gpio python3-rpi.gpio
 
 			#Jessie - Use pip, as offical repo = python3-rpi.gpio: Depends: python3 (< 3.3) but 3.4.2-2 is to be installed
 			elif (( $DISTRO == 3 )); then
-				$AGI python3-pip
+				AGI python3-pip
 				pip3 install RPi.GPIO
 			fi
 
@@ -1456,7 +1457,7 @@
 		if (( $BUILDESSENTIAL == 1 )); then
 			INSTALL_DESCRIPTION='Build Essential'
 			Banner_Installing
-			 $AGI build-essential --no-install-recommends
+			 AGI build-essential --no-install-recommends
 
 			BUILDESSENTIAL=2
 		fi
@@ -1464,7 +1465,7 @@
 		if (( $GITCLIENT == 1 )); then
 			INSTALL_DESCRIPTION='Git'
 			Banner_Installing
-			$AGI git --no-install-recommends
+			AGI git --no-install-recommends
 
 			GITCLIENT=2
 		fi
@@ -1493,7 +1494,7 @@
 		if (( $ALSABASE == 1 )); then
 			INSTALL_DESCRIPTION='ALSA (Linux Sound System)'
 			Banner_Installing
-			$AGI alsa-base alsa-utils
+			AGI alsa-base alsa-utils
 
 			#rpi , enable HQ audio
 			sed -i '/avoid_pwm_pll=/c\avoid_pwm_pll=0' /DietPi/config.txt
@@ -1550,7 +1551,7 @@ _EOF_
 			#Xserver Prereqs (ALL)
 			INSTALL_DESCRIPTION='Xserver (Xinit / Xauth)'
 			Banner_Installing
-			$AGI xinit xauth xserver-xorg xfonts-base x11-xserver-utils x11-common x11-utils --no-install-recommends
+			AGI xinit xauth xserver-xorg xfonts-base x11-xserver-utils x11-common x11-utils --no-install-recommends
 
 			#RPI
 			if (( $HW_MODEL < 10 )); then
@@ -1559,7 +1560,7 @@ _EOF_
 
 				#Wheezy
 				if (( $DISTRO == 1 )); then
-					$AGI xserver-xorg-video-fbturbo xserver-xorg-video-fbdev  --no-install-recommends
+					AGI xserver-xorg-video-fbturbo xserver-xorg-video-fbdev  --no-install-recommends
 
 				#Jessie. Appears fbturbo is now apart of xserver-core. Either way, we dont need to install fbturbo for HW accel.
 				elif (( $DISTRO == 3 )); then
@@ -1570,7 +1571,7 @@ _EOF_
 			elif (( $HW_MODEL == 10 )); then
 				INSTALL_DESCRIPTION='Xserver (AMLogic VPU / MALI)'
 				Banner_Installing
-				$AGI xterm aml-libs mali-x11 xserver-xorg-video-mali --no-install-recommends
+				AGI xterm aml-libs mali-x11 xserver-xorg-video-mali --no-install-recommends
 
 				#cp /DietPi/dietpi/conf/xorg_c1-hk /etc/X11/xorg.conf
 
@@ -1610,7 +1611,7 @@ _EOF_
 			#Remove information file
 			rm /mnt/ftp_client/readme.txt &> /dev/null
 
-			$AGI curlftpfs
+			AGI curlftpfs
 
 			CURLFTPFS=2
 		fi
@@ -1620,7 +1621,7 @@ _EOF_
 
 			INSTALL_DESCRIPTION='Dropbear SSH Server'
 			Banner_Installing
-			$AGI dropbear
+			AGI dropbear
 
 			#set to start on next boot
 			sed -i '/NO_START=1/c\NO_START=0' /etc/default/dropbear
@@ -1633,7 +1634,7 @@ _EOF_
 
 			INSTALL_DESCRIPTION='OpenSSH Server'
 			Banner_Installing
-			$AGI openssh-server --no-install-recommends
+			AGI openssh-server --no-install-recommends
 
 			#14.04 and Jessie, must enable root login
 			if (( $DISTRO == 2 )) || (( $DISTRO == 3 )); then
@@ -1663,7 +1664,7 @@ _EOF_
 
 			INSTALL_DESCRIPTION='Logrotate'
 			Banner_Installing
-			$AGI logrotate
+			AGI logrotate
 
 			LOGGING_LOGROTATE=2
 		fi
@@ -1679,7 +1680,7 @@ _EOF_
 
 			INSTALL_DESCRIPTION='Rsyslog'
 			Banner_Installing
-			$AGI rsyslog --no-install-recommends
+			AGI rsyslog --no-install-recommends
 
 			LOGGING_RSYSLOG=2
 
@@ -1700,7 +1701,7 @@ _EOF_
 			#Wheezy
 			if (( $DISTRO == 1 )); then
 
-				$AGI ffmpeg
+				AGI ffmpeg
 
 			#Ubuntu 14.04 (Odroid's armv7)
 			elif (( $DISTRO == 2 )); then
@@ -1712,7 +1713,7 @@ _EOF_
 				#Skip Compile if binary is already installed
 				if [ ! -f /usr/local/bin/ffmpeg ]; then
 
-					$AGI build-essential libmp3lame-dev libvorbis-dev libtheora-dev libspeex-dev yasm pkg-config libfaac-dev libopenjpeg-dev libx264-dev
+					AGI build-essential libmp3lame-dev libvorbis-dev libtheora-dev libspeex-dev yasm pkg-config libfaac-dev libopenjpeg-dev libx264-dev
 
 					INSTALL_URL_ADDRESS='http://ffmpeg.org/releases/ffmpeg-2.7.2.tar.bz2'
 					wget "$INSTALL_URL_ADDRESS" -O package.tar
@@ -1749,16 +1750,16 @@ _EOF_
 					rm package.deb
 
 					#Install pre-reqs
-					$AGI libogg0 libvorbisenc2 libtheora0 libspeex1 libopencore-amrwb0 libopencore-amrnb0 libass5
+					AGI libogg0 libvorbisenc2 libtheora0 libspeex1 libopencore-amrwb0 libopencore-amrnb0 libass5
 
 				#Add Deb Multimedia repo for ffmpeg
 				elif (( $(cat /etc/apt/sources.list | grep -ci -m1 "http://www.deb-multimedia.org") == 0 )); then
 
 					echo -e "deb http://www.deb-multimedia.org jessie main non-free" >> /etc/apt/sources.list
 					/DietPi/dietpi/dietpi-apt-get_update 2
-					$AGI deb-multimedia-keyring --force-yes
+					AGI deb-multimedia-keyring --force-yes
 					/DietPi/dietpi/dietpi-apt-get_update 2
-					$AGI ffmpeg
+					AGI ffmpeg
 
 				fi
 			fi
@@ -3117,55 +3118,67 @@ _EOF_
 		if (( $memory_split_mode == 3 )); then
 
 			#odroid c1
-			sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
-			sed -i '/setenv vpu /c\setenv vpu "1"' /DietPi/boot.ini
-			sed -i '/setenv m_bpp /c\setenv m_bpp "32"' /DietPi/boot.ini
-
+			if (( $HW_MODEL == 10 )); then
+				sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
+				sed -i '/setenv vpu /c\setenv vpu "1"' /DietPi/boot.ini
+				sed -i '/setenv m_bpp /c\setenv m_bpp "32"' /DietPi/boot.ini
 			#rpi
-			sed -i '/gpu_mem_256=/c\gpu_mem_256=128' /DietPi/config.txt
-			sed -i '/gpu_mem_512=/c\gpu_mem_512=128' /DietPi/config.txt
-			sed -i '/gpu_mem_1024=/c\gpu_mem_1024=128' /DietPi/config.txt
-			sed -i "/rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt
+			elif (( $HW_MODEL < 10 )); then
+				sed -i '/gpu_mem_256=/c\gpu_mem_256=128' /DietPi/config.txt
+				sed -i '/gpu_mem_512=/c\gpu_mem_512=128' /DietPi/config.txt
+				sed -i '/gpu_mem_1024=/c\gpu_mem_1024=128' /DietPi/config.txt
+				sed -i "/rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt
+			fi
+
 		#Mode 2
 		elif (( $memory_split_mode == 2 )); then
 
 			#odroid c1
-			sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
-			sed -i '/setenv vpu /c\setenv vpu "0"' /DietPi/boot.ini
-			sed -i '/setenv m_bpp /c\setenv m_bpp "16"' /DietPi/boot.ini
-
+			if (( $HW_MODEL == 10 )); then
+				sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
+				sed -i '/setenv vpu /c\setenv vpu "0"' /DietPi/boot.ini
+				sed -i '/setenv m_bpp /c\setenv m_bpp "16"' /DietPi/boot.ini
 			#rpi
-			sed -i '/gpu_mem_256=/c\gpu_mem_256=64' /DietPi/config.txt
-			sed -i '/gpu_mem_512=/c\gpu_mem_512=64' /DietPi/config.txt
-			sed -i '/gpu_mem_1024=/c\gpu_mem_1024=64' /DietPi/config.txt
-			sed -i "/rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt
+			elif (( $HW_MODEL < 10 )); then
+				sed -i '/gpu_mem_256=/c\gpu_mem_256=64' /DietPi/config.txt
+				sed -i '/gpu_mem_512=/c\gpu_mem_512=64' /DietPi/config.txt
+				sed -i '/gpu_mem_1024=/c\gpu_mem_1024=64' /DietPi/config.txt
+				sed -i "/rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt
+			fi
+
 		#Mode 1 - DietPi-Cloudshell
 		elif (( $memory_split_mode == 1 )); then
 
 			#odroid c1
-			sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
-			sed -i '/setenv m_bpp /c\setenv m_bpp "16"' /DietPi/boot.ini
-
+			if (( $HW_MODEL == 10 )); then
+				sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
+				sed -i '/setenv m_bpp /c\setenv m_bpp "16"' /DietPi/boot.ini
 			#rpi
-			sed -i '/framebuffer_width=/c\framebuffer_width=320' /DietPi/config.txt
-			sed -i '/framebuffer_height=/c\framebuffer_height=240' /DietPi/config.txt
-			sed -i '/gpu_mem_256=/c\gpu_mem_256=16' /DietPi/config.txt
-			sed -i '/gpu_mem_512=/c\gpu_mem_512=16' /DietPi/config.txt
-			sed -i '/gpu_mem_1024=/c\gpu_mem_1024=16' /DietPi/config.txt
-			sed -i "/rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt
+			elif (( $HW_MODEL < 10 )); then
+				sed -i '/framebuffer_width=/c\framebuffer_width=320' /DietPi/config.txt
+				sed -i '/framebuffer_height=/c\framebuffer_height=240' /DietPi/config.txt
+				sed -i '/gpu_mem_256=/c\gpu_mem_256=16' /DietPi/config.txt
+				sed -i '/gpu_mem_512=/c\gpu_mem_512=16' /DietPi/config.txt
+				sed -i '/gpu_mem_1024=/c\gpu_mem_1024=16' /DietPi/config.txt
+				sed -i "/rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt
+			fi
+
 		#Mode 0
 		elif (( $memory_split_mode == 0 )); then
 
 			#odroid c1
-			#sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
-			sed -i '/setenv vpu /c\setenv vpu "0"' /DietPi/boot.ini
-			sed -i '/setenv m_bpp /c\setenv m_bpp "16"' /DietPi/boot.ini
-
+			if (( $HW_MODEL == 10 )); then
+				#sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
+				sed -i '/setenv vpu /c\setenv vpu "0"' /DietPi/boot.ini
+				sed -i '/setenv m_bpp /c\setenv m_bpp "16"' /DietPi/boot.ini
 			#rpi
-			sed -i '/gpu_mem_256=/c\gpu_mem_256=16' /DietPi/config.txt
-			sed -i '/gpu_mem_512=/c\gpu_mem_512=16' /DietPi/config.txt
-			sed -i '/gpu_mem_1024=/c\gpu_mem_1024=16' /DietPi/config.txt
-			#sed -i "/rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt
+			elif (( $HW_MODEL < 10 )); then
+				sed -i '/gpu_mem_256=/c\gpu_mem_256=16' /DietPi/config.txt
+				sed -i '/gpu_mem_512=/c\gpu_mem_512=16' /DietPi/config.txt
+				sed -i '/gpu_mem_1024=/c\gpu_mem_1024=16' /DietPi/config.txt
+				#sed -i "/rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt
+			fi
+
 		fi
 
 	}
