v8.24
- DietPi-Software | Go: Install on RISC-V via go.dev now and (hopefully) fix Gogs package build by using dev branch for this change. Purge the "golang-go" APT package in case it is installed, as its executables would override the ones in /usr/local/go/bin, which is appended to PATH, not prepanded

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -3078,31 +3078,30 @@ unix_socket_directories = '/run/postgresql'" > "$i/00dietpi.conf"
 		if To_Install 188 # Go
 		then
 			# https://go.dev/doc/install#install
-			if (( $G_HW_ARCH == 11 ))
-			then
-				G_AGI golang-go
-			else
-				case $G_HW_ARCH in
-					3) local arch='arm64';;
-					10) local arch='amd64';;
-					*) local arch='armv6l';;
-				esac
+			case $G_HW_ARCH in
+				3) local arch='arm64';;
+				10) local arch='amd64';;
+				11) local arch='riscv64';;
+				*) local arch='armv6l';;
+			esac
 
-				# Get latest version
-				local file=$(curl -sSfL 'https://go.dev/dl/?mode=json' | grep -wo "go[0-9.]*\.linux-$arch\.tar\.gz" | head -1)
-				[[ $file ]] || { file="go1.20.1.linux-$arch.tar.gz"; G_DIETPI-NOTIFY 1 "Automatic latest ${aSOFTWARE_NAME[$software_id]} version detection failed. \"$file\" will be installed as fallback, but a newer version might be available. Please report this at: https://github.com/MichaIng/DietPi/issues"; }
+			# Get latest version
+			local file=$(curl -sSfL 'https://go.dev/dl/?mode=json' | grep -wo "go[0-9.]*\.linux-$arch\.tar\.gz" | head -1)
+			[[ $file ]] || { file="go1.21.3.linux-$arch.tar.gz"; G_DIETPI-NOTIFY 1 "Automatic latest ${aSOFTWARE_NAME[$software_id]} version detection failed. \"$file\" will be installed as fallback, but a newer version might be available. Please report this at: https://github.com/MichaIng/DietPi/issues"; }
 
-				# Reinstall: Remove previous instance
-				[[ -d '/usr/local/go' ]] && G_EXEC rm -R /usr/local/go
+			# Reinstall: Remove previous instance
+			[[ -d '/usr/local/go' ]] && G_EXEC rm -R /usr/local/go
 
-				Download_Install "https://dl.google.com/go/$file" /usr/local
+			Download_Install "https://dl.google.com/go/$file" /usr/local
 
-				# Add to PATH, but do not overwrite existing script since we did set GOPATH until v8.9 and do not want to cause a breaking change for existing installs
-				# shellcheck disable=SC2016
-				[[ -f '/etc/bashrc.d/go.sh' ]] || G_EXEC eval 'echo '\''export PATH="$PATH:/usr/local/go/bin"'\'' > /etc/bashrc.d/go.sh'
-				# shellcheck disable=SC1091
-				. /etc/bashrc.d/go.sh
-			fi
+			# Add to PATH, but do not overwrite existing script since we did set GOPATH until v8.9 and do not want to cause a breaking change for existing installs
+			# shellcheck disable=SC2016
+			[[ -f '/etc/bashrc.d/go.sh' ]] || G_EXEC eval 'echo '\''export PATH="$PATH:/usr/local/go/bin"'\'' > /etc/bashrc.d/go.sh'
+			# shellcheck disable=SC1091
+			. /etc/bashrc.d/go.sh
+
+			# RISC-V pre-v8.24 and general failsafe action: Purge Go APT Package
+			dpkg-query -s 'golang-go' &> /dev/null && G_AGP golang-go
 		fi
 
 		if To_Install 170 # UnRAR
