v6.10
+ DietPi-Config | Fixed disabling IPv6 on RPi, since it is no kernel module any more

diff --git a/dietpi/dietpi-config b/dietpi/dietpi-config
--- a/dietpi/dietpi-config
+++ b/dietpi/dietpi-config
@@ -3430,9 +3430,9 @@
 							# - On amd64 images, IPv6 is no kernel module, but can be disabled via grub: https://github.com/Fourdee/DietPi/issues/1343#issuecomment-359652751
 							if (( $G_HW_ARCH == 10 )); then
 
-								if (( ! $(grep -ci -m1 'ipv6.disable=1' /etc/default/grub) )); then
+								if ! grep -qi '^[[:blank:]]*GRUB_CMDLINE_LINUX_DEFAULT=".*ipv6.disable=1' /etc/default/grub; then
 
-									sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=\"/GRUB_CMDLINE_LINUX_DEFAULT=\"ipv6.disable=1 /g' /etc/default/grub
+									sed -i '/^[[:blank:]]*GRUB_CMDLINE_LINUX_DEFAULT="/s/="/="ipv6.disable=1 /' /etc/default/grub
 									update-grub
 
 								fi
@@ -3440,6 +3440,8 @@
 							# - On all other images, IPv6 is a kernel module, which can be blacklisted.
 							else
 
+								# Since RPi kernel 4.14.y, IPv6 is no kernel module as well, but keep blacklist as fail-safe:
+								(( $G_HW_MODEL < 10 )) && sed -Ei '/root=/s/( ipv6.disable=.|$)/ ipv6.disable=1/' /boot/cmdline.txt
 								echo 'blacklist ipv6' > /etc/modprobe.d/99-dietpi-blacklist-ipv6.conf
 
 							fi
@@ -3460,11 +3462,12 @@
 
 							if (( $G_HW_ARCH == 10 )); then
 
-								sed -i 's/ipv6.disable=1 //g' /etc/default/grub
+								sed -i '/^[[:blank:]]*GRUB_CMDLINE_LINUX_DEFAULT="/s/ipv6.disable=. //' /etc/default/grub
 								update-grub
 
 							else
 
+								(( $G_HW_MODEL < 10 )) && sed -i '/root=/s/ ipv6.disable=.//' /boot/cmdline.txt
 								rm /etc/modprobe.d/99-dietpi-blacklist-ipv6.conf &> /dev/null
 
 							fi
