v7.3 (#4429)
+ DietPi-Software | AdGuard Home: This DNS sinkhole ad blocker for your LAN, similar to Pi-hole, has been added with software ID 126.
+ DietPi-Software | Lighttpd: Assure that the service is stopped on uninstall
+ DietPi-Software | Pi-hole: On uninstall, fix reverting Unbound config

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -1422,6 +1422,13 @@ INDEX_BROWSER_TARGET=$INDEX_BROWSER_TARGET"
 		aSOFTWARE_DESC[$software_id]='validating, recursive, caching DNS resolver'
 		aSOFTWARE_CATX[$software_id]=13
 		aSOFTWARE_DOCS[$software_id]='https://dietpi.com/docs/software/dns_servers/#unbound'
+		#------------------
+		software_id=126
+
+		aSOFTWARE_NAME[$software_id]='AdGuard Home'
+		aSOFTWARE_DESC[$software_id]='powerful network-wide ads & trackers blocking DNS server'
+		aSOFTWARE_CATX[$software_id]=13
+		aSOFTWARE_DOCS[$software_id]='https://dietpi.com/docs/software/dns_servers/#adguard-home'
 
 		# File Servers
 		#--------------------------------------------------------------------------------
@@ -2010,7 +2017,7 @@ INDEX_BROWSER_TARGET=$INDEX_BROWSER_TARGET"
 					j=84
 				fi
 
-			# Resolve desktop dependency based on install state 
+			# Resolve desktop dependency based on install state
 			elif [[ $j == 'desktop' ]]
 			then
 				# Check for existing desktop (LXDE, MATE, Xfce, GNUstep, LXQt) installation
@@ -2092,6 +2099,16 @@ INDEX_BROWSER_TARGET=$INDEX_BROWSER_TARGET"
 
 		#-------------------------------------------------------------------------
 		# Conflicts and special pre-req software cases
+
+		# Don't let Pi-hole and AdGuard Home be installed at the same time
+		if (( ${aSOFTWARE_INSTALL_STATE[93]} > 0 && ${aSOFTWARE_INSTALL_STATE[126]} > 0 ))
+		then
+			(( ${aSOFTWARE_INSTALL_STATE[93]} == 1 )) && aSOFTWARE_INSTALL_STATE[93]=0
+			(( ${aSOFTWARE_INSTALL_STATE[126]} == 1 )) && aSOFTWARE_INSTALL_STATE[126]=0
+			G_WHIP_MSG "[WARNING] Conflicting software selection
+\n${aSOFTWARE_NAME[93]} and ${aSOFTWARE_NAME[126]} cannot be installed at the same time.
+\nThese pieces of software will be skipped. Other DietPi-Software installations will continue."
+		fi
 
 		# Don't let Tor Relay and Tor Hotspot be installed at the same time
 		if (( ${aSOFTWARE_INSTALL_STATE[184]} > 0 && ${aSOFTWARE_INSTALL_STATE[61]} > 0 ))
@@ -4323,10 +4340,10 @@ amvdec_vp9' > /etc/modules-load.d/dietpi-c4-kodi.conf
 			G_EXEC mkdir -p /etc/systemd/system/unbound.service.d
 			G_EXEC eval "echo -e '[Unit]\nWants=network-online.target\nAfter=network-online.target' > /etc/systemd/system/unbound.service.d/dietpi.conf"
 
-			# Pi-hole part 1
-			if (( ${aSOFTWARE_INSTALL_STATE[93]} > 0 )) && grep -q '^[[:blank:]]*port:[[:blank:]][[:blank:]]*53$' /etc/unbound/unbound.conf.d/dietpi.conf
+			# Pi-hole + AdGuard Home part 1
+			if (( ${aSOFTWARE_INSTALL_STATE[93]} > 0 || ${aSOFTWARE_INSTALL_STATE[126]} > 0 )) && grep -q '^[[:blank:]]*port:[[:blank:]][[:blank:]]*53$' /etc/unbound/unbound.conf.d/dietpi.conf
 			then
-				G_DIETPI-NOTIFY 2 'Configuring Unbound to work for Pi-hole'
+				G_DIETPI-NOTIFY 2 'Configuring Unbound to work for your selected AdBlocker'
 				grep '^[[:blank:]]*nameserver[[:blank:]]' /etc/resolv.conf | grep -qvE '[[:blank:]]127.0.0.1(:53)?$' || echo 'nameserver 9.9.9.9' >> /etc/resolv.conf # Failsafe
 				G_CONFIG_INJECT 'port:[[:blank:]]' '	port: 5335' /etc/unbound/unbound.conf.d/dietpi.conf
 				G_CONFIG_INJECT 'interface:[[:blank:]]' '	interface: 127.0.0.1' /etc/unbound/unbound.conf.d/dietpi.conf
@@ -4350,6 +4367,18 @@ amvdec_vp9' > /etc/modules-load.d/dietpi-c4-kodi.conf
 				then
 					G_CONFIG_INJECT 'PIHOLE_DNS_1=' 'PIHOLE_DNS_1=127.0.0.1#5335' /etc/pihole/setupVars.conf
 					G_EXEC sed -i '/^[[:blank:]]*PIHOLE_DNS_2=/d' /etc/pihole/setupVars.conf
+				fi
+			fi
+
+			# AdGuard Home part 2
+			if (( ${aSOFTWARE_INSTALL_STATE[126]} == 2 ))
+			then
+				G_DIETPI-NOTIFY 2 'Configuring AdGuard Home to use Unbound'
+				if [[ ! -f '/mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf' ]]
+				then
+					echo '127.0.0.1:5335' > /mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf
+					G_CONFIG_INJECT 'upstream_dns_file:[[:blank:]]' '  upstream_dns_file: /mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf' /mnt/dietpi_userdata/adguardhome/AdGuardHome.yaml
+					systemctl -q is-active adguardhome && G_EXEC systemctl restart adguardhome
 				fi
 			fi
 
@@ -4393,6 +4422,55 @@ amvdec_vp9' > /etc/modules-load.d/dietpi-c4-kodi.conf
 			export PIHOLE_SKIP_OS_CHECK=true
 			G_EXEC_NOEXIT=1 G_EXEC_OUTPUT=1 G_EXEC ./install.sh --disable-install-webserver || aSOFTWARE_INSTALL_STATE[$software_id]=0
 			G_EXEC_NOHALT=1 G_EXEC rm install.sh
+		fi
+
+		software_id=126 # AdGuard Home
+		if (( ${aSOFTWARE_INSTALL_STATE[$software_id]} == 1 )); then
+
+			Banner_Installing
+
+			# ARMv6
+			if (( $G_HW_ARCH == 1 )); then
+
+				INSTALL_URL_ADDRESS='https://static.adguard.com/adguardhome/release/AdGuardHome_linux_armv6.tar.gz'
+
+			# ARMv7
+			elif (( $G_HW_ARCH == 2 )); then
+
+				INSTALL_URL_ADDRESS='https://static.adguard.com/adguardhome/release/AdGuardHome_linux_armv7.tar.gz'
+
+			# ARMv8
+			elif (( $G_HW_ARCH == 3 )); then
+
+				INSTALL_URL_ADDRESS='https://static.adguard.com/adguardhome/release/AdGuardHome_linux_arm64.tar.gz'
+
+			# x86_64
+			elif (( $G_HW_ARCH == 10 )); then
+
+				INSTALL_URL_ADDRESS='https://static.adguard.com/adguardhome/release/AdGuardHome_linux_amd64.tar.gz'
+
+			fi
+
+			# Deps: apache2-utils is required for htpasswd command to create bcrypt password hashes
+			DEPS_LIST='apache2-utils'
+			Download_Install "$INSTALL_URL_ADDRESS"
+
+			# Reinstall: Stop service and remove install directory
+			[[ -f '/etc/systemd/system/adguardhome.service' ]] && G_EXEC systemctl stop adguardhome
+			[[ -d '/opt/adguardhome' ]] && G_EXEC rm -R /opt/adguardhome
+
+			G_EXEC mv AdGuardHome /opt/adguardhome
+
+			# Unbound: Switch port to 5335 if it was installed before, else it got just configured within its install step above
+			if (( ${aSOFTWARE_INSTALL_STATE[182]} == 2 )) && grep -q '^[[:blank:]]*port:[[:blank:]][[:blank:]]*53$' /etc/unbound/unbound.conf.d/dietpi.conf
+			then
+				G_DIETPI-NOTIFY 2 'Configuring Unbound to work for AdGuard Home'
+				grep '^[[:blank:]]*nameserver[[:blank:]]' /etc/resolv.conf | grep -qvE '[[:blank:]]127.0.0.1(:53)?$' || echo 'nameserver 9.9.9.9' >> /etc/resolv.conf # Failsafe
+				G_CONFIG_INJECT 'port:[[:blank:]]' '	port: 5335' /etc/unbound/unbound.conf.d/dietpi.conf
+				G_CONFIG_INJECT 'interface:[[:blank:]]' '	interface: 127.0.0.1' /etc/unbound/unbound.conf.d/dietpi.conf
+				G_EXEC systemctl restart unbound
+			fi
+
 		fi
 
 		software_id=33 # Airsonic
@@ -8973,6 +9051,68 @@ _EOF_
 
 		fi
 
+		software_id=126 # AdGuard Home
+		if (( ${aSOFTWARE_INSTALL_STATE[$software_id]} == 1 )); then
+
+			Banner_Configuration
+
+			# Directory
+			G_EXEC mkdir -p /mnt/dietpi_userdata/adguardhome
+
+			# User
+			Create_User -d /mnt/dietpi_userdata/adguardhome adguardhome
+
+			if [[ ! -f '/mnt/dietpi_userdata/adguardhome/AdGuardHome.yaml' ]]
+			then
+				dps_index=$software_id Download_Install 'AdGuardHome.yaml' /mnt/dietpi_userdata/adguardhome/AdGuardHome.yaml
+				# shellcheck disable=SC2016
+				G_CONFIG_INJECT 'password:[[:blank:]]' "  password: $(htpasswd -bnBC 10 '' "$GLOBAL_PW" | tr -d ':\n' | sed 's/\$2y/\$2a/')" /mnt/dietpi_userdata/adguardhome/AdGuardHome.yaml
+			fi
+
+			# Unbound: Configure AdGuard Home to use it
+			if (( ${aSOFTWARE_INSTALL_STATE[182]} > 0 ))
+			then
+				G_DIETPI-NOTIFY 2 'Configuring AdGuard Home to use Unbound'
+				if [[ ! -f '/mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf' ]]
+				then
+					echo '127.0.0.1:5335' > /mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf
+					G_CONFIG_INJECT 'upstream_dns_file:[[:blank:]]' '  upstream_dns_file: /mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf' /mnt/dietpi_userdata/adguardhome/AdGuardHome.yaml
+					systemctl -q is-active adguardhome && G_EXEC systemctl restart adguardhome
+				fi
+			fi
+
+			# Permissions
+			G_EXEC chown -R adguardhome:adguardhome /mnt/dietpi_userdata/adguardhome /opt/adguardhome
+			G_EXEC chmod 755 /opt/adguardhome{,/AdGuardHome}
+
+			# Service
+			cat << '_EOF_' > /etc/systemd/system/adguardhome.service
+[Unit]
+Description=AdGuard Home (DietPi)
+Wants=network-online.target
+After=network-online.target dietpi-boot.service
+
+# Restart attempt only 5 times
+StartLimitIntervalSec=60
+StartLimitBurst=5
+
+[Service]
+User=adguardhome
+AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_RAW
+ExecStart=/opt/adguardhome/AdGuardHome -w /mnt/dietpi_userdata/adguardhome
+ExecReload=/opt/adguardhome/AdGuardHome -s reload
+Restart=on-failure
+RestartSec=5
+
+[Install]
+WantedBy=multi-user.target
+_EOF_
+			# AdGuard Home service needs to be started by systemd, as dietpi-services must not control it to prevent it from killing the systems own DNS server.
+			G_EXEC systemctl enable adguardhome
+			aSTART_SERVICES+=('adguardhome')
+
+		fi
+
 		software_id=33 # Airsonic
 		if (( ${aSOFTWARE_INSTALL_STATE[$software_id]} == 1 )); then
 
@@ -13088,7 +13228,13 @@ _EOF_
 		if (( ${aSOFTWARE_INSTALL_STATE[$software_id]} == -1 )); then
 
 			Banner_Uninstalling
+			# Stop  Lighttpd service
+			[[ -f '/lib/systemd/system/lighttpd.service' ]] && systemctl disable --now lighttpd
+
 			G_AGP lighttpd
+
+			# Remove enabled Lighttpd configuration directory
+			[[ -d '/etc/lighttpd' ]] && rm -R /etc/lighttpd
 
 			# Remove certbot renewal hook
 			[[ -f 'etc/systemd/system/certbot.service.d/dietpi-lighttpd.conf' ]] && rm /etc/systemd/system/certbot.service.d/dietpi-lighttpd.conf
@@ -13547,11 +13693,21 @@ _EOF_
 			# Pi-hole: Assure that it does not resolve via Unbound anymore
 			if [[ -f '/etc/dnsmasq.d/01-pihole.conf' ]] && grep -q '^[[:blank:]]*server=127.0.0.1' /etc/dnsmasq.d/01-pihole.conf
 			then
-				G_WHIP_MSG 'The Pi-hole upstream DNS server has been changed to Quad9 due to Unbound being uninstalled.'
+				G_DIETPI-NOTIFY 2 'The Pi-hole upstream DNS server has been changed to Quad9 due to Unbound being uninstalled.'
 				G_CONFIG_INJECT 'server=127.0.0.1' 'server=9.9.9.9' /etc/dnsmasq.d/01-pihole.conf
-				systemctl -q is-active pihole-FTL && G_EXEC systemctl restart pihole-FTL
+				systemctl -q is-active pihole-FTL && G_EXEC_NOEXIT=1 G_EXEC systemctl restart pihole-FTL
 			fi
 			[[ -f '/etc/pihole/setupVars.conf' ]] && grep -q '^[[:blank:]]*PIHOLE_DNS_1=127.0.0.1' /etc/pihole/setupVars.conf && G_CONFIG_INJECT 'PIHOLE_DNS_1=' 'PIHOLE_DNS_1=9.9.9.9' /etc/pihole/setupVars.conf
+
+			# AdGuard Home: Assure that it does not resolve via Unbound anymore
+			if [[ -f '/mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf' ]]; then
+
+				G_DIETPI-NOTIFY 2 'AdGuard Home upstream DNS server has been changed back to default settings due to Unbound being uninstalled.'
+				G_CONFIG_INJECT 'upstream_dns_file:[[:blank:]]' '  upstream_dns_file: ""' /mnt/dietpi_userdata/adguardhome/AdGuardHome.yaml
+				[[ -f '/mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf' ]]  && G_EXEC_NOEXIT=1 G_EXEC rm /mnt/dietpi_userdata/adguardhome/dietpi-unbound.conf
+				systemctl -q is-active adguardhome && G_EXEC_NOEXIT=1 G_EXEC systemctl restart adguardhome
+
+			fi
 
 			G_AGP unbound
 			[[ -d '/etc/unbound' ]] && rm -R /etc/unbound
@@ -14045,20 +14201,47 @@ _EOF_
 
 			fi
 			# - Lighttpd
-			if [[ -d '/etc/lighttpd/mods-available' ]]; then
+			[[ -d '/etc/lighttpd/conf-available' ]] && G_EXEC_NOEXIT=1 G_EXEC rm -f /etc/lighttpd/conf-{available,enabled}/99-dietpi-pihole{,-block_public_admin}.conf
 
-				lighty-disable-mod dietpi-pihole* 2> /dev/null
-				rm -f /etc/lighttpd/mods-available/99-dietpi-pihole*
-
-			fi
 			# - Nginx
 			[[ -d '/etc/nginx/sites-dietpi' ]] && rm -f /etc/nginx/sites-dietpi/dietpi-pihole*
 
-			# Unbound
-			if (( ${aSOFTWARE_INSTALL_STATE[182]} > 1 )) && [[ -f '/etc/unbound/unbound.conf.d/dietpi-pihole.conf' ]]
+			# Unbound: Switch port to 53 if it is still installed
+			if (( ${aSOFTWARE_INSTALL_STATE[182]} == 2 )) && grep -q '^[[:blank:]]*port:[[:blank:]][[:blank:]]*5335$' /etc/unbound/unbound.conf.d/dietpi.conf
 			then
 				G_DIETPI-NOTIFY 2 'Reconfiguring Unbound to work on its own'
-				rm /etc/unbound/unbound.conf.d/dietpi-pihole.conf
+				grep '^[[:blank:]]*nameserver[[:blank:]]' /etc/resolv.conf | grep -qvE '[[:blank:]]127.0.0.1(:53)?$' || echo 'nameserver 9.9.9.9' >> /etc/resolv.conf # Failsafe
+				G_CONFIG_INJECT 'port:[[:blank:]]' '	port: 53' /etc/unbound/unbound.conf.d/dietpi.conf
+				G_CONFIG_INJECT 'interface:[[:blank:]]' '	interface: 0.0.0.0' /etc/unbound/unbound.conf.d/dietpi.conf
+				G_EXEC_NOEXIT=1 G_EXEC systemctl restart unbound
+			fi
+		fi
+
+		software_id=126 # AdGuard Home
+		if (( ${aSOFTWARE_INSTALL_STATE[$software_id]} == -1 )); then
+
+			Banner_Uninstalling
+			if [[ -f '/etc/systemd/system/adguardhome.service' ]]; then
+
+				G_EXEC systemctl disable --now adguardhome
+				G_EXEC rm /etc/systemd/system/adguardhome.service
+
+			fi
+			[[ -d '/etc/systemd/system/adguardhome.service.d' ]] && G_EXEC rm -R /etc/systemd/system/adguardhome.service.d
+			[[ -d '/opt/adguardhome' ]] && G_EXEC rm -R /opt/adguardhome
+			
+			# Remove user and home directory
+			getent passwd adguardhome > /dev/null && userdel adguardhome
+			G_EXEC rm -Rf /mnt/dietpi_userdata/adguardhome
+
+			# Unbound: Switch port to 53 if it is still installed
+			if (( ${aSOFTWARE_INSTALL_STATE[182]} == 2 )) && grep -q '^[[:blank:]]*port:[[:blank:]][[:blank:]]*5335$' /etc/unbound/unbound.conf.d/dietpi.conf
+			then
+				G_DIETPI-NOTIFY 2 'Reconfiguring Unbound to work on its own'
+				grep '^[[:blank:]]*nameserver[[:blank:]]' /etc/resolv.conf | grep -qvE '[[:blank:]]127.0.0.1(:53)?$' || echo 'nameserver 9.9.9.9' >> /etc/resolv.conf # Failsafe
+				G_CONFIG_INJECT 'port:[[:blank:]]' '	port: 53' /etc/unbound/unbound.conf.d/dietpi.conf
+				G_CONFIG_INJECT 'interface:[[:blank:]]' '	interface: 0.0.0.0' /etc/unbound/unbound.conf.d/dietpi.conf
+				G_EXEC_NOEXIT=1 G_EXEC systemctl restart unbound
 			fi
 		fi
 
@@ -16413,8 +16596,30 @@ We allow it to take up to 30 minutes, it's process can be followed, please be pa
 
 			fi
 
-			# Pi-hole
-			if (( ${aSOFTWARE_INSTALL_STATE[93]} == 1 ))
+			# Avoid having AdGuard Home installed in parallel to Pi-hole
+			if (( ${aSOFTWARE_INSTALL_STATE[93]} > 0 )) && (( ${aSOFTWARE_INSTALL_STATE[126]} > 0 ))
+			then
+				# AdGuard Home selected together with Pi-hole
+				if (( ${aSOFTWARE_INSTALL_STATE[93]} == 1 )) && (( ${aSOFTWARE_INSTALL_STATE[126]} == 1 ))
+				then
+					(( ${aSOFTWARE_INSTALL_STATE[126]} == 1 )) && aSOFTWARE_INSTALL_STATE[126]=0
+					G_WHIP_MSG 'AdGuard Home selected together with Pi-hole. AdGuard Home will be unselected.'
+
+				# AdGuard Home already installed
+				elif (( ${aSOFTWARE_INSTALL_STATE[126]} == 2 ))
+				then
+					(( ${aSOFTWARE_INSTALL_STATE[93]} == 1 )) && aSOFTWARE_INSTALL_STATE[93]=0
+					G_WHIP_MSG 'AdGuard Home already installed. Pi-hole will be unselected.'
+
+				# Pi-hole already installed
+				else
+					(( ${aSOFTWARE_INSTALL_STATE[126]} == 1 )) && aSOFTWARE_INSTALL_STATE[126]=0
+					G_WHIP_MSG 'Pi-hole already installed. AdGuard Home will be unselected.'
+				fi
+			fi
+
+			# Offer to install Unbound along with AdGuard Home and Pi-hole
+			if (( ${aSOFTWARE_INSTALL_STATE[93]} == 1 || ${aSOFTWARE_INSTALL_STATE[126]} == 1 ))
 			then
 				# Add option to use Unbound as upstream DNS server
 				if (( ${aSOFTWARE_INSTALL_STATE[182]} == 0 ))
@@ -16425,7 +16630,7 @@ We allow it to take up to 30 minutes, it's process can be followed, please be pa
 				fi
 
 				# Prompt for static IP
-				if G_WHIP_YESNO 'A static IP address is essential for Pi-hole installations. DietPi-Config can be used to quickly setup your static IP address.
+				if G_WHIP_YESNO 'A static IP address is essential for a DNS server installations. DietPi-Config can be used to quickly setup your static IP address.
 \nIf you have already setup your static IP, please ignore this message.\n\nWould you like to setup your static IP address now?'
 				then
 					G_WHIP_MSG 'DietPi-Config will now be launched. Simply select your Ethernet or Wifi connection from the menu to access the IP address settings.
