v53
EOL corrections in conf folder.
New func folder for global functions.

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -32,20 +32,15 @@
 	#/////////////////////////////////////////////////////////////////////////////////////
 	INTERNET_ADDRESS='http://mirrordirector.raspbian.org'
 	INTERNET_CONNECTED=0
-	INTERNET_SPIDER_TIMEOUT=10
-	INTERNET_SPIDER_RETRYCOUNT=3
 	
 	Check_Internet_Connection(){
 
 		INTERNET_CONNECTED=0
 		
-		#Inform user incase of delay
-		clear
-		echo -e "\nTesting internet connection, please wait....."
+		INTERNET_ADDRESS='http://mirrordirector.raspbian.org'
 		
-		#check internet connection
-		wget -q --spider --timeout="$INTERNET_SPIDER_TIMEOUT" --tries="$INTERNET_SPIDER_RETRYCOUNT" "$INTERNET_ADDRESS"
-		if [ $? -eq 0 ]; then
+		/boot/dietpi/func/check_connection 10 2 "$INTERNET_ADDRESS"	
+		if (( $? == 0 )); then
 			INTERNET_CONNECTED=1
 		fi
 	}
@@ -270,21 +265,21 @@
 			
 			#Ubuntu 14.04 - add repo
 			elif (( $DISTRO == 2 )); then
+			
 				#check source is online
-				wget -q --spider --timeout="$INTERNET_SPIDER_TIMEOUT" --tries="$INTERNET_SPIDER_RETRYCOUNT" http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/
+				INTERNET_ADDRESS='http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/'
+				/boot/dietpi/func/check_connection 5 2 "$INTERNET_ADDRESS"
 				
 				#Install
-				if [ $? -eq 0 ]; then
+				if (( $? == 0 )); then
 					if [ ! -f /etc/apt/sources.list.d/owncloud.list ]; then 
 						sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/owncloud.list"
 						apt-get update
 					fi
 					apt-get install owncloud --force-yes -y
 					
-				#Offline!
 				else
-					WHIP_TITLE='Error - Unable to Connect'
-					whiptail --title "$WHIP_TITLE" --msgbox "Unable to Install Owncloud. http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/ is offline and/or unreachable" 10 60
+					Info_NoConnection_NoInstall
 
 					#Abort Install, prevent configs being applied
 					OWNCLOUD=0
@@ -293,27 +288,28 @@
 		fi
 	 
 		#Ympd MPD
-		if (( $YMPD == 1 )); then    
-			#Check online
-			wget -q --spider --timeout="$INTERNET_SPIDER_TIMEOUT" --tries="$INTERNET_SPIDER_RETRYCOUNT" http://www.ympd.org/downloads/ympd-1.2.3-armhf.tar.bz2
+		if (( $YMPD == 1 )); then  
+			INSTALL_DESCRIPTION='Hifi / Web Interface Music Player (Mpd Ympd)'
+			Banner_Installing
+		
+			#check source is online
+			INTERNET_ADDRESS='http://www.ympd.org/downloads/ympd-1.2.3-armhf.tar.bz2'
+			/boot/dietpi/func/check_connection 5 2 "$INTERNET_ADDRESS"
+
 			#Install
-			if [ $? -eq 0 ]; then
-				INSTALL_DESCRIPTION='Hifi / Web Interface Music Player (Mpd Ympd)'
-				Banner_Installing
+			if (( $? == 0 )); then
 				
 				#Install MPD
 				apt-get install mpd libmpdclient2 -y
 				
 				#Setup YMPD			
-				wget http://www.ympd.org/downloads/ympd-1.2.3-armhf.tar.bz2
+				wget "$INTERNET_ADDRESS"
 				tar -xvf ympd-*
 				rm ympd-*
 				mv ympd /usr/bin/ympd
 				
-			#Offline!
 			else
-				WHIP_TITLE='Error - Unable to Connect'
-				whiptail --title "$WHIP_TITLE" --msgbox "Unable to Install Hifi / Web Interface Music Player (Mpd Ympd). ympd.org is offline and/or unreachable" 10 60
+				Info_NoConnection_NoInstall
 
 				#Abort Install, prevent configs being applied
 				YMPD=0
@@ -322,10 +318,11 @@
 		
 		#Kodi
 		if (( $KODI == 1 )); then
+			INSTALL_DESCRIPTION='Kodi'
+			Banner_Installing
+	
 			#oDroid C1
 			if (( $HW_MODEL == 10 )); then
-				INSTALL_DESCRIPTION='Kodi'
-				Banner_Installing
 				apt-get install libcurl4-gnutls-dev --no-install-recommends -y
 				apt-get install kodi -y
 				
@@ -334,11 +331,12 @@
 				INSTALL_DESCRIPTION='Kodi (Adding Michael Gorven Repo)'
 				Banner_Installing
 
-				#Check APT is online
-				wget -q --spider --timeout="$INTERNET_SPIDER_TIMEOUT" --tries="$INTERNET_SPIDER_RETRYCOUNT" http://archive.mene.za.net/raspbian
+				#check source is online
+				INTERNET_ADDRESS='http://archive.mene.za.net/raspbian'
+				/boot/dietpi/func/check_connection 5 2 "$INTERNET_ADDRESS"
 				
 				#Install
-				if [ $? -eq 0 ]; then
+				if (( $? == 0 )); then
 					#Check if apt address and key needs adding
 					if (( $(cat /etc/apt/sources.list.d/mene.list | grep -ci -m1 'http://archive.mene.za.net/raspbian') == 0 )); then
 						echo -e 'deb http://archive.mene.za.net/raspbian wheezy contrib' >> /etc/apt/sources.list.d/mene.list
@@ -353,10 +351,8 @@
 					
 					apt-get install kodi -y
 					
-				#Offline!
 				else
-					WHIP_TITLE='Error - Unable to Connect'
-					whiptail --title "$WHIP_TITLE" --msgbox "Unable to Install Kodi. archive.mene.za.net/raspbian is offline and/or unreachable" 10 60
+					Info_NoConnection_NoInstall
 
 					#Abort Install, prevent configs being applied
 					KODI=0
@@ -369,17 +365,18 @@
 			INSTALL_DESCRIPTION='RetroPie'
 			Banner_Installing
 
-			#Check GIT is online
-			wget -q --spider --timeout="$INTERNET_SPIDER_TIMEOUT" --tries="$INTERNET_SPIDER_RETRYCOUNT" https://github.com/petrockblog/RetroPie-Setup
+			#check source is online
+			INTERNET_ADDRESS='https://github.com/petrockblog/RetroPie-Setup'
+			/boot/dietpi/func/check_connection 5 2 "$INTERNET_ADDRESS"
 			
 			#Install
-			if [ $? -eq 0 ]; then
+			if (( $? == 0 )); then
 
 				#Install dialog
 				apt-get install dialog -y
 				
 				#Clone RetroPie Git
-				git clone --depth=0 https://github.com/petrockblog/RetroPie-Setup
+				git clone --depth=0 "$INTERNET_ADDRESS"
 				chmod +x ~/RetroPie-Setup/retropie_setup.sh
 
 				#Info for RetroPie script
@@ -388,10 +385,10 @@
 
 				#Run RetroPie setup script
 				~/RetroPie-Setup/retropie_setup.sh
-			else
+
 			#Offline
-				WHIP_TITLE='Error - Unable to Connect'
-				whiptail --title "$WHIP_TITLE" --msgbox "Unable to Install RetroPie. github.com/petrockblog/RetroPie-Setup is offline and/or unreachable" 10 60
+			else
+				Info_NoConnection_NoInstall
 
 				#Abort Install, prevent configs being applied
 				RETROPIE=0
@@ -410,24 +407,29 @@
 			INSTALL_DESCRIPTION='Website URL Address (No-Ip)'
 			Banner_Installing
 			
-			wget https://dl.dropboxusercontent.com/u/33437507/dietpi_wget/noip2.gz
-			wget https://dl.dropboxusercontent.com/u/33437507/dietpi_wget/noip2.sh
+			INTERNET_ADDRESS='http://fuzon.co.uk/downloads/dietpi-noip.zip'
+			/boot/dietpi/func/check_connection 5 2 "$INTERNET_ADDRESS"
 			
-			#Check if Files couldnt be found/downloaded
-			if [ "$(ls | grep -ci -m1 'noip2.gz')" = 0 ] || [ "$(ls | grep -ci -m1 'noip2.sh')" = 0 ]; then
-				WHIP_TITLE='Error - Unable to Connect'
-				whiptail --title "$WHIP_TITLE" --msgbox "Unable to Install NoIp. https://dl.dropboxusercontent.com/u/33437507/dietpi_wget/noip2.gz is offline and/or unreachable" 10 60
-				NOIPDYNDNS=0
-			else
+			#Install
+			if (( $? == 0 )); then
+
 				#NoIp Binary install
-				gzip -d noip2.gz
-				mv noip2 /usr/local/bin/noip2
+				wget "$INTERNET_ADDRESS"
+				unzip dietpi-noip.zip
+				rm dietpi-noip.zip
+				mv noip_binary /usr/local/bin/noip2
 				chmod +x /usr/local/bin/noip2
 
 				#noip2 service file
-				mv noip2.sh /etc/init.d/noip2
+				cp /boot/dietpi/conf/noip_init /etc/init.d/noip2
 				chmod +x /etc/init.d/noip2
 				update-rc.d noip2 defaults 94 6
+
+			else
+				Info_NoConnection_NoInstall
+
+				#Abort Install, prevent configs being applied
+				NOIPDYNDNS=0
 			fi
 		fi
 		
@@ -441,19 +443,19 @@
 		
 		#VPN Server
 		if (( $VPNSERVER == 1 )); then
-
-			#Download Source / extract / delete tar
+		
 			INSTALL_DESCRIPTION='VPN Server (SoftEther) - Download'
 			Banner_Installing
-			wget http://www.softether-download.com/files/softether/v4.15-9546-beta-2015.04.05-tree/Linux/SoftEther_VPN_Server/32bit_-_ARM_EABI/softether-vpnserver-v4.15-9546-beta-2015.04.05-linux-arm_eabi-32bit.tar.gz
 
-			#Check file downloaded
-			if (( $(ls | grep -ci -m1 'softether-vpnserver') == 0 )); then
-				WHIP_TITLE='Error - Unable to Connect'
-				whiptail --title "$WHIP_TITLE" --msgbox "Unable to Install VPN Server.  http://www.softether-download.com/files/softether/v4.15-9546-beta-2015.04.05-tree/Linux/SoftEther_VPN_Server/32bit_-_ARM_EABI/softether-vpnserver-v4.15-9546-beta-2015.04.05-linux-arm_eabi-32bit.tar.gz is offline and/or unreachable" 14 70
-				VPNSERVER=0
-			#Begin Install
-			else
+			#check source is online
+			INTERNET_ADDRESS='http://www.softether-download.com/files/softether/v4.15-9546-beta-2015.04.05-tree/Linux/SoftEther_VPN_Server/32bit_-_ARM_EABI/softether-vpnserver-v4.15-9546-beta-2015.04.05-linux-arm_eabi-32bit.tar.gz'
+			/boot/dietpi/func/check_connection 5 2 "$INTERNET_ADDRESS"
+
+			#Install
+			if (( $? == 0 )); then
+
+				#Download Source / extract / delete tar
+				wget "$INTERNET_ADDRESS"
 				tar zxvf softether-vpnserver-*
 				rm softether-vpnserver-*
 				
@@ -467,6 +469,12 @@
 				cp /boot/dietpi/conf/vpnserver.initd /etc/init.d/vpnserver 
 				chmod +x /etc/init.d/vpnserver
 				update-rc.d vpnserver defaults
+
+			else
+				Info_NoConnection_NoInstall
+
+				#Abort Install, prevent configs being applied
+				VPNSERVER=0
 			fi
 		fi
 		
@@ -474,15 +482,13 @@
 		if (( $OPENTYRIAN == 1 )); then
 			INSTALL_DESCRIPTION='Gaming (OpenTyrian Game)'
 			Banner_Installing
-			wget http://fuzon.co.uk/downloads/dietpi-opentyrian.zip
-
-			#Check file downloaded
-			if (( $(ls | grep -ci -m1 'dietpi-opentyrian') == 0 )); then
-				WHIP_TITLE='Error - Unable to Connect'
-				whiptail --title "$WHIP_TITLE" --msgbox "Unable to Install Gaming (OpenTyrian Game). http://fuzon.co.uk/downloads/dietpi-opentyrian.zip is offline and/or unreachable" 14 70
-				OPENTYRIAN=0
-			#Begin Install
-			else
+			
+			INTERNET_ADDRESS='http://fuzon.co.uk/downloads/dietpi-opentyrian.zip'
+			/boot/dietpi/func/check_connection 5 2 "$INTERNET_ADDRESS"
+			
+			#Install
+			if (( $? == 0 )); then
+				wget "$INTERNET_ADDRESS"
 				apt-get install ibsdl1.2debian libsdl-net1.2 --no-install-recommends -y
 
 				#Unzip binaries and source
@@ -493,6 +499,12 @@
 				#Copy the DietPi run file for OpenTyrian
 				cp /boot/dietpi/conf/opentyrian_run /usr/local/games/opentyrian/run
 				chmod +x /usr/local/games/opentyrian/run
+
+			else
+				Info_NoConnection_NoInstall
+
+				#Abort Install, prevent configs being applied
+				OPENTYRIAN=0
 			fi
 		fi
 	}
@@ -604,6 +616,7 @@
 			elif (( $HW_MODEL == 10 )); then
 				INSTALL_DESCRIPTION='Xserver / Xorg (mali)'
 				Banner_Installing
+				#Mali is already on DietOdroid image
 				apt-get install xinit xauth xserver-xorg xfonts-base --no-install-recommends -y
 			
 			fi
@@ -1078,7 +1091,20 @@
 
 		USB_HDD_CONNECTED=$(df -h | grep -ci -m1 '/dev/sda1')
 	}
+
+	#/////////////////////////////////////////////////////////////////////////////////////
+	# WHIPTAIL INFOs
+	#/////////////////////////////////////////////////////////////////////////////////////
 	
+	Info_NoConnection_NoInstall(){
+		whiptail --title "Error - Unable to Connect" --msgbox "Unable to Install $INSTALL_DESCRIPTION \n\n$INTERNET_ADDRESS is offline and/or unreachable." 14 70
+	}
+
+	Info_UsbDrive_Required(){
+		local name_input=$1
+		whiptail --title "Error - USB Drive Required" --msgbox " A USB Harddrive is required for $name_input \n - This will NOT be installed." 10 60
+	}
+
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# WHIPTAIL MENUS
 	#/////////////////////////////////////////////////////////////////////////////////////
@@ -1420,8 +1446,7 @@
 						INSTALL_DIETPI_CHOICESMADE=true
 					fi
 				else
-					WHIP_TITLE='Error - USB Drive Required'
-					whiptail --title "$WHIP_TITLE" --msgbox " A USB Harddrive is required for BitTorrent (Transmission) \n - This will not be installed" 10 60
+					Info_UsbDrive_Required "BitTorrent"
 				fi
 			;;
 			6)
@@ -1431,8 +1456,7 @@
 						INSTALL_DIETPI_CHOICESMADE=true
 					fi
 				else
-					WHIP_TITLE='Error - USB Drive Required'
-					whiptail --title "$WHIP_TITLE" --msgbox " A USB Harddrive is required for OwnCloud \n - This will not be installed" 10 60
+					Info_UsbDrive_Required "OwnCloud"
 				fi
 			;;
 			7)
@@ -1819,6 +1843,9 @@
 			
 		fi
 		
+		#Clear Screen Buffer
+		clear
+
 		#--------------------------------------------------------------------------------------
 		#Generate blank .install file. Doesnt exist on a fresh image.
 		if [ ! -f /boot/dietpi/.installed ]; then
@@ -1828,6 +1855,7 @@
 		#--------------------------------------------------------------------------------------
 		#Ask our inital questions, before allowing access to the software selection menus.
 		if (( $DIETPI_INSTALL_STAGE == 0 )); then
+		
 		
 			WHIP_TITLE='DietPi - Welcome'
 			whiptail --title "$WHIP_TITLE" --msgbox "Welcome to the DietPi Installation System. \n \nBefore we can begin, we need to ask you a few questions regarding this installation. \n \nPress Enter to begin." 14 70
