v97

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -166,6 +166,8 @@
 	SQUEEZEBOXSERVER=0
 	WORDPRESS=0
 	TIGHTVNCSERVER=0
+	FAIL2BAN=0
+	PHPSYSINFO=0
 
 	#Linux Software
 	INSTALL_LINUX_CHOICESMADE=false
@@ -260,6 +262,8 @@
 		echo -e "SQUEEZEBOXSERVER $SQUEEZEBOXSERVER" >> "$FILEPATH_INSTALLED_FILE"
 		echo -e "WORDPRESS $WORDPRESS" >> "$FILEPATH_INSTALLED_FILE"
 		echo -e "TIGHTVNCSERVER $TIGHTVNCSERVER" >> "$FILEPATH_INSTALLED_FILE"
+		echo -e "FAIL2BAN $FAIL2BAN" >> "$FILEPATH_INSTALLED_FILE"
+		echo -e "PHPSYSINFO $PHPSYSINFO" >> "$FILEPATH_INSTALLED_FILE"
 
 		echo -e "#Additional Linux Software" >> "$FILEPATH_INSTALLED_FILE"
 		echo -e "VIMFULL $VIMFULL" >> "$FILEPATH_INSTALLED_FILE"
@@ -335,6 +339,8 @@
 		SQUEEZEBOXSERVER=$(cat "$FILEPATH_INSTALLED_FILE" | grep -m1 'SQUEEZEBOXSERVER ' | awk '{print $2}')
 		WORDPRESS=$(cat "$FILEPATH_INSTALLED_FILE" | grep -m1 'WORDPRESS ' | awk '{print $2}')
 		TIGHTVNCSERVER=$(cat "$FILEPATH_INSTALLED_FILE" | grep -m1 'TIGHTVNCSERVER ' | awk '{print $2}')
+		FAIL2BAN=$(cat "$FILEPATH_INSTALLED_FILE" | grep -m1 'FAIL2BAN ' | awk '{print $2}')
+		PHPSYSINFO=$(cat "$FILEPATH_INSTALLED_FILE" | grep -m1 'PHPSYSINFO ' | awk '{print $2}')
 
 		#Linux
 		VIMFULL=$(cat "$FILEPATH_INSTALLED_FILE" | grep -m1 'VIMFULL ' | awk '{print $2}')
@@ -404,6 +410,8 @@
 		elif (( $LINUXDASH == 1 )); then
 			WEBSERVER_LASP=1
 		elif (( $PIHOLE == 1 )); then
+			WEBSERVER_LASP=1
+		elif (( $PHPSYSINFO == 1 )); then
 			WEBSERVER_LASP=1
 		fi
 
@@ -1172,8 +1180,6 @@
 				HAPROXY=0
 			fi
 
-
-
 		fi
 
 		#SQUEEZEBOXSERVER
@@ -1234,6 +1240,41 @@
 			Banner_Installing
 
 			apt-get install tightvncserver --no-install-recommends -y
+
+		fi
+
+		#FAIL2BAN
+		if (( $FAIL2BAN == 1 )); then
+			INSTALL_DESCRIPTION='Fail2Ban'
+			Banner_Installing
+
+			apt-get install fail2ban --no-install-recommends -y
+
+		fi
+
+		#PHPSYSINFO
+		if (( $PHPSYSINFO == 1 )); then
+			INSTALL_DESCRIPTION='PhpSysInfo (Stats)'
+			Banner_Installing
+
+			#check source is online
+			INSTALL_URL_ADDRESS='https://github.com/phpsysinfo/phpsysinfo/archive/v3.2.3.zip'
+			/DietPi/dietpi/func/check_connection 5 2 "$INSTALL_URL_ADDRESS"
+
+			#Install
+			if (( $? == 0 )); then
+				wget "$INSTALL_URL_ADDRESS" -O package.zip
+				unzip package.zip -d /var/www/
+				rm package.zip
+				mv /var/www/phpsysinfo-* /var/www/phpsysinfo
+				chown -R www-data:www-data /var/www/phpsysinfo
+				chmod -R 775 /var/www/phpsysinfo
+			else
+				Info_NoConnection_NoInstall
+
+				#Abort Install, prevent configs being applied
+				PHPSYSINFO=0
+			fi
 
 		fi
 
@@ -1507,6 +1548,11 @@ _EOF_
 			apt-get install logrotate -y
 
 			LOGGING_LOGROTATE=2
+		fi
+
+		#Software that requires rsyslog
+		if (( $FAIL2BAN == 1 )); then
+			LOGGING_RSYSLOG=1
 		fi
 
 		if (( $LOGGING_RSYSLOG == 1 )); then
@@ -2612,6 +2658,31 @@ _EOF_
 
 		fi
 
+		#FAIL2BAN
+		if (( $FAIL2BAN == 1 )); then
+
+			cat << _EOF_ > /etc/fail2ban/fail2ban.conf
+[Definition]
+# loglevel #1=error #2=warn #3=info
+loglevel = 3
+logtarget = /var/log/fail2ban.log
+socket = /var/run/fail2ban/fail2ban.sock
+pidfile = /var/run/fail2ban/fail2ban.pid
+_EOF_
+
+			cp /DietPi/dietpi/conf/fail2ban_jail.conf /etc/fail2ban/jail.conf
+
+			FAIL2BAN=2
+
+		fi
+
+		#PHPSYSINFO
+		if (( $PHPSYSINFO == 1 )); then
+
+			PHPSYSINFO=2
+
+		fi
+
 	}
 
 	Install_Apply_GPU_Settings(){
@@ -3521,6 +3592,24 @@ _EOF_
 			fi
 		fi
 
+		local fail2ban_w="off"
+		if (( $FAIL2BAN > 0 )); then
+			fail2ban_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $FAIL2BAN == 1 )); then
+				FAIL2BAN=0
+			fi
+		fi
+
+		local phpsysinfo_w="off"
+		if (( $PHPSYSINFO > 0 )); then
+			phpsysinfo_w="on"
+			#Reset to 0. Menu checklists will apply back to 1
+			if (( $PHPSYSINFO == 1 )); then
+				PHPSYSINFO=0
+			fi
+		fi
+
 		#-----------------------------------------------------------------------------
 		WHIP_TITLE='DietPi Optimized Software Selection'
 
@@ -3540,6 +3629,9 @@ _EOF_
 			"" "────System Stats / Management──────────────" "off" \
 			"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
 			"LinuxDash" "Web interface system stats." $linuxdash_w \
+			"PhpSysInfo" "Web interface system stats." $phpsysinfo_w \
+			"" "────System Security────────────────────────" "off" \
+			"Fail2Ban" "Prevents brute-force attacks with IP ban." $fail2ban_w \
 			"" "────Webserver Stacks───────────────────────" "off" \
 			"LAMP" "Webserver: Apache2 / MySql  / Php." $webserver_lamp_w \
 			"LASP" "Webserver: Apache2 / SQLite / Php." $webserver_lasp_w \
@@ -3578,6 +3670,9 @@ _EOF_
 			"" "────System Stats / Management──────────────" "off" \
 			"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
 			"LinuxDash" "Web interface system stats." $linuxdash_w \
+			"PhpSysInfo" "Web interface system stats." $phpsysinfo_w \
+			"" "────System Security────────────────────────" "off" \
+			"Fail2Ban" "Prevents brute-force attacks with IP ban." $fail2ban_w \
 			"" "────Webserver Stacks───────────────────────" "off" \
 			"LAMP" "Webserver: Apache2 / MySql  / Php." $webserver_lamp_w \
 			"LASP" "Webserver: Apache2 / SQLite / Php." $webserver_lasp_w \
@@ -3618,6 +3713,9 @@ _EOF_
 			"" "────System Stats / Management──────────────" "off" \
 			"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
 			"LinuxDash" "Web interface system stats." $linuxdash_w \
+			"PhpSysInfo" "Web interface system stats." $phpsysinfo_w \
+			"" "────System Security────────────────────────" "off" \
+			"Fail2Ban" "Prevents brute-force attacks with IP ban." $fail2ban_w \
 			"" "────Webserver Stacks───────────────────────" "off" \
 			"LAMP" "Webserver: Apache2 / MySql  / Php." $webserver_lamp_w \
 			"LASP" "Webserver: Apache2 / SQLite / Php." $webserver_lasp_w \
@@ -3675,6 +3773,9 @@ _EOF_
 				"" "────System Stats / Management──────────────" "off" \
 				"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
 				"LinuxDash" "Web interface system stats." $linuxdash_w \
+				"PhpSysInfo" "Web interface system stats." $phpsysinfo_w \
+				"" "────System Security────────────────────────" "off" \
+				"Fail2Ban" "Prevents brute-force attacks with IP ban." $fail2ban_w \
 				"" "────Webserver Stacks───────────────────────" "off" \
 				"LAMP" "Webserver: Apache2 / MySql  / Php." $webserver_lamp_w \
 				"LASP" "Webserver: Apache2 / SQLite / Php." $webserver_lasp_w \
@@ -3729,6 +3830,9 @@ _EOF_
 				"DietPi-Cloudshell" "System stats for your LCD display or monitor." $dietpicloudshell_w \
 				"Raspcontrol" "Web interface system stats." $raspcontrol_w \
 				"LinuxDash" "Web interface system stats." $linuxdash_w \
+				"PhpSysInfo" "Web interface system stats." $phpsysinfo_w \
+				"" "────System Security────────────────────────" "off" \
+				"Fail2Ban" "Prevents brute-force attacks with IP ban." $fail2ban_w \
 				"" "────Webserver Stacks───────────────────────" "off" \
 				"LAMP" "Webserver: Apache2 / MySql  / Php." $webserver_lamp_w \
 				"LASP" "Webserver: Apache2 / SQLite / Php." $webserver_lasp_w \
@@ -3755,6 +3859,18 @@ _EOF_
 		while read choice
 		do
 			case $choice in
+			PhpSysInfo)
+				if (( $PHPSYSINFO == 0 )); then
+					PHPSYSINFO=1
+					INSTALL_DIETPI_CHOICESMADE=true
+				fi
+			;;
+			Fail2Ban)
+				if (( $FAIL2BAN == 0 )); then
+					FAIL2BAN=1
+					INSTALL_DIETPI_CHOICESMADE=true
+				fi
+			;;
 			"LXDE: VNC Server")
 				if (( $TIGHTVNCSERVER == 0 )); then
 					TIGHTVNCSERVER=1
@@ -4354,7 +4470,6 @@ _EOF_
 		/DietPi/dietpi/dietpi-banner 0
 		echo -e "\n Installing Software: $INSTALL_DESCRIPTION \n Please Wait, this may take some time... \n "
 		/DietPi/dietpi/dietpi-funtime 0
-		#sleep 3
 	}
 
 	Banner_Apt_Update(){
@@ -4374,7 +4489,6 @@ _EOF_
 		/DietPi/dietpi/dietpi-banner 0
 		echo -e "\n Please Wait: \n Applying DietPi optimizations for $HW_MODEL_DESCRIPTION \n"
 		/DietPi/dietpi/dietpi-funtime 0
-		#sleep 3
 	}
 
 	Banner_Aborted(){
