v157
+ DietPi-Software | MotionEye (Stretch): Resolved failed installation,
thanks @MichaIng for the repo hint:
https://github.com/Fourdee/DietPi/issues/1155#issue-259888197

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -6544,26 +6544,42 @@ _EOF_
 
 			Banner_Installing
 
-			INSTALL_URL_ADDRESS='http://github.com/Motion-Project/motion/releases/download/release-4.0.1/pi_jessie_motion_4.0.1-1_armhf.deb'
+			#Jessie, prefer latest motion release.
+			if (( $DISTRO == 3 )); then
 
-			#url/redireect always fails wget spider test...
-			/DietPi/dietpi/func/check_connection "http://github.com/Motion-Project/motion"
-			if (( $? == 0 )); then
+				INSTALL_URL_ADDRESS='http://github.com/Motion-Project/motion/releases/download/release-4.0.1/pi_jessie_motion_4.0.1-1_armhf.deb'
+
+				#url/redireect always fails wget spider test...
+				/DietPi/dietpi/func/check_connection "http://github.com/Motion-Project/motion"
+				if (( $? == 0 )); then
+
+					# - Prereqs
+					AGI v4l-utils python python-dev curl libssl-dev libcurl4-openssl-dev libjpeg-dev zlib1g-dev libx264-142 libavcodec56 libavformat56 libmysqlclient18 libswscale3 libpq5
+
+					# - Motion
+					wget "$INSTALL_URL_ADDRESS" -O package.deb
+					dpkg -i package.deb
+					rm package.deb
+
+					# - Motioneye
+					pip install motioneye
+
+				else
+
+					Error_NoConnection_NoInstall
+
+				fi
+
+			#Stretch
+			else
 
 				# - Prereqs
-				AGI v4l-utils python python-dev curl libssl-dev libcurl4-openssl-dev libjpeg-dev libx264-142 libavcodec56 libavformat56 libmysqlclient18 libswscale3 libpq5
+				AGI v4l-utils python python-dev curl libssl-dev libcurl4-openssl-dev libjpeg-dev zlib1g-dev
 
-				# - Motion
-				wget "$INSTALL_URL_ADDRESS" -O package.deb
-				dpkg -i package.deb
-				rm package.deb
+				AGI motion
 
 				# - Motioneye
 				pip install motioneye
-
-			else
-
-				Error_NoConnection_NoInstall
 
 			fi
 
