v145
+ DietPi-Software | Blynk Server: Now available for installation:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=5901#p5901

diff --git a/dietpi/dietpi-software b/dietpi/dietpi-software
--- a/dietpi/dietpi-software
+++ b/dietpi/dietpi-software
@@ -228,7 +228,7 @@ _EOF_
 	# - Software
 	#NB: All software has a unique index that must not be changed (eg: DESKTOP_LXDE = 23)
 	TOTAL_SOFTWARE_INDEXS=0
-	TOTAL_SOFTWARE_INDEXS_HARDLIMIT=131	#Increase as needed. Must be higher than TOTAL_SOFTWARE_INDEXS once calculated in Software_Arrays_Init
+	TOTAL_SOFTWARE_INDEXS_HARDLIMIT=132	#Increase as needed. Must be higher than TOTAL_SOFTWARE_INDEXS once calculated in Software_Arrays_Init
 
 	INSTALLING_INDEX=0					#Which software index is currently being installed?
 
@@ -1318,6 +1318,15 @@ _EOF_
 			 aSOFTWARE_ONLINEDOC_URL[$index_current]='f=8&t=5&start=90#p4293'
 
 		#------------------
+		index_current=131
+
+				 aSOFTWARE_WHIP_NAME[$index_current]='Blynk Server'
+				 aSOFTWARE_WHIP_DESC[$index_current]='msg controller for blynk mobile app and sbcs'
+			aSOFTWARE_CATEGORY_INDEX[$index_current]=11
+					  aSOFTWARE_TYPE[$index_current]=0
+			 aSOFTWARE_ONLINEDOC_URL[$index_current]='f=8&t=5&p=5901#p5901'
+	   aSOFTWARE_REQUIRES_ORACLEJAVA[$index_current]=1
+
 
 		#System security
 		#--------------------------------------------------------------------------------
@@ -4170,6 +4179,31 @@ _EOF_
 				apt-get update
 
 				AGI mosquitto
+
+			else
+
+				Error_NoConnection_NoInstall
+
+			fi
+
+		fi
+
+		#Blynk Server
+		INSTALLING_INDEX=131
+		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
+
+			Banner_Installing
+
+			#Binary URL fails connection test, so we need to parent back a little: https://github.com/Fourdee/DietPi/issues/445#issuecomment-283400449
+			INSTALL_URL_ADDRESS='https://github.com/blynkkk/blynk-server/releases'
+			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
+
+			if (( $? == 0 )); then
+
+				mkdir -p /etc/blynkserver
+
+				INSTALL_URL_ADDRESS='https://github.com/blynkkk/blynk-server/releases/download/v0.22.3/server-0.22.3.jar'
+				wget "$INSTALL_URL_ADDRESS" -O /etc/blynkserver/server.jar
 
 			else
 
@@ -9323,6 +9357,29 @@ _EOF_
 
 		fi
 
+		#Blynk
+		INSTALLING_INDEX=131
+		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then
+
+			# - service
+			local fp_java_binary=$(which java)
+
+			mkdir -p "$FP_DIETPI_USERDATA_DIRECTORY"/blynk
+
+			cat << _EOF_ > /etc/systemd/system/blynkserver.service
+[Unit]
+Description=Blynk Server
+After=network.target
+
+[Service]
+Type=simple
+ExecStart=$fp_java_binary -jar /etc/blynkserver/server.jar -dataFolder $FP_DIETPI_USERDATA_DIRECTORY/blynk
+
+[Install]
+WantedBy=multi-user.target
+_EOF_
+
+		fi
 		#-------------------------------------------------------------------
 
 	}
@@ -9610,6 +9667,17 @@ _EOF_
 
 			rm -R /var/www/ompd
 			mysqladmin -u root -p"$GLOBAL_PW" drop ompd -f
+
+		elif (( $1 == 130 )); then
+
+			AGP python-pip
+
+		elif (( $1 == 131 )); then
+
+			rm /etc/systemd/system/blynkserver.service
+			systemctl daemon-reload
+
+			rm -R /etc/blynkserver
 
 		elif (( $1 == 119 )); then
 
