v6.19
+ DietPi-Patch | Patch software config file renaming

diff --git a/dietpi/patch_file b/dietpi/patch_file
--- a/dietpi/patch_file
+++ b/dietpi/patch_file
@@ -1374,6 +1374,43 @@ You will not face any practical differences, since both services start the same 
 
 			unset afp_config_remove
 			#-------------------------------------------------------------------------------
+			#conf renaming: https://github.com/Fourdee/DietPi/pull/2312/files
+			if [[ -f /etc/apache2/sites-available/owncloud.conf ]]; then
+
+				a2dissite owncloud
+				mv /etc/apache2/sites-available/owncloud.conf /etc/apache2/sites-available/dietpi-owncloud.conf
+				a2ensite dietpi-owncloud
+
+			fi
+			if [[ -f /etc/apache2/sites-available/nextcloud.conf ]]; then
+
+				a2dissite nextcloud
+				mv /etc/apache2/sites-available/nextcloud.conf /etc/apache2/sites-available/dietpi-nextcloud.conf
+				a2ensite dietpi-nextcloud
+
+			fi
+			if [[ -f /etc/apache2/sites-available/rutorrent.conf ]]; then
+
+				a2dissite rutorrent
+				mv /etc/apache2/sites-available/rutorrent.conf /etc/apache2/sites-available/dietpi-rutorrent.conf
+				a2ensite dietpi-rutorrent
+
+			fi
+			[[ -f /etc/nginx/sites-dietpi/owncloud.config ]] && mv /etc/nginx/sites-dietpi/owncloud.config /etc/nginx/conf.d/dietpi-owncloud.conf
+			[[ -f /etc/nginx/sites-dietpi/nextcloud.config ]] && mv /etc/nginx/sites-dietpi/nextcloud.config /etc/nginx/conf.d/dietpi-nextcloud.conf
+			[[ -f /etc/nginx/sites-dietpi/rutorrent.config ]] && mv /etc/nginx/sites-dietpi/rutorrent.config /etc/nginx/conf.d/dietpi-rutorrent.conf
+			[[ -f /etc/nginx/sites-dietpi/dietpi-pydio.config ]] && mv /etc/nginx/sites-dietpi/dietpi-pydio.config /etc/nginx/conf.d/dietpi-pydio.conf
+			[[ -f /etc/nginx/sites-dietpi/dietpi-dav_redirect.config ]] && mv /etc/nginx/sites-dietpi/dietpi-dav_redirect.config /etc/nginx/conf.d/dietpi-dav_redirect.conf
+			# - Failsafe and custom entries
+			for i in /etc/nginx/sites-dietpi/*.config
+			do
+
+				[[ -f $i ]] || break
+				mv $i /etc/nginx/conf.d/
+
+			do
+			[[ -d /etc/nginx/sites-dietpi ]] && rm -R /etc/nginx/sites-dietpi			[[ -f /etc/udev/rules.d/99-input.rules ]] && mv /etc/udev/rules.d/99-input.rules /etc/udev/rules.d/99-dietpi-kodi.rules
+			#-------------------------------------------------------------------------------
 			#Asus TB 2.0.8 image, fix corrupt characters in desktops
 			if (( $G_HW_MODEL == 52 )) && dpkg --get-selections | grep -q 'fonts-dejavu-core'; then
 
@@ -1387,7 +1424,7 @@ You will not face any practical differences, since both services start the same 
 			#	Allo GUI: https://github.com/Fourdee/DietPi/issues/2305
 			#	GMrender: Due to Allo GUI service enable failure.
 			#	Xorg: XU4 conf
-			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/dietpi-software reinstall 113 160 163 6
+			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/dietpi-software reinstall 48 113 160 163 6
 			#-------------------------------------------------------------------------------
 
 		fi
