v6.23
+ DietPi-Patch | Cleanup and fix masked/enabled serial-getty instances for non-existent serial devices

diff --git a/dietpi/patch_file b/dietpi/patch_file
--- a/dietpi/patch_file
+++ b/dietpi/patch_file
@@ -1707,6 +1707,32 @@ NB: When accessing "deluge-console" you need to do that as user "debian-deluged"
 			fi
 			#-------------------------------------------------------------------------------
 
+		elif (( $G_DIETPI_VERSION_SUB == 22 )); then
+
+			#-------------------------------------------------------------------------------
+			# Apply Serial/UART rework: https://github.com/MichaIng/DietPi/pull/2678
+			# - Cleanup: Remove serial-getty masks for all non-existent serial devices
+			for i in /etc/systemd/system/serial-getty@tty{S,AMA,SAC}[0-9].service
+			do
+
+				[[ -L $i && $(readlink $i) == '/dev/null' ]] || continue
+				local tty=${i##*serial-getty@}
+				tty=${tty%.service}
+				[[ -e /dev/$tty ]] || systemctl unmask serial-getty@$tty
+
+			done
+			# - Fix: Disable serial-getty instances for all non-existent serial devices
+			for i in /etc/systemd/system/getty.target.wants/serial-getty@tty{S,AMA,SAC}[0-9].service
+			do
+
+				[[ -L $i ]] || continue
+				local tty=${i##*serial-getty@}
+				tty=${tty%.service}
+				[[ -e /dev/$tty ]] || systemctl disable serial-getty@$tty
+
+			done
+			#-------------------------------------------------------------------------------
+
 		fi
 
 		#-------------------------------------------------------------------------------
