v6.34
+ DietPi-Patch | Update ASIX kernel driver only on RPi CM 3+ (=USBridgeSig) and only for v7+ kernel

diff --git a/dietpi/patch_file b/dietpi/patch_file
--- a/dietpi/patch_file
+++ b/dietpi/patch_file
@@ -2470,53 +2470,6 @@ To reinstall now, run: "dietpi-software reinstall 106 144 145"
 		elif (( $G_DIETPI_VERSION_SUB == 32 )); then
 
 			#-------------------------------------------------------------------------------
-			# RPi: Update USBridgeSig Ethernet driver via postinst kernel script, until it has been merged into official RPi kernel: https://github.com/allocom/USBridgeSig/tree/master/ethernet
-			if (( $G_HW_MODEL < 10 )); then
-
-				cat << '_EOF_' > /etc/kernel/postinst.d/dietpi-USBridgeSig
-#!/bin/bash
-# Only available for v7+ and v8+ kernel
-[[ $1 == *'-v'[78]'+' ]] || exit 0
-echo "[ INFO ] Updating ASIX AX88179 driver for kernel $1 with ARM-optimised builds"
-echo '[ INFO ] - by Allo: https://github.com/allocom/USBridgeSig/tree/master/ethernet'
-echo '[ INFO ] Estimating required module layout...'
-module_layout=$(modprobe --dump-modversions /lib/modules/$1/kernel/drivers/net/usb/asix.ko | mawk '/module_layout/{print $1;exit}') || exit 0
-echo '[ INFO ] Downloading stable branch driver...'
-if ! curl -#fL http://3.230.113.73:9011/Allocom/USBridgeSig/stable_rel/rpi-usbs-$1/ax88179_178a.ko -o /tmp/ax88179_178a.ko ||
-	[[ $module_layout != $(modprobe --dump-modversions /tmp/ax88179_178a.ko | mawk '/module_layout/{print $1;exit}') ]]; then
-
-	echo '[ INFO ] No matching stable branch driver found, trying master branch driver...'
-	if ! curl -#fL http://3.230.113.73:9011/Allocom/USBridgeSig/rpi-usbs-$1/ax88179_178a.ko -o /tmp/ax88179_178a.ko ||
-		[[ $module_layout != $(modprobe --dump-modversions /tmp/ax88179_178a.ko | mawk '/module_layout/{print $1;exit}') ]]; then
-
-		echo '[ INFO ] No matching driver found, cleaning up and aborting...'
-		rm -fv /tmp/ax88179_178a.ko || :
-		echo '[ INFO ] Do not worry, the default RPi kernel driver will be used instead.'
-		exit 0
-
-	fi
-
-fi
-echo '[ INFO ] Installing driver...'
-install -vpm 644 /tmp/ax88179_178a.ko /lib/modules/$1/kernel/drivers/net/usb || exit 0
-echo '[ INFO ] Running depmod...'
-depmod $1 || exit 0
-echo '[ INFO ] All succeeded, cleaning up...'
-rm -v /tmp/ax88179_178a.ko || exit 0
-_EOF_
-				chmod +x /etc/kernel/postinst.d/dietpi-USBridgeSig
-				# Update for all installed v7+ and v8+ kernel versions now
-				for i in /lib/modules/*-v[78]+
-				do
-
-					[[ -d $i ]] || continue
-					i=${i##*/}
-					/etc/kernel/postinst.d/dietpi-USBridgeSig "$i"
-
-				done
-
-			fi
-			#-------------------------------------------------------------------------------
 			# Update config file names
 			[[ -f '/etc/X11/xorg.conf.d/99-dietpi-dpms_off.conf' ]] && mv -v /etc/X11/xorg.conf.d/9{9-dietpi-dpms_off,8-dietpi-disable_dpms}.conf
 			#-------------------------------------------------------------------------------
@@ -2660,6 +2613,48 @@ _EOF_
 				[[ $gpu_mem_current ]] || gpu_mem_current=$(sed -n "/^[[:blank:]]*gpu_mem=/{s/^[^=]*=//p;q}" /boot/config.txt) # base setting
 				[[ $gpu_mem_current ]] || gpu_mem_current=64 # default value
 				(( $gpu_mem_current < 32 )) && /boot/dietpi/func/dietpi-set_hardware gpumemsplit $gpu_mem_current
+			#-------------------------------------------------------------------------------
+			# RPi CM 3+: Update USBridgeSig Ethernet driver via postinst kernel script, until it has been merged into official RPi kernel: https://github.com/allocom/USBridgeSig/tree/master/ethernet
+				cat << '_EOF_' > /etc/kernel/postinst.d/dietpi-USBridgeSig
+#!/bin/bash
+# Only available for v7+
+[[ $1 == *'-v7+' ]] || exit 0
+# Only reasonable for USBridgeSig = CM 3+
+grep -q '^Revision.*10.$' /proc/cpuinfo || exit 0
+echo "[ INFO ] Updating ASIX AX88179 driver for kernel $1 with ARM-optimised build"
+echo '[ INFO ] - by Allo: https://github.com/allocom/USBridgeSig/tree/master/ethernet'
+echo '[ INFO ] Estimating required module layout...'
+module_layout=$(modprobe --dump-modversions /lib/modules/$1/kernel/drivers/net/usb/asix.ko | mawk '/module_layout/{print $1;exit}') || exit 0
+echo '[ INFO ] Downloading stable branch driver...'
+if ! curl -#fL http://3.230.113.73:9011/Allocom/USBridgeSig/stable_rel/rpi-usbs-$1/ax88179_178a.ko -o /tmp/ax88179_178a.ko ||
+	[[ $module_layout != $(modprobe --dump-modversions /tmp/ax88179_178a.ko | mawk '/module_layout/{print $1;exit}') ]]
+then
+	echo '[ INFO ] No matching stable branch driver found, trying master branch driver...'
+	if ! curl -#fL http://3.230.113.73:9011/Allocom/USBridgeSig/rpi-usbs-$1/ax88179_178a.ko -o /tmp/ax88179_178a.ko ||
+		[[ $module_layout != $(modprobe --dump-modversions /tmp/ax88179_178a.ko | mawk '/module_layout/{print $1;exit}') ]]
+	then
+		echo '[ INFO ] No matching driver found, cleaning up and aborting...'
+		rm -fv /tmp/ax88179_178a.ko || :
+		echo '[ INFO ] The default RPi kernel driver will be used instead, which might result in pops and ticks in your audio stream. If so, please try to rerun this script later:'
+		echo " - /etc/kernel/postinst.d/dietpi-USBridgeSig $1"
+		exit 0
+	fi
+fi
+echo '[ INFO ] Installing driver...'
+install -vpm 644 /tmp/ax88179_178a.ko /lib/modules/$1/kernel/drivers/net/usb || exit 0
+echo '[ INFO ] Running depmod...'
+depmod $1 || exit 0
+echo '[ INFO ] All succeeded, cleaning up...'
+rm -v /tmp/ax88179_178a.ko || exit 0
+_EOF_
+				chmod +x /etc/kernel/postinst.d/dietpi-USBridgeSig
+				# Run for all installed v7+ kernel versions now
+				for i in /lib/modules/*-v7+
+				do
+					[[ -d $i ]] || continue
+					i=${i##*/}
+					/etc/kernel/postinst.d/dietpi-USBridgeSig "$i"
+				done
 			fi
 			#-------------------------------------------------------------------------------
 			# MineOS reinstall to migrate from supervisor to systemd unit: https://github.com/MichaIng/DietPi/pull/3904
