v6.23
+ DietPi-Patch | Upgrade Nextcloud versions until 14 incrementally, which is required for PHP7.3
+ DietPi-Patch | Purge old PHP packages actively since at least some PHP7.0 packages somehow survive autoremove even without any dependencies or required/essential marked ones

diff --git a/dietpi/patch_file b/dietpi/patch_file
--- a/dietpi/patch_file
+++ b/dietpi/patch_file
@@ -1772,9 +1772,10 @@ Further info and usage: https://dietpi.com/phpbb/viewtopic.php?f=8&t=5828'
 				#-----------------------------------------------------------------------
 				# PHP7.3 migration: https://github.com/MichaIng/DietPi/issues/2367
 				local reinstall_ids=''
+				local upgrade_php=0
 				if grep -q '^aSOFTWARE_INSTALL_STATE\[89\]=2' /DietPi/dietpi/.installed; then
 
-					# ownCloud does not yet support PHP7.3, so use PHP7.2 here for now...
+					# ownCloud (up to v10.2) does not yet support PHP7.3, so install PHP7.2 for now
 					local PHP_NAME='php7.3'
 					[[ -f '/var/www/owncloud/occ' ]] && PHP_NAME='php7.2'
 
@@ -1785,19 +1786,69 @@ Further info and usage: https://dietpi.com/phpbb/viewtopic.php?f=8&t=5828'
 Your PHP instance will be upgraded to ${PHP_NAME^^}. This enhances security and performance of your web applications and is required to run some of the latest web application version, e.g. Nextcloud 16, ownCloud 10.2 and others.\n
 We will update webserver configurations and backup the whole /etc/php(5) directory to /mnt/dietpi_userdata/php(5)_bak, so you can recover custom setting modifications.\n
 NB: You must update all manually installed PHP-depending web applications that do not use webservers, to use the new ${PHP_NAME^^} socket/instance."
+						upgrade_php=1
+
+						# We need to upgrade Jessie Nextcloud users since NC13 does not support PHP7.3 yet. Check for NC < 14 in general and do incremental upgrading in case.
+						local upgrade_nextcloud=0
+						while [[ -f '/var/www/nextcloud/version.php' ]]
+						do
+
+							# - Estimate Nextcloud version, skip if higher than 13 or invalid
+							local nextcloud_version=$(grep '$OC_VersionString' /var/www/nextcloud/version.php | sed "s/^.*= '//" | sed 's/\..*$//g')
+							disable_error=1 G_CHECK_VALIDINT "$nextcloud_version" 9 13 || break
+
+							# - Inform user
+							G_WHIP_MSG '[ INFO ] Nextcloud will be upgraded\n
+Your Nextcloud (<=13) version does not yet support PHP7.3. On Jessie this is expected since Nextcloud 14 does not support PHP5.6 anymore.\n
+We will upgrade your Nextcloud version to Nextcloud 14 to allow upgrading to PHP7.3.\n
+We will create full backup of your install directory and database and your data will not be touched.'
+							upgrade_nextcloud=1
+
+							# - Backup database and install dir: Use our cloud migration script
+							#	In case of failure, exit to not create any damage
+							G_CHECK_URL 'https://raw.githubusercontent.com/MichaIng/DietPi/master/.meta/dietpi-cloud-migration'
+							G_ERROR_HANDLER_COMMAND='Nextcloud backup'
+							G_ERROR_HANDLER_RETRY=0
+							curl -sSL 'https://raw.githubusercontent.com/MichaIng/DietPi/master/.meta/dietpi-cloud-migration' | bash
+							G_ERROR_HANDLER_EXITCODE=$?
+							G_ERROR_HANDLER
+
+							# - Incremental upgrade since skipping major versions is not supported.
+							until (( $nextcloud_version > 13 ))
+							do
+
+								((nextcloud_version++))
+								G_CHECK_URL https://download.nextcloud.com/server/releases/latest-$nextcloud_version.tar.bz2
+								G_RUN_CMD wget https://download.nextcloud.com/server/releases/latest-$nextcloud_version.tar.bz2
+								G_RUN_CMD rm -R /var/www/nextcloud
+								G_RUN_CMD tar xf latest-$nextcloud_version.tar.bz2 -C /var/www
+								G_RUN_CMD cp -a /mnt/dietpi_userdata/nextcloud_data/dietpi-nextcloud-installation-backup/config/config.php /var/www/nextcloud/config/config.php
+								# - Restore custom apps but prevent overwriting upgraded ones or adding obsolete files
+								for i in /mnt/dietpi_userdata/nextcloud_data/dietpi-nextcloud-installation-backup/apps/*
+								do
+
+									[[ -d /var/www/nextcloud/apps/${i##*/} ]] || G_RUN_CMD cp -a $i /var/www/nextcloud/apps/
+
+								done
+								# - Permissions
+								G_RUN_CMD chown -R www-data:www-data /var/www/nextcloud
+								G_RUN_CMD find /var/www/nextcloud/ -type d -exec chmod 750 {} \;
+								G_RUN_CMD find /var/www/nextcloud/ -type f -exec chmod 640 {} \;
+								# - Upgrade until NC13, then upgrade after PHP7.3 has been installed, since NC13 does not support PHP5.6 anymore
+								(( $nextcloud_version < 14 )) && { ncc upgrade || exit 1; }
+
+							done
+							break
+
+						done
 
 						[[ -d '/etc/php' ]] && G_RUN_CMD cp -a /etc/php /mnt/dietpi_userdata/php_bak
 						[[ -d '/etc/php5' ]] && G_RUN_CMD cp -a /etc/php5 /mnt/dietpi_userdata/php5_bak
-
-						# - Mark existing PHP packages only to not purge dependencies, autoremove after dietpi-software installed PHP7.3
-						apt-mark auto $(dpkg --get-selections | grep -E '^(php[0-9.]*-|libapache2-mod-php)' | mawk '{print $1}')
 
 						# - Lighttpd
 						[[ -f '/etc/lighttpd/conf-available/15-fastcgi-php.conf' ]] && sed -i "s@\"socket\".*\$@\"socket\" => \"/run/php/$PHP_NAME-fpm.sock\",@" /etc/lighttpd/conf-available/15-fastcgi-php.conf
 						# - Nginx
 						[[ -f '/etc/nginx/nginx.conf' ]] && sed -i "s#/run/php.*-fpm.sock#/run/php/$PHP_NAME-fpm.sock#g" /etc/nginx/nginx.conf
-						# - Apache
-						phpdismod php5 php7.0 php7.1 &> /dev/null
 
 					fi
 
@@ -1818,8 +1869,16 @@ NB: You must update all manually installed PHP-depending web applications that d
 				fi
 				/DietPi/dietpi/dietpi-software reinstall 34 35 42 $reinstall_ids
 				#-----------------------------------------------------------------------
-				# Old PHP version autoremoval
-				G_AGA
+				# Remove old PHP version
+				if (( $upgrade_php )); then
+
+					G_AGP php{5,7.0,7.1}-* libapache2-mod-php{5,7.0,7.1}
+					[[ $PHP_NAME = 'php7.3' ]] && G_AGP php7.2-* libapache2-mod-php7.2
+
+					# Upgrade Nextcloud
+					(( $upgrade_nextcloud )) && ncc upgrade
+
+				fi
 
 			fi
 			#-------------------------------------------------------------------------------
