v6.33
+ DietPi-Patch | Update and reapply USBridgeSig Ethernet driver patch to try stable branch drivers first and abort on non-matching module layouts: https://github.com/MichaIng/DietPi/issues/3725

diff --git a/dietpi/patch_file b/dietpi/patch_file
--- a/dietpi/patch_file
+++ b/dietpi/patch_file
@@ -2426,37 +2426,6 @@ To reinstall now, run: "dietpi-software reinstall 106 144 145"
 			# APT configs have been merged into a single file, contained in update archive
 			rm -fv /etc/apt/apt.conf.d/{99-dietpi-norecommends,98-dietpi-no_translations,99-dietpi-forceconf}
 			#-------------------------------------------------------------------------------
-			# RPi: Update USBridgeSig Ethernet driver via postinst kernel script, until it has been merged into official RPi kernel: https://github.com/allocom/USBridgeSig/tree/master/ethernet
-			if (( $G_HW_MODEL < 10 )); then
-
-				cat << '_EOF_' > /etc/kernel/postinst.d/dietpi-USBridgeSig
-#!/bin/bash
-# Only apply to v7+ and v8+ kernel
-[[ $1 == *'-v'[78]'+' ]] || exit 0
-echo "[ INFO ] Updating asix ax88179 driver for kernel $1, as provided by allo.com:"
-echo '[ INFO ] - https://github.com/allocom/USBridgeSig/tree/master/ethernet'
-echo '[ INFO ] Downloading driver...'
-wget http://3.230.113.73:9011/Allocom/USBridgeSig/rpi-usbs-$1/ax88179_178a.ko -O /tmp/ax88179_178a.ko || exit 0
-echo '[ INFO ] Installing driver...'
-install -vpm 644 /tmp/ax88179_178a.ko /lib/modules/$1/kernel/drivers/net/usb || exit 0
-echo '[ INFO ] Running depmod...'
-depmod $1 || exit 0
-echo '[ INFO ] Cleaning up...'
-rm -v /tmp/ax88179_178a.ko || exit 0
-_EOF_
-				chmod +x /etc/kernel/postinst.d/dietpi-USBridgeSig
-				# Update for all installed v7+ and v8+ kernel versions now
-				for i in /lib/modules/*-v[78]+
-				do
-
-					[[ -d $i ]] || continue
-					i=${i##*/}
-					/etc/kernel/postinst.d/dietpi-USBridgeSig "$i"
-
-				done
-
-			fi
-			#-------------------------------------------------------------------------------
 			[[ -f '/boot/config.txt' ]] && G_EXEC_DESC='Removing deprecated "max_usb_current" from config.txt' G_EXEC_NOHALT=1 G_EXEC sed -i '/^[[:blank:]#]*max_usb_current=/d' /boot/config.txt
 			#-----------------------------------------------------------------------
 			# Recreate /etc/sysctl.d/99-sysctl.conf -> ../sysctl.conf symlink if not existent: https://github.com/MichaIng/DietPi/issues/3003#issuecomment-669464255
@@ -2503,6 +2472,52 @@ _EOF_
 
 		elif (( $G_DIETPI_VERSION_SUB == 32 )); then
 
+			#-------------------------------------------------------------------------------
+			# RPi: Update USBridgeSig Ethernet driver via postinst kernel script, until it has been merged into official RPi kernel: https://github.com/allocom/USBridgeSig/tree/master/ethernet
+			if (( $G_HW_MODEL < 10 )); then
+
+				cat << '_EOF_' > /etc/kernel/postinst.d/dietpi-USBridgeSig
+#!/bin/bash
+# Only available for v7+ and v8+ kernel
+[[ $1 == *'-v'[78]'+' ]] || exit 0
+echo "[ INFO ] Updating ASIX AX88179 driver for kernel $1, as provided by allo.com:"
+echo '[ INFO ] - https://github.com/allocom/USBridgeSig/tree/master/ethernet'
+echo '[ INFO ] Estimating required module layout...'
+module_layout=$(modprobe --dump-modversions /lib/modules/$1/kernel/drivers/net/usb/asix.ko | mawk '/module_layout/{print $1;exit}') || exit 0
+echo '[ INFO ] Downloading driver...'
+if ! curl -#fL http://3.230.113.73:9011/Allocom/USBridgeSig/stable_rel/rpi-usbs-$1/ax88179_178a.ko -o /tmp/ax88179_178a.ko ||
+	[[ $module_layout != $(modprobe --dump-modversions /tmp/ax88179_178a.ko | mawk '/module_layout/{print $1;exit}') ]]; then
+
+	echo '[ INFO ] No matching stable branch driver found, trying master branch driver...'
+	if ! curl -#fL http://3.230.113.73:9011/Allocom/USBridgeSig/rpi-usbs-$1/ax88179_178a.ko -o /tmp/ax88179_178a.ko ||
+		[[ $module_layout != $(modprobe --dump-modversions /tmp/ax88179_178a.ko | mawk '/module_layout/{print $1;exit}') ]]; then
+
+		echo '[ INFO ] No matching driver found, cleaning up and aborting...'
+		rm -fv /tmp/ax88179_178a.ko || :
+		exit 0
+
+	fi
+
+fi
+echo '[ INFO ] Installing driver...'
+install -vpm 644 /tmp/ax88179_178a.ko /lib/modules/$1/kernel/drivers/net/usb || exit 0
+echo '[ INFO ] Running depmod...'
+depmod $1 || exit 0
+echo '[ INFO ] Cleaning up...'
+rm -v /tmp/ax88179_178a.ko || exit 0
+_EOF_
+				chmod +x /etc/kernel/postinst.d/dietpi-USBridgeSig
+				# Update for all installed v7+ and v8+ kernel versions now
+				for i in /lib/modules/*-v[78]+
+				do
+
+					[[ -d $i ]] || continue
+					i=${i##*/}
+					/etc/kernel/postinst.d/dietpi-USBridgeSig "$i"
+
+				done
+
+			fi
 			#-------------------------------------------------------------------------------
 			# Update config file names
 			[[ -f '/etc/X11/xorg.conf.d/99-dietpi-dpms_off.conf' ]] && mv -v /etc/X11/xorg.conf.d/9{9-dietpi-dpms_off,8-dietpi-disable_dpms}.conf
