v93

diff --git a/dietpi/patch_file b/dietpi/patch_file
--- a/dietpi/patch_file
+++ b/dietpi/patch_file
@@ -599,6 +599,21 @@ _EOF_
 	elif (( $VERSION_CURRENT == 92 )); then
 		echo -e "92 > 93 patch"
 		#-------------------------------------------------------------------------------
+		#Cleanup left over flag files from old ramlog.
+		rm /var/tmp/ramlog* &> /dev/null
+		#-------------------------------------------------------------------------------
+		#opcache-gui changed to opcache-status
+		if (( $DISTRO == 2 )) || (( $DISTRO == 3 )); then
+			if [ -f /var/www/apc.php ]; then
+				wget https://raw.githubusercontent.com/rlerdorf/opcache-status/master/opcache.php -O /var/www/apc.php
+			fi
+		fi
+		#-------------------------------------------------------------------------------
+		#VM image, missing zip package.
+		if (( $HW_MODEL == 20 )); then
+			/DietPi/dietpi/dietpi-apt-get_update 1
+			apt-get install zip -y
+		fi
 		#-------------------------------------------------------------------------------
 
 	fi
