v6.32
+ DietPi-PostBoot | Give custom boot script notifications colour

diff --git a/dietpi/postboot b/dietpi/postboot
--- a/dietpi/postboot
+++ b/dietpi/postboot
@@ -35,8 +35,8 @@
 
 		[[ $f != *'/readme.txt' && -f $f ]] || continue
 		[[ -x $f ]] || chmod +x $f
-		echo "[ INFO ] DietPi-PostBoot | Running user script: ${f##*/}"
-		$f || { EXIT_CODE=$?; echo "[FAILED] DietPi-PostBoot | User script ${f##*/} failed with exit code: $EXIT_CODE"; }
+		echo -e "\e[90m[\e[0m INFO \e[90m] DietPi-PostBoot | Running user script: ${f##*/}\e[0m"
+		$f || { EXIT_CODE=$?; echo -e "\e[90m[\e[31mFAILED\e[90m] DietPi-PostBoot |\e[0m User script ${f##*/} failed with exit code: $EXIT_CODE"; }
 
 	done
 
