v6.32
+ DietPi-PostBoot | No boot logs are to be moved to disk anymore
+ DietPi-PostBoot | Add exit code handling and error message for user scripts and service starts

diff --git a/dietpi/postboot b/dietpi/postboot
--- a/dietpi/postboot
+++ b/dietpi/postboot
@@ -10,16 +10,13 @@
 	#
 	# Info:
 	# - Location: /boot/dietpi/postboot
-	# - Moves boot logs from /tmp to persistent dir
 	# - DietPi-Update check and DietPi-Services start on regular boot
 	# - Executes optional user scripts from: /var/lib/dietpi/postboot.d/
 	# - Prints login banner
 	#////////////////////////////////////
 
+	EXIT_CODE=0
 	G_DIETPI_INSTALL_STAGE=$(</boot/dietpi/.install_stage)
-
-	# Move all boot logs to disk
-	mv /tmp/dietpi-*.log /var/tmp/dietpi/logs/ &
 
 	# Regular boot
 	if [[ $G_DIETPI_INSTALL_STAGE == 2 ]]; then
@@ -28,7 +25,7 @@
 		grep -q '^[[:blank:]]*CONFIG_CHECK_DIETPI_UPDATES=1' /boot/dietpi.txt && /boot/dietpi/dietpi-update 2 &> /dev/null &
 
 		# Start DietPi controlled services
-		/boot/dietpi/dietpi-services start
+		/boot/dietpi/dietpi-services start || EXIT_CODE=$?
 
 	fi
 
@@ -38,8 +35,8 @@
 
 		[[ $f != *'/readme.txt' && -f $f ]] || continue
 		[[ -x $f ]] || chmod +x $f
-		echo "DietPi-PostBoot | Running user script: ${f##*/}"
-		$f
+		echo "[ INFO ] DietPi-PostBoot | Running user script: ${f##*/}"
+		$f || { EXIT_CODE=$?; echo "[FAILED] DietPi-PostBoot | User script ${f##*/} failed with exit code: $EXIT_CODE"; }
 
 	done
 
@@ -55,6 +52,6 @@
 	fi
 
 	#-----------------------------------------------------------------------------------
-	exit
+	exit $EXIT_CODE
 	#-----------------------------------------------------------------------------------
 }
