v8.15
- DietPi-PostBoot | Further tweak script, removing exit code handling here

diff --git a/dietpi/postboot b/dietpi/postboot
--- a/dietpi/postboot
+++ b/dietpi/postboot
@@ -13,8 +13,7 @@
 	# - Run on boot from dietpi-postboot.service after dietpi-preboot.service and optionally after network
 	#////////////////////////////////////
 
-	EXIT_CODE=0
-	G_DIETPI_INSTALL_STAGE=$(</boot/dietpi/.install_stage)
+	read -r G_DIETPI_INSTALL_STAGE < /boot/dietpi/.install_stage
 
 	# Pre-installed image, 1st run
 	if [ "$G_DIETPI_INSTALL_STAGE" = 10 ]
@@ -27,11 +26,10 @@
 
 		# Continue with normal boot
 		echo 2 > /boot/dietpi/.install_stage
-		G_DIETPI_INSTALL_STAGE=2
 	fi
 
 	# Regular boot
-	if [ "$G_DIETPI_INSTALL_STAGE" = 2 ]
+	if [ "$G_DIETPI_INSTALL_STAGE" = 2 ] || [ "$G_DIETPI_INSTALL_STAGE" = 10 ]
 	then
 		# Run network time sync and check for DietPi updates if chosen, both in background
 		if grep -q '^[[:blank:]]*CONFIG_CHECK_DIETPI_UPDATES=1' /boot/dietpi.txt
@@ -43,7 +41,7 @@
 		fi
 
 		# Start DietPi controlled services
-		/boot/dietpi/dietpi-services start || EXIT_CODE=$?
+		/boot/dietpi/dietpi-services start
 	fi
 
 	# Execute optional user scripts
@@ -52,7 +50,7 @@
 		[ "${f##*/}" != 'readme.txt' ] && [ -f "$f" ] || continue
 		[ -x "$f" ] || chmod +x "$f"
 		echo "\e[90m[\e[0m INFO \e[90m] DietPi-PostBoot | Running user script: ${f##*/}\e[0m"
-		"$f" || { EXIT_CODE=$?; echo "\e[90m[\e[31mFAILED\e[90m] DietPi-PostBoot |\e[0m User script ${f##*/} failed with exit code: $EXIT_CODE"; }
+		"$f" || echo "\e[90m[\e[31mFAILED\e[90m] DietPi-PostBoot |\e[0m User script ${f##*/} failed with exit code: $?"
 	done
 
 	# Print DietPi login banner if no autologin selected
@@ -66,6 +64,6 @@
 	fi
 
 	#-----------------------------------------------------------------------------------
-	exit "$EXIT_CODE"
+	exit 0
 	#-----------------------------------------------------------------------------------
 }
