v8.15
- DietPi-PostBoot | Do not strictly depend on DietPi-PreBoot and turn the script into POSIX/bourne shell complicant
- DietPi-PreBoot | Skip set CPU script in container
- DietPi-Config | Hide performance options in container

diff --git a/dietpi/postboot b/dietpi/postboot
--- a/dietpi/postboot
+++ b/dietpi/postboot
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/dash
 {
 	#////////////////////////////////////
 	# DietPi PostBoot Script
@@ -10,17 +10,14 @@
 	#
 	# Info:
 	# - Location: /boot/dietpi/postboot
-	# - Handles install stage for pre-installed images (AlloGUI)
-	# - Network time sync, DietPi-Update check and DietPi-Services start on regular boot
-	# - Executes optional user scripts from: /var/lib/dietpi/postboot.d/
-	# - Prints login banner
+	# - Run on boot from dietpi-postboot.service after dietpi-preboot.service and optionally after network
 	#////////////////////////////////////
 
 	EXIT_CODE=0
 	G_DIETPI_INSTALL_STAGE=$(</boot/dietpi/.install_stage)
 
 	# Pre-installed image, 1st run
-	if [[ $G_DIETPI_INSTALL_STAGE == 10 ]]
+	if [ "$G_DIETPI_INSTALL_STAGE" = 10 ]
 	then
 		# Create swap file
 		/boot/dietpi/func/dietpi-set_swapfile
@@ -34,7 +31,7 @@
 	fi
 
 	# Regular boot
-	if [[ $G_DIETPI_INSTALL_STAGE == 2 ]]
+	if [ "$G_DIETPI_INSTALL_STAGE" = 2 ]
 	then
 		# Run network time sync and check for DietPi updates if chosen, both in background
 		if grep -q '^[[:blank:]]*CONFIG_CHECK_DIETPI_UPDATES=1' /boot/dietpi.txt
@@ -52,20 +49,20 @@
 	# Execute optional user scripts
 	for f in /var/lib/dietpi/postboot.d/*
 	do
-		[[ $f != *'/readme.txt' && -f $f ]] || continue
-		[[ -x $f ]] || chmod +x "$f"
-		echo -e "\e[90m[\e[0m INFO \e[90m] DietPi-PostBoot | Running user script: ${f##*/}\e[0m"
-		"$f" || { EXIT_CODE=$?; echo -e "\e[90m[\e[31mFAILED\e[90m] DietPi-PostBoot |\e[0m User script ${f##*/} failed with exit code: $EXIT_CODE"; }
+		[ "${f##*/}" != 'readme.txt' ] && [ -f "$f" ] || continue
+		[ -x "$f" ] || chmod +x "$f"
+		echo "\e[90m[\e[0m INFO \e[90m] DietPi-PostBoot | Running user script: ${f##*/}\e[0m"
+		"$f" || { EXIT_CODE=$?; echo "\e[90m[\e[31mFAILED\e[90m] DietPi-PostBoot |\e[0m User script ${f##*/} failed with exit code: $EXIT_CODE"; }
 	done
 
 	# Print DietPi login banner if no autologin selected
-	if [[ ! -f '/etc/systemd/system/getty@tty1.service.d/dietpi-autologin.conf' ]]
+	if [ ! -f '/etc/systemd/system/getty@tty1.service.d/dietpi-autologin.conf' ]
 	then
 		echo
 		/boot/dietpi/func/dietpi-banner 0
 		# Print default login credentials only on first boot
-		[[ $G_DIETPI_INSTALL_STAGE == 2 ]] || echo -e '\n Default Login:\n Username = root\n Password = dietpi (or custom dietpi.txt entry)'
-		echo -e '\n Please hit <return> to login\n'
+		[ "$G_DIETPI_INSTALL_STAGE" = 2 ] || echo '\n Default Login:\n Username = root\n Password = dietpi (or custom dietpi.txt entry)'
+		echo '\n Please hit <return> to login\n'
 	fi
 
 	#-----------------------------------------------------------------------------------
