v6.19.7
+ DietPi-Pre-Patch | Prevent dietpi-software patch to be applied multiple times
+ DietPi-Pre-Patch | Syntax: Correctly escape single quotes within single quotes

diff --git a/dietpi/pre-patch_file b/dietpi/pre-patch_file
--- a/dietpi/pre-patch_file
+++ b/dietpi/pre-patch_file
@@ -93,15 +93,19 @@
 
 			if (( $(sed -n 1p /DietPi/dietpi/.hw_model) > 10 )); then
 
-				echo -e '[ \e[1mINFO\e[0m ] Pre-patch 5 | Docker: Prevent install of a faulty "docker-ce" version in their APT repository'
-				sed -i '\|INSTALL_URL_ADDRESS=\'https://get.docker.com\'|a\echo \'Package: docker-ce
+				if ! grep -q '/etc/apt/preferences.d/dietpi-docker_fix' /DietPi/dietpi/dietpi-software; then
+
+					echo -e '[ \e[1mINFO\e[0m ] Pre-patch 5 | Docker: Prevent install of a faulty "docker-ce" version in their APT repository'
+					sed -i '\|INSTALL_URL_ADDRESS=\'https://get.docker.com\'|a\echo \'Package: docker-ce
 Pin: version 5:18.09.0~3-0~debian-stretch
 Pin-Priority: -1\' > /etc/apt/preferences.d/dietpi-docker_fix' /DietPi/dietpi/dietpi-software
-				(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 5 | An error occurred while applying the fix to: /DietPi/dietpi/dietpi-software
- - Please apply it manually. Add the following lines after INSTALL_URL_ADDRESS=\'https://get.docker.com\':
-	echo \'Package: docker-ce
+					(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 5 | An error occurred while applying the fix to: /DietPi/dietpi/dietpi-software
+ - Please apply it manually. Add the following lines after INSTALL_URL_ADDRESS='\''https://get.docker.com'\'':
+	echo '\''Package: docker-ce
 	Pin: version 5:18.09.0~3-0~debian-stretch
-	Pin-Priority: -1\' > /etc/apt/preferences.d/dietpi-docker_fix'
+	Pin-Priority: -1'\'' > /etc/apt/preferences.d/dietpi-docker_fix'
+
+				fi
 
 				if dpkg -l | grep -q '5:18.09.0~3-0~debian-stretch'; then
 
