v6.19.6
+ DietPi-Pre-Patch | Applying "force-reload" error fix to dietpi-software

diff --git a/dietpi/pre-patch_file b/dietpi/pre-patch_file
--- a/dietpi/pre-patch_file
+++ b/dietpi/pre-patch_file
@@ -55,6 +55,7 @@
 
 		#-------------------------------------------------------------------------------
 		# Pre-patch 2: Hotfix to apply new naming scheme for /etc/nginx/sites-dietpi/*.(config => conf): https://github.com/Fourdee/DietPi/issues/2325#issuecomment-444564109
+		# Pre-patch 3: Fix "systemctl force-reload" error in DietPi-Software 
 		elif [[ $G_DIETPI_VERSION_SUB.$(sed -n 4p /DietPi/dietpi/.version) == '19.G_DIETPI_VERSION_RC=5' ]]; then
 
 			if grep -q 'include /etc/nginx/sites-dietpi/\*\.config;' /etc/nginx/sites-available/default &> /dev/null; then
@@ -67,11 +68,15 @@
 	include /etc/nginx/sites-dietpi/*.conf;'
 				/DietPi/dietpi/dietpi-services start
 
-			else
-
-				echo -e '[ e[1mINFO\e[0m ] The hotfix done with this update does not apply for you.'
-
 			fi
+
+			echo -e '[ \e[1mINFO\e[0m ] Pre-patch 3 | DietPi-Software: Resolving "systemctl force-reload" error in case of inactive services'
+			sed -Ei 's/G_RUN_CMD systemctl force-reload (lighttpd|nginx|apache2)/G_RUN_CMD systemctl restart \1/g' /DietPi/dietpi/dietpi-software
+			(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 3 | An error occured while applying the fix to: /DietPi/dietpi/dietpi-software
+ - Please apply it manually. Replace the 3 lines:
+ 	G_RUN_CMD systemctl force-reload lighttpd|nginx|apache2		with
+	G_RUN_CMD systemctl restart lighttpd|nginx|apache2		respectively'
+
 			echo 0 > /DietPi/dietpi/.update_stage
 			sed -i '/G_DIETPI_VERSION_RC=/c\G_DIETPI_VERSION_RC=6' /DietPi/dietpi/.version
 			echo -e '[ \e[1mINFO\e[0m ] DietPi-Update will now exit. No reboot is required, no further update steps are done.
