v6.19.7
+ DietPi-Patch | DietPi-Software: Patch netdata uninstall from breaking system

diff --git a/dietpi/pre-patch_file b/dietpi/pre-patch_file
--- a/dietpi/pre-patch_file
+++ b/dietpi/pre-patch_file
@@ -42,9 +42,9 @@
 	while (( $EXIT_CODE == 0 ))
 	do
 
-		echo -e "\n\e[1m $G_PROGRAM_NAME\e[0m
+		echo -e "\n \e[1m$G_PROGRAM_NAME\e[0m
 \e[90m─────────────────────────────────────────────────────\e[0m
-[ INFO ] Applying critical pre-patches\n"
+[ \e[1mINFO\e[0m ] Applying critical pre-patches\n"
 
 		#-------------------------------------------------------------------------------
 		# Pre-patch 1: RAMlog 0 free space check due to issues with failing DietPi cron jobs in v6.11
@@ -77,9 +77,23 @@
  	G_RUN_CMD systemctl force-reload lighttpd|nginx|apache2		with
 	G_RUN_CMD systemctl restart lighttpd|nginx|apache2		respectively'
 
+			sed -i '/G_DIETPI_VERSION_RC=/c\G_DIETPI_VERSION_RC=6' /DietPi/dietpi/.version
+
+		fi
+		#-------------------------------------------------------------------------------
+		# Pre-patch 4: Prevent netdata uninstall from breaking the system: https://github.com/Fourdee/DietPi/issues/2336
+		if [[ $G_DIETPI_VERSION_SUB.$(sed -n 4p /DietPi/dietpi/.version) == '19.G_DIETPI_VERSION_RC=6' ]]; then
+		
+			echo -e '[ \e[1mINFO\e[0m ] Pre-patch 4 | Fix a critical issue, where uninstalling netdata would break the whole system'
+			sed -i 's/userdel -rf netdata/userdel netdata/g' /DietPi/dietpi/dietpi-software
+			(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 4 | An error occured while applying the fix to: /DietPi/dietpi/dietpi-software
+ - Please apply it manually. Replace the line:
+ 	userdel -rf netdata	with
+	userdel netdata'
+
 			echo 0 > /DietPi/dietpi/.update_stage
 			rm /DietPi/dietpi/.update_available
-			sed -i '/G_DIETPI_VERSION_RC=/c\G_DIETPI_VERSION_RC=6' /DietPi/dietpi/.version
+			sed -i '/G_DIETPI_VERSION_RC=/c\G_DIETPI_VERSION_RC=7' /DietPi/dietpi/.version
 			echo -e '\n[ \e[1mINFO\e[0m ] DietPi-Update will now exit. No reboot is required, no further update steps are done.
  - To apply the new version string to your terminal session, please manually run:
  	source /DietPi/dietpi/func/dietpi-globals\n'
@@ -87,13 +101,12 @@
 			exit
 
 		fi
-
-		echo -e "\e[1m $G_PROGRAM_NAME\e[0m
-\e[90m─────────────────────────────────────────────────────\e[0m
-[ INFO ] Completed pre-patches with exit code: $EXIT_CODE\n"
-
 		#-------------------------------------------------------------------------------
 		# Finished
+		echo -e " \e[1m$G_PROGRAM_NAME\e[0m
+\e[90m─────────────────────────────────────────────────────\e[0m
+[ \e[1mINFO\e[0m ] Completed pre-patches with exit code: $EXIT_CODE\n"
+
 		break
 		#-------------------------------------------------------------------------------
 
