v6.19.7
- DietPi-Software | Netdata: Resolved an issue, where uninstalling netdata lead to a broken system. Thanks to @PDXUser for reporting this issue: https://github.com/Fourdee/DietPi/issues/2336
- DietPi-Software | Docker: Resolved an issue on RPi, where a faulty "docker-ce" version from repository prevents service start on Raspberry Pi. Thanks to @iaresee and @Garret for reporting this issue, finding and testing workarounds: https://github.com/Fourdee/DietPi/issues/2282

diff --git a/dietpi/pre-patch_file b/dietpi/pre-patch_file
--- a/dietpi/pre-patch_file
+++ b/dietpi/pre-patch_file
@@ -42,9 +42,9 @@
 	while (( $EXIT_CODE == 0 ))
 	do
 
-		echo -e "\n\e[1m $G_PROGRAM_NAME\e[0m
+		echo -e "\n \e[1m$G_PROGRAM_NAME\e[0m
 \e[90m─────────────────────────────────────────────────────\e[0m
-[ INFO ] Applying critical pre-patches\n"
+[ \e[1mINFO\e[0m ] Applying critical pre-patches\n"
 
 		#-------------------------------------------------------------------------------
 		# Pre-patch 1: RAMlog 0 free space check due to issues with failing DietPi cron jobs in v6.11
@@ -62,38 +62,90 @@
 
 				echo -e '[ \e[1mINFO\e[0m ] Pre-patch 2 | Nginx: Hotfix to apply new naming scheme for /etc/nginx/sites-dietpi/*.(config => conf)'
 				sed -i 's|include /etc/nginx/sites-dietpi/\*\.config;|include /etc/nginx/sites-dietpi/\*\.conf;|g' /etc/nginx/sites-available/default
-				(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 2 | An error occured while applying the fix to: /etc/nginx/sites-available/default
- - Please apply it manually. Replace:
- 	include /etc/nginx/sites-dietpi/*.config; with
+				(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 2 | An error occurred while applying the fix to: /etc/nginx/sites-available/default
+ - Please apply it manually. Replace the line:
+ 	include /etc/nginx/sites-dietpi/*.config;	with
 	include /etc/nginx/sites-dietpi/*.conf;'
-				/DietPi/dietpi/dietpi-services start
 
 			fi
 
 			echo -e '[ \e[1mINFO\e[0m ] Pre-patch 3 | DietPi-Software: Resolving "systemctl force-reload" error in case of inactive services'
 			sed -Ei 's/G_RUN_CMD systemctl force-reload (lighttpd|nginx|apache2)/G_RUN_CMD systemctl restart \1/g' /DietPi/dietpi/dietpi-software
-			(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 3 | An error occured while applying the fix to: /DietPi/dietpi/dietpi-software
+			(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 3 | An error occurred while applying the fix to: /DietPi/dietpi/dietpi-software
  - Please apply it manually. Replace the 3 lines:
  	G_RUN_CMD systemctl force-reload lighttpd|nginx|apache2		with
 	G_RUN_CMD systemctl restart lighttpd|nginx|apache2		respectively'
 
+			sed -i '/G_DIETPI_VERSION_RC=/c\G_DIETPI_VERSION_RC=6' /DietPi/dietpi/.version
+
+		fi
+		#-------------------------------------------------------------------------------
+		# Pre-patch 4: Prevent netdata uninstall from breaking the system: https://github.com/Fourdee/DietPi/issues/2336
+		# Pre-patch 5: Prevent APT upgrade to faulty docker-ce version on RPi: https://github.com/Fourdee/DietPi/issues/2282
+		if [[ $G_DIETPI_VERSION_SUB.$(sed -n 4p /DietPi/dietpi/.version) == '19.G_DIETPI_VERSION_RC=6' ]]; then
+		
+			echo -e '[ \e[1mINFO\e[0m ] Pre-patch 4 | Netdata: Fixing a critical issue, where uninstalling netdata would break the system'
+			sed -i 's/userdel -rf netdata/userdel netdata/g' /DietPi/dietpi/dietpi-software
+			(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 4 | An error occurred while applying the fix to: /DietPi/dietpi/dietpi-software
+ - Please apply it manually. Replace the line:
+ 	userdel -rf netdata	with
+	userdel netdata'
+
+			if (( $(sed -n 1p /DietPi/dietpi/.hw_model) < 10 )); then
+
+				echo -e '[ \e[1mINFO\e[0m ] Pre-patch 5 | Docker: Prevent install of a faulty "docker-ce" version in their APT repository'
+
+				if ! grep -q '/etc/apt/preferences.d/dietpi-docker_fix' /DietPi/dietpi/dietpi-software; then
+
+					sed -i "\|INSTALL_URL_ADDRESS='https://get.docker.com'|a\echo 'Package: docker-ce\nPin: version 5:18.09.0~3-0~raspbian-stretch\nPin-Priority: -1' > /etc/apt/preferences.d/dietpi-docker_fix" /DietPi/dietpi/dietpi-software
+					(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 5 | An error occurred while applying the fix to: /DietPi/dietpi/dietpi-software
+ - Please apply it manually. Add the following lines after INSTALL_URL_ADDRESS='\''https://get.docker.com'\'':
+	echo '\''Package: docker-ce
+	Pin: version 5:18.09.0~3-0~raspbian-stretch
+	Pin-Priority: -1'\'' > /etc/apt/preferences.d/dietpi-docker_fix'
+
+				fi
+
+				if dpkg_out="$(dpkg-query -s 'docker-ce' 2>&1)"; then
+
+					echo 'Package: docker-ce
+Pin: version 5:18.09.0~3-0~raspbian-stretch
+Pin-Priority: -1' > /etc/apt/preferences.d/dietpi-docker_fix
+
+					if grep -q '5:18.09.0~3-0~raspbian-stretch' <<< "$dpkg_out"; then
+
+						echo -e '[ \e[1mINFO\e[0m ] Pre-patch 5 | Docker: Downgrading your "docker-ce" package to the last working version'
+						apt-get install -y -qq --allow-downgrades --allow-change-held-packages --allow-unauthenticated docker-ce=18.06.1~ce~3-0~raspbian || EXIT_CODE=5
+						apt-get autoremove --purge -y || EXIT_CODE=5
+						(( $EXIT_CODE == 5 )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 5 | An error has occurred while attempting to downgrade your docker-ce version.
+ - Please try to manually downgrade via:
+ 	G_AGI docker-ce=18.06.1~ce~3-0~raspbian'
+
+					fi
+
+				fi
+
+			fi
+
+			sed -i '/G_DIETPI_VERSION_RC=/c\G_DIETPI_VERSION_RC=7' /DietPi/dietpi/.version
+
+			# Quit update after applying hotfix pre-patches 2-4, which will be replaced by regular code and patch_file update with v6.20
 			echo 0 > /DietPi/dietpi/.update_stage
 			rm /DietPi/dietpi/.update_available
-			sed -i '/G_DIETPI_VERSION_RC=/c\G_DIETPI_VERSION_RC=6' /DietPi/dietpi/.version
-			echo -e '\n[ \e[1mINFO\e[0m ] DietPi-Update will now exit. No reboot is required, no further update steps are done.
+			/DietPi/dietpi/dietpi-services start
+			echo -e '\n[  \e[32mOK\e[0m  ] DietPi-Update will now exit. No reboot is required, no further update steps are done.
  - To apply the new version string to your terminal session, please manually run:
  	source /DietPi/dietpi/func/dietpi-globals\n'
 			kill $PPID
 			exit
 
 		fi
-
-		echo -e "\e[1m $G_PROGRAM_NAME\e[0m
-\e[90m─────────────────────────────────────────────────────\e[0m
-[ INFO ] Completed pre-patches with exit code: $EXIT_CODE\n"
-
 		#-------------------------------------------------------------------------------
 		# Finished
+		echo -e " \e[1m$G_PROGRAM_NAME\e[0m
+\e[90m─────────────────────────────────────────────────────\e[0m
+[ \e[1mINFO\e[0m ] Completed pre-patches with exit code: \e[33m$EXIT_CODE\e[0m\n"
+
 		break
 		#-------------------------------------------------------------------------------
 
