v6.19.7
+ DietPi-Pre-Patch | Prevent faulty "docker-ce" upgrade and downgrade, if required. NB: This is for non-RPi currently to allow testing, will be for RPi only, after testing passed

diff --git a/dietpi/pre-patch_file b/dietpi/pre-patch_file
--- a/dietpi/pre-patch_file
+++ b/dietpi/pre-patch_file
@@ -62,7 +62,7 @@
 
 				echo -e '[ \e[1mINFO\e[0m ] Pre-patch 2 | Nginx: Hotfix to apply new naming scheme for /etc/nginx/sites-dietpi/*.(config => conf)'
 				sed -i 's|include /etc/nginx/sites-dietpi/\*\.config;|include /etc/nginx/sites-dietpi/\*\.conf;|g' /etc/nginx/sites-available/default
-				(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 2 | An error occured while applying the fix to: /etc/nginx/sites-available/default
+				(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 2 | An error occurred while applying the fix to: /etc/nginx/sites-available/default
  - Please apply it manually. Replace the line:
  	include /etc/nginx/sites-dietpi/*.config;	with
 	include /etc/nginx/sites-dietpi/*.conf;'
@@ -71,7 +71,7 @@
 
 			echo -e '[ \e[1mINFO\e[0m ] Pre-patch 3 | DietPi-Software: Resolving "systemctl force-reload" error in case of inactive services'
 			sed -Ei 's/G_RUN_CMD systemctl force-reload (lighttpd|nginx|apache2)/G_RUN_CMD systemctl restart \1/g' /DietPi/dietpi/dietpi-software
-			(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 3 | An error occured while applying the fix to: /DietPi/dietpi/dietpi-software
+			(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 3 | An error occurred while applying the fix to: /DietPi/dietpi/dietpi-software
  - Please apply it manually. Replace the 3 lines:
  	G_RUN_CMD systemctl force-reload lighttpd|nginx|apache2		with
 	G_RUN_CMD systemctl restart lighttpd|nginx|apache2		respectively'
@@ -81,14 +81,39 @@
 		fi
 		#-------------------------------------------------------------------------------
 		# Pre-patch 4: Prevent netdata uninstall from breaking the system: https://github.com/Fourdee/DietPi/issues/2336
+		# Pre-patch 5: Prevent APT upgrade to faulty docker-ce version on RPi: https://github.com/Fourdee/DietPi/issues/2282
 		if [[ $G_DIETPI_VERSION_SUB.$(sed -n 4p /DietPi/dietpi/.version) == '19.G_DIETPI_VERSION_RC=6' ]]; then
 		
 			echo -e '[ \e[1mINFO\e[0m ] Pre-patch 4 | Netdata: Fixing a critical issue, where uninstalling netdata would break the system'
 			sed -i 's/userdel -rf netdata/userdel netdata/g' /DietPi/dietpi/dietpi-software
-			(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 4 | An error occured while applying the fix to: /DietPi/dietpi/dietpi-software
+			(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 4 | An error occurred while applying the fix to: /DietPi/dietpi/dietpi-software
  - Please apply it manually. Replace the line:
  	userdel -rf netdata	with
 	userdel netdata'
+
+			if (( $(sed -n 1p /DietPi/dietpi/.hw_model) > 10 )); then
+
+				echo -e '[ \e[1mINFO\e[0m ] Pre-patch 5 | Docker: Prevent install of a faulty "docker-ce" version in their APT repository'
+				sed -i '\|INSTALL_URL_ADDRESS=\'https://get.docker.com\'|a\echo \'Package: docker-ce
+Pin: version 5:18.09.0~3-0~debian-stretch
+Pin-Priority: -1\' > /etc/apt/preferences.d/dietpi-docker_fix' /DietPi/dietpi/dietpi-software
+				(( $? )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 5 | An error occurred while applying the fix to: /DietPi/dietpi/dietpi-software
+ - Please apply it manually. Add the following lines after INSTALL_URL_ADDRESS=\'https://get.docker.com\':
+	echo \'Package: docker-ce
+	Pin: version 5:18.09.0~3-0~debian-stretch
+	Pin-Priority: -1\' > /etc/apt/preferences.d/dietpi-docker_fix'
+
+				if dpkg -l | grep -q '5:18.09.0~3-0~debian-stretch'; then
+
+					apt-get install -y -qq --allow-downgrades --allow-change-held-packages --allow-unauthenticated docker-ce=18.06.1~ce~3-0~debian || EXIT_CODE=5
+					apt-get autoremove --purge -y || EXIT_CODE=5
+					(( $EXIT_CODE == 5 )) && echo -e '[\e[31mFAILED\e[0m] Pre-patch 5 | An error has occurred while attempting to downgrade your docker-ce version.
+ - Please try to manually downgrade via:
+ 	G_AGI docker-ce=5:18.09.0~3-0~debian-stretch'
+
+				fi
+
+			fi
 
 			sed -i '/G_DIETPI_VERSION_RC=/c\G_DIETPI_VERSION_RC=7' /DietPi/dietpi/.version
 
