ci: allow only Bookworm and Noble hosts
Also do not use Error_Exit if dietpi-globals fail to download. Otherwise use it consequently and avoid doubled "aborting ..." text.

And fix Debian version for which additional raw image and hashes are generated (which should be Debian Bullseye RPi images only).

diff --git a/.build/images/dietpi-build b/.build/images/dietpi-build
--- a/.build/images/dietpi-build
+++ b/.build/images/dietpi-build
@@ -9,7 +9,7 @@ if [[ -f '/boot/dietpi/func/dietpi-globals' ]]
 then
 	. /boot/dietpi/func/dietpi-globals
 else
-	curl -sSf "https://raw.githubusercontent.com/${G_GITOWNER:=MichaIng}/DietPi/${G_GITBRANCH:=master}/dietpi/func/dietpi-globals" -o /tmp/dietpi-globals || Error_Exit 'Failed to download DietPi-Globals'
+	curl -sSf "https://raw.githubusercontent.com/${G_GITOWNER:=MichaIng}/DietPi/${G_GITBRANCH:=master}/dietpi/func/dietpi-globals" -o /tmp/dietpi-globals || { echo 'Failed to download DietPi-Globals, aborting ...'; exit 1; }
 	# shellcheck disable=SC1091
 	. /tmp/dietpi-globals
 	G_EXEC rm /tmp/dietpi-globals
@@ -18,11 +18,11 @@ else
 	case $debian_version in
 		'12.'*|'bookworm/sid') G_DISTRO=7;;
 		'13.'*|'trixie/sid') G_DISTRO=8;;
-		*) Error_Exit "Unsupported distro version \"$debian_version\". Aborting ...";;
+		*) Error_Exit "Unsupported distro version \"$debian_version\"";;
 	esac
 	# Ubuntu ships with /etc/debian_version from Debian testing, hence we assume one version lower.
 	grep -q '^ID=ubuntu' /etc/os-release && ((G_DISTRO--))
-	(( $G_DISTRO < 7 )) && Error_Exit 'Unsupported Ubuntu version. Aborting ...'
+	(( $G_DISTRO < 7 )) && Error_Exit 'Unsupported Ubuntu version'
 fi
 case $G_HW_ARCH_NAME in
 	'armv6l') export G_HW_ARCH=1;;
@@ -30,7 +30,7 @@ case $G_HW_ARCH_NAME in
 	'aarch64') export G_HW_ARCH=3;;
 	'x86_64') export G_HW_ARCH=10;;
 	'riscv64') export G_HW_ARCH=11;;
-	*) Error_Exit "Unsupported host system architecture \"$G_HW_ARCH_NAME\" detected. Aborting ...";;
+	*) Error_Exit "Unsupported host system architecture \"$G_HW_ARCH_NAME\" detected";;
 esac
 readonly G_PROGRAM_NAME='DietPi-Build'
 G_CHECK_ROOT_USER
@@ -77,7 +77,7 @@ do
 		'--sign') shift; SIGN_PASS=$1;;
 		'--test-kernel') TEST_KERNEL=1;;
 		'--test-uboot') TEST_UBOOT=1;;
-		*) Error_Exit "Invalid input \"$1\". Aborting ...";;
+		*) Error_Exit "Invalid input \"$1\"";;
 	esac
 	shift
 done
@@ -165,12 +165,12 @@ case $HW_MODEL in
 	96) iname='OrangePi4A' HW_ARCH=3 partition_start=4 root_size=1000;;
 	97) iname='OrangePiRV' HW_ARCH=11 partition_start=4 root_size=1000;;
 	98) iname='OrangePiRV2' HW_ARCH=11 partition_start=4 root_size=1000;;
-	*) Error_Exit "Invalid hardware model \"$HW_MODEL\" passed. Aborting ...";;
+	*) Error_Exit "Invalid hardware model \"$HW_MODEL\" passed";;
 esac
 
-[[ $VARIANT =~ ^(|iso|vbox|vmx|esxi|hyperv|utm|proxmox|all)$ ]] || Error_Exit "Invalid variant \"$VARIANT\" passed, aborting ..."
+[[ $VARIANT =~ ^(|iso|vbox|vmx|esxi|hyperv|utm|proxmox|all)$ ]] || Error_Exit "Invalid variant \"$VARIANT\" passed"
 
-[[ $EDITION =~ ^(|Amiberry|AlloGUI|all)$ ]] || Error_Exit "Invalid edition \"$EDITION\" passed. Aborting ..."
+[[ $EDITION =~ ^(|Amiberry|AlloGUI|all)$ ]] || Error_Exit "Invalid edition \"$EDITION\" passed"
 
 # Check for valid target architecture and set variables accordingly
 repo='https://deb.debian.org/debian/'
@@ -181,7 +181,7 @@ case $HW_ARCH in
 	3) arch='aarch64' iarch='ARMv8' parch='arm64';;
 	10) arch='x86_64' iarch='x86_64' parch='amd64';;
 	11) arch='riscv64' iarch='RISC-V' parch='riscv64' DISTRO=8;; # RISC-V architecture is available on Trixie only.
-	*) Error_Exit "Invalid architecture \"$HW_ARCH\" passed. Aborting ...";;
+	*) Error_Exit "Invalid architecture \"$HW_ARCH\" passed";;
 esac
 
 # Check for valid target distro version
@@ -189,14 +189,14 @@ case $DISTRO in
 	6) distro='bullseye';;
 	7) distro='bookworm';;
 	8) distro='trixie';;
-	*) Error_Exit "Invalid distro \"$DISTRO\" passed. Aborting ...";;
+	*) Error_Exit "Invalid distro \"$DISTRO\" passed";;
 esac
 
 # Check for valid partition table type and set variables accordingly
 case $PTTYPE in
 	'msdos') [[ $HW_MODEL == 21 ]] && iname+='-BIOS';;
 	'gpt') [[ $HW_ARCH == 10 ]] && efi_size=64 iname+='-UEFI';;
-	*) Error_Exit "Invalid partition table type \"$PTTYPE\" passed. Aborting ...";;
+	*) Error_Exit "Invalid partition table type \"$PTTYPE\" passed";;
 esac
 
 # Check for valid root filesystem type and set variables accordingly
@@ -205,11 +205,11 @@ case $FSTYPE in
 	'ext4') apackages+=('e2fsprogs') afs_opts=('-e' 'remount-ro') afsck=('e2fsck' '-fyD') aresize=('resize2fs');;
 	'f2fs') fsname='F2FS' apackages+=('f2fs-tools') afsck=('fsck.f2fs' '-f') aresize=('resize.f2fs'); uname -r | grep -q '-azure$' && apackages+=('linux-modules-extra-azure');;
 	'btrfs') fsname='Btrfs' apackages+=('btrfs-progs') afsck=('btrfs' 'check' '--repair') aresize=('btrfs' 'filesystem' 'resize' 'max'); ((root_size+=128));;
-	*) Error_Exit "Invalid root filesystem type \"$FSTYPE\" passed. Aborting ...";;
+	*) Error_Exit "Invalid root filesystem type \"$FSTYPE\" passed";;
 esac
 
 # Validate target Git owner and branch
-G_CHECK_URL "https://github.com/$GITOWNER/DietPi/tree/$GITBRANCH" || Error_Exit "Failed to access Git branch \"$GITBRANCH\". Aborting ..."
+G_CHECK_URL "https://github.com/$GITOWNER/DietPi/tree/$GITBRANCH" || Error_Exit "Failed to access Git branch \"$GITBRANCH\""
 
 # Generate image name and define CLONING_TOOL for dietpi-installer
 OUTPUT_IMG_NAME="DietPi_$iname-$iarch-${distro^}"
@@ -217,7 +217,7 @@ OUTPUT_IMG_NAME="DietPi_$iname-$iarch-${distro^}"
 CLONING_TOOL='dd'
 if [[ $VARIANT == 'iso' ]]
 then
-	[[ $HW_ARCH == 10 ]] || Error_Exit "Unsupported variant \"$VARIANT\" (installer image) for architecture \"$HW_ARCH\" passed. Aborting ..."
+	[[ $HW_ARCH == 10 ]] || Error_Exit "Unsupported variant \"$VARIANT\" (installer image) for architecture \"$HW_ARCH\" passed"
 	CLONING_TOOL='Clonezilla'
 	OUTPUT_IMG_NAME+='_Installer'
 fi
@@ -503,7 +503,7 @@ IMAGER_ARGS=("$OUTPUT_IMG_NAME.img")
 [[ $HW_MODEL == [1245] ]] && IMAGER_ARGS+=('--configs-to-boot')
 [[ $SIGN_PASS ]] && IMAGER_ARGS+=('--sign' "$SIGN_PASS")
 # Raspberry Pi Imager info
-[[ $HW_MODEL == [1-5] && $DISTRO == 8 ]] && IMAGER_ARGS+=('--raw-hash-size')
+[[ $HW_MODEL == [1-5] && $DISTRO == 7 ]] && IMAGER_ARGS+=('--raw-hash-size')
 
 ####### IMG/ISO ##########################
 if [[ ! $EDITION || $EDITION == 'all' ]]
