dietpi-build: fix for emulated containers

diff --git a/.build/images/dietpi-build b/.build/images/dietpi-build
--- a/.build/images/dietpi-build
+++ b/.build/images/dietpi-build
@@ -488,7 +488,8 @@ G_EXEC chmod +x rootfs/dietpi-build.sh
 cat << '_EOF_' > rootfs/etc/systemd/system/dietpi-build.service || exit 1
 [Service]
 Type=idle
-StandardOutput=tty
+# StandardOutput=tty fails in emulated containers
+StandardOutput=journal+console
 ExecStart=/dietpi-build.sh
 _EOF_
 G_EXEC ln -s /etc/systemd/system/dietpi-build.service rootfs/etc/systemd/system/multi-user.target.wants/dietpi-build.service
@@ -638,20 +639,16 @@ then
 
 	# Install Allo GUI via automated first run setup right here
 	G_CONFIG_INJECT 'AUTO_SETUP_AUTOMATED=' 'AUTO_SETUP_AUTOMATED=1' rootfs/boot/dietpi.txt
-	# Workaround for failing systemd services in emulated container: https://gitlab.com/qemu-project/qemu/-/issues/1962, https://github.com/systemd/systemd/issues/31219
+	# Workarounds for QEMU-emulated containers
 	if (( $emulation ))
 	then
+		# Failing systemd services: https://gitlab.com/qemu-project/qemu/-/issues/1962, https://github.com/systemd/systemd/issues/31219
 		for i in rootfs/lib/systemd/system/*.service
 		do
 			[[ -f $i ]] || continue
-			grep -Eq '^(Load|Import)Credential=' "$i" || continue
+			grep -Eq '^(Import|Load)Credential=' "$i" || continue
 			G_EXEC mkdir "${i/lib/etc}.d"
-			if (( $DISTRO < 8 ))
-			then
-				G_EXEC eval "echo -e '[Service]\nLoadCredential=' > \"${i/lib/etc}.d/dietpi-no-credentials.conf\""
-			else
-				G_EXEC eval "echo -e '[Service]\nImportCredential=' > \"${i/lib/etc}.d/dietpi-no-credentials.conf\""
-			fi
+			G_EXEC eval "echo -e '[Service]\nImportCredential=\nLoadCredential=' > '${i/lib/etc}.d/dietpi-no-credentials.conf'"
 		done
 	fi
 	G_CONFIG_INJECT 'AUTO_SETUP_INSTALL_SOFTWARE_ID=' 'AUTO_SETUP_INSTALL_SOFTWARE_ID=159' rootfs/boot/dietpi.txt
