v9.10
- CI | Apply better workaround for failing services and hence missing login prompts in QEMU-emulated Trixie containers

diff --git a/.build/images/dietpi-build b/.build/images/dietpi-build
--- a/.build/images/dietpi-build
+++ b/.build/images/dietpi-build
@@ -609,24 +609,15 @@ then
 
 	# Install Allo GUI via automated first run setup right here
 	G_CONFIG_INJECT 'AUTO_SETUP_AUTOMATED=' 'AUTO_SETUP_AUTOMATED=1' rootfs/boot/dietpi.txt
-	# - Workaround for skipped autologin in emulated Trixie containers: https://gitlab.com/qemu-project/qemu/-/issues/1962
+	# - Workaround for failing systemd services and hence missing autologin in emulated Trixie containers: https://gitlab.com/qemu-project/qemu/-/issues/1962, https://github.com/systemd/systemd/issues/31219
 	if (( $DISTRO == 8 && $G_HW_ARCH != $HW_ARCH && ( $G_HW_ARCH > 9 || $G_HW_ARCH < $HW_ARCH ) ))
 	then
-		cat << '_EOF_' > rootfs/etc/systemd/system/dietpi-automation.service
-[Unit]
-Description=DietPi-Automation
-After=dietpi-postboot.service
-
-[Service]
-Type=idle
-StandardOutput=tty
-ExecStart=/bin/dash -c 'infocmp "$TERM" > /dev/null 2>&1 || export TERM=dumb; exec /boot/dietpi/dietpi-login'
-ExecStop=/usr/bin/systemctl start poweroff.target
-
-[Install]
-WantedBy=multi-user.target
-_EOF_
-		G_EXEC ln -s /etc/systemd/system/dietpi-automation.service rootfs/etc/systemd/system/multi-user.target.wants/
+		for i in rootfs/usr/lib/systemd/system/*.service
+		do
+			grep -q '^ImportCredential=' "$i" || continue
+			G_EXEC mkdir "${i/usr\/lib/etc}.d"
+			G_EXEC eval "echo -e '[Service]\nImportCredential=' > ${i/usr\/lib/etc}.d/dietpi-no-ImportCredential.conf"
+		done
 	fi
 	G_CONFIG_INJECT 'AUTO_SETUP_INSTALL_SOFTWARE_ID=' 'AUTO_SETUP_INSTALL_SOFTWARE_ID=159' rootfs/boot/dietpi.txt
 	# Revert autostart option, in case Amiberry image was generated before
@@ -710,9 +701,6 @@ _EOF_
 
 	# Revert ARMv6 Workaround
 	(( $HW_ARCH == 1 )) && G_EXEC rm rootfs/usr/local/bin/uname
-
-	# Revert workaround for skipped autologin in emulated Trixie containers: https://gitlab.com/qemu-project/qemu/-/issues/1962
-	(( $DISTRO == 8 )) && G_EXEC rm rootfs/etc/systemd/system/{multi-user.target.wants/,}dietpi-automation.service
 
 	[[ -f 'rootfs/success' ]] || { G_DIETPI-NOTIFY 1 'The container setup did not finish successfully, aborting...'; exit 1; }
 	G_EXEC rm rootfs/success
