dietpi-build: ...

diff --git a/.build/images/dietpi-build b/.build/images/dietpi-build
--- a/.build/images/dietpi-build
+++ b/.build/images/dietpi-build
@@ -471,15 +471,16 @@ fi
 ##########################################
 # Create boot script and systemd unit to automate DietPi-Installer
 # - NB: WIFI_REQUIRED=1 is always passed here, but ignored by DietPi-Installer for VMs and containers.
+# - Prevent console-getty.service from stealing the controlling terminal
+G_EXEC ln -s /dev/null rootfs/etc/systemd/system/console-getty.service
 cat << _EOF_ > rootfs/dietpi-build.sh || exit 1
 #!/bin/dash -e
 {
-rm -v /etc/systemd/system/graphical.target.wants/dietpi-build.service /etc/systemd/system/dietpi-build.service /dietpi-build.sh
-rmdir -v /etc/systemd/system/graphical.target.wants
+rm -v /etc/systemd/system/multi-user.target.wants/dietpi-build.service /etc/systemd/system/dietpi-build.service /dietpi-build.sh rootfs/etc/systemd/system/console-getty.service
 infocmp "\$TERM" > /dev/null 2>&1 || { echo "[ WARN ] Unsupported TERM=\"\$TERM\", switching to TERM=\"dumb\""; export TERM=dumb; }
 export GITOWNER='$GITOWNER' GITBRANCH='$GITBRANCH' HW_MODEL='$HW_MODEL' IMAGE_CREATOR=0 PREIMAGE_INFO=0 WIFI_REQUIRED=1 DISTRO_TARGET=$DISTRO TEST_KERNEL=$TEST_KERNEL TEST_UBOOT=$TEST_UBOOT RK35XX_MAINLINE=$RK35XX_MAINLINE TMPDIR='/tmp'
 echo '[ INFO ] Running DietPi-Installer for $G_GITOWNER/$G_GITBRANCH'
-bash -c "\$(curl -sSf 'https://raw.githubusercontent.com/$G_GITOWNER/DietPi/$G_GITBRANCH/.build/images/dietpi-installer')" || { echo '[FAILED] DietPi-Installer failed, shutting down ...'; journalctl -n 25; df -h; free -h; exit 1; }
+bash -c "\$(curl -sSf 'https://raw.githubusercontent.com/$G_GITOWNER/DietPi/$G_GITBRANCH/.build/images/dietpi-installer' || echo false)" || { echo '[FAILED] DietPi-Installer failed, shutting down ...'; journalctl -n 25; df -h; free -h; exit 1; }
 > /success
 exit 0
 } > /dev/console 2>&1
@@ -487,9 +488,7 @@ _EOF_
 G_EXEC chmod +x rootfs/dietpi-build.sh
 cat << '_EOF_' > rootfs/etc/systemd/system/dietpi-build.service || exit 1
 [Unit]
-After=graphical.target
-Wants=getty-pre.target
-Before=getty-pre.target
+After=multi-user.target
 
 [Service]
 Type=oneshot
@@ -498,8 +497,7 @@ StandardOutput=journal+console
 ExecStart=-/dietpi-build.sh
 ExecStart=/usr/bin/systemctl --no-block start poweroff.target
 _EOF_
-G_EXEC mkdir rootfs/etc/systemd/system/graphical.target.wants
-G_EXEC ln -s /etc/systemd/system/dietpi-build.service rootfs/etc/systemd/system/graphical.target.wants/dietpi-build.service
+G_EXEC ln -s /etc/systemd/system/dietpi-build.service rootfs/etc/systemd/system/multi-user.target.wants/dietpi-build.service
 
 # Start container
 # - Bind mounts required to allow container reading its own drive info, /dev/disk for GRUB and probably other tools to detect UUIDs
