v8.2 (#5288)
- CI | Enable the workflow for building DietPi images
- CI | Pass G_GITOWNER and G_GITBRANCH to DietPi-Build: We want to use DietPi-Build, DietPi-PREP, DietPi-Imager and in case dietpi-globals from the host or reference repository while using a dedicated owner/branch (e.g. master branch) for the image.
- DietPi-Build | Create cleanup exit trap directly before the image file is allocated, reducing overhead on early errors, e.g. invalid inputs or dependency install errors
- DietPi-Build | Use first free loop device instead of hardcoded /dev/loop0
- DietPi-Build | Unmask and start dbus only when socket was masked before. Else assume that both is either running or at least the socket listening and service not masked. Also do not start service explicitly, leave it up to socket activation. For some reason on GitHub action runners the service "is configured to refuse manual start/stop".
- DietPi-Build | In case of an invalid TERM, assign "dumb" so that tput cannot fail to read terminal dimensions
- DietPi-Imager | Add support for non-DietPi host systems
- DietPi-Globals | Do not attempt to use advanced terminal control codes if it is "dumb"

diff --git a/.build/images/dietpi-build b/.build/images/dietpi-build
--- a/.build/images/dietpi-build
+++ b/.build/images/dietpi-build
@@ -8,9 +8,11 @@ if [[ -f '/boot/dietpi/func/dietpi-globals' ]]
 then
 	. /boot/dietpi/func/dietpi-globals
 else
+	[[ $G_GITOWNER && $G_GITBRANCH ]] || { echo '[FAILED] You must export or pass G_GITOWNER and G_GITBRANCH to the script'; exit 1; }
 	curl -sSf "https://raw.githubusercontent.com/$G_GITOWNER/DietPi/$G_GITBRANCH/dietpi/func/dietpi-globals" -o /tmp/dietpi-globals || exit 1
 	. /tmp/dietpi-globals
 	G_EXEC_NOHALT=1 G_EXEC rm /tmp/dietpi-globals
+	export G_GITOWNER G_GITBRANCH
 fi
 readonly G_PROGRAM_NAME='DietPi-Build'
 G_CHECK_ROOT_USER
@@ -18,12 +20,6 @@ G_CHECK_ROOTFS_RW
 readonly FP_ORIGIN=$PWD # Store origin dir
 G_INIT
 G_EXEC cd "$FP_ORIGIN" # Process everything in origin dir instead of /tmp/$G_PROGRAM_NAME
-G_EXIT_CUSTOM(){
-	findmnt -M "$FP_ORIGIN/rootfs" &> /dev/null && G_EXEC umount -R "$FP_ORIGIN/rootfs"
-	[[ -d $FP_ORIGIN/rootfs ]] && G_EXEC rmdir "$FP_ORIGIN/rootfs"
-	losetup /dev/loop0 &> /dev/null && G_EXEC losetup -d /dev/loop0
-	(( $mask_dbus )) && G_EXEC systemctl mask --now dbus dbus.socket
-}
 
 ##########################################
 # Process inputs
@@ -143,6 +139,15 @@ fi
 ##########################################
 # Partitions and filesystems
 ##########################################
+# Exit trap for cleanup
+G_EXIT_CUSTOM(){
+	findmnt -M "$FP_ORIGIN/rootfs" &> /dev/null && G_EXEC umount -R "$FP_ORIGIN/rootfs"
+	[[ -d $FP_ORIGIN/rootfs ]] && G_EXEC rmdir "$FP_ORIGIN/rootfs"
+	[[ $FP_LOOP ]] && losetup "$FP_LOOP" &> /dev/null && G_EXEC losetup -d "$FP_LOOP"
+	[[ -f $OUTPUT_IMG_NAME.img ]] && G_EXEC rm "$OUTPUT_IMG_NAME.img"
+	(( $mask_dbus )) && G_EXEC systemctl mask --now dbus dbus.socket
+}
+
 # Create image file
 G_EXEC fallocate -l "$((partition_start+efi_size+boot_size+root_size))M" "$OUTPUT_IMG_NAME.img"
 
@@ -167,9 +172,10 @@ else
 fi
 
 # Create loop device
-G_EXEC losetup loop0 "$OUTPUT_IMG_NAME.img"
-G_EXEC partprobe /dev/loop0
-G_EXEC partx -u /dev/loop0
+FP_LOOP=$(losetup -f)
+G_EXEC losetup "$FP_LOOP" "$OUTPUT_IMG_NAME.img"
+G_EXEC partprobe "$FP_LOOP"
+G_EXEC partx -u "$FP_LOOP"
 
 # Create and mount filesystems and fstab
 G_EXEC mkdir rootfs
@@ -177,38 +183,38 @@ G_EXEC mkdir rootfs
 if [[ $PTTYPE == 'gpt' ]]
 then
 	FP_ROOT_DEV=2
-	G_EXEC mkfs.fat -F 32 /dev/loop0p1
-	G_EXEC "mkfs.$FSTYPE" /dev/loop0p2
-	G_EXEC mount /dev/loop0p2 rootfs
+	G_EXEC mkfs.fat -F 32 "${FP_LOOP}p1"
+	G_EXEC "mkfs.$FSTYPE" "${FP_LOOP}p2"
+	G_EXEC mount "${FP_LOOP}p2" rootfs
 	G_EXEC mkdir -p rootfs/boot/efi
-	G_EXEC mount /dev/loop0p1 rootfs/boot/efi
+	G_EXEC mount "${FP_LOOP}p1" rootfs/boot/efi
 	G_EXEC mkdir rootfs/etc
 	cat << _EOF_ > rootfs/etc/fstab
-PARTUUID=$(lsblk -no PARTUUID /dev/loop0p2) / $FSTYPE noatime,lazytime 0 1
-PARTUUID=$(lsblk -no PARTUUID /dev/loop0p1) /boot/efi vfat noatime,lazytime 0 2
+PARTUUID=$(lsblk -no PARTUUID "${FP_LOOP}p2") / $FSTYPE noatime,lazytime 0 1
+PARTUUID=$(lsblk -no PARTUUID "${FP_LOOP}p1") /boot/efi vfat noatime,lazytime 0 2
 _EOF_
 # + boot partition
 elif (( $boot_size ))
 then
 	FP_ROOT_DEV=2
-	G_EXEC mkfs.fat -F 32 /dev/loop0p1
-	G_EXEC "mkfs.$FSTYPE" /dev/loop0p2
-	G_EXEC mount /dev/loop0p2 rootfs
+	G_EXEC mkfs.fat -F 32 "${FP_LOOP}p1"
+	G_EXEC "mkfs.$FSTYPE" "${FP_LOOP}p2"
+	G_EXEC mount "${FP_LOOP}p2" rootfs
 	G_EXEC mkdir rootfs/boot
-	G_EXEC mount /dev/loop0p1 rootfs/boot
+	G_EXEC mount "${FP_LOOP}p1" rootfs/boot
 	G_EXEC mkdir rootfs/etc
 	cat << _EOF_ > rootfs/etc/fstab
-PARTUUID=$(lsblk -no PARTUUID /dev/loop0p2) / $FSTYPE noatime,lazytime 0 1
-PARTUUID=$(lsblk -no PARTUUID /dev/loop0p1) /boot vfat noatime,lazytime 0 2
+PARTUUID=$(lsblk -no PARTUUID "${FP_LOOP}p2") / $FSTYPE noatime,lazytime 0 1
+PARTUUID=$(lsblk -no PARTUUID "${FP_LOOP}p1") /boot vfat noatime,lazytime 0 2
 _EOF_
 # - single partition
 else
 	FP_ROOT_DEV=1
-	G_EXEC "mkfs.$FSTYPE" /dev/loop0p1
-	G_EXEC mount /dev/loop0p1 rootfs
+	G_EXEC "mkfs.$FSTYPE" "${FP_LOOP}p1"
+	G_EXEC mount "${FP_LOOP}p1" rootfs
 	G_EXEC mkdir rootfs/etc
 	cat << _EOF_ > rootfs/etc/fstab
-PARTUUID=$(lsblk -no PARTUUID /dev/loop0p1) / $FSTYPE noatime,lazytime 0 1
+PARTUUID=$(lsblk -no PARTUUID "${FP_LOOP}p1") / $FSTYPE noatime,lazytime 0 1
 _EOF_
 fi
 
@@ -228,6 +234,7 @@ G_EXEC rm -Rf rootfs/var/{cache/apt,lib/apt/lists}/*
 cat << _EOF_ > rootfs/etc/rc.local
 #!/bin/dash
 {
+infocmp "$TERM" > /dev/null 2>&1 || TERM='dumb'
 echo '[ INFO ] Running DietPi-PREP...'
 export GITOWNER='$GITOWNER' GITBRANCH='$GITBRANCH' HW_MODEL='$HW_MODEL' IMAGE_CREATOR=0 PREIMAGE_INFO='from scratch' WIFI_REQUIRED=$WIFI_REQUIRED DISTRO_TARGET=$DISTRO
 bash -c "\$(curl -sSf 'https://raw.githubusercontent.com/$G_GITOWNER/DietPi/$G_GITBRANCH/PREP_SYSTEM_FOR_DIETPI.sh')" || poweroff
@@ -252,20 +259,23 @@ G_EXEC chmod +x rootfs/etc/rc.local
 # Start container
 # - dbus required for container spawn
 mask_dbus=0
-[[ $(readlink /etc/systemd/system/dbus.socket) == '/dev/null' ]] && mask_dbus=1
-G_EXEC systemctl unmask dbus.socket dbus
-G_EXEC systemctl start dbus.socket dbus
+if [[ $(readlink /etc/systemd/system/dbus.socket) == '/dev/null' ]]
+then
+	mask_dbus=1
+	G_EXEC systemctl unmask dbus.socket dbus
+	G_EXEC systemctl start dbus.socket
+fi
 # - Bind mounts required to allow container reading its own drive info, /dev/disk for GRUB and probably other tools to detect UUIDs
 abind=()
-[[ -b '/dev/loop0p2' ]] && abind=('--bind=/dev/loop0p2')
-systemd-nspawn -bD rootfs --bind=/dev/loop0 --bind=/dev/loop0p1 "${abind[@]}" --bind=/dev/disk || exit 1
+[[ -b ${FP_LOOP}p2 ]] && abind=("--bind=${FP_LOOP}p2")
+systemd-nspawn -bD rootfs --bind="$FP_LOOP"{,p1} "${abind[@]}" --bind=/dev/disk || exit 1
 [[ -f 'rootfs/success' ]] || { G_DIETPI-NOTIFY 1 'The container setup did not finish successfully, aborting...'; exit 1; }
 G_EXEC rm rootfs/success
 G_EXEC sync
 G_EXEC sleep 1
 G_EXEC umount -R rootfs
 G_EXEC rmdir rootfs
-G_EXEC losetup -d /dev/loop0
+G_EXEC losetup -d "$FP_LOOP"
 (( $mask_dbus )) && { G_EXEC systemctl mask --now dbus dbus.socket && mask_dbus=0; }
 
 ##########################################
@@ -274,7 +284,7 @@ G_EXEC losetup -d /dev/loop0
 export FP_ROOT_DEV CLONING_TOOL OUTPUT_IMG_NAME MOUNT_IT='Off'
 bash -c "$(curl -sSf "https://raw.githubusercontent.com/$G_GITOWNER/DietPi/$G_GITBRANCH/.meta/dietpi-imager")" 'DietPi-Imager' "$OUTPUT_IMG_NAME.img" || exit 1
 
-[[ $VMTYPE ]] || { G_EXEC rm "$OUTPUT_IMG_NAME.img"; exit 0; }
+[[ $VMTYPE ]] || exit 0
 
 ##########################################
 # Virtual machines
