dietpi-survey_report: enhance sanity checks and ourput
and revert an obsolete workaround for a bash bug, fixed in the meantime.

diff --git a/.meta/dietpi-survey_report b/.meta/dietpi-survey_report
--- a/.meta/dietpi-survey_report
+++ b/.meta/dietpi-survey_report
@@ -1,5 +1,5 @@
 #!/bin/bash
-shopt -s extglob
+shopt -s extglob # +(expr) syntax
 {
 	# Created by MichaIng / micha@dietpi.com / dietpi.com
 
@@ -702,8 +702,8 @@ shopt -s extglob
 				'((aNETWORK_INTERFACE['+([[:graph:]])']++))') iface=${line#*'['} iface=${iface%']'*};;
 				'((aRASPBIAN['[01]']++))') raspbian=${line#*'['} raspbian=${raspbian%']'*};;
 				'MMC='[01]) mmc=${line#*'='};;
-				'((aSOFTWARE[${aSOFTWARE_NAME'${version/./_}'['+([[:digit:]])']:='+([[:digit:]])'}]++))') software=${line##*'['} software=${software%%']'*};;
-				'BENCH_VERSION=2') BENCH_VERSION=${line#*'='};;
+				'((aSOFTWARE[${aSOFTWARE_NAME'${version/./_}'['+([[:digit:]])']:='+([[:digit:]])'}]++))') software_id=${line##*'['} software_id=${software%%']'*};;
+				'BENCH_VERSION=2') BENCH_VERSION=2;;
 				'BENCH_HW_MODEL='+([[:digit:]])) BENCH_HW_MODEL=${line#*'='};;
 				'BENCH_CPU='*) BENCH_CPU=${line#*\'} BENCH_CPU=${BENCH_CPU%\'};;
 				'BENCH_ROOTFS_WRITE='*) BENCH_ROOTFS_WRITE=${line#*\'} BENCH_ROOTFS_WRITE=${BENCH_ROOTFS_WRITE%\'};;
@@ -723,16 +723,16 @@ shopt -s extglob
 			esac
 
 			# Validate and process software name if present
-			[[ $software ]] || continue
-			eval "software=\${aSOFTWARE_NAME${version/./_}[$software]}"
-			if [[ ! $software ]]
+			[[ $software_id ]] || continue
+			eval "software_name=\${aSOFTWARE_NAME${version/./_}[$software_id]}"
+			if [[ ! $software_name ]]
 			then
-				echo "Invalid software ID \"$software\" for DietPi version $version"
+				echo "Invalid software ID \"$software_id\" for DietPi version $version"
 				mv -v "/home/dietpi-survey/survey/$file" /home/dietpi-survey/invalid/
 				return 1
 			fi
-			asoftware+=("$software")
-			unset -v software
+			asoftware+=("$software_name")
+			unset -v software_id software_name
 
 		done < "$file"
 
@@ -776,9 +776,8 @@ shopt -s extglob
 		done
 
 		# Process benchmark results if present and hardware ID valid
-		[[ $BENCH_VERSION && $BENCH_HW_MODEL ]] || return 0
-		[[ $BENCH_VERSION =~ ^[0-9]+$ ]] || { echo "Invalid DietPi-Benchmark version: $BENCH_VERSION"; return 1; }
-		[[ ${aHW_NAME[$BENCH_HW_MODEL]} ]] || { echo "Invalid hardware ID: $BENCH_HW_MODEL"; return 1; }
+		[[ $BENCH_VERSION ]] || return 0
+		[[ $BENCH_HW_MODEL =~ ^[0-9]+$ && ${aHW_NAME[$BENCH_HW_MODEL]} ]] || { echo "Invalid hardware ID: \"$BENCH_HW_MODEL\""; return 1; }
 
 		# CPU
 		if [[ $BENCH_CPU == *[1-9]* && $BENCH_CPU =~ ^[0-9]+\.[0-9]{2}$ ]]
@@ -923,13 +922,9 @@ shopt -s extglob
 
 			# Work out averages
 			# - Divide CPU times by 100 and scale to revert decimal point removal
-			#aBENCH_RESULT_CPU_MIN[i]=$(printf '%.2f' "${aBENCH_RESULT_CPU_MIN[i]}e-2")
-			#aBENCH_RESULT_CPU_MAX[i]=$(printf '%.2f' "${aBENCH_RESULT_CPU_MAX[i]}e-2")
-			#aBENCH_RESULT_CPU_AVG[i]=$(printf '%.2f' "$((${aBENCH_RESULT_CPU_AVG[i]}*10/${aBENCH_CPU_INDEX[i]}+1))e-3")
-			# - Workaround for current bash printf bug: https://bugs.debian.org/1078556
-			aBENCH_RESULT_CPU_MIN[i]=$(mawk "{printf \"%.2f\", ${aBENCH_RESULT_CPU_MIN[i]}e-2}" <<< '')
-			aBENCH_RESULT_CPU_MAX[i]=$(mawk "{printf \"%.2f\", ${aBENCH_RESULT_CPU_MAX[i]}e-2}" <<< '')
-			aBENCH_RESULT_CPU_AVG[i]=$(mawk "{printf \"%.2f\", $((${aBENCH_RESULT_CPU_AVG[i]}*10/${aBENCH_CPU_INDEX[i]}+1))e-3}" <<< '')
+			aBENCH_RESULT_CPU_MIN[i]=$(printf '%.2f' "${aBENCH_RESULT_CPU_MIN[i]}e-2")
+			aBENCH_RESULT_CPU_MAX[i]=$(printf '%.2f' "${aBENCH_RESULT_CPU_MAX[i]}e-2")
+			aBENCH_RESULT_CPU_AVG[i]=$(printf '%.2f' "$((${aBENCH_RESULT_CPU_AVG[i]}*10/${aBENCH_CPU_INDEX[i]}+1))e-3")
 
 			# CPU temps if available
 			aBENCH_RESULT_CPU_TEMP_START_MIN[i]='N/A'
