v7.1
+ DietPi-Survey_results | Cleanup benchmark handling: Since final DietPi v6.17, those are uploaded, and did not contain I/O values with decimal places since then, but only on earlier versions which were never uploaded, and v6.17 early dev. Allow zero values, which are rounded down from below 0.5 MiB correctly. Similarly CPU time has fixed two decimal places since early versions (time -p), hence check for that explicitly and skip the obsolete BENCH_RESULTS_CPU_SCALE variable.
+ DietPi-Survey_results | Remove obsolete rel="home" attribute and link. This was never really implemented, is not documented anywhere relevant and has no effect on SEO.

diff --git a/.meta/dietpi-survey_report b/.meta/dietpi-survey_report
--- a/.meta/dietpi-survey_report
+++ b/.meta/dietpi-survey_report
@@ -76,66 +76,58 @@ shopt -s extglob
 		[73]='ROCK Pi S'
 	)
 
-	# Core Benchmarks
-	aBENCH_CPU_INDEX=()
-	aBENCH_RAM_INDEX=()
-	aBENCH_ROOTFS_INDEX=()
-	# Optional benchmarks
-	aBENCH_LAN_INDEX=()
-	aBENCH_CUSTOMFS_INDEX=()
+	## Benchmark data arrays: aBENCH_XX[$HW_MODEL,${aBENCH_XX_INDEX[$HW_MODEL]}]
 
-	# [$HW_MODEL,${aBENCH_XX_INDEX[$HW_MODEL]}]
+	# Core benchmarks
+	# - CPU time in x.xx seconds
+	aBENCH_CPU_INDEX=()
 	declare -A aBENCH_CPU
-	declare -A aBENCH_ROOTFS_WRITE
-	declare -A aBENCH_ROOTFS_READ
-	declare -A aBENCH_RAM_WRITE
-	declare -A aBENCH_RAM_READ
+	# - CPU temp in integer °C
 	declare -A aBENCH_CPU_TEMP_START
 	declare -A aBENCH_CPU_TEMP_END
+	# - I/O in integer MiB/s
+	aBENCH_RAM_INDEX=()
+	declare -A aBENCH_RAM_WRITE
+	declare -A aBENCH_RAM_READ
+	aBENCH_ROOTFS_INDEX=()
+	declare -A aBENCH_ROOTFS_WRITE
+	declare -A aBENCH_ROOTFS_READ
 
 	# Optional benchmarks
+	aBENCH_CUSTOMFS_INDEX=()
 	declare -A aBENCH_CUSTOMFS_WRITE
 	declare -A aBENCH_CUSTOMFS_READ
+	aBENCH_LAN_INDEX=()
 	declare -A aBENCH_NET_LAN_SPEED
 
-	# Results
-	BENCH_RESULTS_CPU_SCALE=2
+	# Benchmark result arrays: min, max, average
 	aBENCH_RESULT_CPU_MIN=()
 	aBENCH_RESULT_CPU_MAX=()
 	aBENCH_RESULT_CPU_AVG=()
-
-	aBENCH_RESULT_ROOTFS_WRITE_MIN=()
-	aBENCH_RESULT_ROOTFS_WRITE_MAX=()
-	aBENCH_RESULT_ROOTFS_WRITE_AVG=()
-
-	aBENCH_RESULT_ROOTFS_READ_MIN=()
-	aBENCH_RESULT_ROOTFS_READ_MAX=()
-	aBENCH_RESULT_ROOTFS_READ_AVG=()
-
-	aBENCH_RESULT_RAM_WRITE_MIN=()
-	aBENCH_RESULT_RAM_WRITE_MAX=()
-	aBENCH_RESULT_RAM_WRITE_AVG=()
-
-	aBENCH_RESULT_RAM_READ_MIN=()
-	aBENCH_RESULT_RAM_READ_MAX=()
-	aBENCH_RESULT_RAM_READ_AVG=()
-
 	aBENCH_RESULT_CPU_TEMP_START_MIN=()
 	aBENCH_RESULT_CPU_TEMP_START_MAX=()
 	aBENCH_RESULT_CPU_TEMP_START_AVG=()
-
 	aBENCH_RESULT_CPU_TEMP_END_MIN=()
 	aBENCH_RESULT_CPU_TEMP_END_MAX=()
 	aBENCH_RESULT_CPU_TEMP_END_AVG=()
-
-	aBENCH_RESULT_CUSTOMFS_WRITE_MIN=()
-	aBENCH_RESULT_CUSTOMFS_WRITE_MAX=()
-	aBENCH_RESULT_CUSTOMFS_WRITE_AVG=()
-
+	aBENCH_RESULT_RAM_READ_MIN=()
+	aBENCH_RESULT_RAM_READ_MAX=()
+	aBENCH_RESULT_RAM_READ_AVG=()
+	aBENCH_RESULT_RAM_WRITE_MIN=()
+	aBENCH_RESULT_RAM_WRITE_MAX=()
+	aBENCH_RESULT_RAM_WRITE_AVG=()
+	aBENCH_RESULT_ROOTFS_READ_MIN=()
+	aBENCH_RESULT_ROOTFS_READ_MAX=()
+	aBENCH_RESULT_ROOTFS_READ_AVG=()
+	aBENCH_RESULT_ROOTFS_WRITE_MIN=()
+	aBENCH_RESULT_ROOTFS_WRITE_MAX=()
+	aBENCH_RESULT_ROOTFS_WRITE_AVG=()
 	aBENCH_RESULT_CUSTOMFS_READ_MIN=()
 	aBENCH_RESULT_CUSTOMFS_READ_MAX=()
 	aBENCH_RESULT_CUSTOMFS_READ_AVG=()
-
+	aBENCH_RESULT_CUSTOMFS_WRITE_MIN=()
+	aBENCH_RESULT_CUSTOMFS_WRITE_MAX=()
+	aBENCH_RESULT_CUSTOMFS_WRITE_AVG=()
 	aBENCH_RESULT_NET_LAN_SPEED_MIN=()
 	aBENCH_RESULT_NET_LAN_SPEED_MAX=()
 	aBENCH_RESULT_NET_LAN_SPEED_AVG=()
@@ -581,18 +573,18 @@ shopt -s extglob
 			((aSOFTWARE["$i"]++))
 		done
 
-		# Process benchmark results is present and hardware ID valid
+		# Process benchmark results if present and hardware ID valid
 		[[ $BENCH_VERSION && $BENCH_HW_MODEL ]] || return 0
+		[[ $BENCH_VERSION =~ ^[0-9]+$ ]] || { echo "Invalid DietPi-Benchmark version: $BENCH_VERSION"; return 1; }
 		[[ ${aHW_NAME[$BENCH_HW_MODEL]} ]] || { echo "Invalid hardware ID: $BENCH_HW_MODEL"; return 1; }
 
 		# CPU
-		# - BENCH_CPU: Remove decimal point, equals times 100 since CPU time is always in x.xx
-		BENCH_CPU=${BENCH_CPU/.}
-		if [[ $BENCH_CPU =~ ^[0-9]*[1-9][0-9]*$ && $BENCH_CPU_TEMP_START =~ ^[0-9]+$ && $BENCH_CPU_TEMP_END =~ ^[0-9]+$ ]]; then
+		if [[ $BENCH_CPU =~ ^[0-9]+\.[0-9]{2}$ && $BENCH_CPU_TEMP_START =~ ^[0-9]+$ && $BENCH_CPU_TEMP_END =~ ^[0-9]+$ ]]; then
 
-			aBENCH_CPU[$BENCH_HW_MODEL,${aBENCH_CPU_INDEX[$BENCH_HW_MODEL]:=0}]=$BENCH_CPU
+			# CPU time: Remove decimal point, equals times 100 since it's always in x.xx
+			aBENCH_CPU[$BENCH_HW_MODEL,${aBENCH_CPU_INDEX[$BENCH_HW_MODEL]:=0}]=${BENCH_CPU/.}
 
-			# Patch for 5 digit CPU temps: https://github.com/MichaIng/DietPi/issues/2715
+			# CPU temps: Patch for millidegree: https://github.com/MichaIng/DietPi/issues/2715
 			(( $BENCH_CPU_TEMP_START > 200 )) && (( BENCH_CPU_TEMP_START /= 1000 ))
 			(( $BENCH_CPU_TEMP_END > 200 )) && (( BENCH_CPU_TEMP_END /= 1000 ))
 
@@ -603,10 +595,7 @@ shopt -s extglob
 		fi
 
 		# RootFS
-		# - Remove decimal places
-		BENCH_ROOTFS_WRITE=${BENCH_ROOTFS_WRITE%%.*}
-		BENCH_ROOTFS_READ=${BENCH_ROOTFS_READ%%.*}
-		if [[ $BENCH_ROOTFS_WRITE =~ ^[0-9]*[1-9][0-9]*$ && $BENCH_ROOTFS_READ =~ ^[0-9]*[1-9][0-9]*$ ]]; then
+		if [[ $BENCH_ROOTFS_WRITE =~ ^[0-9]+$ && $BENCH_ROOTFS_READ =~ ^[0-9]+$ ]]; then
 
 			aBENCH_ROOTFS_WRITE[$BENCH_HW_MODEL,${aBENCH_ROOTFS_INDEX[$BENCH_HW_MODEL]:=0}]=$BENCH_ROOTFS_WRITE
 			aBENCH_ROOTFS_READ[$BENCH_HW_MODEL,${aBENCH_ROOTFS_INDEX[$BENCH_HW_MODEL]}]=$BENCH_ROOTFS_READ
@@ -615,11 +604,8 @@ shopt -s extglob
 		fi
 
 		# RAM
-		# - https://github.com/MichaIng/DietPi/issues/2715 | nullify this score and ignore it in min/max/avg processing.
-		# - Remove decimal places
-		BENCH_RAM_WRITE=${BENCH_RAM_WRITE%%.*}
-		BENCH_RAM_READ=${BENCH_RAM_READ%%.*}
-		if [[ $BENCH_VERSION =~ ^[0-9]+$ && $BENCH_RAM_WRITE =~ ^[0-9]*[1-9][0-9]*$ && $BENCH_RAM_READ =~ ^[0-9]*[1-9][0-9]*$ ]] && (( $BENCH_VERSION > 1 )); then
+		# - Skip results prior to DietPi-Benchmark v2 (DietPi v6.23): https://github.com/MichaIng/DietPi/issues/2715
+		if (( $BENCH_VERSION > 1 )) && [[ $BENCH_RAM_WRITE =~ ^[0-9]+$ && $BENCH_RAM_READ =~ ^[0-9]+$ ]]; then
 
 			aBENCH_RAM_WRITE[$BENCH_HW_MODEL,${aBENCH_RAM_INDEX[$BENCH_HW_MODEL]:=0}]=$BENCH_RAM_WRITE
 			aBENCH_RAM_READ[$BENCH_HW_MODEL,${aBENCH_RAM_INDEX[$BENCH_HW_MODEL]}]=$BENCH_RAM_READ
@@ -628,10 +614,7 @@ shopt -s extglob
 		fi
 
 		# Custom FS
-		# - Remove decimal places
-		BENCH_CUSTOMFS_WRITE=${BENCH_CUSTOMFS_WRITE%%.*}
-		BENCH_CUSTOMFS_READ=${BENCH_CUSTOMFS_READ%%.*}
-		if [[ $BENCH_CUSTOMFS_WRITE =~ ^[0-9]*[1-9][0-9]*$ && $BENCH_CUSTOMFS_READ =~ ^[0-9]*[1-9][0-9]*$ ]]; then
+		if [[ $BENCH_CUSTOMFS_WRITE =~ ^[0-9]+$ && $BENCH_CUSTOMFS_READ =~ ^[0-9]+$ ]]; then
 
 			aBENCH_CUSTOMFS_WRITE[$BENCH_HW_MODEL,${aBENCH_CUSTOMFS_INDEX[$BENCH_HW_MODEL]:=0}]=$BENCH_CUSTOMFS_WRITE
 			aBENCH_CUSTOMFS_READ[$BENCH_HW_MODEL,${aBENCH_CUSTOMFS_INDEX[$BENCH_HW_MODEL]}]=$BENCH_CUSTOMFS_READ
@@ -640,9 +623,7 @@ shopt -s extglob
 		fi
 
 		# LAN
-		# - Remove decimal places
-		BENCH_NET_LAN_SPEED=${BENCH_NET_LAN_SPEED%%.*}
-		if [[ $BENCH_NET_LAN_SPEED =~ ^[0-9]*[1-9][0-9]*$ ]]; then
+		if [[ $BENCH_NET_LAN_SPEED =~ ^[0-9]+$ ]]; then
 
 			aBENCH_NET_LAN_SPEED[$BENCH_HW_MODEL,${aBENCH_LAN_INDEX[$BENCH_HW_MODEL]:=0}]=$BENCH_NET_LAN_SPEED
 			((aBENCH_LAN_INDEX[$BENCH_HW_MODEL]++))
@@ -747,9 +728,9 @@ shopt -s extglob
 				# Last item in current array. Work out averages
 				(( $j == ${aBENCH_CPU_INDEX[$i]} - 1 )) || continue
 				# - Devide CPU times by 100 and scale to revert decimal point removal
-				aBENCH_RESULT_CPU_MIN[$i]=$(printf "%.${BENCH_RESULTS_CPU_SCALE}f" "${aBENCH_RESULT_CPU_MIN[$i]}e-2")
-				aBENCH_RESULT_CPU_MAX[$i]=$(printf "%.${BENCH_RESULTS_CPU_SCALE}f" "${aBENCH_RESULT_CPU_MAX[$i]}e-2")
-				aBENCH_RESULT_CPU_AVG[$i]=$(printf "%.${BENCH_RESULTS_CPU_SCALE}f" "$((${aBENCH_RESULT_CPU_AVG[$i]}*10/${aBENCH_CPU_INDEX[$i]}+1))e-3")
+				aBENCH_RESULT_CPU_MIN[$i]=$(printf '%.2f' "${aBENCH_RESULT_CPU_MIN[$i]}e-2")
+				aBENCH_RESULT_CPU_MAX[$i]=$(printf '%.2f' "${aBENCH_RESULT_CPU_MAX[$i]}e-2")
+				aBENCH_RESULT_CPU_AVG[$i]=$(printf '%.2f' "$((${aBENCH_RESULT_CPU_AVG[$i]}*10/${aBENCH_CPU_INDEX[$i]}+1))e-3")
 				aBENCH_RESULT_CPU_TEMP_START_AVG[$i]=$(( ${aBENCH_RESULT_CPU_TEMP_START_AVG[$i]} / ${aBENCH_CPU_INDEX[$i]} ))
 				aBENCH_RESULT_CPU_TEMP_END_AVG[$i]=$(( ${aBENCH_RESULT_CPU_TEMP_END_AVG[$i]} / ${aBENCH_CPU_INDEX[$i]} ))
 			done
@@ -861,7 +842,6 @@ shopt -s extglob
 <html lang="en">
 	<head>
 		<meta charset="utf-8">
-		<link rel="home" href="https://dietpi.com/">
 		<link rel="canonical" href="https://dietpi.com/survey/">
 		<title>DietPi-Survey statistics</title>
 		<meta name="description" content="DietPi usage statistics and benchmarks based on DietPi-Survey uploads">
@@ -951,7 +931,7 @@ shopt -s extglob
 	</head>
 	<body>
 		<nav style="height: 40px; width: 100%; position: fixed; top: 0; left: 0; right: 0; padding: 10px 10px; background-color: #181a1c; display: inline-table">
-			<a href="/" rel="home" style="padding: 10px 60px; background-image: url(/images/dietpi-logo_240x80.png); background-size: cover; background-position: bottom"/>
+			<a href="/" style="padding: 10px 60px; background-image: url(/images/dietpi-logo_240x80.png); background-size: cover; background-position: bottom"/>
 			<a href="#device">Device</a>
 			<a href="#distro">Distro</a>
 			<a href="#software">Software</a>
