v7.8
+ DietPi-Survey_report | Be more verbose about why a survey upload was found to be invalid

diff --git a/.meta/dietpi-survey_report b/.meta/dietpi-survey_report
--- a/.meta/dietpi-survey_report
+++ b/.meta/dietpi-survey_report
@@ -617,20 +617,34 @@ shopt -s extglob
 				'BENCH_CPU_TEMP_START='*) BENCH_CPU_TEMP_START=${line#*\'} BENCH_CPU_TEMP_START=${BENCH_CPU_TEMP_START%\'};;
 				'BENCH_CPU_TEMP_END='*) BENCH_CPU_TEMP_END=${line#*\'} BENCH_CPU_TEMP_END=${BENCH_CPU_TEMP_END%\'};;
 				'BENCH_NET_LAN_SPEED='*) BENCH_NET_LAN_SPEED=${line#*\'} BENCH_NET_LAN_SPEED=${BENCH_NET_LAN_SPEED%\'};;
-				*) mv -v "/home/dietpi-survey/survey/$file" /home/dietpi-survey/invalid/; return 1;; # Invalid line
+				*)
+					echo "Invalid line: $line"
+					mv -v "/home/dietpi-survey/survey/$file" /home/dietpi-survey/invalid/
+					return 1
+				;;
 			esac
 
 			# Validate and process software name if present
 			[[ $software ]] || continue
 			eval "software=\${aSOFTWARE_NAME${version/./_}[$software]}"
-			[[ $software ]] || { mv -v "/home/dietpi-survey/survey/$file" /home/dietpi-survey/invalid/; return 1; }
+			if [[ ! $software ]]
+			then
+				echo "Invalid software ID for DietPi version $version"
+				mv -v "/home/dietpi-survey/survey/$file" /home/dietpi-survey/invalid/
+				return 1
+			fi
 			asoftware+=("$software")
 			unset -v software
 
 		done < "$file"
 
 		# Values that must exist
-		[[ $version && $device && $arch && $cpu_count && $distro && $autostart && ${aAUTOSTART_NAME[$autostart]} && $automated && $iface ]] || { mv -v "/home/dietpi-survey/survey/$file" /home/dietpi-survey/invalid/; return 1; }
+		if ! [[ $version && $device && $arch && $cpu_count && $distro && $autostart && ${aAUTOSTART_NAME[$autostart]} && $automated && $iface ]]
+		then
+			echo 'Missing survey value'
+			mv -v "/home/dietpi-survey/survey/$file" /home/dietpi-survey/invalid/
+			return 1
+		fi
 
 		# Sort out files that are > 6 months old
 		(( $DATE_NOW - $(date -u '+%s' -r "$file") < 15724800 )) || { mv "/home/dietpi-survey/survey/$file" /home/dietpi-survey/old/; ((SURVEY_COUNT_INACTIVE++)); return 0; }
@@ -738,7 +752,12 @@ shopt -s extglob
 		for file in *
 		do
 			# Skip and move away match with invalid name or when not a file
-			[[ $file =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.txt$ && -f $file ]] || { mv -v "/home/dietpi-survey/survey/$file" /home/dietpi-survey/invalid/; continue; }
+			if ! [[ $file =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.txt$ && -f $file ]]
+			then
+				echo 'Invalid file name'
+				mv -v "/home/dietpi-survey/survey/$file" /home/dietpi-survey/invalid/
+				continue
+			fi
 
 			# Optout files
 			if [[ ! -s $file ]]
