v8.2
- DietPi-Imager | Add support for non-DietPi host systems
- DietPi-Build | Attempt to assure that within systemd-nspawn container /dev/console is not seen as capable terminal

diff --git a/.meta/dietpi-imager b/.meta/dietpi-imager
--- a/.meta/dietpi-imager
+++ b/.meta/dietpi-imager
@@ -17,7 +17,15 @@
 	#////////////////////////////////////
 
 	# Import DietPi-Globals ---------------------------------------------------------------
-	. /boot/dietpi/func/dietpi-globals
+	if [[ -f '/boot/dietpi/func/dietpi-globals' ]]
+	then
+		. /boot/dietpi/func/dietpi-globals
+	else
+		[[ $G_GITOWNER && $G_GITBRANCH ]] || { echo '[FAILED] You must export or pass G_GITOWNER and G_GITBRANCH to the script'; exit 1; }
+		curl -sSf "https://raw.githubusercontent.com/$G_GITOWNER/DietPi/$G_GITBRANCH/dietpi/func/dietpi-globals" -o /tmp/dietpi-globals || exit 1
+		. /tmp/dietpi-globals
+		G_EXEC_NOHALT=1 G_EXEC rm /tmp/dietpi-globals
+	fi
 	readonly G_PROGRAM_NAME='DietPi-Imager'
 	G_CHECK_ROOT_USER
 	G_CHECK_ROOTFS_RW
