META | DietPi-Image: Only resize2fs needs to run multiple times; Add root check, GB locale and /tmp working dir

diff --git a/.meta/dietpi-image b/.meta/dietpi-image
--- a/.meta/dietpi-image
+++ b/.meta/dietpi-image
@@ -26,6 +26,15 @@
 	ROOT=$3
 	[[ $4 == GPT ]] && GPT=1 || GPT=0
 
+	# Check root
+	(( $UID )) && { echo 'ERROR: This script must run with root permissions. Please retry with "sudo".'; exit 1; }
+
+	# Force locale
+	export LC_ALL='en_GB.UTF-8'
+
+	# Move to /tmp for temp file creation
+	cd /tmp
+
 	# Check source
 	SOURCE_IS_FILE=1
 	if [[ $SOURCE == /dev/* ]]; then
@@ -39,6 +48,7 @@
 
 	fi
 
+	# Install required packages
 	apt-get -y install gparted gdisk gpart dosfstools zerofree p7zip
 
 	# GPT images (RockPro64) after reading the image AND again after shrinking
@@ -73,25 +83,35 @@
 	# Fsck
 	e2fsck -f $ROOT_DEV
 
-	# Run the shrinking multiple times as the size can be reduced every time a bid more
-	for i in {0..2}
+	# Shrink file system
+	# - Run multiple times until no change is done any more
+	out=''
+	FS_SIZE=0
+	while :
 	do
 
-		# Shrink root file system to minimum size
-		resize2fs -M $ROOT_DEV
-		read -p 'The minimum file system size above is as well the minimum for gparted, besides gparted shows a larger minimum already.
-Press CTRL+C to exit, else gparted will now start to allow partition resizing'
+		resize2fs -M $ROOT_DEV | tee resize2fs_out
+		if out=$(grep -m1 'Nothing to do!' resize2fs_out); then
 
-		# gparted to resize boot partition to minimum
-		gparted $SOURCE
-		read -p 'If failed press CTRL+C to exit and prevent further action, else, press any key to continue...'
+			FS_SIZE=$(mawk '{print $5 * 4096}' <<< $out)
+			echo "[  OK  ] Shrunken file system to $FS_SIZE bytes"
+			break
 
-		sync
-
-		# Override free space with zeros to purge removed data and allow further image/archive size reduction
-		zerofree -v $ROOT_DEV
+		fi
 
 	done
+
+	read -p 'The minimum file system size above is as well the minimum for gparted, besides gparted shows a larger minimum already.
+Press CTRL+C to exit, else gparted will now start to allow partition resizing'
+
+	# gparted to resize boot partition to minimum
+	gparted $SOURCE
+	read -p 'If failed press CTRL+C to exit and prevent further action, else, press any key to continue...'
+
+	sync
+
+	# Override free space with zeros to purge removed data and allow further image/archive size reduction
+	zerofree -v $ROOT_DEV
 
 	# GPT images (RockPro64) after reading the image AND again after shrinking
 	# To fix:
