v6.31
+ DietPi-Imager | Open interactive bash subshell for image content review/changes if user chooses to
+ DietPi-Imager | Wrap fsck into G_EXEC error handler to allow rerun in case of found errors, wrap more commands into G_EXEC to prevent unexpected states and increased verbosity

diff --git a/.meta/dietpi-imager b/.meta/dietpi-imager
--- a/.meta/dietpi-imager
+++ b/.meta/dietpi-imager
@@ -29,7 +29,7 @@
 	FP_SOURCE_IMG=
 	FP_SOURCE=
 	FP_ROOT_DEV=
-	FP_MNT_TMP='/tmp/tmp_rootfs'
+	FP_MNT_TMP="/tmp/$G_PROGRAM_NAME_rootfs"
 	ROOT_PARTITION_INDEX=0
 	OUTPUT_IMG_NAME=
 	OUTPUT_IMG_EXT='img'
@@ -204,23 +204,34 @@ Do you want to overwrite or backup the existing file to $PWD/$OUTPUT_IMG_NAME.$O
 
 		fi
 
-		e2fsck -f $FP_ROOT_DEV || exit 1
+		G_EXEC_OUTPUT= 1 G_EXEC e2fsck -f $FP_ROOT_DEV
 
 		# Remount image for any required edits
-		mkdir -p $FP_MNT_TMP
-		if G_EXEC_NOHALT=1 G_EXEC mount $FP_ROOT_DEV $FP_MNT_TMP; then
+		G_EXEC mkdir -p $FP_MNT_TMP
+		G_EXEC mount $FP_ROOT_DEV $FP_MNT_TMP
+		# - Remove bash history, which is stored on shutdown, hence cannot be removed via DietPi-PREP
+		rm -fv $FP_MNT_TMP/{root,home/*}/.bash_history
+		if G_WHIP_YESNO "Do you want to review/edit contained files?
+\nAn interactive bash subshell will open.
+\nPlease use the \"exit\" command when you are finished, to return to $G_PROGRAM_NAME.
+\nMount is: $FP_ROOT_DEV > $FP_MNT_TMP"; then
 
-			# Remove bash history, which is stored on shutdown, hence cannot be removed via DietPi-PREP
-			rm -fv $FP_MNT_TMP/{root,home/*}/.bash_history
-			G_WHIP_MSG "Image mounted for file editing, make changes if required: $FP_ROOT_DEV > $FP_MNT_TMP\n\nPress 'Ok' when you are finished."
-			sync
-			G_EXEC umount $FP_MNT_TMP
-			partprobe $FP_SOURCE # Failsafe
-			partx -u $FP_SOURCE # Failsafe
-			e2fsck -f $FP_ROOT_DEV || exit 1 # Failsafe
+			# Prevent dietpi-login call in subshell
+			local reallow_dietpi_login=1
+			[[ $G_DIETPI_LOGIN ]] && reallow_dietpi_login=0
+			export G_DIETPI_LOGIN=1
+			G_EXEC cd $FP_MNT_TMP
+			bash &> /dev/tty < /dev/tty
+			G_EXEC cd $FP_ORIGIN
+			(( $reallow_dietpi_login )) && unset -v G_DIETPI_LOGIN
 
 		fi
-		rmdir $FP_MNT_TMP
+		sync
+		G_EXEC umount $FP_MNT_TMP
+		G_EXEC rmdir $FP_MNT_TMP
+		G_EXEC partprobe $FP_SOURCE # Failsafe
+		G_EXEC partx -u $FP_SOURCE # Failsafe
+		G_EXEC_OUTPUT= 1 G_EXEC e2fsck -f $FP_ROOT_DEV || exit 1 # Failsafe
 
 		# Shrink file system to minimum
 		# - Run multiple times until no change is done any more
