v6.25 (WIP)

diff --git a/.meta/dietpi-imager b/.meta/dietpi-imager
--- a/.meta/dietpi-imager
+++ b/.meta/dietpi-imager
@@ -25,16 +25,37 @@
 	FP_LOOPBACK=''
 	FP_ROOT_DEV=''
 	ROOT_PARTITION_INDEX=''
-	OUTPUT_FILE_NAME=''
+	OUTPUT_IMG_NAME=''
 	OUTPUT_7Z_NAME=''
 	GPT=0
 	DIETPI_VERSION='v6.25'
 
+
+
+	Delete_Loopback(){
+
+		[[ $FP_LOOPBACK ]] && G_RUN_CMD losetup -d $FP_LOOPBACK
+
+	}
+
+	Exit_On_Fail(){
+
+		Delete_Loopback
+		exit 1
+
+	}
+
 	Menu_Main(){
 
+		G_WHIP_MENU_ARRAY=(
 
-		#Read image?
-		if G_WHIP_YESNO 'Would you like to save an existing disk to image? eg: /dev/sda > myimage.img'; then
+			'Drive' ': Save a drive/disk contents to an image, that you can work with'
+			'Image' ': Use an existing image file (.img) to work with'
+
+		)
+
+		! G_WHIP_MENU 'Please select a option:' && Exit_On_Fail
+		if [[ ${G_WHIP_RETURNED_VALUE,,} == 'drive' ]]; then
 
 			#detect drives and list?
 			blkid -o device > .blkid_list
@@ -42,36 +63,36 @@
 			while read line
 			do
 
-				G_WHIP_MENU_ARRAY+=("$line" '')
+				G_WHIP_MENU_ARRAY+=("${line//[0-9]/}" '')
 
 			done < .blkid_list
 			rm .blkid_list
 
-			! G_WHIP_MENU 'Please select the drive you wish to save as an image:' && exit 1
+			! G_WHIP_MENU 'Please select the drive you wish to save as an image:' && Exit_On_Fail
 			FP_SOURCE="$HOME/myimage.img"
-			! dd if=$G_WHIP_RETURNED_VALUE of=$FP_SOURCE bs=4K status=progress && exit 1
+			! dd if=$G_WHIP_RETURNED_VALUE of=$FP_SOURCE bs=4K status=progress && Exit_On_Fail
 
-		#Select image
-		else
+		elif [[ ${G_WHIP_RETURNED_VALUE,,} == 'image' ]]; then
 
 			/DietPi/dietpi/dietpi-explorer 1 $HOME
 			local fp_selected='/tmp/.dietpi-explorer_selected_location'
-			[[ ! -f $fp_selected ]] && exit 1
-			FP_SOURCE=$(</tmp/.dietpi-explorer_selected_location)
+			[[ ! -f $fp_selected ]] && Exit_On_Fail
+			FP_SOURCE=$(< $fp_selected)
+			rm $fp_selected
 
 		fi
 
-		G_WHIP_YESNO 'Is this a GPT filesystem?' && GPT=1
+		G_WHIP_YESNO "Is $FP_SOURCE a GPT filesystem?" && GPT=1
 
-		! G_WHIP_INPUTBOX 'Please enter the RootFS parition number (eg: 1)' && exit 1
+		! G_WHIP_INPUTBOX "Please enter the RootFS parition number for $FP_SOURCE (eg: 1)" && Exit_On_Fail
 		ROOT_PARTITION_INDEX=$G_WHIP_RETURNED_VALUE
 
 		G_WHIP_DEFAULT_ITEM="DietPi_<device>-<arch>-<distro>"
-		! G_WHIP_INPUTBOX "Please enter the output filename\n - DietPi_<device>-<arch>-<distro>\n - EG: DietPi_RPi-armv6-stretch" && exit 1
-		OUTPUT_FILE_NAME=$G_WHIP_RETURNED_VALUE
+		! G_WHIP_INPUTBOX "Please enter the new/output filename for $FP_SOURCE\n - DietPi_<device>-<arch>-<distro>\n - EG: DietPi_RPi-armv6-stretch" && Exit_On_Fail
+		OUTPUT_IMG_NAME=$G_WHIP_RETURNED_VALUE
 
 		G_WHIP_DEFAULT_ITEM=$DIETPI_VERSION
-		! G_WHIP_INPUTBOX "Please enter the DietPi version for this image" && exit 1
+		! G_WHIP_INPUTBOX "Please enter the DietPi version for this image" && Exit_On_Fail
 		DIETPI_VERSION=$G_WHIP_RETURNED_VALUE
 
 	}
@@ -82,7 +103,8 @@
 
 		if [[ ! -f $FP_SOURCE ]]; then
 
-			echo "ERROR: Source image file ($FP_SOURCE) does not exist"; exit 1;
+			echo "ERROR: Source image file ($FP_SOURCE) does not exist"
+			Exit_On_Fail
 
 		fi
 
@@ -96,7 +118,7 @@
 		# RUN
 		# - gdisk "$IMAGE_FP/$IMAGE_NAME"
 		#	w | y
-		(( $GPT )) && echo 'w\ny\nq\n' | gdisk $FP_SOURCE
+		(( $GPT )) && echo 'w\ny\nq\n' | gdisk $FP_SOURCE #needs testing for automation...
 
 		# Attach .img file to loop device
 		modprobe loop
@@ -130,11 +152,23 @@
 
 			elif out=$(grep -m1 -i 'no such file or directory' resize2fs_out); then
 
-				echo '[FAIL] Partition not found' && exit 1
+				echo '[FAIL] Partition not found' && Exit_On_Fail
 
 			fi
 
 		done
+
+		# Remount image for any required edits.
+		fp_mnt='loopback_rootfs'
+		mkdir -p /mnt/$fp_mnt
+		if G_ERROR_HANDLER_INFO_ONLY=1 G_RUN_CMD mount $FP_ROOT_DEV /mnt/$fp_mnt; then
+
+			G_WHIP_MSG "Image mounted for file editing, make changes if required: $FP_ROOT_DEV > /mnt/$fp_mnt\n\nPress 'Ok' when you are finished."
+			sync
+			G_RUN_CMD umount /mnt/$fp_mnt
+			partprobe $FP_LOOPBACK #probably not required as no partition changes, regardless, no harm.
+
+		fi
 
 		# Estimate minimum end sector
 		PART_START=$(fdisk -l -o Start $FP_SOURCE | tail -1) # 512 byte sectors
@@ -164,33 +198,44 @@
 		# Create final image in $HOME
 		cd $HOME
 
-		# add version number to output file name
-		OUTPUT_7Z_NAME="$OUTPUT_FILE_NAME.7z"
-		OUTPUT_FILE_NAME=${OUTPUT_FILE_NAME//DietPi_/DietPi_${DIETPI_VERSION}_}
-
 		#  truncate to used size
 		truncate --size=$IMAGE_SIZE "$FP_SOURCE"
-		mv $FP_SOURCE $OUTPUT_FILE_NAME.img #TODO: if not same file...
+
+		# Loopback finished, clear loop
+		partprobe $FP_LOOPBACK
+		sync
+		Delete_Loopback
+
+		# add version number to output file name
+		OUTPUT_7Z_NAME="$OUTPUT_IMG_NAME.7z"
+		OUTPUT_IMG_NAME=${OUTPUT_IMG_NAME//DietPi_/DietPi_${DIETPI_VERSION}_}
+		OUTPUT_IMG_NAME+='.img'
+
+		# Move new img to HOME
+		mv $FP_SOURCE $OUTPUT_IMG_NAME #TODO: if not same already location/file...
 
 		# Generate hashes: MD5, SHA1, SHA256
 		echo '[INFO] Generating hash.txt, please wait...'
 		cat << _EOF_ > hash.txt
-FILE:	$OUTPUT_FILE_NAME.img
+FILE:	$OUTPUT_IMG_NAME
 DATE:	$(date)
-MD5:	$(md5sum $OUTPUT_FILE_NAME.img | mawk '{print $1}')
-SHA1:	$(sha1sum $OUTPUT_FILE_NAME.img | mawk '{print $1}')
-SHA256:	$(sha256sum $OUTPUT_FILE_NAME.img | mawk '{print $1}')
+MD5:	$(md5sum $OUTPUT_IMG_NAME | mawk '{print $1}')
+SHA1:	$(sha1sum $OUTPUT_IMG_NAME | mawk '{print $1}')
+SHA256:	$(sha256sum $OUTPUT_IMG_NAME | mawk '{print $1}')
 _EOF_
 
 		# Download current README
-		! wget https://raw.githubusercontent.com/MichaIng/DietPi/master/README.md -O README.md && exit 1
+		! wget https://raw.githubusercontent.com/MichaIng/DietPi/master/README.md -O README.md && Exit_On_Fail
 
 		# Generate 7z archive
 		# NB: LZMA2 ultra compression method requires 2G RAM
 		[[ -f $OUTPUT_7Z_NAME ]] && rm $OUTPUT_7Z_NAME
-		7zr a -m0=lzma2 -mx=9 $OUTPUT_7Z_NAME $OUTPUT_FILE_NAME.img hash.txt README.md
+		if 7zr a -m0=lzma2 -mx=9 $OUTPUT_7Z_NAME $OUTPUT_IMG_NAME hash.txt README.md; then
 
-		[[ -f $OUTPUT_7Z_NAME ]] && G_WHIP_MSG "[INFO] $HOME/$OUTPUT_7Z_NAME created"
+			rm hash.txt README.md
+			G_WHIP_MSG "[INFO] $HOME/$OUTPUT_7Z_NAME created"
+
+		fi
 
 	}
 
