v7.1
+ DietPi-Survey_report | Further syntax and old version handling

diff --git a/.meta/dietpi-survey_report b/.meta/dietpi-survey_report
--- a/.meta/dietpi-survey_report
+++ b/.meta/dietpi-survey_report
@@ -512,6 +512,8 @@ shopt -s extglob
 			case "$line" in
 
 				'#'*) :;; # Pre-v7.1
+				'((aSURVEY_VERSION[6]++))') :;; # Pre-v6.22
+				'((aSURVEY_SENTCOUNT['+([[:digit:]])']++))') :;; # Pre-v6.22
 				'((aDIETPI_VERSION['7.[[:digit:]]']++))'|'((aDIETPI_VERSION['6.[123][[:digit:]]']++))') version=${line#*'['} version=${version%']'*};;
 				'((aGIT_BRANCH['+([[:graph:]])']++))') branch=${line#*'['} branch=${branch%']'*};; # since v6.17
 				'((aDEVICE_NAME['+([[:print:]])']++))') device=${line#*'['} device=${device%']'*};;
@@ -519,22 +521,25 @@ shopt -s extglob
 				'((aCPU_COUNT['+([[:digit:]])']++))') cpu_count=${line#*'['} cpu_count=${cpu_count%']'*};;
 				'((aDISTRO_VERSION['+([[:alpha:]])']++))') distro=${line#*'['} distro=${distro%']'*};;
 				'((aAUTOSTART_OPTION[${aAUTOSTART_NAME['+([[:digit:]])']:='+([[:digit:]])'}]++))') autostart=${line##*'['} autostart=${autostart%%']'*};;
+				'((aAUTOSTART_OPTION[${aAUTOSTART_NAME['+([[:digit:]])']}]++))') autostart=${line##*'['} autostart=${autostart%%']'*};; # Pre-v6.17
 				'((aAUTO_SETUP_AUTOMATED['[01]']++))') automated=${line#*'['} automated=${automated%']'*};;
 				'((aNETWORK_INTERFACE['+([[:graph:]])']++))') iface=${line#*'['} iface=${iface%']'*};;
 				'((aRASPBIAN['[01]']++))') raspbian=${line#*'['} raspbian=${raspbian%']'*};; # since v6.31
 				'((aSOFTWARE[${aSOFTWARE_NAME'${version/./_}'['+([[:digit:]])']:='+([[:digit:]])'}]++))') software=${line##*'['} software=${software%%']'*};;
+				'((aSOFTWARE[${aSOFTWARE_NAME'${version/./_}'['+([[:digit:]])']}]++))') software=${line##*'['} software=${software%%']'*};; # Pre-v6.17
 				'BENCH_VERSION='[12]) BENCH_VERSION=${line#*'='};; # 1 until v6.23, 2 afterwards
 				'BENCH_HW_MODEL='+([[:digit:]])) BENCH_HW_MODEL=${line#*'='};;
-				'BENCH_CPU=') BENCH_CPU=${line#*\'} BENCH_CPU=${BENCH_CPU%\'};;
-				'BENCH_ROOTFS_WRITE=') BENCH_ROOTFS_WRITE=${line#*\'} BENCH_ROOTFS_WRITE=${BENCH_ROOTFS_WRITE%\'};;
-				'BENCH_ROOTFS_READ=') BENCH_ROOTFS_READ=${line#*\'} BENCH_ROOTFS_READ=${BENCH_ROOTFS_READ%\'};;
-				'BENCH_RAM_WRITE=') BENCH_RAM_WRITE=${line#*\'} BENCH_RAM_WRITE=${BENCH_RAM_WRITE%\'};;
-				'BENCH_RAM_READ=') BENCH_RAM_READ=${line#*\'} BENCH_RAM_READ=${BENCH_RAM_READ%\'};;
-				'BENCH_CUSTOMFS_WRITE=') BENCH_CUSTOMFS_WRITE=${line#*\'} BENCH_CUSTOMFS_WRITE=${BENCH_CUSTOMFS_WRITE%\'};;
-				'BENCH_CUSTOMFS_READ=') BENCH_CUSTOMFS_READ=${line#*\'} BENCH_CUSTOMFS_READ=${BENCH_CUSTOMFS_READ%\'};;
-				'BENCH_CPU_TEMP_START=') BENCH_CPU_TEMP_START=${line#*\'} BENCH_CPU_TEMP_START=${BENCH_CPU_TEMP_START%\'};;
-				'BENCH_CPU_TEMP_END=') BENCH_CPU_TEMP_END=${line#*\'} BENCH_CPU_TEMP_END=${BENCH_CPU_TEMP_END%\'};;
-				'BENCH_NET_LAN_SPEED=') BENCH_NET_LAN_SPEED=${line#*\'} BENCH_NET_LAN_SPEED=${BENCH_NET_LAN_SPEED%\'};;
+				'BENCH_HW_MODEL=-1') BENCH_HW_MODEL=22;; # Pre-v6.29: Migrate fallback "-1" to Generic Device
+				'BENCH_CPU='*) BENCH_CPU=${line#*\'} BENCH_CPU=${BENCH_CPU%\'};;
+				'BENCH_ROOTFS_WRITE='*) BENCH_ROOTFS_WRITE=${line#*\'} BENCH_ROOTFS_WRITE=${BENCH_ROOTFS_WRITE%\'};;
+				'BENCH_ROOTFS_READ='*) BENCH_ROOTFS_READ=${line#*\'} BENCH_ROOTFS_READ=${BENCH_ROOTFS_READ%\'};;
+				'BENCH_RAM_WRITE='*) BENCH_RAM_WRITE=${line#*\'} BENCH_RAM_WRITE=${BENCH_RAM_WRITE%\'};;
+				'BENCH_RAM_READ='*) BENCH_RAM_READ=${line#*\'} BENCH_RAM_READ=${BENCH_RAM_READ%\'};;
+				'BENCH_CUSTOMFS_WRITE='*) BENCH_CUSTOMFS_WRITE=${line#*\'} BENCH_CUSTOMFS_WRITE=${BENCH_CUSTOMFS_WRITE%\'};;
+				'BENCH_CUSTOMFS_READ='*) BENCH_CUSTOMFS_READ=${line#*\'} BENCH_CUSTOMFS_READ=${BENCH_CUSTOMFS_READ%\'};;
+				'BENCH_CPU_TEMP_START='*) BENCH_CPU_TEMP_START=${line#*\'} BENCH_CPU_TEMP_START=${BENCH_CPU_TEMP_START%\'};;
+				'BENCH_CPU_TEMP_END='*) BENCH_CPU_TEMP_END=${line#*\'} BENCH_CPU_TEMP_END=${BENCH_CPU_TEMP_END%\'};;
+				'BENCH_NET_LAN_SPEED='*) BENCH_NET_LAN_SPEED=${line#*\'} BENCH_NET_LAN_SPEED=${BENCH_NET_LAN_SPEED%\'};;
 				*) mv -v "/home/dietpi-survey/survey/$file" /home/dietpi-survey/invalid/; return 1;; # Invalid line
 
 			esac
@@ -560,18 +565,19 @@ shopt -s extglob
 		((aDEVICE_NAME["$device"]++))
 		((aCPU_ARCH["$arch"]++))
 		((aCPU_COUNT["$cpu_count"]++))
+		((aDISTRO_VERSION["$distro"]++))
 		((aAUTOSTART_OPTION[${aAUTOSTART_NAME["$autostart"]}]++))
 		((aAUTO_SETUP_AUTOMATED["$automated"]++))
 		((aNETWORK_INTERFACE["$iface"]++))
-		((aRASPBIAN["$raspbian"]++))
-		((aDIETPI_VERSION["$version"]++))
+		[[ $raspbian ]] && ((aRASPBIAN["$raspbian"]++))
 		for i in "${asoftware[@]}"
 		do
 			((aSOFTWARE["$i"]++))
 		done
 
 		# Process benchmark results is present and hardware ID valid
-		[[ $BENCH_VERSION && $BENCH_HW_MODEL && ${aHW_NAME[$BENCH_HW_MODEL]} ]] || continue
+		[[ $BENCH_VERSION && $BENCH_HW_MODEL ]] || return 0
+		[[ ${aHW_NAME[$BENCH_HW_MODEL]} ]] || { echo "Invalid hardware ID: $BENCH_HW_MODEL"; return 1; }
 
 		# CPU
 		# - BENCH_CPU: Remove decimal point, equals times 100 since CPU time is always in x.xx
@@ -945,7 +951,7 @@ shopt -s extglob
 		<table>
 			<tr><td>Total system count</td><td align="right">$SURVEY_COUNT_TOTAL</td></tr>
 			<tr><td>Systems sending survey data</td><td align="right">$SURVEY_COUNT_OPTIN</td><td align="right">$(( $SURVEY_COUNT_OPTIN * 100 / $SURVEY_COUNT_TOTAL ))%</td></tr>
-			<tr><td>Systems opted out DietPi-Survey</td><td align="right">$SURVEY_COUNT_OPTOUT</td><td align="right">$(( $SURVEY_COUNT_EMPTY * 100 / $SURVEY_COUNT_TOTAL ))%</td></tr>
+			<tr><td>Systems opted out DietPi-Survey</td><td align="right">$SURVEY_COUNT_OPTOUT</td><td align="right">$(( $SURVEY_COUNT_OPTOUT * 100 / $SURVEY_COUNT_TOTAL ))%</td></tr>
 		</table>
 
 		<h3 id="version"><a href="#version">DietPi versions &para</a></h3>
@@ -1024,7 +1030,7 @@ shopt -s extglob
 				<td bgcolor="#2B5D00">Lowest</td>
 				<td bgcolor="#5D0000">Highest</td>
 			</tr>
-			$(for i in "${!aBENCH_CPU_INDEX[@]}"; do echo "<tr><td>${aHW_NAME[$i]:=$i}</td><td>${aBENCH_CPU_INDEX[$i]}</td><td bgcolor=\"#34005D\">	${aBENCH_RESULT_CPU_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_CPU_MIN[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_CPU_MAX[$i]}</td><td bgcolor=\"#34005D\">${aBENCH_RESULT_CPU_TEMP_START_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_CPU_TEMP_START_MIN[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_CPU_TEMP_START_MAX[$i]}</td><td bgcolor=\"#34005D\">${aBENCH_RESULT_CPU_TEMP_END_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_CPU_TEMP_END_MIN[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_CPU_TEMP_END_MAX[$i]}</td></tr>"; done | sort -nk 2 -t '	')
+			$(for i in "${!aBENCH_CPU_INDEX[@]}"; do echo "<tr><td>${aHW_NAME[$i]}</td><td>${aBENCH_CPU_INDEX[$i]}</td><td bgcolor=\"#34005D\">	${aBENCH_RESULT_CPU_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_CPU_MIN[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_CPU_MAX[$i]}</td><td bgcolor=\"#34005D\">${aBENCH_RESULT_CPU_TEMP_START_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_CPU_TEMP_START_MIN[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_CPU_TEMP_START_MAX[$i]}</td><td bgcolor=\"#34005D\">${aBENCH_RESULT_CPU_TEMP_END_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_CPU_TEMP_END_MIN[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_CPU_TEMP_END_MAX[$i]}</td></tr>"; done | sort -nk 2 -t '	')
 		</table>
 
 		<h3 id="bench_ram"><a href="#bench_ram">DietPi-Benchmarks | RAM I/O &para</a></h3>
@@ -1044,7 +1050,7 @@ shopt -s extglob
 				<td bgcolor="#2B5D00">Fastest</td>
 				<td bgcolor="#5D0000">Slowest</td>
 			</tr>
-			$(for i in "${!aBENCH_RAM_INDEX[@]}"; do echo "<tr><td>${aHW_NAME[$i]:=$i}</td><td>${aBENCH_RAM_INDEX[$i]}</td><td bgcolor=\"#34005D\">	${aBENCH_RESULT_RAM_WRITE_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_RAM_WRITE_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_RAM_WRITE_MIN[$i]}</td><td bgcolor=\"#34005D\">${aBENCH_RESULT_RAM_READ_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_RAM_READ_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_RAM_READ_MIN[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
+			$(for i in "${!aBENCH_RAM_INDEX[@]}"; do echo "<tr><td>${aHW_NAME[$i]}</td><td>${aBENCH_RAM_INDEX[$i]}</td><td bgcolor=\"#34005D\">	${aBENCH_RESULT_RAM_WRITE_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_RAM_WRITE_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_RAM_WRITE_MIN[$i]}</td><td bgcolor=\"#34005D\">${aBENCH_RESULT_RAM_READ_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_RAM_READ_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_RAM_READ_MIN[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
 		</table>
 
 		<h3 id="bench_disk"><a href="#bench_disk">DietPi-Benchmarks | RootFS I/O &para</a></h3>
@@ -1064,7 +1070,7 @@ shopt -s extglob
 				<td bgcolor="#2B5D00">Fastest</td>
 				<td bgcolor="#5D0000">Slowest</td>
 			</tr>
-			$(for i in "${!aBENCH_ROOTFS_INDEX[@]}"; do echo "<tr><td>${aHW_NAME[$i]:=$i}</td><td>${aBENCH_ROOTFS_INDEX[$i]}</td><td bgcolor=\"#34005D\">	${aBENCH_RESULT_ROOTFS_WRITE_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_ROOTFS_WRITE_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_ROOTFS_WRITE_MIN[$i]}</td><td bgcolor=\"#34005D\">${aBENCH_RESULT_ROOTFS_READ_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_ROOTFS_READ_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_ROOTFS_READ_MIN[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
+			$(for i in "${!aBENCH_ROOTFS_INDEX[@]}"; do echo "<tr><td>${aHW_NAME[$i]}</td><td>${aBENCH_ROOTFS_INDEX[$i]}</td><td bgcolor=\"#34005D\">	${aBENCH_RESULT_ROOTFS_WRITE_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_ROOTFS_WRITE_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_ROOTFS_WRITE_MIN[$i]}</td><td bgcolor=\"#34005D\">${aBENCH_RESULT_ROOTFS_READ_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_ROOTFS_READ_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_ROOTFS_READ_MIN[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
 		</table>
 
 		<h3 id="bench_custom"><a href="#bench_custom">DietPi-Benchmarks | Custom FS I/O &para</a></h3>
@@ -1084,7 +1090,7 @@ shopt -s extglob
 				<td bgcolor="#2B5D00">Fastest</td>
 				<td bgcolor="#5D0000">Slowest</td>
 			</tr>
-			$(for i in "${!aBENCH_CUSTOMFS_INDEX[@]}"; do echo "<tr><td>${aHW_NAME[$i]:=$i}</td><td>${aBENCH_CUSTOMFS_INDEX[$i]}</td><td bgcolor=\"#34005D\">	${aBENCH_RESULT_CUSTOMFS_WRITE_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_CUSTOMFS_WRITE_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_CUSTOMFS_WRITE_MIN[$i]}</td><td bgcolor=\"#34005D\">${aBENCH_RESULT_CUSTOMFS_READ_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_CUSTOMFS_READ_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_CUSTOMFS_READ_MIN[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
+			$(for i in "${!aBENCH_CUSTOMFS_INDEX[@]}"; do echo "<tr><td>${aHW_NAME[$i]}</td><td>${aBENCH_CUSTOMFS_INDEX[$i]}</td><td bgcolor=\"#34005D\">	${aBENCH_RESULT_CUSTOMFS_WRITE_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_CUSTOMFS_WRITE_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_CUSTOMFS_WRITE_MIN[$i]}</td><td bgcolor=\"#34005D\">${aBENCH_RESULT_CUSTOMFS_READ_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_CUSTOMFS_READ_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_CUSTOMFS_READ_MIN[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
 		</table>
 
 		<h3 id="bench_lan"><a href="#bench_lan">DietPi-Benchmarks | LAN I/O &para</a></h3>
@@ -1100,7 +1106,7 @@ shopt -s extglob
 				<td bgcolor="#2B5D00">Fastest</td>
 				<td bgcolor="#5D0000">Slowest</td>
 			</tr>
-			$(for i in "${!aBENCH_LAN_INDEX[@]}"; do echo "<tr><td>${aHW_NAME[$i]:=$i}</td><td>${aBENCH_LAN_INDEX[$i]}</td><td bgcolor=\"#34005D\">	${aBENCH_RESULT_NET_LAN_SPEED_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_NET_LAN_SPEED_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_NET_LAN_SPEED_MIN[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
+			$(for i in "${!aBENCH_LAN_INDEX[@]}"; do echo "<tr><td>${aHW_NAME[$i]}</td><td>${aBENCH_LAN_INDEX[$i]}</td><td bgcolor=\"#34005D\">	${aBENCH_RESULT_NET_LAN_SPEED_AVG[$i]}</td><td bgcolor=\"#2B5D00\">${aBENCH_RESULT_NET_LAN_SPEED_MAX[$i]}</td><td bgcolor=\"#5D0000\">${aBENCH_RESULT_NET_LAN_SPEED_MIN[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
 		</table>
 	</body>
 </html>
