v9.1
- DietPi-Patches | Move forward several kernel and software updates

diff --git a/.update/patches b/.update/patches
--- a/.update/patches
+++ b/.update/patches
@@ -1477,46 +1477,9 @@ Patch_8_25()
 
 Patch_9_0()
 {
-	# Quartz64
-	if (( $G_HW_MODEL == 49 ))
-	then
-		for i in quartz64{a,b} soquartz
-		do
-			dpkg --compare-versions "$(dpkg-query -Wf '${Version}' "firmware-$i" 2> /dev/null)" lt-nl 6.6.12-dietpi1 || continue
-			G_DIETPI-NOTIFY 2 "Updating $i kernel and bootloader ..."
-			G_EXEC_OUTPUT=1 G_EXEC curl -fo package.deb "https://dietpi.com/downloads/binaries/firmware-$i.deb"
-			G_EXEC_OUTPUT=1 G_EXEC dpkg -i --force-confdef,confold package.deb
-			G_EXEC rm package.deb
-			break
-		done
-
-	# VisionFive 2
-	elif (( $G_HW_MODEL == 81 )) && dpkg --compare-versions "$(dpkg-query -Wf '${Version}' linux-image-visionfive2 2> /dev/null)" lt-nl 6.1.73-dietpi1
-	then
-		G_DIETPI-NOTIFY 2 'Updating RISC-V StarFive VisionFive 2 kernel ...'
-		G_EXEC_OUTPUT=1 G_EXEC curl -fo package.deb 'https://dietpi.com/downloads/binaries/linux-image-visionfive2.deb'
-		G_EXEC_OUTPUT=1 G_EXEC dpkg -i --force-confdef,confold package.deb
-		G_EXEC rm package.deb
-
-	# Star64
-	elif (( $G_HW_MODEL == 84 )) && dpkg --compare-versions "$(dpkg-query -Wf '${Version}' linux-image-star64 2> /dev/null)" lt-nl 6.1.73-dietpi1
-	then
-		G_DIETPI-NOTIFY 2 'Updating RISC-V PINE64 Star64 kernel ...'
-		G_EXEC_OUTPUT=1 G_EXEC curl -fo package.deb 'https://dietpi.com/downloads/binaries/linux-image-star64.deb'
-		G_EXEC_OUTPUT=1 G_EXEC dpkg -i --force-confdef,confold package.deb
-		G_EXEC rm package.deb
-	fi
-
 	# Software updates and migrations
 	if [[ -f '/boot/dietpi/.installed' ]]
 	then
-		# Amiberry
-		if grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[108\]=2' /boot/dietpi/.installed && dpkg --compare-versions "$(dpkg-query -Wf '${Version}' amiberry 2> /dev/null)" lt 5.6.5-dietpi1
-		then
-			G_DIETPI-NOTIFY 2 'Preparing Amiberry upgrade to v5.6.5, including migration for RPi systems from fake KMS DispmanX to full KMS SDL2 graphics backend'
-			echo 108 >> /var/tmp/dietpi/dietpi-update_reinstalls
-		fi
-
 		# Nextcloud
 		# - Apache
 		if [[ -f '/etc/apache2/sites-available/dietpi-nextcloud.conf' ]]
@@ -1535,21 +1498,6 @@ Patch_9_0()
 
 		# Kodi
 		[[ -f '/usr/share/applications/kodi.desktop' ]] && G_CONFIG_INJECT 'Exec=' 'Exec=kodi --standalone' /usr/share/applications/kodi.desktop
-
-		# vaultwarden
-		if grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[183\]=2' /boot/dietpi/.installed && dpkg --compare-versions "$(dpkg-query -Wf '${Version}' vaultwarden 2> /dev/null)" lt 1.30.1-dietpi3
-		then
-			# Pre-v8.7 cleanup
-			if [[ -f '/opt/vaultwarden/target/release/vaultwarden' ]]
-			then
-				G_EXEC rm -R /opt/vaultwarden
-				[[ -f '/etc/systemd/system/vaultwarden.service' ]] && G_EXEC rm /etc/systemd/system/vaultwarden.service
-			fi
-			G_DIETPI-NOTIFY 2 'Updating vaultwarden package ...'
-			G_EXEC_OUTPUT=1 G_EXEC curl -fo package.deb "https://dietpi.com/downloads/binaries/$G_DISTRO_NAME/vaultwarden_$G_HW_ARCH_NAME.deb"
-			G_AGI ./package.deb
-			G_EXEC rm package.deb
-		fi
 	fi
 }
 
@@ -1560,6 +1508,36 @@ Patch_9_1()
 	then
 		G_DIETPI-NOTIFY 2 'Removing obsolete USBridge Sig driver update script, since Allo does not provides those for revent kernel versions anymore'
 		G_EXEC rm /etc/kernel/postinst.d/dietpi-USBridgeSig
+	fi
+
+	# Quartz64
+	if (( $G_HW_MODEL == 49 ))
+	then
+		for i in quartz64{a,b} soquartz
+		do
+			dpkg --compare-versions "$(dpkg-query -Wf '${Version}' "firmware-$i" 2> /dev/null)" lt-nl 6.7.4-dietpi1 || continue
+			G_DIETPI-NOTIFY 2 "Updating $i kernel and bootloader ..."
+			G_EXEC_OUTPUT=1 G_EXEC curl -fo package.deb "https://dietpi.com/downloads/binaries/firmware-$i.deb"
+			G_EXEC_OUTPUT=1 G_EXEC dpkg -i --force-confdef,confold package.deb
+			G_EXEC rm package.deb
+			break
+		done
+
+	# VisionFive 2
+	elif (( $G_HW_MODEL == 81 )) && dpkg --compare-versions "$(dpkg-query -Wf '${Version}' linux-image-visionfive2 2> /dev/null)" lt-nl 6.1.78-dietpi1
+	then
+		G_DIETPI-NOTIFY 2 'Updating RISC-V StarFive VisionFive 2 kernel ...'
+		G_EXEC_OUTPUT=1 G_EXEC curl -fo package.deb 'https://dietpi.com/downloads/binaries/linux-image-visionfive2.deb'
+		G_EXEC_OUTPUT=1 G_EXEC dpkg -i --force-confdef,confold package.deb
+		G_EXEC rm package.deb
+
+	# Star64
+	elif (( $G_HW_MODEL == 84 )) && dpkg --compare-versions "$(dpkg-query -Wf '${Version}' linux-image-star64 2> /dev/null)" lt-nl 6.1.78-dietpi1
+	then
+		G_DIETPI-NOTIFY 2 'Updating RISC-V PINE64 Star64 kernel ...'
+		G_EXEC_OUTPUT=1 G_EXEC curl -fo package.deb 'https://dietpi.com/downloads/binaries/linux-image-star64.deb'
+		G_EXEC_OUTPUT=1 G_EXEC dpkg -i --force-confdef,confold package.deb
+		G_EXEC rm package.deb
 	fi
 
 	# Software updates and migrations
@@ -1600,6 +1578,28 @@ map $arg_v $asset_immutable {
 		then
 			G_DIETPI-NOTIFY 2 'Updating Squeezelite package ...'
 			G_EXEC_OUTPUT=1 G_EXEC curl -fo package.deb "https://dietpi.com/downloads/binaries/$G_DISTRO_NAME/squeezelite_$G_HW_ARCH_NAME.deb"
+			G_AGI ./package.deb
+			G_EXEC rm package.deb
+		fi
+
+		# Amiberry
+		if grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[108\]=2' /boot/dietpi/.installed && dpkg --compare-versions "$(dpkg-query -Wf '${Version}' amiberry 2> /dev/null)" lt 5.6.6-dietpi1
+		then
+			G_DIETPI-NOTIFY 2 'Preparing Amiberry upgrade to v5.6.6, including migration for RPi systems from fake KMS DispmanX to full KMS SDL2 graphics backend'
+			echo 108 >> /var/tmp/dietpi/dietpi-update_reinstalls
+		fi
+
+		# vaultwarden
+		if grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[183\]=2' /boot/dietpi/.installed && dpkg --compare-versions "$(dpkg-query -Wf '${Version}' vaultwarden 2> /dev/null)" lt 1.30.3-dietpi2
+		then
+			# Pre-v8.7 cleanup
+			if [[ -f '/opt/vaultwarden/target/release/vaultwarden' ]]
+			then
+				G_EXEC rm -R /opt/vaultwarden
+				[[ -f '/etc/systemd/system/vaultwarden.service' ]] && G_EXEC rm /etc/systemd/system/vaultwarden.service
+			fi
+			G_DIETPI-NOTIFY 2 'Updating vaultwarden package ...'
+			G_EXEC_OUTPUT=1 G_EXEC curl -fo package.deb "https://dietpi.com/downloads/binaries/$G_DISTRO_NAME/vaultwarden_$G_HW_ARCH_NAME.deb"
 			G_AGI ./package.deb
 			G_EXEC rm package.deb
 		fi
