v7.2 (#4388)
+ DietPi-Patches | Apply patches based on current version and store intermediate versions reached, now that the amount of patches is high and they start to conflict (ID 67 removed but now re-assigned for Firefox)
+ DietPi-Patches | LibSSL1.0.0: Remove obsolete install flag

diff --git a/.update/patches b/.update/patches
--- a/.update/patches
+++ b/.update/patches
@@ -31,46 +31,52 @@ G_CHECK_ROOT_USER
 G_CHECK_ROOTFS_RW
 G_INIT
 
-# v7.0: Remove obsolete udev rule, as WiFi power saving is disabled via /etc/network/intefaces > "wireless-power off" > /etc/network/if-pre-up.d/wireless-tools (wireless-tools package) when the WiFi interface is configured.
-[[ -f '/etc/udev/rules.d/10-wifi-disable-powermanagement.rules' ]] && G_EXEC rm /etc/udev/rules.d/10-wifi-disable-powermanagement.rules
+# Version-based incremental patches
+Patch_7_0()
+{
+	# Remove obsolete udev rule, as WiFi power saving is disabled via /etc/network/intefaces > "wireless-power off" > /etc/network/if-pre-up.d/wireless-tools (wireless-tools package) when the WiFi interface is configured.
+	[[ -f '/etc/udev/rules.d/10-wifi-disable-powermanagement.rules' ]] && G_EXEC rm /etc/udev/rules.d/10-wifi-disable-powermanagement.rules
+}
 
-# v7.1: Migrate from DietPi-NordVPN to DietPi-VPN
-[[ -f '/boot/dietpi/misc/dietpi-nordvpn' ]] && G_EXEC rm /boot/dietpi/misc/dietpi-nordvpn
-[[ -d '/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn' ]] && G_EXEC mv /var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn /var/lib/dietpi/dietpi-vpn
-if [[ -f '/var/lib/dietpi/dietpi-vpn/settings_dietpi.conf' ]]
-then
-	G_EXEC sed -Ei 's/^NORDVPN_(SERVER|USERNAME|PASSWORD)=/VPN_\1=/' /var/lib/dietpi/dietpi-vpn/settings_dietpi.conf
-	. /var/lib/dietpi/dietpi-vpn/settings_dietpi.conf
-	[[ -f '/etc/openvpn/client.ovpn' ]] || G_EXEC cp -a "/etc/openvpn/ovpn_$PROTOCOL/$VPN_SERVER" /etc/openvpn/client.ovpn
-	unset -v VPN_SERVER PROTOCOL VPN_USERNAME VPN_PASSWORD
-	G_EXEC sed -i 's|/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/|/var/lib/dietpi/dietpi-vpn/|' /etc/openvpn/client.ovpn
-fi
-if [[ -f '/etc/systemd/system/dietpi-nordvpn.service' ]]
-then
-	systemctl -q is-enabled dietpi-nordvpn && G_EXEC systemctl enable dietpi-vpn
-	G_EXEC systemctl disable dietpi-nordvpn
-	G_EXEC rm /etc/systemd/system/dietpi-nordvpn.service
-fi
+Patch_7_1()
+{
+	# Migrate from DietPi-NordVPN to DietPi-VPN
+	[[ -f '/boot/dietpi/misc/dietpi-nordvpn' ]] && G_EXEC rm /boot/dietpi/misc/dietpi-nordvpn
+	[[ -d '/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn' ]] && G_EXEC mv /var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn /var/lib/dietpi/dietpi-vpn
+	if [[ -f '/var/lib/dietpi/dietpi-vpn/settings_dietpi.conf' ]]
+	then
+		G_EXEC sed -Ei 's/^NORDVPN_(SERVER|USERNAME|PASSWORD)=/VPN_\1=/' /var/lib/dietpi/dietpi-vpn/settings_dietpi.conf
+		. /var/lib/dietpi/dietpi-vpn/settings_dietpi.conf
+		[[ -f '/etc/openvpn/client.ovpn' ]] || G_EXEC cp -a "/etc/openvpn/ovpn_$PROTOCOL/$VPN_SERVER" /etc/openvpn/client.ovpn
+		unset -v VPN_SERVER PROTOCOL VPN_USERNAME VPN_PASSWORD
+		G_EXEC sed -i 's|/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/|/var/lib/dietpi/dietpi-vpn/|' /etc/openvpn/client.ovpn
+	fi
+	if [[ -f '/etc/systemd/system/dietpi-nordvpn.service' ]]
+	then
+		systemctl -q is-enabled dietpi-nordvpn && G_EXEC systemctl enable dietpi-vpn
+		G_EXEC systemctl disable dietpi-nordvpn
+		G_EXEC rm /etc/systemd/system/dietpi-nordvpn.service
+	fi
 
-# v7.1: MariaDB: Rename config file: https://github.com/MichaIng/DietPi/commit/c306d449a7c4ed86a1e9ff7c4914d9e1c2afd11a
-[[ -f '/etc/mysql/mariadb.conf.d/99-dietpi-4byte.cnf' ]] && G_EXEC mv /etc/mysql/mariadb.conf.d/99-dietpi-4byte.cnf /etc/mysql/mariadb.conf.d/97-dietpi.cnf
+	# MariaDB: Rename config file: https://github.com/MichaIng/DietPi/commit/c306d449a7c4ed86a1e9ff7c4914d9e1c2afd11a
+	[[ -f '/etc/mysql/mariadb.conf.d/99-dietpi-4byte.cnf' ]] && G_EXEC mv /etc/mysql/mariadb.conf.d/99-dietpi-4byte.cnf /etc/mysql/mariadb.conf.d/97-dietpi.cnf
 
-# v7.1: RPi: Additionally blacklist the bcm2835_isp kernel module when the RPi camera feature is disabled: https://github.com/MichaIng/DietPi/issues/4203
-[[ -f '/etc/modprobe.d/dietpi-disable_rpi_camera.conf' ]] && ! grep -q 'bcm2835_isp' /etc/modprobe.d/dietpi-disable_rpi_camera.conf && echo 'blacklist bcm2835_isp' >> /etc/modprobe.d/dietpi-disable_rpi_camera.conf
+	# RPi: Additionally blacklist the bcm2835_isp kernel module when the RPi camera feature is disabled: https://github.com/MichaIng/DietPi/issues/4203
+	[[ -f '/etc/modprobe.d/dietpi-disable_rpi_camera.conf' ]] && ! grep -q 'bcm2835_isp' /etc/modprobe.d/dietpi-disable_rpi_camera.conf && echo 'blacklist bcm2835_isp' >> /etc/modprobe.d/dietpi-disable_rpi_camera.conf
 
-# v7.1: Mark now dedicated Go as installed if OpenBazaar is
-[[ -d '/usr/local/go' ]] && ! grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[188\]=2' /boot/dietpi/.installed && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[58\]=2' /boot/dietpi/.installed && G_CONFIG_INJECT 'aSOFTWARE_INSTALL_STATE\[188\]=' 'aSOFTWARE_INSTALL_STATE[188]=2' /boot/dietpi/.installed
+	# Mark now dedicated Go as installed if OpenBazaar is
+	[[ -d '/usr/local/go' ]] && ! grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[188\]=2' /boot/dietpi/.installed && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[58\]=2' /boot/dietpi/.installed && G_CONFIG_INJECT 'aSOFTWARE_INSTALL_STATE\[188\]=' 'aSOFTWARE_INSTALL_STATE[188]=2' /boot/dietpi/.installed
 
-# v7.1: Interactively inform user about possible No-IP => DietPi-DDNS migration
-[[ -f '/boot/dietpi/.installed' ]] && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[67\]=2' /boot/dietpi/.installed && G_WHIP_MSG '[ INFO ] No-IP client installation found
+	# Interactively inform user about possible No-IP => DietPi-DDNS migration
+	[[ -f '/boot/dietpi/.installed' ]] && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[67\]=2' /boot/dietpi/.installed && G_WHIP_MSG '[ INFO ] No-IP client installation found
 \nThe No-IP client install option has been replaced by our new DietPi-DDNS tool. The No-IP client remains functional on your system but we recommend a migration to our new tool.
 \nSimply run "dietpi-ddns" from console, select "No-IP" as provider, enter domain and credentials, then select "Apply". The old No-IP client and service will be removed automatically as last step, once a final DDNS update test succeeded.'
 
-# v7.1: Remove obsolete DietPi-NordVPN and No-IP install states
-[[ -f '/boot/dietpi/.installed' ]] && grep -qE '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[(67|171)\]=' /boot/dietpi/.installed && G_EXEC sed -Ei '/^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[(67|171)\]=/d' /boot/dietpi/.installed
+	# Remove obsolete DietPi-NordVPN and No-IP install states
+	[[ -f '/boot/dietpi/.installed' ]] && grep -qE '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[(67|171)\]=' /boot/dietpi/.installed && G_EXEC sed -Ei '/^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[(67|171)\]=/d' /boot/dietpi/.installed
 
-# v7.1: Inform user about possible Sonarr v2 => v3 upgrade
-[[ -f '/mnt/dietpi_userdata/sonarr/nzbdrone.pid' ]] && G_WHIP_MSG '[ INFO ] Sonarr v3 has been released
+	# Inform user about possible Sonarr v2 => v3 upgrade
+	[[ -f '/mnt/dietpi_userdata/sonarr/nzbdrone.pid' ]] && G_WHIP_MSG '[ INFO ] Sonarr v3 has been released
 \nYou seem to use Sonarr v2 while Sonarr v3 is now available. A migration is safe to do, but in some cases you might need to redo some configuration, so we do not force the upgrade now.
 \nTo migrate to Sonarr v3, run the following command from console:
  - dietpi-software reinstall 144
@@ -78,64 +84,97 @@ fi
  - Run "dietpi-arr_to_ram 2" once manually, which updates your database backup but also creates a new script.
  - Use that script /mnt/dietpi_userdata/sonarr/dietpi-arr_to_ram.sh without arguments to update your database backup via "Custom Scripts". This is required as Sonarr v3 does not allow arguments for custom scripts and does not allow to call scripts from within the /boot directory.'
 
-# v7.1: Removing obsolete DietPi-Arr_to_RAM backup files
-rm -f /mnt/dietpi_userdata/{{sonarr,radarr}/nzbdrone.db-{shm,wal},lidarr/lidarr.db-{shm,wal}}.bak
+	# Removing obsolete DietPi-Arr_to_RAM backup files
+	rm -f /mnt/dietpi_userdata/{{sonarr,radarr}/nzbdrone.db-{shm,wal},lidarr/lidarr.db-{shm,wal}}.bak
 
-# v7.1: On 64-bit RPi systems, remove the obsolete foreign architecture armhf
-[[ $G_HW_MODEL -le 9 && $G_HW_ARCH == 3 && $(dpkg --print-architecture) == 'arm64' ]] && ! dpkg-query -l '*:armhf' &> /dev/null && G_EXEC dpkg --remove-architecture 'armhf'
+	# On 64-bit RPi systems, remove the obsolete foreign architecture armhf
+	[[ $G_HW_MODEL -le 9 && $G_HW_ARCH == 3 && $(dpkg --print-architecture) == 'arm64' ]] && ! dpkg-query -l '*:armhf' &> /dev/null && G_EXEC dpkg --remove-architecture 'armhf'
 
-# v7.1: Plex Media Server: Fix secure remote access via app.plex.tv did not work if Unbound with DNS rebinding protection is installed: https://dietpi.com/phpbb/viewtopic.php?t=8896
-[[ -f '/boot/dietpi/.installed' ]] && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[42\]=2' /boot/dietpi/.installed && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[182\]=2' /boot/dietpi/.installed && echo -e 'server:\n\tprivate-domain: "plex.direct"' > /etc/unbound/unbound.conf.d/dietpi-plex.conf
+	# Plex Media Server: Fix secure remote access via app.plex.tv did not work if Unbound with DNS rebinding protection is installed: https://dietpi.com/phpbb/viewtopic.php?t=8896
+	[[ -f '/boot/dietpi/.installed' ]] && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[42\]=2' /boot/dietpi/.installed && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[182\]=2' /boot/dietpi/.installed && echo -e 'server:\n\tprivate-domain: "plex.direct"' > /etc/unbound/unbound.conf.d/dietpi-plex.conf
+}
 
-# v7.2: Odroid XU4 does not support rng-tools: https://github.com/MichaIng/DietPi/issues/4318
-if [[ $G_HW_MODEL == 11 ]]
-then
-	dpkg-query -s rng-tools5 &> /dev/null && G_AGP rng-tools5
-	dpkg-query -s haveged &> /dev/null || G_AGI haveged
-fi
-
-# v7.2: Move raspimjpeg executable to a common system path
-if [[ -f '/boot/dietpi/.installed' ]] && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[59\]=2' /boot/dietpi/.installed
-then
-	G_DIETPI-NOTIFY 2 'Moving raspimjpeg executable to a common system path'
-	[[ -f '/opt/vc/bin/raspimjpeg' ]] && G_EXEC mv /{opt/vc,usr/local}/bin/raspimjpeg
-	[[ -L '/usr/bin/raspimjpeg' ]] && G_EXEC rm /usr/bin/raspimjpeg
-fi
-
-# v7.2: Rename Bitwarden_RS into vaultwarden: https://github.com/MichaIng/DietPi/issues/4325
-if [[ -d '/mnt/dietpi_userdata/bitwarden_rs' ]]
-then
-	G_DIETPI-NOTIFY 2 'vaultwarden will be reinstalled now.'
-	# Remove Bitwarden_RS service
-	if [[ -f '/etc/systemd/system/bitwarden_rs.service' ]]
+Patch_7_2()
+{
+	# Odroid XU4 does not support rng-tools: https://github.com/MichaIng/DietPi/issues/4318
+	if [[ $G_HW_MODEL == 11 ]]
 	then
-		G_EXEC systemctl disable --now bitwarden_rs
-		G_EXEC rm /etc/systemd/system/bitwarden_rs.service
+		dpkg-query -s rng-tools5 &> /dev/null && G_AGP rng-tools5
+		dpkg-query -s haveged &> /dev/null || G_AGI haveged
 	fi
-	[[ -d '/etc/systemd/system/bitwarden_rs.service.d' ]] && G_EXEC rm -R /etc/systemd/system/bitwarden_rs.service.d
-	# Remove Bitwarden_RS user and group
-	getent passwd bitwarden_rs > /dev/null && G_EXEC userdel bitwarden_rs
-	getent group bitwarden_rs > /dev/null && G_EXEC groupdel bitwarden_rs
-	# Remove Bitwarden_RS install directory
-	[[ -d '/opt/bitwarden_rs' ]] && G_EXEC rm -R /opt/bitwarden_rs
-	# Update and rename Bitwarden_RS config file
-	if [[ -f '/mnt/dietpi_userdata/bitwarden_rs/bitwarden_rs.env' ]]
+
+	# Move raspimjpeg executable to a common system path
+	if [[ -f '/boot/dietpi/.installed' ]] && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[59\]=2' /boot/dietpi/.installed
 	then
-		G_CONFIG_INJECT 'DATA_FOLDER=' 'DATA_FOLDER=/mnt/dietpi_userdata/vaultwarden' /mnt/dietpi_userdata/bitwarden_rs/bitwarden_rs.env
-		G_EXEC mv /mnt/dietpi_userdata/bitwarden_rs/{bitwarden_rs,vaultwarden}.env
+		G_DIETPI-NOTIFY 2 'Moving raspimjpeg executable to a common system path'
+		[[ -f '/opt/vc/bin/raspimjpeg' ]] && G_EXEC mv /{opt/vc,usr/local}/bin/raspimjpeg
+		[[ -L '/usr/bin/raspimjpeg' ]] && G_EXEC rm /usr/bin/raspimjpeg
 	fi
-	G_EXEC mv /mnt/dietpi_userdata/{bitwarden_rs,vaultwarden}
-	# Start vaultwarden reinstallation
-	/boot/dietpi/dietpi-software reinstall 183 || G_WHIP_MSG '[WARNING] The vaultwarden (re)install failed.
+
+	# Rename Bitwarden_RS into vaultwarden: https://github.com/MichaIng/DietPi/issues/4325
+	if [[ -d '/mnt/dietpi_userdata/bitwarden_rs' ]]
+	then
+		G_DIETPI-NOTIFY 2 'vaultwarden will be reinstalled now.'
+		# Remove Bitwarden_RS service
+		if [[ -f '/etc/systemd/system/bitwarden_rs.service' ]]
+		then
+			G_EXEC systemctl disable --now bitwarden_rs
+			G_EXEC rm /etc/systemd/system/bitwarden_rs.service
+		fi
+		[[ -d '/etc/systemd/system/bitwarden_rs.service.d' ]] && G_EXEC rm -R /etc/systemd/system/bitwarden_rs.service.d
+		# Remove Bitwarden_RS user and group
+		getent passwd bitwarden_rs > /dev/null && G_EXEC userdel bitwarden_rs
+		getent group bitwarden_rs > /dev/null && G_EXEC groupdel bitwarden_rs
+		# Remove Bitwarden_RS install directory
+		[[ -d '/opt/bitwarden_rs' ]] && G_EXEC rm -R /opt/bitwarden_rs
+		# Update and rename Bitwarden_RS config file
+		if [[ -f '/mnt/dietpi_userdata/bitwarden_rs/bitwarden_rs.env' ]]
+		then
+			G_CONFIG_INJECT 'DATA_FOLDER=' 'DATA_FOLDER=/mnt/dietpi_userdata/vaultwarden' /mnt/dietpi_userdata/bitwarden_rs/bitwarden_rs.env
+			G_EXEC mv /mnt/dietpi_userdata/bitwarden_rs/{bitwarden_rs,vaultwarden}.env
+		fi
+		G_EXEC mv /mnt/dietpi_userdata/{bitwarden_rs,vaultwarden}
+		# Start vaultwarden reinstallation
+		/boot/dietpi/dietpi-software reinstall 183 || G_WHIP_MSG '[WARNING] The vaultwarden (re)install failed.
 \nHowever, all required dietpi-update migration steps have been done and it will hence finish.
 \nRepeat the reinstall manually to bring up your new vaultwarden instance, when you find time: "dietpi-software reinstall 183"'
+	fi
+
+	# Fix disabling dietpi-desktop_setup
+	[[ -f '/var/lib/dietpi/dietpi-software/installed/desktop/dietpi-desktop_setup.sh' ]] && grep -q 'echo -e' /var/lib/dietpi/dietpi-software/installed/desktop/dietpi-desktop_setup.sh && G_EXEC sed -i 's/echo -e/echo/' /var/lib/dietpi/dietpi-software/installed/desktop/dietpi-desktop_setup.sh
+	for i in /{root,home/*}/.config/autostart/dietpi-desktop_setup.desktop
+	do
+		[[ -f $i ]] && grep -q '^-e ' "$i" && G_EXEC sed -i 's/^-e //' "$i"
+	done
+
+	# Remove obsolete LibSSL1.0.0 install state
+	[[ -f '/boot/dietpi/.installed' ]] && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[126\]=' /boot/dietpi/.installed && G_EXEC sed -i '/^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[126\]=/d' /boot/dietpi/.installed
+}
+
+# v6.35 => v7 migration
+if (( $G_DIETPI_VERSION_CORE == 6 && $G_DIETPI_VERSION_SUB > 34 ))
+then
+	G_DIETPI_VERSION_CORE=7
+	G_DIETPI_VERSION_SUB=-1
+
+# Failsafe: Error out on invalid version
+elif ! (( $G_DIETPI_VERSION_CORE > 6 ))
+then
+	G_DIETPI-NOTIFY 1 "Unsupported DietPi version $G_DIETPI_VERSION_CORE.$G_DIETPI_VERSION_SUB.$G_DIETPI_VERSION_RC. Aborting..."
+	G_DIETPI-NOTIFY 2 'Please run "dietpi-update" to repeat the regular update path.'
+	exit 1
 fi
 
-# v7.2: Fix disabling dietpi-desktop_setup
-[[ -f '/var/lib/dietpi/dietpi-software/installed/desktop/dietpi-desktop_setup.sh' ]] && grep -q 'echo -e' /var/lib/dietpi/dietpi-software/installed/desktop/dietpi-desktop_setup.sh && G_EXEC sed -i 's/echo -e/echo/' /var/lib/dietpi/dietpi-software/installed/desktop/dietpi-desktop_setup.sh
-for i in /{root,home/*}/.config/autostart/dietpi-desktop_setup.desktop
+# Main loop
+while :
 do
-	[[ -f $i ]] && grep -q '^-e ' "$i" && G_EXEC sed -i 's/^-e //' "$i"
+	((G_DIETPI_VERSION_SUB++))
+	G_DIETPI_VERSION_RC=0
+	declare -F "Patch_${G_DIETPI_VERSION_CORE}_$G_DIETPI_VERSION_SUB" > /dev/null || break
+	G_DIETPI-NOTIFY 2 "Patching to DietPi v$G_DIETPI_VERSION_CORE.$G_DIETPI_VERSION_SUB..."
+	"Patch_${G_DIETPI_VERSION_CORE}_$G_DIETPI_VERSION_SUB"
+	G_VERSIONDB_SAVE
+	G_DIETPI-NOTIFY 0 "Patched to DietPi v$G_DIETPI_VERSION_CORE.$G_DIETPI_VERSION_SUB"
 done
 
 exit 0
