dietpi-patches: move migrations forward
and make RK3588 legacy => vendor migration mandatory

diff --git a/.update/patches b/.update/patches
--- a/.update/patches
+++ b/.update/patches
@@ -2356,6 +2356,102 @@ sudo sysctl -p /etc/sysctl.d/dietpi-syncthing.confs
 			G_EXEC_NOFAIL=1 G_EXEC phpenmod dietpi
 		fi
 	fi
+}
+
+Patch_9_17()
+{
+	# ZeroPi
+	if (( $G_HW_MODEL == 59 )) && [[ -f '/boot/dietpiEnv.txt' ]]
+	then
+		G_DIETPI-NOTIFY 2 'Removing device tree overlays for unwired USB controllers on ZeroPi'
+		G_EXEC sed --follow-symlinks -i '/^[[:blank:]]*overlays=/s/usbhost1[[:blank:]]*//' /boot/dietpiEnv.txt
+		G_EXEC sed --follow-symlinks -i '/^[[:blank:]]*overlays=/s/usbhost2[[:blank:]]*//' /boot/dietpiEnv.txt
+	fi
+
+	if [[ -f '/etc/apt/trusted.gpg.d/raspbian-archive-keyring.gpg.dpkg-new' ]]
+	then
+		G_DIETPI-NOTIFY 2 'Replace obsolete Raspbian key symlink with real key shipped since Trixie'
+		G_EXEC rm /etc/apt/trusted.gpg.d/raspbian-archive-keyring.gpg
+		G_EXEC mv /etc/apt/trusted.gpg.d/raspbian-archive-keyring.gpg{.dpkg-new,}
+	fi
+
+	# Software updates, migrations and patches
+	if [[ -f '/boot/dietpi/.installed' ]]
+	then
+		# Raspotify: Remove obsolete systemd unit fixes to prevent an endless failure loop on shutdown: https://github.com/dtcooper/raspotify/pull/735
+		[[ -f '/etc/systemd/system/raspotify-crash-report-generator.service.d/dietpi.conf' ]] && G_EXEC rm /etc/systemd/system/raspotify-crash-report-generator.service.d/dietpi.conf
+		[[ -d '/etc/systemd/system/raspotify-crash-report-generator.service.d' ]] && G_EXEC rmdir --ignore-fail-on-non-empty /etc/systemd/system/raspotify-crash-report-generator.service.d
+		[[ -f '/etc/systemd/system/raspotify.service.d/dietpi.conf' ]] && G_EXEC rm /etc/systemd/system/raspotify.service.d/dietpi.conf
+		[[ -d '/etc/systemd/system/raspotify.service.d' ]] && G_EXEC rmdir --ignore-fail-on-non-empty /etc/systemd/system/raspotify.service.d
+
+		# NZBGet
+		if [[ -f '/mnt/dietpi_userdata/nzbget/nzbget.conf' ]] && grep -q '^Server1.Cipher=RC4-MD5$' /mnt/dietpi_userdata/nzbget/nzbget.conf
+		then
+			G_DIETPI-NOTIFY 2 'Removing insecure and widely unsupported cipher suite from NZBGet config'
+			G_EXEC sed --follow-symlinks -i '/^Server1.Cipher=RC4-MD5$/c\Server1.Cipher=' /mnt/dietpi_userdata/nzbget/nzbget.conf
+		fi
+
+		# ProFTPD
+		if [[ -f '/etc/proftpd/proftpd.conf' ]] && grep -q '^[[:blank:]]*MultilineRFC2228[[:blank:]]' /etc/proftpd/proftpd.conf
+		then
+			G_DIETPI-NOTIFY 2 'Removing deprecated setting from ProFTPD config'
+			G_EXEC sed --follow-symlinks -i '/^[[:blank:]]*MultilineRFC2228[[:blank:]]/d' /etc/proftpd/proftpd.conf
+		fi
+
+		# Pi-hole v6 migration
+		# - /etc/pihole/pihole.toml indicates that Pi-hole has been upgraded to v6 already.
+		# - The /var/www/pihole symlink indicates that an instance installed via dietpi-software has not been migrated yet.
+		if [[ -f '/etc/pihole/pihole.toml' && -L '/var/www/pihole' ]] && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[93\]=2' /boot/dietpi/.installed
+		then
+			# Remove DietPi specific v5 files
+			# - Symlinks
+			G_EXEC rm /var/www/pihole
+			[[ -L '/var/www/admin' ]] && G_EXEC rm /var/www/admin
+			# - Webserver configs
+			[[ -d '/etc/apache2/sites-available' ]] && G_EXEC rm -f /etc/apache2/sites-{available,enabled}/dietpi-pihole*
+			[[ -d '/etc/lighttpd/conf-available' ]] && G_EXEC rm -f /etc/lighttpd/conf-{available,enabled}/99-dietpi-pihole*
+			[[ -d '/etc/nginx/sites-dietpi' ]] && G_EXEC rm -f /etc/nginx/sites-dietpi/dietpi-pihole*
+
+			# Remove www-data user from pihole group
+			getent group pihole | grep -Eq '(:|,)www-data(,|$)' && G_EXEC gpasswd -d www-data pihole
+
+			# Change web UI port to 8089 and 8489 (HTTPS) to avoid conflict with webservers and other web applications
+			G_EXEC pihole-FTL --config webserver.port 8089,8489s
+
+			# Inform user about differences to stock Pi-hole installation
+			G_WHIP_MSG "[ INFO ] Pi-hole network ports changed to 8089 and 8489
+\nTo align migrated Pi-hole v6 instances with fresh installs, and avoid possible conflicts with dedicated webservers, the network ports have been changed to 8089 and 8489 (HTTPS). Your Pi-hole instance will hence be available at:
+- http://$(G_GET_NET ip):8089/admin/
+- https://$(G_GET_NET ip):8489/admin/
+\nThis can be changed via web UI or following console command, e.g. for ports 80 and 443 (HTTPS):
+- pihole-FTL --config webserver.port 80,443s"
+
+			# Offer to uninstall webserver and PHP if no dependant is installed
+			# - If only PHP or only a webserver is installed, one has been uninstalled already, and the other is assumed to be still needed for something else.
+			if grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[89\]=2' /boot/dietpi/.installed && grep -Eq '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[(83|84|85)\]=2' /boot/dietpi/.installed
+			then
+				G_WHIP_CHECKLIST_ARRAY=()
+				# - webserver
+				if ! /boot/dietpi/dietpi-software list | grep -q '| =2 |.*+webserver'
+				then
+					grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[83\]=2' /boot/dietpi/.installed && G_WHIP_CHECKLIST_ARRAY+=(83 'Apache webserver' off)
+					grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[84\]=2' /boot/dietpi/.installed && G_WHIP_CHECKLIST_ARRAY+=(84 'Lighttpd webserver' off)
+					grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[85\]=2' /boot/dietpi/.installed && G_WHIP_CHECKLIST_ARRAY+=(85 'Nginx webserver' off)
+				fi
+				# - PHP: Exclude webserver stacks which are meta selections only
+				/boot/dietpi/dietpi-software list | grep '| =2 |.*+PHP' | grep -vEq '^.\[32mID (75|76|78|79|81|82)' || G_WHIP_CHECKLIST_ARRAY+=(89 'PHP server' off)
+				if (( ${#G_WHIP_CHECKLIST_ARRAY[@]} ))
+				then
+					G_WHIP_BUTTON_CANCEL_TEXT='Skip'
+					# shellcheck disable=SC2086
+					G_WHIP_CHECKLIST '[ INFO ] Possibly obsolete webserver and/or PHP installation detected
+\nYou recently updated Pi-hole to v6, which now does not require any webserver or PHP anymore.
+\nWe detected a webserver and/or PHP installation on your system, but no dependant among installed dietpi-software options.
+\nIf you are sure that you do not require the webserver and/or PHP anymore, you can select them for uninstall below. Use the space bar to (de)select the ones which shall be uninstalled:' && /boot/dietpi/dietpi-software uninstall $G_WHIP_RETURNED_VALUE
+				fi
+			fi
+		fi
+	fi
 
 	# RPi firmware migration: Do after all other patches
 	if (( $G_HW_MODEL < 10 && $G_DISTRO > 6 )) && ! dpkg-query -s 'raspi-firmware' &> /dev/null
@@ -2369,42 +2465,37 @@ sudo sysctl -p /etc/sysctl.d/dietpi-syncthing.confs
 \nThis can be done any time later via dietpi-config > Advanced Options > RPi firmware migration.' && /boot/dietpi/func/dietpi-set_software rpi_firmware_migration
 
 	# RK3588 migration to vendor kernel
-	elif (( $G_HW_CPUID == 11 )) && dpkg-query -s 'linux-image-legacy-rk35xx' &> /dev/null && ! dpkg-query -s 'linux-image-vendor-rk35xx' &> /dev/null
+	elif (( $G_HW_CPUID == 11 )) && dpkg-query -s 'linux-image-legacy-rk35xx' &> /dev/null && ! dpkg-query -s 'linux-image-vendor-rk35xx' &> /dev/null && ! dpkg-query -s 'linux-image-current-rockchip64' &> /dev/null && ! dpkg-query -s 'linux-image-edge-rockchip64' &> /dev/null
 	then
-		if G_WHIP_DEFAULT_ITEM='yes' G_WHIP_YESNO '[ INFO ] Major kernel upgrade to Linux 6.1 available
-\nFor RK3588 SoC SBCs, we offer a major kernel upgrade to Linux 6.1, based on a new Rockchip kernel source which should provide not only new kernel features, but higher quality as well, compared to the old Rockchip Linux 5.10 legacy kernel.
-\nHowever, while we are not aware of any left issues, it is still good to have a backup in place, and we do not enforce the upgrade. You can do it any time later.
-\nDo you want to migrate to the new Linux 6.1 kernel now?'
-		then
-			G_AGI linux-{image,dtb}-vendor-rk35xx
-			dpkg-query -s 'linux-headers-legacy-rk35xx' &> /dev/null && G_AGI linux-headers-vendor-rk35xx
-			dpkg-query -s 'linux-libc-dev-legacy-rk35xx' &> /dev/null && G_AGI linux-libc-dev-vendor-rk35xx
-			G_AGP linux-{image,dtb,headers,libc-dev}-legacy-rk35xx
-			# The /boot/dtb symlink has been found to be missing after kernel removed, despite a newer kernel being installed already. Assure it is present and correct.
-			[[ $(realpath '/boot/dtb') == '/boot/dtb-6.1.'* ]] || G_EXEC ln -sf /boot/dtb-6.1.* /boot/dtb
-			# Migrate U-Boot as well
-			case $G_HW_MODEL in
-				78) G_AGI linux-u-boot-rock-5b-vendor;;
-				79)
-					if dpkg-query -s 'linux-u-boot-nanopi-r6s-legacy' &> /dev/null
-					then
-						G_AGI linux-u-boot-nanopi-r6s-vendor
+		G_DIETPI-NOTIFY 2 'Migrating from Linux 5.10 legacy kernel to Linux 6.1 vendor kernel'
+		G_AGI linux-{image,dtb}-vendor-rk35xx
+		dpkg-query -s 'linux-headers-legacy-rk35xx' &> /dev/null && G_AGI linux-headers-vendor-rk35xx
+		dpkg-query -s 'linux-libc-dev-legacy-rk35xx' &> /dev/null && G_AGI linux-libc-dev-vendor-rk35xx
+		G_AGP linux-{image,dtb,headers,libc-dev}-legacy-rk35xx
+		# The /boot/dtb symlink has been found to be missing after kernel removed, despite a newer kernel being installed already. Assure it is present and correct.
+		[[ $(realpath '/boot/dtb') == '/boot/dtb-6.1.'* ]] || G_EXEC ln -sf /boot/dtb-6.1.* /boot/dtb
+		# Migrate U-Boot as well
+		case $G_HW_MODEL in
+			78) G_AGI linux-u-boot-rock-5b-vendor;;
+			79)
+				if dpkg-query -s 'linux-u-boot-nanopi-r6s-legacy' &> /dev/null
+				then
+					G_AGI linux-u-boot-nanopi-r6s-vendor
 
-					elif dpkg-query -s 'linux-u-boot-nanopi-r6c-legacy' &> /dev/null
-					then
-						G_AGI linux-u-boot-nanopi-r6c-vendor
+				elif dpkg-query -s 'linux-u-boot-nanopi-r6c-legacy' &> /dev/null
+				then
+					G_AGI linux-u-boot-nanopi-r6c-vendor
 
-					elif dpkg-query -s 'linux-u-boot-nanopct6-legacy' &> /dev/null
-					then
-						G_AGI linux-u-boot-nanopct6-vendor
-					fi
-				;;
-				80) G_AGI linux-u-boot-orangepi5-vendor;;
-				82) G_AGI linux-u-boot-orangepi5-plus-vendor;;
-				85) G_AGI linux-u-boot-rock-5a-vendor;;
-				*) :;;
-			esac
-		fi
+				elif dpkg-query -s 'linux-u-boot-nanopct6-legacy' &> /dev/null
+				then
+					G_AGI linux-u-boot-nanopct6-vendor
+				fi
+			;;
+			80) G_AGI linux-u-boot-orangepi5-vendor;;
+			82) G_AGI linux-u-boot-orangepi5-plus-vendor;;
+			85) G_AGI linux-u-boot-rock-5a-vendor;;
+			*) :;;
+		esac
 
 	# NanoPi R5S/R5C migration from legacy image with 8 partitions to Armbian-based kernel and bootloader
 	elif (( $G_HW_MODEL == 76 )) && dpkg-query -s 'firmware-nanopi5' &> /dev/null
@@ -2588,102 +2679,6 @@ SUBSYSTEM=="leds", KERNEL=="wan_led", ACTION=="add", ATTR{trigger}="netdev", ATT
 SUBSYSTEM=="leds", KERNEL=="lan1_led", ACTION=="add", ATTR{trigger}="netdev", ATTR{device_name}="eth1", ATTR{link}="1", ATTR{rx}="1", ATTR{tx}="1", RUN+="/bin/ip l s eth1 up", RUN+="/bin/ip l s eth1 down"
 SUBSYSTEM=="leds", KERNEL=="user_led", ACTION=="add", ATTR{trigger}="netdev", ATTR{device_name}="wlan0", ATTR{link}="1", ATTR{rx}="1", ATTR{tx}="1", RUN+="/bin/ip l s wlan0 up", RUN+="/bin/ip l s wlan0 down"
 _EOF_
-			fi
-		fi
-	fi
-}
-
-Patch_9_17()
-{
-	# ZeroPi
-	if (( $G_HW_MODEL == 59 )) && [[ -f '/boot/dietpiEnv.txt' ]]
-	then
-		G_DIETPI-NOTIFY 2 'Removing device tree overlays for unwired USB controllers on ZeroPi'
-		G_EXEC sed --follow-symlinks -i '/^[[:blank:]]*overlays=/s/usbhost1[[:blank:]]*//' /boot/dietpiEnv.txt
-		G_EXEC sed --follow-symlinks -i '/^[[:blank:]]*overlays=/s/usbhost2[[:blank:]]*//' /boot/dietpiEnv.txt
-	fi
-
-	if [[ -f '/etc/apt/trusted.gpg.d/raspbian-archive-keyring.gpg.dpkg-new' ]]
-	then
-		G_DIETPI-NOTIFY 2 'Replace obsolete Raspbian key symlink with real key shipped since Trixie'
-		G_EXEC rm /etc/apt/trusted.gpg.d/raspbian-archive-keyring.gpg
-		G_EXEC mv /etc/apt/trusted.gpg.d/raspbian-archive-keyring.gpg{.dpkg-new,}
-	fi
-
-	# Software updates, migrations and patches
-	if [[ -f '/boot/dietpi/.installed' ]]
-	then
-		# Raspotify: Remove obsolete systemd unit fixes to prevent an endless failure loop on shutdown: https://github.com/dtcooper/raspotify/pull/735
-		[[ -f '/etc/systemd/system/raspotify-crash-report-generator.service.d/dietpi.conf' ]] && G_EXEC rm /etc/systemd/system/raspotify-crash-report-generator.service.d/dietpi.conf
-		[[ -d '/etc/systemd/system/raspotify-crash-report-generator.service.d' ]] && G_EXEC rmdir --ignore-fail-on-non-empty /etc/systemd/system/raspotify-crash-report-generator.service.d
-		[[ -f '/etc/systemd/system/raspotify.service.d/dietpi.conf' ]] && G_EXEC rm /etc/systemd/system/raspotify.service.d/dietpi.conf
-		[[ -d '/etc/systemd/system/raspotify.service.d' ]] && G_EXEC rmdir --ignore-fail-on-non-empty /etc/systemd/system/raspotify.service.d
-
-		# NZBGet
-		if [[ -f '/mnt/dietpi_userdata/nzbget/nzbget.conf' ]] && grep -q '^Server1.Cipher=RC4-MD5$' /mnt/dietpi_userdata/nzbget/nzbget.conf
-		then
-			G_DIETPI-NOTIFY 2 'Removing insecure and widely unsupported cipher suite from NZBGet config'
-			G_EXEC sed --follow-symlinks -i '/^Server1.Cipher=RC4-MD5$/c\Server1.Cipher=' /mnt/dietpi_userdata/nzbget/nzbget.conf
-		fi
-
-		# ProFTPD
-		if [[ -f '/etc/proftpd/proftpd.conf' ]] && grep -q '^[[:blank:]]*MultilineRFC2228[[:blank:]]' /etc/proftpd/proftpd.conf
-		then
-			G_DIETPI-NOTIFY 2 'Removing deprecated setting from ProFTPD config'
-			G_EXEC sed --follow-symlinks -i '/^[[:blank:]]*MultilineRFC2228[[:blank:]]/d' /etc/proftpd/proftpd.conf
-		fi
-
-		# Pi-hole v6 migration
-		# - /etc/pihole/pihole.toml indicates that Pi-hole has been upgraded to v6 already.
-		# - The /var/www/pihole symlink indicates that an instance installed via dietpi-software has not been migrated yet.
-		if [[ -f '/etc/pihole/pihole.toml' && -L '/var/www/pihole' ]] && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[93\]=2' /boot/dietpi/.installed
-		then
-			# Remove DietPi specific v5 files
-			# - Symlinks
-			G_EXEC rm /var/www/pihole
-			[[ -L '/var/www/admin' ]] && G_EXEC rm /var/www/admin
-			# - Webserver configs
-			[[ -d '/etc/apache2/sites-available' ]] && G_EXEC rm -f /etc/apache2/sites-{available,enabled}/dietpi-pihole*
-			[[ -d '/etc/lighttpd/conf-available' ]] && G_EXEC rm -f /etc/lighttpd/conf-{available,enabled}/99-dietpi-pihole*
-			[[ -d '/etc/nginx/sites-dietpi' ]] && G_EXEC rm -f /etc/nginx/sites-dietpi/dietpi-pihole*
-
-			# Remove www-data user from pihole group
-			getent group pihole | grep -Eq '(:|,)www-data(,|$)' && G_EXEC gpasswd -d www-data pihole
-
-			# Change web UI port to 8089 and 8489 (HTTPS) to avoid conflict with webservers and other web applications
-			G_EXEC pihole-FTL --config webserver.port 8089,8489s
-
-			# Inform user about differences to stock Pi-hole installation
-			G_WHIP_MSG "[ INFO ] Pi-hole network ports changed to 8089 and 8489
-\nTo align migrated Pi-hole v6 instances with fresh installs, and avoid possible conflicts with dedicated webservers, the network ports have been changed to 8089 and 8489 (HTTPS). Your Pi-hole instance will hence be available at:
-- http://$(G_GET_NET ip):8089/admin/
-- https://$(G_GET_NET ip):8489/admin/
-\nThis can be changed via web UI or following console command, e.g. for ports 80 and 443 (HTTPS):
-- pihole-FTL --config webserver.port 80,443s"
-
-			# Offer to uninstall webserver and PHP if no dependant is installed
-			# - If only PHP or only a webserver is installed, one has been uninstalled already, and the other is assumed to be still needed for something else.
-			if grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[89\]=2' /boot/dietpi/.installed && grep -Eq '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[(83|84|85)\]=2' /boot/dietpi/.installed
-			then
-				G_WHIP_CHECKLIST_ARRAY=()
-				# - webserver
-				if ! /boot/dietpi/dietpi-software list | grep -q '| =2 |.*+webserver'
-				then
-					grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[83\]=2' /boot/dietpi/.installed && G_WHIP_CHECKLIST_ARRAY+=(83 'Apache webserver' off)
-					grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[84\]=2' /boot/dietpi/.installed && G_WHIP_CHECKLIST_ARRAY+=(84 'Lighttpd webserver' off)
-					grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[85\]=2' /boot/dietpi/.installed && G_WHIP_CHECKLIST_ARRAY+=(85 'Nginx webserver' off)
-				fi
-				# - PHP: Exclude webserver stacks which are meta selections only
-				/boot/dietpi/dietpi-software list | grep '| =2 |.*+PHP' | grep -vEq '^.\[32mID (75|76|78|79|81|82)' || G_WHIP_CHECKLIST_ARRAY+=(89 'PHP server' off)
-				if (( ${#G_WHIP_CHECKLIST_ARRAY[@]} ))
-				then
-					G_WHIP_BUTTON_CANCEL_TEXT='Skip'
-					# shellcheck disable=SC2086
-					G_WHIP_CHECKLIST '[ INFO ] Possibly obsolete webserver and/or PHP installation detected
-\nYou recently updated Pi-hole to v6, which now does not require any webserver or PHP anymore.
-\nWe detected a webserver and/or PHP installation on your system, but no dependant among installed dietpi-software options.
-\nIf you are sure that you do not require the webserver and/or PHP anymore, you can select them for uninstall below. Use the space bar to (de)select the ones which shall be uninstalled:' && /boot/dietpi/dietpi-software uninstall $G_WHIP_RETURNED_VALUE
-				fi
 			fi
 		fi
 	fi
