v7.6
+ DietPi-Patches | Put v6 => v7 migration code into better visible place

diff --git a/.update/patches b/.update/patches
--- a/.update/patches
+++ b/.update/patches
@@ -191,20 +191,6 @@ Patch_7_2()
 	fi
 }
 
-# v6.35 => v7 migration
-if (( $G_DIETPI_VERSION_CORE == 6 && $G_DIETPI_VERSION_SUB > 34 ))
-then
-	G_DIETPI_VERSION_CORE=7
-	G_DIETPI_VERSION_SUB=-1
-
-# Failsafe: Error out on invalid version
-elif ! (( $G_DIETPI_VERSION_CORE > 6 ))
-then
-	G_DIETPI-NOTIFY 1 "Unsupported DietPi version $G_DIETPI_VERSION_CORE.$G_DIETPI_VERSION_SUB.$G_DIETPI_VERSION_RC. Aborting..."
-	G_DIETPI-NOTIFY 2 'Please run "dietpi-update" to repeat the regular update path.'
-	exit 1
-fi
-
 Patch_7_3()
 {
 	# If the user did not remove the "dietpi" sodoers manually, update it to allow "sudo -u <user> -g <group>" with all target users and groups.
@@ -328,6 +314,20 @@ Patch_7_6()
 		G_EXEC sed -Ei 's/[[:blank:]]*elevator=[^[:blank:]]*//' /boot/cmdline.txt
 	fi
 }
+
+# v6.35 => v7 migration
+if (( $G_DIETPI_VERSION_CORE == 6 && $G_DIETPI_VERSION_SUB > 34 ))
+then
+	G_DIETPI_VERSION_CORE=7
+	G_DIETPI_VERSION_SUB=-1
+
+# Failsafe: Error out on invalid version
+elif ! (( $G_DIETPI_VERSION_CORE > 6 ))
+then
+	G_DIETPI-NOTIFY 1 "Unsupported DietPi version $G_DIETPI_VERSION_CORE.$G_DIETPI_VERSION_SUB.$G_DIETPI_VERSION_RC. Aborting..."
+	G_DIETPI-NOTIFY 2 'Please run "dietpi-update" to repeat the regular update path.'
+	exit 1
+fi
 
 # Main loop
 while :
