v7.6
+ DietPi-Pre-patches | Skip suite change patch on Buster+, since it throws a notice only (both "apt update" and "apt-get update") and does not require any interactive confirmation. Due to lack of test options, we leave it in place for Stretch systems.

diff --git a/.update/pre-patches b/.update/pre-patches
--- a/.update/pre-patches
+++ b/.update/pre-patches
@@ -73,20 +73,11 @@ Package: linux-image-* linux-headers-* linux-dtb-* linux-u-boot-* armbian-firmwa
 \nPackage: *\nPin: origin apt.armbian.com\nPin-Priority: -1' > /etc/apt/preferences.d/dietpi-armbian"
 fi
 
-# v7.4: Update APT repositories once, accepting the suite change, when Bullseye has been released, as pre-v7.4 G_AGUP does not include this yet.
-if (( $G_DIETPI_VERSION_CORE < 7 || ( $G_DIETPI_VERSION_CORE == 7 && $G_DIETPI_VERSION_SUB < 4 ) )) && curl -sSfL 'https://deb.debian.org/debian/dists/bullseye/Release' | grep -q '^Suite: stable$'
+# v7.4: On Stretch, allow interactive suite change once, to assure the update does not hang or fail on G_AGUP. From Buster on, the suite change throws a notice only and does not require any confirmation.
+if (( $G_DISTRO < 5 )) && (( $G_DIETPI_VERSION_CORE < 7 || ( $G_DIETPI_VERSION_CORE == 7 && $G_DIETPI_VERSION_SUB < 4 ) )) && curl -sSfL 'https://deb.debian.org/debian/dists/bullseye/Release' | grep -q '^Suite: stable$'
 then
-	if (( $G_DISTRO > 4 ))
-	then
-		G_DIETPI-NOTIFY 2 'Debian Bullseye has been released, so we accept the repository suite change once.'
-		G_EXEC apt-get --allow-releaseinfo-change-suite -q update
-
-	# On Stretch that option is not supported yet. If it's an interactive call, allow to accept it manually:
-	elif [[ $G_INTERACTIVE == 1 ]]
-	then
-		G_DIETPI-NOTIFY 2 'Debian Bullseye has been released, so you need to accept the repository suite change once.'
-		apt-get update
-	fi	
+	G_DIETPI-NOTIFY 2 'Debian Bullseye has been released, so you need to accept the Stretch suite change from "oldstable" to "oldoldstable" once.'
+	apt-get update	
 fi
 
 # v7.4
