dietpi-software: Plex Media Server: migrate to new APT repo

diff --git a/.update/pre-patches b/.update/pre-patches
--- a/.update/pre-patches
+++ b/.update/pre-patches
@@ -627,5 +627,29 @@ Signed-By: /etc/apt/keyrings/dietpi-influxdb.asc"
 	fi
 fi
 
+# v10.1
+if (( $G_DIETPI_VERSION_CORE < 10 || ( $G_DIETPI_VERSION_CORE == 10 && $G_DIETPI_VERSION_SUB < 1 ) ))
+then
+	if [[ -f '/boot/dietpi/.installed' ]] && grep -q '^[[:blank:]]*aSOFTWARE_INSTALL_STATE\[42\]=2' /boot/dietpi/.installed
+	then
+		G_DIETPI-NOTIFY 2 'Updating Plex repository'
+		# APT key
+		G_EXEC mkdir -p /etc/apt/keyrings
+		G_EXEC curl -sSfLo /etc/apt/keyrings/dietpi-plex.asc 'https://downloads.plex.tv/plex-keys/PlexSign.v2.key'
+		# APT source
+		G_EXEC eval 'cat << '\''_EOF_'\'' > /etc/apt/sources.list.d/dietpi-plex.sources
+Types: deb
+URIs: https://repo.plex.tv/deb
+Suites: public
+Components: main
+Signed-By: /etc/apt/keyrings/dietpi-plex.asc'
+		# Cleanup old keys and lists
+		G_EXEC rm -f /etc/apt/sources.list.d/plexmediaserver.list
+		G_EXEC rm -f /etc/apt/trusted.gpg.d/dietpi-plexmediaserver.gpg
+		G_EXEC rm -f /usr/share/keyrings/plexmediaserver.gpg
+		G_EXEC rm -f /usr/share/keyrings/plexmediaserver.v2.gpg
+	fi
+fi
+
 exit 0
 }
