v7.1
+ DietPi-Arr_to_RAM | Add support for Sonarr v3 and Radarr v3
+ DietPi-Arr_to_RAM | On first link to RAM, create a script in the programs data dir to update the linked database backups, as v3 do not support arguments to pass to custom scripts anymore and do not allow to start scripts from within /boot.

diff --git a/dietpi/misc/dietpi-arr_to_RAM b/dietpi/misc/dietpi-arr_to_RAM
--- a/dietpi/misc/dietpi-arr_to_RAM
+++ b/dietpi/misc/dietpi-arr_to_RAM
@@ -63,9 +63,30 @@ Supported programs:
 
 	# Program files array
 	declare -A aFILES=()
-	# - Sonarr/Radarr: Both use the same file names
-	[[ ${INPUT_PROG:-sonarr} == 'sonarr' ]] && aFILES[sonarr]='nzbdrone.db nzbdrone.db-shm nzbdrone.db-wal'
-	[[ ${INPUT_PROG:-radarr} == 'radarr' ]] && aFILES[radarr]='nzbdrone.db nzbdrone.db-shm nzbdrone.db-wal'
+	# - Sonarr
+	if [[ ${INPUT_PROG:-sonarr} == 'sonarr' ]]
+	then
+		# v3
+		if [[ -f '/mnt/dietpi_userdata/sonarr/sonarr.db' || -f '/mnt/dietpi_userdata/sonarr/sonarr.db.bak' ]]
+		then
+			aFILES[sonarr]='sonarr.db sonarr.db-shm sonarr.db-wal'
+		# v2
+		else
+			aFILES[sonarr]='nzbdrone.db nzbdrone.db-shm nzbdrone.db-wal'
+		fi
+	fi
+	# - Radarr
+	if [[ ${INPUT_PROG:-sonarr} == 'sonarr' ]]
+	then
+		# v3
+		if [[ -f '/mnt/dietpi_userdata/radarr/radarr.db' || -f '/mnt/dietpi_userdata/radarr/radarr.db.bak' ]]
+		then
+			aFILES[sonarr]='radarr.db radarr.db-shm radarr.db-wal'
+		# v2
+		else
+			aFILES[sonarr]='nzbdrone.db nzbdrone.db-shm nzbdrone.db-wal'
+		fi
+	fi
 	# - Lidarr
 	[[ ${INPUT_PROG:-lidarr} == 'lidarr' ]] && aFILES[lidarr]='lidarr.db lidarr.db-shm lidarr.db-wal'
 
@@ -73,8 +94,8 @@ Supported programs:
 	(( ${#aFILES[@]} )) || { error=1 Print "Invalid input program ($INPUT_PROG). Aborting...
 $USAGE"; exit 1; }
 
-	FP_DISK=''
-	FP_RAM=''
+	FP_DISK=
+	FP_RAM=
 
 	Link_To_Ram(){
 
@@ -101,6 +122,15 @@ $USAGE"; exit 1; }
 			[[ -d $FP_DISK ]] || continue
 
 			Print "${i^} detected"
+
+			# Create update backup script
+			if [[ ! -f $FP_RAM/dietpi-arr_to_RAM.sh ]]
+			then
+				Print "Creating $FP_RAM/dietpi-arr_to_RAM.sh to be used as ${i^} custom script"
+				echo -e '#!/bin/dash\n/boot/dietpi/misc/dietpi-arr_to_RAN 2 '"$i" > $FP_RAM/dietpi-arr_to_RAM.sh || { error=$? Print "Creating $FP_RAM/dietpi-arr_to_RAM.sh failed. Skipping this program..."; continue; }
+				chmod +x "$FP_RAM/dietpi-arr_to_RAM.sh" || { error=$? Print "Applying $FP_RAM/dietpi-arr_to_RAM.sh execute permissions failed. Skipping this program..."; continue; }
+				chown "$i:dietpi" "$FP_RAM/dietpi-arr_to_RAM.sh" || { error=$? Print "Applying $FP_RAM/dietpi-arr_to_RAM.sh ownership failed. Skipping this program..."; continue; }
+			fi
 
 			# Update backup
 			if (( $INPUT == 2 )); then
@@ -150,7 +180,7 @@ $USAGE"; exit 1; }
 
 					FP_DISK="/mnt/dietpi_userdata/$i/$j"
 					FP_RAM="/tmp/${i}_db_link/$j"
-					local fp_target=''
+					local fp_target=
 
 					# - Source exists and is no symlink, expected situation
 					if [[ -f $FP_DISK && ! -L $FP_DISK ]]; then
