dietpi-servarr-to-ram: further hardening
Check again and fail if database backup and RAM dir are symlinks right before processing those, and fail in case: it would mean that the symlink was created in a short time period, indicating an attempt to gain access to external files. We should probably point this out in the output?

It is not perfect yet, a race condition remains. We need to think through how the script can be used:
- Only updating database backups is possible as respective service user
- Everything else requires root. Hence we actually can use a root-only path for the RAM dir, e.g. a subdir. And we could do write operations within the program dir via "runuser" as service user. That would also eliminate the need for "chown".

However, since this requires more testing, doing the less intrusive change for now, to at least minimize the race condition.

diff --git a/dietpi/misc/dietpi-servarr_to_ram b/dietpi/misc/dietpi-servarr_to_ram
--- a/dietpi/misc/dietpi-servarr_to_ram
+++ b/dietpi/misc/dietpi-servarr_to_ram
@@ -109,6 +109,7 @@ $USAGE"; exit 1; }
 		[[ -L "$FP_DISK-wal" && ! -f "$FP_DISK-wal" ]] && rm "$FP_DISK-wal"
 
 		# Create a backup first, which includes -shm and -wal, then copy that to RAM. If it fails, skip that program.
+		[[ -L $FP_DISK.bak ]] && { error=1 Print "${i^} database backup ($FP_DISK.bak) is a symlink again. Skipping this program..."; return 1; }
 		sqlite3 "$FP_DISK" ".save ${FP_DISK}.bak" || { error=$? Print "Creating ${i^} database backup failed. Skipping this program..."; return 1; }
 		chown "$i" "${FP_DISK}.bak" || { error=$? Print "Setting ${i^} database backup ownership failed. Skipping this program..."; return 1; }
 		cp -aL --no-preserve=timestamps "${FP_DISK}.bak" "$FP_RAM" || { error=$? Print "Copying ${i^} database to RAM failed. Skipping this program..."; return 1; }
@@ -137,18 +138,6 @@ $USAGE"; exit 1; }
 			FP_DISK="/mnt/dietpi_userdata/$i"
 			FP_RAM="/tmp/${i}_db_link"
 
-			# Remove RAM dir and database backup if it is a symlink, for security reasons
-			if [[ -L $FP_RAM ]]
-			then
-				Print "Removing ${i^} RAM directory ($FP_RAM) for security reasons, since it is a symlink..."
-				rm "$FP_RAM" || { error=$? Print "Removing ${i^} RAM directory symlink ($FP_RAM) failed. Skipping this program..."; continue; }
-			fi
-			if [[ -L $FP_DISK/${aFILE[$i]}.bak ]]
-			then
-				Print "Removing ${i^} database backup ($FP_DISK/${aFILE[$i]}.bak) for security reasons, since it is a symlink..."
-				rm "$FP_DISK/${aFILE[$i]}.bak" || { error=$? Print "Removing ${i^} database backup symlink ($FP_DISK/${aFILE[$i]}.bak) failed. Skipping this program..."; continue; }
-			fi
-
 			# Skip non-installed program
 			[[ -d $FP_DISK ]] || continue
 
@@ -164,12 +153,25 @@ $USAGE"; exit 1; }
 				chown "$i:dietpi" "$FP_DISK/dietpi-servarr_to_ram.sh" || { error=$? Print "Applying $FP_DISK/dietpi-servarr_to_ram.sh ownership failed."; }
 			fi
 
+			# Remove RAM dir and database backup if it is a symlink, for security reasons
+			if [[ -L $FP_RAM ]]
+			then
+				Print "Removing ${i^} RAM directory ($FP_RAM) for security reasons, since it is a symlink..."
+				rm "$FP_RAM" || { error=$? Print "Removing ${i^} RAM directory symlink ($FP_RAM) failed. Skipping this program..."; continue; }
+			fi
+			if [[ -L $FP_DISK/${aFILE[$i]}.bak ]]
+			then
+				Print "Removing ${i^} database backup ($FP_DISK/${aFILE[$i]}.bak) for security reasons, since it is a symlink..."
+				rm "$FP_DISK/${aFILE[$i]}.bak" || { error=$? Print "Removing ${i^} database backup symlink ($FP_DISK/${aFILE[$i]}.bak) failed. Skipping this program..."; continue; }
+			fi
+
 			# Update backup
 			if (( $INPUT == 2 )); then
 
 				if [[ -f $FP_RAM/${aFILE[$i]} ]]; then
 
 					Print "Updating ${i^} database backup..."
+					[[ -L $FP_DISK/${aFILE[$i]}.bak ]] && { error=1 Print "${i^} database backup ($FP_DISK/${aFILE[$i]}.bak) is a symlink again. Skipping this program..."; continue; }
 					sqlite3 "$FP_RAM/${aFILE[$i]}" ".save $FP_DISK/${aFILE[$i]}.bak" || { error=$? Print "Updating ${i^} database backup failed."; continue; }
 					Print "Updated ${i^} database backup."
 
@@ -196,6 +198,7 @@ $USAGE"; exit 1; }
 
 				Print "Linking ${i^} database to RAM..."
 				# - Pre-create RAM dir
+				[[ -L $FP_RAM ]] && { error=1 Print "${i^} RAM directory ($FP_RAM) is a symlink again. Skipping this program..."; continue; }
 				[[ -d $FP_RAM ]] || mkdir -p "$FP_RAM" || { error=$? Print "Pre-creating RAM directory for ${i^} failed ($FP_RAM). Skipping this program..."; continue; }
 				# - chown dir in case created by root but program user wants to store back to disk
 				chown "$i" "$FP_RAM" || EXIT_CODE=$?
@@ -229,6 +232,7 @@ $USAGE"; exit 1; }
 					[[ ! -L $FP_DISK ]] || rm "$FP_DISK" || { error=$? Print "Removing orphaned database symlink failed ($FP_DISK). Skipping this program..."; continue; }
 
 					# Recover from backup
+					[[ -L $FP_DISK.bak ]] && { error=1 Print "${i^} database backup ($FP_DISK.bak) is a symlink again. Skipping this program..."; continue; }
 					mv "${FP_DISK}.bak" "$FP_DISK" || { error=$? Print "Recovering database from backup failed (${FP_DISK}.bak). Skipping this program..."; continue; }
 
 					Link_To_Ram || continue
@@ -245,6 +249,7 @@ $USAGE"; exit 1; }
 				if [[ -d $FP_RAM ]]; then
 
 					Print "Storing database from RAM ($FP_RAM) back to disk ($FP_DISK)..."
+					[[ -L $FP_RAM ]] && { error=1 Print "${i^} RAM directory ($FP_RAM) is a symlink again. Skipping this program..."; continue; }
 					# "-u" will only copy newer files, thus actually used by program.
 					# "--remove-destination" will remove expected existing symlinks.
 					cp -au --remove-destination "$FP_RAM/." "$FP_DISK" || { error=$? Print "Storing ${i^} database from RAM back to disk failed."; continue; }
