dietpi-servarr-to-ram: guard RAM dir and database backup against malicious symlinks
So if a compromised service user pre-creates either/and of those as symlink to a sensitive directory elsewhere, the script won't create/overwrite/copy following that symlink. Instead it will (attempt to) remove the symlink before processing, or skip it if removal fails. This is also safe to do regarding data loss, since only a symlink is ever removed, and users are transparently informed, in case that symlink was created without bad intention.

diff --git a/dietpi/misc/dietpi-servarr_to_ram b/dietpi/misc/dietpi-servarr_to_ram
--- a/dietpi/misc/dietpi-servarr_to_ram
+++ b/dietpi/misc/dietpi-servarr_to_ram
@@ -137,6 +137,18 @@ $USAGE"; exit 1; }
 			FP_DISK="/mnt/dietpi_userdata/$i"
 			FP_RAM="/tmp/${i}_db_link"
 
+			# Remove RAM dir and database backup if it is a symlink, for security reasons
+			if [[ -L $FP_RAM ]]
+			then
+				Print "Removing ${i^} RAM directory ($FP_RAM) for security reasons, since it is a symlink..."
+				rm "$FP_RAM" || { error=$? Print "Removing ${i^} RAM directory symlink ($FP_RAM) failed. Skipping this program..."; continue; }
+			fi
+			if [[ -L $FP_DISK/${aFILE[$i]}.bak ]]
+			then
+				Print "Removing ${i^} database backup ($FP_DISK/${aFILE[$i]}.bak) for security reasons, since it is a symlink..."
+				rm "$FP_DISK/${aFILE[$i]}.bak" || { error=$? Print "Removing ${i^} database backup symlink ($FP_DISK/${aFILE[$i]}.bak) failed. Skipping this program..."; continue; }
+			fi
+
 			# Skip non-installed program
 			[[ -d $FP_DISK ]] || continue
 
