v6.23
+ DietPi-Arr_to_RAM | Skip chown for whole RAM/disk dir, since we use cp -a/mv to preserve permissions. In case of failure, the source of changed permissions should be examined instead of doing the failsafe chown silently that does not fix the initial cause. chown $FP_RAM (without content) and disk symlink explicitly to allow *arr program user storing database back to disk cleanly.
+ DietPi-Arr_to_RAM | Allow exit code for boot service. Otherwise the service can be inactive even that databases might already partly been moved to RAM. On shutdown those would then not be stored back to disk, which should always be done.
+ DietPi-Arr_to_RAM | Minor coding and wording

diff --git a/dietpi/misc/dietpi-arr_to_RAM b/dietpi/misc/dietpi-arr_to_RAM
--- a/dietpi/misc/dietpi-arr_to_RAM
+++ b/dietpi/misc/dietpi-arr_to_RAM
@@ -79,7 +79,7 @@ $USAGE"; exit 1; }
 		Print "Linking $FP_DISK to RAM ($FP_RAM)..."
 		mv $FP_DISK ${FP_DISK}.bak || { error=$? Print "Creating backup failed for $FP_DISK. Skipping this file..."; return; }
 		ln -s $FP_RAM $FP_DISK || EXIT_CODE=$?
-		# Failsafe: chown link in case created by root but program user wants to restore
+		# chown link in case created by root but program user wants to store back to disk
 		chown -h $i $FP_DISK || EXIT_CODE=$?
 		cp -a --no-preserve=timestamps ${FP_DISK}.bak $FP_RAM || EXIT_CODE=$?
 
@@ -140,6 +140,8 @@ $USAGE"; exit 1; }
 				Print "Linking ${i^} database to RAM..."
 				# - Pre-create RAM dir
 				[[ -d $FP_RAM ]] || mkdir -p $FP_RAM || { error=$? Print "Pre-creating RAM directory for ${i^} failed ($FP_RAM). Skipping this program..."; continue; }
+				# - chown dir in case created by root but program user wants to store back to disk
+				chown $i $FP_RAM || EXIT_CODE=$?
 
 				for j in ${aFILES[$i]}
 				do
@@ -188,23 +190,19 @@ $USAGE"; exit 1; }
 
 				done
 
-				# - Failsafe: chown fully to program user since nothing else ever needs or should access this database directly
-				chown -R ${i}:${i} /tmp/${i}_db_link
 				Print "Linked ${i^} database to RAM."
 
-			# Store to disk
+			# Store back to disk
 			elif (( $INPUT == 0 )); then
 
 				if [[ -d $FP_RAM ]]; then
 
-					Print "Restoring database from RAM ($FP_RAM) to disk ($FP_DISK)..."
+					Print "Storing database from RAM ($FP_RAM) back to disk ($FP_DISK)..."
 					# - "-u" will only copy newer files, thus actually used by program.
 					# - "--remove-destination" will remove expected existing symlinks.
-					cp -au --remove-destination $FP_RAM/. $FP_DISK || { error=$? Print "Restoring ${i^} database from RAM to disk failed."; continue; }
+					cp -au --remove-destination $FP_RAM/. $FP_DISK || { error=$? Print "Storing ${i^} database from RAM back to disk failed."; continue; }
 					rm -R $FP_RAM
-					# - Failsafe: chown fully to program user since nothing else ever needs or should access this database directly
-					chown -R ${i}:${i} $FP_DISK
-					Print "Restored ${i^} database from RAM to disk."
+					Print "Stored ${i^} database from RAM back to disk."
 
 				else
 
@@ -243,7 +241,7 @@ Before=dietpi-preboot.service sonarr.service radarr.service lidarr.service
 [Service]
 Type=forking
 RemainAfterExit=yes
-ExecStart=/bin/dash -c '/DietPi/dietpi/misc/dietpi-arr_to_RAM 1 2>&1 >> $FP_LOG'
+ExecStart=-/bin/dash -c '/DietPi/dietpi/misc/dietpi-arr_to_RAM 1 2>&1 >> $FP_LOG'
 ExecStop=/bin/dash -c '/DietPi/dietpi/misc/dietpi-arr_to_RAM 0 2>&1 > $FP_LOG'
 
 [Install]
@@ -276,16 +274,10 @@ _EOF_
 		Toggle_Link_To_Ram
 		(( $EXIT_CODE )) && Print '[ERROR] An issue has occurred. Please check the above output for details.'
 
-	# - Enable Link to RAM on boot
-	elif [[ $INPUT == 'enable' ]]; then
+	# - Enable/Disable Link to RAM on boot
+	elif [[ $INPUT == 'enable' || $INPUT == 'disable' ]]; then
 
-		Enable_On_Boot
-		(( $EXIT_CODE )) && Print "[ERROR] An issue has occurred. Please check the log for details: $FP_LOG"
-
-	# - Disable Link to RAM on boot
-	elif [[ $INPUT == 'disable' ]]; then
-
-		Disable_On_Boot
+		${INPUT^}_On_Boot
 		(( $EXIT_CODE )) && Print "[ERROR] An issue has occurred. Please check the log for details: $FP_LOG"
 
 	else
