Add TUI menu to dietpi-servarr_to_ram, update launcher, bashrc alias and patches
Co-authored-by: StephanStS <57687516+StephanStS@users.noreply.github.com>

diff --git a/dietpi/misc/dietpi-servarr_to_ram b/dietpi/misc/dietpi-servarr_to_ram
--- a/dietpi/misc/dietpi-servarr_to_ram
+++ b/dietpi/misc/dietpi-servarr_to_ram
@@ -1,7 +1,7 @@
 #!/bin/bash
 {
 	#////////////////////////////////////
-	# DietPi Link Arr to RAM
+	# DietPi Link Servarr to RAM
 	#
 	#////////////////////////////////////
 	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
@@ -9,13 +9,13 @@
 	#////////////////////////////////////
 	#
 	# Info:
-	# - Moves Sonarr, Radarr and Lidarr database files to RAM, leaving symlinks on disk
+	# - Moves Sonarr, Radarr, Lidarr and Prowlarr database files to RAM, leaving symlinks on disk
 	# - Reduces disk I/O and enhances database I/O performance
 	# - Creates a backup first and automatically restores from backup on next start in case of system crash
 	# NB: Not supported on Jessie: https://github.com/MichaIng/DietPi/issues/2689#issuecomment-487306241
 	#
 	readonly USAGE='
-Usage: dietpi-arr_to_RAM <command> [<program>]
+Usage: dietpi-servarr_to_ram <command> [<program>]
 Available commands:
   1 [<program>]		Link (program) database(s) to RAM
   2 [<program>]		Update (program) database backup(s)
@@ -27,11 +27,12 @@ Supported programs:
   sonarr		Apply to Sonarr database only
   radarr		Apply to Radarr database only
   lidarr		Apply to Lidarr database only
+  prowlarr		Apply to Prowlarr database only
 '	#////////////////////////////////////
 
 	# Import DietPi-Globals --------------------------------------------------------------
 	#. /boot/dietpi/func/dietpi-globals	# Skip globals for faster execution on early boot stage
-	readonly PROGRAM_NAME='DietPi-Arr_to_RAM'
+	readonly PROGRAM_NAME='DietPi-Servarr_to_RAM'
 	# Import DietPi-Globals --------------------------------------------------------------
 
 	# Grab input
@@ -53,42 +54,48 @@ Supported programs:
 
 	}
 
-	# Check for required root or program specific permissions permissions
+	# Check for required root or program specific permissions
 	# - Handling systemd service always requires root permissions
 	# - Database backup updates can be done as program user when defined via $2
 	(( $UID )) && [[ $INPUT != 2 || $USER != "$INPUT_PROG" ]] && { error=1 Print 'This script must run as root user. Please use: "sudo"'; exit 1; }
 
-	# Boot service log file
-	FP_LOG='/var/tmp/dietpi/logs/dietpi-arr_to_RAM.log'
-
 	# Program database name array
 	declare -A aFILE=()
-	# - Sonarr
-	if [[ ${INPUT_PROG:-sonarr} == 'sonarr' ]]
-	then
-		# v3
-		if [[ -f '/mnt/dietpi_userdata/sonarr/sonarr.db' || -f '/mnt/dietpi_userdata/sonarr/sonarr.db.bak' ]]
+
+	Init_Programs()
+	{
+		aFILE=()
+		# - Sonarr
+		if [[ ${INPUT_PROG:-sonarr} == 'sonarr' ]]
 		then
-			aFILE[sonarr]='sonarr.db'
-		# v2
-		else
-			aFILE[sonarr]='nzbdrone.db'
+			# v3
+			if [[ -f '/mnt/dietpi_userdata/sonarr/sonarr.db' || -f '/mnt/dietpi_userdata/sonarr/sonarr.db.bak' ]]
+			then
+				aFILE[sonarr]='sonarr.db'
+			# v2
+			else
+				aFILE[sonarr]='nzbdrone.db'
+			fi
 		fi
-	fi
-	# - Radarr
-	if [[ ${INPUT_PROG:-radarr} == 'radarr' ]]
-	then
-		# v3
-		if [[ -f '/mnt/dietpi_userdata/radarr/radarr.db' || -f '/mnt/dietpi_userdata/radarr/radarr.db.bak' ]]
+		# - Radarr
+		if [[ ${INPUT_PROG:-radarr} == 'radarr' ]]
 		then
-			aFILE[radarr]='radarr.db'
-		# v2
-		else
-			aFILE[radarr]='nzbdrone.db'
+			# v3
+			if [[ -f '/mnt/dietpi_userdata/radarr/radarr.db' || -f '/mnt/dietpi_userdata/radarr/radarr.db.bak' ]]
+			then
+				aFILE[radarr]='radarr.db'
+			# v2
+			else
+				aFILE[radarr]='nzbdrone.db'
+			fi
 		fi
-	fi
-	# - Lidarr
-	[[ ${INPUT_PROG:-lidarr} == 'lidarr' ]] && aFILE[lidarr]='lidarr.db'
+		# - Lidarr
+		[[ ${INPUT_PROG:-lidarr} == 'lidarr' ]] && aFILE[lidarr]='lidarr.db'
+		# - Prowlarr
+		[[ ${INPUT_PROG:-prowlarr} == 'prowlarr' ]] && aFILE[prowlarr]='prowlarr.db'
+	}
+
+	Init_Programs
 
 	# Check for valid input program
 	(( ${#aFILE[@]} )) || { error=1 Print "Invalid input program ($INPUT_PROG). Aborting...
@@ -106,6 +113,7 @@ $USAGE"; exit 1; }
 		[[ -L "$FP_DISK-wal" && ! -f "$FP_DISK-wal" ]] && rm "$FP_DISK-wal"
 
 		# Create a backup first, which includes -shm and -wal, then copy that to RAM. If it fails, skip that program.
+		[[ -L $FP_DISK.bak ]] && { error=1 Print "${i^} database backup ($FP_DISK.bak) is a symlink again. Skipping this program..."; return 1; }
 		sqlite3 "$FP_DISK" ".save ${FP_DISK}.bak" || { error=$? Print "Creating ${i^} database backup failed. Skipping this program..."; return 1; }
 		chown "$i" "${FP_DISK}.bak" || { error=$? Print "Setting ${i^} database backup ownership failed. Skipping this program..."; return 1; }
 		cp -aL --no-preserve=timestamps "${FP_DISK}.bak" "$FP_RAM" || { error=$? Print "Copying ${i^} database to RAM failed. Skipping this program..."; return 1; }
@@ -140,13 +148,31 @@ $USAGE"; exit 1; }
 			Print "${i^} detected"
 
 			# Create update backup script
-			if [[ ! -f $FP_DISK/dietpi-arr_to_RAM.sh ]]
+			# - Remove script if it is a symlink, for security reasons
+			if [[ -L $FP_DISK/dietpi-servarr_to_ram.sh ]]
 			then
-				Print "Creating $FP_DISK/dietpi-arr_to_RAM.sh to be used as ${i^} custom script"
+				Print "Removing $FP_DISK/dietpi-servarr_to_ram.sh for security reasons, since it is a symlink..."
+				rm "$FP_DISK/dietpi-servarr_to_ram.sh" || { error=$? Print "Removing $FP_DISK/dietpi-servarr_to_ram.sh failed. Skipping this program..."; continue; }
+			fi
+			if [[ ! -f $FP_DISK/dietpi-servarr_to_ram.sh ]]
+			then
+				Print "Creating $FP_DISK/dietpi-servarr_to_ram.sh to be used as ${i^} custom script"
 				# shellcheck disable=SC2320
-				echo -e '#!/bin/dash\n/boot/dietpi/misc/dietpi-arr_to_RAM 2 '"$i" > "$FP_DISK/dietpi-arr_to_RAM.sh" || { error=$? Print "Creating $FP_DISK/dietpi-arr_to_RAM.sh failed."; }
-				chmod +x "$FP_DISK/dietpi-arr_to_RAM.sh" || { error=$? Print "Applying $FP_DISK/dietpi-arr_to_RAM.sh execute permissions failed."; }
-				chown "$i:dietpi" "$FP_DISK/dietpi-arr_to_RAM.sh" || { error=$? Print "Applying $FP_DISK/dietpi-arr_to_RAM.sh ownership failed."; }
+				echo -e '#!/bin/dash\n/boot/dietpi/misc/dietpi-servarr_to_ram 2 '"$i" > "$FP_DISK/dietpi-servarr_to_ram.sh" || { error=$? Print "Creating $FP_DISK/dietpi-servarr_to_ram.sh failed."; }
+				chmod +x "$FP_DISK/dietpi-servarr_to_ram.sh" || { error=$? Print "Applying $FP_DISK/dietpi-servarr_to_ram.sh execute permissions failed."; }
+				chown "$i:dietpi" "$FP_DISK/dietpi-servarr_to_ram.sh" || { error=$? Print "Applying $FP_DISK/dietpi-servarr_to_ram.sh ownership failed."; }
+			fi
+
+			# Remove RAM dir and database backup if it is a symlink, for security reasons
+			if [[ -L $FP_RAM ]]
+			then
+				Print "Removing ${i^} RAM directory ($FP_RAM) for security reasons, since it is a symlink..."
+				rm "$FP_RAM" || { error=$? Print "Removing ${i^} RAM directory symlink ($FP_RAM) failed. Skipping this program..."; continue; }
+			fi
+			if [[ -L $FP_DISK/${aFILE[$i]}.bak ]]
+			then
+				Print "Removing ${i^} database backup ($FP_DISK/${aFILE[$i]}.bak) for security reasons, since it is a symlink..."
+				rm "$FP_DISK/${aFILE[$i]}.bak" || { error=$? Print "Removing ${i^} database backup symlink ($FP_DISK/${aFILE[$i]}.bak) failed. Skipping this program..."; continue; }
 			fi
 
 			# Update backup
@@ -155,6 +181,7 @@ $USAGE"; exit 1; }
 				if [[ -f $FP_RAM/${aFILE[$i]} ]]; then
 
 					Print "Updating ${i^} database backup..."
+					[[ -L $FP_DISK/${aFILE[$i]}.bak ]] && { error=1 Print "${i^} database backup ($FP_DISK/${aFILE[$i]}.bak) is a symlink again. Skipping this program..."; continue; }
 					sqlite3 "$FP_RAM/${aFILE[$i]}" ".save $FP_DISK/${aFILE[$i]}.bak" || { error=$? Print "Updating ${i^} database backup failed."; continue; }
 					Print "Updated ${i^} database backup."
 
@@ -181,6 +208,7 @@ $USAGE"; exit 1; }
 
 				Print "Linking ${i^} database to RAM..."
 				# - Pre-create RAM dir
+				[[ -L $FP_RAM ]] && { error=1 Print "${i^} RAM directory ($FP_RAM) is a symlink again. Skipping this program..."; continue; }
 				[[ -d $FP_RAM ]] || mkdir -p "$FP_RAM" || { error=$? Print "Pre-creating RAM directory for ${i^} failed ($FP_RAM). Skipping this program..."; continue; }
 				# - chown dir in case created by root but program user wants to store back to disk
 				chown "$i" "$FP_RAM" || EXIT_CODE=$?
@@ -214,6 +242,7 @@ $USAGE"; exit 1; }
 					[[ ! -L $FP_DISK ]] || rm "$FP_DISK" || { error=$? Print "Removing orphaned database symlink failed ($FP_DISK). Skipping this program..."; continue; }
 
 					# Recover from backup
+					[[ -L $FP_DISK.bak ]] && { error=1 Print "${i^} database backup ($FP_DISK.bak) is a symlink again. Skipping this program..."; continue; }
 					mv "${FP_DISK}.bak" "$FP_DISK" || { error=$? Print "Recovering database from backup failed (${FP_DISK}.bak). Skipping this program..."; continue; }
 
 					Link_To_Ram || continue
@@ -230,6 +259,7 @@ $USAGE"; exit 1; }
 				if [[ -d $FP_RAM ]]; then
 
 					Print "Storing database from RAM ($FP_RAM) back to disk ($FP_DISK)..."
+					[[ -L $FP_RAM ]] && { error=1 Print "${i^} RAM directory ($FP_RAM) is a symlink again. Skipping this program..."; continue; }
 					# "-u" will only copy newer files, thus actually used by program.
 					# "--remove-destination" will remove expected existing symlinks.
 					cp -au --remove-destination "$FP_RAM/." "$FP_DISK" || { error=$? Print "Storing ${i^} database from RAM back to disk failed."; continue; }
@@ -256,8 +286,8 @@ $USAGE"; exit 1; }
 		(( $INPUT == 0 )) && sync
 
 		# Start programs we stopped before
-		# - NB: Due to Before=, *arr.service waits for dietpi-arr_to_RAM.service to finish, timing it out.
-		# - "--no-block" allows dietpi-arr_to_RAM.service to only enqueue *arr.service starts and finish, to allow them starting afterwards.
+		# - NB: Due to Before=, *arr.service waits for dietpi-servarr_to_ram.service to finish, timing it out.
+		# - "--no-block" allows dietpi-servarr_to_ram.service to only enqueue *arr.service starts and finish, to allow them starting afterwards.
 		if [[ ${astart_services[0]} ]]; then
 
 			Print "Enqueuing ${astart_services[*]} service start(s)..."
@@ -268,43 +298,52 @@ $USAGE"; exit 1; }
 	}
 
 	# shellcheck disable=SC2329
-	Enable_On_Boot(){
-
-		cat << _EOF_ > /etc/systemd/system/dietpi-arr_to_RAM.service
+	Enable_On_Boot()
+	{
+		cat << '_EOF_' > /etc/systemd/system/dietpi-servarr_to_ram.service || EXIT_CODE=$?
 [Unit]
-Description=DietPi-Arr_to_RAM
+Description=DietPi-Servarr_to_RAM
 Requisite=tmp.mount
 After=tmp.mount
-Before=dietpi-preboot.service sonarr.service radarr.service lidarr.service
+Before=sonarr.service radarr.service lidarr.service prowlarr.service
 
 [Service]
 Type=oneshot
 RemainAfterExit=yes
-ExecStart=-/bin/dash -c '/boot/dietpi/misc/dietpi-arr_to_RAM 1 2>&1 >> $FP_LOG'
-ExecStop=/bin/dash -c '/boot/dietpi/misc/dietpi-arr_to_RAM 0 2>&1 > $FP_LOG'
+# We want to preserve logs from the last service stop, to know whether there were issues storing the database back to disk.
+ExecStart=-/bin/dash -c '/boot/dietpi/misc/dietpi-servarr_to_ram 1 2>&1 >> /var/tmp/dietpi/logs/dietpi-servarr_to_ram.log'
+ExecStop=/bin/dash -c '/boot/dietpi/misc/dietpi-servarr_to_ram 0 2>&1 > /var/tmp/dietpi/logs/dietpi-servarr_to_ram.log'
 
 [Install]
 WantedBy=multi-user.target
 _EOF_
-		systemctl daemon-reload
-		systemctl enable --now dietpi-arr_to_RAM || EXIT_CODE=$?
-
+		systemctl daemon-reload || EXIT_CODE=$?
+		systemctl enable --now dietpi-servarr_to_ram || EXIT_CODE=$?
 	}
 
 	# shellcheck disable=SC2329
-	Disable_On_Boot(){
-
-		if [[ -f '/etc/systemd/system/dietpi-arr_to_RAM.service' ]]
-		then
-			systemctl disable --now dietpi-arr_to_RAM || EXIT_CODE=$?
-			rm /etc/systemd/system/dietpi-arr_to_RAM.service
-		fi
-
+	Disable_On_Boot()
+	{
+		[[ -f '/etc/systemd/system/dietpi-servarr_to_ram.service' ]] || return 0
+		systemctl --no-reload disable --now dietpi-servarr_to_ram || EXIT_CODE=$?
+		rm /etc/systemd/system/dietpi-servarr_to_ram.service || EXIT_CODE=$?
 	}
 
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Main Loop
 	#/////////////////////////////////////////////////////////////////////////////////////
+	# Assure SQLite is available
+	GLOBALS_LOADED=0
+	if ! command -v sqlite3 &> /dev/null
+	then
+		Print 'Installing SQLite, used by this script to create database backups...'
+		. /boot/dietpi/func/dietpi-globals
+		G_PROGRAM_NAME='DietPi-Servarr_to_RAM'
+		GLOBALS_LOADED=1
+		G_AGUP
+		G_AGI sqlite3
+	fi
+
 	# Toggle Link to RAM
 	if [[ $INPUT == [012] ]]; then
 
@@ -315,7 +354,89 @@ _EOF_
 	elif [[ $INPUT == 'enable' || $INPUT == 'disable' ]]; then
 
 		"${INPUT^}_On_Boot"
-		(( $EXIT_CODE )) && Print "[ERROR] An issue has occurred. Please check the log for details: $FP_LOG"
+		(( $EXIT_CODE )) && Print '[ERROR] An issue has occurred. Please check the above output for details.'
+
+	# Interactive TUI mode
+	elif [[ ! $INPUT ]]; then
+
+		(( $GLOBALS_LOADED )) || . /boot/dietpi/func/dietpi-globals
+		G_PROGRAM_NAME='DietPi-Servarr_to_RAM'
+		G_INIT
+
+		Menu_Program()
+		{
+			G_WHIP_MENU_ARRAY=(
+				'all' ': Apply to all installed programs'
+				'sonarr' ': Apply to Sonarr only'
+				'radarr' ': Apply to Radarr only'
+				'lidarr' ': Apply to Lidarr only'
+				'prowlarr' ': Apply to Prowlarr only'
+			)
+			G_WHIP_BUTTON_CANCEL_TEXT='Back'
+			G_WHIP_MENU 'Please select a program to apply this to:' || return 1
+			INPUT_PROG=$G_WHIP_RETURNED_VALUE
+			[[ $INPUT_PROG == 'all' ]] && INPUT_PROG=''
+			Init_Programs
+		}
+
+		Menu_Main()
+		{
+			local boot_status='disabled'
+			systemctl -q is-enabled dietpi-servarr_to_ram 2> /dev/null && boot_status='enabled'
+
+			G_WHIP_MENU_ARRAY=(
+				'' '●─ Database '
+				'link' ': Link Servarr databases to RAM'
+				'store' ': Store databases back to disk'
+				'backup' ': Update database backups'
+				'' '●─ Boot service '
+				'boot' "[${boot_status^}] Enable/disable link to RAM on system boot"
+			)
+
+			G_WHIP_BUTTON_CANCEL_TEXT='Exit'
+			G_WHIP_MENU "DietPi-Servarr_to_RAM: Link Sonarr, Radarr, Lidarr and Prowlarr databases to RAM
+\nBoot service: $boot_status" || return 1
+
+			case $G_WHIP_RETURNED_VALUE in
+
+				'link')
+					Menu_Program || return 0
+					INPUT=1
+					Toggle_Link_To_Ram
+					(( $EXIT_CODE )) && G_WHIP_MSG '[ERROR] An issue has occurred. Please check the above output for details.'
+					EXIT_CODE=0
+				;;
+
+				'store')
+					Menu_Program || return 0
+					INPUT=0
+					Toggle_Link_To_Ram
+					(( $EXIT_CODE )) && G_WHIP_MSG '[ERROR] An issue has occurred. Please check the above output for details.'
+					EXIT_CODE=0
+				;;
+
+				'backup')
+					Menu_Program || return 0
+					INPUT=2
+					Toggle_Link_To_Ram
+					(( $EXIT_CODE )) && G_WHIP_MSG '[ERROR] An issue has occurred. Please check the above output for details.'
+					EXIT_CODE=0
+				;;
+
+				'boot')
+					if [[ $boot_status == 'enabled' ]]; then
+						Disable_On_Boot
+					else
+						Enable_On_Boot
+					fi
+					(( $EXIT_CODE )) && G_WHIP_MSG '[ERROR] An issue has occurred. Please check the above output for details.'
+					EXIT_CODE=0
+				;;
+
+			esac
+		}
+
+		while :; do Menu_Main || break; done
 
 	else
 
