v7.1
+ DietPi-Arr_to_RAM | Satisfy shellcheck

diff --git a/dietpi/misc/dietpi-arr_to_RAM b/dietpi/misc/dietpi-arr_to_RAM
--- a/dietpi/misc/dietpi-arr_to_RAM
+++ b/dietpi/misc/dietpi-arr_to_RAM
@@ -127,7 +127,7 @@ $USAGE"; exit 1; }
 			if [[ ! -f $FP_RAM/dietpi-arr_to_RAM.sh ]]
 			then
 				Print "Creating $FP_RAM/dietpi-arr_to_RAM.sh to be used as ${i^} custom script"
-				echo -e '#!/bin/dash\n/boot/dietpi/misc/dietpi-arr_to_RAN 2 '"$i" > $FP_RAM/dietpi-arr_to_RAM.sh || { error=$? Print "Creating $FP_RAM/dietpi-arr_to_RAM.sh failed. Skipping this program..."; continue; }
+				echo -e '#!/bin/dash\n/boot/dietpi/misc/dietpi-arr_to_RAN 2 '"$i" > "$FP_RAM/dietpi-arr_to_RAM.sh" || { error=$? Print "Creating $FP_RAM/dietpi-arr_to_RAM.sh failed. Skipping this program..."; continue; }
 				chmod +x "$FP_RAM/dietpi-arr_to_RAM.sh" || { error=$? Print "Applying $FP_RAM/dietpi-arr_to_RAM.sh execute permissions failed. Skipping this program..."; continue; }
 				chown "$i:dietpi" "$FP_RAM/dietpi-arr_to_RAM.sh" || { error=$? Print "Applying $FP_RAM/dietpi-arr_to_RAM.sh ownership failed. Skipping this program..."; continue; }
 			fi
