v6.26
+ DietPi-NordVPN | Do root user and rootfs R/W check only when menu is to be loaded, otherwise printing status would prompt error messages even that both is not required. This allows to load DietPi-Globals as well just for menu, which speeds up status print.
+ DietPi-NordVPN | Force non-interactive mode on status print, to skip any whiptail prompt
+ DietPi-NordVPN | Update WAN IP only on before first menu load, on connect, disconnect and refresh, to speed up all other navigation steps, which do not affect the connection state. This is due the WAN IP check can take up to two seconds, which adds a significant delay.
+ DietPi-NordVPN | Move RX/TX obtaining into an own function and remove DietPi-Globals dependency from it. This allows to share very most code between menu mode and status print.
+ DietPi-NordVPN | Further coding and wording enhancements

diff --git a/dietpi/misc/dietpi-nordvpn b/dietpi/misc/dietpi-nordvpn
--- a/dietpi/misc/dietpi-nordvpn
+++ b/dietpi/misc/dietpi-nordvpn
@@ -10,30 +10,24 @@
 	#
 	# Info:
 	# - GUI to setup a NordVPN connection
-	# - Automatically starts service during boot
-	# Usage:
-	# - /DietPi/dietpi/misc/dietpi-nordvpn
-	# - /DietPi/dietpi/misc/dietpi-nordvpn status
-	#////////////////////////////////////
+	# - Allows to automatically connect on boot
+	# - Allows to add post-up and pre-down scripts
 	USAGE='
-Usage: dietpi-norddvpn [<command>]
+Usage: dietpi-nordvpn [<command>]
 Available commands:
   <empty>		Interactive menu to edit, connect and apply NordVPN settings
   status		Print NordVPN connection status info
 '	#////////////////////////////////////
 
-	COLOUR_RESET='\e[0m'
+	# Import DietPi-Globals --------------------------------------------------------------
+	# - Only loaded for interactive menu
+	G_PROGRAM_NAME='DietPi-NordVPN'
+	# Import DietPi-Globals --------------------------------------------------------------
 
 	# Grab Inputs
-	INPUT_CMD=$1
-
-	# Import DietPi-Globals --------------------------------------------------------------
-	. /DietPi/dietpi/func/dietpi-globals
-	G_PROGRAM_NAME='DietPi-NordVPN'
-	G_CHECK_ROOT_USER
-	G_CHECK_ROOTFS_RW
-	G_INIT
-	# Import DietPi-Globals --------------------------------------------------------------
+	INPUT=$1
+	# - Force non-interactive mode on status print, to skip any whiptail prompt
+	[[ $INPUT == 'status' ]] && G_INTERACTIVE=0
 
 	FP_SETTINGS_DIETPI='/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/settings_dietpi.conf'
 	FP_SETTINGS_OVPN='/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/settings_ovpn.conf'
@@ -45,30 +39,17 @@ Available commands:
 	PROTOCOL='udp'
 
 	NET_DEV='tun0'
+	MAX_WAIT_FOR_CONNECTION=5
+	NORDVPN_INSTALLED=0
 	NORDVPN_SERVICE=0
 	NORDVPN_CONNECTED=0
-	MAX_WAIT_FOR_CONNECTION=5
 	WAN_IP=''
+	RX='N/A'
+	TX='N/A'
 
-	Update_Wan_Ip(){ WAN_IP=$(curl -sLm 2 https://dietpi.com/myip.php 2>&1); }
+	Update_Wan_Ip(){ WAN_IP=$(curl -sSfLm 2 https://dietpi.com/myip.php 2>&1); }
 
 	Init(){
-		if [[ $1 == 'status' ]]; then
-			
-			# Check installed
-			until grep -q 'aSOFTWARE_INSTALL_STATE\[171\]=2' /DietPi/dietpi/.installed
-			do
-			
-				echo "$G_PROGRAM_NAME is not installed!"
-				break
-			
-			done
-
-			# Check service exists
-			[[ -f '/lib/systemd/system/dietpi-nordvpn.service' ]] && NORDVPN_SERVICE=1
-
-			return
-		fi
 
 		# Check installed
 		until grep -q 'aSOFTWARE_INSTALL_STATE\[171\]=2' /DietPi/dietpi/.installed
@@ -80,27 +61,43 @@ Available commands:
 
 			else
 
-				TARGETMENUID=-1 #Exit path without save.
-				break
+				TARGETMENUID=-1 # Skip menu
+				return
 
 			fi
 
 		done
+		NORDVPN_INSTALLED=1
 
 		# Check service exists
 		[[ -f '/lib/systemd/system/dietpi-nordvpn.service' ]] && NORDVPN_SERVICE=1
-
-		Read_Settings
 
 	}
 
 	Check_Connected(){
 
-		NORDVPN_CONNECTED=0
 		#systemctl status dietpi-nordvpn | grep -qi 'initialization sequence completed'
-		ip r s dev $NET_DEV &>/dev/null && NORDVPN_CONNECTED=1
-
+		ip r s dev $NET_DEV &> /dev/null && NORDVPN_CONNECTED=1 || NORDVPN_CONNECTED=0
 		return $(( ! $NORDVPN_CONNECTED ))
+
+	}
+
+	Get_Connection_Info(){
+
+		RX='N/A'
+		if [[ -f /sys/class/net/$NET_DEV/statistics/rx_bytes ]]; then
+
+			local rx=$(</sys/class/net/$NET_DEV/statistics/rx_bytes)
+			[[ $rx =~ ^[0-9]+$ ]] && RX="$(( $rx / 1024 / 1024 )) MiB"
+
+		fi
+		TX='N/A'
+		if [[ -f /sys/class/net/$NET_DEV/statistics/tx_bytes ]]; then
+
+			local tx=$(</sys/class/net/$NET_DEV/statistics/tx_bytes)
+			[[ $tx =~ ^[0-9]+$ ]] && TX="$(( $tx / 1024 / 1024 )) MiB"
+
+		fi
 
 	}
 
@@ -108,7 +105,7 @@ Available commands:
 
 	Save_Settings(){
 
-		if [[ ! $NORDVPN_SERVER || ! $NORDVPN_USERNAME || ! $NORDVPN_PASSWORD ]]; then
+		if ! [[ $NORDVPN_SERVER && $NORDVPN_USERNAME && $NORDVPN_PASSWORD ]]; then
 
 			G_WHIP_MSG '[FAILED] You need to enter your NordVPN username + password and select a server, before settings can be applied.'
 			return 1
@@ -130,13 +127,13 @@ PROTOCOL='$PROTOCOL'
 _EOF_
 
 		local fp_ovpn="/etc/openvpn/ovpn_$PROTOCOL/$NORDVPN_SERVER"
-		G_CONFIG_INJECT 'auth-user-pass([[:blank:]]|$)' "auth-user-pass $FP_SETTINGS_OVPN" $fp_ovpn
-		[[ -f $FP_SETTINGS_UP || -f $FP_SETTINGS_DOWN ]] && G_CONFIG_INJECT 'script-security[[:blank:]]' 'script-security 2' $fp_ovpn 'auth[[:blank:]]' || sed -i '/^[[:blank:]]*script-security[[:blank:]]/d' $fp_ovpn
-		[[ -f $FP_SETTINGS_UP ]] && G_CONFIG_INJECT 'route-up[[:blank:]]' "route-up $FP_SETTINGS_UP" $fp_ovpn 'auth[[:blank:]]' || sed -i '/^[[:blank:]]*up[[:blank:]]/d' $fp_ovpn
-		[[ -f $FP_SETTINGS_DOWN ]] && G_CONFIG_INJECT 'route-pre-down[[:blank:]]' "route-pre-down $FP_SETTINGS_DOWN" $fp_ovpn 'auth[[:blank:]]' || sed -i '/^[[:blank:]]*down[[:blank:]]/d' $fp_ovpn
-
 		chmod 600 $FP_SETTINGS_OVPN $FP_SETTINGS_DIETPI $fp_ovpn
 		chown root:root $FP_SETTINGS_OVPN $FP_SETTINGS_DIETPI $fp_ovpn
+
+		G_CONFIG_INJECT 'auth-user-pass([[:blank:]]|$)' "auth-user-pass $FP_SETTINGS_OVPN" $fp_ovpn
+		[[ -f $FP_SETTINGS_UP || -f $FP_SETTINGS_DOWN ]] && G_CONFIG_INJECT 'script-security[[:blank:]]' 'script-security 2' $fp_ovpn 'auth[[:blank:]]'
+		[[ -f $FP_SETTINGS_UP ]] && G_CONFIG_INJECT 'route-up[[:blank:]]' "route-up $FP_SETTINGS_UP" $fp_ovpn 'auth[[:blank:]]' || sed -i '/^[[:blank:]]*route-up[[:blank:]]/d' $fp_ovpn
+		[[ -f $FP_SETTINGS_DOWN ]] && G_CONFIG_INJECT 'route-pre-down[[:blank:]]' "route-pre-down $FP_SETTINGS_DOWN" $fp_ovpn 'auth[[:blank:]]' || sed -i '/^[[:blank:]]*route-pre-down[[:blank:]]/d' $fp_ovpn
 
 		cat << _EOF_ > /lib/systemd/system/dietpi-nordvpn.service
 [Unit]
@@ -157,13 +154,12 @@ _EOF_
 		do
 
 			Check_Connected && break
-
-			G_DIETPI-NOTIFY 2 "Waiting for connection ($i/$MAX_WAIT_FOR_CONNECTION)"
+			G_DIETPI-NOTIFY -2 "Waiting for connection ($i/$MAX_WAIT_FOR_CONNECTION)"
 			sleep 1
 
 		done
 
-		(( $NORDVPN_CONNECTED )) || G_WHIP_MSG "Connection failed/time out: $NORDVPN_SERVER\n\nPlease verify account details are correct.\n\nIf problems persist, please check the status of 'systemctl status dietpi-nordvpn -l'"
+		(( $NORDVPN_CONNECTED )) || G_WHIP_MSG "Connection failed/timeout: $NORDVPN_SERVER\n\nPlease verify account details are correct.\n\nIf problems persist, please check the status of \"systemctl -l status dietpi-nordvpn\""
 
 	}
 
@@ -183,34 +179,19 @@ _EOF_
 	# TARGETMENUID=0
 	Menu_Main(){
 
-		Update_Wan_Ip
-
 		local text_status="Status:\n - WAN IP: $WAN_IP\n"
-		if (( $NORDVPN_SERVICE )) && Check_Connected; then
+		if (( ! $NORDVPN_SERVICE )); then
 
-			text_status+=" - Connected : $NORDVPN_SERVER\n"
+			text_status+=' - Not configured\n - NordVPN subscription: https://go.nordvpn.net/aff_c?offer_id=15&aff_id=5305&url_id=902'
 
-			local net_rx_byte=0
-			local net_tx_byte=0
-			local net_rx_mb='N/A'
-			local net_tx_mb='N/A'
+		elif ! Check_Connected; then
 
-			if [[ -f /sys/class/net/$NET_DEV/statistics/rx_bytes && -f /sys/class/net/$NET_DEV/statistics/tx_bytes ]]; then
-
-				net_rx_byte=$(</sys/class/net/$NET_DEV/statistics/rx_bytes)
-				disable_error=1 G_CHECK_VALIDINT "$net_rx_byte" 0 && net_rx_mb="$(( $net_rx_byte / 1024 / 1024 )) MiB"
-
-				net_tx_byte=$(</sys/class/net/$NET_DEV/statistics/tx_bytes)
-				disable_error=1 G_CHECK_VALIDINT "$net_tx_byte" 0 && net_tx_mb="$(( $net_tx_byte / 1024 / 1024 )) MiB"
-
-			fi
-
-			text_status+=" - Usage     : Sent = $net_tx_mb | Recieved = $net_rx_mb"
+			text_status+=' - Disconnected\n - NordVPN subscription: https://go.nordvpn.net/aff_c?offer_id=15&aff_id=5305&url_id=902'
 
 		else
 
-			(( $NORDVPN_SERVICE )) && text_status+=' - Disconnected' || text_status+=' - Not configured'
-			text_status+='\n - NordVPN subscription: https://go.nordvpn.net/aff_c?offer_id=15&aff_id=5305&url_id=902'
+			Get_Connection_Info
+			text_status+=" - Usage     : Sent = $TX | Received = $RX"			
 
 		fi
 
@@ -243,6 +224,7 @@ _EOF_
 			if [[ $G_WHIP_RETURNED_VALUE == 'Apply' ]]; then
 
 				Save_Settings
+				Update_Wan_Ip
 
 			elif [[ $G_WHIP_RETURNED_VALUE == 'Edit Up' ]]; then
 
@@ -281,6 +263,7 @@ _EOF_
 			elif [[ $G_WHIP_RETURNED_VALUE == 'Disconnect' ]]; then
 
 				G_RUN_CMD systemctl stop dietpi-nordvpn
+				Update_Wan_Ip
 				LAST_SELECTED_NAME='Refresh'
 
 			elif [[ $G_WHIP_RETURNED_VALUE == 'Server' ]]; then
@@ -298,18 +281,20 @@ _EOF_
 
 				# - Select server
 				G_DIETPI-NOTIFY 2 'Populating NordVPN server list, please wait...'
-				cd /etc/openvpn/ovpn_$PROTOCOL
 				G_WHIP_MENU_ARRAY=()
-				for i in *.ovpn
+				for i in /etc/openvpn/ovpn_$PROTOCOL/*.ovpn
 				do
 
-					G_WHIP_MENU_ARRAY+=("$i" '')
+					G_WHIP_MENU_ARRAY+=("${i##*/}" '')
 
 				done
-				cd /tmp/$G_PROGRAM_NAME
 
 				G_WHIP_DEFAULT_ITEM=$NORDVPN_SERVER
 				G_WHIP_MENU 'Please select a NordVPN server to use:' && NORDVPN_SERVER=$G_WHIP_RETURNED_VALUE
+
+			elif [[ $G_WHIP_RETURNED_VALUE == 'Refresh' ]]; then
+
+				Update_Wan_Ip
 
 			fi
 
@@ -325,57 +310,44 @@ _EOF_
 	# Main Loop
 	#/////////////////////////////////////////////////////////////////////////////////////
 	#-----------------------------------------------------------------------------------
-	
+	Init
 	#-----------------------------------------------------------------------------------
-	if [[ $INPUT_CMD == 'status' ]]; then
+	if [[ $INPUT == 'status' ]]; then
 
-		initStatus=$(Init 'status')
-		if [[ $initStatus ]]; then
+		if (( ! $NORDVPN_INSTALLED )); then
 
-			# Not installed
-			G_DIETPI-NOTIFY 1 "$initStatus"; exit 1;
+			echo -e "\e[33m$G_PROGRAM_NAME is not installed! Please run: \"dietpi-software install 171\"\e[0m"
+
+		elif (( ! $NORDVPN_SERVICE )); then
+
+			echo -e "\e[33m$G_PROGRAM_NAME is not installed! Please run: \"dietpi-nordvpn\"\e[0m"
+
+		elif ! Check_Connected; then
+
+			echo -e '\e[1;31mDisconnected\e[0m'
 
 		else
-			# Installed; get status
-			NORDVPN_SERVICE=1
-			if (( $NORDVPN_SERVICE )) && Check_Connected; then
 
-				text_status="\e[1;32mConnected$COLOUR_RESET"
+			Get_Connection_Info
+			echo -e "\e[1;32mConnected\e[0m - Sent = $TX | Received = $RX"
 
-				net_rx_byte=0
-				net_tx_byte=0
-				net_rx_mb='N/A'
-				net_tx_mb='N/A'
-
-				if [[ -f /sys/class/net/$NET_DEV/statistics/rx_bytes && -f /sys/class/net/$NET_DEV/statistics/tx_bytes ]]; then
-
-					net_rx_byte=$(</sys/class/net/$NET_DEV/statistics/rx_bytes)
-					disable_error=1 G_CHECK_VALIDINT "$net_rx_byte" 0 && net_rx_mb="$(( $net_rx_byte / 1024 / 1024 )) MiB"
-
-					net_tx_byte=$(</sys/class/net/$NET_DEV/statistics/tx_bytes)
-					disable_error=1 G_CHECK_VALIDINT "$net_tx_byte" 0 && net_tx_mb="$(( $net_tx_byte / 1024 / 1024 )) MiB"
-
-				fi
-
-				text_status+=" - Sent = $net_tx_mb | Recieved = $net_rx_mb"
-
-			else
-
-				(( $NORDVPN_SERVICE )) && text_status+="\e[1;31mDisconnected$COLOUR_RESET" || text_status+="Not configured"
-
-			fi
-			echo -e "$text_status"
 		fi
 
-	elif [[ $INPUT_CMD ]]; then
-		
+	elif [[ $INPUT ]]; then
+
 		# Unknown input
-		G_DIETPI-NOTIFY 1 "Invalid input command ($command). Aborting...\n$USAGE"
+		echo -e "\e[90m[\e[0m\e[31mFAILURE\e[0m\e[90m]\e[0m \e[90m$G_PROGRAM_NAME | \e[0mInvalid input command ($INPUT). Aborting...\n$USAGE"
 		exit 1
 
 	else
 
-		Init
+		. /DietPi/dietpi/func/dietpi-globals
+		G_PROGRAM_NAME='DietPi-NordVPN'
+		G_CHECK_ROOT_USER
+		G_CHECK_ROOTFS_RW
+		G_INIT
+		Read_Settings
+		Update_Wan_Ip
 
 		while (( $TARGETMENUID >= 0 ))
 		do
@@ -383,6 +355,7 @@ _EOF_
 			Menu_Main
 
 		done
+
 	fi
 	#-----------------------------------------------------------------------------------
 	exit
