v7.1
+ DietPi-Arr_to_RAM | Use safer approach to create database backups: The -shm and -wal files do sometimes not exist, e.g. when the connection is closed temporarily. In theory the should never exist when the program is not running, but in practice it does at least with Sonarr and Lidarr, which obviously do not close connections gracefully or use certain SQLite flags to keep those files intentionally. However, havoc can happen when those files do not exist while the database is linked to RAM or stored back to disk: In the first case, if the program then crashes, up-to-date -shm + -wal files will be mixed with a backup database file, in the second case, the -shm and -wal symlinks will stay on disk, breaking program start as the RAM dir is removed. Especially in combination with the automatic backup restoring, mixing of old and new files can happen, corrupting the database. At least when linking to RAM and for backup creation, SQLite is used now to read and store the database to the backup location, which includes -shm and -wal, so that a single consistent database file is present for the program to start with.

diff --git a/dietpi/misc/dietpi-arr_to_RAM b/dietpi/misc/dietpi-arr_to_RAM
--- a/dietpi/misc/dietpi-arr_to_RAM
+++ b/dietpi/misc/dietpi-arr_to_RAM
@@ -61,18 +61,18 @@ Supported programs:
 	# Boot service log file
 	FP_LOG='/var/tmp/dietpi/logs/dietpi-arr_to_RAM.log'
 
-	# Program files array
-	declare -A aFILES=()
+	# Program database name array
+	declare -A aFILE=()
 	# - Sonarr
 	if [[ ${INPUT_PROG:-sonarr} == 'sonarr' ]]
 	then
 		# v3
 		if [[ -f '/mnt/dietpi_userdata/sonarr/sonarr.db' || -f '/mnt/dietpi_userdata/sonarr/sonarr.db.bak' ]]
 		then
-			aFILES[sonarr]='sonarr.db sonarr.db-shm sonarr.db-wal'
+			aFILE[sonarr]='sonarr.db'
 		# v2
 		else
-			aFILES[sonarr]='nzbdrone.db nzbdrone.db-shm nzbdrone.db-wal'
+			aFILE[sonarr]='nzbdrone.db'
 		fi
 	fi
 	# - Radarr
@@ -81,17 +81,17 @@ Supported programs:
 		# v3
 		if [[ -f '/mnt/dietpi_userdata/radarr/radarr.db' || -f '/mnt/dietpi_userdata/radarr/radarr.db.bak' ]]
 		then
-			aFILES[sonarr]='radarr.db radarr.db-shm radarr.db-wal'
+			aFILE[radarr]='radarr.db'
 		# v2
 		else
-			aFILES[sonarr]='nzbdrone.db nzbdrone.db-shm nzbdrone.db-wal'
+			aFILE[radarr]='nzbdrone.db'
 		fi
 	fi
 	# - Lidarr
-	[[ ${INPUT_PROG:-lidarr} == 'lidarr' ]] && aFILES[lidarr]='lidarr.db lidarr.db-shm lidarr.db-wal'
+	[[ ${INPUT_PROG:-lidarr} == 'lidarr' ]] && aFILE[lidarr]='lidarr.db'
 
 	# Check for valid input program
-	(( ${#aFILES[@]} )) || { error=1 Print "Invalid input program ($INPUT_PROG). Aborting...
+	(( ${#aFILE[@]} )) || { error=1 Print "Invalid input program ($INPUT_PROG). Aborting...
 $USAGE"; exit 1; }
 
 	FP_DISK=
@@ -100,11 +100,15 @@ $USAGE"; exit 1; }
 	Link_To_Ram(){
 
 		Print "Linking $FP_DISK to RAM ($FP_RAM)..."
-		mv "$FP_DISK" "${FP_DISK}.bak" || { error=$? Print "Creating backup failed for $FP_DISK. Skipping this file..."; return; }
-		ln -s "$FP_RAM" "$FP_DISK" || EXIT_CODE=$?
+		# For actual database file, create a backup first, which includes -shm and -wal, then copy that to RAM. If it fails, skip that program.
+		if [[ $FP_RAM == *'.db' ]]
+		then
+			sqlite3 "$FP_DISK" ".save ${FP_DISK}.bak" || { error=$? Print "Creating ${i^} database backup failed. Skipping this program..."; return 1; }
+			cp -a --no-preserve=timestamps "${FP_DISK}.bak" "$FP_RAM" || { error=$? Print "Copying ${i^} database to RAM failed. Skipping this program..."; return 1; }
+		fi
+		ln -sf "$FP_RAM" "$FP_DISK" || EXIT_CODE=$?
 		# chown link in case created by root but program user wants to store back to disk
 		chown -h "$i" "$FP_DISK" || EXIT_CODE=$?
-		cp -a --no-preserve=timestamps "${FP_DISK}.bak" "$FP_RAM" || EXIT_CODE=$?
 
 	}
 
@@ -112,7 +116,8 @@ $USAGE"; exit 1; }
 
 		local astart_services=()
 
-		for i in "${!aFILES[@]}"
+		# Loop through programs
+		for i in "${!aFILE[@]}"
 		do
 
 			FP_DISK="/mnt/dietpi_userdata/$i"
@@ -124,29 +129,22 @@ $USAGE"; exit 1; }
 			Print "${i^} detected"
 
 			# Create update backup script
-			if [[ ! -f $FP_RAM/dietpi-arr_to_RAM.sh ]]
+			if [[ ! -f $FP_DISK/dietpi-arr_to_RAM.sh ]]
 			then
-				Print "Creating $FP_RAM/dietpi-arr_to_RAM.sh to be used as ${i^} custom script"
-				echo -e '#!/bin/dash\n/boot/dietpi/misc/dietpi-arr_to_RAN 2 '"$i" > "$FP_RAM/dietpi-arr_to_RAM.sh" || { error=$? Print "Creating $FP_RAM/dietpi-arr_to_RAM.sh failed. Skipping this program..."; continue; }
-				chmod +x "$FP_RAM/dietpi-arr_to_RAM.sh" || { error=$? Print "Applying $FP_RAM/dietpi-arr_to_RAM.sh execute permissions failed. Skipping this program..."; continue; }
-				chown "$i:dietpi" "$FP_RAM/dietpi-arr_to_RAM.sh" || { error=$? Print "Applying $FP_RAM/dietpi-arr_to_RAM.sh ownership failed. Skipping this program..."; continue; }
+				Print "Creating $FP_DISK/dietpi-arr_to_RAM.sh to be used as ${i^} custom script"
+				echo -e '#!/bin/dash\n/boot/dietpi/misc/dietpi-arr_to_RAN 2 '"$i" > "$FP_DISK/dietpi-arr_to_RAM.sh" || { error=$? Print "Creating $FP_DISK/dietpi-arr_to_RAM.sh failed."; }
+				chmod +x "$FP_DISK/dietpi-arr_to_RAM.sh" || { error=$? Print "Applying $FP_DISK/dietpi-arr_to_RAM.sh execute permissions failed."; }
+				chown "$i:dietpi" "$FP_DISK/dietpi-arr_to_RAM.sh" || { error=$? Print "Applying $FP_DISK/dietpi-arr_to_RAM.sh ownership failed."; }
 			fi
 
 			# Update backup
 			if (( $INPUT == 2 )); then
 
-				if [[ -d $FP_RAM ]]; then
+				if [[ -f $FP_RAM/${aFILE[$i]} ]]; then
 
-					Print "Updating ${i^} database backups..."
-					for j in ${aFILES[$i]}
-					do
-
-						FP_RAM="/tmp/${i}_db_link/$j"
-						[[ -f $FP_RAM ]] || { Print "$FP_RAM not found. Skipping this file..."; continue; }
-						cp -a "$FP_RAM" "$FP_DISK/$j.bak" || EXIT_CODE=$?
-
-					done
-					Print "Updated ${i^} database backups."
+					Print "Updating ${i^} database backup..."
+					sqlite3 "$FP_RAM/${aFILE[$i]}" ".save $FP_DISK/${aFILE[$i]}.bak" || { error=$? Print "Updating ${i^} database backup failed."; continue; }
+					Print "Updated ${i^} database backup."
 
 				else
 
@@ -175,44 +173,45 @@ $USAGE"; exit 1; }
 				# - chown dir in case created by root but program user wants to store back to disk
 				chown "$i" "$FP_RAM" || EXIT_CODE=$?
 
-				for j in ${aFILES[$i]}
+				# Loop through database file, shm and wal
+				for j in "${aFILE[$i]}"{,-shm,-wal}
 				do
 
 					FP_DISK="/mnt/dietpi_userdata/$i/$j"
 					FP_RAM="/tmp/${i}_db_link/$j"
 					local fp_target=
 
-					# - Source exists and is no symlink, expected situation
+					# Source exists and is no symlink, expected situation
 					if [[ -f $FP_DISK && ! -L $FP_DISK ]]; then
 
-						Link_To_Ram
+						Link_To_Ram || continue 2
 
-					# - Link + target exists, should only happen when running the script two times in same session
+					# Link + target exists, should only happen when running the script two times in same session
 					elif [[ -L $FP_DISK ]] && fp_target=$(readlink -e "$FP_DISK"); then
 
 						if [[ $fp_target == "$FP_RAM" ]]; then
 
 							Print "$FP_DISK already linked to RAM ($FP_RAM). Skipping this file..."
 
-						# - Failsafe: Restore file from wrong symlink, should never occur but required for this script to function
+						# Failsafe: Restore file from wrong symlink, should never occur but required for this script to function
 						else
 
 							Print "$FP_DISK already linked to $fp_target. Restoring original file location before linking to RAM..."
 							rm "$FP_DISK" || { error=$? Print "Removing symlink failed ($FP_DISK). Skipping this file..."; continue; }
 							mv "$fp_target" "$FP_DISK" || { error=$? Print "Restoring original file failed ($fp_target). Skipping this file..."; continue; }
-							Link_To_Ram
+							Link_To_Ram || continue 2
 
 						fi
 
-					# - Source does not exist or is orphaned link, should only happen after crash
+					# Source does not exist or is orphaned link, should only happen after crash
 					elif [[ -f ${FP_DISK}.bak ]]; then
 
 						Print "$FP_DISK not found. Recovering from backup first (${FP_DISK}.bak)..."
-						# - Remove possible orphaned symlink
+						# Remove possible orphaned symlink
 						[[ ! -L $FP_DISK ]] || rm "$FP_DISK" || { error=$? Print "Removing orphaned symlink failed ($FP_DISK). Skipping this file..."; continue; }
-						# - Recover from backup
+						# Recover from backup
 						mv "${FP_DISK}.bak" "$FP_DISK" || { error=$? Print "Recovering file from backup failed (${FP_DISK}.bak). Skipping this file..."; continue; }
-						Link_To_Ram
+						Link_To_Ram || continue 2
 
 					else
 
@@ -230,8 +229,8 @@ $USAGE"; exit 1; }
 				if [[ -d $FP_RAM ]]; then
 
 					Print "Storing database from RAM ($FP_RAM) back to disk ($FP_DISK)..."
-					# - "-u" will only copy newer files, thus actually used by program.
-					# - "--remove-destination" will remove expected existing symlinks.
+					# "-u" will only copy newer files, thus actually used by program.
+					# "--remove-destination" will remove expected existing symlinks.
 					cp -au --remove-destination "$FP_RAM/." "$FP_DISK" || { error=$? Print "Storing ${i^} database from RAM back to disk failed."; continue; }
 					rm -R "$FP_RAM"
 					Print "Stored ${i^} database from RAM back to disk."
@@ -298,13 +297,13 @@ _EOF_
 	#/////////////////////////////////////////////////////////////////////////////////////
 	# Main Loop
 	#/////////////////////////////////////////////////////////////////////////////////////
-	# - Toggle Link to RAM
+	# Toggle Link to RAM
 	if [[ $INPUT == [012] ]]; then
 
 		Toggle_Link_To_Ram
 		(( $EXIT_CODE )) && Print '[ERROR] An issue has occurred. Please check the above output for details.'
 
-	# - Enable/Disable Link to RAM on boot
+	# Enable/Disable Link to RAM on boot
 	elif [[ $INPUT == 'enable' || $INPUT == 'disable' ]]; then
 
 		"${INPUT^}_On_Boot"
