v6.23
+ DietPi-Arr_to_RAM | Restart services to prevent possible issues when services are starting too quickly afterwards. Restart includes 100 ms sleep by default which can/should be increased by maintainer.
+ DietPi-Arr_to_RAM | Add more info output to allow better error tracking, e.g. when service (re)start hangs, leading to dietpi-arr_to_RAM.service timeout: https://github.com/MichaIng/DietPi/issues/2689#issuecomment-481107853
+ DietPi-Arr_to_RAM | Fine tuning: Be stricter on input arguments and enhance usage output

diff --git a/dietpi/misc/dietpi-arr_to_RAM b/dietpi/misc/dietpi-arr_to_RAM
--- a/dietpi/misc/dietpi-arr_to_RAM
+++ b/dietpi/misc/dietpi-arr_to_RAM
@@ -1,8 +1,7 @@
 #!/bin/bash
 {
-
 	#////////////////////////////////////
-	# DietPi Move Arr to RAM
+	# DietPi Link Arr to RAM
 	#
 	#////////////////////////////////////
 	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
@@ -10,14 +9,18 @@
 	#////////////////////////////////////
 	#
 	# Info:
-	# - Moves arr program database files to RAM (/tmp) with symlink, and, back to disk
+	# - Moves Sonarr, Radarr and Lidarr database files to RAM, leaving a symlink on disk
+	# - Reduces disk I/O and enhances database I/O performance
+	# - Creates a backup first and automatically restores from backup on next start in case of system crash
 	#
-	# Usage:
-	# - /DietPi/dietpi/misc/dietpi-arr_to_RAM 1		= Link to RAM
-	# - /DietPi/dietpi/misc/dietpi-arr_to_RAM 0		= Store to disk
-	# - /DietPi/dietpi/misc/dietpi-arr_to_RAM enable	= Enable Link to RAM on boot
-	# - /DietPi/dietpi/misc/dietpi-arr_to_RAM disable	= Disable Link to RAM on boot
-	#////////////////////////////////////
+	USAGE='
+Usage: /DietPi/dietpi/misc/dietpi-arr_to_RAM <command>
+Available commands:
+  1		Link to RAM
+  0		Store to disk
+  enable	Enable Link to RAM on boot
+  disable	Disable Link to RAM on boot
+'	#////////////////////////////////////
 
 	# Import DietPi-Globals --------------------------------------------------------------
 	#. /DietPi/dietpi/func/dietpi-globals	# Skip globals for faster execution on early boot stage
@@ -37,10 +40,10 @@
 	}
 
 	# Check for required root permissions
-	(( $UID )) && { error=1 Print "This script must run with root privileges. Please use: \"sudo\""; exit 1; }
+	(( $UID )) && { error=1 Print 'This script must run with root privileges. Please use: "sudo"'; exit 1; }
 
 	# Grab input
-	[[ $1 ]] && INPUT=$1
+	INPUT=$@
 
 	EXIT_CODE=0
 
@@ -93,7 +96,7 @@
 			# Link to RAM + backup
 			if (( $INPUT == 1 )); then
 
-				Print 'Linking files to RAM...'
+				Print "Linking ${i^} files to RAM..."
 
 				# - Pre-create RAM dir
 				[[ -d $FP_RAM ]] || mkdir -p $FP_RAM || { error=$? Print "Pre-creating RAM directory for ${^i} failed ($FP_RAM). Skipping this program..."; continue; }
@@ -148,8 +151,15 @@
 				# - Failsafe: chown fully to program run user since nothing else ever needs or should access these databases directly
 				chown -R ${i}:${i} /tmp/${i}_db_link
 
+				Print "Linked ${i^} files to RAM."
+
 				# - Restart program if we stopped it before
-				(( $handle_service )) && systemctl start $i
+				if (( $handle_service )); then
+
+					Print "Restarting ${i^} service..."
+					systemctl restart $i
+
+				fi
 
 			# Store to disk
 			elif (( $INPUT == 0 )); then
@@ -174,6 +184,8 @@
 				chown -R ${i}:${i} $FP_DISK
 				# - Failsafe: Sync to disk now
 				sync
+
+				Print "Restored ${^i} files from RAM to disk."
 
 			fi
 
@@ -225,25 +237,26 @@ _EOF_
 	if [[ $INPUT == [01] ]]; then
 
 		Toggle_Link_To_Ram
+		(( $EXIT_CODE )) && error=$EXIT_CODE Print 'An issue has occurred. Please check the above output for details.'
 
 	# - Enable Link to RAM on boot
-	elif [[ ${INPUT,,} == 'enable' ]]; then
+	elif [[ $INPUT == 'enable' ]]; then
 
 		Enable_On_Boot
+		(( $EXIT_CODE )) && error=$EXIT_CODE Print "An issue has occurred. Please check the log for details: $FP_LOG"
 
 	# - Disable Link to RAM on boot
-	elif [[ ${INPUT,,} == 'disable' ]]; then
+	elif [[ $INPUT == 'disable' ]]; then
 
 		Disable_On_Boot
+		(( $EXIT_CODE )) && error=$EXIT_CODE Print "An issue has occurred. Please check the log for details: $FP_LOG"
 
 	else
 
-		error=1 Print "Unknown input argument: $INPUT. Aborting..."
-		exit 1
+		error=1 Print "Invalid input argument: ${INPUT:-<none>}. Aborting...
+$USAGE"
 
 	fi
-
-	(( $EXIT_CODE )) && error=$EXIT_CODE Print "An issue has occurred. Please check the log for details: $FP_LOG"
 
 	#-----------------------------------------------------------------------------------
 	exit $EXIT_CODE
