v6.23
+ DietPi-Arr_to_RAM | Reverting https://github.com/MichaIng/DietPi/commit/54faaaac606dbc6d0c25af2e962cf3f5d93676d6 for now. Investigate on DietPi-Postboot level why Sonarr/Radarr/Lidarr fail to start.
+ DietPi-Arr_to_RAM | Use systemd unit Type=oneshot which fits better here and matches the intentions of how these are used, since there is simply no process running after ExecStart has finished: https://www.freedesktop.org/software/systemd/man/systemd.service.html#Examples

diff --git a/dietpi/misc/dietpi-arr_to_RAM b/dietpi/misc/dietpi-arr_to_RAM
--- a/dietpi/misc/dietpi-arr_to_RAM
+++ b/dietpi/misc/dietpi-arr_to_RAM
@@ -99,7 +99,6 @@ $USAGE"; exit 1; }
 			[[ -d $FP_DISK ]] || continue
 
 			Print "${i^} detected"
-			start_services+=" $i"
 
 			# Update backup
 			if (( $INPUT == 2 )); then
@@ -126,8 +125,14 @@ $USAGE"; exit 1; }
 
 			fi
 
-			Print "Stopping ${i^} service..."
-			systemctl stop $i || { error=$? Print "Stopping ${i^} service failed. Skipping this program..."; continue; }
+			# If active, stop program before handling database and restart afterwards
+			if pgrep -f $i &> /dev/null; then
+
+				Print "Stopping ${i^} service..."
+				start_services+=" $i"
+				systemctl stop $i || { error=$? Print "Stopping ${i^} service failed. Skipping this program..."; continue; }
+
+			fi
 
 			# Link to RAM + backup
 			if (( $INPUT == 1 )); then
@@ -234,9 +239,9 @@ After=dietpi-ramdisk.service tmp.mount
 Before=dietpi-preboot.service sonarr.service radarr.service lidarr.service
 
 [Service]
-Type=forking
+Type=oneshot
 RemainAfterExit=yes
-ExecStart=/bin/dash -c '/DietPi/dietpi/misc/dietpi-arr_to_RAM 1 2>&1 >> $FP_LOG'
+ExecStart=-/bin/dash -c '/DietPi/dietpi/misc/dietpi-arr_to_RAM 1 2>&1 >> $FP_LOG'
 ExecStop=/bin/dash -c '/DietPi/dietpi/misc/dietpi-arr_to_RAM 0 2>&1 > $FP_LOG'
 
 [Install]
