dietpi-servarr-to-ram: another malicious symlink protection
and assure that old service is removed on DietPi update, even if it was disabled via systemctl instead of "dietpi-arr_to_RAM disable".

diff --git a/dietpi/misc/dietpi-servarr_to_ram b/dietpi/misc/dietpi-servarr_to_ram
--- a/dietpi/misc/dietpi-servarr_to_ram
+++ b/dietpi/misc/dietpi-servarr_to_ram
@@ -141,6 +141,12 @@ $USAGE"; exit 1; }
 			Print "${i^} detected"
 
 			# Create update backup script
+			# - Remove script if it is a symlink, for security reasons
+			if [[ -L $FP_DISK/dietpi-servarr_to_ram.sh ]]
+			then
+				Print "Removing $FP_DISK/dietpi-servarr_to_ram.sh for security reasons, since it is a symlink..."
+				rm "$FP_DISK/dietpi-servarr_to_ram.sh" || { error=$? Print "Removing $FP_DISK/dietpi-servarr_to_ram.sh failed. Skipping this program..."; continue; }
+			fi
 			if [[ ! -f $FP_DISK/dietpi-servarr_to_ram.sh ]]
 			then
 				Print "Creating $FP_DISK/dietpi-servarr_to_ram.sh to be used as ${i^} custom script"
