v9.4
- CI | Armbian: Add own version suffix for packages

diff --git a/.github/workflows/armbian.yml b/.github/workflows/armbian.yml
--- a/.github/workflows/armbian.yml
+++ b/.github/workflows/armbian.yml
@@ -65,6 +65,31 @@ jobs:
             git fetch origin main
             git rebase origin/main
         fi
+    - name: Obtain version suffix
+      run: |
+        cd build
+        read -r version < VERSION
+        case '${{ github.event.inputs.asset }}' in
+            firmware) package='armbian-firmware';;
+            uboot) package='linux-uboot-${{ github.event.inputs.board }}-${{ github.event.inputs.board }}';;
+            kernel)
+                family=$(. 'config/boards/${{ github.event.inputs.board }}.'* &> /dev/null; echo "$BOARDFAMILY")
+                echo "Board family is:             $family"
+                family=$(BRANCH='${{ github.event.inputs.branch }}'; . "config/sources/families/$family.conf" &> /dev/null; echo "$LINUXFAMILY")
+                echo "Linux family is:             $family"
+                package="linux-image-${{ github.event.inputs.branch }}-$family"
+            ;;
+            *) echo 'ERROR: Invalid asset "${{ github.event.inputs.asset }}"'; exit 1;;
+        esac
+        curl -fO "https://dietpi.com/downloads/binaries/$package.deb"
+        cur_version=$(dpkg-deb -f "$package.deb" Version)
+        rm "$package.deb"
+        cur_suffix=${cur_version#*-dietpi}
+        echo "Current package version is:  $cur_version"
+        echo "New Armbian version is:      $version"
+        [ "$version-dietpi$cur_suffix" = "$cur_version" ] && version="$version-dietpi$((cur_suffix+1))" || version="$version-dietpi1"
+        echo "New package version will be: $version"
+        echo "version" > VERSION
     - name: Build asset
       run: |
         cd build
